### ISSUE TITLE
MonoHttpClientChannel subscribes to Mono with a null subscriber

### ISSUE THREAD

**Issue by bclozel** [reactor/reactor-netty#1]
According to [this line](https://github.com/reactor/reactor-netty/blob/53ef5c2749942e403aeb6023c401f9e4a9140303/src/main/java/reactor/ipc/netty/http/MonoHttpClientChannel.java#L122), `MonoHttpClientChannel` subscribes to a `Mono` using a null subscriber, which is now forbidden by this [reactor-core commit](https://github.com/reactor/reactor-core/commit/7f9d8588ee60d4b9aebf462e20fd4aa88e00240e#diff-d1cd10e1a53ba4b94822fe16b8d40914R2262)

**Comment by smaldini** [comment]
Fixed in the next core snapshot
