### ISSUE TITLE
In Connection Provider Document, Different Fields Has Same Description (DEFAULT_POOL_MAX_CONNECTIONS and DEFAULT_POOL_ACQUIRE_TIMEOUT)

### ISSUE THREAD

**Issue by limited107** [reactor/reactor-netty#1002]
## Expected Behavior

I wonder two different fields has same description.
https://projectreactor.io/docs/netty/release/api/reactor/netty/resources/ConnectionProvider.html

They have same description as below.
if -1 will never wait to acquire before opening a new connection in an unbounded fashion.

## Actual Behavior

DEFAULT_POOL_MAX_CONNECTIONS
```
static final int DEFAULT_POOL_MAX_CONNECTIONS
Default max connections, if -1 will never wait to acquire before opening a new connection in an unbounded fashion. Fallback to available number of processors (but with a minimum value of 16)
```

DEFAULT_POOL_ACQUIRE_TIMEOUT
```
static final long DEFAULT_POOL_ACQUIRE_TIMEOUT
Default acquisition timeout (milliseconds) before error. If -1 will never wait to acquire before opening a new connection in an unbounded fashion. Fallback 45 seconds
```
## Steps to Reproduce

```java
@Test
public void repoCase() {

}
```

## Your Environment

* Reactor version(s) used:
* Other relevant libraries versions (eg. `netty`, ...):
* JVM version (`javar -version`):
* OS and version (eg `uname -a`):

**Comment by violetagg** [comment]
@limited107 Thanks for the report. I fixed `ConnectionProvider#DEFAULT_POOL_MAX_CONNECTIONS` javadoc
https://projectreactor.io/docs/netty/snapshot/api/reactor/netty/resources/ConnectionProvider.html#DEFAULT_POOL_MAX_CONNECTIONS
