### ISSUE TITLE
How to route outgoing traffic to proxy server in netty

### ISSUE THREAD

**Issue by wunaidage** [reactor/reactor-netty#1004]
Hi, I have a hoverfly running on my local as proxy server. I want to route all my outgoing traffic to the hoverfly server. I have been trying java vm arguments and system properties until I read about System.setProperty or java vm arguments is not working for netty so I tried the solution provided in https://github.com/reactor/reactor-netty/issues/887#issuecomment-549439355 
I modified the webclient creation code. however, there's still no traffic captured by hoverfly. 
I'm using spring boot 2 + webflux + netty
All my application's outgoing traffic is HTTPS and it is not there in ProxyProvider enum. does it mean https traffic will be direct connect?
So I changed one endpoint to http://www.example.com, but still nothing captured by hoverfly.
this is my hoverfly status
+------------+----------+
| Hoverfly   | running  |
| Admin port |     8888 |
| Proxy port |     8500 |
| Proxy type | forward  |
| Mode       | capture  |
| Middleware | disabled |
| CORS       | disabled |
+------------+----------+

```
HttpClient httpClient = HttpClient.create(connectionProvider)
                .keepAlive(webClientProperties.isSocketKeepAlive())
                .tcpConfiguration(client -> {
                    client.proxy(proxy -> proxy.type(ProxyProvider.Proxy.HTTP).host("localhost").port(8500));
                    ......
                  })
```

Could somebody help?

**Comment by violetagg** [comment]
Use [Gitter](https://gitter.im/reactor/reactor-netty) or [stackoverflow.com](https://stackoverflow.com/questions/tagged/reactor-netty) for questions.

We do have tests with Hoverfly so check your setup
https://github.com/reactor/reactor-netty/blob/master/src/test/java/reactor/netty/http/client/HttpClientProxyTest.java

**Comment by dineshbhagat** [comment]
> Use [Gitter](https://gitter.im/reactor/reactor-netty) or [stackoverflow.com](https://stackoverflow.com/questions/tagged/reactor-netty) for questions.
> 
> We do have tests with Hoverfly so check your setup
> https://github.com/reactor/reactor-netty/blob/master/src/test/java/reactor/netty/http/client/HttpClientProxyTest.java

Updated url: https://github.com/reactor/reactor-netty/blob/master/reactor-netty-http/src/test/java/reactor/netty/http/client/HttpClientProxyTest.java
