### ISSUE TITLE
HTTP server should turn error signals to 500 response

### ISSUE THREAD

**Issue by rstoyanchev** [reactor/reactor-netty#101]
We've known about this for a very long time and have a [TODO in our tests](https://github.com/spring-projects/spring-framework/blob/c59e192b0f448ff15ca2bc22229b1d49d612ce72/spring-web/src/test/java/org/springframework/http/server/reactive/ErrorHandlerIntegrationTests.java#L49). 

We forgot about it because we generally handle all error signals resulting from request handling but if the error occurs very early it [leads to hanging](https://jira.spring.io/browse/SPR-15560). 

We will patch this one on our end because a UriSyntaxException can be turned to a 400 but I'm reporting it here since it should also be fixed in reactor-netty.

**Comment by rstoyanchev** [comment]
One extra note here. Following the resolution of [SPR-16051](https://jira.spring.io/browse/SPR-16051) we now allow (unhandled) error signals to flow to Reactor Netty and we do expect them to be turned into a 500, if the response is not yet committed, or the connection is closed otherwise. 

If necessary we can do the setting of the response to 500, if not yet committed, but at the moment we're simply letting the error signals propagate and hence expect this ticket to be resolved.

**Comment by violetagg** [comment]
@rstoyanchev I believe we do that 
https://github.com/reactor/reactor-netty/blob/12522fff9aacabc7aabadb7c0ed156aa542e6bcc/reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerOperations.java#L685-L693
