### ISSUE TITLE
Netty metrics OutOfMemoryError

### ISSUE THREAD

**Issue by deci260** [reactor/reactor-netty#1010]
Using reactor-netty metrics causes a java OutOfMemory error when dealing with multiple requests at the same time.
I'm assuming it's a metrics issue because when disabling netty metrics it works fine.

## Steps to Reproduce (using spring-boot-starter-reactor-netty)

- Activate reactor-netty metrics:
```java
@Bean 
public NettyWebServerFactoryCustomizer customizer(Environment environment, ServerProperties serverProperties) {
	return new NettyWebServerFactoryCustomizer(environment, serverProperties) {
		@Override
		public void customize(NettyReactiveWebServerFactory factory) {
			factory.addServerCustomizers(httpServer -> httpServer.metrics(true));
		}
	};
}
```

- Perform multiple requests at the same time (In my tests I wrote a python script with 10 threads, each one of them performs infinite gets on netty).

## Your Environment

I'm using spring cloud gateway 2.2.2.BUILD-SNAPSHOT and spring cloud dependencies Hoxton.BUILD-SNAPSHOT with other metrics enabled. 

* Reactor version(s) used: 0.9.4.RELEASE
* Netty version: 4.1.45.Final
* JVM version: 1.8.0_191 
* OS and version: Windows 10 Insider Preview (10.0.19564 Build 19564)

This happens only when netty metrics are enabled, spring cloud gateway metrics or jvm metrics provided by spring do not cause this.

**Comment by violetagg** [comment]
@deci260 Can you give us more information - how is configured Spring Gateway, do you have a lot of URLs or just simultaneous requests to one and the same URL? Can you give us reproducible example?

**Comment by deci260** [comment]
@violetagg Spring cloud gateway is configured to use different static routes and uses discovery locator. It is also configured to generate custom tags, which has caused no problem as of now. I first found out about this issue in-browser, while on a page that uses spring cloud gateway to load different resources (all requests are routed to the same route). I've also been able to reproduce it by doing simultaneous requests to the same url over and over again. Unfortunately I haven't been able to reproduce the issue at home and I cannot give you the project on which this happens, but I'll be able to give you some more info tomorrow.

**Comment by deci260** [comment]
After further analysis,  might not be a problem on your side. I am able to reproduce this issue when a certain number of tags are used. I also get this warning from reactor before the application starts dying:
```[reactor-http-epoll-5] WARN  r.n.h.MicrometerHttpMetricsRecorder$MaxUriTagsMeterFilter - Reached the maximum number of URI tags for meter name prefix [reactor.netty.http.server].```

**Comment by deci260** [comment]
A reason for this error could be that netty creates a new uri tag for every new uri that is hit by a request instead of using a uri template. Here's why this could be a problem:
https://github.com/micrometer-metrics/micrometer/issues/458#issuecomment-367482930

**Comment by violetagg** [comment]
@deci260 thanks a lot

**Comment by cdmatta** [comment]
The root cause for the memory leak is the following

There is an internal map used for collecting the micrometer meters.

MicrometerHttpMetricsRecorder.java
```java
protected final ConcurrentMap<MeterKey, Timer> dataReceivedTimeCache = PlatformDependent.newConcurrentHashMap();
```

MicrometerHttpClientMetricsRecorder.java
```java
@Override
public void recordDataReceivedTime(SocketAddress remoteAddress, String uri, String method, String status, Duration time) {
	String address = Metrics.formatSocketAddress(remoteAddress);
	Timer dataReceivedTime = dataReceivedTimeCache.computeIfAbsent(new MeterKey(uri, address, method, status),
			key -> dataReceivedTimeBuilder.tags(REMOTE_ADDRESS, address, URI, uri, METHOD, method, STATUS, status)
										  .register(REGISTRY));
	dataReceivedTime.record(time);
}
```

The uri value used to create the MeterKey is NOT templated. Meaning for each different value used in a URI (path param for ex), the keys in the Map will continue to grow thereby resulting in OOM.

The real fix here is either to completely drop the URI from MeterKey or use templated one. Personally, since these are tcp level metrics, I would prefer not having the uri in there.

**Comment by bclozel** [comment]
FYI Spring Boot is already tagging URL templates at the `WebClient` level (see [here](https://github.com/spring-projects/spring-boot/blob/fd05bc2a4a684504dd4ac6edbc96f622d5bad7fc/spring-boot-project/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/metrics/web/reactive/client/MetricsWebClientFilterFunction.java) and [here](https://github.com/spring-projects/spring-boot/blob/fd05bc2a4a684504dd4ac6edbc96f622d5bad7fc/spring-boot-project/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/metrics/web/reactive/client/WebClientExchangeTags.java#L68-L71)).
Tagging URLs will always lead to cardinality explosion, so I'd be in favor of dropping the URI tag altogether. Maybe keeping the domain could be useful, but even then that information could be provided by `WebClient` with the URL, and the important bit is already here with the remote address.

**Comment by violetagg** [comment]
@bclozel Reactor Netty is not always used in Spring Framework context. Thanks for the pointers in WebClient.

**Comment by violetagg** [comment]
We are going to address this issue with two fixes:
1. PR #1067 - `NoopMeter` is returned as a result when there is `MeterFilter.maximumAllowableTags` configuration on the system and the action `onMaxReached` is `DENY`. Having this filter and not caching `NoopMeter` will prevent OOM.
2. PR #1066 - a new API is added so that when enabling metrics on the server/client, a function for transforming the actual uri to a templated can be provided. With this approach the end user may return not just `templated` uri but may apply some other logic. Also with this approach there is no need of integration with Spring Framework.

**Comment by ukayani** [comment]
Thanks for the changes @violetagg 
Function to transform the uri is a good solution.

**Comment by steven-sheehy** [comment]
There is still a cardinality explosion here since REMOTE_ADDRESS varies for nearly every request, especially since it includes random client port with IP. In my opinion, it should be removed. I can open another issue.

**Comment by violetagg** [comment]
@steven-sheehy yes please open an issue, it is interesting what happens with the connection pooling in such situation.

**Comment by steven-sheehy** [comment]
@violetagg It's on the server when receiving requests.

**Comment by steven-sheehy** [comment]
Created issue https://github.com/reactor/reactor-netty/issues/1075 for this
