### ISSUE TITLE
WebClient Connections stuck in `active` state after PrematureCloseException: Connection prematurely closed BEFORE response

### ISSUE THREAD

**Issue by plxz** [reactor/reactor-netty#1012]
## Expected Behavior
after exchange all connections should be released to pool always - even if server is misbehaving
## Actual Behavior
we observe connections stuck in `active` state long after exchange ended

## Steps to Reproduce
Faulty connections correspond to following log entries:

```
12:34:11.073 [reactor-http-epoll-1] WARN  reactor.netty.http.client.HttpClientConnect - [id: 0x6c97fa4a, L:/127.0.0.1:56062 ! R:localhost/127.0.0.1:8765] The connection observed an error
reactor.netty.http.client.PrematureCloseException: Connection prematurely closed BEFORE response
```

Each such case seem to happen after `response_incomplete`
`12:34:11.069 [reactor-http-epoll-1] DEBUG reactor.netty.resources.PooledConnectionProvider - [id: 0x6c97fa4a, L:/127.0.0.1:56062 ! R:localhost/127.0.0.1:8765] onStateChange(POST{uri=/, connection=PooledConnection{channel=[id: 0x6c97fa4a, L:/127.0.0.1:56062 ! R:localhost/127.0.0.1:8765]}}, [response_incomplete])`
and 2 successive `READ COMPLETE` entries (see attached log for details).
```
12:34:10.968 [reactor-http-epoll-1] DEBUG reactor.netty.http.client.HttpClient - [id: 0x6c97fa4a, L:/127.0.0.1:56062 - R:localhost/127.0.0.1:8765] READ COMPLETE
12:34:10.969 [reactor-http-epoll-1] DEBUG reactor.netty.http.client.HttpClient - [id: 0x6c97fa4a, L:/127.0.0.1:56062 - R:localhost/127.0.0.1:8765] READ COMPLETE
```

That results in some number of connections retaining 'active' state even though they are not being used (or usable!) anymore - effectively 'leaking'.
Issue can be observed when using `PooledConnectionProvider` - such connections pile up until `maxConnections`is reached. Then any new request fails after `acquireTimeout` - effectively blocking the connection to destination.

This happens in real world when sending requests to one of our partners. To reproduce the issue in local env I hacked netty-disruptor and mischievous-server projects.
Steps to reproduce:
- clone from git@github.com:plxz/reproduce-netty-disruptor.git (source: https://github.com/plxz/reproduce-netty-disruptor)
- in new shell `cd mischievous-server && ./gradlew bootRun`
- in new shell `cd netty-disruptor && ./gradlew bootRun`
- `curl -v localhost:8123/req/8` - small amounts of requests work fine, exec `curl -s  http://localhost:8123/actuator/prometheus | grep reactor_netty_connection_provider_disruptorFixedConnectionPool_active_connections` to see all connections are released
- now hit it with bigger amount: `curl -v localhost:8123/req/900`
- `curl -s  http://localhost:8123/actuator/prometheus | grep reactor_netty_connection_provider_disruptorFixedConnectionPool_active_connections` now will show some number of 'active' (unusable really)  connections
- when number of stuck connections reaches 100 (limit of `ConnectionProvider` `maxConnections`) any further attempt to destination fails

## Environment
* Reactor version(s) used:
`io.projectreactor:reactor-core:3.3.2.RELEASE`
* Other relevant libraries versions:
`io.projectreactor.netty:reactor-netty:0.9.4.RELEASE`
* JVM version:
```
openjdk version "11.0.3" 2019-04-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.3+7)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.3+7, mixed mode)
```

```
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_212-b03)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.212-b03, mixed mode)
```

* OS and version (eg `uname -a`):
`Linux pl-black 4.15.0-74-generic #84-Ubuntu SMP Thu Dec 19 08:06:28 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by plxz** [comment]
[disruptor.log](https://github.com/reactor/reactor-netty/files/4236330/disruptor.log)
[disruptorlog-grepped-for-0x6c97fa4a.log](https://github.com/reactor/reactor-netty/files/4236331/disruptorlog-grepped-for-0x6c97fa4a.log)

**Comment by t1mek1ller** [comment]
Also encountered this problem,  this connections seemed to be leaking. The permit was not returned to pool, then every new request throwed `PoolAcquireTimeoutException`. The stack trace is as follows:

**Comment by martinkrc** [comment]
Hi, is there any known work-around? What is the impact in case of elastic pools?

**Comment by t1mek1ller** [comment]
I think I have found the cause for this bug. The `PooledConnection`  does not release the tcp connection when the connection observe a `HttpClientState.RESPONSE_INCOMPLETE` state. 

`HttpClientState.RESPONSE_INCOMPLETE`  is listened separately in `HttpClientOperations.onInboundClose `
```
protected void onInboundClose() {
	if (isInboundCancelled() || isInboundDisposed()) {
		listener().onStateChange(this, ConnectionObserver.State.DISCONNECTING);
		return;
	}
	// listened separately
	listener().onStateChange(this, HttpClientState.RESPONSE_INCOMPLETE);
	if (responseState == null) {
		if (markSentBody()) {
			listener().onUncaughtException(this, new PrematureCloseException("Connection has been closed BEFORE response, while sending request body"));
		}
		else {
			listener().onUncaughtException(this, new PrematureCloseException("Connection prematurely closed BEFORE response"));
		}
		return;
	}
	super.onInboundError(new PrematureCloseException("Connection prematurely closed DURING response"));
}
```

But the `PooledConnection` does not  release the underlying tcp connection  when state is not `DISCONNECTING`,  this method implementation is as follows:


```
public void onStateChange(Connection connection, State newState) {
	if(log.isDebugEnabled()) {
		log.debug(format(connection.channel(), "onStateChange({}, {})"), connection, newState);
	}

	if (newState == State.DISCONNECTING) {

		if (log.isDebugEnabled()) {
			log.debug(format(connection.channel(), "Releasing channel"));
		}

		ConnectionObserver obs = channel.attr(OWNER)
				.getAndSet(ConnectionObserver.emptyListener());

		if (pooledRef == null) {
			return;
		}

                // release the underlying tcp connection only the newState is State.DISCONNECTING
		pooledRef.release()
		         .subscribe(
		                ......);
		return;
	}

	......
}
```

So, when use FIX connection pool, when granted permit reach the max configuration, new request can not borrow a connection from this pool any more and will throw a `PoolAcquireTimeoutException`.

**Comment by violetagg** [comment]
@t1mek1ller `onInboundClose()` is invoked when the channel becomes inactive, at that point the channel is closed. We have a hook that will invalidate the channel from the pool.
https://github.com/reactor/reactor-netty/blob/v0.9.5.RELEASE/src/main/java/reactor/netty/resources/PooledConnectionProvider.java#L570
When you see `Connection prematurely....` exception can you correlate all logs using the channel id so that we can see all events related to that channel?
 For example the channel id bellow is `id: 0x1ccd4b74`:

```
2020-02-26 09:49:27.148  WARN 15489 --- [ctor-http-nio-5] r.netty.http.client.HttpClientConnect    : [id: 0x1ccd4b74, L:/127.0.0.1:56729 ! R:localhost/127.0.0.1:56716] The connection observed an error
```

**Comment by violetagg** [comment]
@plxz @t1mek1ller @martinkrc Do you think you can build Reactor Netty with the patch below and test?

```
diff --git a/src/main/java/reactor/netty/resources/PooledConnectionProvider.java b/src/main/java/reactor/netty/reso
urces/PooledConnectionProvider.java
index 658eee7b..27f8d436 100644
--- a/src/main/java/reactor/netty/resources/PooledConnectionProvider.java
+++ b/src/main/java/reactor/netty/resources/PooledConnectionProvider.java
@@ -569,7 +569,7 @@ final class PooledConnectionProvider implements ConnectionProvider {
                        }
                        channel.closeFuture()
                               .addListener(ff ->
-                                  pooledRef.invalidate()
+                                  pooledRef.release()
                                            .subscribe(null, null, () -> {
                                                if (log.isDebugEnabled()) {
                                                    log.debug(format(channel, "Channel closed, now {} active connec
tions and " +
```

@simonbasle When I switch from `pooledRef.invalidate` to `pooledRef.release ` I do not see the issue. I'm testing the provided reproducible example on Ubuntu.

**Comment by plxz** [comment]
> When you see `Connection prematurely....` exception can you correlate all logs using the channel id so that we can see all events related to that channel?

That's precisely what `disruptorlog-grepped-for-0x6c97fa4a.log` is, see my first comment with attachements.


@violetagg I just tested it basing your proposed change on 
```
commit a04f459b3cc712a1e82e7a49458d3f7d37deefdc (HEAD -> 0.9.4, origin/0.9.4)
[artifactory-release] Next development version 0.9.5.BUILD-SNAPSHOT
```

I was still able to reproduce issue. Logs seem to tell the same story.

**Comment by t1mek1ller** [comment]
> onInboundClose() is invoked when the channel becomes inactive, at that point the channel is closed. We have a hook that will invalidate the channel from the pool.

@violetagg After adding some logs and trying many tests（OMG！A long story..）, I found the hook you mentioned did not take effect because it held an old `PooledRef<PooledConnection>`. 

When the `PooledRef<PooledConnection>` is released ,  it will create a new `PooledRef<PooledConnection>` instance and return it to the pool.  Although the hook is invoked after the underlying channel is closed, `poolRef.invalidate(`) will return immediately because the `poolRef` here is an old one and has been released before(see `AbstractPooledRef.markAcquired`). Thus, the new `PooledRef<PooledConnection>` has no chance to be released or be invalidated and the connection pool will run out.

The possible fix is no matter what `ConnectionObserver.State` is generated when channel is inactive, the `PooledRef<PooledConnection>` should be released  in a unified way,  then the hook is no longer needed in such case.

**Comment by violetagg** [comment]
@t1mek1ller thanks a lot for analysis. Can you try this PR #1017

**Comment by violetagg** [comment]
the fix is in 0.9.6.BUILD-SNAPSHOT if you can test it

**Comment by plxz** [comment]
Tested it with 0.9.6.BUILD-SNAPSHOT and seems to work fine. Thanks!

**Comment by rdp** [comment]
For followers seems to have also caused this on our azure sdk:

```
      [2021-03-27 20:20:14,584][parallel-40] Operators ERROR - Operator called default onErrorDropped
      reactor.netty.internal.shaded.reactoqr.pool.PoolAcquireTimeoutException: Pool#acquire(Duration) has been pending for more than the configured timeout of 45000ms
 
      [2021-03-27 20:20:14,591][parallel-35] Schedulers ERROR - Scheduler worker in group main failed with an uncaught exception
      reactor.netty.internal.shaded.reactor.pool.PoolAcquireTimeoutException: Pool#acquire(Duration) has been pending for more than the configured timeout of 45000ms

      [2021-03-29 15:17:17,222][reactor-http-nio-31] HttpClientConnect WARN  - [id: 0x336126a2, L:0.0.0.0/0.0.0.0:53320 ! R:fhdpsprodst.blob.core.windows.net/52.239.169.100:443]
      The connection observed an error reactor.netty.http.client.PrematureCloseException: Connection has been closed BEFORE response, while sending request body
```
Upgrade seemed to fix it.
