### ISSUE TITLE
Support Graceful Shutdown

### ISSUE THREAD

**Issue by violetagg** [reactor/reactor-netty#1022]
The current solution is

Stoping the `ServerSocketChannel` so that no more connections are accepted

```
DisposableServer#disposeNow()
```

Disposing the `LoopResources` with a delay in order to close the current active connections.

```
HttpResources.disposeLoopsAndConnectionsLater(quietPeriod, timeout)
    .delaySubscription(Duration.ofSeconds(20)) --> this delay is just an example
    .block();
```

or 

```
LoopResources.disposeLater(quietPeriod, timeout)
    .delaySubscription(Duration.ofSeconds(20)) --> this delay is just an example
    .block();
```

We need a solution to be able to dispose the `LoopResources` as soon as there is no active connections instead of waiting a fixed time.

**Comment by violetagg** [comment]
@rstoyanchev @wilkinsona PTAL #1034 
What do you think about this approach?

**Comment by deepak-auto** [comment]
Hello @violetagg, 

I am following up on your comment on this [StackOverflow question](https://stackoverflow.com/questions/60746294/how-to-handle-reactor-netty-terminating-a-request-in-spring-webflux?noredirect=1#comment107489187_60746294). It seems like this issue tackles graceful shutdown of the `reactor-netty` server. However, the feature I am looking for is graceful shutdown of a request cancelled by a client (while the server is running and processing other requests.) What we are seeing is when a client cancels an in-flight request, the server simply stops processing. We would ideally like to capture the cancellation signal and perform some cleanup. 

Could you let me know if it fixes the problem I am facing as well? If so, how could we capture the said cancellation signal?

Thank you!

**Comment by violetagg** [comment]
@deepak-auto let's use [Gitter](https://gitter.im/reactor/reactor-netty) to this in order to not hijack this issue.

**Comment by wilkinsona** [comment]
This looks good to me, @violetagg. Thank you.
