### ISSUE TITLE
Provide HttpClientResponse.request() api

### ISSUE THREAD

**Issue by adriancole** [reactor/reactor-netty#1031]
Let's add an api that makes it easy to tell which request of caused the current response.

## Motivation
On implicit retry and redirect, which request caused the response could be somewhat unclear. Also, some code the user is unaware of could have modified the request. In tracing, it is helpful to know the exact request line and properties a response hook received. This is not just useful at reactor-netty tier, but also for clarifying abstractions above, such as WebClient

## Desired solution
Provide HttpClientResponse.request() api

## Considered alternatives
The best current alternative is to map the cherry-picked properties available on `HttpClientResponse`, such as method, to a fake request object. However, this lacks certain properties, unless I'm mistaken, such as the request headers.

Another alternative is to add an atomic reference to the reactor context to track this. However, it is expensive and also doesn't guarantee what you've tracked was definitely the same object as what caused the request (due to immutability), iiuc.

## Additional context
https://github.com/openzipkin/brave/blob/master/instrumentation/http/src/main/java/brave/http/HttpResponse.java#L40

**Comment by adriancole** [comment]
FYI right now, we rely on implementation detail that the response is also the request. it may still be nicer to provide a casting getter of the request type.

**Comment by violetagg** [comment]
@adriancole I'm looking at this one. I think that the only methods that are interesting are 
reactor.netty.http.client.HttpClientRequest#isFollowRedirect
reactor.netty.http.client.HttpClientRequest#requestHeaders
https://projectreactor.io/docs/netty/release/api/reactor/netty/http/client/HttpClientRequest.html

So instead of exposing the request we can expose only these two methods.

@rstoyanchev @simonbasle @smaldini Wdyt?

**Comment by adriancole** [comment]
let's say if you have a redirect and its requestline changes from POST to GET and a different path. i that's readable sounds good however achieved.

**Comment by violetagg** [comment]
@adriancole We do not change the method when redirecting, we already have 
https://projectreactor.io/docs/netty/release/api/reactor/netty/http/client/HttpClientInfos.html#resourceUrl--
https://projectreactor.io/docs/netty/release/api/reactor/netty/http/client/HttpClientInfos.html#redirectedFrom--

**Comment by adriancole** [comment]
ok cool. I know some clients can change whole requestline on redirect, good to know this doesn't

**Comment by simonbasle** [comment]
so in a nutshell, adding `HttpClientResponse#isRequestRedirected` and `HttpClientResponse#getRequestHeaders` ?

Note I'm using `getRequest` as a prefix for the headers, unlike the other accessors right now. I feel this one is the only one that only makes sense from a request perspective, and thus should be a bit more differentiated in the API.
