### ISSUE TITLE
Allow decoration of Mono<Connection>

### ISSUE THREAD

**Issue by codefromthecrypt** [reactor/reactor-netty#1036]
We'd like a means to decorate the `Mono<Connection>` created in the HttpClient's `MonoHttpConnect.subscribe()` without resorting to static hooks. If we had an explicit hook, context propagation would be easier to follow and likely more performant.

## Motivation
Right now, sleuth resorts to [static hooks](https://github.com/spring-cloud/spring-cloud-sleuth/blob/master/spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/reactor/TraceReactorAutoConfiguration.java) in order to configure trace context propagation defined in [ScopePassingSpanSubscriber](https://github.com/spring-cloud/spring-cloud-sleuth/blob/master/spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/reactor/ScopePassingSpanSubscriber.java). The setup is more complex and error prone vs being able to affect the Mono directly.

## Desired solution
Some means to achieve the same as what we do [here](https://github.com/spring-cloud/spring-cloud-sleuth/blob/0d237b564f48c55eed7e85e68adb79c2b388280c/spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/reactor/ReactorSleuth.java), except not reliant on static hooks. It could be simplfied as the reactor context already includes the trace properties we need.

## Considered alternatives
Right now, we can rely on static hooks as sleuth already sets them up

## Additional context
n/a

**Comment by violetagg** [comment]
@adriancole You have [mapConnect](https://projectreactor.io/docs/netty/release/api/reactor/netty/http/client/HttpClient.html#mapConnect-java.util.function.BiFunction-)
so you can decorate `Mono<Connection>`
what else is needed?

**Comment by violetagg** [comment]
I thing that `mapConnect` can be used in these scenarios. Closing this issue. We can reopen it if it is needed.
