### ISSUE TITLE
Add Http2 support

### ISSUE THREAD

**Issue by yschimke** [reactor/reactor-netty#104]
Wishlist item for Http2 support.  Seems based on keepalive support that reused connections are possible.

**Comment by thekalinga** [comment]
This item seemed to tagged to 0.9.0.RELEASE.

Any idea where I can find the release schedule for this?

Thanks

**Comment by smaldini** [comment]
We will work on that around Q2 - We haven't set a date but it should align with Spring Framework 5.1 work as well. We're looking pretty much to this indeed ( see reactor netty roadmap from S1P here https://speakerdeck.com/smaldini/springoneplatform-2017-reactor-now-and-tomorrow) !

**Comment by thekalinga** [comment]
@smaldini Can you please share if any progress is being made to this?

**Comment by violetagg** [comment]
@thekalinga you can take a look here https://github.com/reactor/reactor-netty/blob/master/src/test/java/reactor/netty/http/HttpTests.java#L496
there is still not API for working with streams

**Comment by thekalinga** [comment]
@violetagg Thanks for that. Do u have any idea when the development on this item starts?

**Comment by violetagg** [comment]
> Do u have any idea when the development on this item start & any target you have in mind for completion?

What do you mean?
The upgrade from HTTP/1.1 to HTTP/2 is there, what the missing part is to work directly with the streams....
The 0.8.0.M1 is around the corner

**Comment by thekalinga** [comment]
@violetagg Sorry for my ignorance. I dont have much idea about the internal apis created in this project to support HTTP2 API. Is it fair to say 0.8.0 will contain full HTTP2 support?

**Comment by violetagg** [comment]
> Is it fair to say 0.8.0 will contain full HTTP2 support?

yes

**Comment by medalliaerlich** [comment]
Hi, Which is the release date for 0.8.0? 
Is there a RC version?

**Comment by violetagg** [comment]
@medalliaerlich We are currently work towards M1, what do you want to see as HTTP/2 support in 0.8? Just supporting HTTP/2 protocol, or manipulating the streams etc.
It will be very helpful to know what people need as HTTP/2 support

Thanks,
Violeta

**Comment by medalliaerlich** [comment]
We are planning on using Spring Cloud Gateway which is using Reactor Netty, and are waiting for release 0.8. Please check thread https://github.com/spring-cloud/spring-cloud-gateway/issues/7

**Comment by violetagg** [comment]
HTTP/2 support for HttpServer available as part of 0.8.0.M1
#402

**Comment by violetagg** [comment]
HTTP/2 for the server is available with Reactor Netty 0.8.x
HTTP/2 for the client will be tracked here #639
