### ISSUE TITLE
Why Backlog is 0

### ISSUE THREAD

**Issue by yechao4j** [reactor/reactor-netty#1044]
When i start Springcloud gateway in 'Alibaba Cloud Elastic Compute Service', i found
```
State       Recv-Q Send-Q   Local Address:Port 
LISTEN      0        0                    *:8080 
```
Send-Q is 0, but 'somaxconn' is 262144
```
[abc@iZt4nc4r ~]$ cat /proc/sys/net/core/somaxconn
262144
```
Is anything problem with server?
netty version is 4.1.38.Final, reactor-netty 0.8.10, core 3.2.11

**Comment by violetagg** [comment]
@yechao4j version 0.8.10 is almost 1 year old. Please first upgrade to the latest version.

**Comment by yechao4j** [comment]
@violetagg need time to upgrade to the latest version, it will be ok ?

**Comment by violetagg** [comment]
Closing this issue. We can reopen it if it is needed.
