### ISSUE TITLE
reactor.netty.pool.maxIdleTime don't take effect

### ISSUE THREAD

**Issue by wm240918567** [reactor/reactor-netty#1059]
hi,
  My English is not so good, I wish I could make that clear.
  I set system  property in the main funtion before springapplication.run,
        System.setProperty(ReactorNetty.POOL_MAX_IDLE_TIME, "60000");

  When the.application be started by springapplication.run, I found reactor.netty.pool.maxIdleTime don't take effect,
  Because at the line 332 of TcpResources class ，function ConnectionProvider.fixed be invoked。
but I see javadoc of  this function ，‘@deprecated as of 0.9.5. Use {@link #create(String, int)}’
  Function fixed set  maxIdleTime is null.
  So I think TcpResources class should to invoke function of create , Is that right？

* Reactor version(s) used:  reactor-netty 0.9.6-RELEASE
* Other relevant libraries versions (eg. `netty`, ...):  
  spring boot 2.2.6.RELEASE
* JVM version (`javar -version`): 1.8.0_231
* OS and version (eg `uname -a`): mac os 10.15.3

**Comment by violetagg** [comment]
@wm240918567 This was fixed https://github.com/reactor/reactor-netty/commit/c6a4f7914153ef485da5a626055a42629d860cce

Please try 0.9.7.BUILD-SNAPSHOT
