### ISSUE TITLE
reactor.netty.http.client.PrematureCloseException: Connection prematurely closed BEFORE response

### ISSUE THREAD

**Issue by radhakrishnanch** [reactor/reactor-netty#1061]
### **Expected Behavior**

WebClient should not pick the inactive channel from the pool for serving new requests.

### **Actual Behavior**

There is a race-condition, sometimes WebClient picks inactive channel from the poll and cause of connection error.
.
### **TCP Client Debug Log**

Below log shows an inactive connection is picked just before unregistering and causes for connection error.

[DEBUG] 2020-04-09 02:54:48.573 [reactor-http-epoll-6] TcpClient - [id: 0xbced41ae, L:/10.12.43.11:44708 ! R:<URL Here>:80] INACTIVE

[WARN ] 2020-04-09 02:54:48.573 [reactor-http-epoll-6] HttpClientConnect - [id: 0xbced41ae, L:/10.12.43.11:44708 ! R:<URL here>:80] The connection observed an error
reactor.netty.http.client.PrematureCloseException: Connection prematurely closed BEFORE response

[DEBUG] 2020-04-09 02:54:48.578 [reactor-http-epoll-6] TcpClient - [id: 0xbced41ae, L:/10.12.43.11:44708 ! R:<URL Here>:80] UNREGISTERED

### **Steps to Reproduce**

I am using below code to create WebClient

`@Bean
  public WebClient webClient() {

    ConnectionProvider connectionProvider = ConnectionProvider
        .fixed("fixed", 1000,
            25000, Duration
                .ofSeconds(120));

    TcpClient tcpClient = TcpClient.create(connectionProvider)
        .wiretap(orchCCMConfig().isWebClientLogEnabled())
        .option(ChannelOption.CONNECT_TIMEOUT_MILLIS, 1000)
        .doOnConnected(conn -> conn
            .addHandlerLast(new ReadTimeoutHandler(
                2000,
                TimeUnit.MILLISECONDS))
            .addHandlerLast(new WriteTimeoutHandler(
                500,
                TimeUnit.MILLISECONDS))
            .addHandler(new IdleStateHandler(
                2000,
                500, 5000,
                TimeUnit.MILLISECONDS)));

    HttpClient httpClient = HttpClient.from(tcpClient)
        .compress(true);

    return WebClient.builder()
        .clientConnector(new ReactorClientHttpConnector(httpClient))
        .build();

  }`

###  Your Environment

* Reactor BOM version used: Dysprosium-SR4
 * Netty version : 0.9.4
* JVM version : 1.8.0_77 (Java HotSpot(TM) 64-Bit Server VM)
* OS and version : Linux x86_64 x86_64 x86_64 GNU/Linu

**Comment by violetagg** [comment]
@radhakrishnanch Please test with 0.9.6.RELEASE. In that version we have fixes related to the connection pool.

**Comment by radhakrishnanch** [comment]
@violetagg Thank you for your reply. I will test with 0.9.6.RELEASE and update the observation here.

**Comment by violetagg** [comment]
I'm closing this issue. We can reopen it if it is needed.
