### ISSUE TITLE
[HTTP2] Consider X-Forwarded-For header in remote address

### ISSUE THREAD

**Issue by Tiller** [reactor/reactor-netty#1088]
Sending an H2C Prior knowledge query to my reactor-netty server with the header "X-Forwarded-For" doesn't take the header into account when retrieving remote address.

I am not entirely sure whether this is a bug or not, and tbh I'm not even sure the X-Forwarded-Host is part of the http2 "standard", but just in case, I'm opening this feature request!

## Motivation
Similarly to HTTP, I think remote address should be computed using forwarded headers to avoid specific parsing of this header in my code

## Desired solution
Same behavior as for HTTP1 (I haven't checked how it works in HTTP1, sorry)

**Comment by violetagg** [comment]
@Tiller did you specify `HttpServer.forwarded(true)`?
https://projectreactor.io/docs/netty/release/reference/index.html#_obtaining_the_remote_client_address

**Comment by Tiller** [comment]
I did not indeed. And it works with it. Thanks and sorry for the ticket!
