### ISSUE TITLE
Source line numbrers are outdated in reference documentation

### ISSUE THREAD

**Issue by izeye** [reactor/reactor-netty#1097]
Source line numbrers seem to be outdated in the reference documentation.

For example, see https://projectreactor.io/docs/netty/release/reference/index.html#server-tcp-level-configurations-channel-options

**Comment by violetagg** [comment]
@izeye This was fixed with 5dccb280b00e1dae9ee49c835ec0bc110f773455 and the fix will be available with the next 0.9.8.RELEASE

**Comment by izeye** [comment]
@violetagg Sorry for the noise. I should have checked before opening this.

Actually, I wanted to fix it, but I wasn't sure how to avoid this sort of out-of-sync.

**Comment by violetagg** [comment]
> Actually, I wanted to fix it, but I wasn't sure how to avoid this sort of out-of-sync.

Yes it is very inconvenient.
In master currently we are rewriting some of the APIs and I moved those setting to the beginning of the file so hopefully there will be less cases like this.
Please note that the documentation in master needs some rework that we will do before milestone publishing.
