### ISSUE TITLE
add  ability to configure response  timeout for the web-socket handshake operation

### ISSUE THREAD

**Issue by Fetsivalen** [reactor/reactor-netty#1100]
Currently, there is a way to configure timeout via reactor timeout according to https://github.com/reactor/reactor-netty/issues/26
and this timeout will work as the response timeout for the handshake operation but at the same time, it will abort established web-socket connection.

## Expected Behavior
1. should be the ability to configure the separate timeout for the Handshake operation which won't abort the web-socket connection

## Actual Behavior
Timeout ends established web-socket connection and there are no other options to set timeout to handshake operation

## Steps to Reproduce
I've prepared a test which could be copy/pasted into 
reactor.netty.http.client.WebsocketTest  tests class.
Hope such example is proper as well as reproducible sample

```java
@Test
	public void testTimeoutshouldNotAbortWebSocketConnection() {
		MonoProcessor<WebSocketCloseStatus> statusClient = MonoProcessor.create();

		httpServer =
				HttpServer.create()
						.port(0)
						.handle((req, res) ->
								res.sendWebsocket((in, out) -> Mono.delay(Duration.ofSeconds(1)).
										then(out.sendObject(new CloseWebSocketFrame(NORMAL_CLOSURE)).then())))
						.wiretap(true)
						.bindNow();

		HttpClient.create()
				.port(httpServer.port())
				.websocket()
				.uri("/")
				.handle((in, out) -> {
					in.receiveCloseStatus()
							.subscribeWith(statusClient);

					return out.sendObject(in.receiveFrames()
							.doOnNext(WebSocketFrame::retain)
							.then());
				})
				.timeout(Duration.ofMillis(100)) 
				.subscribe();

		StepVerifier.create(statusClient)
				.assertNext(closeStatus -> assertThat(closeStatus).isEqualTo(NORMAL_CLOSURE))
				.expectComplete()
				.verify(Duration.ofSeconds(10));
	}
```

## Possible Solution
1. Add a separate property to specify a timeout for the web-socket handshake operation
for example similar one to the netty https://github.com/netty/netty/issues/8841
2. Prevent timeout to be applied to the established web-socket connection.

## Your Environment
it is reproducible on 0.9.6.RELEASE, 0.9.7.RELEASE,  and latest master in this project

another versions seems not to be relevant in this case.

**Comment by violetagg** [comment]
@Fetsivalen With the current API you are able to do that:

On the server side:
https://projectreactor.io/docs/netty/release/api/reactor/netty/http/server/HttpServerResponse.html#sendWebsocket-java.util.function.BiFunction-
With `.sendWebsocket` you will receive `Mono<Void>` that completes when the handshake completes.

So you can have something like

```
res.sendWebsocket(...)
   .timeout(Duration)
```

On the client side:
https://projectreactor.io/docs/netty/release/api/reactor/netty/http/client/HttpClient.WebsocketReceiver.html#connect--
Instead of using `.handle` you can first call `.connect`.

So you can have something like

```
Connection connection =
        HttpClient.create()
                  .wiretap(true)
                  .websocket()
                  .uri("wss://echo.websocket.org")
                  .connect()
                  .timeout(Duration.ofSeconds(2))
                  .block();

connection.outbound()
          .sendString(Mono.just("echo"))
          .then()
          .subscribe();

connection.inbound()
           .receiveObject()
           .ofType(TextWebSocketFrame.class)
           .map(TextWebSocketFrame::text)
           .doOnNext(System.out::println)
           .blockLast();
```

Wdyt?

**Comment by Fetsivalen** [comment]
Hi @violetagg ,

Seems like this solution will fix my test.
I've missed it since I tried to find a way to do it through [Spring Framework's client](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/reactive/socket/client/ReactorNettyWebSocketClient.html)
And there is only `execute` method.

By the way as far as I understand in production usage `block` and similar blocking operator have to be avoided.
and it will look like
 ```
        HttpClient.create()
                  .wiretap(true)
                  .websocket()
                  .uri("wss://echo.websocket.org")
                  .connect()
                  .timeout(Duration.ofSeconds(2))
                 .inbound()
                .receiveObject()
// do smth with frames here
```
from [timeout's Javadoc](https://projectreactor.io/docs/core/release/api/reactor/core/publisher/Mono.html#timeout-java.time.Duration-) it works as a timeout for the specific Mono.
It may work, but I need more time to "inject" all this stuff inside my project since I will need to rework  Spring's implementation a bit more.
Probably the proper place for this enhancement in Spring framework project.
Anyway, I will test whether this will work and let you know.

**Comment by Fetsivalen** [comment]
By the way it'll be nice to have API like:
```
Mono<Connection> connection =
        HttpClient.create()
                  .wiretap(true)
                  .websocket()
                  .uri("wss://echo.websocket.org")
                  .connect(Duration.ofSeconds(2));
```
which seems like a more obvious one (at least for me)

**Comment by violetagg** [comment]
@Fetsivalen I used `block` as it was in a test and I wanted just to show that you can use the operators from Reactor.

you can do the following without `block`

```
HttpClient.create()
          .wiretap(true)
          .websocket()
          .uri("wss://echo.websocket.org")
          .connect()
          .timeout(Duration.ofSeconds(2))
          .subscribe(conn -> do something with the connection);
```

**Comment by Fetsivalen** [comment]
@violetagg sorry for long response on this.

I've tested your suggestion and it worked just fine
when i reworked [spring boot client](
https://github.com/spring-projects/spring-framework/blob/master/spring-webflux/src/main/java/org/springframework/web/reactive/socket/client/ReactorNettyWebSocketClient.java) to look like this
```
        return getHttpClient()
// headers omitted
                .websocket(protocols, getMaxFramePayloadLength(), this.getHandlePing())
                .uri(url.toString())
                .connect()
                .timeout(handshakeTimeout,
                        Mono.error(new TimeoutException("Handshake response took longer than timeout: " + handshakeTimeout)))
                .flatMapMany((connection) -> {
                    // omitted not relevant stuff
                    WebSocketSession session = new ReactorNettyWebSocketSession(
                            //end code change
                            (WebsocketInbound) connection, (WebsocketOutbound) connection, info, factory, getMaxFramePayloadLength());
                    return Flux.from(handler.handle(session).checkpoint(url + " [ReactorNettyWebSocketClient]"));
                })
                .doOnRequest(n -> {
                    if (log.isDebugEnabled()) {
                        log.debug("Connecting to " + url);
                    }
                })
                .next();
```

I just wonder will you accept a PR  to have a method in [WebsocketFinalizer]https://github.com/reactor/reactor-netty/blob/master/src/main/java/reactor/netty/http/client/WebsocketFinalizer.java
to have another  `handle` and `connect` method which will accept Duration as a handshake timeout?

**Comment by violetagg** [comment]
@Fetsivalen I think that using Reactor Core operators for timeout give you many more options and I don't think that we need to replicate Reactor Core functionality in Reactor Netty.
https://projectreactor.io/docs/core/release/api/reactor/core/publisher/Mono.html#timeout-java.time.Duration-

**Comment by Fetsivalen** [comment]
@violetagg  I've not meant to repeat timeout logic
my idea was to have shortcut methods like
```
public Mono<? extends Connection> connect(Duration handshakeTimeout) {
		return super.connect().timeout(handshakeTimeout);
	}
```
and similar one for handle
wdyt?

**Comment by violetagg** [comment]
@Fetsivalen I understood but then somebody will come and ask for a new method with `timeout + fallback` or `timeout + scheduler` or any other combination that currently Reactor Core provides.

**Comment by Fetsivalen** [comment]
ok so I will open a ticket in spring project then
Thanks for the help!
