### ISSUE TITLE
Can't customize SNI values in client requests

### ISSUE THREAD

**Issue by jblashka** [reactor/reactor-netty#1105]
## Motivation
I'm trying to use a customized reactor netty httpclient within a spring cloud gateway application but it doesn't look like there's a way to set the SNI value to something *different* than the hostname specified in the server list. I have a gateway in front of a set of load balancers that handle traffic for multiple services and the load balancer expects SNI to be set for the relevant service rather than the load balancer's hostname. I have a custom HttpClient bean but I couldn't see a way to override the remote address that the SslProvider would uses set the SNI values while still connecting to the original address

## Desired solution
I believe this [test class](https://github.com/netty/netty/blob/4.1/handler/src/test/java/io/netty/handler/ssl/SniClientTest.java) from the netty handler code demonstrates the behavior I'm interested in; it sets SNI to "sni.netty.io" even though the request is routed to `new LocalAddress("test")`

**Comment by violetagg** [comment]
@jblashka For which version do you need this enhancement?

**Comment by jblashka** [comment]
I'm using reactor-netty 0.9.6.RELEASE at the moment because that's the version of the dependency pulled in with spring-cloud-starter-gateway 2.2.2.RELEASE

**Comment by violetagg** [comment]
@jblashka You can specify custom SNI with the following

```
  .secure(ssl -> ssl.sslContext(sslClient)
                    .handlerConfigurator(h -> {
                        SSLEngine engine = h.engine();
                        SSLParameters sslParameters = engine.getSSLParameters();
                        sslParameters.setServerNames(Collections.singletonList(new SNIHostName("vily")));
                        engine.setSSLParameters(sslParameters);
  }))
```

**Comment by violetagg** [comment]
@jblashka I'm closing the issue, if this approach of configuring SNI is not enough we can reopen this issue.
