### ISSUE TITLE
On Server side not able to retrieve a domain object from a HttpServerRequest/ByteBufFlux object using subscribe or doOnNext

### ISSUE THREAD

**Issue by acgrimes** [reactor/reactor-netty#1107]
This is a client/server environment. For this application the client sends a request object to the server. The server needs to do some business logic on the request object that may or may not involve a database. Based on the request received a different response is returned to the client. The server receives the domain request object contained in a HttpServerRequest that holds a ByteBufFlux publisher. Subscribe() or doOnNext() were used to extract the domain request object. In the sample provided neither of these techniques worked since the onSuccess lambda is never invoked. In other words, on the server side there doesn't seem to be a way to get the domain request object from the ByteBufFlux object contained in the HttpServerRequest. However, when the server returns a response object in the form of an HttpServerResponse, the client is able to use subscribe() and the onSuccess lambda to extract the received domain response object. A sample client/server is attached in the zip file reactorNetty.zip. Run the client and server in separate terminals and build both the client and server with "mvn compile". Execute the client with 'mvn exec:java -Dexec.mainClass="client.Client" '. Execute the server with 'mvn exec:java -Dexec.mainClass="server.Server" '. Nothing is printed to the console on the server side, but the client prints the received response object returned by the server. Subscribe() works on the client side, but doOnNext() doesnot invoke onSuccess on the server side.
My environment is:
Apache Maven 3.6.3
Maven home: /usr/share/maven
Java version: 11.0.6, vendor: Oracle Corporation, runtime: /home/linuxlp/opt/graalvm/graalvm-svm-linux-20.1.0-ea+28
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.4.0-31-generic", arch: "amd64", family: "unix"
Thanks.
[reactorNetty.zip](https://github.com/reactor/reactor-netty/files/4663317/reactorNetty.zip)

**Comment by violetagg** [comment]
@acgrimes The snippet below does NOT have subscribe so receiving the request body will not be triggered

```
.post("/echo",
        (request, response) -> {
            request.receive()
                   .aggregate()
                   .doOnNext(onSuccess)
                   .doOnError(onError)
                   .doOnTerminate(onCompletion);    <= does NOT have subscribe so the execution will not be triggered
            return response.send(Mono.just(Unpooled.copiedBuffer(SerializationUtils.serialize(electionResponse))));
}))
```

Has to be rewritten either as:

```
.post("/echo",
        (request, response) -> {
            request.receive()
                   .aggregate()
                   .doOnNext(onSuccess)
                   .doOnError(onError)
                   .doOnTerminate(onCompletion)
                   .subscribe();
            return response.send(Mono.just(Unpooled.copiedBuffer(SerializationUtils.serialize(electionResponse))));
}))
```
This structure means: Send this response immediately, I'll subscribe for the request and when it comes I will handle it
Do you want this? The request body may come in a later stage.

or:

```
.post("/echo",
        (request, response) -> {
            return response.send(request.receive()
                              .aggregate()
                              .doOnNext(onSuccess)
                              .doOnError(onError)
                              .doOnTerminate(onCompletion)
                              .flatMap(aggregatedBody -> Mono.just(Unpooled.copiedBuffer(SerializationUtils.serialize(electionResponse)))));
}))
```

This means invoke send operation when I receive the request and transform it into a response.
So here the response is not sent immediately, but when the aggregated request body is available.
In this case you do not need to invoke subscribe because Reactor Netty will subscribe for it as part of the send operation.

**Comment by acgrimes** [comment]
Yes, I want the case where the response comes immediately with the request arriving later. But when I add subscribe() as here:
.post("/echo",
        (request, response) -> {
            request.receive()
                   .aggregate()
                   .doOnNext(onSuccess)
                   .doOnError(onError)
                   .doOnTerminate(onCompletion)
                   .subscribe();
            return response.send(Mono.just(Unpooled.copiedBuffer(SerializationUtils.serialize(electionResponse))));
}))

or subscribe(onSuccess, onError, onCompletion), none of the lambdas are called, especially onSuccess. That seems to be the problem. I need the onSuccess lambda to be invoked so I can get  the ElectionRequest domain object out of the Flux object, process it and return a separate response to the client.

**Comment by violetagg** [comment]
@acgrimes That's as expected as I wrote
"Do you want this? The request body may come in a later stage."
According to the specification (https://tools.ietf.org/html/rfc7230#section-6.3)

```
A server MUST read
   the entire request message body or close the connection after sending
   its response, since otherwise the remaining data on a persistent
   connection would be misinterpreted as the next request.
```

As you send the full response, we can only drop the incoming data and close the connection. We don't know what's the size of the incoming data.

If you want enable the Reactor Netty logs + add to the configuration `wiretap(true)` so that you will be able to see the traffic between the server and the client.

**Comment by violetagg** [comment]
What you can do is the following:

In your send operation use Flux.concat()
Where the first Publisher will be what you have now and the second publisher will be what you want to send as a result of the request

**Comment by violetagg** [comment]
```
public class Server {

    private static final Logger log = Logger.getLogger(Server.class.getSimpleName());

    public static void main(String[] args) {

        ElectionResponse electionResponse = new ElectionResponse("aResponse");

        Consumer<byte[]> onSuccess = (request) -> {
            System.out.println("onSuccess: Request received!");
        };
        Consumer<Throwable> onError = (Throwable ex) -> {
            ex.getMessage();
        };
        Runnable onCompletion = () -> {
            System.out.println("Message Completed");

        };

        DisposableServer server =
            HttpServer.create()
                      .host("localhost")
                      .port(8080)
                      .wiretap(true)
                      .route(routes ->
                          routes
                            .post("/echo",
                                    (request, response) -> {
                                        MonoProcessor<byte[]> mono = MonoProcessor.create();
                                        request.receive()
                                                .aggregate()
                                                .asByteArray()
                                                .doOnNext(onSuccess)
                                                .doOnError(onError)
                                                .doOnTerminate(onCompletion)
                                                .subscribeWith(mono);
                                        return response.send(Flux.concat(Mono.just(Unpooled.copiedBuffer(SerializationUtils.serialize(electionResponse))),
                                                mono.flatMap(bytes -> {
                                                    ElectionRequest electionRequest = SerializationUtils.deserialize(bytes);
                                                    byte[] requestBytes = SerializationUtils.serialize(new ElectionResponse(electionRequest.getRequest()));
                                                    return Mono.just(Unpooled.copiedBuffer(requestBytes));
                                                })));
                            }))
                        .bindNow();

        server.onDispose()
                .block();
    }
}
```

**Comment by acgrimes** [comment]
Thanks, this code gives me access to the request object and it can be passed to a service for processing, but when I run this code nothing gets returned to the client. This confuses me since I can write very similar code using Spring WebFlux, get access to the request, process it and return a response to the client. Here is a code snippet that we use in Spring, which is using Reactor Netty.
With Spring I can use a Router, Handler and a Service to achieve what I need.

The router gets a POST from the client, that contains an ElectionRequest:
`code`
    @Bean
    public RouterFunction ServerResponse  electionTransaction() {

        return route(RequestPredicates.POST("/election/transaction").
                        and(RequestPredicates.accept(MediaType.APPLICATION_JSON)),
                electionTransactionHandler::electionTransactionResponse);
    }

The Router invokes a handler, passing it a ServerRequest:
`code`
    public Mono ServerResponse electionTransactionResponse(ServerRequest serverRequest) {

        return ServerResponse.
                ok().
                contentType(MediaType.APPLICATION_JSON).
                body(BodyInserters.fromProducer(serverRequest.bodyToMono(ElectionRequest.class).
                                flatMap(p -> electionService.electionTransactionResponse(p)),
                        ElectionResponse.class)).
                doOnSuccess(System.out::println);

    }

The handler then calls a service, passing the ElectionRequest domain object, the service does some processing, and returning a Mono<ElectionResponse> domain object:
`code`
    public Mono ElectionResponse electionTransactionResponse(ElectionRequest electionRequest) {
 
       ElectionResponse electionResponse = new ElectionResponse("aResponse");
        return Mono.just(electionResponse);
    }

The handler returns a ServerResponse back to the router and this is returned to the client. With this Spring WebFlux code the server can process the request domain object and the client gets back a server response. i am trying to achieve the same interaction in Reactor Netty without introducing Spring.  I can send the Spring WebFlux code if that is useful.

**Comment by rstoyanchev** [comment]
@acgrimes the WebFlux snippet doesn't look similar to me. It's echoing the request body in the response body.

**Comment by acgrimes** [comment]
But that is exactly what I am trying to do with Reactor-Netty. Get the request body out of the request, do some processing on it and return a reactive response with or without request content. I haven't been able to put together Reactor-netty code that does both of those things. The reactor code I have tried either returns a response to the client without letting me retrieve the request body, or as with the last code provided, I can get the request body, but not the response is not returning to the client. Since Spring WebFlux is based on Reactor-netty, I am not sure why I can't achieve getting the request body and returning a response. I would think this is common in microservices, having a client Post a request, have the microservice process the request body and return a response, all being done reactively, async/nonblocking.

**Comment by violetagg** [comment]
@acgrimes Then that's what I proposed you at the beginning 

```
.post("/echo",
        (request, response) -> {
            return response.send(request.receive()
                              .aggregate()
                              .doOnNext(onSuccess)
                              .doOnError(onError)
                              .doOnTerminate(onCompletion)
                              .flatMap(aggregatedBody -> Mono.just(Unpooled.copiedBuffer(SerializationUtils.serialize(electionResponse)))));
}))
```

In the `flatMap` you can transform the request content as you like and return a response

**Comment by acgrimes** [comment]
Ok, let me try that. Thanks, for your patience while I try to understand how this is working.

**Comment by violetagg** [comment]
great that it's working!
