### ISSUE TITLE
HttpClientRequest#sendWebsocket() does not honor HttpClientRequest.failOnClientError(boolean) or HttpClientRequest.failOnServerError(boolean)

### ISSUE THREAD

**Issue by nebhale** [reactor/reactor-netty#113]
Currently, the `HttpClientRequest#sendWebsocket()` does not honor the request's settings for `HttpClientRequest.failOnClientError(boolean)` or `HttpClientRequest.failOnServerError(boolean)`.  This leads to exceptions being thrown when they should not be.  The `sendWebsocket()` method should honor those settings.

This problem was [raised as an issue](https://github.com/cloudfoundry/cf-java-client/issues/774) in the `cf-java-client`, so I'd like to request a 0.6.5 with a fix rather than waiting for an incompatible 0.7.0.

**Comment by smaldini** [comment]
Fixed by https://github.com/reactor/reactor-netty/commit/63dd43d690bf19971fcfb4cb3e885b577ec486da

**Comment by nebhale** [comment]
I'm guessing this means that this won't be a 0.6.5 release then.  Putting it in 0.7.0 means that we're blocked until 3.1.0 and 0.7.0 are final and can't deliver a fix to our users until then.
