### ISSUE TITLE
query string encoding twice by netty when exists equal character inside

### ISSUE THREAD

**Issue by et00448** [reactor/reactor-netty#1132]
Hello

I am using spring-cloud Hoxton.SR4 with spring boot (spring-boot-starter-parent) 2.2.5.
I have an encoding problem with query params containing the equal character "=" due to reactor.netty.http.client.HttpClientConnect.

For instance,  the whole string (passed throw spring cloud gateway inside query string) : 
http://xx.xx.xx.xx/foo?test_egal==%223

become twice URIencode to the backend : 
test_egal==%25223 

How can I preserve the integrity of the query parameters (get method) when exists equals characters ?

Thank you !

**Comment by violetagg** [comment]
@et00448 Can you elaborate more why you think it is an issue in Reactor Netty and explicitly in `reactor.netty.http.client.HttpClientConnect`?
Reactor Netty has API only for `uri` and `path`.

Very basic test shows that there is no encoding issue:

```
public class Test {

	public static void main(String[] args) {
		DisposableServer server =
				HttpServer.create()
					.port(8080)
					.handle((req, res) -> {
						System.out.println("uri : " + req.uri());
						System.out.println("path : " + req.path());
						System.out.println("fullpath : " + req.fullPath());
						return res.sendString(Mono.just("test"));
					})
					.wiretap(true)
					.bindNow();

		HttpClient.create()
			.wiretap(true)
			.get()
			.uri("http://localhost:8080/foo?test_egal==%223")
			.responseContent()
			.aggregate()
			.block();

		server.onDispose()
			.block();
	}
}
```

The result from `System.out` is:

```
uri : /foo?test_egal==%223
path : foo
fullpath : /foo
```

**Comment by et00448** [comment]
Hi,

You are right. 
The problem was due to malformed URL received by spring cloud gateway.
Indeed existing "=" character inside the URI received generated a double URL encode in spring cloud gateway. 
We solve this issue by reurlencode each incoming stream.

Thank'you for your quick answer !
best regards
