### ISSUE TITLE
http client use regular expression have performance problems

### ISSUE THREAD

**Issue by wu560130911** [reactor/reactor-netty#1133]
https://github.com/reactor/reactor-netty/blob/master/src/main/java/reactor/netty/http/client/UriEndpointFactory.java#L33

per request need RE have performance problems, can provide method with URI object instead of uri string ?

**Comment by violetagg** [comment]
@wu560130911 Do you always request different endpoints or just one? Can you specify once [baseUrl](https://projectreactor.io/docs/netty/release/api/reactor/netty/http/client/HttpClient.html#baseUrl-java.lang.String-) and then in `uri` just the path to the resource?

**Comment by wu560130911** [comment]
I'm using like that.
https://github.com/spring-cloud/spring-cloud-gateway/blob/master/spring-cloud-gateway-core/src/main/java/org/springframework/cloud/gateway/filter/NettyRoutingFilter.java#L131
`Flux<HttpClientResponse> responseFlux = getHttpClient(route, exchange)
				.headers(headers -> {
					headers.add(httpHeaders);
					// Will either be set below, or later by Netty
					headers.remove(HttpHeaders.HOST);
					if (preserveHost) {
						String host = request.getHeaders().getFirst(HttpHeaders.HOST);
						headers.add(HttpHeaders.HOST, host);
					}
				}).request(method).uri(url).send((req, nettyOutbound) -> {`

baseUrl is always null.

**Comment by violetagg** [comment]
@wu560130911 The new API will be available with 0.9.8.RELEASE

@rstoyanchev @spencergibb From performance point of view it will be better to switch to this new API.

**Comment by spencergibb** [comment]
What release train will this be part of? And which boot version will consume it.

**Comment by violetagg** [comment]
> What release train will this be part of? And which boot version will consume it.

Reactor Bom : Dysprosium-SR8, Spring Boot : 2.2.8.RELEASE
