### ISSUE TITLE
Suggest : Provide build task to package single jar for easy

### ISSUE THREAD

**Issue by kitepad** [reactor/reactor-netty#1140]
## Motivation

When we use reactor-netty without gadle/maven and other build tools, we have to manage runtime dependencies. 
## Desired solution

Would you provide official build task to produce minimal reactor-netty single jar includes minimal required third-party packages (for example, netty/log/reactor-core)?

**Comment by violetagg** [comment]
@kitepad 

> When we use reactor-netty without gadle/maven and other build tools

Can you tell us more about this, what these tools are?

**Comment by kitepad** [comment]
For example, sbt. Maybe eclipse jdt is a simple build tool to help me build some small java based microservices as uber-jar. In my eclipse project, I like add needed jar file with dependencies by my self without maven/gradle.

**Comment by violetagg** [comment]
@kitepad With the current approach if a security vulnerability appears in some of the third party dependencies you are able to update it independent from Reactor Netty.
If we provide such "fat" jar, Reactor Netty will be responsible for the security vulnerabilities that may appear in the third party dependencies. We can not take such a responsibility, but you can build such jar at your own risk.
