### ISSUE TITLE
reactor.netty.http.client.PrematureCloseException: Connection prematurely closed BEFORE response

### ISSUE THREAD

**Issue by lombook** [reactor/reactor-netty#1141]
hello, I've seen this issue before，recently upgrade reactor-netty to 0.9.7.release ,but i still face this issue.

spring-boot-dependencies: 2.3.0.RELEASE
netty: 4.1.49.Final
JVM version : jdk 1.8

scene:
 Mono<ClientResponse> resp = webClient.post()
            .uri(url)
            .headers(c -> this.processHeader(c, token, headers))
            .body(Mono.just(requestBody), requestBodyClass)
            .exchange()
            .timeout(retryConfig.getTimeout())
            .retryWhen(retry)
            .flatMap(r -> {
                log.debug("Received response from {}", url);
                return Mono.just(r);
            });

the percent of this kind of issue is not high, but i don't have a good solution.
any reply will be appreciated.

**Comment by violetagg** [comment]
@lombook Check this https://github.com/reactor/reactor-netty/issues/1092#issuecomment-627792713 and try to obtain tcp dump

**Comment by violetagg** [comment]
@lombook Closing this issue, if you have more information we can reopen it.
