### ISSUE TITLE
Reactor netty doesnt handle 1k request in one connection

### ISSUE THREAD

**Issue by sukawanth** [reactor/reactor-netty#1146]
We are using spring cloud gateway as a HTTP2 proxy, with reactor netty to receive request and uses "Spring WebClient + reactor Jetty" to forward the request to the other hop. 

We are sending 4k requests over four connections to proxy. Sometimes only header Frame is sent to jetty client but it fails to receive the request content.

We are running the proxy in a Kubernetes environment with 4VCPU and 4GB as the profile for the container.

Our understanding is 4 threads are created in reactor netty and each thread is handling one connection. Can it be possible that reactor netty threads are busy and cannot respond to jetty client content subscription request. We tried all other options and narrowed down to this cause.

If we run the same traffic with 32 connections towards proxy then there is no issue...!
If there any tuning to be done to achieve this kind of traffic model.
 
## Your Environment
* Reactor version(s) used: 0.9.5.RELEASE
* Other relevant libraries versions (eg. `netty`, ...): netty 4.1.46.Final
* JVM version (`javar -version`): open jdk 14
* OS and version (eg `uname -a`): Linux 4.1.12-112.16.4.el7uek.x86_64

**Comment by violetagg** [comment]
@sukawanth If it is possible please upgrade to the latest released versions.
Can you apply BlockHound so that we are sure there is no blocking call?
https://github.com/reactor/blockHound/

**Comment by sukawanth** [comment]
Hi, we upgraded Netty to 4.1.50.Final and Reactor Netty to 0.9.8.RELEASE. and still the problem persists. 

We are using Vegeta to do HTTP2 load testing and as I mentioned earlier we created 4 connections 20 seconds apart and running 1k traffic on each. We see four connections taking equal amount of load and suddenly one thread starts dangling and requests only on the particular thread starts to timeout. 

Our observation is when ever second connection is made the first connection CPU utilization shoots to 80% on one core. The timeouts are happening because jetty client is not able to read the request body content form reactor netty thread and its always the first thread that is unstable.
Is it because the first thread also acts as a boss thread?

customize(NettyReactiveWebServerFactory factory) {
		LoopResources resource = LoopResources.create("ingress-h2c");
		ReactorResourceFactory reactorResourceFactory = new ReactorResourceFactory();
		reactorResourceFactory.setLoopResources(resource);
		factory.setResourceFactory(reactorResourceFactory);

this is how i created a seperate Loop resource to the NettyWebServerFactory. Is there any customization's required?

Is there a way to set max-concurrent streams and window_size in the HTTP2 Settings frame?.

**Comment by violetagg** [comment]
> Is there a way to set max-concurrent streams and window_size in the HTTP2 Settings frame?.

We use Netty defaults
max concurrent streams -  Integer.MAX_VALUE
initial window size - 65535

Is it possible for you to provide a reproducible example?

**Comment by violetagg** [comment]
@sukawanth You have many components involved in your scenario, without some small reproducible example we cannot proceed with the investigation. I'm closing this issue, we can reopen it when you provide more details.
