### ISSUE TITLE
Persistent HTTP connections

### ISSUE THREAD

**Issue by ek-ex** [reactor/reactor-netty#1158]
In AWS, I'm calling a service ELB behind a R53. I have updated the R53 entry to point to a new ELB after a new deployment, however is still calling the old service.

My thinking is that somehow, once it establishes the connection to the service, the connection is never renewed or expired, or there is a DNS caching configured somewhere?

If I halt momentarily the traffic, the connection will expire and re-create the connection, but as long as the connection is active is never expired.

I tried forcing a DNS TTL to java before starting springboot but no luck. 
`java.security.Security.setProperty("networkaddress.cache.ttl", "30");`

Is there any fix for this ? Maybe setting some TTL to the connections ?

**Comment by violetagg** [comment]
@ek-ex you can configure max life time for the connections in a connection pool
https://projectreactor.io/docs/netty/release/reference/index.html#_connection_pool

```
ConnectionProvider.builder("my-pool")
                  .maxLifeTime(Duration.ofMillis(60))
                  .build();
```

Use [Gitter](https://gitter.im/reactor/reactor-netty) or [StackOverflow](https://stackoverflow.com/questions/tagged/reactor-netty) for questions
