### ISSUE TITLE
Increasing number of open file descriptors

### ISSUE THREAD

**Issue by cpp03** [reactor/reactor-netty#1163]
Each HTTP request sent using _HttpClient_ opens a new file descriptor which seems to be never closed. This eventually causes `java.io.IOException: Too many open files in system`.

It might be related to: https://github.com/netty/netty/issues/9419.

## Expected Behavior

Resources are released when the are no longer needed.

## Actual Behavior

The number of created sockets increases with each HTTP request sent.

`lsof -p <pid>` command shows them as
```
...
java    <pid> user   36u     sock                0,9       0t0  543037 protocol: TCPv6
java    <pid> user   37u     sock                0,9       0t0  545115 protocol: TCPv6
java    <pid> user   38u     sock                0,9       0t0  545289 protocol: TCPv6
java    <pid> user   39u     sock                0,9       0t0  545293 protocol: TCPv6
...
```
They are not visible in `netstat`.

## Steps to Reproduce

Minimal reproducible example:
```java
package com.example.httpclienttest;

import com.sun.management.UnixOperatingSystemMXBean;
import reactor.netty.http.client.HttpClient;
import java.lang.management.ManagementFactory;

public class Main {
    public static void main(String[] args) throws InterruptedException {
        final var osMxBean = ManagementFactory.getOperatingSystemMXBean();

        if (!(osMxBean instanceof UnixOperatingSystemMXBean)) {
            System.err.println("Non-Unix OS");
            System.exit(1);
        }

        final var unixOsMxBean = (UnixOperatingSystemMXBean) osMxBean;

        for (int i = 0; i < 20; i++) {
            HttpClient.create()
                    .baseUrl("http://example.com")
                    .keepAlive(false)
                    .get()
                    .response()
                    .block();

            System.out.println("Number of open file descriptors: " + unixOsMxBean.getOpenFileDescriptorCount());

            Thread.sleep(2_500L);
        }
    }
}
```

## Your Environment

* Reactor version(s) used: 0.9.8.RELEASE
* Other relevant libraries versions: netty 4.1.50.Final
* JVM version: 11.0.7
* OS and version: Linux 5.4.0-37-generic

**Comment by violetagg** [comment]
@cpp03 Please try 0.9.9.BUILD-SNAPSHOT it might be this issue #1152

**Comment by cpp03** [comment]
@violetagg In the 0.9.9.BUILD-SNAPSHOT version the issue no longer occurs. Thank you!

**Comment by violetagg** [comment]
@cpp03 thanks for testing it.

Closing as a duplicate for #1152
