### ISSUE TITLE
HTTP client unable to specify which IP to bind to, please provide example and documentation

### ISSUE THREAD

**Issue by lfmunoz** [reactor/reactor-netty#1164]
Reactor Netty suppose to make using Netty easier but I cannot figure out how to bind different IP addresses to different HTTP clients which I would think it is a common thing to do. 

I am unable to find examples or documentation on this. 

I know that in regular Netty you usually do that with a bootstrap but with reactor I have no idea how to do because when you create a bootstrap you have to specify the handler and group not sure what to specify for that.

My initial guess is something like this, but I get errors about not setting group, handler etc, and not sure what to do for that
```
    fun newHttpClient(inetAddress: InetAddress): HttpClient {
        val provider = ConnectionProvider.newConnection()
        val tcpClient = TcpClient.create(provider).bootstrap { b ->
            // create a new bootstrap per ip address
            val bootstrap = b.clone()
            bootstrap.bind(InetSocketAddress(inetAddress, 0))
            bootstrap
        }
        return HttpClient.from(tcpClient)
    }
```

Please let me know the correct way of doing this and consider putting it in the documentation.

**Comment by violetagg** [comment]
@lfmunoz The way that you are using for specifying the bind address for the client is correct.
Would you like to contribute an example to the documentation?

**Comment by violetagg** [comment]
```
public static void main(String[] args) {
	ConnectionProvider provider = ConnectionProvider.newConnection();
	TcpClient tcpClient =
			TcpClient.create(provider)
					.bootstrap(b -> b.localAddress(new InetSocketAddress("host", port)));
	String response =
			HttpClient.from(tcpClient)
					.get()
					.uri("https://example.com")
					.responseContent()
					.aggregate()
					.asString()
					.block();
	System.out.println("Response " + response);
}
```

Not `bind`, but `localAddress`

**Comment by violetagg** [comment]
@lfmunoz Thanks for the PR. The change 160172f04cd2decc330427c2a2b8e10ddbec06fd was applied to 0.9.x branch and then forward merge to master
