### ISSUE TITLE
Trouble getting Webclient to work with SSL

### ISSUE THREAD

**Issue by marcbarb** [reactor/reactor-netty#1166]
The problem I'm having is similar to issue #640 and I used the code that @Violetagg used with JVM arguments for all my keystore and truststore parameters as well as the noOpenSsl=true flag, but I always get a bad certificate error.  I have tracked down with a breakpoint at line 861 of sun.security.ssl.ClientHandshaker in the serverHelloDone method that the sslContext.getX509KeyManager() returns a DummyX509KeyManager thus not returning any certificates and giving a "Warning: no suitable certificate found - continuing without client authentication" error in the network SSL debugging.  Calling the same server with an AsyncRestTemplate or a FeignClient returns a key manager and data from the server.  The ClientHandshaker code is in the openjdk for 1.8.  Any ideas?  I'm running:

Reactor Netty version
0.9.7.RELEASE

JVM version (e.g. java -version)
openjdk version "1.8.0_252"
OpenJDK Runtime Environment (build 1.8.0_252-8u252-b09-1~18.04-b09)
OpenJDK 64-Bit Server VM (build 25.252-b09, mixed mode)

OS version (e.g. uname -a)
Linux m2 4.15.3-041503-generic #201802120730 SMP Mon Feb 12 07:31:14 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by violetagg** [comment]
@marcbarb Is it possible that you face something similar #1102

**Comment by marcbarb** [comment]
No, I am using https.  Here is the code that calls a server created from the example at:

https://www.baeldung.com/x-509-authentication-in-spring-security

```
        String block = WebClient.builder()
                .clientConnector(new ReactorClientHttpConnector(
                        HttpClient.create()
                                .secure(spec -> spec.sslContext(SslContextBuilder.forClient()))))
                .build()
                .get()
                .uri("https://localhost:8443/user")
                .retrieve()
                .bodyToMono(String.class)
                .block();
```

**Comment by marcbarb** [comment]
To give more information, I do have a certificate installed for localhost.  I installed the certificate from the information at: https://www.baeldung.com/x-509-authentication-in-spring-security into the java truststore.  If I had not done that I don't think I could have had the server return data and things work by calling the same server with an AsyncRestTemplate.  The following code works for me while the above does not:
```
        AsyncRestTemplate a = new AsyncRestTemplate();
        ListenableFuture<ResponseEntity<String>> exchange = a.exchange("https://localhost:8443/user", 
                HttpMethod.GET, RequestEntity.EMPTY, String.class);
        ResponseEntity<String> block = exchange.get();
```

**Comment by marcbarb** [comment]
I am trying to access the site with a client certificate.  It seems that delegating the creation of the SSLContext to Netty loads the truststore, but not the key store.  If I load and add a keystore things work:

```
String keyStoreLocation = System.getProperty("javax.net.ssl.keyStore");
String keyStorePassword = System.getProperty("javax.net.ssl.keyStorePassword");

KeyStore keyStore = KeyStore.getInstance("JKS");
keyStore.load(new FileInputStream(ResourceUtils.getFile(keyStoreLocation)), keyStorePassword.toCharArray());

// Set up key manager factory to use our key store
KeyManagerFactory keyManagerFactory = KeyManagerFactory.getInstance(KeyManagerFactory.getDefaultAlgorithm());
keyManagerFactory.init(keyStore, keyStorePassword.toCharArray());

String block = WebClient.builder()
        .clientConnector(new ReactorClientHttpConnector(
                HttpClient.create()
                        .secure(spec -> spec.sslContext(SslContextBuilder.forClient()
                        .keyManager(keyManagerFactory)))))
        .build()
        .get()
        .uri("https://localhost:8443/user")
        .retrieve()
        .bodyToMono(String.class)
        .block();
```

**Comment by violetagg** [comment]
@marcbarb That's exactly what the author did in https://github.com/reactor/reactor-netty/issues/640#issuecomment-478738139, right?

Are we OK with this issue? Should I close it?

**Comment by marcbarb** [comment]
Not exactly.  He set a keystore and truststore.  I only had to set a keystore.  It looks like Netty sets the truststore.  It would have been nice if Netty set the keystore also, but I'm OK with closing this.

**Comment by gabac** [comment]
@violetagg Do you know why netty respects the JVM param for the trustStore but not for the keyStore and we have to manually configure this?

**Comment by violetagg** [comment]
@gabac Please use Netty support channels for Netty related questions.

**Comment by gabac** [comment]
@violetagg Sorry I was under the impression that this has to do with the webclient in combination with netty.

**Comment by marcbarb** [comment]
No, but i did see in the code that it does use the default trust store if
you don't supply one. There is no code to do the same thing with the key
store
