### ISSUE TITLE
`HttpClientException` can potentially leak buffers

### ISSUE THREAD

**Issue by simonbasle** [reactor/reactor-netty#118]
`HttpClientException` keeps a reference to the `HttpResponse` that it represents.

I think this might be problematic, especially in cases where the response is eg. a `DefaultFullHttpResponse`, which holds a `ByteBuf`.

My concern is that either the bytebuf is released by the handler and is thus unusable _or_ it is not released and thus should be released by the user, **which is deeply hidden by the exception** (you can technically release it but you need to think about calling `message()` on it then checking if it is a `ByteBufHolder`).

**Comment by smaldini** [comment]
We are no longer going to provide such exception as we plan to remove server/client error handling #182, let's track that in this one then.
