### ISSUE TITLE
SslHandshakeTimeoutException

### ISSUE THREAD

**Issue by lombook** [reactor/reactor-netty#1187]
reactor-netty-0.9.7.REALSE
springboot  2.3.0.REALSE

Is this a bug? Is there a solution?
try set work count , but it doesn't work. 
any reply will be appreciated. thanks.

Caused by: io.netty.handler.ssl.SslHandshakeTimeoutException: handshake timed out after 10000ms#012	at io.netty.handler.ssl.SslHandler$5.run(SslHandler.java:2054)

**Comment by violetagg** [comment]
@lombook You do not specify whether this is server or client, but let's say it is a client then look at the javadoc (10s is default)

https://projectreactor.io/docs/netty/release/api/reactor/netty/http/client/HttpClient.html#secure-java.util.function.Consumer-

You can either specify it via builder or system property.

```
.secure(ssl -> ssl.sslContext(sslClient).handshakeTimeoutMillis(...))
```
