### ISSUE TITLE
HttpClient with websocket can not pass Host Header since 0.9.7

### ISSUE THREAD

**Issue by gongmingbin** [reactor/reactor-netty#1194]
## Expected Behavior
httpClient pass Host Header to Sever
## Actual Behavior
httpClient lost Host Header since 0.9.7
## Steps to Reproduce

```java
 @Test(timeout = 10000)
  public void test() {
    DisposableServer disposableServer =
        HttpServer.create()
            .port(9999)
            .handle(
                (req, resp) -> {
                  String host = req.requestHeaders().get("Host");
                  if (host.equals("test.com")) { // Test Host
                    return resp.sendWebsocket(
                        (i, o) -> {
                          return o.sendClose();
                        });
                  } else {
                    return resp.status(404);
                  }
                })
            .bindNow();

    HttpClient httpClient = HttpClient.create();
    httpClient
        .headers(
            entries -> {
              entries.add("Host", "test.com");
              entries.add("aa", "bb");
            })
        .baseUrl("http://localhost:" + disposableServer.port())
        .websocket()
        .connect()
        .block();
  }

```
Run the test with 0.9.6.RELEASE, Test pass. But run the test with 0.9.7.RELEASE, Test failed!
## Your Environment

* Reactor version(s) used:
* Other relevant libraries versions (eg. `netty`, ...):
* JVM version (`javar -version`):
* OS and version (eg `uname -a`):

**Comment by violetagg** [comment]
@gongmingbin @Unthrottled We do not preserve the custom HOST header as a result of #1047
In addition to that we have this fix in Netty 4.1.48.Final https://github.com/netty/netty/issues/10101

I prepared a PR #1197 that fixes this issue and also keeps a correct behaviour for the issue from #1047.

PTAL

**Comment by violetagg** [comment]
As discussed in #1197 I'm going to revert #1047

**Comment by violetagg** [comment]
@gongmingbin Will you be able to verify the change? Please try 0.9.10.BUILD-SNAPSHOT.

**Comment by violetagg** [comment]
I'm closing this, if there is an issue with the revert we can reopen it.
