### ISSUE TITLE
Spring Cloud Gateway: Netty Byte Buff Leak Errors: ERROR io.netty.util.ResourceLeakDetector.reportTracedLeak - LEAK: ByteBuf.release() was not called

### ISSUE THREAD

**Issue by avijha19** [reactor/reactor-netty#1195]
I am getting 

```
29-06-2020 21:22:50.182 [lettuce-epollEventLoop-5-2] ERROR io.netty.util.ResourceLeakDetector.reportTracedLeak - LEAK: ByteBuf.release() was not called before it's garbage-collected. See https://netty.io/wiki/reference-counted-objects.html for more information.
Recent access records: 
Created at:
	io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:363)
	io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:187)
	io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:178)
	io.netty.channel.unix.PreferredDirectByteBufAllocator.ioBuffer(PreferredDirectByteBufAllocator.java:53)
	io.netty.channel.DefaultMaxMessagesRecvByteBufAllocator$MaxMessageHandle.allocate(DefaultMaxMessagesRecvByteBufAllocator.java:114)
	io.netty.channel.epoll.EpollRecvByteAllocatorHandle.allocate(EpollRecvByteAllocatorHandle.java:75)
	io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:777)
	io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:475)
	io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
	io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	java.lang.Thread.run(Thread.java:748)
```

## Expected Behavior
No leak
## Actual Behavior
Ecxception:
ERROR io.netty.util.ResourceLeakDetector.reportTracedLeak - LEAK: ByteBuf.release() was not called before it's garbage-collected. See https://netty.io/wiki/reference-counted-objects.html for more information.
Recent access records: 

## Steps to Reproduce
When I use Spring cloud Gateway filter  to log request and response.

Order of the filter is

Ordered.HIGHEST_PRECEDENCE + 1

```
GatewayServerHttpRequestDecorator requestDecorator = new GatewayServerHttpRequestDecorator(request);
			InetSocketAddress address = requestDecorator.getRemoteAddress();
			HttpMethod method = requestDecorator.getMethod();
			URI url = requestDecorator.getURI();
			HttpHeaders headers = requestDecorator.getHeaders();
			Flux<DataBuffer> requestDataBuffers = requestDecorator.getBody();
		
			AtomicReference<String> requestBody = new AtomicReference<>("");
			MultiValueMap<String, String> queryParams = requestDecorator.getDelegate().getQueryParams();
			requestDataBuffers.subscribe(requestDataBuffer -> {
				CharBuffer charBuffer = StandardCharsets.UTF_8.decode(requestDataBuffer.asByteBuffer());
				requestBody.set(charBuffer.toString());
				DataBufferUtils.release(requestDataBuffer);

			});

ServerHttpResponseDecorator responseDecorator = new ServerHttpResponseDecorator(response) {

				@Override
				public Mono<Void> writeWith(Publisher<? extends DataBuffer> responseDataBuffers) {

					if (responseDataBuffers instanceof Flux) {

						Flux<? extends DataBuffer> fluxBody = (Flux<? extends DataBuffer>) responseDataBuffers;
						return super.writeWith(fluxBody.map(responseDataBuffer -> {
							byte[] content = new byte[responseDataBuffer.readableByteCount()];
							responseDataBuffer.read(content);
							String responseBody = new String(content, Charset.forName("UTF-8"));
							if (!isInValidLogPath && (isValidLogPath || gatewayGlobalProperties.getLogServiceuris().contains(url.getPath()))) {
								logResMessage.append(requestId).append(LOG_RESPONSE_START)
										.append(LOG_RESPONSE_STATUS_CODE).append(this.getStatusCode())
										.append(LOG_RESPONSE_HEADERS).append(this.getHeaders())
										.append(LOG_RESPONSE_BODY).append(responseBody).append(LOG_RESPONSE_END);
								if (this.getStatusCode().is4xxClientError()
										|| this.getStatusCode().is5xxServerError()) {
									logger.error(logResMessage.toString());
								} else {
									logger.info(logResMessage.toString());
								}
							}
							 //org.springframework.web.reactive.function.client.DefaultClientResponse
							 DataBufferUtils.release(responseDataBuffer);
							return bufferFactory.wrap(content);
						}));
						
					} else {
						return super.writeWith(responseDataBuffers);

					}
				}

			};
```

## Possible Solution
I thought that I am not using //org.springframework.web.reactive.function.client.DefaultClientResponse
DataBufferUtils.release(responseDataBuffer);
But even after using that I am getting same error.
## Your Environment

* Reactor version(s) used:
* Other relevant libraries versions (eg. `netty`, ...):
Netty : 4.1.49, Spring Cloud : Hoxton.SR5
* JVM version (`javar -version`):1.8
* OS and version (eg `uname -a`):

**Comment by violetagg** [comment]
@avijha19 So your main goal is to log the request/response? Do you have some special requirement for that or you can use  what Spring Gateway provides? See the documentation:
https://cloud.spring.io/spring-cloud-gateway/reference/html/#wiretap

**Comment by avijha19** [comment]
Yes I can use that, but we have some custom requirement, where based on path pattern, we don't have to log, so wanted to use custom global filter. Please confirm. Can I release databuffer at the same time when i read that

```
AtomicReference<String> requestBody = new AtomicReference<>("");
			MultiValueMap<String, String> queryParams = requestDecorator.getDelegate().getQueryParams();
			requestDataBuffers.subscribe(requestDataBuffer -> {
				CharBuffer charBuffer = StandardCharsets.UTF_8.decode(requestDataBuffer.asByteBuffer());
				requestBody.set(charBuffer.toString());
				DataBufferUtils.release(requestDataBuffer);

			});
```
Response Buffer

```
ServerHttpResponse response = exchange.getResponse();

			DataBufferFactory bufferFactory = response.bufferFactory();	

			ServerHttpResponseDecorator responseDecorator = new ServerHttpResponseDecorator(response) {

				@Override
				public Mono<Void> writeWith(Publisher<? extends DataBuffer> responseDataBuffers) {

					if (responseDataBuffers instanceof Flux) {

						Flux<? extends DataBuffer> fluxBody = (Flux<? extends DataBuffer>) responseDataBuffers;
						return super.writeWith(fluxBody.map(responseDataBuffer -> {
							byte[] content = new byte[responseDataBuffer.readableByteCount()];
							responseDataBuffer.read(content);
							String responseBody = new String(content, Charset.forName("UTF-8"));
							if (!isInValidLogPath && (isValidLogPath || gatewayGlobalProperties.getLogServiceuris().contains(url.getPath()))) {
								logResMessage.append(requestId).append(LOG_RESPONSE_START)
										.append(LOG_RESPONSE_STATUS_CODE).append(this.getStatusCode())
										.append(LOG_RESPONSE_HEADERS).append(this.getHeaders())
										.append(LOG_RESPONSE_BODY).append(responseBody).append(LOG_RESPONSE_END);
								if (this.getStatusCode().is4xxClientError()
										|| this.getStatusCode().is5xxServerError()) {
									logger.error(logResMessage.toString());
								} else {
									logger.info(logResMessage.toString());
								}
							}
							 //org.springframework.web.reactive.function.client.DefaultClientResponse
							 DataBufferUtils.release(responseDataBuffer);
							return bufferFactory.wrap(content);
						}));
						
					} else {
						return super.writeWith(responseDataBuffers);

					}
				}

			};
```

**Comment by avijha19** [comment]
Any way when I used 
logging.level.reactor.netty=TRACE


```
spring.cloud.gateway.httpserver.wiretap=true
spring.cloud.gateway.httpclient.wiretap=true
```

I got `2020-07-08 12:52:22.788 TRACE [,,,] 40212 --- [ctor-http-nio-3] reactor.netty.channel.ChannelOperations  : [id: 0xf3471aeb, L:/0:0:0:0:0:0:0:1:8082 - R:/0:0:0:0:0:0:0:1:57468] Disposing ChannelOperation from a channel

java.lang.Exception: ChannelOperation terminal stack
	at reactor.netty.channel.ChannelOperations.terminate(ChannelOperations.java:415)
	at reactor.netty.http.server.HttpServerOperations.cleanHandlerTerminate(HttpServerOperations.java:561)`

**Comment by avijha19** [comment]
Actually following works
```
logging.level.reactor.netty=DEBUG 
spring.cloud.gateway.httpserver.wiretap=true
spring.cloud.gateway.httpclient.wiretap=true
```
but still want to use the global filter

**Comment by avijha19** [comment]
@violetagg as mentioned in https://github.com/reactor/reactor-netty/issues/1178, we might have issue in 0.9.8 of netty so now using 0.9.9 version....

**Comment by violetagg** [comment]
@avijha19 I commented in Spring Gateway issue as I think this one here is related more to your usage of the Spring Gateway functionality.

**Comment by avijha19** [comment]
Thanks @violetagg

**Comment by skorhone** [comment]
There's just so many issues with this code. Trash it, there's nothing useful in it. I just recently spent a day and a half writing algorithm for capturing request and response contents. I have background in writing extremely scalable applications and I still found task very difficult (reactor is fairly new to me, but events and threading I've used for ovee two decades). We had requirements that couldn't be filled with default gateway components: capturing up to X bytes and delaying request/response until logged. I actually posted on stackoverflow about it

Your current implementation will corrupt request and produce multiple log entries for each response. It might just work locally with small responses.

There's reasonably good implementations with spring cloud gateway for capturing body as string - use them. Trust me, you don't want to spend weeks testing your code for corner cases - or have random errors in your production

**Comment by avijha19** [comment]
@skorhone, thanks for the feedback, till now its working good in my local except the exception, could you please share the other default implementation to capture request response as string as you have mentioned for spring cloud gateway. Thanks in advance.

**Comment by skorhone** [comment]
@avijha19 Read: https://cloud.spring.io/spring-cloud-static/spring-cloud-gateway/2.1.0.RELEASE/single/spring-cloud-gateway.html#_modify_request_body_gatewayfilter_factory

This filter converts request body to e.g string. It passes that string to a callback that you need to define. From callback you return whatever you want to pass upstream. If you don't wish to modify content, return Mono.just() with then string you got.

There's similar filter for response.

And if your logging is async, you can do something like: return log(ex, s).then(Mono.just(s))

**Comment by violetagg** [comment]
I think this whole discussion should be moved in SCG issue as there SCG maintainers can help better.
Wdyt?

**Comment by violetagg** [comment]
@avijha19 I'm closing this. If Reactor Netty problem is discovered we can reopen it.
