### ISSUE TITLE
Missing dependency reactor.util.retry.Retry in v0.9.8.RELEASE and later

### ISSUE THREAD

**Issue by HrFlorianHoffmann** [reactor/reactor-netty#1207]
We observed a seeming regression error when upgrading from Spring Boot 2.2.7.RELEASE to 2.2.8.RELEASE, and thereby from [reactor-netty v0.9.7.RELEASE to v0.9.8.RELEASE](https://github.com/reactor/reactor-netty/compare/v0.9.7.RELEASE...v0.9.8.RELEASE).

After the upgrade, specific Spring integration tests fail with a `NoClassDefFound` runtime error, caused by the dependency `reactor.util.retry.Retry` not being available to `reactor.netty.http.client.HttpClientConnect`.

Could you kindly verify whether the released versions v0.9.8.RELEASE and v0.9.9.RELEASE contain the required dependency, and if not, provide a fix?

**Comment by violetagg** [comment]
@HrFlorianHoffmann please use release `0.9.9` as there is a problem with opened FDs in `0.9.8`
About the dependency please update Reactor Core to the latest version.
You can do this easily with updating `reactor-bom` to `Dysprosium-SR9` thus you will update both Reactor Netty and Reactor Core to the latest releases

**Comment by HrFlorianHoffmann** [comment]
Thanks for the info, @violetagg!

Looks like Spring doesn't use `reactor-bom` but includes the parts individually:

```
[INFO] --- maven-dependency-plugin:3.1.2:tree (default-cli) @ automatedprocedures-srv ---
[INFO] com.sap.grc.automatedprocedures:automatedprocedures-srv:jar:0.0.1-SNAPSHOT
[INFO] ...
[INFO] +- org.springframework.boot:spring-boot-starter-webflux:jar:2.2.8.RELEASE:compile
[INFO] |  +- org.springframework.boot:spring-boot-starter-reactor-netty:jar:2.2.8.RELEASE:compile
[INFO] |  |  +- io.projectreactor.netty:reactor-netty:jar:0.9.7.RELEASE:compile
[INFO] |  |  |  +- io.netty:netty-codec-http2:jar:4.1.50.Final:compile
[INFO] |  |  |  +- io.netty:netty-handler:jar:4.1.50.Final:compile
[INFO] |  |  |  |  \- io.netty:netty-resolver:jar:4.1.50.Final:compile
[INFO] |  |  |  +- io.netty:netty-handler-proxy:jar:4.1.50.Final:compile
[INFO] |  |  |  |  \- io.netty:netty-codec-socks:jar:4.1.50.Final:compile
[INFO] |  |  |  \- io.netty:netty-transport-native-epoll:jar:linux-x86_64:4.1.50.Final:compile
[INFO] |  |  |     \- io.netty:netty-transport-native-unix-common:jar:4.1.50.Final:compile
[INFO] ...
[INFO] \- io.projectreactor:reactor-core:jar:3.3.0.RELEASE:compile
[INFO]    \- org.reactivestreams:reactive-streams:jar:1.0.3:compile
```

I'll check in with them.

**Comment by violetagg** [comment]
@HrFlorianHoffmann that's interesting

https://github.com/spring-projects/spring-framework/blob/5.2.x/build.gradle#L31

**Comment by HrFlorianHoffmann** [comment]
So they are using the reactor-bom, but the repackaging reduces the dependency tree to the effectively used libraries and thus hides that fact. Your link points to Spring Boot 2.3.x, by the way. Ours is 2.2.x, which still uses Maven instead of Gradle. But looks like the upgrade to Dysprosium-SR9 [has already been accounted for](https://github.com/spring-projects/spring-boot/blob/9558779dd411f02a471a9a8b61f5da5960b90a02/spring-boot-project/spring-boot-dependencies/pom.xml#L176). This was done 14 days ago, after their [v2.2.8.RELEASE](https://github.com/spring-projects/spring-boot/tree/v2.2.8.RELEASE), so I guess all we have to do is wait for v2.2.9.RELEASE. 😄

**Comment by violetagg** [comment]
@HrFlorianHoffmann You can easily update to the BOM even as of today if you use the dependency management that Spring Boot provide. It's just one property to your pom.xml file

```
<properties>
	<reactor-bom.version>Dysprosium-SR9</reactor-bom.version>
</properties>
```
