### ISSUE TITLE
Allow for a Pluggable HTTP Proxy Handling Function

### ISSUE THREAD

**Issue by alzimmermsft** [reactor/reactor-netty#1213]
I have a requirement to support both Basic and Digest authentication when using an HTTP proxy. The `HttpProxyHandler` provided by Reactor Netty only supports Basic authentication. In order to support Digest authentication I'm required to create a custom `ProxyHandler`/`ChannelDuplexHandler` implementation and hook it into the correct location in the pipeline.

## Motivation

Adding support for additional proxy authentication schemes is more difficult than expected.

## Desired solution

Allow for a `Supplier` or `Function` to be passed into `HttpProxyHandler` that would handle generating the `Proxy-Authorization` header on a per call basis.

## Considered alternatives

Allow for `ProxyProvider` to pick up on additional `ProxyHandler` sub classes when `ProxyProvider.newProxyHandler` is invoked.

**Comment by violetagg** [comment]
@alzimmermsft Can't you use the API for providing `Consumer<HttpHeaders>`?
https://projectreactor.io/docs/netty/release/api/reactor/netty/tcp/ProxyProvider.Builder.html#httpHeaders-java.util.function.Consumer-
Here is a test that uses this functionality
https://github.com/reactor/reactor-netty/blob/858870723821c31a2430201b328eb8b1b3d81951/src/test/java/reactor/netty/tcp/ProxyProviderTest.java#L207-L214

**Comment by alzimmermsft** [comment]
I'll try this out, one issue I'm seeing with this route is the requirement to update the `Proxy-Authorization` header when the proxy requires Digest authentication to be recalculated. Though I'm not certain if that scenario warrants a new TCP connection and SSL session.

**Comment by violetagg** [comment]
@alzimmermsft We use it as a Supplier so we should invoke `get()` when we create a new proxy handler.
https://github.com/reactor/reactor-netty/blob/858870723821c31a2430201b328eb8b1b3d81951/src/main/java/reactor/netty/tcp/ProxyProvider.java#L372-L379

**Comment by alzimmermsft** [comment]
Finished my investigation, this solution would work, thank you for the quick responses @violetagg.
