### ISSUE TITLE
Default client ConnectionProvider pool does not respect system variable reactor.netty.pool.maxConnections

### ISSUE THREAD

**Issue by jonnysco** [reactor/reactor-netty#1222]
## Expected Behavior

When the system variable `-Dreactor.netty.pool.maxConnections=777` is supplied to the jvm the default client connection pool should respect the setting provided if it is greater than the default `500`. This only occurs if the `HttpClient.client()` builder is invoked without specifying a `ConfigurationProvider` instance.

## Actual Behavior
The default pool is always 500 max connections.

## Steps to Reproduce

1. Add `systemProperty("reactor.netty.pool.maxConnections", "777")` to `build.gradle` under `project.tasks.withType(Test).all {}`
1. Run this test `reactor.netty.http.client.HttpClientTest#simpleTestHttps`
1. Check logs for `maxConnections`, observe equals 500, not 777.

## Possible Solution

```
Index: src/main/java/reactor/netty/tcp/TcpResources.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- src/main/java/reactor/netty/tcp/TcpResources.java	(revision 24864fbcee726d5f4647bd6e4d225c3bc7a88920)
+++ src/main/java/reactor/netty/tcp/TcpResources.java	(date 1595597861120)
@@ -295,7 +295,7 @@
 			BiFunction<LoopResources, ConnectionProvider, T> onNew) {
 		if (previous == null) {
 			loops = loops == null ? LoopResources.create("reactor-" + name) : loops;
-			provider = provider == null ? ConnectionProvider.create(name, 500) : provider;
+			provider = provider == null ? ConnectionProvider.create(name, Math.max(500, DEFAULT_POOL_MAX_CONNECTIONS)) : provider;
 		}
 		else {
 			loops = loops == null ? previous.defaultLoops : loops;

```

## Your Environment

Reproduced using reactor-netty master as described above.
First experienced this using Spring Boot WebFlux following the webclient configuration example, which does trigger the code 
path which results in calling `HttpClient.create()` as per this issue.

* Reactor version(s) used: commit `24864fbcee726d5f4647bd6e4d225c3bc7a88920`
* Other relevant libraries versions (eg. `netty`, ...):
* JVM version (`javar -version`): openjdk version "11.0.7"
* OS and version (eg `uname -a`): 4.15.0-111-generic #112-Ubuntu SMP Thu Jul 9 20:32:34 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by violetagg** [comment]
@jonnysco This works as expected and it is documented here
https://projectreactor.io/docs/netty/release/reference/index.html#_connection_pool

`DEFAULT_POOL_MAX_CONNECTIONS` is taken into consideration only if the ConnectionProvider builder does not specify maxConnections.
https://github.com/reactor/reactor-netty/blob/24864fbcee726d5f4647bd6e4d225c3bc7a88920/src/main/java/reactor/netty/resources/ConnectionProvider.java#L270

If you want a different connection pool configurations you can easily provide such using `ReactorResourceFactory`
https://docs.spring.io/spring/docs/current/spring-framework-reference/web-reactive.html#webflux-client-builder-reactor-resources

**Comment by jonnysco** [comment]
@violetagg 
The document does specify the default of 500 using a "fixed" pool, not that the 500 specifically is immutable. It can be overridden by code using the ConnectionProvider builders (which do respect `reactor.netty.pool.maxConnections`), but not through configuration.

E.g. Setting the following system variables should be expected to override the pool defaults.
```
systemProperty("reactor.netty.pool.maxConnections", "777")
systemProperty("reactor.netty.pool.acquireTimeout", "888")
```

I'd expect the following 3 examples to result in the same pool configuration of 777 maxConnections and 888 acquireTimeout.
```
// the minimal configuration, also the default in Spring Boot examples.
StepVerifier.create(HttpClient.create()
			    .get()
			    .uri("https://example.com")
			    .response((r, buf) -> Mono.just(r.status().code())))
		            .expectNextMatches(status -> status >= 200 && status < 400)
		            .expectComplete()
		            .verify();
// the minimal configuration supplying a ConnectionProvider instance allowing the builder to set up the pool defaults.
		StepVerifier.create(HttpClient.create(ConnectionProvider.builder("cliA").build())
				.get()
				.uri("https://example.com")
				.response((r, buf) -> Mono.just(r.status().code())))
				.expectNextMatches(status -> status >= 200 && status < 400)
				.expectComplete()
				.verify();
// the minimal configuration supplying a ConnectionProvider instance allowing the builder to set up the pool defaults (using create wrapper).
		StepVerifier.create(HttpClient.create(ConnectionProvider.create("cliB"))
				.get()
				.uri("https://example.com")
				.response((r, buf) -> Mono.just(r.status().code())))
				.expectNextMatches(status -> status >= 200 && status < 400)
				.expectComplete()
				.verify();
```
Results in:
```
10:18:33.191 [Test worker] DEBUG r.n.r.PooledConnectionProvider - Creating a new [http] client pool [PoolFactory{leasingStrategy=fifo, maxConnections=500, maxIdleTime=-1, maxLifeTime=-1, metricsEnabled=false, pendingAcquireMaxCount=1000, pendingAcquireTimeout=888}] for [example.com:443]
10:18:33.962 [Test worker] DEBUG r.n.r.PooledConnectionProvider - Creating a new [cliA] client pool [PoolFactory{leasingStrategy=fifo, maxConnections=777, maxIdleTime=-1, maxLifeTime=-1, metricsEnabled=false, pendingAcquireMaxCount=1554, pendingAcquireTimeout=888}] for [example.com:443]
10:18:34.310 [Test worker] DEBUG r.n.r.PooledConnectionProvider - Creating a new [cliB] client pool [PoolFactory{leasingStrategy=fifo, maxConnections=777, maxIdleTime=-1, maxLifeTime=-1, metricsEnabled=false, pendingAcquireMaxCount=500, pendingAcquireTimeout=888}] for [example.com:443]
```
The `maxConnections` remains 500 in the default pool, but it does allow the `pendingAcquireTimeout` to be set via system var.

**Comment by violetagg** [comment]
@jonnysco Users have different requirements for the default implementation: some of them want the system property to be applied only if it is bigger than the default setting (500 max connections), other - to apply system property always when it exists, etc.

Because of that Reactor Netty provides one default that is not controlled by the system property and in addition gives the possibility to configure the connection pool per client or globally.

The examples (that you gave above) are per client, but you can also do the following:

`HttpResources.set(ConnectionProvider.create("mypool"));`

Using this approach you instruct Reactor Netty that the pool is `global` and max connections property is controlled by the system property.

**Comment by jonnysco** [comment]
@violetagg Thanks that explains the motivations behind it. (The PR changes the behaviour to be as you describe in your first user scenario, but the second is always ignored under the default config).

Coming at the netty client config from the Spring Boot examples as a "correct setup" for a single client instance, it falls into this tar pit of the fixed immutable 500 cap.

In prod deploys it's not uncommon users will find it easier to add config, than add code changes. It doesn't seem clear from the documentation that the CLI var would _not_ work only under this absolute default configuration, but all other CLI vars do.  Maybe just a documentation thing (possibly Spring Boot)?

**Comment by violetagg** [comment]
@jonnysco Would you like to provide a PR to the documentation?

For Spring Boot you can use `ReactorResourceFactory` to Reactor Netty resources.

**Comment by violetagg** [comment]
@jonnysco I updated the documentation https://projectreactor.io/docs/netty/snapshot/reference/index.html#_connection_pool

**Comment by PyAntony** [comment]
Hi,

I've been trying to understand (for days) the distinction between "connection pool", which defaults to 500, and "maxConnections", which defaults to 2 * N processors. I thought I understood, but after reading this thread clearly I don't. Can someone please explain the difference to me?

Documentation states a max connection pool of 500, with up to 1000 connections in "pending" state. then it says that "maxConnections" defaults to 2 * N processors??? I thought these 2 concepts were different, but reading through this thread it seems like connection pool and "maxConnections" is the same thing? please explain.

**Comment by violetagg** [comment]
> Hi,
> 
> I've been trying to understand (for days) the distinction between "connection pool", which defaults to 500, and "maxConnections", which defaults to 2 * N processors. I thought I understood, but after reading this thread clearly I don't. Can someone please explain the difference to me?
> 
> Documentation states a max connection pool of 500, with up to 1000 connections in "pending" state. then it says that "maxConnections" defaults to 2 * N processors??? I thought these 2 concepts were different, but reading through this thread it seems like connection pool and "maxConnections" is the same thing? please explain.
> 
> (Also asked on #2052)

I replied here
https://github.com/reactor/reactor-netty/issues/2052#issuecomment-1048586578

**Comment by im-abhijit** [comment]
@violetagg why there is no option to configure minimum no of connections in connection pool

**Comment by violetagg** [comment]
@im-abhijit Please do not use closed issues for discussions. Bring the discussion to [Gitter](https://gitter.im/reactor/reactor-netty) or as an enhancement request.
