### ISSUE TITLE
Misleading statement about Gradle support for Maven BOMs

### ISSUE THREAD

**Issue by asarkar** [reactor/reactor-netty#1223]
"Gradle has no core support for Maven BOMs"
https://projectreactor.io/docs/netty/release/reference/index.html#_gradle_installation

This hasn't been true since Gradle 5, which was released in Nov, 2018.

```
implementation(platform("io.projectreactor:reactor-bom:Dysprosium-SR10"))
```

**Comment by violetagg** [comment]
@asarkar Would you like to make a PR?

**Comment by asarkar** [comment]
@violetagg Sorry, not at this time.

**Comment by violetagg** [comment]
> @violetagg Sorry, not at this time.

OK no problem.

**Comment by violetagg** [comment]
@asarkar @simonbasle PTAL #1229
