### ISSUE TITLE
Disposing PooledConnections that are not actively used under LRU policy.

### ISSUE THREAD

**Issue by jun-lee** [reactor/reactor-netty#1230]
## Motivation

My application is using **HttpClient** to access a massive number of endpoints to provide a **Link Preview** service. Over time, Netty-related resources are taking a lot of memory as shown below. Mostly by the PooledConnections, they have never been destroyed once they have been initialized for a unique endpoint with the InetSocketAddress as a key, and redundant data like HeaderEntity, DefaultAttribute in each config of the pool.

<img width="1233" alt="스크린샷 2020-07-29 오전 11 53 24" src="https://user-images.githubusercontent.com/12035676/88767519-f0ea9000-d1a3-11ea-84ce-d61cee6efef1.png">

## Desired solution

Could we have an LRU mechanism to release the old PooledConnections which are not actively reused?

**Comment by violetagg** [comment]
@jun-lee Do you think that this feature request will serve your requirement?
https://github.com/reactor/reactor-pool/issues/86

For which version do you need this feature: 0.9.x or 1.0.0?

/cc @simonbasle

**Comment by jun-lee** [comment]
@violetagg Thanks for the link. Yes, that's exactly what I'm expecting. And I'm using 1.0.0-M1 because of the Multi Content-Length issues.

**Comment by violetagg** [comment]
@jun-lee Multi Content-Length issues?

**Comment by jun-lee** [comment]
@violetagg this one https://github.com/netty/netty/pull/10349

**Comment by violetagg** [comment]
@jun-lee all Reactor Netty releases depend on the latest released Netty version at that point of the release.
So 0.8.20 and 0.9.10 releases use 4.1.51.Final
https://github.com/reactor/reactor-netty/releases/tag/v0.9.10.RELEASE
https://github.com/reactor/reactor-netty/releases/tag/v0.8.20.RELEASE

**Comment by jun-lee** [comment]
@violetagg Sorry, after checking my code again. This is not related to 1.0.0-M1, but somehow, I was using spring boot 2.4.0-M1, therefore, 1.0.0-M1 was used.

**Comment by violetagg** [comment]
@jun-lee Ok so we are targeting 1.0.0? I need this in order to be able to fix the version where this feature request is needed.

**Comment by jun-lee** [comment]
@violetagg Yes, we are.

**Comment by violetagg** [comment]
This is depending on reactor/reactor-pool#86
