### ISSUE TITLE
websocket broadcast

### ISSUE THREAD

**Issue by yn425611317** [reactor/reactor-netty#1263]
Does reactor-netty have a websocket broadcast api? In netty, there is a DefaultChannelGroup.writeAndFlush() method sent to each socketchannel.

**Comment by violetagg** [comment]
@yn425611317 No
For questions use [Gitter](https://gitter.im/reactor/reactor-netty) or [stackoverflow.com](https://stackoverflow.com/questions/tagged/reactor-netty)
