### ISSUE TITLE
Expose also the oritinal request in redirect request consumer

### ISSUE THREAD

**Issue by peterjurkovic** [reactor/reactor-netty#1265]
The current behavior of the client is when a follow-redirect is enabled and the `hostname` changes, sensitive headers like `Authorization` or `Cookie` are being stripped. Witch makes sense from a security point of view. However there is a couple of use-cases when an application needs to re-inject them. With the current client is almost not possible.

## Current solution
There is an option to pass `redirectRequestConsumer` where is possible to set stripped headers, however there is not way to access the original request. 

## Desired solution
Be able to access the original, previous request.

1. One option would be introducing new method `List<Reqeusts> request.redirectedFromRequests()` 
2. Using `BiConsumer<HttpClientRequest, HttpClientRequest>`  (originalRequest, newRequest)
3. Or any other solutions which allows to do that.

**Comment by violetagg** [comment]
@peterjurkovic `Using BiConsumer<HttpClientRequest, HttpClientRequest> (originalRequest, newRequest)` you need the original or previous request?

**Comment by peterjurkovic** [comment]
> Using BiConsumer<HttpClientRequest, HttpClientRequest> (originalRequest, newRequest) you need the original or previous request?

whatever is easier, both would resolve this issue :+1: 

> Or for example we may expose Using BiConsumer<HttpHeaders, HttpClientRequest> (defaultHeaders, newRequest)

Yep, this would also fine :+1:

**Comment by istibekesi** [comment]
@violetagg Is there a way to control this for incoming cookies, set by the response headers? 
What if the response is a redirect with an extra `set-cookie` in the response header. In this case, I would like to have that cookie included in the subsequent request. As far as I see the `redirectRequestBiConsumer`, it exposes the request headers... not the response. 
Am I missing something?

**Comment by violetagg** [comment]
@istibekesi You don't have direct access to response headers. You need to store this information somehow on your own.
You can use either 

https://projectreactor.io/docs/netty/release/api/reactor/netty/http/client/HttpClient.html#followRedirect-java.util.function.BiPredicate-java.util.function.BiConsumer-

or

https://projectreactor.io/docs/netty/release/api/reactor/netty/http/client/HttpClient.html#doOnRedirect-java.util.function.BiConsumer-

**Comment by istibekesi** [comment]
@violetagg 
I would like to have a conditional followRedirect configuration that handles cookies on the redirect(s). So I’ve tried something like this:
```
                    final Map<CharSequence, Set<Cookie>> cookieJar = new HashMap<>();
                    HttpClient
                        .create()
                        .doOnRequest(
                            (req, c) -> myCookieJar.values().stream().flatMap(Collection::stream).forEach(req::addCookie)
                        )
                        .followRedirect(
                            (req, res) -> {
                               // ...
                            },
                            (headers, redirect) ->
                                myCookieJar.values().stream().flatMap(Collection::stream).forEach(redirect::addCookie)
                        )
                        .doOnRedirect((res, conn) -> myCookieJar.putAll(res.cookies()))
                        .doOnResponse((res, conn) -> myCookieJar.putAll(res.cookies()))
```

The above solution does not seem nice, but it seemed to work on 1.0.34. However, the cookies are not added to the request as I expected on 1.1.14.
Any help or guidance on this issue is highly appreciated.

**Comment by istibekesi** [comment]
@violetagg 

I wrote a test for this to reproduce and it seems the behavior has been changed somewhere between `1.0.x` and `1.1.x`.
I've also opened a new [bug](https://github.com/reactor/reactor-netty/issues/3035) for this issue.
