### ISSUE TITLE
java.lang.VerifyError: class reactor.ipc.netty.http.client.MonoHttpClientResponse overrides final method subscribe.(Lorg/reactivestreams/Subscriber;)V

### ISSUE THREAD

**Issue by HarshaVardhanAcharyAthaluri** [reactor/reactor-netty#1271]
`
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-webflux</artifactId>
			<exclusions>
				<exclusion>
					<artifactId>spring-boot-starter-reactor-netty</artifactId>
					<groupId>org.springframework.boot</groupId>
				</exclusion>
			</exclusions>
		</dependency>`

`

`

**Comment by violetagg** [comment]
@HarshaVardhanAcharyAthaluri Please specify Reactor Core version and Reactor Netty version.

**Comment by HarshaVardhanAcharyAthaluri** [comment]
spring-boot-starter-reactor-netty-2.2.2.RELEASE

**Comment by HarshaVardhanAcharyAthaluri** [comment]
spring-boot-starter-reactor-netty-2.2.2.RELEASE

internally using 
reactor-netty  - 0.9.2.RELEASE as a compile time dependency

**Comment by violetagg** [comment]
@HarshaVardhanAcharyAthaluri you have some dependency mismatch because this package `reactor.ipc.netty` was used till 0.7.x version and we changed it to `reactor.netty` with version 0.8.x

**Comment by violetagg** [comment]
@HarshaVardhanAcharyAthaluri Were you able to resolve the dependency mismatch?

**Comment by HarshaVardhanAcharyAthaluri** [comment]
Yes @violetagg thank you so much for your help

**Comment by violetagg** [comment]
@HarshaVardhanAcharyAthaluri OK, closing this one
