### ISSUE TITLE
Unix Domain Sockets work in 1.0.0-M1 but not in 0.9.11.RELEASE

### ISSUE THREAD

**Issue by shs96c** [reactor/reactor-netty#1272]
When obtaining an M1 snapshot of `reactor-netty` from https://repo.spring.io/libs-snapshot, connecting using a `DomainSocketAddress` works fine. The same code with the latest public version of `reactor-netty` (0.9.11.RELEASE as I write this) throws an exception.

Example code:

```java
SocketAddress domainAddr = new DomainSocketAddress("/var/run/docker.sock");

HttpClient client = HttpClient.create()
      .followRedirect(true)
      .keepAlive(true)
      .remoteAddress(() -> domainAddr);
```

## Expected Behavior
Connecting using a unix domain socket should be fine.

## Actual Behavior
An exception is thrown by the 0.9.11.RELEASE:

```
reactor.core.Exceptions$ReactiveException: io.netty.channel.AbstractChannel$AnnotatedConnectException: connect(..) failed: Address family not supported by protocol family: /var/run/docker.sock
	at reactor.core.Exceptions.propagate(Exceptions.java:393)
	at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:97)
	at reactor.core.publisher.Mono.block(Mono.java:1680)
```

## Possible Solution
Presumably there's a patch in the snapshot that could/should be merged into the mainline.

## Your Environment
macOS Catalina
OpenJDK 11
io.projectreactor:reactor-core:3.3.9.RELEASE
io.projectreactor.netty:reactor-netty:0.9.11.RELEASE
Netty vesion: 4.1.51.Final

Looking at the dates in the maven repos, M1 shipped on `2020-06-22` and 0.9.11.RELEASE shipped on `2020-08-10`

**Comment by violetagg** [comment]
Unfortunately the implementation comes with backwards incompatible changes and I do not see how we can backport this to the released versions
our RC1 is the next month so the release of the new functionality is not far away
