### ISSUE TITLE
POST body intermittently not sent

### ISSUE THREAD

**Issue by agilekevin** [reactor/reactor-netty#1302]
About 2% of the time, POST requests do not send their body.

I'm using reactor-netty within Spring Cloud Gateway to modify headers and proxy requests to downstream services.  I do not inspect or attempt to modify the body in any way.

The body is very small, 5-10 lines of xml.

I've verified by the wiretap tracing that the body arrives successfully TO the gateway in the case where it is not sent.

I have reactor-netty wiretap logs blow for what I think is a channel Id that has first a successful interaction, then a failed one.

## Expected Behavior
The body is sent downstream

## Actual Behavior
The body is omitted, and the connection is closed prematurely.  Downstream service reports an IO error "connection closed before all body content could be read". A pcap shows that no body is sent.

## Possible cause
I notice INACTIVE/CLOSE events in the log during the failing interaction.  They all happen at the same millisecond as the rest of the data, so it doesn't seem like it could be a timeout.

### Failed request logs
All at timestamp 4:24:30.257
```
[id: 0x457bdbeb, - ] onStateChange(POST{}, [request_prepared])
[id: 0x457bdbeb, - ] CLOSE
[id: 0x457bdbeb, - ] FLUSH
[id: 0x457bdbeb, - ] WRITE: 1091B (body redacted, this WRITE has headers only, as first WRITE above)
[id: 0x457bdbeb, - ] Channel acquired, now 7 active connections and 39 inactive connections
[id: 0x457bdbeb, ! ] INACTIVE
[id: 0x457bdbeb, ! ] onStateChange(POST{}, [disconnecting])
[id: 0x457bdbeb, ! ] Channel closed, now 6 active connections and 39 inactive connections
[id: 0x457bdbeb, ! ] CLOSE
[id: 0x457bdbeb, - ] Handler is being applied: {… method=POST}
[id: 0x457bdbeb, ! ] UNREGISTERED
```

## Environment

* Reactor version(s) used:  0.9.11
* spring boot 2.3.3
* spring cloud gateway 2.2.2
* JVM version (`java -version`): openjdk 11
* OS and version (eg. `uname -a`): container openjdk:11-jre-slim

**Comment by agilekevin** [comment]
I should add that this behavior is consistent across multiple downstream services, so I don't think it's the service rejecting the connection, etc.

The downstream service reports a pretty consistent error: IOException connection closed before body could be read (UT000128)

**Comment by agilekevin** [comment]
Also, the packet capture shows the first packet above, and the downstream service replies with `ack`, and the `ack` is ack'd.  Then my service even sends a `fin` which gets `fin ack`'d.  So I don't think it's something outside the system closing the connection.

**Comment by violetagg** [comment]
@agilekevin Is it possible to provide a reproducible example. I tried with very simple POST, but I do not see issues.

**Comment by agilekevin** [comment]
The problem doesn't occur with simple requests, just at load.  And no, I haven't put together a load test for it.

I see the problem across several services.  I looked for special characters in the body as a potential issue, but found none.

We did change from Spring Cloud Gateway to Ambassador, running on the same k8s cluster, which makes the issue go away.  That (plus the pcaps) I think does a good job of eliminating Azure networking as the root cause, further focusing on Spring Cloud Gateway and Reactor-Netty.

**Comment by violetagg** [comment]
@agilekevin I'm not able to reproduce this behaviour. If you are able to provide a reproducible example, we can reopen the issue.

**Comment by abelyliu** [comment]
I have the same problem，use below code can recurring problems
https://github.com/abelyliu/spring-gateway-demo
@violetagg 
I tried the following two environments
Darwin 1s-iMac.local 20.5.0 Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64 x86_64
Linux fedora 5.13.8-200.fc34.x86_64 #1 SMP Wed Aug 4 19:59:54 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by violetagg** [comment]
@abelyliu Please create a new issue.
