### ISSUE TITLE
How to monitor connection pool?

### ISSUE THREAD

**Issue by Lovnx** [reactor/reactor-netty#1306]
I want to monitor behaviour of connection pool, Is there any metrics enable switch?

**Comment by violetagg** [comment]
@Lovnx Check this https://projectreactor.io/docs/netty/release/reference/index.html#_metrics_2
For further questions consider using [Gitter](https://gitter.im/reactor/reactor-netty) or [stackoverflow.com](https://stackoverflow.com/questions/tagged/reactor-netty)
