### ISSUE TITLE
HTTP_server metrics is are not recording "error" when calling HTTP client close to socket

### ISSUE THREAD

**Issue by jtorkkel** [reactor/reactor-netty#1321]
Current behavior:
No metrics related to http_server_reqests_seconds_count recorded

If tcp.metrics(true) then the following metrics can be seen
reactor_netty_tcp_server_errors_total{app="xxx",host="yyy",remote_address="127.0.0.1:45935",uri="tcp"} 1.0
reactor_netty_tcp_server_errors_total{app="xxx",host="yyy",remote_address="127.0.0.1:45951"uri="tcp"} 1.0
but remote_address should be removed. 

Expected behavior:
http_server_requests_seconds_count{app="xxx",exception="clientSocketClose",host="YYY",method="GET",outcome="SERVER_ERROR",status="500",uri="aaa/bbb"} 1.0
or
http_server_requests_seconds_count{app="xxx", host="YYY",method="GET",outcome="SOCKET_CLOSE",status="500",uri="aaa/bbb"} 1.0
Preferable possibility to include failure reason included into the metrics 

reactor_netty_tcp_server_errors_total is not enought because
- uri is missing, HTTP uri would be needed
- tcp.metrics(true) expose too much data and cannot be always used even remote_address removed

Normal springboot2 http_server metrics are enabled and tcp.metrics enabled using code below

@Configuration
public class WebServerCustomizer {

    @Bean
    public WebServerFactoryCustomizer serverFactoryCustomizer() {
        return new NettyTimeoutCustomizer();
    }

    class NettyTimeoutCustomizer implements WebServerFactoryCustomizer<NettyReactiveWebServerFactory> {
        @Override
        public void customize(NettyReactiveWebServerFactory factory) {
            int five = 5000;
            factory.addServerCustomizers(server -> server.tcpConfiguration(tcp ->
                    tcp.metrics(true).option(ChannelOption.CONNECT_TIMEOUT_MILLIS, five)
                            .doOnConnection(connection ->
                                    connection
                                            .addHandlerLast(new WriteTimeoutHandler(2000, TimeUnit.MILLISECONDS))
                                            .addHandlerLast(new ReadTimeoutHandler(20000, TimeUnit.MILLISECONDS))
                            )));
        }
    }
}

Reactor version(s) used: 0.9.10
JVM version (`java -version`): 8
OS and version (eg. `uname -a`): Windows 10

**Comment by violetagg** [comment]
@jtorkkel `http_server_requests_seconds_count` is not provided by Reactor Netty.

Here you can find all metrics that Reactor Netty HttpServer exposes
https://projectreactor.io/docs/netty/release/reference/index.html#_metrics_4

Follow the snippet below in order to enable Reactor Netty HttpServer metrics

```
@Bean
public WebServerFactoryCustomizer serverFactoryCustomizer() {
	return new NettyTimeoutCustomizer();
}

class NettyTimeoutCustomizer implements WebServerFactoryCustomizer<NettyReactiveWebServerFactory> {
	@Override
	public void customize(NettyReactiveWebServerFactory factory) {
		int five = 5000;
		factory.addServerCustomizers(server -> server.metrics(true, Function.identity()).tcpConfiguration(tcp ->
				tcp.option(ChannelOption.CONNECT_TIMEOUT_MILLIS, five)
						.doOnConnection(connection ->
								connection
										.addHandlerLast(new WriteTimeoutHandler(2000, TimeUnit.MILLISECONDS))
										.addHandlerLast(new ReadTimeoutHandler(20000, TimeUnit.MILLISECONDS))
						)));
	}
}
```

**Comment by violetagg** [comment]
@jtorkkel I'm closing this. We can reopen it if there is an issue with Reactor Netty metrics.
