### ISSUE TITLE
HTTP server metrics not recorded when ReadTimeoutHandler enabled

### ISSUE THREAD

**Issue by jtorkkel** [reactor/reactor-netty#1322]
Enable ad timeout (and or write timeout) for HTTP server, when timeout expire metrics should record the timeout.

Current behavior:
No metrics related to http_server_reqests_seconds_count recorded
tcp.metrics(true) not showing anything related to error.

Expected behavior:
http_server_requests_seconds_count{app="xxx",exception="asyncTimeout",host="YYY",method="GET",outcome="SERVER_ERROR",status="500",uri="aaa/bbb"} 1.0
or 
http_server_requests_seconds_count{app="xxx",host="YYY",method="GET",outcome="TIMEOUT", status="500",uri="aaa/bbb"} 1.0

Preferable possibility to include failure reason included into the metrics.

@Configuration
public class WebServerCustomizer {

    @Bean
    public WebServerFactoryCustomizer serverFactoryCustomizer() {
        return new NettyTimeoutCustomizer();
    }

    class NettyTimeoutCustomizer implements WebServerFactoryCustomizer<NettyReactiveWebServerFactory> {
        @Override
        public void customize(NettyReactiveWebServerFactory factory) {
            int five = 5000;
            factory.addServerCustomizers(server -> server.tcpConfiguration(tcp ->
                    tcp.metrics(true).option(ChannelOption.CONNECT_TIMEOUT_MILLIS, five)
                            .doOnConnection(connection ->
                                    connection
                                            .addHandlerLast(new WriteTimeoutHandler(2000, TimeUnit.MILLISECONDS))
                                            .addHandlerLast(new ReadTimeoutHandler(20000, TimeUnit.MILLISECONDS))
                            )));
        }
    }
}

Reactor version(s) used: 0.9.10
JVM version (`java -version`): 8
OS and version (eg. `uname -a`): Windows 10

**Comment by violetagg** [comment]
@jtorkkel `http_server_requests_seconds_count` is not provided by Reactor Netty.
Here you can find all metrics that Reactor Netty HttpServer exposes
https://projectreactor.io/docs/netty/release/reference/index.html#_metrics_4

If I have the following configuration (note how I enable the metrics)

```
@Bean
public WebServerFactoryCustomizer serverFactoryCustomizer() {
	return new NettyTimeoutCustomizer();
}

class NettyTimeoutCustomizer implements WebServerFactoryCustomizer<NettyReactiveWebServerFactory> {
	@Override
	public void customize(NettyReactiveWebServerFactory factory) {
		int five = 5000;
		factory.addServerCustomizers(server -> server.metrics(true, Function.identity()).tcpConfiguration(tcp ->
				tcp.option(ChannelOption.CONNECT_TIMEOUT_MILLIS, five)
						.doOnConnection(connection ->
								connection
										.addHandlerLast(new WriteTimeoutHandler(2000, TimeUnit.MILLISECONDS))
										.addHandlerLast(new ReadTimeoutHandler(20000, TimeUnit.MILLISECONDS))
						)));
	}
}
```

And controller

```
@RestController
public class MyController {
	@PostMapping("/")
	public String hello(@RequestBody String body) {
		return body;
	}
}
```

And send a request to this endpoint but delay explicitly the request body in order to trigger ReadTimeoutException

Then I'm able to see the following metrics:

```
curl http://localhost:8080/actuator/metrics/reactor.netty.http.server.response.time
{"name":"reactor.netty.http.server.response.time","description":"Total time for the request/response","baseUnit":"seconds","measurements":[{"statistic":"COUNT","value":1.0},{"statistic":"TOTAL_TIME","value":20.137594279},{"statistic":"MAX","value":20.137594279}],"availableTags":[{"tag":"method","values":["POST"]},{"tag":"uri","values":["/"]},{"tag":"status","values":["500"]}]}
```

**Comment by violetagg** [comment]
@jtorkkel I'm closing this. We can reopen it if there is an issue with Reactor Netty metrics.
