### ISSUE TITLE
ConnectionObserver#currentContext visible in doOnChannelInit should have the context of the subscription that drove it.

### ISSUE THREAD

**Issue by crankydillo** [reactor/reactor-netty#1327]
We feel that `doOnChannelInit` should have access to the client 'request' subscription that drove it firing.  The only place we saw to look was in `ConnectionObserver#currentContext`.  Seems like it could go there; however, ultimately, we just need it somewhere:)

I added the following to `TcpClientTests` to show what we are thinking:

```
       @Test
	public void testSubscriberContextAndDoOnChannelInit() throws Exception {
		DisposableServer server = null;
		try {
			server = TcpServer.create().port(0).bindNow();

			final String contextKey = "marcels-key";
			final AtomicReference<String> contextualData = new AtomicReference<>();
			final CountDownLatch channelInitialized = new CountDownLatch(1);
			final String contextValue = "marcels-context";

			TcpClient.create()
					.doOnChannelInit((connectionObserver, channel, remoteAddress) -> {
						if (connectionObserver.currentContext().hasKey(contextKey)) {
							contextualData.set(connectionObserver.currentContext().get(contextKey));
						}
						channelInitialized.countDown();
					})
					.remoteAddress(server::address)
					.wiretap(true)
					.connect()
					.contextWrite(Context.of(contextKey, contextValue))
					.subscribe();

			assertTrue(channelInitialized.await(30, TimeUnit.SECONDS));
			assertNotNull(contextualData.get());
			assertEquals(contextValue, contextualData.get());
		} finally {
			if (server != null)
				server.disposeNow();
		}
	}
```

**Comment by anilgursel** [comment]
I think the propagation of context is broken in two places:

1. In `SimpleDequePool`, `primary.subscribe(alreadyPropagated -> { }, alreadyPropagatedOrLogged -> { });`
2. Context not being passed to `PendingConnectionObserver`.

Sending a PR to tackle the second one for your review.

**Comment by violetagg** [comment]
@crankydillo @anilgursel Do you want to have the PR and continue using `Hooks.onLastOperator` or should we wait for Reactor Pool to start propagating the Context?

/cc @simonbasle

**Comment by anilgursel** [comment]
We already use `Hooks.onLastOperator` for tracing in general.  So, if the PR can be merged, it should help with our immediate issue.  We can re-visit later when Reactor Pool starts propagating the Context. (I need to see why the PR build failed though).

**Comment by violetagg** [comment]
@crankydillo @anilgursel #1335 is available in the current `1.0.0-SNAPSHOT`

**Comment by anilgursel** [comment]
Thank you @violetagg !

**Comment by violetagg** [comment]
https://github.com/reactor/reactor-pool/issues/103
has been fixed
