### ISSUE TITLE
io.netty.util.IllegalReferenceCountException: refCnt: 0, decrement: 1

### ISSUE THREAD

**Issue by deepakThedeveloper** [reactor/reactor-netty#1334]
I am getting above error when trying to communicate between two microservice via spring webclient -- zuul gateway -- webflux.

Surprising thing is this error comes when I am routing the request via zuul. If there is two independent service communicating directly without any gateway I am not getting above error.

reactor-netty version 0.8.5 I am using.

Can I get some help please. I have gone throught various GitHub reactor page regarding this issue but I didn't found any help.

**Comment by violetagg** [comment]
@deepakThedeveloper 
> reactor-netty version 0.8.5 I am using.

This version is too old and we may have fixed that already.

Try to upgrade

**Comment by deepakThedeveloper** [comment]
I have upgraded it to 0.9.12.RELEASE.
earlier error is gone but getting new error.

ClassNotFoundException: reactor.util.retry.Retry

I also checked in 0.9.12 jar and there I am also not able to see Retry class

**Comment by violetagg** [comment]
@deepakThedeveloper Were you able to upgrade and test the latest releases?

**Comment by deepakThedeveloper** [comment]
@violetagg thanks for your guidance. Yes I was able to upgrade it and things are working now. Besides reactor upgrade there was another oauth issue in my application so was not able to communicate to remote service.  Will close the thread now. Sorry for the delay in informing
