### ISSUE TITLE
Provide a callback-like parameter to indicate the data has been flushed for "send" method in NettyOutbound

### ISSUE THREAD

**Issue by JamesChenX** [reactor/reactor-netty#1343]
## Motivation

We need to send our custom "close" frame over TCP connection and then close the TCP connection once we make sure that the close frame is flushed.
In netty, we can use io.netty.channel.ChannelOutboundInvoker#writeAndFlush(java.lang.Object)
```
return channel().writeAndFlush(frame)
	.addListener(ChannelFutureListener.CLOSE);
```
but in reactor netty, there is no callback or mono that we can use for that.

## Desired solution

Provide a mono or a callback that indicates the data has been flushed.

**Comment by violetagg** [comment]
@JamesChenX `NettyOutbound#send...` is exactly what you need

let's take `sendObject` (this is relevant for all `send` methods)
https://projectreactor.io/docs/netty/release/api/reactor/netty/NettyOutbound.html#sendObject-java.lang.Object-

```
Returns:
A Mono to signal successful sequence write (e.g. after "flush") or any error during write
```

**Comment by JamesChenX** [comment]
@violetagg Thank you for confirmation. I was not sure whether `send` is equivalent to `writeAndFlush` because it isn't easy to figure it out from source code.
