### ISSUE TITLE
Enable KeepAlive in TcpServer by Default

### ISSUE THREAD

**Issue by gonwan** [reactor/reactor-netty#1345]
See: https://github.com/spring-cloud/spring-cloud-gateway/issues/1985

Suggesting to enable KeepAlive in TcpServer by default, to fix endless increasing TCP connections.

**Comment by violetagg** [comment]
@gonwan In which version do you need this feature? 0.9.x or 1.0.0

**Comment by gonwan** [comment]
@violetagg Maybe add a complete fix in 1.0.x branch?
The default value of Tcp KeepAlive is 7200 seconds under Linux. That's a bit too long. Enabling KeepAlive might be considered as a quick fix, since no code change required for users.
Better to expose API to customize read/write timeout values in TcpServer, and let spring-cloud-gateway make it configurable and provide reasonable timeout default values. Am I right?

**Comment by violetagg** [comment]
@gonwan Yes it will be TCP server API for keepAliveTimeout, by default it will not be enabled by Reactor Netty but Spring Gateway can add something by default and also will be able to expose a configuration for that

**Comment by violetagg** [comment]
@gonwan I'm gonna expose this API - #1376. Can you take a look and see whether this is what you expect from this feature request?

**Comment by gonwan** [comment]
@violetagg Yes, LGTM with both branches. Thank you.
