### ISSUE TITLE
"Infinity" Memory Usage

### ISSUE THREAD

**Issue by MarcelCoding** [reactor/reactor-netty#1349]
If I serve e.g. 10MB a `.webp` file via the reactor-netty http server,
the used memory is not cleaned up again.
The problem only exists if compression is enabled.

Http Server started, with any request:
![grafik](https://user-images.githubusercontent.com/34819524/96891533-0ca2c100-1489-11eb-9d3c-9316cfc9bd74.png)

While processing the request:
![grafik](https://user-images.githubusercontent.com/34819524/96891614-1fb59100-1489-11eb-824e-331341bdf917.png)

About 1 minute after the request: (after I finish this Issue after about 10 minutes, the memory consumption is still the same)
![grafik](https://user-images.githubusercontent.com/34819524/96891744-3fe55000-1489-11eb-80b6-b80ec6cc104a.png)

(The code below was used for the images)

## Steps to Reproduce
```java
@Test
public void repoCase() {
  HttpServer.create()
    .bindAddress(() -> new InetSocketAddress("127.0.0.1", 6060))
    .compress(true)
    .handle((request, response) -> {
      response.header(HttpHeaderNames.CONTENT_TYPE, "image/webp");
      return response.sendFile(Path.of("<10-MB-WEBP-FILE>"));
    })
    .bindNow()
    .onDispose()
    .block();
}
```

## Your Environment
Windows 10 (winver)
![grafik](https://user-images.githubusercontent.com/34819524/96892007-7e7b0a80-1489-11eb-94bc-4a5e2ea040c7.png)

AdoptOpenJDK 15: (java --version)
```
openjdk 15 2020-09-15
OpenJDK Runtime Environment AdoptOpenJDK (build 15+36)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 15+36, mixed mode, sharing)
```

Gradle 6.7 (./gradlew --version)
```
------------------------------------------------------------
Gradle 6.7
------------------------------------------------------------

Build time:   2020-10-14 16:13:12 UTC
Revision:     312ba9e0f4f8a02d01854d1ed743b79ed996dfd3

Kotlin:       1.3.72
Groovy:       2.5.12
Ant:          Apache Ant(TM) version 1.10.8 compiled on May 10 2020
JVM:          11.0.8 (AdoptOpenJDK 11.0.8+10)
OS:           Windows 10 10.0 amd64
```

Reactor in Gradle:
```groovy
api(platform('io.projectreactor:reactor-bom:Dysprosium-SR12'))
api('io.projectreactor:reactor-core')
api('io.projectreactor.netty:reactor-netty')
```
![grafik](https://user-images.githubusercontent.com/34819524/96892659-255fa680-148a-11eb-888e-c9b44c404122.png)

Firefox Developer:
![grafik](https://user-images.githubusercontent.com/34819524/96893194-be8ebd00-148a-11eb-86bd-e73b94d38d97.png)
**But i have the same problem with the chromium based edge**
![grafik](https://user-images.githubusercontent.com/34819524/96893407-f564d300-148a-11eb-9892-8351cf00bb5e.png)

**Comment by violetagg** [comment]
@MarcelCoding By default Netty uses memory pooling. Is it possible that you actually see this? Do you have OOM or Out of Direct memory?

If you minimise the heap (-Xmx) and the direct memory (-Dio.netty.maxDirectMemory) do you see OOM or Out of Direct memory?

**Comment by MarcelCoding** [comment]
@violetagg 
I tested it again and found that it stops at about 700 MB by default.
But with the options `-Xmx100M` and `-Dio.netty.maxDirectMemory100M` the limit is about 120MB.
I think the remaining 20MB come from Gradle.

Thank you for the enlightening answer.
But I still have one question:
Does Netty clean the memory only when spaces is needed?

**Comment by violetagg** [comment]
@MarcelCoding These links are interesting (by default Reactor Netty uses `PooledByteBufAllocator`)
https://netty.io/wiki/using-as-a-generic-library.html#performance
https://netty.io/wiki/reference-counted-objects.html
https://livebook.manning.com/book/netty-in-action/chapter-5/147

**Comment by MarcelCoding** [comment]
Thanks!
