### ISSUE TITLE
HTTP server connection Pool metrics

### ISSUE THREAD

**Issue by jtorkkel** [reactor/reactor-netty#1366]
HTTP server Connection Pool metrics missing.

SpringBoot 1 / Jetty (and Tomcat) provides HTTP server connection pool metrics
 - jetty_threads_busy
- jetty_threads_config_max
- jetty_threads_config_min
- jetty_threads_current
- jetty_threads_idle
- jetty_threads_jobs

In Springboot 2 WebFlux provides Pooled ConnectionProvider metrics
https://projectreactor.io/docs/netty/release/reference/index.html#_metrics_5
- reactor.netty.connection.provider.total.connections
- reactor.netty.connection.provider.active.connections
- reactor.netty.connection.provider.idle.connections

Similar metrics should be available for HTTP server

**Comment by violetagg** [comment]
@jtorkkel 
> HTTP server Connection Pool metrics missing.
> 
> SpringBoot 1 / Jetty (and Tomcat) provides HTTP server connection pool metrics
> 
> * jetty_threads_busy
> * jetty_threads_config_max
> * jetty_threads_config_min
> * jetty_threads_current
> * jetty_threads_idle
> * jetty_threads_jobs

These are not connections but threads?
Reactor Netty uses event loop, it works with a very few threads (typically equal to the number of cores).

> 
> In Springboot 2 WebFlux provides Pooled ConnectionProvider metrics
> https://projectreactor.io/docs/netty/release/reference/index.html#_metrics_5
> 
> * reactor.netty.connection.provider.total.connections
> * reactor.netty.connection.provider.active.connections
> * reactor.netty.connection.provider.idle.connections
> 
> Similar metrics should be available for HTTP server

HTTP server does not use connection pool. Can you clarify a bit?

**Comment by violetagg** [comment]
@jtorkkel In order to address this enhancement we need an answers to the questions above.

**Comment by jtorkkel** [comment]
Hi, sorry for the delay.

I did not mean actual pools but have similar metrics how many sockets/channels netty server has open, how many are active and how many are inactive.

I found that extending Netty ChannelInboundHandlerAdapter methods channelActive and channelInactive it might be possible to tract the active connections. I hope the number of open socket can be found somewhere so with this data metrics could be created.
Article referring how incoming connection can be limited using this approach. https://stackoverflow.com/questions/46849964/how-to-set-maximum-concurrent-connections-with-netty

**Comment by violetagg** [comment]
@jtorkkel Thanks a lot for the input. We will try to schedule this for some of the next releases.
