### ISSUE TITLE
EPOLL + blocking HTTP - timeouts, closed connection, huge amount of time to process

### ISSUE THREAD

**Issue by nnl-1** [reactor/reactor-netty#1368]
I have a chain of REST API calls using reactive webclient.
Both non-blocking and blocking calls (in separate thread) work fine w/o epoll (my local machine - nio).
Non-blocking call works fine with epoll (google cloud run) but blocking call either hangs with 'connection closed' or just executes minutes (instead of seconds for non-blocking call).

After moving to separate elastic scheduler + custom http client + huge timeouts (20 min) calls started to go though but there is something wrong definitely. 

## Expected Behavior

the same performance for blocking operations, no closed connections etc.

## Steps to Reproduce

```java
package netty.epoll.bugreport;

import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.web.reactive.function.client.ExchangeStrategies;
import org.springframework.web.reactive.function.client.WebClient;
import org.springframework.web.reactive.function.server.RouterFunction;
import org.springframework.web.reactive.function.server.RouterFunctions;
import org.springframework.web.reactive.function.server.ServerResponse;
import reactor.core.publisher.Mono;

import java.time.Duration;
import java.util.concurrent.*;

@Configuration
public class DefaultRouter1 {

    public class Exec {
        private final BlockingQueue<String> queue = new LinkedBlockingQueue<>(10);
        private final ExecutorService executor = Executors.newFixedThreadPool(1);

        public Exec() {
            final Runnable consumer = () -> {
                try {
                    while (true) {
                        String url = queue.poll(5, TimeUnit.SECONDS);
                        if (url != null) {
                            try {
                                exec(url).flatMap(ok -> exec(url).flatMap(ok1 -> exec(url)))
                                        .block();
                            }
                            catch (Exception e) {
                            }
                        }
                    }
                } catch (Exception e) {
                }
            };
            executor.execute(consumer);
        }

        static final int MAX_IN_MEMORY_SIZE = 16 * 1024 * 1024;

        public WebClient webClient(String baseUrl) {
            return WebClient.builder()
                    .exchangeStrategies(ExchangeStrategies.builder()
                            .codecs(configurer -> configurer
                                    .defaultCodecs()
                                    .maxInMemorySize(MAX_IN_MEMORY_SIZE))
                            .build())
                    .baseUrl(baseUrl)
                    .build();
        }

        public Mono<Boolean> exec(String url) {
            return webClient(url).get()
                    .retrieve()
                    .bodyToMono(byte[].class)
                    .retry(3)
                    .timeout(Duration.ofSeconds(25))
                    .map(body -> true);
        }

        public void put(String url) {
            queue.add(url);
        }
    }

    private final Exec exec = new Exec();

    @Bean
    public RouterFunction<ServerResponse> route(HttpHandler handler) {

        return RouterFunctions.
                route()
                .GET("exec", req -> {
                    final String url = req.queryParam("url").orElseThrow(() -> new RuntimeException());
                    exec.put(url);
                    return ServerResponse.ok().build();
                })

                .GET("exec-s", req -> {
                    final String url = req.queryParam("url").orElseThrow(() -> new RuntimeException());
                    return exec.exec(url).flatMap(ok -> ServerResponse.ok().build());
                })
                .build();
    }
}

```

log after executing /exec:

 2020-11-05 22:39:01.752 MSK
[DEBUG] 2020-11-05 19:39:01.752 [pool-2-thread-1] PooledConnectionProvider - Creating a new client pool [PoolFactory {maxConnections=500, pendingAcquireMaxCount=-1, pendingAcquireTimeout=45000, maxIdleTime=-1, maxLifeTime=-1, metricsEnabled=false}] for [www.highreshdwallpapers.com:443]
Default
2020-11-05 22:39:17.952 MSK
reactor.core.Exceptions$ReactiveException: java.util.concurrent.TimeoutException: Did not observe any item or terminal signal within 25000ms in 'Mono.retry ⇢ at ...DefaultRouter1$Exec.exec(DefaultRouter.java:104)' (and no fallback has been configured)
Default
2020-11-05 22:39:17.952 MSK
Caused by: java.util.concurrent.TimeoutException: Did not observe any item or terminal signal within 25000ms in 'Mono.retry ⇢ at .DefaultRoute1r$Exec.exec(DefaultRouter.java:104)' (and no fallback has been configured)
Default
2020-11-05 22:39:17.952 MSK
at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.handleTimeout(FluxTimeout.java:288) ~[reactor-core-3.3.11.RELEASE.jar:3.3.11.RELEASE]
Default
2020-11-05 22:39:17.953 MSK
Assembly trace from producer [reactor.core.publisher.MonoTimeout] :
Default
2020-11-05 22:39:17.953 MSK
reactor.core.publisher.Mono.timeout(Mono.java:4519)
Default
2020-11-05 22:39:17.953 MSK
|_ Mono.timeout ⇢ at.DefaultRouter1$Exec.exec(DefaultRouter1.java:105)
Default
2020-11-05 22:39:17.953 MSK
at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.handleTimeout(FluxTimeout.java:288) ~[reactor-core-3.3.11.RELEASE.jar:3.3.11.RELEASE]
Default
2020-11-05 22:39:17.953 MSK
at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.doTimeout(FluxTimeout.java:273) ~[reactor-core-3.3.11.RELEASE.jar:3.3.11.RELEASE]
Default
2020-11-05 22:39:17.953 MSK
at reactor.core.publisher.FluxTimeout$TimeoutTimeoutSubscriber.onNext(FluxTimeout.java:395) ~[reactor-core-3.3.11.RELEASE.jar:3.3.11.RELEASE]
Default
2020-11-05 22:45:15.668 MSK
|_ Mono.timeout ⇢ at.DefaultRouter1$Exec.exec(DefaultRouter1.java:105)
Default
2020-11-05 22:46:08.725 MSK
|_ Mono.timeout ⇢ at .DefaultRouter1$Exec.exec(DefaultRouter1.java:105)

OR:

javax.net.ssl.SSLException: SSLEngine closed already\n\tat io.netty.handler.ssl.SslHandler.wrap(SslHandler.java:854) ~[netty-handler-4.1.53.Final.jar:4.1.53.Final]\n\tSuppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 

OR just closed connections etc.

## Your Environment

google cloud run

* Reactor version(s) used:

org.springframework.boot:spring-boot-starter-webflux 2.2.2.RELEASE
reactor-netty 0.9.13.RELEASE

* Other relevant libraries versions (eg. `netty`, ...):
* JVM version (`java -version`):
java 8
* OS and version (eg. `uname -a`):
docker base image - openjdk:8

**Comment by violetagg** [comment]
@nnl-1 You are updating only Reactor Netty version, however Reactor Netty requires a concrete Netty version and when it is related to the natives (epoll) it is even more important to run Reactor Netty with the corresponding Netty version.

Either use a new Spring Boot version where Reactor Netty and Netty are compatible or update also Netty version.

**Comment by nnl-1** [comment]
@violetagg thanks for reply, where I can find compatibility info? What version of spring-boot & reactor-netty I should use in this case?

**Comment by violetagg** [comment]
@nnl-1 
Spring Boot dependencies:
- 2.2.2.RELEASE
https://github.com/spring-projects/spring-boot/blob/3ce438d6a3122539b86a70261bd572ef771d6c03/spring-boot-project/spring-boot-dependencies/pom.xml#L174
https://github.com/spring-projects/spring-boot/blob/3ce438d6a3122539b86a70261bd572ef771d6c03/spring-boot-project/spring-boot-dependencies/pom.xml#L163
- 2.2.11.RELEASE
https://github.com/spring-projects/spring-boot/blob/275574dd949484ae759b2386979c2483702794dd/spring-boot-project/spring-boot-dependencies/pom.xml#L176
https://github.com/spring-projects/spring-boot/blob/275574dd949484ae759b2386979c2483702794dd/spring-boot-project/spring-boot-dependencies/pom.xml#L164

**Comment by nnl-1** [comment]
@violetagg Ok, I've updated spring-boot to 2.2.11 - no help - the same error.

**Comment by violetagg** [comment]
@nnl-1 

I did some modifications to the example in order to be able to run it

```
@Bean
public RouterFunction<ServerResponse> route() {

return RouterFunctions.
            route()
            .GET("/exec", req -> {
                final String url = req.queryParam("url").orElseThrow(() -> new RuntimeException());
                exec.put(url);
                return ServerResponse.ok().build();
            })

            .GET("/exec-s", req -> {
                final String url = req.queryParam("url").orElseThrow(() -> new RuntimeException());
                return exec.exec(url).flatMap(ok -> ServerResponse.ok().build()).log();
            })
            .build();
}
```

And added logging here:

```
public Exec() {
    final Runnable consumer = () -> {
        try {
            while (true) {
                String url = queue.poll(5, TimeUnit.SECONDS);
                if (url != null) {
                    try {
                        exec(url).flatMap(ok -> exec(url).flatMap(ok1 -> exec(url))).log("blocking")      <======LOGGING
                                .block();
                    }
                    catch (Exception e) {
                    }
                }
            }
        } catch (Exception e) {
        }
    };
    executor.execute(consumer);
}
```

I tried the following request `curl http://localhost:8080/exec?url=http://example.com` and I'm able to see the following in the logs:

```
2020-11-06 11:57:14.069  INFO 7301 --- [pool-1-thread-1] blocking                                 : | onSubscribe([Fuseable] MonoFlatMap.FlatMapMain)
2020-11-06 11:57:14.070  INFO 7301 --- [pool-1-thread-1] blocking                                 : | request(unbounded)
2020-11-06 11:57:14.625  INFO 7301 --- [or-http-epoll-3] blocking                                 : | onNext(true)
2020-11-06 11:57:14.626  INFO 7301 --- [or-http-epoll-3] blocking                                 : | onComplete()
```

I'm testing a VM with Ubuntu 18.04

How to reproduce the issue?

**Comment by nnl-1** [comment]
@violetagg Ubuntu 16.04.1 - works as expected.
But in gcr it doesn't work on:
Linux cs-903866143123-default-boost-b6d44 5.4.49+ #1 SMP Sun Oct 18 19:43:35 PDT 2020 x86_64 GNU/Linux

What could I do to trace the reason?

**Comment by nnl-1** [comment]
@violetagg 
any thoughts on how to catch the reason?

**Comment by violetagg** [comment]
@nnl-1 If you make the blocking call to make just 1 remote call as the non blocking call, is the result the same?

**Comment by nnl-1** [comment]
@violetagg same error with just 1 blocking call. No error with non-blocking call.

{
  "textPayload": "reactor.core.Exceptions$ReactiveException: java.util.concurrent.TimeoutException: Did not observe any item or terminal signal within 25000ms in 'Mono.flatMap ⇢ at org.springframework.web.reactive.function.client.DefaultWebClient$DefaultResponseSpec.bodyToMono(DefaultWebClient.java:465)' (and no fallback has been configured)",
  "insertId": "",
  "resource": {
    "type": "cloud_run_revision",
    "labels": {
      "revision_name": "",
      "project_id": "",
      "location": "europe-west1",
      "configuration_name": "",
      "service_name": ""
    }
  },
  "timestamp": "2020-11-10T13:18:04.199812Z",
  "labels": {
    "instanceId": ""
  },
  "logName": "projects/../logs/run.googleapis.com%2Fstdout",
  "receiveTimestamp": "2020-11-10T13:18:04.239199698Z"
}

**Comment by nnl-1** [comment]
@violetagg probably GCR just takes all the cpu alloc from my container in such cases - https://cloud.google.com/run/docs/tips/general#avoiding_background_activities
we could close it I think.
thanks

**Comment by rstoyanchev** [comment]
A couple of things don't seem right. First `WebClient` is created for every call and that's not ideal. Second the call to `put` can block if the queue is full but a WebFlux server handler should not be blocked. As Reactor Netty is used for both server and client they actually share resources, so exhausting the server resources also impacts the client.

**Comment by nnl-1** [comment]
@rstoyanchev what do you suggest regarding creating webclient? 
You're right about put though.
tx

**Comment by rstoyanchev** [comment]
Simply create a `WebClient` instance once and re-use it.

**Comment by violetagg** [comment]
https://cloud.google.com/run/docs/tips/general#avoiding_background_activities

Yes as described - a background process after response returned

```
When an application running on Cloud Run finishes handling a request, the container instance's access to CPU will be disabled or severely limited. Therefore, you should not start background threads or routines that run outside the scope of the request handlers.
```
