### ISSUE TITLE
No UdpServer found under reactor.ipc.netty.udp

### ISSUE THREAD

**Issue by beihaifeiwu** [reactor/reactor-netty#137]

**Comment by violetagg** [comment]
Hello,

Please provide more information about the issue.

Regards,
Violeta

**Comment by beihaifeiwu** [comment]
Hi, I want to use reactor in my udp server project, but I found that only **reactor.ipc.netty.udp.UdpClient** exist, Is this correct ?

**Comment by smaldini** [comment]
We'll take care of that in 0.8 indeed, right now UdpClient is UdpServer #174)
