### ISSUE TITLE
Performance regression in Spring Cloud Gateway

### ISSUE THREAD

**Issue by violetagg** [reactor/reactor-netty#1370]
Related to https://github.com/spring-cloud/spring-cloud-gateway/issues/1956

**Comment by johndudo** [comment]
when are you going to release 0.9.14.RELEASE, before  0.9.14.RELEASE come out,  use 0.9.7 instead?  Is 0.9.7 stable?

**Comment by violetagg** [comment]
The issue is a regression caused by #1185 that is released with 0.9.10.RELEASE

@johndudo For the moment 0.9.14.RELEASE is scheduled for 07.12
The regression is introduced in 0.9.10.RELEASE so you can either use 0.9.7.RELEASE or 0.9.9.RELEASE

**Comment by violetagg** [comment]
`0.9.14.RELEASE` is available with the fix from the PR #1371
