### ISSUE TITLE
FluxReceive should check the reference count of the bytebuf and only tries to release it quietly if it isn't 0

### ISSUE THREAD

**Issue by JamesChenX** [reactor/reactor-netty#1372]
## Expected Behavior
1. FluxReceive should check the reference count of the bytebuf and only tries to release it if it isn't 0.
2. Then, releases the bytebuf **quietly** even if Netty throws IllegalReferenceCountException (refCnt: 0, decrement: 1) because it's meaningless to log the exception infinitely while we have infinite inbound WebSocket message to handle.
Of course, allowing developers to set a log level for it is also a good option.

## Actual Behavior
FluxReceive always throws IllegalReferenceCountException if we release the bytebuf in another thread in our own project.

**And we must release it manually**. Because our code consumes the inbound messages from the WebSocketSession and retains the bytebuf so that it won't be released by FluxReceive (copying is unacceptable because we really do care about performance) and then send the bytebuf to another server in another thread over RPC.

**As a result, there is no guarantee that we will release the bytebuf first or FluxReceive will do first.**

## Steps to Reproduce
The following code shows how we retain and release the bytebuf from the WebSocket session.

```java
        Flux<WebSocketMessage> responseOutput = webSocketSession.receive()
                .flatMap(inboundMessage -> {
                    if (!node.isActive()) {
                        return Mono.error(TurmsBusinessException.get(TurmsStatusCode.UNAVAILABLE));
                    }
                    switch (inboundMessage.getType()) {
                        case BINARY:
                            DataBuffer payload = inboundMessage.getPayload();
                            if (payload.capacity() == 0) {
                                return workflowMediator.processHeartbeatRequest(userId, deviceType)
                                        .thenReturn(webSocketSession.binaryMessage(factory -> ((NettyDataBufferFactory) factory).wrap(HEARTBEAT_BYTE_BUF)));
                            } else {
                                SimpleTurmsRequest turmsRequest = TurmsRequestUtil.parseSimpleRequest(payload.asByteBuffer());
                                ByteBuf requestBuffer = NettyDataBufferFactory.toByteBuf(payload);
                                // 1. We retain the bytebuf
                                requestBuffer.retain();
                                ServiceRequest request = new ServiceRequest(userId,
                                        deviceType,
                                        turmsRequest.getRequestId(),
                                        turmsRequest.getType(),
                                        requestBuffer);
                                // 2. processServiceRequest() will send the bytebuf to another server in another thread.
                                return workflowMediator.processServiceRequest(request)
                                        .map(notification ->
                                                webSocketSession.binaryMessage(factory -> ((NettyDataBufferFactory) factory).wrap(ProtoUtil.getDirectByteBuffer(notification))))
                                        .doOnTerminate(() -> {
                                            // 3. Release the bytebuf to make sure there is no memory leak
                                            int refCnt = requestBuffer.refCnt();
                                            if (refCnt > 0) {
                                                requestBuffer.release(refCnt);
                                            }
                                        });
                            }
                        case TEXT:
                        case PING:
                            return Mono.just(PONG_MESSAGE);
                        case PONG:
                        default:
                            // ignore the message
                            return Mono.empty();
                    }
                });
```

## Possible Solution

1. FluxReceive should check the reference count of the bytebuf and only tries to release it if it isn't 0.
2. Then, releases the bytebuf **quietly** even if Netty throws IllegalReferenceCountException (refCnt: 0, decrement: 1).

## Your Environment

* Reactor version(s) used: 
reactor-netty-core-1.0.0
* Other relevant libraries versions (eg. `netty`, ...):
netty-4.1.53.Final

**Comment by violetagg** [comment]
@JamesChenX So even when you use `retain` you see the issue. Is that correct?
Or you see the issue only if you not `retain` ?

**Comment by JamesChenX** [comment]
@violetagg I can see the IllegalReferenceCountException for both cases randomly. And **the reason for that is FluxReceive tries to release the bytebuf while I do the same work too** (because I need to make sure the bytebuf is released after we have retained it). And if we don't release it manually, we won't get the exception but we have to do this for the reason mentioned above.

For details:
1. If FluxReceive tries to release the bytebuf first, it doesn't really release the bytebuf because we have retained it. And then we will release the bytebuf in step 3 (as what shows in the code above). In this case, there should no exception.
2. If we release the bytebuf in step 3 first, and the FluxReceive tries to release it. In this case, there should an exception because FluxReceive doesn't check whether the buffer has been released.

FYI: reactor.netty.channel.FluxReceive#drainReceiver
![image](https://user-images.githubusercontent.com/44962329/98446060-28c78300-2156-11eb-8a7c-5617321a1e14.png)

**Comment by violetagg** [comment]
@JamesChenX I think that there is some misunderstanding about `retain`/`release`. `retain` increases the counter, `release` decreases the counter.

The `release` invoked in Reactor Netty releases the first counter as Reactor Netty is the last component in the Netty chain
https://netty.io/wiki/reference-counted-objects.html

If a component invoked in `onNext` DO NOT consume the buffer directly, but buffers it etc., then this component should have `retain` + `release`.
If a component invoked in `onNext` consumes the buffer directly, then there is no need to do `retain` + `release` and Reactor Netty will release the buffer.

If all components in the chain do the same then there will not be such exception.
https://docs.spring.io/spring-framework/docs/current/reference/html/core.html#databuffers-buffer-pooled
Recently similar was discussed here: https://github.com/netty/netty/issues/10723#issuecomment-714951358

**Comment by JamesChenX** [comment]
@violetagg Thanks for your detailed reply and I have understood why reactor-netty behaviors in that way and continue with our project. Thanks.

**Comment by JamesChenX** [comment]
@violetagg I am sorry to reopen the ticket again because after I dive into the bug the whole day, I confirm that **the bytebuf is released by FluxReceive unexpectedly if the downstream code executes in another thread even we still use the Flux/Mono model**.

The following image shows how the bug occurs.
![image](https://user-images.githubusercontent.com/44962329/98469047-5ecd3b80-2218-11eb-9f16-e3d01217d701.png)
1. (Step 1) FluxReceive will trigger our business logic by onNext(v)
2. (Step 4) And our code will call updateHeartbeatTimestamp() that is a network request to Redis (Note that the refCnt is still 1)
3. (Step 5) Then, The ReferenceCountUtil.release will be called and it works fine because the refCnt is 1.
4. (Step 6) After the network operation has been done, the code in step 6 will be called, and the refCnt has become 0 since step

**Comment by violetagg** [comment]
@JamesChenX 
Check the very simple example below where `release` is not needed because of the network operation:

```
HttpServer server =
		HttpServer.create()
		          .port(PORT)
		          .route(r -> r.post("/echo",
		                  (req, res) -> res.header(CONTENT_TYPE, TEXT_PLAIN)
		                                   .send(req.receive().retain())));
``` 

This is a very simple `echo` example.
In this example you can see that only `retain` is invoked but not `release`, if you read again the wiki that I mentioned, when you delegate the work to Netty to send the data to the network you do not need to `release`, you delegate this work to Netty, because Netty knows when exactly the buffer is written and has to be `released`.

But if you for example buffers the data for late evaluation on the server (so it is not send to the network, but the data will be consumed on a later stage) then you need to `retain` and then `release`, because in this case only know when exactly to `release` that particular buffer.

So in the situation above are you the one that knows when to `release` the data, or you delegate this to some other component?

**Comment by JamesChenX** [comment]
I know when the bytebuf should be released (it should be released after the bytebuf has been flushed to another server. In other words, it must be released in `doOnTerminate` just below step 3 in the image below)
but we also delegate the release job to RSocket.
But the problem is if we try to delegate the bytebuf to RSocket, it will throw because the bytebuf has been released by FluxReceive as I have mentioned above. (BTW: We try to follow the Reactor model all the way)

For the management of the lifecycle of bytebuf, I know we don't need to maintain it in most cases because Netty and other underlying frameworks should do the job, but in this case we **have to** maintain it manually because FluxReceive will release the bytebuf unexpectedly for the reason mentioned in **Reproduction steps**.

As a result,
1. If we remove all our code to `retain` and `release` the bytebuf, RSocket will throw because we delegate a bytebuf with the refCnt of 0 to it (it has been released by FluxReceive).
2. If we keep our `retain` and `release`, FluxReceive will throw IllegalReferenceCountException (refCnt: 0, decrement: 1) because we may have released the bytebuf by the code in `onTerminate`
![image](https://user-images.githubusercontent.com/44962329/98470286-955a8480-221f-11eb-8a83-27381320537a.png)
.

And I will try the example later since I need to go to sleep now. Anyway, thanks for your help!

**Comment by violetagg** [comment]
@JamesChenX From your explanation your case is exactly similar to the `echo` example above. You have to `retain` and then leave the release to RSocket.

**Comment by JamesChenX** [comment]
@violetagg Thanks for your support. With your suggestion, I have fixed the bug finally by the following code: **We retain once and release it once rather than releasing it to 0**. And no exception will be thrown currently.
![image](https://user-images.githubusercontent.com/44962329/98486222-02d5d780-2257-11eb-8958-7abd982efa11.png)

I think this issue and the code can help other developers if they encounter the same problem. And it's better to document the behavior of FluxReceive because it's really obscure and time-consuming to find out why the bytebuf is released unexpectedly and randomly, especially to pinpoint it in a big project.
