### ISSUE TITLE
open new issue about:reactor.netty.http.client.PrematureCloseException: Connection prematurely closed BEFORE response

### ISSUE THREAD

**Issue by ctlove0523** [reactor/reactor-netty#1375]
## Expected Behavior

I use Spring Coud Gateway as my API gateway, i call proxy service's api through Spring Cloud Gateway when proxy service return response i expected i can get right response.
## Actual Behavior
when load is small it works well,but when load become bigger and bigger(200 workers),i get an exception:
~~~
reactor.netty.http.client.PrematureCloseException: Connection prematurely closed BEFORE response
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	|_ checkpoint ⇢ org.springframework.cloud.gateway.filter.WeightCalculatorWebFilter [DefaultWebFilterChain]
	|_ checkpoint ⇢ org.springframework.boot.actuate.metrics.web.reactive.server.MetricsWebFilter [DefaultWebFilterChain]
	|_ checkpoint ⇢ HTTP GET "/iomgr/v1/probe/liveness" [ExceptionHandlingWebHandler]
Stack trace:
2020-11-10 03:07:49,270Z WARN[reactor-http-nio-4]<client.HttpClientConnect,299>-[id: 0x863ab339, L:0.0.0.0/0.0.0.0:60772 ! R:/100.95.175.206:443] The connection observed an error
reactor.netty.http.client.PrematureCloseException: Connection prematurely closed BEFORE response
~~~

## Steps to Reproduce

1、create a proxy service and the service just only has one endpoint like:/v1/probe/liveness,the endpoint just return ok
```java
curl -i http://ip:port/v1/probe/liveness
HTTP/1.1 200
```
2、start spring cloud gateway application and create simple route like bellow:
~~~
@Bean
public RouteLocator kubernetesRoutes(RouteLocatorBuilder builder) {
	log.info("begin to load kubernetes routes");
	return builder.routes()
		.route("kubernetes", new Function<PredicateSpec, Route.AsyncBuilder>() {
			@Override
			public Route.AsyncBuilder apply(PredicateSpec predicateSpec) {
				return predicateSpec.path("/v1/probe/liveness/**")
					.uri("http://100.95.175.206:80");
			}
		})
		.build();
}
~~~
3、use apache jmeter to load test
~~~
number of threads(users)：200
Ramp-up period(second)：1
Loop count：infinite
~~~
## Possible Solution

according to other issue about this,I thry the below solution but it not work:
1、add jvm parameter:
-Dreactor.netty.pool.leasingStrategy=lifo
2、set maxIdleTime 
~~~yaml
spring:
  cloud:
    gateway:
      metrics:
        enabled: true
      httpclient:
        pool:
          maxIdleTime: 2000
        ssl:
          useInsecureTrustManager: true
        wiretap: true
~~~
## Your Environment

Spring Cloud Gateway：2.2.5.RELEASE
reactor-netty：0.9.12.RELEASE
reactor-core：3.3.10.RELEASE
java version：java version "1.8.0_201"
                      java(TM) SE Runtime Environment (build 1.8.0_201-b09)
                      Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)

* Reactor version(s) used: reactor-netty：0.9.12.RELEASE；reactor-core：3.3.10.RELEASE
* Other relevant libraries versions：netty 4.1.52.Final
* JVM version (`java -version`):java version "1.8.0_201"
* OS and version: Windows 10 (CYGWIN_NT-10.0 DESKTOP-TJTHRU9 3.1.6(0.340/5/3) 2020-07-09 08:20 x86_64 Cygwin)

**Comment by violetagg** [comment]
@ctlove0523 So when you apply the configuration for leasing strategy and idle timeout, do you see the issue?

**Comment by ctlove0523** [comment]
> @ctlove0523 So when you apply the configuration for leasing strategy and idle timeout, do you see the issue?

@violetagg 
In my test, when i configure for leasing strategy and idle timeout the error still appears.

**Comment by violetagg** [comment]
@ctlove0523 Any chance to provide reproducible example?

**Comment by ctlove0523** [comment]
@violetagg ok, I will write a example for reproduce this issue.In addition,i use okhttp to perform request to the same proxy service,it works well。

**Comment by launceviya** [comment]
？？？？

**Comment by violetagg** [comment]
@ctlove0523 Were you able to identify a reproducible example?

**Comment by ctlove0523** [comment]
> @ctlove0523 Were you able to identify a reproducible example? Are you able to take a TCP dump so that we can see which party closes the connection.

Ok,this is a example code can reproduce this issue,you can get from [here](https://github.com/ctlove0523/reactor-test). This weekend i will try reproduce and get a tcp dump file.

**Comment by violetagg** [comment]
@ctlove0523 There you have many routes, which one reproduces the problem?

**Comment by ctlove0523** [comment]
@violetagg The route with id “test_route” can reproduce issue and you need pull the latest code.The follow this tcpdump file when issue occur.
![image](https://user-images.githubusercontent.com/9432235/99891241-b2249c80-2ca2-11eb-8e49-7460cff5fd45.png)

10.71.53.153 is http client（Spring Cloud Gateway) address and 172.16.0.79 is proxy service address. whole tcpdump file
[gateway.zip](https://github.com/reactor/reactor-netty/files/5578745/gateway.zip)

**Comment by violetagg** [comment]
Thanks I can reproduce it. And I think this is the same issue described here #1201.

**Comment by violetagg** [comment]
@johanhaleby And your use case is related to a response with an empty body?

**Comment by johanhaleby** [comment]
@violetagg Yes, the server returns with status code 204 (no content).

**Comment by AsCat** [comment]
@ctlove0523  
Can you help test it with this [RP](https://github.com/spring-cloud/spring-cloud-gateway/pull/2093)

**Comment by ctlove0523** [comment]
> @ctlove0523
> Can you help test it with this [RP](https://github.com/spring-cloud/spring-cloud-gateway/pull/2093) ?

Ok，I will test this PR later

**Comment by violetagg** [comment]
@ctlove0523 The PR was applied to Spring Gateway. What's the result of your testing?

**Comment by ctlove0523** [comment]
@violetagg when i apply this issue to Spring Cloud Gateway,it works well,problem disappeared,so i close this issue.Thanks everyone for your help.

**Comment by AsCat** [comment]
good news, thanks for the tests !  @ctlove0523

**Comment by nitinb-kr** [comment]
> > @ctlove0523 So when you apply the configuration for leasing strategy and idle timeout, do you see the issue?
> 
> @violetagg In my test, when i configure for leasing strategy and idle timeout the error still appears.

@ctlove0523 Hello , I am having similar issue when I connect from my laptop the api is working fine(calling from spring cloud gateway) but on using the Virtual desktop system given by the client it gives a timeout issue
![intellijconsole](https://user-images.githubusercontent.com/83672553/135520505-1c36157d-b0c7-49b4-b02a-3c5aef3d5e84.png)
![postmanop](https://user-images.githubusercontent.com/83672553/135520507-fe9eecee-574e-431f-b8c7-577e131c175f.png)

**Comment by huzhixiang** [comment]
> @violetagg when i apply this issue to Spring Cloud Gateway,it works well,problem disappeared,so i close this issue.Thanks everyone for your help.

I got the same problem "reactor.netty.http.client.PrematureCloseException: Connection prematurely closed BEFORE response"；how to fix it ? Do you find the answer?

**Comment by violetagg** [comment]
@huzhixiang Open a new issue where we will track your particular use case. Please provide a reproducible example.
