### ISSUE TITLE
HttpClient `onComplete` with no HTTP response

### ISSUE THREAD

**Issue by bclozel** [reactor/reactor-netty#138]
This issue can be reproduced using [this project](https://github.com/nickolayrusev/flashscore-stats-reactive), taken from a [StackOverflow question](https://stackoverflow.com/questions/44930448/reactive-webclient-not-emitting-a-response).

After some digging, I think I might have found some race condition in the `HttpClient` connection pool management (see [my answer on SO](https://stackoverflow.com/a/44965430/22982) including workaround suggestion).

## Issue description

1. A connection is taken from the pool to send a request
2. Response is received from the remote server, everything works fine
3. The remote server sends a `FIN, ACK` TCP packet, asking the connection to be closed
4. Right after that the same connection is used to send an HTTP GET request
5. After that, a `FIN, ACK` TCP packet is sent from the client on that connection
6. `RST` TCP packets are exchanged, the connection is closed
7. the `Mono<ClientResponse>` emits `onComplete` without emitting a response

![image](https://user-images.githubusercontent.com/103264/28318626-c14a9cdc-6bcb-11e7-8ea8-342b56e5dfba.png)

(Sorry about the lame screen capture, I can provide you with the actual pcap file if you'd like).

## Expected Behavior

I think that this might be a two-part issue:
* the connection pool should not reuse connections that are about to be closed
* the client should *never* `onComplete` if no response has been received (i.e. an empty `Mono`), but should rather emit an `onError` signal

**Comment by rstoyanchev** [comment]
The behavior is also observed under https://jira.spring.io/browse/SPR-15584 which has a link to a performance test project.

**Comment by violetagg** [comment]
The fix is back-ported to 0.6.x and will be available in 0.6.6.RELEASE onwards
