### ISSUE TITLE
Unicode characters encoded incorrectly on a fetch request

### ISSUE THREAD

**Issue by FireMasterK** [reactor/reactor-netty#1380]
## Expected Behavior
Unicode characters are encoded correctly on a fetch request.

## Actual Behavior
The character gets converted to a .
![image](https://user-images.githubusercontent.com/20838718/98983984-935a3380-2547-11eb-8b98-79e949c8b79d.png)

## Steps to Reproduce
Run the code below, then open http://127.0.0.1:8080/test on your browser (tested on Brave)
It will display `’` correctly.
Now, open the dev tools and paste `fetch('http://127.0.0.1:8080/test')` in the console.
Then, navigate to the network tab and click on the request you just sent and click on the response tab.
You would see that the character was encoded incorrectly.

```java
       HttpServer.create().port(8080).route(routes -> {

	    routes.get("/test", (req, res) -> {

		return res.addHeader("Access-Control-Allow-Origin", "*").send(ByteBufFlux.fromString(Flux.just("’")));

	    });

	}).bindNow();

	Thread.sleep(Long.MAX_VALUE);
```

## Possible Solution
Not sure.

## Your Environment

* Reactor version(s) used: 1.0.1
* Other relevant libraries versions (eg. `netty`, ...): N/A
* JVM version (`java -version`): OpenJ9 VM AdoptOpenJDK (build openj9-0.23.0, JRE 11 Windows 10 amd64-64-Bit Compressed References 20201022_795 (JIT enabled, AOT enabled)
* OS and version (eg. `uname -a`): Microsoft Windows [Version 10.0.19042.610]

**Comment by violetagg** [comment]
@FireMasterK You are using the method with `Charset.defaultCharset()`
Can you try the other method where you can provide the encoding?

`ByteBufFlux.fromString(Flux.just("’"), StandardCharsets.UTF_16, ByteBufAllocator.DEFAULT)`

**Comment by FireMasterK** [comment]
That seems to fix it! Is there a way to set the default encoding in that case?

**Comment by violetagg** [comment]
@FireMasterK This is a programatic API you can use either the method that does not specify the encoding or the method that does.

**Comment by FireMasterK** [comment]
Thanks! I also found another fix: use `-Dfile.encoding=UTF-8` as a JVM argument.
