### ISSUE TITLE
Provide a better way to indicate what needs to be set when creating a proxy

### ISSUE THREAD

**Issue by utwyko** [reactor/reactor-netty#139]
I was attempting to verify the fix made to Proxy Settings for #126 , but for some reason I could not get my HttpClient to use a proxy. The following code did not result in a set proxy:

```java
private static final HttpClient httpClient = HttpClient.builder()
        .options(ops -> ops
                .host("jsonplaceholder.typicode.com")
                .port(80)
                .proxy(proxyOps -> proxyOps.host("sample-proxy").port(1234).build()))
        .build();
```

After some debugging, it turns out that the proxy is only set when a proxy type is set (ClientOptions, line 93-97). 

```java
if (Objects.nonNull(builder.proxyOptions) &&
		Objects.nonNull(builder.proxyOptions.getType()) &&
		Objects.nonNull(builder.proxyOptions.getAddress())) {
	this.proxyOptions = builder.proxyOptions;
}
```

As a user, it is unclear what the required settings are when setting a proxy. It would be great if there was a guided builder, a runtime exception when creating the client or at the least some Javadoc on the builders.

### Reactor Netty version
0.7.0.M1

**Comment by violetagg** [comment]
@utwyko PTAL #142

**Comment by utwyko** [comment]
@violetagg thanks!
