### ISSUE TITLE
Add Reactor ChannelGroup

### ISSUE THREAD

**Issue by MarcelCoding** [reactor/reactor-netty#1390]
## Motivation
A easy to use ChannelGroup with reactor utility functions. (Accessing all active connections)

## Desired solution
Add a custom ChannelGroup extension/implementation.

## Additional context
If you want, I can do that.

**Comment by violetagg** [comment]
@MarcelCoding 
In Reactor Netty 0.9.x you have this for TcpServer/HttpServer
https://github.com/reactor/reactor-netty/blob/197581fcad1315f268409f0d1f40a53e99312651/src/main/java/reactor/netty/tcp/TcpServer.java#L563
https://github.com/reactor/reactor-netty/blob/197581fcad1315f268409f0d1f40a53e99312651/src/main/java/reactor/netty/http/server/HttpServer.java#L668
In Reactor Netty 1.0.x we have it for all UDP/TCP/HTTP client/server
https://github.com/reactor/reactor-netty/blob/ecbcfd79df0831aa5205542b2b0a4279269f2041/reactor-netty-core/src/main/java/reactor/netty/transport/Transport.java#L92

**Comment by MarcelCoding** [comment]
@violetagg yeah but no reactor channel group implementation (Mono Flux methods)

**Comment by violetagg** [comment]
@MarcelCoding Can you describe in more details the use case?

**Comment by MarcelCoding** [comment]
@violetagg I mean a class witch extends the Netty Channel Group and add extra methods to send data with the Reactors Flux and Mono. And maybe also add special methods/implementations to work with http and websockets for broadcasts.

**Comment by violetagg** [comment]
@MarcelCoding For websockets  what's the problem with using the current API. You can connect which will give you a `Connection`, then using `Mono.when/whenDelayError` you can invoke `Connection.outbound().send*()`

**Comment by MarcelCoding** [comment]
Ok, then i use the default Netty methods.

Another related question:
I look up a bit and i don't found a way to check if a channel in a `ChannelGroup` is a Http or a Websocket Connection.

**Comment by violetagg** [comment]
> Ok, then i use the default Netty methods.
> 
> Another related question:
> I look up a bit and i don't found a way to check if a channel in a `ChannelGroup` is a Http or a Websocket Connection.

Because it is not intended to use the send methods in `ChannelGroup`.

Please describe in more details what you want to achieve in order to be able to suggest you a solution.
For example if you are on the client side and you try to use the send methods from `ChannelGroup` you will use connections that are in the connection pool without any acquiring before that.

**Comment by MarcelCoding** [comment]
I have an http server that accepts websocket connections, what I want to do is send notifications to all connected clients.

**Comment by violetagg** [comment]
`reactor.netty.http.server.HttpServerResponse#sendWebsocket(...)` will notify you when the upgrade is successful.
You can use `reactor.netty.http.server.HttpServerResponse#withConnection` to access the connection and also `Connection#onDispose()` will notify you when the connection is closed

Can you try those?

**Comment by MarcelCoding** [comment]
Thanks, this works the way I wanted it to. If you have no questions, I'll close this issue.
