### ISSUE TITLE
Reintroduce OSGI and adapt OSGI Bundle-Version to new Europium scheme

### ISSUE THREAD

**Issue by simonbasle** [reactor/reactor-netty#1392]
Since OSGI support was only removed in reactor-netty, the 2020.0.x cycle should continue to have direct support. However, due to the versioning scheme change, the `Bundle-Version` must be forced (see reactor/reactor#689 for context).

Reintroduce OSGI bnd configuration that was removed in [this commit](https://github.com/reactor/reactor-netty/pull/1084/files#diff-49a96e7eea8a94af862798a45174e6ac43eb4f8b4bd40759b5da63ba31ec3ef7L90) and adapt it to force `BundleVersion`.

**Comment by violetagg** [comment]
@swimmesberger Reactor Netty version 1.0.0 was separated on different modules, so I recommend that you use directly `reactor-netty-core` and `reactor-netty-http`, the old `reactor-netty` is kept only for a migration path and it will be an empty bundle that will just import and export the packages from `reactor-netty-core` and `reactor-netty-http`.

**Comment by swimmesberger** [comment]
@violetagg we will do that when the new version is compatible with OSGi

@simonbasle thanks for keeping OSGi compatibility for now. I completely understand that you want to use a custom versioning scheme that does not fit into the opiniated view of OSGi but I'm still if the new versioning scheme carries some kind of semantic that could be generalized for the BND plugin to always generate semantic versions based on your custom versioning scheme (e.g. by reordering the parts of the version).

Do I correctly understand the new versioning scheme that it's simply the release day of a specific version? Or do you still have a semantic version that carries information about if it's a breaking change or not?

**Comment by simonbasle** [comment]
@swimmesberger it caries the same information as before for modules, and has some calver component to it for release trains, see https://spring.io/blog/2020/04/30/updates-to-spring-versions (maybe not clear enough in the blog post, but module versions are still not strictly semantic versioning)

**Comment by violetagg** [comment]
@swimmesberger The artefacts are available from the Spring snapshot repository (https://repo.spring.io/snapshot/io/projectreactor/netty/). It will be great if you can test them.
