### ISSUE TITLE
Deprecation notices are not clear

### ISSUE THREAD

**Issue by vchekan** [reactor/reactor-netty#1397]
`TcpClient.bootstrap()` method has been deprecated. But deprecation notice says "Use the methods exposed on {@link TcpClient} level". The problem is, this function is already at TcpClient level, so the notice does not make sense to me.
https://github.com/reactor/reactor-netty/blob/b63bd55785556588df7f761d6df6519017dac701/reactor-netty-core/src/main/java/reactor/netty/tcp/TcpClient.java#L135

Another one is `reactor.netty.http.client.HttpClient:tcpConfiguration()`. It's deprecation notice says "Use HttpClient methods for TCP level configurations". And again, we are already in HttpClient class, which has something like 58 methods. And it is not clear at all, which one suppose to be used and how.

Another problem is dissaperence of `reactor.netty.channel.BootstrapHandlers` in v-1.0 release. I could not locate any deprecation release notice so I can not find any way to port Baeldung's solution:
https://www.baeldung.com/spring-log-webclient-calls#2-logging-with-netty-httpclient

## Expected Behavior

Ideally solution would include an example how to configure tracing of http traffic in plain text format (no hexdump).

**Comment by violetagg** [comment]
@vchekan We added a lot of new features so it is not feasible to add examples to that particular function. What we can do is to make the java doc for these new features such that you can find the one that you need and also to add an example in the reference documentation.
The one that you are asking for is

https://projectreactor.io/docs/netty/release/api/reactor/netty/transport/Transport.html#wiretap-java.lang.String-io.netty.handler.logging.LogLevel-reactor.netty.transport.logging.AdvancedByteBufFormat-
https://projectreactor.io/docs/netty/release/api/reactor/netty/transport/logging/AdvancedByteBufFormat.html

May be it is better to add an example here?

**Comment by TheConen** [comment]
@vchekan See https://github.com/reactor/reactor-netty/issues/233#issuecomment-745597979 for an example of how to enable the new human-readable logging

**Comment by dushkin** [comment]
> `TcpClient.bootstrap()` method has been deprecated. But deprecation notice says "Use the methods exposed on {@link TcpClient} level". The problem is, this function is already at TcpClient level, so the notice does not make sense to me.
> https://github.com/reactor/reactor-netty/blob/b63bd55785556588df7f761d6df6519017dac701/reactor-netty-core/src/main/java/reactor/netty/tcp/TcpClient.java#L135
> 
> Another one is `reactor.netty.http.client.HttpClient:tcpConfiguration()`. It's deprecation notice says "Use HttpClient methods for TCP level configurations". And again, we are already in HttpClient class, which has something like 58 methods. And it is not clear at all, which one suppose to be used and how.
> 
> Another problem is dissaperence of `reactor.netty.channel.BootstrapHandlers` in v-1.0 release. I could not locate any deprecation release notice so I can not find any way to port Baeldung's solution:
> https://www.baeldung.com/spring-log-webclient-calls#2-logging-with-netty-httpclient
> 
> ## Expected Behavior
> Ideally solution would include an example how to configure tracing of http traffic in plain text format (no hexdump).

So, I still cannot understand how to deal with "reactor.netty.http.client.HttpClient:tcpConfiguration(). It's deprecation notice says "Use HttpClient methods for TCP level configurations".... Any advise will be blessed :)

**Comment by violetagg** [comment]
@dushkin Everything that you can configure via `HttpClient.tcpConfiguration()`, now you can configure using directly methods exposed by `HttpClient`.

For example:

Instead of 
```
HttpClient.tcpConfiguration(tcpClient -> tcpClient.option(ChannelOption.CONNECT_TIMEOUT_MILLIS, 10000));
```

You can call 

```
HttpClient.option(ChannelOption.CONNECT_TIMEOUT_MILLIS, 10000);
```

Which configuration are you looking for?

**Comment by violetagg** [comment]
@vchekan @dushkin @TheConen I updated the various javadoc (see #1450 ). For example: https://projectreactor.io/docs/netty/snapshot/api/reactor/netty/http/client/HttpClient.html#tcpConfiguration-java.util.function.Function-
https://projectreactor.io/docs/netty/snapshot/api/reactor/netty/tcp/TcpClient.html#bootstrap-java.util.function.Function-
I updated also the reference documentation:
https://projectreactor.io/docs/netty/snapshot/reference/index.html#_wire_logger_2

**Comment by atokle** [comment]
Are there any option to log request/responses TEXTUAL but drop headers to avoid that sensitive data like Authorization header is logged?

**Comment by edgar-philipp** [comment]
I am also using BootstrapHandlers.updateConfiguration() and found no equivalent replacement.
Some help on where to find an equivalent functionality is appreciated :-)

**Comment by violetagg** [comment]
@atokle @edgar-philipp Please use [Gitter](https://gitter.im/reactor/reactor-netty) for any questions.

**Comment by coditori** [comment]
The same problem on "httpClient.tcpConfiguration"
```
Deprecated
Use the other methods exposed by HttpClient to achieve the same configurations. This method will be removed in version 1.1.0.
```

**Comment by maria-ind** [comment]
@violetagg 
Hello Violeta,
Could you please help me to re-write conditional setting of proxy, considering the tcpConfiguration() method is deprecated now.
My current code is:
`private ReactorClientHttpConnector proxyConnector() {`
`        var httpClient = HttpClient.create()`
`                .tcpConfiguration(tcpClient -> {`
`                    if (proxyEnabled) {`
`                        tcpClient = tcpClient.proxy(proxy -> proxy.type(ProxyProvider.Proxy.HTTP).address(new InetSocketAddress(proxyHost, proxyPort)));`
`                    }`
`                    return tcpClient.option(ChannelOption.CONNECT_TIMEOUT_MILLIS, 2000).doOnConnected(connection ->`
`                                    connection.addHandlerLast(new ReadTimeoutHandler(2000)).addHandlerLast(new WriteTimeoutHandler(2000)));`
`                });`
`        return new ReactorClientHttpConnector(httpClient);`
`    }`

**Comment by violetagg** [comment]
@maria-ind I will encourage you to use [Gitter](https://gitter.im/reactor/reactor-netty) or [stackoverflow.com](https://stackoverflow.com/questions/tagged/reactor-netty) for your questions.

The code above should be translated like this:

```
private ReactorClientHttpConnector proxyConnector() {
    var httpClient =
            HttpClient.create()
                      .option(ChannelOption.CONNECT_TIMEOUT_MILLIS, 2000)
                      .doOnConnected(connection ->
connection.addHandlerLast(new ReadTimeoutHandler(2000)).addHandlerLast(new WriteTimeoutHandler(2000)));

    if (proxyEnabled) {
        httpClient = httpClient.proxy(proxy -> proxy.type(ProxyProvider.Proxy.HTTP).address(new InetSocketAddress(proxyHost, proxyPort)));
    }

    return new ReactorClientHttpConnector(httpClient);
}
```

**Comment by sikhasr** [comment]
@violetagg  Can you help me re-write the below snippet as the bootstrap and HttpClient.from(tcp) are deprecated:

 TcpClient.bootstrap(bootstrap -> BootstrapHandlers.updateLogSupport(bootstrap, new HttpLoggingHandler()))

webClient = WebClient.builder().clientConnector(new ReactorClientHttpConnector(HttpClient.from(tcpClient)))

**Comment by violetagg** [comment]
@sikhasr I will encourage you to use [Gitter](https://gitter.im/reactor/reactor-netty) or [stackoverflow.com](https://stackoverflow.com/questions/tagged/reactor-netty) for your questions.
Also please check our [Reference Documentation](https://projectreactor.io/docs/netty/release/reference/index.html#_lifecycle_callbacks_4) where you can find an example with custom `LoggingHandler`.
