### ISSUE TITLE
ByteBuf is too unqualified for WebSocket messages

### ISSUE THREAD

**Issue by rstoyanchev** [reactor/reactor-netty#14]
For WebSocket the `NettyInbound.receive()` which provides ByteBuf's is too unqualified to be useful because there is no way of knowing the boundaries of a complete WebSocket message nor whether it is binary, text, or pong. It's possible to use `NettyInbound.receiveObject().cast(WebSocketFrame.class)` but  it would be nicer if a handler is given something a little less generic and more tailored to a WebSocket interaction -- e.g. a `receive` method that provides WebSocketFrame's.

A similar improvement on the outbound side would remove the need to specify text vs binary when calling one of the `HttpOutbound#upgradeToWebSocketXxx` methods since the input would already be WebSocketFrame's.

**Comment by smaldini** [comment]
Fixed with WebsocketInbound#receiveFrames()
