### ISSUE TITLE
set timeout in Spring WebFlux webclient - Deprecated

### ISSUE THREAD

**Issue by simpleusr** [reactor/reactor-netty#1400]
Hi

We are trying to configure connect / read timeout settings on the reactive http client.

Previously this was possible using TcpClient as below

https://stackoverflow.com/questions/48992992/set-timeout-in-spring-webflux-webclient

Currently this seems to be deprecated 

    @Deprecated
	public static HttpClient from(TcpClient tcpClient) {
		Objects.requireNonNull(tcpClient, "tcpClient");
		return HttpClientConnect.applyTcpClientConfig(tcpClient.configuration());
	}

and we could not find equivalent configs in httpClient.

What is the correct way of doing this?

Regards

**Comment by violetagg** [comment]
@simpleusr You should use the methods on HttpClient level directly. See the code below.

```
HttpClient.create()
          .option(ChannelOption.CONNECT_TIMEOUT_MILLIS, ...)
          .responseTimeout(Duration.ofMillis(...))
```
