### ISSUE TITLE
Exception in reactor.netty.channel.ChannelOperations#onError should be logged on the error level

### ISSUE THREAD

**Issue by JamesChenX** [reactor/reactor-netty#1407]
## Motivation

We cannot even know what happened even if an exception has occurred because reactor.netty.channel.ChannelOperations#onError suppress the exception and only log the exception on the debug level (it's unreasonable) while it should be logged on the error level. 

## Desired solution

reactor.netty.channel.ChannelOperations#onError should log the exception on the error level.

**Comment by violetagg** [comment]
@JamesChenX Please describe in more details the use case, whether it happens on the server or on the client. If possible provide some code and logs.

**Comment by JamesChenX** [comment]
**Background**
When our server tried to emit (flush) a ByteBuf instance to a client WebSocket session (via org.springframework.web.reactive.socket.WebSocketSession#send), the session was closed unexpectedly and there was no any log produced (the log level is INFO) on our servers, and no any exception was passed to our code (We have tried to log any exception if we can get one).
After debugging, I found that it's because the ByteBuf was released unexpectedly and reactor netty suppresses the exception and won't pass the exception to our code.

**Solution**
reactor.netty.channel.ChannelOperations#onError should log the exception on the ERROR level, so we can know what happened (we cannot even know there is an exception until we debug our server currently).

**Code Snippet**
```
public class ChannelOperations<INBOUND extends NettyInbound, OUTBOUND extends NettyOutbound>
		implements NettyInbound, NettyOutbound, Connection, CoreSubscriber<Void> {
	@Override
	public final void onError(Throwable t) {
		if (isDisposed()) {
			if (log.isDebugEnabled()) { // reactor-netty only log the exception on the debug level and it's unreasonable for any robust system
				log.debug(format(channel(), "An outbound error could not be processed"), t);
			}
			return;
		}
		OUTBOUND_CLOSE.set(this, Operators.cancelledSubscription());
		onOutboundError(t);
	}
}
```

**Comment by violetagg** [comment]
@JamesChenX 
https://github.com/reactor/reactor-netty/blob/8a87ab297166d03cd1ab492842f11b421589f106/reactor-netty-core/src/main/java/reactor/netty/channel/ChannelOperations.java#L233-L243

`onOutboundError(t)` is not invoked only in case of `isDisposed()`

https://github.com/reactor/reactor-netty/blob/8a87ab297166d03cd1ab492842f11b421589f106/reactor-netty-core/src/main/java/reactor/netty/channel/ChannelOperations.java#L199-L202

`isDisposed()` can happen only when:
- the client closed the connection - in that case if you subscribe for `reactor.netty.http.websocket.WebsocketInbound#receiveCloseStatus` you will receive a notification for the connection close
- the subscription has been already canceled

We are going to keep this log with a DEBUG level as we believe after addressing issue #1406 you are able to receive notifications for connection closed.
