### ISSUE TITLE
Expose more convenient way to selectively perform access logs

### ISSUE THREAD

**Issue by ctlove0523** [reactor/reactor-netty#1417]
## Motivation
Before open this issue,i read issue about access log #1357 and #436,but what i want is not log some api,for example, access log  not log this API。
~~~
@GetMapping(value = "/v5/gateway/liveness")
public Mono<Void> liveness() {
	return Mono.empty();
}
~~~
## Desired solution
If use tomcat,i can do like this:
~~~java
public class SelfTomcatAccessLog extends AccessLogValve {

    private final TomcatLogger tomcatLogger = new TomcatLogger();

    public SelfTomcatAccessLog() {
        super();
    }

    @Override
    public void log(java.io.CharArrayWriter message) {
        String messageContent = message.toString();
        if (!messageContent.contains("liveness")) {
            tomcatLogger.info(messageContent);
        }
    }
}
~~~
can reactor-netty support method like this or other methods?

**Comment by simonbasle** [comment]
Currently, it is technically possible to "filter" access logs: one needs to set up an access log `Function` that returns `null` for the cases where no access log should be performed.

This has two caveats (other than being completely undocumented):
 - setting up a `Function<AccessLogArgProvider, AccessLog>` doesn't automatically enable access logging (one needs to ALSO set the `reactor.netty.http.server.accessLogEnabled` system property to `"true"`)
 - there is currently no way for the custom `Function` to emulate the default behavior, other than copying some private code. so no way to ensure we're just filtering out some cases and the other cases are treated as if default configuration was being used...

It is also very difficult to perform integration testing: the current tests validate that the arg provider is initialized with the correct values in the handlers, but that's about it. There is currently no possibility of testing the `.accessLog(Function)` method of the configuration leads to the appropriate line in the log.

**Comment by simonbasle** [comment]
One promising solution that we're exploring with @aneveu is to expose convenience factory methods for the `Function` to be passed to `HttpServerConfiguration#accessLog(Function)`. These functions can themselves be considered factories, and the entry point would be `AccessLog` public class. We'd have:
 1. a `defaultFactory()` that just mimics the default behavior (provided access logs are switched on)
 2. a `filteringFactory(Predicate<AccessLogArgProvider>)` that apply a predicate before delegating to the above
 3. a `filterAndFormatFactory(Predicate<AccessLogArgProvider>, Function<AccessLogArgProvider,AccessLog>)` that applies both a predicate and a custom format for the access log

For the case where no filtering is needed, but a custom format is needed, one can merely write a `Function<AccessLogArgProvider,AccessLog>)` themselves.

Having both 1. and 2. would allow users to filter out some cases (eg. healtcheck endpoints), then treat other cases with a custom format (eg. admin endpoints) then fallback to the default formatting for the rest of the access logs.

**Comment by violetagg** [comment]
> Having both 1. and 2. would allow users to filter out some cases (eg. healtcheck endpoints), then treat other cases with a custom format (eg. admin endpoints) then fallback to the default formatting for the rest of the access logs.

@simonbasle If you have access log viewer where you defined which fields will be shown, how will behave this log viewer if we change format depending on the URL?

**Comment by violetagg** [comment]
> It is also very difficult to perform integration testing: the current tests validate that the arg provider is initialized with the correct values in the handlers, but that's about it. There is currently no possibility of testing the `.accessLog(Function)` method of the configuration leads to the appropriate line in the log.

Isn't it possible to do it like this https://github.com/reactor/reactor-netty/blob/master/reactor-netty-core/src/test/java/reactor/netty/transport/logging/ReactorNettyLoggingHandlerTest.java

**Comment by simonbasle** [comment]
the consequences of having heterogeneous patterns for access logs are ultimately the responsibility of the user, but maybe that use case is too niche to justify offering convenience methods. that said, we'd need method 3. in any case, to enable both filtering AND (preferably homogeneous) configuration of the log format.

maybe we don't need 1. for now, although I get the feeling that it is always useful to expose something that let users mimic the default behavior, especially when we introduce more composability.

for logging, we'll look into the appender trick which would probably work as well.

for the access log activation itself, ok let's discuss this in a separate issue.
