### ISSUE TITLE
How to switch WebSocketClientHandshaker version

### ISSUE THREAD

**Issue by liuzhongkai** [reactor/reactor-netty#1418]
I now use spring-boot-starter-webflux:2.4.0->reactor-netty:1.0.1, the WebSocketClient handshake fails, and the reactor-netty uses WebSocketVersion.V13, can this be dynamic?

**Comment by liuzhongkai** [comment]
This is the log

**Comment by liuzhongkai** [comment]
This is the log
8:18:48.397 [main] DEBUG reactor.util.Loggers$LoggerFactory - Using Slf4j logging framework
18:18:48.444 [main] DEBUG io.netty.util.internal.logging.InternalLoggerFactory - Using SLF4J as the default logging framework
18:18:48.446 [main] DEBUG io.netty.util.internal.PlatformDependent - Platform: MacOS
18:18:48.449 [main] DEBUG io.netty.util.internal.PlatformDependent0 - -Dio.netty.noUnsafe: false
18:18:48.450 [main] DEBUG io.netty.util.internal.PlatformDependent0 - Java version: 8
18:18:48.452 [main] DEBUG io.netty.util.internal.PlatformDependent0 - sun.misc.Unsafe.theUnsafe: available
18:18:48.453 [main] DEBUG io.netty.util.internal.PlatformDependent0 - sun.misc.Unsafe.copyMemory: available
18:18:48.454 [main] DEBUG io.netty.util.internal.PlatformDependent0 - java.nio.Buffer.address: available
18:18:48.455 [main] DEBUG io.netty.util.internal.PlatformDependent0 - direct buffer constructor: available
18:18:48.456 [main] DEBUG io.netty.util.internal.PlatformDependent0 - java.nio.Bits.unaligned: available, true
18:18:48.456 [main] DEBUG io.netty.util.internal.PlatformDependent0 - jdk.internal.misc.Unsafe.allocateUninitializedArray(int): unavailable prior to Java9
18:18:48.456 [main] DEBUG io.netty.util.internal.PlatformDependent0 - java.nio.DirectByteBuffer.<init>(long, int): available
18:18:48.457 [main] DEBUG io.netty.util.internal.PlatformDependent - sun.misc.Unsafe: available
18:18:48.457 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.tmpdir: /var/folders/p8/4p6pxfhs79qccl3jy3dghzjr0000gn/T (java.io.tmpdir)
18:18:48.457 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.bitMode: 64 (sun.arch.data.model)
18:18:48.460 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.maxDirectMemory: 7635730432 bytes
18:18:48.461 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.uninitializedArrayAllocationThreshold: -1
18:18:48.464 [main] DEBUG io.netty.util.internal.CleanerJava6 - java.nio.ByteBuffer.cleaner(): available
18:18:48.464 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.noPreferDirect: false
18:18:48.640 [main] DEBUG reactor.netty.tcp.TcpResources - [http] resources will use the default LoopResources: DefaultLoopResources {prefix=reactor-http, daemon=true, selectCount=16, workerCount=16}
18:18:48.640 [main] DEBUG reactor.netty.tcp.TcpResources - [http] resources will use the default ConnectionProvider: reactor.netty.resources.DefaultPooledConnectionProvider@69a10787
18:18:48.755 [main] DEBUG io.netty.util.ResourceLeakDetector - -Dio.netty.leakDetection.level: simple
18:18:48.756 [main] DEBUG io.netty.util.ResourceLeakDetector - -Dio.netty.leakDetection.targetRecords: 4
18:18:49.050 [main] DEBUG org.springframework.web.reactive.socket.client.ReactorNettyWebSocketClient - Connecting to ws://101.132.226.236:10000
18:18:49.058 [main] DEBUG reactor.netty.resources.DefaultLoopKQueue - Default KQueue support : false
18:18:49.074 [main] DEBUG reactor.netty.resources.DefaultLoopEpoll - Default Epoll support : false
18:18:49.078 [main] DEBUG io.netty.channel.MultithreadEventLoopGroup - -Dio.netty.eventLoopThreads: 32
18:18:49.109 [main] DEBUG io.netty.util.internal.InternalThreadLocalMap - -Dio.netty.threadLocalMap.stringBuilder.initialSize: 1024
18:18:49.109 [main] DEBUG io.netty.util.internal.InternalThreadLocalMap - -Dio.netty.threadLocalMap.stringBuilder.maxSize: 4096
18:18:49.116 [main] DEBUG io.netty.channel.nio.NioEventLoop - -Dio.netty.noKeySetOptimization: false
18:18:49.117 [main] DEBUG io.netty.channel.nio.NioEventLoop - -Dio.netty.selectorAutoRebuildThreshold: 512
18:18:49.128 [main] DEBUG io.netty.util.internal.PlatformDependent - org.jctools-core.MpscChunkedArrayQueue: available
18:18:49.161 [main] DEBUG io.netty.util.NetUtil - -Djava.net.preferIPv4Stack: false
18:18:49.161 [main] DEBUG io.netty.util.NetUtil - -Djava.net.preferIPv6Addresses: false
18:18:49.172 [main] DEBUG io.netty.util.NetUtilInitializations - Loopback interface: lo0 (lo0, 0:0:0:0:0:0:0:1%lo0)
18:18:49.173 [main] DEBUG io.netty.util.NetUtil - Failed to get SOMAXCONN from sysctl and file /proc/sys/net/core/somaxconn. Default: 128
18:18:49.213 [main] DEBUG reactor.netty.resources.PooledConnectionProvider - Creating a new [http] client pool [PoolFactory{evictionInterval=PT0S, leasingStrategy=fifo, maxConnections=500, maxIdleTime=-1, maxLifeTime=-1, metricsEnabled=false, pendingAcquireMaxCount=1000, pendingAcquireTimeout=45000}] for [/101.132.226.236:10000]
18:18:49.310 [main] DEBUG io.netty.channel.DefaultChannelId - -Dio.netty.processId: 70783 (auto-detected)
18:18:49.316 [main] DEBUG io.netty.channel.DefaultChannelId - -Dio.netty.machineId: ac:de:48:ff:fe:00:11:22 (auto-detected)
18:18:49.362 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.numHeapArenas: 32
18:18:49.362 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.numDirectArenas: 32
18:18:49.362 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.pageSize: 8192
18:18:49.362 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.maxOrder: 11
18:18:49.363 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.chunkSize: 16777216
18:18:49.363 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.smallCacheSize: 256
18:18:49.363 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.normalCacheSize: 64
18:18:49.363 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.maxCachedBufferCapacity: 32768
18:18:49.363 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.cacheTrimInterval: 8192
18:18:49.363 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.cacheTrimIntervalMillis: 0
18:18:49.363 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.useCacheForAllThreads: true
18:18:49.363 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.maxCachedByteBuffersPerChunk: 1023
18:18:49.381 [main] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.allocator.type: pooled
18:18:49.381 [main] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.threadLocalDirectBufferSize: 0
18:18:49.381 [main] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.maxThreadLocalCharBufferSize: 16384
18:18:49.418 [reactor-http-nio-2] DEBUG reactor.netty.resources.DefaultPooledConnectionProvider - [id: 0x73bb8967] Created a new pooled channel, now 1 active connections and 0 inactive connections
18:18:49.444 [reactor-http-nio-2] DEBUG io.netty.buffer.AbstractByteBuf - -Dio.netty.buffer.checkAccessible: true
18:18:49.444 [reactor-http-nio-2] DEBUG io.netty.buffer.AbstractByteBuf - -Dio.netty.buffer.checkBounds: true
18:18:49.445 [reactor-http-nio-2] DEBUG io.netty.util.ResourceLeakDetectorFactory - Loaded default ResourceLeakDetector: io.netty.util.ResourceLeakDetector@737526ff
18:18:49.448 [reactor-http-nio-2] DEBUG reactor.netty.transport.TransportConfig - [id: 0x73bb8967] Initialized pipeline DefaultChannelPipeline{(reactor.left.httpCodec = io.netty.handler.codec.http.HttpClientCodec), (reactor.right.reactiveBridge = reactor.netty.channel.ChannelOperationsHandler)}
18:18:49.501 [reactor-http-nio-2] DEBUG reactor.netty.resources.DefaultPooledConnectionProvider - [id: 0x73bb8967, L:/192.168.7.83:49559 - R:/101.132.226.236:10000] Registering pool release on close event for channel
18:18:49.501 [reactor-http-nio-2] DEBUG reactor.netty.resources.DefaultPooledConnectionProvider - [id: 0x73bb8967, L:/192.168.7.83:49559 - R:/101.132.226.236:10000] Channel connected, now 1 active connections and 0 inactive connections
18:18:49.503 [reactor-http-nio-2] DEBUG reactor.netty.resources.DefaultPooledConnectionProvider - [id: 0x73bb8967, L:/192.168.7.83:49559 - R:/101.132.226.236:10000] onStateChange(PooledConnection{channel=[id: 0x73bb8967, L:/192.168.7.83:49559 - R:/101.132.226.236:10000]}, [connected])
18:18:49.516 [reactor-http-nio-2] DEBUG reactor.netty.resources.DefaultPooledConnectionProvider - [id: 0x73bb8967, L:/192.168.7.83:49559 - R:/101.132.226.236:10000] onStateChange(GET{uri=/, connection=PooledConnection{channel=[id: 0x73bb8967, L:/192.168.7.83:49559 - R:/101.132.226.236:10000]}}, [configured])
18:18:49.516 [reactor-http-nio-2] DEBUG reactor.netty.http.client.HttpClientConnect - [id: 0x73bb8967, L:/192.168.7.83:49559 - R:/101.132.226.236:10000] Handler is being applied: {uri=ws://101.132.226.236:10000/, method=GET}
18:18:49.521 [reactor-http-nio-2] DEBUG reactor.netty.resources.DefaultPooledConnectionProvider - [id: 0x73bb8967, L:/192.168.7.83:49559 - R:/101.132.226.236:10000] onStateChange(GET{uri=/, connection=PooledConnection{channel=[id: 0x73bb8967, L:/192.168.7.83:49559 - R:/101.132.226.236:10000]}}, [request_prepared])
18:18:49.553 [reactor-http-nio-2] DEBUG reactor.netty.ReactorNetty - [id: 0x73bb8967, L:/192.168.7.83:49559 - R:/101.132.226.236:10000] Added encoder [reactor.left.httpAggregator] at the beginning of the user pipeline, full pipeline: [reactor.left.httpCodec, reactor.left.httpAggregator, reactor.right.reactiveBridge, DefaultChannelPipeline$TailContext#0]
18:18:49.553 [reactor-http-nio-2] DEBUG reactor.netty.ReactorNetty - [id: 0x73bb8967, L:/192.168.7.83:49559 - R:/101.132.226.236:10000] Non Removed handler: reactor.left.httpMetricsHandler, context: null, pipeline: DefaultChannelPipeline{(reactor.left.httpCodec = io.netty.handler.codec.http.HttpClientCodec), (reactor.left.httpAggregator = io.netty.handler.codec.http.HttpObjectAggregator), (reactor.right.reactiveBridge = reactor.netty.channel.ChannelOperationsHandler)}
18:18:49.553 [reactor-http-nio-2] DEBUG reactor.netty.http.client.HttpClientOperations - [id: 0x73bb8967, L:/192.168.7.83:49559 - R:/101.132.226.236:10000] Attempting to perform websocket handshake with ws://101.132.226.236:10000/
18:18:51.779 [reactor-http-nio-2] DEBUG io.netty.handler.codec.http.websocketx.WebSocketClientHandshaker13 - WebSocket version 13 client handshake key: zLWCVOAaT37m6St96uziWg==, expected response: Q/WBDUmUn4y41Kl97NUxUFc7jFo=
18:18:51.801 [reactor-http-nio-2] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.maxCapacityPerThread: 4096
18:18:51.801 [reactor-http-nio-2] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.maxSharedCapacityFactor: 2
18:18:51.801 [reactor-http-nio-2] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.linkCapacity: 16
18:18:51.801 [reactor-http-nio-2] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.ratio: 8
18:18:51.801 [reactor-http-nio-2] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.delayedQueue.ratio: 8
18:18:53.131 [reactor-http-nio-2] WARN reactor.netty.http.client.HttpClientConnect - [id: 0x73bb8967, L:/192.168.7.83:49559 - R:/101.132.226.236:10000] The connection observed an error
io.netty.handler.codec.http.websocketx.WebSocketClientHandshakeException: Invalid challenge. Actual: Kfh9QIsMVZcl6xEPYxPHzW8SZ8w=. Expected: Q/WBDUmUn4y41Kl97NUxUFc7jFo=
	at io.netty.handler.codec.http.websocketx.WebSocketClientHandshaker13.verify(WebSocketClientHandshaker13.java:288)
	at io.netty.handler.codec.http.websocketx.WebSocketClientHandshaker.finishHandshake(WebSocketClientHandshaker.java:302)
	at reactor.netty.http.client.WebsocketClientOperations.onInboundNext(WebsocketClientOperations.java:119)
	at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:94)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

**Comment by violetagg** [comment]
@liuzhongkai Do you provide request header `sec-websocket-version`?

**Comment by violetagg** [comment]
@liuzhongkai Sorry for the client `WebSocketVersion.V13` currently is hardcoded. We need to expose a configuration for the version via `WebsocketClientSpec`.

**Comment by liuzhongkai** [comment]
Hi, that can only wait for the next version at the moment, looking forward to
