### ISSUE TITLE
Provide a way to configure `AccessLog` programatically

### ISSUE THREAD

**Issue by aneveu** [reactor/reactor-netty#1428]
Should we allow the users to configure `AccesLog` programmatically?

## Motivation
Actually in order to enable `AccessLog`, one needs to activate it through the `ACCESS_LOG_ENABLED` system property declared in server configuration whereas the `accessLog` method just provides configuration option, which might be confusing for the user.

## Desired solution
The user could used different combination to enable or not AccessLog, and specify or not a custom configuration, for example:

```java
HttpServer.create()
    .port(8080)
    .route(r -> r.get("/hello",
    .(req, res) -> res.header(CONTENT_TYPE, TEXT_PLAIN)
    .sendString(Mono.just("Hello World!"))))

    .accessLog(false, null) // don't enable AccessLog
    .accessLog(true, DEFAULT) // enable AccessLog and use default configuration
    .accessLog(true, argProvider -> AccessLog.create("user-agent={}", argProvider.requestHeader("user-agent"))) //enable AccessLog and use custom configuration

    .bindNow()
    .onDispose()
    .block();
```

**Comment by violetagg** [comment]
@aneveu What about 2 methods?

`accessLog(boolean)` this enables/disables the default (access log with Common Log Format)
`accessLog(boolean, AccessLogFactory)` this enables/disables access log with Custom Log Format

**Comment by simonbasle** [comment]
given that #1417 overlaps a bit with that one, we might want to only introduce `.accessLog(boolean)` in this iteration, then use #1421 to add the variant with a factory and deprecate the old `Function`-based variant.

**Comment by rstoyanchev** [comment]
> accessLog(boolean) this enables/disables the default (access log with Common Log Format)
> accessLog(boolean, AccessLogFactory) this enables/disables access log with Custom Log Format

I'm wondering if when the intent is to disable, would an `AccessLogFactory` even need to be provided or would be `null` in that case? If so then perhaps just `accessLog(AccessLogFactory)` is enough with a separate method to disable it, or alternatively maybe the `AccessLogFactory` could have some special instance for no access log.

**Comment by violetagg** [comment]
> > accessLog(boolean) this enables/disables the default (access log with Common Log Format)
> > accessLog(boolean, AccessLogFactory) this enables/disables access log with Custom Log Format
> 
> I'm wondering if when the intent is to disable, would an `AccessLogFactory` even need to be provided or would be `null` in that case? If so then perhaps just `accessLog(AccessLogFactory)` is enough with a separate method to disable it, or alternatively maybe the `AccessLogFactory` could have some special instance for no access log.

@rstoyanchev The idea is when you are in the cloud, you take the enable/disable information from the active profile.
So you will have something like this
`accessLog(envEnable/Disable, AccessLogFactory)`

But we may want to have `Supplier`in case it is disabled we will not invoke that `Supplier` at all
`accessLog(boolean, Supplier<AccessLogFactory>)`

Wdyt?

**Comment by rstoyanchev** [comment]
For property based initialization, `accessLog(boolean)` should be sufficient right? For `(boolean, AccessLogFactory)` something would need to provide a factory and if it is provided then it implied "enabled".

**Comment by simonbasle** [comment]
No, I don't think a `Supplier` is necessary at all. A `Function` is already lazy by nature.

For the second method, I wonder: customizing the access log seems to imply one _has_ to use the programmatic approach, right? So the profile requirement would not really apply there?

Unless you really anticipate people will mix the two approaches and provide a factory while delegating to the "profile" to chose whether or not to enable it?

I have the same sentiment as @rstoyanchev from the beginning that `.accessLog(AccessLogFactory)` should imply activation of access logging...

**Comment by violetagg** [comment]
@rstoyanchev @simonbasle Let say we have this:

```
@Component
public class MyNettyWebServerCustomizer
        implements WebServerFactoryCustomizer<NettyReactiveWebServerFactory> {
    @Override
    public void customize(NettyReactiveWebServerFactory factory) {
        factory.addServerCustomizers(httpServer -> {
             return httpServer.wiretap(true)
                                          .accessLog(ENV-VAR, AccessLogFactory);
        });
    }
}
```

How you propose to control enable/disable access log except having a property in my cloud profile that controls that.
Should I change the code every time when I want to enable/disable?

**Comment by simonbasle** [comment]
Wouldn't it be possible to do this:

```java
@Component
public class MyNettyWebServerCustomizer
        implements WebServerFactoryCustomizer<NettyReactiveWebServerFactory> {
    @Override
    public void customize(NettyReactiveWebServerFactory factory) {
        factory.addServerCustomizers(httpServer -> {
            HttpServer server = httpServer.wiretap(true);
            if (profile.getProperty("accesslog")) httpServer = httpServer.accessLog(AccessLogFactory);
            return httpServer;
        });
    }
}
```

That's not terrible boilerplate to write for the percentage of users that want to conditionally enable while programmatically customize the access log.

If we look at `HttpServer`, eg. `forwarded` configuration, we see similar patterns:
 - `forwarded(boolean)` for conditional enabling, with default handler
 - `forwarded(BiFunction)` for fine tuning (no boolean, passing a bifunction means activating it)

**Comment by simonbasle** [comment]
`wiretap` is the same: there is the base, property-friendly `wiretap(boolean)`, but then you have `wiretap(String, LogLevel)`, right?

**Comment by violetagg** [comment]
> Wouldn't it be possible to do this:
> 
> ```java
> @Component
> public class MyNettyWebServerCustomizer
>         implements WebServerFactoryCustomizer<NettyReactiveWebServerFactory> {
>     @Override
>     public void customize(NettyReactiveWebServerFactory factory) {
>         factory.addServerCustomizers(httpServer -> {
>             HttpServer server = httpServer.wiretap(true);
>             if (profile.getProperty("accesslog")) httpServer = httpServer.accessLog(AccessLogFactory);
>             return httpServer;
>         });
>     }
> }
> ```
> 
> That's not terrible boilerplate to write for the percentage of users that want to conditionally enable while programmatically customize the access log.
> 
> If we look at `HttpServer`, eg. `forwarded` configuration, we see similar patterns:
> 
> * `forwarded(boolean)` for conditional enabling, with default handler
> * `forwarded(BiFunction)` for fine tuning (no boolean, passing a bifunction means activating it)

`forwarde(BiFunction)` has a different meaning than `accessLog(...)` because `forwarde(BiFunction)` says enable/disable  based on request/response

the API closer to this is 
`metrics(.....)`

**Comment by simonbasle** [comment]
Ok so that's the API we're settling on:

 - `accessLog(boolean)` allows to programmatically enable/disable access logging with default factory (takes precedence over `ACCESS_LOG` constant from sysprop
 - `accessLog(boolean, AccessLogFactory)` (to be added via #1417) to programmatically customize the factory BUT potentially ignore that factory if the `boolean` part is `false` (takes precedence over the sysprop, if `false` the function is never invoked, might even not be stored)

Each option is self-sufficient. If calling `accessLog(true)` after `accessLog(true, myFactory)` for example would remove the custom factory.
