### ISSUE TITLE
NullPointerException on connectionInfo.getScheme() in HttpServerOperations for Unix Domain Sockets

### ISSUE THREAD

**Issue by anupam-contaque** [reactor/reactor-netty#1434]
`ConnectionInfo` in `HttpServerOperations`  is annotated as `@Nullable` but there isn't any null check before calling `getScheme()`

https://github.com/reactor/reactor-netty/blob/380a10adb86cf5711bb68b25c715ead9abf9afae/reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerOperations.java#L375

See https://github.com/spring-projects/spring-boot/issues/24529#issuecomment-747158696

**Comment by violetagg** [comment]
@anupam-contaque PTAL PR #1436
