### ISSUE TITLE
Is it possible to close connection when server receive SYN from client?

### ISSUE THREAD

**Issue by ctlove0523** [reactor/reactor-netty#1441]
I have a tcp server and i want to control concurrency of establish connection between client to my server,like one second only process 100 establish connection request,the 101 request will be refused.So I need close connection in second step of 3-way-handshake.
![](https://camo.githubusercontent.com/9fa277572eb26f706f221812d4fb67f03b9e654a4a2b94ea8abcfb1ae95bef8b/687474703a2f2f75706c6f61642e77696b696d656469612e6f72672f77696b6970656469612f636f6d6d6f6e732f612f61322f5463705f73746174655f6469616772616d5f66697865642e737667)

## Motivation
If we can do something in step 2 of 3-way-handshake,then we can make a **RateLimiter** to protect our server avoid run out of CPU.

## Desired solution
I read current code of [TcpServer](https://github.com/reactor/reactor-netty/blob/master/reactor-netty-core/src/main/java/reactor/netty/tcp/TcpServer.java).it support some callback like `doOnUnbound`,`doOnConnection` and `doOnBound`,is it possible support add a callback like`doOneSynReceived` to do this?

**Comment by violetagg** [comment]
@ctlove0523 I don't know for a Netty event that can be used for this scenario. The closest event is `io.netty.channel.ChannelInboundHandler#channelActive` and we already expose that via `ConnectionObserver`, state https://projectreactor.io/docs/netty/release/api/reactor/netty/ConnectionObserver.State.html#CONNECTED

`TcpServer.childObserve((connection, state) -> ...)`

**Comment by ctlove0523** [comment]
@violetagg thanks,i realize this needs netty support and i will go to the netty community for help.
