### ISSUE TITLE
SSLSessionContext Memory leak issue

### ISSUE THREAD

**Issue by yangbongsoo** [reactor/reactor-netty#1443]
Hello. I have a question about SSLSessionContext.

at first, my server heap memory limit is 2G and my server memory went up little by little.

<img width="1434" alt="스크린샷 2020-12-28 오후 2 39 48" src="https://user-images.githubusercontent.com/7060510/103192033-91430d00-491a-11eb-8a50-5c6e64997ed6.png">

and then I got a error message as below. 
```
2020-10-08 15:15:23.139 ERROR default    c.n.s.p.GlobalErrorWebExceptionHandler - [GlobalErrorWebExceptionHandler] SSLException type
io.netty.handler.ssl.SslHandshakeTimeoutException: handshake timed out after 10000ms
        at io.netty.handler.ssl.SslHandler$5.run(SslHandler.java:2054)
        Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException:
Error has been observed at the following site(s):
        |_ checkpoint ⇢ org.springframework.cloud.gateway.filter.WeightCalculatorWebFilter [DefaultWebFilterChain]
        |_ checkpoint ⇢ org.springframework.boot.actuate.metrics.web.reactive.server.MetricsWebFilter [DefaultWebFilterChain]
        |_ checkpoint ⇢ HTTP POST "/lius-api/lam/v1/penalty/auth/block?blockType=MI&blockKey=46c80e988e3bc903d12d52353f716a58&limit=1&valid=true" [ExceptionHandlingWebHandler]
Stack trace:
                at io.netty.handler.ssl.SslHandler$5.run(SslHandler.java:2054)
                at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
                at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:170)
                at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
                at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
                at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
                at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
                at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
                at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
                at java.lang.Thread.run(Thread.java:745)
```

As the limit (2G) approached, a few seconds of minor gc occurred, resulting in ssl handshake timeout error.

so I made heap dump.

<img width="1418" alt="스크린샷 2020-12-28 오후 2 42 13" src="https://user-images.githubusercontent.com/7060510/103192132-ec74ff80-491a-11eb-8f39-7d6192bbcc8d.png">

Eclipse Memory Analyzer analyzed the ssl session memory cache part with leak spect.
but It wasn't clear. so I increased the memory size to 4G. And I upgrade the jdk8 version to 275.

However, the problem has not been solved.

before
<img width="1392" alt="스크린샷 2020-12-28 오후 2 47 01" src="https://user-images.githubusercontent.com/7060510/103192317-92286e80-491b-11eb-8f8c-4cc5aadf475b.png">

after
<img width="1411" alt="스크린샷 2020-12-28 오후 2 47 26" src="https://user-images.githubusercontent.com/7060510/103192334-a10f2100-491b-11eb-827a-778725383fc4.png">

The important point is this. **Servers with low requests (same version) do not experience this issue.**
and my httpclient pool type is disabled. but I'm not sure it is related.

Please give me some advice on what I need to check. Thank you. 

## Steps to Reproduce
I can't make reproduce project because of ssl issue.
Several different https domains are needed for testing, but are difficult to have.

## Your Environment
OS version : CentOS 7.7
JVM version (`java -version`): jdk-8u275-linux-x64
Spring Boot version : 2.3.4.RELEASE
SCG version : 2.2.5.RELEASE
reactor-netty version : 0.9.12.RELEASE

**Comment by bilak** [comment]
Hi, I've seen simillar issue in our microservices. There was an issue with caching of ssl context in jdk. Try to start your services with this parameters `-Djavax.net.ssl.sessionTimeout=900 -Djavax.net.ssl.sessionCacheSize=1000`. This changed something for us, but we can still see some memory leaks somewhere. Not easy to track them.

**Comment by yangbongsoo** [comment]
@bilak thanks to reply. I also though that problem was by jdk. so I updated jdk version to 275.
Because they updated the default SSL session cache size to 20480 (https://bugs.openjdk.java.net/browse/JDK-8210985).

But even if I upgrade jdk version, the problem was not solved.
I'm not sure It is jdk issue. so I wrote this issue.

I couldn't find jvm option in google search. how did you find this?
`-Djavax.net.ssl.sessionTimeout=900 -Djavax.net.ssl.sessionCacheSize=1000`

I found the java code. but It is not sure.
```java
SSLContext.getDefault().getServerSessionContext().setSessionCacheSize(20480);
SSLContext.getDefault().getServerSessionContext().setSessionTimeout(86400); // 24 hour
//  or 
System.setProperty("javax.net.ssl.sessionCacheSize", "20480");
```

anyway, you told me you have  memory leak problem yet. I wonder your next step.

**Comment by bilak** [comment]
@yangbongsoo everything depends on traffic in your service. If there is a lot o ssl calls potentialy the cache could be a problem. Try to lower the time and you will se if that helps a bit.  
I have problem with jvm setup because I'm working in Kubernetes cluster and that's giving me headakes. Don't know how to properly setup the jvm flags and we have there some leaks that are being solved also by spring libraries.

**Comment by violetagg** [comment]
@yangbongsoo Can you provide more information how you configure the server and the client? Can you check this one also https://github.com/reactor/reactor-netty/issues/1054? If you switch to OpenSsl is there any difference?

**Comment by yangbongsoo** [comment]
@violetagg 

the jdk8-275 version also increases steadily to 3.84G.

![스크린샷 2021-01-22 오후 3 08 09](https://user-images.githubusercontent.com/7060510/105472464-51840100-5cdf-11eb-948e-d2bc91ef7210.png)

However, it is maintained without further increase from 3.84G.

![스크린샷 2021-01-22 오후 3 08 24](https://user-images.githubusercontent.com/7060510/105472473-53e65b00-5cdf-11eb-8104-d4264466e826.png)

I use spring cloud gateway. 
So I made httpClient by choosing the settings I used.
The real code uses the httpClient created by Gateway AutoConfiguration. And the pool type is DISABLED.

```java
public class SSLTest {
	public static void main(String[] args) throws InterruptedException {

		// pool type is DISABLED
		ConnectionProvider connectionProvider = ConnectionProvider.newConnection();
		HttpClient httpClient = HttpClient.create(connectionProvider);
		httpClient.tcpConfiguration(tcpClient -> setTcpOptions(tcpClient));

		for (int i = 0; i < 10_000_000; i++) {
			int j = i;
			httpClient
				.get()
				.uri("https://api.covid19api.com/")
				.response((resp, respContent) -> respContent.aggregate().asString())
				.doOnNext(respBody -> System.out.println(j + ": " + respBody.substring(0, 20)))
				.single().block();
			Thread.sleep(1500);
		}
	}

	public static TcpClient setTcpOptions(TcpClient tcpClient) {
		HttpClientProperties.Ssl ssl = new HttpClientProperties.Ssl();
		return tcpClient
			.secure(sslContextSpec -> {
				SslContextBuilder sslContextBuilder = SslContextBuilder.forClient();
				sslContextBuilder.trustManager(InsecureTrustManagerFactory.INSTANCE);
				sslContextBuilder = sslContextBuilder
						.keyManager(ssl.getKeyManagerFactory());

				sslContextSpec.sslContext(sslContextBuilder)
					.defaultConfiguration(ssl.getDefaultConfigurationType())
					.handshakeTimeout(ssl.getHandshakeTimeout())
					.closeNotifyFlushTimeout(ssl.getCloseNotifyFlushTimeout())
					.closeNotifyReadTimeout(ssl.getCloseNotifyReadTimeout());
			});
	}
}
```

**Comment by violetagg** [comment]
@yangbongsoo Actually you are observing exactly what was the issue here https://github.com/reactor/reactor-netty/issues/1054#issuecomment-610861166

So either configure the security directly with `HttpClient.secure` or use `HttpClient.from`

**Comment by yangbongsoo** [comment]
thank you to advise.
I'll do stress test using below code.
after that I'll report to you.
```java
		// pool type is DISABLED
		ConnectionProvider connectionProvider = ConnectionProvider.newConnection();
		HttpClient httpClient = HttpClient.create(connectionProvider);

		HttpClientProperties.Ssl ssl = new HttpClientProperties.Ssl();
		httpClient.secure(sslContextSpec -> {
			SslContextBuilder sslContextBuilder = SslContextBuilder.forClient();
			sslContextBuilder.trustManager(InsecureTrustManagerFactory.INSTANCE);
			sslContextBuilder.keyManager(ssl.getKeyManagerFactory());

			sslContextSpec.sslContext(sslContextBuilder)
				.defaultConfiguration(ssl.getDefaultConfigurationType())
				.handshakeTimeout(ssl.getHandshakeTimeout())
				.closeNotifyFlushTimeout(ssl.getCloseNotifyFlushTimeout())
				.closeNotifyReadTimeout(ssl.getCloseNotifyReadTimeout());
		});
```

**Comment by violetagg** [comment]
@yangbongsoo I'll be interested in the results when you have them. Thanks.

**Comment by violetagg** [comment]
@yangbongsoo Let me close this one. If there is still an issue, we can reopen it.

**Comment by yangbongsoo** [comment]
@violetagg For Your Information, I upgrade jdk version to jdk-8u275, and above problem was solved ... 
thank you for advice.
