### ISSUE TITLE
Silent discard of HTTP request

### ISSUE THREAD

**Issue by idikshit** [reactor/reactor-netty#1449]
I was trying to figure out a way to silently discard an incoming HTTP Request without sending back any response. Is there any way I can achieve this?. Thanks in advance.

**Comment by violetagg** [comment]
@idikshit Please ask questions either on [Gitter](https://gitter.im/reactor/reactor-netty) or [stackoverflow.com](https://stackoverflow.com/questions/tagged/reactor-netty)
