### ISSUE TITLE
 '$PERSISTENT_CHANNEL'  Exception when ReactorNetty is used in multi classloader project

### ISSUE THREAD

**Issue by leleueri** [reactor/reactor-netty#1471]
Hi,

I'm currently using reactor-netty (0.9.11.RELEASE) through SpringData R2DBC (v 1.1.0-RELEASE).
I'm facing an issue in my projet with the ReactorNetty class.

Here is some Context. My application use a plugin system, each plugin has this own classloader that inherit from the "main classloader". The main classloader uses netty in order to expose HTTP Endpoint. I need to implement two different SpringData/R2DBC plugins that may run simultanously according to the application deployment.

When the two plugins run simultanously, I have the following exception:
```
Caused by: java.lang.IllegalArgumentException: '$PERSISTENT_CHANNEL' is already in use
	at io.netty.util.ConstantPool.createOrThrow(ConstantPool.java:109)
	at io.netty.util.ConstantPool.newInstance(ConstantPool.java:91)
	at io.netty.util.AttributeKey.newInstance(AttributeKey.java:55)
	at reactor.netty.ReactorNetty.<clinit>(ReactorNetty.java:829)
	... 136 common frames omitted
```
https://github.com/reactor/reactor-netty/blob/8a87ab297166d03cd1ab492842f11b421589f106/reactor-netty-core/src/main/java/reactor/netty/ReactorNetty.java#L943

This is due to the fact that the ContantPool is hold by the main classload through the static variable of AttributeKey named `pool` that is also used by the Http Connection pool.  When the first R2DBC want to initialize the AttributeKey  the ConstantPool create the instance but when the second one try to do it, the exception occurs because '$PERSISTENT_CHANNEL' has been initialized by the first plugin.

I don't know if some one already faced to this issue and if there are a clean workaround.

## Expected Behavior
Both plugin start and initialize ReactorNetty without exception.

## Actual Behavior
When second plugin start, the `java.lang.IllegalArgumentException: '$PERSISTENT_CHANNEL' is already in use` occurs 

## Possible Solution

I'm not comfortable with the ReactoNetty source code, but may be providing the ReactorNetty class as a Singleton taking as 'getInstance' parameters the AttributeKey names may solve this issue. Thanks to this, it will be possible to define custom names at plugin bootstrap and avoid the name collision.

## Your Environment

* Reactor version(s) used: 0.9.11
* Other relevant libraries versions (eg. `netty`, ...): Netty 4.1.49 / SpringData R2DBC (v 1.1.0-RELEASE).
* JVM version (`java -version`): 11.0.7

**Comment by violetagg** [comment]
@leleueri I'm wondering whether we can use `io.netty.util.AttributeKey#valueOf(java.lang.String)`

**Comment by leleueri** [comment]
Hi @violetagg ,

I missed this one, indeed having a static method that checks first is the AttributeKey exists before creating a new one will be better.

I will try it and open a PR if it is ok.

**Comment by violetagg** [comment]
> Hi @violetagg ,
> 
> I missed this one, indeed having a static method that checks first is the AttributeKey exists before creating a new one will be better.
> 
> I will try it and open a PR if it is ok.

This will be great!

**Comment by violetagg** [comment]
@leleueri Were you able to take a look at this?

**Comment by leleueri** [comment]
Sorry @violetagg, I was quite busy last week, I will try to look at it this week.

**Comment by violetagg** [comment]
> Sorry @violetagg, I was quite busy last week, I will try to look at it this week.

Thanks

**Comment by leleueri** [comment]
Hi @violetagg 

I have just create the PR #1503 .
I tried to write a simple Unit Test to validate the fix but unfortunately I was no able to write it. :(

I tested this fix on my project and the issue is solved.

**Comment by violetagg** [comment]
@leleueri Thanks for the PR! I added one suggestion there.

**Comment by leleueri** [comment]
@violetagg I made the change and override my last commit.
