### ISSUE TITLE
PooledConnectionProvider is creating multiple channel pools for same http client and address

### ISSUE THREAD

**Issue by kushagraThapar** [reactor/reactor-netty#1472]
After upgrading from reactor-netty 0.9.15.RELEASE to 1.x.x (tested 1.0.3) as well, we are seeing `PooledConnectionProvider` is creating multiple channel pools from same http client and for same remote addresses. 

## Expected Behavior
For the same remote address and from the same client, existing channel pools should be re-used. 

## Actual Behavior
In latest version of reactor-netty, `PooledConnectionProvider` is creating multiple channel pools from same http client and for same remote addresses. 

This change in behavior is causing multiple channel pools being created, and exhausting the network resources, resulting in `ConnectionTimeout` Exceptions. 

## Steps to Reproduce
Here is the repro code: 
https://github.com/kushagraThapar/reactor-netty-test

Run the main application, and you will see that for 1000 requests, 1000 new channel pools are created. 
Interesting thing to note is, if you change the pom.xml and point to 0.9.15.RELEASE of reactor-netty, you will only see 5 channel pools being created (1 for each type of remote address). 

P.S: To change the pom.xml to reactor-netty version 0.9.15.RELEASE, you will have to change slight code in `ReactorNettyClient.java` in the repro, because of non-backward compatibility in the major version. 

## Possible Solution
Afters some digging, I found out that this is because of the recent change in the way of creating `PooledConnectionProvider.PoolKey` object. When calculating the `pipelineKey`, `config.channelHash()` is called, which has added new fields for creating hash value for `TransportConfig`, specially `ConnectionObserver`. 

I believe this is causing the issue for our Azure Cosmos DB Java SDK internal http client, because we use `observe` API for each http request, which is important for us to calculate some internal metrics. You can see it in the sample code here : https://github.com/kushagraThapar/reactor-netty-test/blob/master/src/main/java/com/example/ReactorNettyClient.java#L93 

## Your Environment

* Reactor version(s) used: 1.0.1, 1.0.2, 1.0.3
* Other relevant libraries versions (eg. `netty`, ...): reactor-core - latest versions (3.4.x), slf4j, log4j
* JVM version (`java -version`): 1.8
* OS and version (eg. `uname -a`): macOS 11.1

**Comment by violetagg** [comment]
@kushagraThapar You are setting the observer every time when you send a request. For us this is a different observer, we do not check that configuration in 0.9.x, it is checked only in 1.0.x as we consider this incompatible change.
You need to move that to the main client configuration.

```
    public Mono<HttpResponse> send(final HttpRequest request, Duration responseTimeout) {
        Objects.requireNonNull(request.httpMethod());
        Objects.requireNonNull(request.uri());

        final AtomicReference<ReactorNettyHttpResponse> responseReference = new AtomicReference<>();

        return this.httpClient
            .observe((connection, state) -> {
                Instant time = Instant.now();
                if (state.equals(HttpClientState.CONNECTED) || state.equals(HttpClientState.ACQUIRED)) {
                    request.reactorNettyRequestRecord().setTimeConnected(time);
                } else if (state.equals(HttpClientState.CONFIGURED)) {
                    request.reactorNettyRequestRecord().setTimeConfigured(time);
                } else if (state.equals(HttpClientState.REQUEST_SENT)) {
                    request.reactorNettyRequestRecord().setTimeSent(time);
                } else if (state.equals(HttpClientState.RESPONSE_RECEIVED)) {
                    request.reactorNettyRequestRecord().setTimeReceived(time);
                }
            })
```

**Comment by violetagg** [comment]
@kushagraThapar PTAL #1473 - a test for the various configurations that can affect the connection pool creation.

**Comment by kushagraThapar** [comment]
@violetagg - thanks for adding the tests cases, it helps in understanding this behavior. 
However, as you see, in the `observe` API call, we update the time metrics for each request, I am not sure how can I set this configuration when setting up the client as I don't have access to `request` object during client creation.

**Comment by violetagg** [comment]
@kushagraThapar Can you use Reactor Context + Netty attributes?

```
@Test
void test() {
	AttributeKey<String> attributeKey = AttributeKey.valueOf("propagated");

	HttpClient client =
		HttpClient.create(ConnectionProvider.create("test", 1))
			.observe((conn, state) -> {
				if (state.equals(HttpClientState.CONNECTED) || state.equals(HttpClientState.ACQUIRED)) {
					if (conn instanceof ConnectionObserver) {
						ConnectionObserver observer = (ConnectionObserver) conn;
						String propagated = observer.currentContext().getOrDefault("key", "empty");
						System.out.println(state + " " + propagated);
						conn.channel().attr(attributeKey).set(propagated);
					}
				}
				else if (state.equals(HttpClientState.CONFIGURED)) {
					System.out.println(state + " " + conn.channel().attr(attributeKey));
				}
				else if (state.equals(HttpClientState.REQUEST_SENT)) {
					System.out.println(state + " " + conn.channel().attr(attributeKey));
				}
				else if (state.equals(HttpClientState.RESPONSE_RECEIVED)) {
					System.out.println(state + " " + conn.channel().attr(attributeKey));
				}
			});

	client.get()
		.uri("https://example.com")
		.responseContent()
		.aggregate()
		.contextWrite(Context.of("key", "value1"))
		.block();

	client.get()
		.uri("https://example.com")
		.responseContent()
		.aggregate()
		.contextWrite(Context.of("key", "value2"))
		.block();
}
```

With
`.contextWrite(Context.of("key", "value1"))`
`.contextWrite(Context.of("key", "value2"))`

you can propagate the request
then on CONNECT/AQUIRE you can add a channel attribute and then access it when you need it

```
String propagated = observer.currentContext().getOrDefault("key", "empty");
conn.channel().attr(attributeKey).set(propagated);
```

More about Reactor Context
https://projectreactor.io/docs/core/release/reference/#context

**Comment by kushagraThapar** [comment]
Thanks @violetagg , it looks very promising, I will use it and will let you know if I run into any issues. 
Hopefully, this should solve our problem.

**Comment by violetagg** [comment]
@kushagraThapar LGTM

**Comment by kushagraThapar** [comment]
Thanks @violetagg  - we are good with this, closing this issue, thanks again for your help!
