### ISSUE TITLE
Allow setting HttpHeaders on send without copying

### ISSUE THREAD

**Issue by JonathanGiles** [reactor/reactor-netty#1479]
In my use case, I have a HTTP header class in my library that contains all headers I want to send on an outgoing request, but I am manually copying them into the request by calling `HttpClientRequest.addHeader(CharSequence, CharSequence)`. This feels like unnecessary work, as I would much rather wrap my HTTP header class with an adapter that extends from `io.netty.handler.codec.http.HttpHeaders`, and then to pass this in directly. 

I do note that there exists both `HttpClientRequest.headers(HttpHeaders)` and `HttpClient.headers(HttpHeaders)` where I could pass in a pre-constructed HttpHeaders instance, but my observation is that in both cases I am unable to provide the definitive HttpHeaders instance, and therefore iteration over and copying from one data structure to another is inevitable.

I am therefore curious if there is a recommended approach to avoid this copying, or any plans to support directly setting a pre-populated HttpHeaders instance without copying it?

**Comment by violetagg** [comment]
@JonathanGiles We need to guarantee that the headers and their values are validated. When you provide `io.netty.handler.codec.http.HttpHeaders` we do not know the exact implementation behind it, because of that we always copy the headers and validate them.

**Comment by JonathanGiles** [comment]
Thanks for getting back to me so quickly! Could you speak to what validation entails in this context, and why this is necessary? I would have assumed that Netty itself would perform this validation, but my understanding is extremely limited in this area, so I look forward to learning more! Thanks.

**Comment by violetagg** [comment]
@JonathanGiles

When we create the Netty request we enable the headers validation
https://github.com/reactor/reactor-netty/blob/91c651c15e8c39140c784078b4f3a32d4490efb4/reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientOperations.java#L148

https://github.com/netty/netty/blob/1e87c711b4404299fe140eabffa9be3e2ada6565/codec-http/src/main/java/io/netty/handler/codec/http/DefaultHttpRequest.java#L38

Take a look at 
https://github.com/netty/netty/blob/1e87c711b4404299fe140eabffa9be3e2ada6565/codec-http/src/main/java/io/netty/handler/codec/http/DefaultHttpHeaders.java#L93
https://github.com/netty/netty/blob/1e87c711b4404299fe140eabffa9be3e2ada6565/codec-http/src/main/java/io/netty/handler/codec/http/DefaultHttpHeaders.java#L422
https://github.com/netty/netty/blob/1e87c711b4404299fe140eabffa9be3e2ada6565/codec-http/src/main/java/io/netty/handler/codec/http/DefaultHttpHeaders.java#L417

**Comment by violetagg** [comment]
@JonathanGiles Were you able to look at those?

**Comment by JonathanGiles** [comment]
Thanks for clarifying with the many useful links. I understand the point you are making - that deferring the validation to netty, by copying all headers into its implementation, provides safety to the user. It is unfortunate as the copying is an extra cost that I would rather not pay, but so be it. Thanks for your help!
