### ISSUE TITLE
Application fails to handle traffic when HTTP2 Cleartext response is sent from Server

### ISSUE THREAD

**Issue by idikshit** [reactor/reactor-netty#1486]
Hi, we are using Spring Cloud Gateway with Reactor Netty, we are running load test with HTTP2 ClearText traffic to test a scenario where the request is rejected at the server instead of routing the request to back end service. According to our observations the Memory and CPU usage of the application spiked and application performance degraded. 
We tested the similar scenario with HTTP 1.1 enabled and we could observe no issue with HTTP 1.1. traffic. 
We are using the following versions in our project
1. Spring Boot - 2.3.3
2. Spring Cloud Starter Gateway - 1.1.2
3. Netty - 4.1.50
4. Reactor Netty Core - 0.9.9.RELEASE
We tried similar scenarios with latest versions of Spring Boot, Spring Cloud Starter Gateway, Netty and Reactor Netty Core but the observation remained the same.

This is a demo project for the same
[demo.zip](https://github.com/reactor/reactor-netty/files/5897752/demo.zip)

**Comment by violetagg** [comment]
@idikshit Please provide more information for the load test. Do you use H2C prior-knowledge or H2C upgrade?

**Comment by idikshit** [comment]
@violetagg We are using H2C prior-knowledge for load test.

**Comment by violetagg** [comment]
and can you provide more information for the load test so that I will be able to reproduce the issue?

**Comment by idikshit** [comment]
@violetagg We are using httpgo client to send traffic at 5k TPS with appropriate request body which are rejected at Server, we see the performance of the above attached application good for nearly 15-20 min, then there is a sudden memory spike and the performance of the application degrades.

**Comment by violetagg** [comment]
> appropriate request body

Can you tell me what you mean with `appropriate request body`?

**Comment by idikshit** [comment]
@violetagg We are sending json request body for each request according to the API operation (Ex - PUT, PATCH, POST). The requests having no json request body (Ex - GET API operation) work fine but the application crashes for the API operations having request body... the memory spikes and application crashes. We have used a work-around and we release the request body resources every time we return an error response from Netty Server. Following is the work-around added.

`Flux.from(exchange.getRequest().getBody()).map(DataBufferUtils::release).subscribe();`

The application works fine with the above work-around but there is still a gradual increase in memory over a long period of time.

**Comment by idikshit** [comment]
@violetagg Could you please confirm if it is an issue/ bug?

**Comment by violetagg** [comment]
@idikshit I tried to reproduce that but without success, can you provide some setup for the client that I can use to reproduce this?

**Comment by idikshit** [comment]
@violetagg We are using Kubernetes environment to deploy our application, please find the attached zip file for vegeta client setup in Kubernetes environment and appropriate commands to reproduce the issue.
[vegeta_demo.zip](https://github.com/reactor/reactor-netty/files/5936565/vegeta_demo.zip)

**Comment by violetagg** [comment]
@idikshit I'll take a look at this. Thanks a lot.

**Comment by idikshit** [comment]
@violetagg Is there any update regarding this ticket?

**Comment by violetagg** [comment]
@idikshit Can you test the current `1.0.5-SNAPSHOT`?
maven repo https://repo.spring.io/snapshot

**Comment by idikshit** [comment]
@violetagg We are unable to resolve all the dependencies after migrating from 0.9.9.RELEASE to 1.0.5-SANPSHOT for io.projectReactor.netty.reactor-netty.

**Comment by violetagg** [comment]
@idikshit I back ported the fix to 0.9.x via c6e7a97. Can you try `0.9.18.BUILD-SNAPSHOT`?

**Comment by idikshit** [comment]
@violetagg The performance test result with 0.9.18.BUILD-SNAPSHOT was similar to 0.9.9.RELEASE version. There is still a gradual increase in memory over a long period of time.

**Comment by idikshit** [comment]
@violetagg Could you please confirm if there is any update on this ticket, Thanks

**Comment by violetagg** [comment]
@idikshit It is still under investigation

**Comment by violetagg** [comment]
@idikshit Do you observe some error logs like this `io.netty.util.ResourceLeakDetector       : LEAK: ByteBuf.release() was not called`? I'm testing with the latest Reactor Netty/Spring Boot/Spring Gateway and I do not observe the behaviour that you describe.

**Comment by violetagg** [comment]
@idikshit Were you able to test with the latest releases?

**Comment by violetagg** [comment]
@idikshit Let me close this, we can reopen it if needed.
