### ISSUE TITLE
Add an option to allow developers to enable thread affinity of Netty if net.openhft.affinity is on classpath

### ISSUE THREAD

**Issue by JamesChenX** [reactor/reactor-netty#1489]
## Motivation

1. Make full use of CPUs cache
2. Reduce context switching

## Desired solution

Add an option to allow developers to enable thread affinity of Netty if net.openhft.affinity is on classpath

```java
TcpServer.create()
	.host("localhost") 
	.port(8080)
	// .threadAffinity() // Something like this
	// .threadAffinity(false)
	.bindNow();
```

Reference: https://github.com/netty/netty/wiki/Thread-Affinity
## Considered alternatives

No.

## Additional context

No.

**Comment by violetagg** [comment]
@JamesChenX You should be able to use the current API

```
ThreadFactory threadFactory = new AffinityThreadFactory("atf_wrk", AffinityStrategies.DIFFERENT_CORE);
EventLoopGroup eventLoopGroup = new NioEventLoopGroup(10, threadFactory);

TcpServer.create()
	.host("localhost") 
	.port(8080)
	.runOn(eventLoopGroup)
	.bindNow();
```

https://projectreactor.io/docs/netty/release/api/reactor/netty/transport/Transport.html#runOn-io.netty.channel.EventLoopGroup-

**Comment by JamesChenX** [comment]
OK, it's fine for us to use the APIs, and I just wanted to confirm whether you will do it so that we don't reinvent the wheel. Thanks.

**Comment by JamesChenX** [comment]
@violetagg . One more enhancement point, we would like to specify the number of select (acceptor) threads and the number of workers while using thread affinity. But there is no way for that now, could you provide a method like `.runOn(acceptorEventLoopGroup, workerEventLoopGroup)`?

**Comment by violetagg** [comment]
@JamesChenX You can do it like this:

```
final int acceptorThreads = 1;
final int workerThreads = 10;
EventLoopGroup acceptorGroup = new NioEventLoopGroup(acceptorThreads);
ThreadFactory threadFactory = new AffinityThreadFactory("atf_wrk", AffinityStrategies.DIFFERENT_CORE);
EventLoopGroup workerGroup = new NioEventLoopGroup(workerThreads, threadFactory);

TcpServer.create()
	.host("localhost") 
	.port(8080)
        .runOn(new LoopResources() {
	         @Override
	         public EventLoopGroup onServer(boolean useNative) {
		         return workerGroup;
	         }

	         @Override
	         public EventLoopGroup onServerSelect(boolean useNative) {
		         return acceptorGroup;
	         }
         })
	.bindNow();
```

**Comment by JamesChenX** [comment]
@violetagg it can work but the code isn't that elegant compared to `runOn(acceptorEventLoopGroup, workerEventLoopGroup)`. Anyway, thanks for your continuous support!
