### ISSUE TITLE
Provide method to close WebSocket connection outside of a Flux Subscriber's Cancellation

### ISSUE THREAD

**Issue by rstoyanchev** [reactor/reactor-netty#15]
A Subscriber to the Flux of input WebSocket messages can use the Cancellation it receives to close the WebSocket connection. 

It would be very useful to expose a `close()` method that can be called by something other than the Flux Subscriber. For example a 3rd party `WebSocketSession` abstraction built around the Reactor Netty WebSocket support that itself does not subscribe to the input Flux. 

Semantically this should be possible assuming there is only one Subscriber for a given WebSocket connection? Or potentially some WebSocket handler's may not even subscribe to the inbound stream effectively ignoring it and only broadcasting messages -- even in those cases it should be possible to close the connection somehow.
 
There should also be a way to specify a close status, e.g. `close(int status)`.

**Comment by smaldini** [comment]
Related to https://stackoverflow.com/questions/42069471/shutting-down-a-netty-tcpclient-channel-in-reactor-3-0-4/42086633#42086633

**Comment by smaldini** [comment]
Work around for now is to call outbound/inbound.context().dispose(), it should call sendClose as cancel()

**Comment by rstoyanchev** [comment]
Are there drawbacks to this workaround? For the contract I need to implement there are two issues. No way to specify a close status and no way to return proper completion notification `Mono<Void>` or is the `dispose()` actually synchronous?

Why close the ticket by the way?
