### ISSUE TITLE
Add support for configuring the HttpRequestDecoder when creating an HttpServer

### ISSUE THREAD

**Issue by wilkinsona** [reactor/reactor-netty#150]
A Spring Boot user has [raised an issue](https://github.com/spring-projects/spring-boot/issues/9955) that's caused by Netty's default configuration that limits the initial line of an HTTP request to 4096 bytes. As far as I can tell, Reactor Netty doesn't allow this to be configured as [the default `HttpRequestDecoder` constructor is used](https://github.com/reactor/reactor-netty/blob/f895546df5ecff24340366c8772d7b71a58c6195/src/main/java/reactor/ipc/netty/http/server/HttpServer.java#L210).

Would it be possible to expose the configuration options offered by `HttpRequestDecoder` to users?

**Comment by balopat** [comment]
+1

**Comment by violetagg** [comment]
Covered by #256
