### ISSUE TITLE
Webflux Webclient - Error when sending HTTP2 requests as client to a HTTP2 enabled server

### ISSUE THREAD

**Issue by patpatpat123** [reactor/reactor-netty#1500]
Small question regarding an issue while sending HTTP2 request to a server that is HTTP2 enabled please

**Caused by: io.netty.handler.codec.http2.Http2Exception: First received frame was not SETTINGS. Hex dump for first 5 bytes: 485454502f**

The setup:
On server side, a Spring Webflux application 2.4.2, where http2 with mTLS is enabled. The java version is 11. 
```
server.http2.enabled=true
server.ssl.client-auth=need
server.ssl.enabled-protocols=TLSv1.3
server.ssl.enabled=true
server.ssl.key-alias=server
server.ssl.key-password=x
server.ssl.key-store-password=x
server.ssl.key-store-provider=SUN
server.ssl.key-store-type=JKS
server.ssl.key-store=keystore.p12
server.ssl.trust-store-password=x
server.ssl.trust-store-provider=SUN
server.ssl.trust-store-type=JKS
server.ssl.trust-store=truststore.p12
```

I know it is HTTP2 successfully enabled, because when I curl it, I see on the curl response.

```
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* Connection state changed (MAX_CONCURRENT_STREAMS == 4294967295)!
< HTTP/2 200
``` 

And in server side log, I do see ```Feb/2021:+0000] "GET /route HTTP/2.0" 200 288448 24 ms```

Now, **the issue**:

A client using Webflux Webclient, initialized as such:

```
WebClient.create().mutate().defaultHeader(HttpHeaders.CONTENT_TYPE, MediaType.APPLICATION_JSON_VALUE).clientConnector(new ReactorClientHttpConnector(HttpClient.create().protocol(HttpProtocol.H2).wiretap(true).secure(sslContextSpec -> sslContextSpec.sslContext(getSslContext())))).build();
```

Note the .protocol(HttpProtocol.H2)

When using this Webclient to send the exact same request to this http2 enabled server, I see this exception:
First received frame was not SETTINGS. Hex dump for first 5 bytes: **485454502f;**

```
org.springframework.web.reactive.function.client.WebClientRequestException: First received frame was not SETTINGS. Hex dump for first 5 bytes: 485454502f; nested exception is io.netty.handler.codec.http2.Http2Exception: First received frame was not SETTINGS. Hex dump for first 5 bytes: 485454502f
	at org.springframework.web.reactive.function.client.ExchangeFunctions$DefaultExchangeFunction.lambda$wrapException$9(ExchangeFunctions.java:137) ~[spring-webflux-5.3.3.jar!/:5.3.3]
```

After research online, 485454502f stands for HTTP/, but my server is HTTP2 enabled!

It is not a gRPC server, just HTTP2 enabled.

Hence, I do not understand why am I facing this issue.

Thank you for your help.

**Comment by violetagg** [comment]
@patpatpat123 Can you provide a reproducible example? Or at least can you enable the wire log in order to see what kind of response was returned by the server?
This error is returned either the server does not support HTTP/2 or for some reason it returned HTTP/1.x response

**Comment by patpatpat123** [comment]
Hello @violetagg ,

Thank you for taking a look at this.
Yes, both clients and servers are 2.4.2. I tried with 2.5 M1, still reproducible.

And I am very sure the server is HTTP2 enabled, other clients such a curl, go clients, call it on a daily basis, and I got their confirmation they see HTTP2, so do I in my server log.

Will try to add an example!

Good day

**Comment by patpatpat123** [comment]
Hello @violetagg ,

https://github.com/patpatpat123/http2notworkingmaybe

In this repo, there is a minimal reproducible example.
Unfortunately, I am not able to provides the secrets, such as the server's server keystore, server trust store, keystore used by server to talk to client.

Vice versa, not able to provide the client keystore, client trust store, keystore used by client to talk to server.

(6 files in total I am not able to provide)

But if you have a set of certificates ready, this is easily reproducible.

Furthermore, the SpringBoot Admin Server here is acting as a **client**, trying to get some app metrics.

The SpringBoot client app is actually the **server**, since he is the one exposing metrics for SBA Server to come get status.

Apologies for the confusion, hence, the error is happening on the SBA Server side, while he is acting as client in order to get metrics.

You will see in the SBA Server the HTTP2 client: with the wiretap AND the HTTP2 protocol.

```
@Bean
	public ClientHttpConnector customHttpClient() {
		return new ReactorClientHttpConnector(HttpClient.create().wiretap(true).protocol(HttpProtocol.H2).secure(ssl -> ssl.sslContext(getSslContext())));
	}
```

Could you please let me know if you successfully reproduced the issue?

Any further information you need, please let me know!

**Comment by violetagg** [comment]
@patpatpat123 Thanks! I'll take a look.

**Comment by violetagg** [comment]
@patpatpat123 Thanks again for the example!

Here are the findings:

Reactor Netty provides two types of `SslContext` configuration:

https://projectreactor.io/docs/netty/release/api/reactor/netty/tcp/SslProvider.SslContextSpec.html

You can provide either `SslContext` or `SslContextBuilder`.

When you provide `SslContextBuilder`, if it is needed we are able to extend the configuration based on the protocol configuration:

https://github.com/reactor/reactor-netty/blob/0452d8e27a7eba1b45ba97c6a1209eff762c6ea1/reactor-netty-core/src/main/java/reactor/netty/tcp/SslProvider.java#L396-L422

However if you provide `SslContext`, we consider that as a final configuration for the `SslContext`.

In your use case you provide `SslContext` for the `HttpClient` and thus we do not touch it. However there is no configuration for HTTP/2 support in that `SslContext` and in this case the client and the server negotiate to use HTTP/1.1 protocol.

Solution:
- Either extend `SslContext` with a configuration that supports HTTP/2
- Or provide `SslContextBuild` and Reactor Netty will be able to apply some default HTTP/2 configuration

**Comment by patpatpat123** [comment]
A big thank you @violetagg , learned something new.

I chose to use the SslContextBuilder, and indeed, issue is now resolved.
I couldn't image a SslContext was static even if I provide my own http2 HttpClient!  

Many thanks and good day.

**Comment by violetagg** [comment]
@patpatpat123 It is nice that it is working now.
