### ISSUE TITLE
UDP File Description Leak at DNS check in ConnectionProvider.newConnection() mode

### ISSUE THREAD

**Issue by alset0326** [reactor/reactor-netty#1515]
## Expected Behavior

The UDP socket should be closed after DNS check.
## Actual Behavior

The UDP socket not close after DNS check and cause `Too many open files` err. This bug might occurred in the new DNS module after version 1.0.0. I only test on the newest version 1.0.4

Keep the socket open might work on the default HttpResources but not work in the `ConnectionProvider.newConnection()` mode.
## Steps to Reproduce

```java
@Test
public void repoCase() {
 Mono.defer(() -> HttpClient.create(ConnectionProvider.newConnection())
                .host("xx")
                .port(80)
                .baseUrl("/")
                .get()
                .response())
                .repeat(Integer.MAX_VALUE)
                .blockLast();
}
```

## Possible Solution

The UDP socket should be closed.

## Your Environment

* Reactor version(s) used:1.0.4
* Other relevant libraries versions (eg. `netty`, ...):netty 4.1.59.final
* JVM version (`java -version`):
 java version "1.8.0_281"
Java(TM) SE Runtime Environment (build 1.8.0_281-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.281-b09, mixed mode)
* OS and version (eg. `uname -a`):
Linux ubuntu 4.4.0-154-generic #181-Ubuntu SMP Tue Jun 25 05:29:03 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
and 
Darwin A-MBP 18.7.0 Darwin Kernel Version 18.7.0: Tue Nov 10 00:07:31 PST 2020; root:xnu-4903.278.51~1/RELEASE_X86_64 x86_64

**Comment by alset0326** [comment]
I also create a repo to reproduce the issue. Just run `./gradlew test` to reproduce it

[https://github.com/alset0326/reactor-netty-issue1515-reproducer](url)

**Comment by violetagg** [comment]
@alset0326 Why do you need to use different `HttpClient` instances? Every `HttpClient` has its own resolver.

**Comment by alset0326** [comment]
@violetagg That can do. But the leak still exist. Is there any method to close the udp socket? the method `provider.disposeLater()` do nothing at all.

**Comment by violetagg** [comment]
@alset0326 If you are able to test `1.0.5-SNAPSHOT` it will be great.

**Comment by alset0326** [comment]
It works great! Thanks :)

**Comment by violetagg** [comment]
@alset0326 Thanks for the testing!
