### ISSUE TITLE
Getting a Premature connection close exception quite often

### ISSUE THREAD

**Issue by ankur-bhargava** [reactor/reactor-netty#1522]
Hi @violetagg  i am getting the PrematureCloseException exception  **reactor.netty.http.client.PrematureCloseException: Connection prematurely closed BEFORE response** quite often in our application. even after getting the exception we are getting a proper response, but we have to remove this exception from the logs.

return webClient.post().uri(url).body(BodyInserters.fromValue(request)).retrieve() .bodyToMono(response)

we are using spring boot - 2.3.4-Release and java 11, reactor-netty is 0.9.7-RELEASE.

I have checked default timeout,  it is like 10000ms can you confirm it?

as per the documentation(in the below link) it is due to too many concurrent connections opened/acquire, so just by adding connection timeout in post call will resolve my issue?

sample - webClient.post().uri(url).body(BodyInserters.fromValue(request)).retrieve()            .bodyToMono(response).timeout(Duration.ofMillis(15000))
                
https://projectreactor.io/docs/netty/snapshot/reference/index.html#_connection_pool

can you please answer the above question, Thanks in advance!!!!

**Comment by violetagg** [comment]
@ankur-bhargava The components versions that you use are too old, there are fixes in the resent versions that might be related to the issue that you observe.
Please upgrade to the latest components versions and retest your scenario.

**Comment by ankur-bhargava** [comment]
@violetagg  sorry i have mentioned the incorrect version of reactor-netty, we are using 0.9.12.RELEASE.

We are using a high load around 500-600 tps.

**as per the documentation(in the below link) it is due to too many concurrent connections opened/acquire, so just by adding connection timeout in post call will resolve my issue?**

sample - webClient.post().uri(url).body(BodyInserters.fromValue(request)).retrieve() .bodyToMono(response).timeout(Duration.ofMillis(15000))

**Comment by violetagg** [comment]
@ankur-bhargava Please take a look at this video https://youtu.be/LLSln1_JAMY?t=1923 for the various timeouts in Reactor Netty.
Also please note that in Reactor Netty 0.9.10 there was a serious regression that was later fixed in 0.9.14, so I recommend an upgrade even though that you are on 0.9.12 at the moment.

**Comment by ankur-bhargava** [comment]
Thanks, i will upgrade it to latest one more then 0.9.14 and let you know if it is still persist.

can you please answer one last question:
webClient.post().uri(url).body(BodyInserters.fromValue(request)).retrieve() .**bodyToMono(response)**
Here what is the value of **default request timeout** inside library ?

**Comment by violetagg** [comment]
@ankur-bhargava

> Here what is the value of default request timeout inside library ?

There is only `CONNECT_TIMEOUT` by default (30000ms), all other timeouts are not specified.

**Comment by violetagg** [comment]
@ankur-bhargava Were you able to upgrade? Do you still see the issue?

**Comment by violetagg** [comment]
@@ankur-bhargava I'm closing this. If you are able to provide more information we can reopen it.
