### ISSUE TITLE
Spring Webflux - Setup to wait longer for a slow service not taking effect

### ISSUE THREAD

**Issue by patpatpat123** [reactor/reactor-netty#1523]
Hello Reactor Netty Team,

Just wanted to raise a small issue, a small observation please.
We are the client, and we use a Webflux WebClient in order to query a third party API ( they are the server ).
The API is well known to be flaky, and very slow. On a lucky day, this flaky third party API will response within 2-3 secs. 

But usually, it will take 5 to 8 seconds. But to be fair, the processing on their side is quite complex, and the payload they return is very interesting, hence, we are happy to "wait a bit longer".

With this sentence in mind, we tried all combinations and even now have something like this

```
 @Bean
    @Primary
    public WebClient getWebClient() {
        return WebClient.create().mutate().defaultHeader(HttpHeaders.CONTENT_TYPE, MediaType.APPLICATION_JSON_VALUE, HttpHeaders.ACCEPT, MediaType.APPLICATION_JSON_VALUE).clientConnector(getReactorClientHttpConnector()).build();
    }

    public SslContextBuilder getSslContextBuilder() {
        final ApplicationProtocolConfig applicationProtocolConfig = new ApplicationProtocolConfig(ApplicationProtocolConfig.Protocol.ALPN, ApplicationProtocolConfig.SelectorFailureBehavior.NO_ADVERTISE, ApplicationProtocolConfig.SelectedListenerFailureBehavior.ACCEPT, ApplicationProtocolNames.HTTP_2, ApplicationProtocolNames.HTTP_1_1);
        return NettySslUtils.forClient(sslFactory()).applicationProtocolConfig(applicationProtocolConfig);
    }


 public ReactorClientHttpConnector getReactorClientHttpConnector() {
        return new ReactorClientHttpConnector(HttpClient.create().wiretap(true)

                //we are REALLY happy to wait :)
                .responseTimeout(Duration.ofSeconds(10))
                .option(ChannelOption.CONNECT_TIMEOUT_MILLIS, 10 * 1000)
                .doOnConnected(conn -> conn.addHandlerLast(new ReadTimeoutHandler(10))
                        .addHandlerLast(new WriteTimeoutHandler(10)))

                .metrics(true, () -> new MicrometerChannelMetricsRecorder(SERVICE, HTTP)).secure(sslContextSpec -> sslContextSpec.sslContext(getSslContextBuilder())));
    }
```

And even on the http request:

```
webClient.post().uri(uri).body(BodyInserters.fromValue(b)).exchangeToMono(response -> Mono.just(getResponse(response)).metrics().timeout(Duration.ofSeconds(10L));
```

We pretty much took every documentation we could find, and add a longer wait time wherever possible. 
Unfortunately, we still experience some kind of "time out".

The VIP of the third party service has logs, and saw 200 responses when it was behaving fast, and for all other time, when it was slower, it **returned a 499 error code**.

This is where I am puzzled, because a 499 would mean the client, my app "don't want to wait long enough".

Which is a bit puzzling to me, we can clearly see in the code.

```

                .responseTimeout(Duration.ofSeconds(10))
                .option(ChannelOption.CONNECT_TIMEOUT_MILLIS, 10 * 1000)
                .doOnConnected(conn -> conn.addHandlerLast(new ReadTimeoutHandler(10))
                        .addHandlerLast(new WriteTimeoutHandler(10)))


.timeout(Duration.ofSeconds(10L));
```

With wiretap on, we do see this in our client side log. Not sure if it is related.

```
2021-02-19 04:19:15.509 DEBUG [service,,] 82 --- [or-http-epoll-1] reactor.netty.http.client.HttpClient     : [id: 0xe2283fe3, L:/L:39440 - R:R:443] READ COMPLETE
2021-02-19 04:19:20.355 DEBUG [service,,] 82 --- [or-http-epoll-1] reactor.netty.http.client.HttpClient     : [id: 0xe2283fe3, L:/L:39440 - R:R:443] CLOSE
2021-02-19 04:19:20.356 DEBUG [service,,] 82 --- [or-http-epoll-1] reactor.netty.http.client.HttpClient     : [id: 0xe2283fe3, L:/L:39440 ! R:R:443] CLOSE
2021-02-19 04:19:20.356 DEBUG [service,,] 82 --- [or-http-epoll-1] reactor.netty.http.client.HttpClient     : [id: 0xe2283fe3, L:/L:39440 ! R:R:443] USER_EVENT: SslCloseCompletionEvent(java.nio.channels.ClosedChannelException)
2021-02-19 04:19:20.356 DEBUG [service,,] 82 --- [or-http-epoll-1] reactor.netty.http.client.HttpClient     : [id: 0xe2283fe3, L:/L:39440 ! R:R:443] INACTIVE
2021-02-19 04:19:20.356 DEBUG [service,,] 82 --- [or-http-epoll-1] reactor.netty.http.client.HttpClient     : [id: 0xe2283fe3, L:/L:39440 ! R:R:443] UNREGISTERED
```
Would it be possible those settings are not working please?

Or maybe we are not using them correctly?

How to simply "wait longer" please?

Many thanks for your help.

**Comment by violetagg** [comment]
@patpatpat123 Please take a look at this video https://youtu.be/LLSln1_JAMY?t=1923 for the various timeouts in Reactor Netty.

From my point of view you do not need 
- `conn.addHandlerLast(new ReadTimeoutHandler(10))`
- the timeout here
`webClient.post().uri(uri).body(BodyInserters.fromValue(b)).exchangeToMono(response -> Mono.just(getResponse(response)).metrics().timeout(Duration.ofSeconds(10L));`

**Comment by patpatpat123** [comment]
Hello @violetagg ,

The video and you presentation is very instructive.
Many thanks for providing the link.

Indeed, with the setup you mentioned during the talk (page 91), we are able to configure the time out.

On a bi-party client(2)-server(3), where I am the client, and setup the configuration as you described in page91,  we could see our client "wiling to wait longer" the flaky server. Many thanks.

I would like to ask a follow up question if you do not mind.

How to keep this behavior on a tri-party frontEnd(1)-[client/server(2)]-server(3) please?

Same setup as above. The server is a flaky server, which takes a lot of time to respond.

The client this time, is a front end UI. (web page, smartphone, etc...)

While I was the client previously, in this second scenario, **I am now the server of the web UI(1)**. But I **am still a client of the flaky server(3)**.

I believe the app taking this role, at the same time a client, same time a server, might bring some trouble.

Using the same setup you proposed, while we could wait in a client(2)-server(3) architecture, we are currently timing out, or "breaking" in a client(1) - client/server(2) - server(3) architecture.

The client, webUI, smartphone actually has a time out setup at 3 seconds.

No matter how I setup my configuration following page91, the clients are configured with a time out at 3. For obvious reasons, they are clients in the wild, I cannot change this.

So, the **client will time out at 3 seconds**. I setup my app, following page91 to **wait for flaky server, even up to 10 seconds**. The **flaky server takes** some long processing, **up to 4-5**. seconds.


I was expecting the client would time out at 3 seconds, but I would still wait for the flaky server to complete and get the flaky server's important payload!

But it seems not to be the case. at 3 second, the UI times out, and while I am in the middle of talking with the flaky server, the flaky server sees a 499, as in I do not want to wait anymore.

May I ask if this is expected in terms of design?

Also, how to achieve the "willing to wait longer" a flaky server, regardless of a client timing out please?

Thank you for your help.

**Comment by violetagg** [comment]
@patpatpat123 Please use [Gitter](https://gitter.im/reactor/reactor-netty) for any questions.
