### ISSUE TITLE
HttpClient.newConnection keeps file open

### ISSUE THREAD

**Issue by jochy** [reactor/reactor-netty#1532]
Since the recent upgrade of Spring Boot 2.4.2 / 2.4.3 we noticed that our JVM keeps file opened : 
![image](https://user-images.githubusercontent.com/6574544/110138342-2b6b7980-7dd2-11eb-8213-441ac27f9f3e.png)

The use of unpooled connections seems to be the culprit : it keeps sock files opened :'(

## Expected Behavior
For each new unpooled connection, the JVM creates a new sock file. When the connection is not used anymore, the sock file must be closed. 

## Actual Behavior
For each new unpooled connection, the JVM creates a new sock file. When the connection is not used anymore, the sock file is still opened. The JVM can live until ... too many files are opened. 

## Steps to Reproduce
Here is an example where this bevahior occurs. You can call that endpoint and see that the number of opened file is increasing each time you call it. 
Thanks to actuator with the endpoint `/actuator/metrics/process.files.open`, you can see very quickly how many files are opened by the JVM (in fact, the graph above is using that metric). 

```java
    @GetMapping("/test")
    public Mono<String> test() {
        return WebClient.builder()
            .clientConnector(new ReactorClientHttpConnector(HttpClient.newConnection().keepAlive(false)))
            .baseUrl("https://www.google.com")
            .build()
            .get()
            .retrieve()
            .bodyToMono(String.class);
    }
```

## Possible Solution
Use a pooled connection with : `HttpClient.create()`
I think, Spring Boot 2.4.0 didn't have this issue... I'll have to double check that one.

## Your Environment

* Reactor version(s) used: `1.0.3`
* Other relevant libraries versions (eg. `netty`, ...): `Spring boot 2.4.3 / 2.4.2`
* JVM version : `11.0.3`
* OS and version : `Ubuntu 20.10`

**Comment by violetagg** [comment]
@ jochy Is it possible that this one is a duplicate to #1515? Can you test 1.0.5-SNAPSHOT?

**Comment by jochy** [comment]
@violetagg After a test using the 1.0.5-SNAPSHOT, it seems that files are well closed. So it may be a duplicate, sorry for the inconvenience. 

Thank you for your help and reactivity !
