### ISSUE TITLE
Leak when using HttpClient with metrics AND NewConnectionProvider

### ISSUE THREAD

**Issue by bruto1** [reactor/reactor-netty#1547]
EventExecutorGroup.terminationFuture().listeners collection grows in an unbounded manner as long as HttpClient is being used for new requests and the listeners not being removed are the metric tracking wrappers created in reactor.netty.transport.ClientTransportConfig#resolverInternal

This is not an issue with pooled connectionprovider or when the client metrics are off

## Expected Behavior
No leak

## Actual Behavior
Yes leak

## Steps to Reproduce
No test case immediately available, issue discovered during load testing of my service (the whole webflux stack)

## Your Environment
RHEL 8.3
OpenJDK 11.0.9
spring-webflux 5.3.4
reactor-netty 1.0.4
netty 4.1.59
reactor 3.4.3

link to screenshots from MAT showing dumps with and without connection pooling attached
https://imgur.com/a/FVXqotv

**Comment by violetagg** [comment]
@bruto1 Can you test #1548 ?

**Comment by bruto1** [comment]
here's a small test with a bunch of client invocations: https://github.com/bruto1/rnetty-leak-test

**Comment by bruto1** [comment]
seems to have worked, @violetagg

**Comment by violetagg** [comment]
@bruto1 Thanks for testing it!
