### ISSUE TITLE
Documentation & Examples

### ISSUE THREAD

**Issue by magx2** [reactor/reactor-netty#155]
Hi,

Do you have some tutorial/examples how to use this plugin with Netty? I think that Java docs are not sufficient. 

Thanks

**Comment by magx2** [comment]
Any update on this?

**Comment by stavalfi** [comment]
Is it a pre-requirement to control `Netty` before learning this library? If yes, which topics in `Netty`?

**Comment by violetagg** [comment]
In most cases there is no such prerequisite.

**Comment by kweheliye** [comment]
@violetagg 

Is there a way to have early access of the new 0.8.0 release?, just to see and test the new up coming features and changes.

Appreciate if you can point out. Thanks

**Comment by violetagg** [comment]
@kweheliye Hey, yes sure, try our 0.8.0.M2 from https://repo.spring.io/libs-milestone
