### ISSUE TITLE
uriTagValue is shared across different HttpClient instances

### ISSUE THREAD

**Issue by skaba** [reactor/reactor-netty#1559]
If I configure multiple HttpClient Instances as such
```java
HttpClient.create().metrics(enable, uri -> "/books/{id}")
```
```java
HttpClient.create().metrics(enable, uri -> "/authors/{id}")
```

## Expected Behavior
They're shared (Probably the latest overrides but I can't say)

## Actual Behavior
uriTagValue function belongs to individual HttpClient instance not global.

**Comment by violetagg** [comment]
@skaba Please specify Reactor Netty version.

**Comment by skaba** [comment]
io.projectreactor.netty:reactor-netty-http:1.0.4
