### ISSUE TITLE
User-Agent header cannot be overridden 

### ISSUE THREAD

**Issue by violetagg** [reactor/reactor-netty#1560]
Based on the Gitter discussion https://gitter.im/reactor/reactor-netty?at=6059b884a7dfe1372ef09163

**Comment by justinesymphony** [comment]
Hi @violetagg, giving it a second thought, I am not sure this is actually an issue.
In https://github.com/reactor/reactor-netty/blob/1ee8169b665795f8ce6a2c0e02592210bf719b9d/reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientConnect.java#L497, we're using the headers-implementation-specific `contains` which, according to the "hashing strategy" used (https://github.com/1030907690/netty-netty-4.1.27.Final/blob/master/codec/src/main/java/io/netty/handler/codec/DefaultHeaders.java#L55), may or may not be matching header names in case sensitive manner.
If we are enforcing a case insensitive behaviour in Reactor Netty, then it will not be compliant with what Netty does any more.
To me it seems that this issue should be closed now.

**Comment by violetagg** [comment]
@justinesymphony I added a test with PR #1565 that verifies that the custom header will be preserved
