### ISSUE TITLE
Metrics

### ISSUE THREAD

**Issue by dbacinski** [reactor/reactor-netty#157]
Is there a plan to add metrics support like in RxNetty?

https://github.com/ReactiveX/RxNetty/issues/98
https://github.com/ReactiveX/RxNetty/blob/0.5.x/rxnetty-http/src/main/java/io/reactivex/netty/protocol/http/server/events/HttpServerEventsListener.java

And as for now how can it access similar data in Reactor-Netty?

**Comment by violetagg** [comment]
Metrics support using micrometer #790
