### ISSUE TITLE
Is there a way to fix out the “io.netty.handler.proxy.HttpProxyHandler$HttpProxyConnectException:” while trying to get the token from an external API

### ISSUE THREAD

**Issue by agarwaljayant7** [reactor/reactor-netty#1583]
Hi,

I'm using the below code snipped which is throwing err. at method `retrieve().bodyToMono(String.class)`. The purpose here is to retrieve the response from an external API which is supposed to provide a token in `String` format.

**Code snippet:**

```
final ReactorClientHttpConnector connector =
      new ReactorClientHttpConnector(
            HttpClient.create().tcpConfiguration(
                  tcpClient -> tcpClient.proxy(
                        proxy -> proxy.type(ProxyProvider.Proxy.HTTP)
                                    .host("abc-proxy.uk.xyz.abcintra.net")
                                    .port(3128) ) ) );

String tokenResponse = WebClient.builder()
      .clientConnector(connector)
      .build()
      .post()
      .uri("https://dev.api.abc.com/oauth2/token.oauth2")
      .headers(httpHeaders -> {
            httpHeaders.add("Authorization", authHeader);    // authHeader was generated to something like "Basic jWdb2njwUiOD3jcIfNs4dDjk3sle9oRj3sjer=" 
            httpHeaders.add("Content_Type", "application/x-www-form-urlencoded");
      })
      .body(BodyInserters.fromValue("grant_type=client_credentials"))
      .retrieve()
      .bodyToMono(String.class)
      .block();
```
After running this code, it's giving the exception - `io.netty.handler.proxy.HttpProxyHandler$HttpProxyConnectException:`
and it's detailed msg. is:
`[id: 0x62f7d272, L:/51.135.65.49:52907 ! R:security-abc-proxy.uk.xyz.abcintra.net/59.11.19.11:3128] The connection observed an error`. 

So, I think, the connection b/w my local client and proxy server is not getting established. Note: I've not mentioned the exact proxy URL here for security reasons, thanks! 

PS: I Will capture the traffic with Wireshark and share it here as soon as it's available with me. Thanks & Regards, Jayant.

**Comment by violetagg** [comment]
@agarwaljayant7 I've edited your comment to improve the formatting.

**Comment by agarwaljayant7** [comment]
@violetagg 
tx for editing my comment, pls be informed that from last five to six days i've been working to implement the WebClient interface to generate the Oath2 Token from an external third party API by using the above code snippet shared in this issue# 1583. Please be informed that my Postman client installed in the same OS and is able to generate the token by using the same credentials, but when it comes to the WebClient interface which is also running in the same OS is unable to do the same. 

So, currently i removed the proxy settings to let the WebClient auto-detect the proxy and generate me the token by using the below code snippet:

public class WebClientService {

	@Value("${vendor.clientid}")
	private String clientID;

	@Value("${vendor.clientsecret}")
	private String clientSecret;

	@Value("${vendor.uri}")
	private String uri;

	@Value("${vendor.valuationsUri}")
	private String valuationsUri;



	public String getToken() {

		WebClient client = null;

		ObjectMapper mapper = null;

		String body = "grant_type=client_credentials";

		String auth = "Bearer ";

		String token = null;
		String responseToString = null;

		String basic = clientID + ":" + clientSecret;
		byte[] encodedAuth = Base64.encodeBase64(basic.getBytes(StandardCharsets.US_ASCII));
		String authHeader = "Basic " + new String(encodedAuth);

		String tokenResponse = WebClient.builder()
				.build().post().uri(uri).headers(httpHeaders -> {
					httpHeaders.add("Authorization", authHeader);
					httpHeaders.add("Content_Type", "application/x-www-form-urlencoded");
				}).body(BodyInserters.fromValue("grant_type=client_credentials")).retrieve().bodyToMono(String.class).block();

And, this throws me the attached exception.
[Exception.txt](https://github.com/reactor/reactor-netty/files/6277819/Exception.txt)

Any help is highly appreciated. thanks!

**Comment by agarwaljayant7** [comment]
@violetagg tx for editing my comment, pls be informed that from last five to six days i've been working to implement the WebClient interface to generate the Oath2 Token from an external third party API by using the above code snippet shared in this issue# 1583. Please be informed that my Postman client installed in the same OS and is able to generate the token by using the same credentials, but when it comes to the WebClient interface which is also running in the same OS is unable to do the same. So, currently i removed the proxy settings to let the WebClient auto-detect the proxy and generate me the token by using the below code snippet: 



public class WebClientService { @Value("${vendor.clientid}") private String clientID; @Value("${vendor.clientsecret}") private String clientSecret; @Value("${vendor.uri}") private String uri; @Value("${vendor.valuationsUri}") private String valuationsUri; public String getToken() { WebClient client = null; ObjectMapper mapper = null; String body = "grant_type=client_credentials"; String auth = "Bearer "; String token = null; String responseToString = null; String basic = clientID + ":" + clientSecret; byte[] encodedAuth = Base64.encodeBase64(basic.getBytes(StandardCharsets.US_ASCII)); String authHeader = "Basic " + new String(encodedAuth); String tokenResponse = WebClient.builder() .build().post().uri(uri).headers(httpHeaders -> { httpHeaders.add("Authorization", authHeader); httpHeaders.add("Content_Type", "application/x-www-form-urlencoded"); 
}).body(BodyInserters.fromValue("grant_type=client_credentials")).retrieve().bodyToMono(String.class).block(); 

And, this throws me the  io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection timed out: no further information:. Exception.txt Any help is highly appreciated. thanks!

**Comment by violetagg** [comment]
@agarwaljayant7 Do you need this `authHeader` for the proxy?

**Comment by agarwaljayant7** [comment]
@violetagg , yes authHeader is needed  as without it the vendor API won't be able to authenticate my request and generate me the token. thanks

**Comment by violetagg** [comment]
@agarwaljayant7 Is it possible that you proxy configuration need in addition this one

https://projectreactor.io/docs/netty/release/api/reactor/netty/transport/ProxyProvider.Builder.html#httpHeaders-java.util.function.Consumer-

**Comment by violetagg** [comment]
@agarwaljayant7 One additional thing: Reactor Netty uses `CONNECT` method for the proxy functionality. Does your proxy support it?

**Comment by agarwaljayant7** [comment]
@violetagg , yes, i think so. But, so far i've not used the it. Here, is my implementation:

		final ReactorClientHttpConnector connector = new ReactorClientHttpConnector(
				HttpClient.create().tcpConfiguration(tcpClient -> tcpClient.proxy(proxy -> proxy
						.type(ProxyProvider.Proxy.HTTP).host("security-abc-proxy.uk.xyz.abcintra.net").port(3128))));
		final ExchangeStrategies strategies = ExchangeStrategies.builder()
				.codecs(configurer -> configurer.defaultCodecs().maxInMemorySize(16 * 1024 * 1024)).build();

		String tokenResponse = WebClient.builder().clientConnector(connector).exchangeStrategies(strategies).
				build()
				.post()
				.uri(uri)
				.headers(httpHeaders -> {
					   httpHeaders.add("Authorization", authHeader);   
                                           httpHeaders.add("Content_Type", "application/x-www-form-urlencoded");
				})
				.body(BodyInserters.fromValue("grant_type=client_credentials"))
				.retrieve()
				.bodyToMono(String.class)
				.block();

Please note that this is now giving me the "Caused by: io.netty.handler.proxy.HttpProxyHandler$HttpProxyConnectException: http, none, security-abc-proxy.uk.xyz.abcintra.net/59.11.19.11:3128 => abc.api.xyz.com:443, **status: 407 Proxy Authentication Required" exception.**

SO, as a workaround i'm now thinking on how to pass my username and passwd into the WebClient to address this issue. Pls, correct me if wrong or pls. provide your feedback to address this. thanks!

**Comment by violetagg** [comment]
@agarwaljayant7 https://tools.ietf.org/html/rfc7235#section-3.2

```
The 407 (Proxy Authentication Required) status code is similar to 401
   (Unauthorized), but it indicates that the client needs to
   authenticate itself in order to use a proxy.  The proxy MUST send a
   Proxy-Authenticate header field (Section 4.3) containing a challenge
   applicable to that proxy for the target resource.  The client MAY
   repeat the request with a new or replaced Proxy-Authorization header
   field (Section 4.4).
```

**Comment by agarwaljayant7** [comment]
@violetagg , thx for sharing this. But, this shows more about the reason behind the 407 (Proxy Authentication Required) which is already known to me. So, i'm currently in the process of finding out the required implementation to fix this issue out. So, any suggestion towards the coding implementation to fix this out is highly appreciated. thanks!

**Comment by violetagg** [comment]
@agarwaljayant7 For my proxy that I use for testing I provide user/password. You need to check what you need to provide when connecting to your proxy. You may need user/password or some specific headers. All these configurations need to be applied to `(proxy -> proxy.type(ProxyProvider.Proxy.HTTP).host("security-abc-proxy.uk.xyz.abcintra.net").port(3128))`

**Comment by agarwaljayant7** [comment]
@violetagg , i tried with my user/password as can be seen in the below code, but still got the same exception "Caused by: io.netty.handler.proxy.HttpProxyHandler$HttpProxyConnectException: http, none, security-abc-proxy.uk.xyz.abcintra.net/59.11.19.11:3128 => abc.api.xyz.com:443, status: 407 Proxy Authentication Required" exception.Required"

	HttpClient httpClient = HttpClient.create()
		            .tcpConfiguration(tcpClient ->
		                    tcpClient.proxy(proxy -> proxy.type(ProxyProvider.Proxy.HTTP).host("security-abc-proxy.uk.xyz.abcintra.net").port(3128)
		                    		**.username("ÄPAC'\'MYUSERID")
		                    		.password(pwd)));**      // Here, Function <String, String> **pwd** = username -> "****" ;


So, how about the "specific headers" which was mentioned by u earlier in above comment. Any specific coding sol. of the same? thx!

**Comment by agarwaljayant7** [comment]
@violetagg , i tried with my user/password as can be seen in the below code, but still got the same exception "Caused by: io.netty.handler.proxy.HttpProxyHandler$HttpProxyConnectException: http, none, security-abc-proxy.uk.xyz.abcintra.net/59.11.19.11:3128 => abc.api.xyz.com:443, status: 407 Proxy Authentication Required" exception.Required"

HttpClient httpClient = HttpClient.create()
	            .tcpConfiguration(tcpClient ->
	                    tcpClient.proxy(proxy -> proxy.type(ProxyProvider.Proxy.HTTP).host("security-abc-proxy.uk.xyz.abcintra.net").port(3128)
	                    		.username("ÄPAC'\'MYUSERID")
	                    		.password(pwd)));      // Here, Function <String, String> **pwd** = username -> "****" ;

**Comment by violetagg** [comment]
@agarwaljayant7 I don't know what the requirements for your proxy are. Proxy authentication is similar to `normal` HTTP authentication. With my proxy that I use for testing I provide proxy user/pass.

**Comment by violetagg** [comment]
@agarwaljayant7 Were you able to clarify your proxy requirements?

**Comment by agarwaljayant7** [comment]
@violetagg yes,, it was due to my corporate's internal proxy which was blocking this. So, i've raised a request to allow my application to call the external API of the third party vendor from the corporate network itself. So, i think the network team here would need to whitelist the external API in the proxy server to address this issue.

**Comment by violetagg** [comment]
@agarwaljayant7 Thanks! Let me close that, we can reopen it if it is needed.
