### ISSUE TITLE
request example:http://localhost:18997/smqtt/publish?test=78787878788.  How to get the request parameter test？ 

### ISSUE THREAD

**Issue by 1ssqq1lxr** [reactor/reactor-netty#1606]
## Steps to Reproduce

```java
@Test
public void repoCase() {

}
```

## Your Environment

* Reactor version(s) used:
* Other relevant libraries versions (eg. `netty`, ...):
* JVM version (`java -version`):
* OS and version (eg. `uname -a`):

**Comment by violetagg** [comment]
@1ssqq1lxr Currently Reactor Netty does not parse the query, you have to parse it by yourself.
There is a feature request for this #68

**Comment by 1ssqq1lxr** [comment]
thanks




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Violeta ***@***.***&gt;; 
发送时间: 2021年4月20日(星期二) 下午2:58
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [reactor/reactor-netty] request example:http://localhost:18997/smqtt/publish?test=78787878788.  How to get the request parameter test？  (#1606)





 
@1ssqq1lxr Currently Reactor Netty does not parse the query, you have to parse it by yourself.
 There is a feature request for this #68
