### ISSUE TITLE
Add Per-Channel MetricsRecorder builder with a ContextView or similar 

### ISSUE THREAD

**Issue by smaldini** [reactor/reactor-netty#1628]
Currently Metric Recorders are client/server wide which might not be enough in some metrics captures scenarios.

We would like to capture informations in clients from the context for instance (to add extra micrometer tags). I think this could take the shape of of a client/server builder `metric(boolean enable, Function<Context, ChannelMetricsRecorder>)`.
It could use the `connectionObserver.currentContext()` as an argument.

**Comment by violetagg** [comment]
@smaldini The metrics recorder is supposed to be one and the same for a given `HttpClient` while `ContextView` is per request. With #1646 I'm proposing new abstract classes that a custom metrics recorder can extend when an access to the `ContextView` is needed. PTAL
