### ISSUE TITLE
Allow HttpClient to configure HttpResponseDecoder.allowDuplicateContentLengths

### ISSUE THREAD

**Issue by jonybuzz** [reactor/reactor-netty#1636]
It would be nice to configure the field `allowDuplicateContentLengths` directly from the HttpClient builder. For example:

```
HttpClient
            .create()
            .httpResponseDecoder (options -> options
                .allowDuplicateContentLengths(true)
            )
```

## Motivation
Every other option of [HttpResponseDecoder](https://github.com/netty/netty/blob/d34212439068091bcec29a8fad4df82f0a82c638/codec-http/src/main/java/io/netty/handler/codec/http/HttpResponseDecoder.java) is configurable from that API

## Desired solution
Add a config method in [HttpDecoderSpec](https://github.com/reactor/reactor-netty/blob/main/reactor-netty-http/src/main/java/reactor/netty/http/HttpDecoderSpec.java)

## Additional context
Option introduced in July 2020 https://github.com/netty/netty/pull/10349

**Comment by violetagg** [comment]
@jonybuzz Can you please elaborate on the use case for this feature request?

**Comment by jonybuzz** [comment]
@violetagg sure. I'm working on a microservice that uses Spring Boot Webflux and when doing a request to other ms, some component in the middle is duplicating the content length header when the response is returning.
Obviously, the best thing to do is correct the response handling. But at the moment is much more hard than using a feature like the requested.
There is a good and simple explanation in this Netty's PR comment: https://github.com/netty/netty/pull/10349#issuecomment-645062496
I hope I was clear. Thanks!
