### ISSUE TITLE
IPV6 Spring Boot 2.4.5 (gateway) and reactor netty 1.0.6 stopped working

### ISSUE THREAD

**Issue by koldat** [reactor/reactor-netty#1637]
After upgrade to Spring Boot 2.4.5 with netty reactor 1.0.6 we are not able to use IPV6 anymore. The problem is that strict decoding were added that throws an exception (#1589).

Right now we had to disable Forwarded filter using:
spring.cloud.gateway.forwarded.enabled=false

## Expected Behavior
DefaultHttpForwardedHeaderHandler should fallback to parseXForwardedInfo in case strict decoding fails. Otherwise server can stop working just because of incorrect implementation of any gateway vendor in IPV6 environment. As fixing these gateways gets time I do not think strict decoding of forwarded information is a good idea.

## Actual Behavior
```
java.lang.IllegalArgumentException: Invalid IPv4 address 0:0:0:0:0:0:0:1:50532
    at reactor.netty.transport.AddressUtils.parseAddress(AddressUtils.java:132)
    at reactor.netty.http.server.DefaultHttpForwardedHeaderHandler.parseForwardedInfo(DefaultHttpForwardedHeaderHandler.java:66)
    at reactor.netty.http.server.DefaultHttpForwardedHeaderHandler.apply(DefaultHttpForwardedHeaderHandler.java:47)
```

Root cause is that Spring org.springframework.cloud.gateway.filter.headers.ForwardedHeadersFilter is not encoding "Forwarded" according to standard, but there can be many more gateways.

## Steps to Reproduce
Use spring cloud gateway and spring boot 2.4.5 + netty reactor 1.0.6. Then use curl using IPV6 address to spring cloud gateway (or any other broken gateway) that points final application.

## Possible Solution
```java
    @Override
    public ConnectionInfo apply(ConnectionInfo connectionInfo, HttpRequest request) {
        String forwardedHeader = request.headers().get(FORWARDED_HEADER);
        if (forwardedHeader != null) {
            try {
                return parseForwardedInfo(connectionInfo, forwardedHeader);
            } catch (IllegalArgumentException e) {
                // Fallback to xforwarded info
            }
        }
        return parseXForwardedInfo(connectionInfo, request);
    }
```

Or make strict configurable and not hardcoded as "true".

## Your Environment
* Spring Boot 2.4.5
* Spring Cloud Gateway 3.0.2
* Reactor netty 1.0.6

**Comment by koldat** [comment]
@violetagg @simonbasle Please take a look as you were involved in the PR

**Comment by violetagg** [comment]
@koldat What about you provide your own handler for the Forwarded headers?

You can do it with:

```
@Component
public class MyNettyWebServerCustomizer
        implements WebServerFactoryCustomizer<NettyReactiveWebServerFactory> {
    @Override
    public void customize(NettyReactiveWebServerFactory factory) {
        factory.addServerCustomizers(httpServer ->
                httpServer.forwarded((connectionInfo, httpRequest) -> {...}));
    }
}
```

**Comment by koldat** [comment]
@violetagg Yes, but then I would need to "copy" the class and maintain it. This call is also default so everyone using spring boot will hit this problem and everyone will need to provide own copy of this class. We should not break the contract (It was not failing with illegal exception before).

I was thinking about wrapping the class, but it is package private and also final. Having many implementations across the world for the same thing does not seems to be best solution to me in long term. Yes in short term I can copy and use "false".

**Comment by koldat** [comment]
@rstoyanchev any comment? As you were part of review.

**Comment by violetagg** [comment]
> DefaultHttpForwardedHeaderHandler should fallback to parseXForwardedInfo in case strict decoding fails.

@koldat There wasn't a fallback to `parseXForwardedInfo`, the source prior `1.0.6` version:
https://github.com/reactor/reactor-netty/blob/v1.0.5/reactor-netty-http/src/main/java/reactor/netty/http/server/DefaultHttpForwardedHeaderHandler.java#L45-L51

The both decoding of `Forwarded` header and the result were not correct prior 1.0.6 and I do not see how we can provide something less strict.

My opinion is that the source of the problem should be fixed and not to make compromises with the validation in Reactor Netty.

For a workarounds there is an API for providing another interpretation of the decoding of `Forwarded` header.

**Comment by koldat** [comment]
I know there was no fallback, but before it did not break whole communication channel. As it was not required before all upstreams could have been broken (like Spring gateway is right now). That means until someone fixes Spring Gateway or potentially other types of gateway, your library will not work. It is pretty strong behavior change.

I know I can workaround it. And I did. And everyone else will need to. But for common library like this one you should give a time to accommodate such a big change. Another option is to give a fallback which at least does not break the server. Only forwarded headers will not be processed in case these does not follow standard. Everyone would understand it. 

Internet is full of legacy software that is maybe not following standards, but these works right now. Like yours were working. Putting assertions in the path that can be easily misused by third party gateways is not good approach IMHO.

**Comment by violetagg** [comment]
@simonbasle @rstoyanchev The only possibility that I see is to provide a configuration so if we are not able to parse the `Forwarded` header to log an error and to continue as `forwarded` functionality is not enabled. Wdyt?

**Comment by rstoyanchev** [comment]
Perhaps as a system property, to be able to enable the previous behavior, to be phased out eventually. It's also worth pointing out that the previous behavior isn't deterministic and that's never a good thing also from a security standpoint.

**Comment by violetagg** [comment]
@koldat  I'm gonna add a system property that can be used to disable the strict decoding. Wdyt?

**Comment by koldat** [comment]
I am not fan of these global properties as it makes it harder in complex (mixed) deployments.  Why do you think having "strict" parameter exposed as wrong one? Simply if validation do not pass and strict is true filter simply works as headers are not available (because these are not valid). It will just not throw an exception.

We can create another variant of "forwarded" in http server:
```
class HttpServer {

	public final HttpServer forwarded(boolean forwardedEnabled, boolean strict);
```

**Comment by violetagg** [comment]
@koldat This system property should be used as a workaround for a short time of period as such it is easier to enable a system property for a given existing solution. Having an API implies that you have to change the existing solution in order to enable this workaround.

**Comment by violetagg** [comment]
@rstoyanchev @simonbasle @koldat PTAL #1640

**Comment by koldat** [comment]
Sure I am fine. I just kept in mind that it took me two hours to find why something that worked stopped working during  micro version upgrade. More people will hit this issue. We are covered already. Just was thinking about other people as they will not know about this magic property.

**Comment by anthonywanted** [comment]
@koldat Such a magic

> Just was thinking about other people as they will not know about this magic property.

**Comment by yash-trillionLoans** [comment]
Hi @koldat @anthonywanted @violetagg 
I am using Spring WebFlux, I am getting this error 

`Decoding failed: REQUEST(decodeResult: failure(java.lang.IllegalArgumentException: Invalid IPv4 address), version: HTTP/1.1)`

after placing my application behind a gateway from a cloud provider. 
Can you please help me, What is the workaround for this?

**Comment by violetagg** [comment]
@yash-trillionLoans Try to set the property `reactor.netty.http.server.forwarded.strictValidation=false`

**Comment by violetagg** [comment]
@yash-trillionLoans Then please open a new issue with a reproducible example. Thanks!
