### ISSUE TITLE
Bnd: reactor-http import packages not exported by reactor-core

### ISSUE THREAD

**Issue by simondaudin** [reactor/reactor-netty#1650]
I tried to migrate our OSGI based environment from 0.9.x -> 1.0.x after you've made it possible.

Reactor-netty-http module is using packages that are defined by reactor-netty-core as Private-Package.
Since OSGI support have been reintroduced with split between modules (http, core) https://github.com/reactor/reactor-netty/issues/1392 and following the work done with some shadow Jar https://github.com/reactor/reactor-netty/pull/915 there is an unsolvable dependency for reactor-netty-http on `reactor.netty.internal.shaded.reactor.pool` in an OSGI environment

## Expected Behavior
reactor-netty-http should used only packages defined in `Export-Package` inside reactor-netty-core MANIFEST

## Actual Behavior
reactor-netty-http uses `reactor.netty.internal.shaded.reactor.pool` defined as Private-Package in reactor-netty-core

## Possible Solution
I can see two ways:
* `reactor.netty.internal.shaded.reactor.pool` should still be hidden: shadow jar could be imported directly by reactor-netty-http (I haven't tried it yet)
* `reactor.netty.internal.shaded.reactor.pool` can be exposed:
  * remove `!reactor.netty.internal*` from reactor-netty-core `Export-Package` (I tried it successfully)
  * Export shadow jar as `reactor.netty.internal.shaded` (but I guess that is not the point)
Maybe @swimmesberger could confirm or invalidate this issue 

## Your Environment
* reactor-netty 1.0.7

**Comment by violetagg** [comment]
@simondaudin 

> remove !reactor.netty.internal* from reactor-netty-core Export-Package (I tried it successfully)

Let's do this. Would you like to provide a PR?

**Comment by simondaudin** [comment]
Ok thanks,
The PR is ready
