### ISSUE TITLE
After setting up the proxy, HttpClient accesses the address of the HTTP protocol to 403, and it has no problem accessing the address of the HTTPS protocol

### ISSUE THREAD

**Issue by FuDongHai** [reactor/reactor-netty#1654]
##### example：

```java
    @Test
    public void repoCase1() {
        ConnectionProvider connectionProvider = ConnectionProvider.create("es", 10);
        HttpClient httpClient = HttpClient.create(connectionProvider)
                .proxy(proxy -> proxy.type(ProxyProvider.Proxy.HTTP).address(new InetSocketAddress("47.243.12.14", 18888)))
                .option(ChannelOption.CONNECT_TIMEOUT_MILLIS, 20000);

        httpClient.get()
                .uri("http://www.baidu.com")
                .responseSingle((r, b) -> b.asString(StandardCharsets.UTF_8).map(s -> {
                    return s;
                }))
                .block();
    }
```

#### exception：

```
reactor.core.Exceptions$ReactiveException: io.netty.handler.proxy.HttpProxyHandler$HttpProxyConnectException: http, none, /ip:18888 => host:80, status: 403 Access violation
```

----------------------------------------------------------------------------------------------------------

```java
    @Test
    public void repoCase2() {
        ConnectionProvider connectionProvider = ConnectionProvider.create("es", 10);
        HttpClient httpClient = HttpClient.create(connectionProvider)
                .proxy(proxy -> proxy.type(ProxyProvider.Proxy.HTTP).address(new InetSocketAddress("47.243.12.14", 18888)))
                .option(ChannelOption.CONNECT_TIMEOUT_MILLIS, 20000);

        httpClient.get()
                .uri("https://www.baidu.com")
                .responseSingle((r, b) -> b.asString(StandardCharsets.UTF_8).map(s -> {
                    return s;
                }))
                .block();
    }
```

#### I don't know why I would report 403 when using reactor netty to access the address of the HTTP protocol? For your help, thank you

* Reactor version(s) used: 3.4.3
* Other relevant libraries versions (eg. `netty`, ...): netty 4.1.59.Final
* JVM version (`java -version`): 1.8.0_231
* OS and version (eg. `uname -a`):

**Comment by violetagg** [comment]
@FuDongHai It seems that you can reproduce this, is it possible to extract a reproducible example?

**Comment by violetagg** [comment]
@FuDongHai I've edited your comment to improve the formatting. You might want to check out this [Mastering Markdown guide](https://guides.github.com/features/mastering-markdown/) for future reference.

**Comment by violetagg** [comment]
@FuDongHai Please check that your proxy supports CONNECT method

**Comment by FuDongHai** [comment]
@violetagg You can try it with my modified example

**Comment by violetagg** [comment]
@FuDongHai Let's test whether your proxy supports CONNECT method

Execute the following:

`curl -x http://47.243.12.14:18888 http://www.baidu.com -v --proxytunnel`

**Comment by FuDongHai** [comment]
@violetagg The execution result：
➜  Desktop curl -x http://47.243.12.14:18888 http://www.baidu.com -v --proxytunnel
* Rebuilt URL to: http://www.baidu.com/
*   Trying 47.243.12.14...
* TCP_NODELAY set
* Connected to 47.243.12.14 (47.243.12.14) port 18888 (#0)
* Establish HTTP proxy tunnel to www.baidu.com:80
> CONNECT www.baidu.com:80 HTTP/1.1
> Host: www.baidu.com:80
> User-Agent: curl/7.54.0
> Proxy-Connection: Keep-Alive

**Comment by violetagg** [comment]
@FuDongHai Is the response the same as if you execute the same command but without `--proxytunnel`?

**Comment by FuDongHai** [comment]
Do not add ```-- proxytunnel```，```curl - x http://47.243.12.14 :18888 http://www.baidu.com -v``` It can be accessed successfully

But I have a question. RestTemplate uses ```47.243.12.14: 18888``` to set proxy access ```http://www.baidu.com``` It can be successful, but the proxy access is set by using reactor-netty Httpclient ```http://www.baidu.com``` It's 403. I don't know what the difference is

**Comment by violetagg** [comment]
@FuDongHai The difference is that Reactor Netty uses `CONNECT` method always regardless of whether you access `http` or `https` (https://github.com/netty/netty/issues/10475). Because of that I'm asking whether you have one and the same result when you run `curl` with/out `--proxytunnel` in order to check whether your proxy supports `CONNECT` method. Some proxies does not support `CONNECT` method when requesting `http`.

**Comment by FuDongHai** [comment]
@violetagg Thank you very much. I already know the answer

**Comment by FuDongHai** [comment]
@violetagg We added ```connectport 80``` to the proxy configuration, and the problem was solved. Thank you very much

Because there was no problem using resttemplate before, there was a problem using netty, so there was no doubt that it was a proxy problem. Through your answer, it is confirmed that the problem is agent configuration

**Comment by FuDongHai** [comment]
@violetagg We added ```connectport 80``` to the proxy configuration, and the problem was solved. Thank you very much

Because there was no problem using RestTemplate before, there was a problem using netty, so there was no doubt that it was a proxy problem. Through your answer, it is confirmed that the problem is agent configuration

**Comment by FuDongHai** [comment]
@violetagg We added ```connectport 80``` to the proxy configuration, and the problem was solved. Thank you very much

Because there was no problem using RestTemplate before, there was a problem using netty, so there was no doubt that it was a proxy problem. Through your answer, it is confirmed that the problem is agent configuration

**Comment by FuDongHai** [comment]
@violetagg We added ```connectport 80``` to the proxy configuration, and the problem was solved. Thank you very much

Because there was no problem using RestTemplate before, there was a problem using netty, so there was no doubt that it was a proxy problem. Through your answer, it is confirmed that the problem is agent configuration

**Comment by bobo87114** [comment]
How to solve it, can you give an example. @FuDongHai

**Comment by shahbozhalimov** [comment]
@violetagg I have this problem can you help me ? Is the response the same as if you execute the same command but without --proxytunnel this is answer no

**Comment by violetagg** [comment]
@shahbozhalimov Please review this FAQ https://projectreactor.io/docs/netty/release/reference/index.html#faq.proxy-connect-method
