### ISSUE TITLE
Netty Reactive WebSocket - how to enable it to receive wss://

### ISSUE THREAD

**Issue by phnxfire** [reactor/reactor-netty#1657]
Hello, 
thanks for reading this.
I have created a netty reactive websocket app running on cloud.
Now I just need to make it able to receive wss:// connections... how to do it?

**Comment by violetagg** [comment]
@phnxfire For questions please consider using [Gitter](https://gitter.im/reactor/reactor-netty) or [stackoverflow.com](https://stackoverflow.com/questions/tagged/reactor-netty)

**Comment by phnxfire** [comment]
Thanks @violetagg I have posted a question here: https://stackoverflow.com/q/67844667/13944450
