### ISSUE TITLE
Add option to remove a added route from HttpServerRoutes

### ISSUE THREAD

**Issue by roggenbrot** [reactor/reactor-netty#1669]
At the moment it's not possible to remove a previously added route from `HttpServerRoutes`

## Motivation
I'm currently working on an "Webflux light" for OSGI. Because of the dynamic nature of OSGI (Components are dynamic added/removed) I need a way to remove a previous added route when the component that added the route is removed.

While the OSGI side is pretty easy to implement, the problem is that there is no way currently to remove a previous added route ...

## Desired solution

Extend [HttpServerRoutes](https://github.com/reactor/reactor-netty/blob/main/reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerRoutes.java) to a remove option. Remove option should be overloaded to be able to remove by:

(Examples, not thread safe)

- Predicate instance
```java
  public HttpServerRoutes remove(Predicate<? super HttpServerRequest> condition) {
      for(HttpRouteHandler h: handlers){
          if(h.condition.equals(condition)){
              handlers.remove(h);
          }
      }
      return this;
  }
```
- Handler instance
```java
  public HttpServerRoutes remove(BiFunction<? super HttpServerRequest, ? super HttpServerResponse, ? extends Publisher<Void>> handler) {
      for(HttpRouteHandler h: handlers){
          if(h.handler.equals(handler)){
              handlers.remove(h);
          }
      }
      return this;
  }
```
- Path
 ```java
  public HttpServerRoutes remove(String path) {
      for(HttpRouteHandler h: handlers){
          if(h.path != null && h.path.equals(path)){
              handlers.remove(h);
          }
      }
      return this;
  }
```

## Considered alternatives

Extend [HttpServerRoutes](https://github.com/reactor/reactor-netty/blob/main/reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerRoutes.java) and add a new variant for each method that uses a publisher as a argument

```java
  public interface HttpServerRoute {

      Predicate<? super HttpServerRequest> condition();

      BiFunction<? super HttpServerRequest, ? super HttpServerResponse, ? extends Publisher<Void>> handler()

  }

public void route(Publisher<HttpServerRoute> publisher) {
  publisher.subscribe(new Subscriber<HttpServerRoute>() {
  
	  private final List<HttpRouteHandler> publisherHandlers = new CopyOnWriteArrayList<>();
  
	  @Override
	  public void onSubscribe(Subscription subscription) {
		  subscription.request(Integer.MAX_VALUE);
	  }
  
	  @Override
	  public void onNext(HttpServerRoute httpServerRoute) {
		  publisherHandlers.add(addRoute(httpServerRoute.condition(), httpServerRoute.handler()));
	  }
  
	  @Override
	  public void onError(Throwable t) {
  
		  // TODO: Remove all handlers added ??????
  
	  }
  
	  @Override
	  public void onComplete() {
  
		  // Remove all handler added by the publisher
		  initialOrderHandlers.removeAll(publisherHandlers);
		  handlers.removeAll(publisherHandlers);
	  }
  });
}
```

or

Extend [HttpServerRoutes](https://github.com/reactor/reactor-netty/blob/main/reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerRoutes.java) and add a new variant for each method that returns a [Subscription](https://github.com/reactive-streams/reactive-streams-jvm/blob/master/api/src/main/java/org/reactivestreams/Subscription.java) or similar.

```java
  public Subscription publishRoute(Predicate<? super HttpServerRequest> condition,
                                BiFunction<? super HttpServerRequest, ? super HttpServerResponse, ? extends Publisher<Void>> handler) {
      Objects.requireNonNull(condition, "condition");
      Objects.requireNonNull(handler, "handler");

      if (condition instanceof HttpPredicate) {
          HttpRouteHandler httpRouteHandler = new HttpRouteHandler(condition,
                  handler,
                  (HttpPredicate) condition, ((HttpPredicate) condition).uri);

          handlers.add(httpRouteHandler);
          initialOrderHandlers.add(httpRouteHandler);
          return new Subscription() {
              @Override
              public void request(long n) {

              }

              @Override
              public void cancel() {
                  handlers.remove(httpRouteHandler);
              }
          };

```

**Comment by roggenbrot** [comment]
I'm willing to provide a pull request if this is something you would consider to add

**Comment by OlegDokuka** [comment]
@roggenbrot please go ahead. Will be happy to guide you through the process!

**Comment by ctlove0523** [comment]
This is a good idea, also i think modify(add、delete) route after `HttpServer.bind()` is helpful, especially use reactor netty to construct a API Gateway directly(not like Spring Cloud Gateway).In current version there is no way to do this.

**Comment by roggenbrot** [comment]
After playing around a little bit i like the [publisher](https://github.com/roggenbrot/reactor-netty/blob/feature/1669-remove-route/reactor-netty-http/src/main/java/reactor/netty/http/server/DefaultHttpServerRoutes.java#L111-L140) approach most, but it has some downsides.

Publisher passed  is not allowed to complete before user wants to remove all routes added via the publisher, otherwise the added route(s) is immediately removed again.

Not sure if most of the people would just use `Mono.just` and wonder why the route is never executed.

**Comment by violetagg** [comment]
@roggenbrot  Please take a look at #1676

**Comment by roggenbrot** [comment]
I'm currently on vacation. I will update the issue asap
