### ISSUE TITLE
Test case failures on environments with locale != en

### ISSUE THREAD

**Issue by roggenbrot** [reactor/reactor-netty#1673]
When trying to build `reactor-netty` on a environment with a locale set != en. The following test cases will fail after startting the build with ``

[DefaultPooledConnectionProviderTest.fixedPoolTwoAcquire()](https://github.com/reactor/reactor-netty/blob/main/reactor-netty-core/src/test/java/reactor/netty/resources/DefaultPooledConnectionProviderTest.java#L132)

[HttpClientTest.testRetryDisabledWhenHeadersSent()](https://github.com/reactor/reactor-netty/blob/main/reactor-netty-http/src/test/java/reactor/netty/http/client/HttpClientTest.java#L1272)

and 8 others.

## Expected Behavior

Build finishes successful on environments with locale != en

## Actual Behavior

Build fails

## Steps to Reproduce

Start build on environment with locale != en

## Possible Solution

```java
StepVerifier.create(pool.acquire(config, observer, remoteAddress, config.resolverInternal()))
			        .verifyErrorMatches(msg -> msg.getMessage().contains("Connection refused"));
StepVerifier.create(pool.acquire(config, observer, remoteAddress, config.resolverInternal()))
			        .verifyErrorMatches(msg -> msg.getMessage().contains("Connection refused"));
```
to 
```java
StepVerifier.create(pool.acquire(config, observer, remoteAddress, config.resolverInternal()))
			        .verifyErrorMatches(msg -> msg.getCause() instanceof ConnectException);
StepVerifier.create(pool.acquire(config, observer, remoteAddress, config.resolverInternal()))
			        .verifyErrorMatches(msg -> msg.getCause() instanceof ConnectException);
```

and remove other language dependent tests

## Your Environment

Reactor version(s) used:
reactor-netty 1.0.8
JVM version :
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.7+10, mixed mode)
OS and version:
Linux 5.12.10-arch1-1 #1 SMP PREEMPT Thu, 10 Jun 2021 16:34:50 +0000 x86_64 GNU/Linux

**Comment by roggenbrot** [comment]
Or is this not supported?

**Comment by violetagg** [comment]
@roggenbrot The proposed solutions looks OK. Would you like to create a PR?

**Comment by roggenbrot** [comment]
There might be also more locale specific problems in runtime code

[AbortedException](https://github.com/roggenbrot/reactor-netty/blob/fbce9325c2da531e1877b6ada84eaf74db3c40fd/reactor-netty-core/src/main/java/reactor/netty/channel/AbortedException.java#L56)

**Comment by violetagg** [comment]
@roggenbrot Can you run all tests and provide info with the failing tests?

**Comment by roggenbrot** [comment]
I've fixed every test in my branch, except one which seems not to be locale related and only fails from time to time:

```
UdpServerTests > supportsUdpMulticast() FAILED
    org.opentest4j.AssertionFailedError: [latch await] 
    Expecting value to be true but was false
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at reactor.netty.udp.UdpServerTests.supportsUdpMulticast(UdpServerTests.java:181)

```
It fails only when doing a `./gradlew build`, I can run the test case within IntelliJ succesfully

![grafik](https://user-images.githubusercontent.com/41467575/122273909-43c75600-cee2-11eb-8158-a31e7ae2cd64.png)

My environment

```
[xxxxxxxx@xxxxxxxxxxxxxxx reactor-netty]$ env
SHELL=/bin/bash
SESSION_MANAGER=******************
XDG_CONFIG_DIRS=/etc/xdg
XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session0
XDG_MENU_PREFIX=xfce-
TERMINAL_EMULATOR=JetBrains-JediTerm
JAVA_HOME=/home/*********/.sdkman/candidates/java/current
SSH_AUTH_SOCK=******************
TERM_SESSION_ID=*********************************
SDKMAN_CANDIDATES_DIR=/home/***************/.sdkman/candidates
DESKTOP_SESSION=xfce
SSH_AGENT_PID=3642
GTK_MODULES=canberra-gtk-module:canberra-gtk-module
XDG_SEAT=seat0
PWD=/home/****************/Projects/third-party/reactor-netty
XDG_SESSION_DESKTOP=xfce
LOGNAME=sdais
QT_QPA_PLATFORMTHEME=gtk2
XDG_SESSION_TYPE=x11
PANEL_GDK_CORE_DEVICE_EVENTS=0
IDEA_JDK=/usr/lib/jvm/java-11-openjdk/
XAUTHORITY=/home/sdais/.Xauthority
DESKTOP_STARTUP_ID=wrapper-2.0/|usr|bin|idea/******************
XDG_GREETER_DATA_DIR=/var/lib/lightdm-data/******************
MOTD_SHOWN=pam
HOME=/home/******************
LANG=de_DE.UTF-8
XDG_CURRENT_DESKTOP=XFCE
SDKMAN_VERSION=5.8.3+506
XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
GROOVY_HOME=/home/************/.sdkman/candidates/groovy/current
IDEA_CLASSPATH=/usr/lib/jvm/java-11-openjdk//lib/*:/usr/lib/jvm/java-11-openjfx//lib/*
NVM_DIR=/home/*************/.nvm
XDG_SESSION_CLASS=user
TERM=xterm-256color
USER=sdais
MAVEN_HOME=/home/************/.sdkman/candidates/maven/current
SDKMAN_DIR=/home/*************/.sdkman
DISPLAY=:0.0
SHLVL=2
NVM_CD_FLAGS=
XDG_VTNR=7
SDKMAN_CANDIDATES_API=https://api.sdkman.io/2
XDG_SESSION_ID=2
XDG_RUNTIME_DIR=/run/user/1000
XDG_DATA_DIRS=/usr/local/share:/usr/share
PATH=**************
GDMSESSION=xfce
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
SDKMAN_PLATFORM=Linux64
MAIL=/var/spool/mail/************
_=/usr/bin/env

```
Maybe it's better if I open another issue for this problem after I've done further testing

**Comment by violetagg** [comment]
> Maybe it's better if I open another issue for this problem after I've done further testing

Yes please do so
