### ISSUE TITLE
ColocatedEventLoopGroup do not work for "reactor-http-nio-2"

### ISSUE THREAD

**Issue by copbint** [reactor/reactor-netty#1679]
## Expected Behavior
ColocatedEventLoopGroup works well, so connections created will register to the local event loop

## Actual Behavior
`reactor-http-nio-2` behaves abnormal, `localLoop.isSet()` returns false, so  connections created in `reactor-http-nio-2` do not register to the local event loop。

## Steps to Reproduce
please see minmal demo in: <https://github.com/copbint/netty-debug>
1. run `ApplicationOfA`
2. run `ApplicationOfB`
3. run `for((i=0;i<=30;i++))do curl http://localhost:8080/v1/time -s -o /dev/null;done`

you will see output of `ApplicationOfA` like this:
```
[Thread[reactor-http-nio-2,5,main]] controller executing...->[Thread[reactor-http-nio-4,5,main]] Mono executing...
[Thread[reactor-http-nio-1,5,main]] controller executing...->[Thread[reactor-http-nio-1,5,main]] Mono executing...
[Thread[reactor-http-nio-2,5,main]] controller executing...->[Thread[reactor-http-nio-4,5,main]] Mono executing...
[Thread[reactor-http-nio-3,5,main]] controller executing...->[Thread[reactor-http-nio-3,5,main]] Mono executing...
[Thread[reactor-http-nio-4,5,main]] controller executing...->[Thread[reactor-http-nio-4,5,main]] Mono executing...
[Thread[reactor-http-nio-1,5,main]] controller executing...->[Thread[reactor-http-nio-1,5,main]] Mono executing...
[Thread[reactor-http-nio-2,5,main]] controller executing...->[Thread[reactor-http-nio-4,5,main]] Mono executing...
[Thread[reactor-http-nio-3,5,main]] controller executing...->[Thread[reactor-http-nio-3,5,main]] Mono executing...
[Thread[reactor-http-nio-4,5,main]] controller executing...->[Thread[reactor-http-nio-4,5,main]] Mono executing...
[Thread[reactor-http-nio-1,5,main]] controller executing...->[Thread[reactor-http-nio-1,5,main]] Mono executing...
```

## Possible Reason
```
	ColocatedEventLoopGroup(EventLoopGroup eventLoopGroup) {
		this.eventLoopGroup = eventLoopGroup;
		for (EventExecutor ex : eventLoopGroup) {
			if (ex instanceof EventLoop) {
				//"FutureReturnValueIgnored" this is deliberate
				ex.submit(() -> {
					if (!localLoop.isSet()) { // set a line break point here with condition: `"reactor-http-nio-2".equals(Thread.currentThread().getName())`
						localLoop.set((EventLoop) ex);
					}
				});
			}
		}
	}
```
by add line break point, I found that:
the task submited to `reactor-http-nio-2` is executed **after** the elg.next() is called:
```
		MonoChannelPromise monoChannelPromise = new MonoChannelPromise(channel);
		channel.unsafe().register(elg.next(), monoChannelPromise);// please see this line
		Throwable cause = monoChannelPromise.cause();
		if (cause != null) {
			if (channel.isRegistered()) {
				// "FutureReturnValueIgnored" this is deliberate
				channel.close();
			}
			else {
				channel.unsafe().closeForcibly();
			}
		}
```

## Your Environment
* Reactor version(s) used: 1.0.7
* Other relevant libraries versions (eg. `netty`, ...): 4.1.65
* JVM version (`java -version`): openjdk version "11.0.8" 2020-07-14
* OS and version (eg. `uname -a`):  I have tested on windows 10(4 core), windows 10(12 core), and ubuntu 20.04(64 core), all can reproduce this. 

# thanks!

**Comment by violetagg** [comment]
@copbint Thanks for the reproducible example, it helped a lot. If you are able to test 1.0.9-SNAPSHOT it will be great!

**Comment by copbint** [comment]
I have tested 1.0.9-SNAPSHOT, and it works well. Thanks for your great work!
A small tip for others:
SNAPSHOT versions can be found on: http://repo.spring.io/libs-snapshot-local/

**Comment by violetagg** [comment]
> I have tested 1.0.9-SNAPSHOT, and it works well. Thanks for your great work!
> A small tip for others:
> SNAPSHOT versions can be found on: http://repo.spring.io/libs-snapshot-local/

thanks
