### ISSUE TITLE
MonoToCompletableFuture#get never return because the invocation of onComplete method before onSubscribe

### ISSUE THREAD

**Issue by codergmc** [reactor/reactor-netty#1684]
The problem comes from [https://github.com/spring-projects/spring-framework/issues/26464#issue-795660549](https://github.com/spring-projects/spring-framework/issues/26464#issue-795660549)

## Steps to Reproduce
A demo to reproduce:[https://github.com/codergmc/websocket-demo](https://github.com/codergmc/websocket-demo)

- rabbitmq(enable stomp):3.8.16 
- java:adopt-openjdk-15.0.2

- Visit [http://localhost:9999/test](http://localhost:9999/test)

- Visit [http://localhost:9999/checking](http://localhost:9999/checking) and problem occured when the result as follow

```
java.base@15.0.2/jdk.internal.misc.Unsafe.park(Native Method)
java.base@15.0.2/java.util.concurrent.locks.LockSupport.park(LockSupport.java:211)
java.base@15.0.2/java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1860) 
java.base@15.0.2/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3137) 
java.base@15.0.2/java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1887) 
java.base@15.0.2/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2062) 
app//reactor.core.publisher.MonoToCompletableFuture.get(MonoToCompletableFuture.java:81) 
app//org.springframework.util.concurrent.CompletableToListenableFutureAdapter.get(CompletableToListenableFutureAdapter.java:99) 
app//org.springframework.messaging.simp.stomp.StompBrokerRelayMessageHandler$SystemSessionConnectionHandler.forward(StompBrokerRelayMessageHandler.java:1081) 
.......
```

- You can find some lastest logs as follow.This mean  the invocation of `MonoToCompletableFuture#onComplete` method before `MonoToCompletableFuture#onSubscribe`.Because `MonoToCompletableFuture.ref` is null when invoke `MonoToCompletableFuture#onComplete` method

```
2021-06-23 05:14:28.062  INFO 37138 --- [ient-loop-nio-2] r.c.publisher.MonoToCompletableFuture    : onComplete this:reactor.core.publisher.MonoToCompletableFuture@379a9335[Not completed] ref:null
2021-06-23 05:14:28.062  INFO 37138 --- [    test_thread] r.c.publisher.MonoToCompletableFuture    : onSubscribe this:reactor.core.publisher.MonoToCompletableFuture@379a9335[Not completed] ref:null
2021-06-23 05:14:28.062  INFO 37138 --- [    test_thread] r.c.publisher.MonoToCompletableFuture    : get start this:reactor.core.publisher.MonoToCompletableFuture@379a9335[Not completed, 1 dependents] ref:reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber@55777635
```

**Comment by violetagg** [comment]
@codergmc This is more Reactor Core related.
@simonbasle @OlegDokuka PTAL

**Comment by OlegDokuka** [comment]
Looking into that

**Comment by OlegDokuka** [comment]
Seems to be upstream publisher problem. MonoToCompletableFuture has nothing to do with that since it is just a conversion layer between upstream and the downstream `.get` method.

@codergmc can y

**Comment by OlegDokuka** [comment]
Indeed. This is a bug in reactor-netty. At that place, https://github.com/reactor/reactor-netty/blob/3ecd06c52263a61fb06a21fada7174f05a0d1173/reactor-netty-core/src/main/java/reactor/netty/FutureMono.java#L97 `onSubscribe` happens after the subscription listener is set. which means that there can be a race between onComplete and onSubscribe signaling

**Comment by codergmc** [comment]
I open a issue in reactor-core [https://github.com/reactor/reactor-core/issues/2723#issue-928288429](https://github.com/reactor/reactor-core/issues/2723#issue-928288429)

**Comment by OlegDokuka** [comment]
@codergmc I don't think it is related to reactor anyhow. It's reactor-netty bug.

**Comment by codergmc** [comment]
@OlegDokuka  
 A simplified spring invoke chain :
```
private final NettyOutbound outbound;

public void send(ByteBuf byteBuf) {
		Mono<Void> sendCompletion = this.outbound.send(Mono.just(byteBuf)).then();
		return  sendCompletion.toFuture().get();
}
```
I have never studied any reactor documentation.So i don't know  what to do  when invoke `outbound.send(Mono.just(byteBuf)).then()`.   But in my opinion it contains at least two threads.One invoke `send` .Another
one is netty eventloop.Maybe it also hava some reactor thread. `Mono` contact netty `ChannelFuture` return by netty `write` and this thread. Regardless of whether the `Mono` internal implementation is asynchronous or synchronous.`Mono.toFuture()` shoud do right thing.`Mono.toFuture()` return  `MonoToCompletableFuture`, it use atomicReference field `ref`.But it didn't consider the situation that invoke `onComplete` happen before `onSubscribe` .So i think it hava bug in `MonoToCompletableFuture` and it belong to  `reactor-core`.

**Comment by OlegDokuka** [comment]
Just FYI. Oncomplete before onSubscribe is illegal behavior (as of Reactive Streams spec) and MonoToCompletableFuture should not handle that at all.

As I mentioned it is something at FutureMono (part of Reactor-netty) or something on the spring side.

Thank you for your investigation!

**Comment by hurahurat** [comment]
I think put s.onSubscribe(fs) before future.addListener(fs) could fix this bug. 
@violetagg Please fix it soon and make it backward compatibility for older versions.

**Comment by codergmc** [comment]
@hurahurat I think so

**Comment by violetagg** [comment]
@rstoyanchev With Spring Boot 2.3.11.RELEASE the provided example does not fail, with Spring Boot 2.3.12.RELEASE - it fails. In both cases Reactor Netty is 0.9.20.RELEASE and Netty is 4.1.65.Final.
I see you mentioned here some change in Spring Framework https://github.com/spring-projects/spring-framework/issues/26464#issuecomment-852913502

**Comment by hurahurat** [comment]
These changes are not applied in springboot version 2.3.x and the version of spring is the same (5.2.15.RELEASE) on both 2.3.11.RELEASE and 2.3.12.RELEASE.
I think the results should be the same for both versions and I did not observe any failures in 2.3.12.RELEASE version while testing.
@violetagg Could you test it again in 2.3.12.RELEASE version?

**Comment by violetagg** [comment]
> These changes are not applied in springboot version 2.3.x and the version of spring is the same (5.2.15.RELEASE) on both 2.3.11.RELEASE and 2.3.12.RELEASE.
> I think the results should be the same for both versions and I did not observe any failures in 2.3.12.RELEASE version while testing.
> @violetagg Could you test it again in 2.3.12.RELEASE version?

Yes you are correct my IDE didn't refresh the project - the issue is not in 2.3.x and it is in 2.4/2.5

**Comment by violetagg** [comment]
All, let me summarise the issue:

In version 2.3.x, Spring Framework (based on Reactor Netty 0.9.x) uses `MonoProcessor`
https://github.com/spring-projects/spring-framework/blob/43901b2c6a10edd0909350f6b7efefe99f4d0076/spring-core/src/main/java/org/springframework/util/concurrent/MonoToListenableFutureAdapter.java#L38

`MonoProcessor` guards `onSubscribe`/`onComplete` thus the issue in Reactor Netty is not visible.

In Spring Framework versions 2.4.x/2.5.x (based on Reactor Netty 1.0.x), `MonoToListenableFutureAdapter` was rewritten and the implementation was switched to use `MonoToCompletableFuture`. And now the guards are not there anymore and thus the issue in Reactor Netty is revealed. 

Thank you all for the reproducible example and the debugging effort!

We are going to prepare a fix for Reactor Netty.

**Comment by violetagg** [comment]
The fix is available in 1.0.9-SNAPSHOT.
If you can test it, it will be great! Thanks.

**Comment by hurahurat** [comment]
@violetagg @OlegDokuka Thank you for the fix. I have one more question. When the future of future.addListener(fs) is run then finished before the guard(check fs.cancelled again then future.removeListener(fs)), what could happen in this case?

**Comment by violetagg** [comment]
@hurahurat So basically the question is if we add the listener here

https://github.com/reactor/reactor-netty/blob/1675390ff411ee29337b8c46123ab677130c6fca/reactor-netty-core/src/main/java/reactor/netty/FutureMono.java#L144

and it finishes immediately:

Case one: There is NO `cancel` signal -> you will have `onSubscribe` followed by `onComplete`

Case two: There is `cancel` signal -> you will have `onSubscribe`, then you may have `cancel` followed by `onComplete` as `cancel` may be executed in a separate thread.
Also according to the spec we have:

```
If a Subscription is cancelled its Subscriber MUST eventually stop being signaled.
--
💡 | The intent of this rule is to make sure that Publishers respect a Subscriber’s request to cancel a Subscription when Subscription.cancel() has been called. The reason for eventually is because signals can have propagation delay due to being asynchronous.
```

https://github.com/reactive-streams/reactive-streams-jvm

**Comment by hurahurat** [comment]
@violetagg Thank you for your explanation.
