### ISSUE TITLE
Performance degradation when using SSL with WebFlux (Netty server)

### ISSUE THREAD

**Issue by jonathannaguin** [reactor/reactor-netty#1685]
**Affects:** 

spring-boot-starter-webflux:2.4.6
spring-boot-starter-reactor-netty:2.4.6

**Description**

I have a small WebFlux app that, for the sake of this issue, just logs stuff when it receives a request from a HTTP endpoint.
This endpoint is being hit by a load test performed by Gatling on my laptop. 
The app runs on a Docker container (limited to 1 CPU and 2 GB of RAM) and using 150 netty IO workers.
With SSL off (plain HTTP) the container can handle 100 requests per second:
```
================================================================================
---- Global Information --------------------------------------------------------
> request count                                      90000 (OK=90000  KO=0     )
> min response time                                    110 (OK=110    KO=-     )
> max response time                                  81107 (OK=81107  KO=-     )
> mean response time                                  3562 (OK=3562   KO=-     )
> std deviation                                       8615 (OK=8615   KO=-     )
> response time 50th percentile                        199 (OK=199    KO=-     )
> response time 75th percentile                        338 (OK=338    KO=-     )
> response time 95th percentile                      21932 (OK=21905  KO=-     )
> response time 99th percentile                      42839 (OK=42841  KO=-     )
> mean requests/sec                                 99.889 (OK=99.889 KO=-     )
---- Response Time Distribution ------------------------------------------------
> t < 800 ms                                         73446 ( 82%)
> 800 ms < t < 1200 ms                                 650 (  1%)
> t > 1200 ms                                        15904 ( 18%)
> failed                                                 0 (  0%)
================================================================================

```
If I add SSL, the load test for 100 req/s fails with a bunch of "SSLException: handshake timed out". Notice I see this error on the load test output, not on the container. I have to decrease the load to **just 15 req/s** to avoid the handshake errors.
I know that SSL will impose some overhead but I wasn't expecting this degradation.
By the way, this is my netty server configurer:
```
    @Bean
    public NettyServerCustomizer nettyServerCustomizer()
    {
        return httpServer -> httpServer.idleTimeout(Duration.ofMinutes(10))
                                   .option(ChannelOption.SO_BACKLOG, 65535)
                                   .option(ChannelOption.SO_REUSEADDR, true)
                                   .childOption(ChannelOption.TCP_NODELAY, true)
                                   .childOption(ChannelOption.SO_KEEPALIVE, true);
    }
```

**Comment by violetagg** [comment]
@jonathannaguin https://github.com/spring-projects/spring-framework/issues/27087#issuecomment-866079662

There are some interesting points that @bclozel outlined in the comment above.

Can you elaborate more on the scenario and some of the decisions that you did?

**Comment by jonathannaguin** [comment]
My Gatling scenario inserts a constant number of users to meet the number of requests per second I want. I am not re-using connections for the users, but in reality, I can't expect my callers to re-user connections.
The JVM is configured with -XX:MaxRAMPercentage=80.0 and -Dreactor.netty.ioWorkerCount=150, so we leave some headroom plus we increased the number of workers, as by default it would only use 4 which is quite low.
I don't think I am using openssl library if that does not come by default.

Please let me know if you need more details from me

**Comment by violetagg** [comment]
@jonathannaguin What's the difference when you use 150 threads vs 4 threads? You write it is quite low, do you have any numbers from the performance test?

**Comment by jonathannaguin** [comment]
@violetagg  with only 4 threads, the container is not able to cope with 100 req/secs. After a few seconds of having the load test running, I start getting many  "connection timed out" on Gatling, where the timeout is 1 minute, so there are requests taking that long to be processed by the app. Increasing the number of workers addresses this problem in expense of memory.

**Comment by violetagg** [comment]
> @violetagg with only 4 threads, the container is not able to cope with 100 req/secs. After a few seconds of having the load test running, I start getting many "connection timed out" on Gatling, where the timeout is 1 minute, so there are requests taking that long to be processed by the app. Increasing the number of workers addresses this problem in expense of memory.

@jonathannaguin Is it possible that you execute in the event loop some CPU intensive/blocking operations?

**Comment by jonathannaguin** [comment]
@violetagg  I can add BlockHound and run another test, but I am just logging the JSON payload at this point. I have turned off all of the business logic of the service to understand better this problem.

**Comment by violetagg** [comment]
> @violetagg I can add BlockHound and run another test, but I am just logging the JSON payload at this point. I have turned off all of the business logic of the service to understand better this problem.

@jonathannaguin Interesting ... you use async appender for logging, don't you?
Also you use different containers for the road runner and the application, don't you?

**Comment by jonathannaguin** [comment]
@violetagg I was using the default appender, just switched to use the async appender. In addition to this change, I added BlockHound and noticed one of my dependencies was making a blocking call:
```
UUID.randomUUID().toString()
```
I commented out that code for now (I need to find a workable solution for this though) and executed another load test with just 4 worker threads and the results were much better than before. I can load 100 requests per second with not issue.

However, this test was done against the HTTP version of the app, when I enable SSL on the application, I am still get loads "handshake timed out" on Gatling.

**Comment by violetagg** [comment]
@jonathannaguin Let's continue this discussion on [Gitter](https://gitter.im/reactor/reactor-netty) - our channel for real-time discussions. If it appears a problem in Reactor Netty we can reopen this issue.

> UUID.randomUUID().toString()

You have to offload blocking calls in another thread pool.
Check here for more information https://projectreactor.io/docs/core/release/reference/#faq.wrap-blocking

**Comment by violetagg** [comment]
Link to the Gitter discussion
https://gitter.im/reactor/reactor-netty?at=60dd80904e325e6132b3482e
