### ISSUE TITLE
Connection has been closed BEFORE response, while sending request body

### ISSUE THREAD

**Issue by niuzhimin** [reactor/reactor-netty#1695]
Description:

First of all, this error is reported by gateway gateway

The reason for the error is that the size of the image uploaded on the web service exceeds the configuration of spring. Servlet. Multipart. Max file size = 10MB, but it is intercepted in the file Upload Interceptor of the web service and gives a friendly response. I don't know why the gateway reported this mistake

Ask the great God to answer

**Comment by violetagg** [comment]
@niuzhimin Most probably this is a duplicate to #1478. Please check your Spring Cloud Gateway version.

**Comment by niuzhimin** [comment]
@violetagg The spring cloud gateway version is 2.1.1 I just had a look #1478 I don't see the solution。Can you give us a detailed answer please

**Comment by niuzhimin** [comment]
@violetagg Why and how to solve this problem? Is it related to the gateway version?

**Comment by niuzhimin** [comment]
@violetagg Why and how to solve this problem? Is it related to the gateway version?

**Comment by violetagg** [comment]
@niuzhimin This has been fixed in Reactor Netty v1.0.4 which is Spring Cloud Gateway v3.0.2

The fix that was made is that you will receive the original error from the server i.e. error code 400, describing that the upload size is invalid.

**Comment by niuzhimin** [comment]
What is the corresponding version of springboot?

**Comment by violetagg** [comment]
> What is the corresponding version of springboot?

Spring Boot v2.4.3/v2.5.0

**Comment by niuzhimin** [comment]
Does it have to be this high?

**Comment by violetagg** [comment]
> Does it have to be this high?

I didn't get it

Reactor Netty 1.0.4 (where the fix was included for the first time) is available with Spring Boot v2.4.3.
Spring Boot v2.5.0 contains the fix from the very beginning.

**Comment by niuzhimin** [comment]
Well, I mean, is it compatible with other versions? If the spring boot version is 2.4.3, the cloud service version must be the latest. Is there any other solution? As long as the gateway does not report an error and gives a friendly prompt that the upload of files is restricted

**Comment by violetagg** [comment]
> Well, I mean, is it compatible with other versions? If the spring boot version is 2.4.3, the cloud service version must be the latest. Is there any other solution? As long as the gateway does not report an error and gives a friendly prompt that the upload of files is restricted

That should be discussed with Spring Cloud Gateway maintainers ...

**Comment by niuzhimin** [comment]
OK, thank you very much for your help, beautiful lady

**Comment by violetagg** [comment]
@niuzhimin Let me close this issue as duplicate. We can reopen it, if it is needed.
