### ISSUE TITLE
httpClient.responseTimeout cannot be unset

### ISSUE THREAD

**Issue by philsttr** [reactor/reactor-netty#1697]
Calling `httpClient.responseTimeout(null)` results in an NPE, rather than unsetting the value like the documentation indicates.

## Expected Behavior
https://github.com/reactor/reactor-netty/blob/863ab78e13e56cc3828dac2daa44e6ff7187f99d/reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClient.java#L1315-L1316

## Actual Behavior
NullPointerException is thrown

https://github.com/reactor/reactor-netty/blob/863ab78e13e56cc3828dac2daa44e6ff7187f99d/reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClient.java#L1329

## Steps to Reproduce

```java
@Test
public void repoCase() {
    HttpClient.create().responseTimeout(null);
}
```

## Possible Solution
remove requireNonNull

## Your Environment

* Reactor version(s) used: 1.0.8

**Comment by violetagg** [comment]
@philsttr nice catch!
Here is a fix for it #1700
Thanks a lot!
