### ISSUE TITLE
Reactor Netty does calculate the poolkey hash for every supplied MetricsRecorder

### ISSUE THREAD

**Issue by smaldini** [reactor/reactor-netty#1707]
In https://github.com/reactor/reactor-netty/blob/main/reactor-netty-core/src/main/java/reactor/netty/transport/TransportConfig.java#L83, the supplied metrics recorder instance is used to calculate the channelHash() value. This is causing the pool key cardinality to explode beyond whats expected.

As a workaround, implementing hashcode/equals or returning the same metricsRecorder is possible. However it seems much safer to calculate the hash off the supplier itself instead of the supplied instance.

**Comment by violetagg** [comment]
@smaldini PTAL #1717 I decided to obtain the metrics resolver on the configuration step when the metrics are enabled.
