### ISSUE TITLE
reactor_netty_connection_provider_active_connections is always 0, despite successful http requests

### ISSUE THREAD

**Issue by patpatpat123** [reactor/reactor-netty#1712]
Hello Reactor Team,

I wanted to repot an issue where the metric ```reactor_netty_connection_provider_active_connections``` always stays at 0, despite successful http requests.

Setup of experiment, at the hour, there is a trigger from an external app to my Spring Webflux app (I am the server). My Spring Webflux app will then make an http request (outbound, this time, I am the client) to a third party API.

The third party API is very resilient, and never fails. For proof, we do always get their HTTP response back.

Now, looking at the four metrics described here: https://projectreactor.io/docs/netty/release/reference/index.html#_metrics_3

```
reactor.netty.connection.provider.total.connections
reactor.netty.connection.provider.active.connections
reactor.netty.connection.provider.idle.connections
reactor.netty.connection.provider.pending.connections
```

I am surprise why active stays at 0, always.

I do see ```total.connections``` being incremented at every hour. I would say this is expected, since every hour, I make a successful http request to someone else.

I do see ```idle.connections``` being incremented at every hour. I would say this is expected, since every hour, I make a successful http request to someone else, I would imagine, after the successful request, the connection becomes idle, and stay that way forever

I do see ```pending.connections``` being flat at 0. but I would say this is expected since the http request is always successful, nothing is waiting, nothing is pending.

But I am surprised active stays at 0. I would have expected, at some point, active being incremented, since there is some kind of connection between me and the third party app.

Is it possible there is an issue this particular counter on not being incremented please?

Thank you

**Comment by violetagg** [comment]
@patpatpat123
From the documentation we have this

`reactor.netty.connection.provider.active.connections`
```
The number of the connections that have been successfully acquired and are in active use
```

May be it is not clear and we have to enhance the documentation. 

So active connection is such connection that is currently processing a request, once you receive the response we return this connection to the pool and it is no more active, but idle connection.

Basically `total connections = active connections + idle connections`

**Comment by patpatpat123** [comment]
Yes, this is exactly what I am trying to point out! Thanks!

"once you receive the response we return this connection to the pool and it is no more active, but idle connection."

This means, at some point, when I did not receive the response yet, the connection should be active, with 0 idle.

And then, once I receive the connection, there should be 0 active, and 1 idle.

But what I am observing, it a 0 always for active.

What I am seeing after a response is:

```total connections = active connections + idle connections```
```1 = 0 + 1```

But at the moment of a http request, I see
```total connections = active connections + idle connections```
```1 = 0 + 0```

The active connection always stays 0, no matter how many http request I am making or made

**Comment by violetagg** [comment]
@patpatpat123 Can you provide some reproducible example?

We do have tests and they do not show such behaviour so it might be something specific for your scenario.

https://github.com/reactor/reactor-netty/blob/1c89a987e1aa9a5629979e3a109d1839595eb6c5/reactor-netty-http/src/test/java/reactor/netty/resources/PooledConnectionProviderDefaultMetricsTest.java#L100-L108

**Comment by patpatpat123** [comment]
Understood, and thank you for pointing me to this, I will try to dig if it is not a "me issue".

Since there is a set of test already in place, maybe it is just me.

On my side, I am just also raising am issue based on Grafana data:

<img width="1722" alt="Screen Shot 2021-07-05 at 4 16 20 PM" src="https://user-images.githubusercontent.com/43899031/124439722-5976bf80-ddac-11eb-99bc-de86e9a02709.png">

For example here, we can clearly see http connections, with address being resolved, connect and SSL handshake.

But is those graph, we can clearly see active was flat 0 all the time. I was expecting an increase matching the time stamp.

<img width="1717" alt="Screen Shot 2021-07-05 at 4 17 49 PM" src="https://user-images.githubusercontent.com/43899031/124439902-8f1ba880-ddac-11eb-858f-23d54bce9f5e.png">

Will dig further

**Comment by patpatpat123** [comment]
Hello,

I have updated this https://github.com/patpatpat123/questionnettytrace to be. reproducible example.

In this test, I will trigger periodically, as one off, (just one curl one in a while) or put pressure (use gatling to put load)

The code will use Reactor Netty Http Client to send requests to a third party. In my test case, I am the also the third party, and received all the requests fine.

Unfortunately, the metrics behavior is the same as in the screenshot. It is flat always for ACTIVE.

Please let me know if I need to add anything else.

Thank you

**Comment by violetagg** [comment]
@patpatpat123 Interesting ... Can you point me where you enable the HttpClient metrics?

**Comment by patpatpat123** [comment]
I forgot to upload the latest commit. Updated 🙏

Overall, there are couple of places:

https://github.com/patpatpat123/questionnettytrace/blob/main/src/main/java/com/question/WebClientServiceImpl.java#L36

https://github.com/patpatpat123/questionnettytrace/blob/main/src/main/java/com/question/WebClientServiceImpl.java#L45

https://github.com/patpatpat123/questionnettytrace/blob/main/src/main/java/com/question/SomeConfiguration.java#L50

With such, I would have expected the metrics, especially the ACTIVE to go up and down. 

Can you kindly comment if everything is ok?

Thank you

**Comment by violetagg** [comment]
@patpatpat123 In your sample add the following

`WebClientServiceImpl`

```
    MeterRegistry registry = new SimpleMeterRegistry();

    WebClientServiceImpl() {
        Metrics.addRegistry(registry);
    }
```

```
        final var httpClient      = HttpClient.create()
                .wiretap("reactor.netty.http.client.HttpClient", LogLevel.INFO, AdvancedByteBufFormat.TEXTUAL)
                .metrics(true, Function.identity())
                .doOnResponse((res, conn) -> {
                    System.out.println("active connections >>> " + getGaugeValue());
                });
```

```
    private double getGaugeValue() {
        Gauge gauge = registry.find(CONNECTION_PROVIDER_PREFIX + ACTIVE_CONNECTIONS).gauge();
        double result = -1;
        if (gauge != null) {
            result = gauge.value();
        }
        return result;
    }
```

you should see

```
active connections >>> 1.0
```

and also if you enable in `application.properties` -> `logging.level.reactor.netty.resources=debug` you should be able to see

```
Channel connected, now: 1 active connections, 0 inactive connections and 0 pending acquire requests.
```

**Comment by patpatpat123** [comment]
Hello @violetagg,

Indeed, this is working, and I am now seeing the metric being incremented.
Thank you

**Comment by violetagg** [comment]
> Hello @violetagg,
> 
> Indeed, this is working, and I am now seeing the metric being incremented.
> Thank you

That's very good!
