### ISSUE TITLE
DefaultConfigurationType marked as deprecated, but still used in public, non-deprecated API

### ISSUE THREAD

**Issue by crankydillo** [reactor/reactor-netty#1730]
[Non-deprecated usage](https://github.com/reactor/reactor-netty/blob/2ea7d622242f8750b70844c0a69a49446e8872f1/reactor-netty-core/src/main/java/reactor/netty/tcp/SslProvider.java#L97)

[Deprecation](https://github.com/reactor/reactor-netty/blob/2ea7d622242f8750b70844c0a69a49446e8872f1/reactor-netty-core/src/main/java/reactor/netty/tcp/SslProvider.java#L269)

Looks like `SslProvider#updateDefaultConfiguration` should be deprecated as well...

* Reactor version(s) used: 1.0.7

**Comment by violetagg** [comment]
@crankydillo nice catch - should be fixed with #1731
