### ISSUE TITLE
 Webclient + Hystix  ERR Caused by: java.lang.OutOfMemoryError: Direct buffer memory 

### ISSUE THREAD

**Issue by p4pramod** [reactor/reactor-netty#1735]
I am making a successive call to an API back to back using flux. The api call is made through webclient and under hystrix short circuit library.

## Expected Behavior
It should make the call properly 

## Actual Behavior
Failing with out of memory issue intermittently 

   .[31m2021-07-13T21:55:18.53+0800 [APP/PROC/WEB/1] ERR Caused by: java.lang.OutOfMemoryError: Direct buffer memory.[0m
   .[31m2021-07-13T21:55:18.53+0800 [APP/PROC/WEB/1] ERR 	at java.nio.Bits.reserveMemory(Bits.java:694).[0m
   .[31m2021-07-13T21:55:18.53+0800 [APP/PROC/WEB/1] ERR 	at java.nio.DirectByteBuffer.<init>(DirectByteBuffer.java:123).[0m
   .[31m2021-07-13T21:55:18.53+0800 [APP/PROC/WEB/1] ERR 	at java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:311).[0m
   .[31m2021-07-13T21:55:18.53+0800 [APP/PROC/WEB/1] ERR 	at io.netty.channel.unix.Buffer.allocateDirectWithNativeOrder(Buffer.java:40).[0m
   .[31m2021-07-13T21:55:18.53+0800 [APP/PROC/WEB/1] ERR 	at io.netty.channel.epoll.EpollEventArray.<init>(EpollEventArray.java:56).[0m
   .[31m2021-07-13T21:55:18.53+0800 [APP/PROC/WEB/1] ERR 	at io.netty.channel.epoll.EpollEventLoop.<init>(EpollEventLoop.java:95).[0m
   .[31m2021-07-13T21:55:18.53+0800 [APP/PROC/WEB/1] ERR 	at io.netty.channel.epoll.EpollEventLoopGroup.newChild(EpollEventLoopGroup.java:151).[0m
   .[31m2021-07-13T21:55:18.53+0800 [APP/PROC/WEB/1] ERR 	at io.netty.channel.epoll.EpollEventLoopGroup.newChild(EpollEventLoopGroup.java:35).[0m
   .[31m2021-07-13T21:55:18.53+0800 [APP/PROC/WEB/1] ERR 	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:84).[0m
   .[31m2021-07-13T21:55:18.53+0800 [APP/PROC/WEB/1] ERR 	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:58).[0m
   .[31m2021-07-13T21:55:18.53+0800 [APP/PROC/WEB/1] ERR 	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:47).[0m
   .[31m2021-07-13T21:55:18.53+0800 [APP/PROC/WEB/1] ERR 	at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:59).[0m
   .[31m2021-07-13T21:55:18.53+0800 [APP/PROC/WEB/1] ERR 	at io.netty.channel.epoll.EpollEventLoopGroup.<init>(EpollEventLoopGroup.java:112).[0m
   .[31m2021-07-13T21:55:18.53+0800 [APP/PROC/WEB/1] ERR 	at io.netty.channel.epoll.EpollEventLoopGroup.<init>(EpollEventLoopGroup.java:99).[0m
   .[31m2021-07-13T21:55:18.53+0800 [APP/PROC/WEB/1] ERR 	at io.netty.channel.epoll.EpollEventLoopGroup.<init>(EpollEventLoopGroup.java:76).[0m
   .[31m2021-07-13T21:55:18.53+0800 [APP/PROC/WEB/1] ERR 	at reactor.netty.resources.DefaultLoopEpoll.newEventLoopGroup(DefaultLoopEpoll.java:64).[0m
   .[31m2021-07-13T21:55:18.53+0800 [APP/PROC/WEB/1] ERR 	at reactor.netty.resources.DefaultLoopResources.cacheNativeServerLoops(DefaultLoopResources.java:252).[0m
   .[31m2021-07-13T21:55:18.53+0800 [APP/PROC/WEB/1] ERR 	at reactor.netty.resources.DefaultLoopResources.cacheNativeClientLoops(DefaultLoopResources.java:267).[0m
   .[31m2021-07-13T21:55:18.53+0800 [APP/PROC/WEB/1] ERR 	at reactor.netty.resources.DefaultLoopResources.onClient(DefaultLoopResources.java:199).[0m
   .[31m2021-07-13T21:55:18.53+0800 [APP/PROC/WEB/1] ERR 	at reactor.netty.tcp.TcpResources.onClient(TcpResources.java:218).[0m
   .[31m2021-07-13T21:55:18.53+0800 [APP/PROC/WEB/1] ERR 	at reactor.netty.http.client.HttpClientConnect$HttpTcpClient.connect(HttpClientConnect.java:135).[0m
   .[31m2021-07-13T21:55:18.53+0800 [APP/PROC/WEB/1] ERR 	at reactor.netty.tcp.TcpClientOperator.connect(TcpClientOperator.java:43).[0m
   .[31m2021-07-13T21:55:18.53+0800 [APP/PROC/WEB/1] ERR 	at reactor.netty.tcp.TcpClientOperator.connect(TcpClientOperator.java:43).[0m
   .[31m2021-07-13T21:55:18.53+0800 [APP/PROC/WEB/1] ERR 	at reactor.netty.tcp.TcpClientOperator.connect(TcpClientOperator.java:43).[0m
   .[31m2021-07-13T21:55:18.53+0800 [APP/PROC/WEB/1] ERR 	at reactor.netty.tcp.TcpClientOperator.connect(TcpClientOperator.java:43).[0m
   .[31m2021-07-13T21:55:18.53+0800 [APP/PROC/WEB/1] ERR 	at reactor.netty.tcp.TcpClientOperator.connect(TcpClientOperator.java:43).[0m
   .[31m2021-07-13T21:55:18.53+0800 [APP/PROC/WEB/1] ERR 	at reactor.netty.tcp.TcpClient.connect(TcpClient.java:189).[0m
   .[31m2021-07-13T21:55:18.53+0800 [APP/PROC/WEB/1] ERR 	at reactor.netty.http.client.HttpClientFinalizer.connect(HttpClientFinalizer.java:68).[0m
   .[31m2021-07-13T21:55:18.53+0800 [APP/PROC/WEB/1] ERR 	at reactor.netty.http.client.HttpClientFinalizer.responseConnection(HttpClientFinalizer.java:85).[0m
   .[31m2021-07-13T21:55:18.53+0800 [APP/PROC/WEB/1] ERR 	at org.springframework.http.client.reactive.ReactorClientHttpConnector.connect(ReactorClientHttpConnector.java:112).[0m
   .[31m2021-07-13T21:55:18.53+0800 [APP/PROC/WEB/1] ERR 	at org.springframework.web.reactive.function.client.ExchangeFunctions$DefaultExchangeFunction.exchange(ExchangeFunctions.java:104).[0m
   .[31m2021-07-13T21:55:18.53+0800 [APP/PROC/WEB/1] ERR 	at org.springframework.cloud.sleuth.instrument.web.client.TraceExchangeFilterFunction$MonoWebClientTrace.subscribe(TraceWebClientBeanPostProcessor.java:241).[0m
   .[31m2021-07-13T21:55:18.53+0800 [APP/PROC/WEB/1] ERR 	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:150).[0m
   .[31m2021-07-13T21:55:18.53+0800 [APP/PROC/WEB/1] ERR 	at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onNext(ScopePassingSpanSubscriber.java:96).[0m
   .[31m2021-07-13T21:55:18.53+0800 [APP/PROC/WEB/1] ERR 	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:114).[0m
   .[31m2021-07-13T21:55:18.53+0800 [APP/PROC/WEB/1] ERR 	at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onNext(ScopePassingSpanSubscriber.java:96).[0m
   .[31m2021-07-13T21:55:18.53+0800 [APP/PROC/WEB/1] ERR 	at reactor.core.publisher.MonoNext$NextSubscriber.onNext(MonoNext.java:76).[0m
   .[31m2021-07-13T21:55:18.53+0800 [APP/PROC/WEB/1] ERR 	at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onNext(ScopePassingSpanSubscriber.java:96).[0m
   .[31m2021-07-13T21:55:18.53+0800 [APP/PROC/WEB/1] ERR 	at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onNext(ScopePassingSpanSubscriber.java:96).[0m
   .[31m2021-07-13T21:55:18.53+0800 [APP/PROC/WEB/1] ERR 	at reactor.core.publisher.FluxDematerialize$DematerializeSubscriber.onNext(FluxDematerialize.java:91).[0m
   .[31m2021-07-13T21:55:18.53+0800 [APP/PROC/WEB/1] ERR 	at reactor.core.publisher.FluxDematerialize$DematerializeSubscriber.onNext(FluxDematerialize.java:38).[0m
   .[31m2021-07-13T21:55:18.53+0800 [APP/PROC/WEB/1] ERR 	at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onNext(ScopePassingSpanSubscriber.java:96).[0m
   .[31m2021-07-13T21:55:18.53+0800 [APP/PROC/WEB/1] ERR 	at reactor.core.publisher.FluxFlattenIterable$FlattenIterableSubscriber.drainAsync(FluxFlattenIterable.java:405).[0m
   .[31m2021-07-13T21:55:18.53+0800 [APP/PROC/WEB/1] ERR 	at reactor.core.publisher.FluxFlattenIterable$FlattenIterableSubscriber.drain(FluxFlattenIterable.java:649).[0m
   .[31m2021-07-13T21:55:18.53+0800 [APP/PROC/WEB/1] ERR 	at reactor.core.publisher.FluxFlattenIterable$FlattenIterableSubscriber.onNext(FluxFlattenIterable.java:249).[0m
   .[31m2021-07-13T21:55:18.53+0800 [APP/PROC/WEB/1] ERR 	at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onNext(ScopePassingSpanSubscriber.java:96).[0m
   .[31m2021-07-13T21:55:18.53+0800 [APP/PROC/WEB/1] ERR 	at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:67).[0m
   .[31m2021-07-13T21:55:18.53+0800 [APP/PROC/WEB/1] ERR 	at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onNext(ScopePassingSpanSubscriber.java:96).[0m
   .[31m2021-07-13T21:55:18.53+0800 [APP/PROC/WEB/1] ERR 	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1637).[0m
   .[31m2021-07-13T21:55:18.53+0800 [APP/PROC/WEB/1] ERR 	at reactor.core.publisher.MonoFlatMap$FlatMapInner.onNext(MonoFlatMap.java:241).[0m
   .[31m2021-07-13T21:55:18.53+0800 [APP/PROC/WEB/1] ERR 	at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onNext(ScopePassingSpanSubscriber.java:96).[0m
   .[31m2021-07-13T21:55:18.53+0800 [APP/PROC/WEB/1] ERR 	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1637).[0m
   .[31m2021-07-13T21:55:18.53+0800 [APP/PROC/WEB/1] ERR 	at reactor.core.publisher.MonoIgnoreThen$ThenAcceptInner.onNext(MonoIgnoreThen.java:296).[0m
   .[31m2021-07-13T21:55:18.53+0800 [APP/PROC/WEB/1] ERR 	at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2199).[0m
   .[31m2021-07-13T21:55:18.53+0800 [APP/PROC/WEB/1] ERR 	at reactor.core.publisher.MonoIgnoreThen$ThenAcceptInner.onSubscribe(MonoIgnoreThen.java:285).[0m
   .[31m2021-07-13T21:55:18.53+0800 [APP/PROC/WEB/1] ERR 	at reactor.core.publisher.MonoJust.subscribe(MonoJust.java:54).[0m
   .[31m2021-07-13T21:55:18.53+0800 [APP/PROC/WEB/1] ERR 	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:55).[0m
   .[31m2021-07-13T21:55:18.53+0800 [APP/PROC/WEB/1] ERR 	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.drain(MonoIgnoreThen.java:153).[0m
   .[31m2021-07-13T21:55:18.53+0800 [APP/PROC/WEB/1] ERR 	at reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:56).[0m
   .[31m2021-07-13T21:55:18.53+0800 [APP/PROC/WEB/1] ERR 	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:55).[0m
   .[31m2021-07-13T21:55:18.53+0800 [APP/PROC/WEB/1] ERR 	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:150).[0m
   .[31m2021-07-13T21:55:18.53+0800 [APP/PROC/WEB/1] ERR 	at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onNext(ScopePassingSpanSubscriber.java:96).[0m
   .[31m2021-07-13T21:55:18.53+0800 [APP/PROC/WEB/1] ERR 	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1637).[0m
   .[31m2021-07-13T21:55:18.53+0800 [APP/PROC/WEB/1] ERR 	at reactor.core.publisher.MonoCollectList$MonoCollectListSubscriber.onComplete(MonoCollectList.java:121).[0m
   .[31m2021-07-13T21:55:18.53+0800 [APP/PROC/WEB/1] ERR 	at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onComplete(ScopePassingSpanSubscriber.java:112).[0m
   .[31m2021-07-13T21:55:18.53+0800 [APP/PROC/WEB/1] ERR 	at reactor.core.publisher.DrainUtils.postCompleteDrain(DrainUtils.java:131).[0m
   .[31m2021-07-13T21:55:18.53+0800 [APP/PROC/WEB/1] ERR 	at reactor.core.publisher.DrainUtils.postComplete(DrainUtils.java:186).[0m
   .[31m2021-07-13T21:55:18.53+0800 [APP/PROC/WEB/1] ERR 	at reactor.core.publisher.FluxMaterialize$MaterializeSubscriber.onComplete(FluxMaterialize.java:134).[0m
   .[31m2021-07-13T21:55:18.53+0800 [APP/PROC/WEB/1] ERR 	at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onComplete(ScopePassingSpanSubscriber.java:112).[0m
   .[31m2021-07-13T21:55:18.53+0800 [APP/PROC/WEB/1] ERR 	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1638).[0m
   .[31m2021-07-13T21:55:18.53+0800 [APP/PROC/WEB/1] ERR 	at reactor.core.publisher.MonoCollectList$MonoCollectListSubscriber.onComplete(MonoCollectList.java:121).[0m
   .[31m2021-07-13T21:55:18.53+0800 [APP/PROC/WEB/1] ERR 	at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onComplete(ScopePassingSpanSubscriber.java:112).[0m
   .[31m2021-07-13T21:55:18.53+0800 [APP/PROC/WEB/1] ERR 	at reactor.core.publisher.FluxFirstNonEmptyEmitting$FirstNonEmptyEmittingSubscriber.onComplete(FluxFirstNonEmptyEmitting.java:333).[0m
   .[31m2021-07-13T21:55:18.53+0800 [APP/PROC/WEB/1] ERR 	at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onComplete(ScopePassingSpanSubscriber.java:112).[0m
   .[31m2021-07-13T21:55:18.53+0800 [APP/PROC/WEB/1] ERR 	at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:136).[0m
   .[31m2021-07-13T21:55:18.53+0800 [APP/PROC/WEB/1] ERR 	at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onComplete(ScopePassingSpanSubscriber.java:112).[0m
   .[31m2021-07-13T21:55:18.53+0800 [APP/PROC/WEB/1] ERR 	at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onComplete(ScopePassingSpanSubscriber.java:112).[0m
   .[31m2021-07-13T21:55:18.53+0800 [APP/PROC/WEB/1] ERR 	at reactor.core.publisher.FluxIterable$IterableSubscription.fastPath(FluxIterable.java:333).[0m
   .[31m2021-07-13T21:55:18.53+0800 [APP/PROC/WEB/1] ERR 	at reactor.core.publisher.FluxIterable$IterableSubscription.request(FluxIterable.java:198).[0m
   .[31m2021-07-13T21:55:18.53+0800 [APP/PROC/WEB/1] ERR 	at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.request(ScopePassingSpanSubscriber.java:79).[0m
   .[31m2021-07-13T21:55:18.53+0800 [APP/PROC/WEB/1] ERR 	at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.request(ScopePassingSpanSubscriber.java:79).[0m
   .[31m2021-07-13T21:55:18.53+0800 [APP/PROC/WEB/1] ERR 	at reactor.core.publisher.FluxMap$MapSubscriber.request(FluxMap.java:155).[0m
   .[31m2021-07-13T21:55:18.53+0800 [APP/PROC/WEB/1] ERR 	at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.request(ScopePassingSpanSubscriber.java:79).[0m
   .[31m2021-07-13T21:55:18.53+0800 [APP/PROC/WEB/1] ERR 	at reactor.core.publisher.Operators$DeferredSubscription.set(Operators.java:1533).[0m
   .[31m2021-07-13T21:55:18.53+0800 [APP/PROC/WEB/1] ERR 	at reactor.core.publisher.FluxFirstNonEmptyEmitting$FirstNonEmptyEmittingSubscriber.onSubscribe(FluxFirstNonEmptyEmitting.java:300).[0m
   .[31m2021-07-13T21:55:18.53+0800 [APP/PROC/WEB/1] ERR 	at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onSubscribe(ScopePassingSpanSubscriber.java:71).[0m
   .[31m2021-07-13T21:55:18.53+0800 [APP/PROC/WEB/1] ERR 	at reactor.core.publisher.FluxMap$MapSubscriber.onSubscribe(FluxMap.java:86).[0m
   .[31m2021-07-13T21:55:18.53+0800 [APP/PROC/WEB/1] ERR 	at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onSubscribe(ScopePassingSpanSubscriber.java:71).[0m
   .[31m2021-07-13T21:55:18.53+0800 [APP/PROC/WEB/1] ERR 	at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onSubscribe(ScopePassingSpanSubscriber.java:71).[0m
   .[31m2021-07-13T21:55:18.53+0800 [APP/PROC/WEB/1] ERR 	at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:139).[0m
   .[31m2021-07-13T21:55:18.53+0800 [APP/PROC/WEB/1] ERR 	at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:63).[0m
   .[31m2021-07-13T21:55:18.53+0800 [APP/PROC/WEB/1] ERR 	at reactor.core.publisher.InternalFluxOperator.subscribe(InternalFluxOperator.java:53).[0m
   .[31m2021-07-13T21:55:18.53+0800 [APP/PROC/WEB/1] ERR 	at reactor.core.publisher.FluxDefer.subscribe(FluxDefer.java:54).[0m
   .[31m2021-07-13T21:55:18.53+0800 [APP/PROC/WEB/1] ERR 	at reactor.core.publisher.Flux.subscribe(Flux.java:8174).[0m
   .[31m2021-07-13T21:55:18.53+0800 [APP/PROC/WEB/1] ERR 	at reactor.core.publisher.FluxFirstNonEmptyEmitting$RaceCoordinator.subscribe(FluxFirstNonEmptyEmitting.java:204).[0m
   .[31m2021-07-13T21:55:18.53+0800 [APP/PROC/WEB/1] ERR 	at reactor.core.publisher.FluxFirstNonEmptyEmitting.subscribe(FluxFirstNonEmptyEmitting.java:132).[0m
   .[31m2021-07-13T21:55:18.53+0800 [APP/PROC/WEB/1] ERR 	at reactor.core.publisher.Mono.subscribe(Mono.java:4105).[0m
   .[31m2021-07-13T21:55:18.53+0800 [APP/PROC/WEB/1] ERR 	at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onComplete(FluxSwitchIfEmpty.java:75).[0m
   .[31m2021-07-13T21:55:18.53+0800 [APP/PROC/WEB/1] ERR 	at reactor.core.publisher.Operators.complete(Operators.java:132).[0m
   .[31m2021-07-13T21:55:18.53+0800 [APP/PROC/WEB/1] ERR 	at reactor.core.publisher.MonoEmpty.subscribe(MonoEmpty.java:45).[0m
   .[31m2021-07-13T21:55:18.53+0800 [APP/PROC/WEB/1] ERR 	at reactor.core.publisher.InternalFluxOperator.subscribe(InternalFluxOperator.java:53).[0m
   .[31m2021-07-13T21:55:18.53+0800 [APP/PROC/WEB/1] ERR 	at reactor.core.publisher.FluxDefer.subscribe(FluxDefer.java:54).[0m
   .[31m2021-07-13T21:55:18.53+0800 [APP/PROC/WEB/1] ERR 	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:55).[0m
   .[31m20

## Steps to Reproduce

 private final ReactiveCircuitBreakerFactory cbFactory;
    private final SelfInvokingWebClient selfInvokingWebClient;

make a call to the external api ..

cbFactory.create(SELF_INVOKING_API).run(selfInvokingWebClient
                        .getWebClient()
                        .post()
                        .uri("/api/enrich-designation")
                        .body(Mono.just(tradeDetailDtoList), TradeDetailDto.class)
                        .retrieve()
                        .onStatus(HttpStatus::is5xxServerError,
                                response -> Mono.error(new ServiceException("Server error", response.rawStatusCode())))
                        .bodyToMono(Void.class)
                        .retryWhen(Retry.anyOf(RuntimeException.class)
                                .backoff(Backoff.exponential(Duration.ofSeconds(1), Duration.ofSeconds(30), 2, true))
                                .jitter(Jitter.RANDOM_JITTER)
                                .retryMax(3))
                        .onErrorReturn(null)
                , throwable -> {
                    log.error("Error in DesignationEnricherApi call", throwable);
                    return Mono.empty();
                });

call this in a parallel flux

## Your Environment

* Reactor version(s) used: 3.3.2
* Other relevant libraries versions 4.1.46
* JVM version (`java -version`): 1.8

**Comment by violetagg** [comment]
@p4pramod Please update the Spring Framework and Reactor Netty to the latest available releases.
Reactor Core 3.3.2 is more than year old (https://github.com/reactor/reactor/releases/tag/Dysprosium-SR3) and we have fixes in both Spring Framework and Reactor Netty

**Comment by p4pramod** [comment]
It has been updated to : 

   Spring Framework version is : 2.2.4 

   <dependency>
        <groupId>io.projectreactor.netty</groupId>
        <artifactId>reactor-netty</artifactId>
        <version>0.9.21.RELEASE</version>
      </dependency>

      <dependency>
        <groupId>io.projectreactor</groupId>
        <artifactId>reactor-core</artifactId>
        <version>3.3.18.RELEASE</version>
      </dependency>

Is this  combination ok..?

**Comment by p4pramod** [comment]
Again this error.
   .[31m2021-07-14T09:36:51.75+0800 [APP/PROC/WEB/0] ERR Exception in thread "hystrix-selfInvokingApigroup-20" Exception in thread "hystrix-selfInvokingApigroup-10" java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread..[0m
   .[31m2021-07-14T09:36:51.75+0800 [APP/PROC/WEB/0] ERR 	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:59).[0m
   .[31m2021-07-14T09:36:51.75+0800 [APP/PROC/WEB/0] ERR 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511).[0m
   .[31m2021-07-14T09:36:51.75+0800 [APP/PROC/WEB/0] ERR 	at java.util.concurrent.FutureTask.run(FutureTask.java:266).[0m
   .[31m2021-07-14T09:36:51.75+0800 [APP/PROC/WEB/0] ERR 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149).[0m
   .[31m2021-07-14T09:36:51.75+0800 [APP/PROC/WEB/0] ERR 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624).[0m
   .[31m2021-07-14T09:36:51.75+0800 [APP/PROC/WEB/0] ERR 	at java.lang.Thread.run(Thread.java:748).[0m
   .[31m2021-07-14T09:36:51.75+0800 [APP/PROC/WEB/0] ERR Caused by: java.lang.OutOfMemoryError: Direct buffer memory.[0m


This works well in none cloud environment. When the code is executed with Eureka then problem arises.

**Comment by violetagg** [comment]
> It has been updated to :
> 
> Spring Framework version is : 2.2.4

You can see 
Spring Framework versions here: https://github.com/spring-projects/spring-framework/releases
there is no version 2.2.4

Spring Boot version here: https://github.com/spring-projects/spring-boot/releases


> This works well in none cloud environment. When the code is executed with Eureka then problem arises.

Is this deployed with a buildpack? If yes is it possible that the memory calculator gave you less memory?

**Comment by violetagg** [comment]
@p4pramod Were you able to check the memory calculator settings?

**Comment by violetagg** [comment]
@p4pramod I'm closing this, we can reopen it if it's needed.
