### ISSUE TITLE
java.lang.ClassCastException: class reactor.netty.http.client.FailedHttpClientRequest cannot be cast to class reactor.netty.channel.ChannelOperations

### ISSUE THREAD

**Issue by htim** [reactor/reactor-netty#1738]
We started using tracing and chose reactor-netty-brave, but encountered an error from the title.
Seems that `reactor.netty.http.client.HttpClientRequest` doesn't inherit `reactor.netty.channel.ChannelOperations`, but there is a cast. 
The line where exception is thrown - https://github.com/reactor/reactor-netty/blob/13d65cd373937bb69e86bde46d98e02442cccb31/reactor-netty-http-brave/src/main/java/reactor/netty/http/brave/TracingHttpClientDecorator.java#L258

## Expected Behavior

Channel is cleaned up properly
## Actual Behavior

java.lang.ClassCastException: class reactor.netty.http.client.FailedHttpClientRequest cannot be cast to class reactor.netty.channel.ChannelOperations
## Your Environment

* Reactor version(s) used: reactor-netty 1.0.8, reactor-core 3.4.7

**Comment by violetagg** [comment]
@htim Would you like to provide a PR?

**Comment by htim** [comment]
> @htim Would you like to provide a PR?

Unfortunately I'm not familiar with this code and not sure how to do that properly

**Comment by violetagg** [comment]
@htim #1739 should fix this `ClassCastException`
