### ISSUE TITLE
Response time becomes very slow after a while 

### ISSUE THREAD

**Issue by rey5137** [reactor/reactor-netty#1754]
I encountered this issue when using Spring cloud Hoxton.SR10. To test it, I try to use netty only and strip down all Spring codes.

My test repo is [here](https://github.com/rey5137/test_spring_cloud_gateway/tree/netty_only) in branch **netty_only**

I tested with both latest version (1.0.9) and the version in Spring cloud Hoxton.SR10 (0.9.17.RELEASE) and the results are same

Here is my code:
```
class TestApplication {

    @Throws(Exception::class)
    fun run() {
        val bossGroup: EventLoopGroup = NioEventLoopGroup()
        val workerGroup: EventLoopGroup = NioEventLoopGroup()
        try {
            val httpBootstrap = ServerBootstrap()
            httpBootstrap.group(bossGroup, workerGroup)
                .channel(NioServerSocketChannel::class.java)
                .childHandler(ServerInitializer())
                .option(ChannelOption.SO_BACKLOG, 128)
                .childOption(ChannelOption.SO_KEEPALIVE, true)
            val httpChannel: ChannelFuture = httpBootstrap.bind(8081).sync()
            httpChannel.channel().closeFuture().sync()
        } finally {
            workerGroup.shutdownGracefully()
            bossGroup.shutdownGracefully()
        }
    }
}

class ServerInitializer : ChannelInitializer<Channel>() {
    override fun initChannel(ch: Channel) {
        val pipeline: ChannelPipeline = ch.pipeline()
        pipeline.addLast(HttpServerCodec())
        pipeline.addLast(HttpObjectAggregator(Int.MAX_VALUE))
        pipeline.addLast(ServerHandler())
    }
}

class ServerHandler : SimpleChannelInboundHandler<FullHttpRequest?>() {
    override fun channelRead0(ctx: ChannelHandlerContext, msg: FullHttpRequest?) {
        val content = Unpooled.copiedBuffer("Hello World!", CharsetUtil.UTF_8)
        val response: FullHttpResponse = DefaultFullHttpResponse(HttpVersion.HTTP_1_1, HttpResponseStatus.OK, content)
        response.headers()[HttpHeaderNames.CONTENT_TYPE] = "text/html"
        response.headers()[HttpHeaderNames.CONTENT_LENGTH] = content.readableBytes()
        ctx.write(response)
        ctx.flush()
    }
}

fun main(args: Array<String>) {
    TestApplication().run()
}
```
I used Jmeter to run 30 threads in 2 mins. Here is the response time chart:
<img width="1040" alt="Screen Shot 2021-07-26 at 15 03 24" src="https://user-images.githubusercontent.com/4095408/126955771-71e2da38-8982-4236-9910-68c47731123d.png">
You can see after a while the response time became very slow. I tested many time and result is always consistent

**Comment by violetagg** [comment]
@rey5137
The example above with **netty_only** can be translated to the one below **reactor_netty_only**
Can you execute your performance test and tell us the results?
Also it is a bit unclear: Do you see the issue with **Spring Cloud Gateway** but not with **netty_only** or you see the issue with both?

```
fun main(args: Array<String>) {
    val nThreads = Math.max(1, SystemPropertyUtil.getInt(
            "io.netty.eventLoopThreads", NettyRuntime.availableProcessors() * 2))
    val loop = LoopResources.create("test", nThreads, nThreads, true)
    try {
        val disposableServer = HttpServer.create()
                .port(8081)
                .tcpConfiguration {
                    it.selectorOption(ChannelOption.SO_BACKLOG, 128)
                            .option(ChannelOption.SO_KEEPALIVE, true)
                            // Specifies: bossGroup, workerGroup, NIO transport
                            .runOn(loop, false)
                }
                .handle { req, res ->
                    req.receive()
                            // Aggregates the incoming data
                            .aggregate()
                            .then(res.header(HttpHeaderNames.CONTENT_TYPE, "text/html")
                                    .header(HttpHeaderNames.CONTENT_LENGTH, "12")
                                    // Sending Mono will send FullHttpResponse
                                    .send(Mono.just(Unpooled.copiedBuffer("Hello World!", CharsetUtil.UTF_8)))
                                    .then())
                }
                .bindNow();

        disposableServer.onDispose().block();
    } finally {
        loop.disposeLater().block()
    }
}
```

**Comment by rey5137** [comment]
The issue happened with both Spring Cloud Gateway (in **master** branch) & Netty only (in **netty_only** branch). I also have tested with your code (in **reactor_netty_branch**) and the result still same as before
<img width="1038" alt="Screen Shot 2021-07-27 at 09 15 14" src="https://user-images.githubusercontent.com/4095408/127084582-5254b81c-1312-4f2f-990e-d5b99babedee.png">

Btw, here is the issue I raised on spring cloud gateway repo: [2302](https://github.com/spring-cloud/spring-cloud-gateway/issues/2302). And I tested on JVM 8, MacOs Catalina, MacBook Pro (2019)

**Comment by violetagg** [comment]
@rey5137 Can you provide the JMeter script that you use?

**Comment by rey5137** [comment]
I have added JMeter script to the [test](https://github.com/rey5137/test_spring_cloud_gateway/tree/reactor_netty_only) repo. The file name is test.jmx. And I currently using Jmeter 5.0 to run it.

**Comment by violetagg** [comment]
@rey5137 Can you try with a newer version for **Kotlin**: instead of **1.4.0** -> **1.5.21**?

**Comment by rey5137** [comment]
I already tried with newer Kotlin version and result was still same. But now, I'm suspecting the problem lie in Jmeter itself. I switched to Gatling and didn't encounter this issue anymore

**Comment by violetagg** [comment]
@rey5137 Are we OK to close this one?

**Comment by violetagg** [comment]
@rey5137 I'm closing this. If we need something in Reactor Netty we can reopen it.
