### ISSUE TITLE
Connection reset by peer exception

### ISSUE THREAD

**Issue by RitikaDangal** [reactor/reactor-netty#1774]
We have a micro service based spring boot architecture where we are using spring webclient (which internally uses reactor netty) for internal communication between services.
The issue that we faced on production was, we were getting random "connection reset by peer" exception in our services. No logs for the same request could be found in the called service.
This is how we were initialising our webclient earlier:

**webClient = WebClient.builder().build();**

To fix the same, we diabled connection pooling and initialised our webclient as below, post that the same exception was fixed.

**webClient = WebClient.builder().clientConnector(new ReactorClientHttpConnector(HttpClient.newConnection())).build();**

But how can we fix the same with connection pooling enabled as disabling connection pooling comes with its own disadvantages? 

**Reactor Netty version: 1.0.9**
**Spring boot version: 2.5.3**

**Exception:**

2021-08-16 12:20:24,095 WARN  [reactor-http-epoll-1] reactor.util.Loggers$Slf4JLogger: [id:04a24430-45, L:/10.0.8.88:33848 - R:172.20.0.20/172.20.0.20:3148] **The connection observed an error, the request cannot be retried as the headers/body were sent**
io.netty.channel.unix.Errors$NativeIoException: readAddress(..) failed: **Connection reset by peer**
2021-08-16 12:20:24,100 ERROR [reactor-http-epoll-1] reactor.util.Loggers$Slf4JLogger: Operator called default onErrorDropped
reactor.core.Exceptions$ErrorCallbackNotImplemented: org.springframework.web.reactive.function.client.WebClientRequestException: readAddress(..) failed: Connection reset by peer; nested exception is io.netty.channel.unix.Errors$NativeIoException: readAddress(..) failed: Connection reset by peer
Caused by: org.springframework.web.reactive.function.client.WebClientRequestException: readAddress(..) failed: Connection reset by peer; nested exception is io.netty.channel.unix.Errors$NativeIoException: readAddress(..) failed: Connection reset by peer
	at org.springframework.web.reactive.function.client.ExchangeFunctions$DefaultExchangeFunction.lambda$wrapException$9(ExchangeFunctions.java:141)
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	|_ checkpoint ⇢ Request to GET http://172.20.0.20:3148/v1/users/referral/ec148ff3-5dd9-473f-a7f0-cb180a5e21f0 [DefaultWebClient]
Stack trace:
		at org.springframework.web.reactive.function.client.ExchangeFunctions$DefaultExchangeFunction.lambda$wrapException$9(ExchangeFunctions.java:141)
		at reactor.core.publisher.MonoErrorSupplied.subscribe(MonoErrorSupplied.java:55)
		at reactor.core.publisher.Mono.subscribe(Mono.java:4338)
		at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:103)
		at reactor.core.publisher.FluxPeek$PeekSubscriber.onError(FluxPeek.java:222)
		at reactor.core.publisher.FluxPeek$PeekSubscriber.onError(FluxPeek.java:222)
		at reactor.core.publisher.FluxPeek$PeekSubscriber.onError(FluxPeek.java:222)
		at reactor.core.publisher.MonoNext$NextSubscriber.onError(MonoNext.java:93)
		at reactor.core.publisher.MonoFlatMapMany$FlatMapManyMain.onError(MonoFlatMapMany.java:204)
		at reactor.core.publisher.SerializedSubscriber.onError(SerializedSubscriber.java:124)
		at reactor.core.publisher.FluxRetryWhen$RetryWhenMainSubscriber.whenError(FluxRetryWhen.java:225)
		at reactor.core.publisher.FluxRetryWhen$RetryWhenOtherSubscriber.onError(FluxRetryWhen.java:274)
		at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.drain(FluxConcatMap.java:414)
		at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.onNext(FluxConcatMap.java:251)
		at reactor.core.publisher.EmitterProcessor.drain(EmitterProcessor.java:491)
		at reactor.core.publisher.EmitterProcessor.tryEmitNext(EmitterProcessor.java:299)
		at reactor.core.publisher.SinkManySerialized.tryEmitNext(SinkManySerialized.java:100)
		at reactor.core.publisher.InternalManySink.emitNext(InternalManySink.java:27)
		at reactor.core.publisher.FluxRetryWhen$RetryWhenMainSubscriber.onError(FluxRetryWhen.java:190)
		at reactor.core.publisher.MonoCreate$DefaultMonoSink.error(MonoCreate.java:189)
		at reactor.netty.http.client.HttpClientConnect$HttpObserver.onUncaughtException(HttpClientConnect.java:384)
		at reactor.netty.ReactorNetty$CompositeConnectionObserver.onUncaughtException(ReactorNetty.java:647)
		at reactor.netty.resources.DefaultPooledConnectionProvider$DisposableAcquire.onUncaughtException(DefaultPooledConnectionProvider.java:219)
		at reactor.netty.resources.DefaultPooledConnectionProvider$PooledConnection.onUncaughtException(DefaultPooledConnectionProvider.java:467

**Comment by violetagg** [comment]
@RitikaDangal  Please capture the traffic with Wireshark and share it. Is it possible that some network component (e.g. firewall etc.) closes the connection because of inactivity? If you configure `maxIdleTime` for the connection pool, do you see the issue? (https://projectreactor.io/docs/netty/release/reference/index.html#connection-pool-timeout)

**Comment by RitikaDangal** [comment]
@violetagg  I have tried capturing the traffic using Wireshark but did not see anything there. All was at network layer. 
Will configure maxIdleTime and monitor for a day or two.
Thanks

**Comment by violetagg** [comment]
@RitikaDangal Were you able to verify the `maxIdleTime` configuration?

**Comment by RitikaDangal** [comment]
@violetagg Will get back to you with an update by the end of this week.

**Comment by RitikaDangal** [comment]
@violetagg We used the following connection provider and the issue is now resolved.

		ConnectionProvider provider = ConnectionProvider.builder("fixed")
				.maxConnections(500)
				.maxIdleTime(Duration.ofSeconds(20))
				.maxLifeTime(Duration.ofSeconds(60))
				.pendingAcquireTimeout(Duration.ofSeconds(60))
				.evictInBackground(Duration.ofSeconds(120)).build();

		this.webClient = WebClient.builder()
				.clientConnector(new ReactorClientHttpConnector(HttpClient.create(provider)))
				.build();
Thanks

**Comment by TDtianzhenjiu** [comment]
Hello @violetagg 
after configuring the `maxIdelTime` it is work.
But why?

As I understood, this error means receiving an RST packet from the peer
And that parameter only indicates how long the connection should stay idle in the connection pool. 
if the connection has been removed from the pool, the connection will be closed?
attempting to read/write data on a channel that is closed will cause this error. is that right?

**Comment by violetagg** [comment]
@TDtianzhenjiu Take a look here https://projectreactor.io/docs/netty/release/reference/index.html#faq.connection-closed it is similar to what you are asking.

**Comment by TDtianzhenjiu** [comment]
Thanks @violetagg  🙏
in this case, however,
We can also retry on  `WebClientRequestException`, it also can resolve this issue. am I right?

**Comment by violetagg** [comment]
> Thanks @violetagg 🙏
> in this case, however,
> We can also retry on `WebClientRequestException`, it also can resolve this issue. am I right?

@TDtianzhenjiu you have to be careful with requests retry (for example if they are not idempotent https://www.rfc-editor.org/rfc/rfc9110.html#section-9.2.2)

**Comment by dalvan-bevilaqua** [comment]
> @violetagg We used the following connection provider and the issue is now resolved.
> 
> ```
> 	ConnectionProvider provider = ConnectionProvider.builder("fixed")
> 			.maxConnections(500)
> 			.maxIdleTime(Duration.ofSeconds(20))
> 			.maxLifeTime(Duration.ofSeconds(60))
> 			.pendingAcquireTimeout(Duration.ofSeconds(60))
> 			.evictInBackground(Duration.ofSeconds(120)).build();
> 
> 	this.webClient = WebClient.builder()
> 			.clientConnector(new ReactorClientHttpConnector(HttpClient.create(provider)))
> 			.build();
> ```
> 
> Thanks

solved to me

**Comment by jzpeepz** [comment]
> @violetagg We used the following connection provider and the issue is now resolved.
> 
> ```
> 	ConnectionProvider provider = ConnectionProvider.builder("fixed")
> 			.maxConnections(500)
> 			.maxIdleTime(Duration.ofSeconds(20))
> 			.maxLifeTime(Duration.ofSeconds(60))
> 			.pendingAcquireTimeout(Duration.ofSeconds(60))
> 			.evictInBackground(Duration.ofSeconds(120)).build();
> 
> 	this.webClient = WebClient.builder()
> 			.clientConnector(new ReactorClientHttpConnector(HttpClient.create(provider)))
> 			.build();
> ```
> 
> Thanks

This worked for me, BUT my request now seem to take a LOT longer. up to 20+ seconds from <= 5 seconds before. Anyone else experience this?

**Comment by YevhenPalamarchuk** [comment]
> Hi @RitikaDangal , @violetagg ,
> 
> We were also facing a very similar issue with communication between springboot based microservices deployed in kubernetes. **Reactor Netty version: 1.0.10 Spring boot version: 2.5.4**
> ....
> We tried setting the maxIdleTime with env varibales through **reactor.netty.pool.maxIdleTime: 600000**. It ddint seem to be updating the maxIdleTime though. we use spring-boot-starter-webflux.
> ...

The issue with the non-functional environment parameter occurs because the [System.getProperty()](https://docs.oracle.com/javase/tutorial/essential/environment/sysprop.html) method is used in the following code:
https://github.com/reactor/reactor-netty/blob/c33825e6d8cb9408642f089e1c61f4d6e086563a/reactor-netty-core/src/main/java/reactor/netty/resources/ConnectionProvider.java#L70-L72

This method reads system properties, not environment variables.

You can add the system property to the VM using the following command:
`java -Dreactor.netty.pool.maxIdleTime=30000 -jar /app/your-application.jar`

**Comment by mehedihasan03** [comment]
This is how I solved my problem.
```
@Bean
public HttpClient httpClientWithTimeout() {
    // Create the connection provider with desired settings
    ConnectionProvider provider = ConnectionProvider.builder("fixed")
            .maxConnections(500)                           // Max number of connections in the pool
            .maxIdleTime(Duration.ofSeconds(20))           // Time after which idle connections are closed
            .maxLifeTime(Duration.ofSeconds(60))           // Max lifetime for a connection in the pool
            .pendingAcquireTimeout(Duration.ofSeconds(60)) // Max wait time to acquire a connection from the pool
            .evictInBackground(Duration.ofSeconds(120))    // Frequency of eviction of idle connections
            .build();

    // Create HttpClient with connection provider and timeouts
    return HttpClient.create(provider)
            .option(ChannelOption.CONNECT_TIMEOUT_MILLIS, 60000)
            .responseTimeout(Duration.ofMillis(TIMEOUT))
            .doOnConnected(connection -> {
                connection.addHandlerLast(new ReadTimeoutHandler(60000, TimeUnit.MILLISECONDS));
                connection.addHandlerLast(new WriteTimeoutHandler(60000, TimeUnit.MILLISECONDS));
            })
            // Enable detailed logging
            .wiretap("reactor.netty.http.client.HttpClient", LogLevel.DEBUG, AdvancedByteBufFormat.TEXTUAL);
}
```

**Comment by Raj002** [comment]
@RitikaDangal , @violetagg 
I'm using Spring Boot 3.0.5 with WebClient and encountering intermittent **_Connection reset by peer_** errors, particularly when requests are made after a period of inactivity (the idle duration varies and is not consistent). I’ve reviewed and tried the suggested solutions mentioned above, including setting _**reactor.netty.pool.maxIdleTime**_, but the issue still persists. I'm seeking guidance on how to ensure that idle connections are properly managed or refreshed to prevent these errors.

**Exception:**

{"timestamp":"2025-04-22T09:03:58.879Z","level":"WARN","logger":"r.n.http.client.HttpClientConnect","message":"The connection observed an error, the request cannot be retried as the headers/body were sent","thread":"reactor-http-epoll-2","dd.trace_id":"","dd.span_id":"","stack_trace":"i.n.c.unix.Errors$NativeIoException: recvAddress(..) failed: Connection reset by peer\n"}
{"timestamp":"2025-04-22T09:03:58.885Z","level":"ERROR","logger":"o.s.w.s.a.HttpWebHandlerAdapter","message":"[66f449f3] 500 Server Error for HTTP GET \"/login/oauth2/code/okta?code=kjnksdf87689KJBNKJ68dsnksd&state=js683KJBsdfbsj3jnkbi4rjk78HJ3D\"","thread":"reactor-http-epoll-2","dd.trace_id":"","dd.span_id":"","stack_trace":"i.n.c.unix.Errors$NativeIoException: recvAddress(..) failed: Connection reset by peer\nWrapped by: o.s.w.r.f.c.WebClientRequestException: recvAddress(..) failed: Connection reset by peer\n\tat

**Comment by violetagg** [comment]
@Raj002 You can follow the recommendations here https://projectreactor.io/docs/netty/release/reference/appendices.html#faq.connection-closed, they apply also for `Connection reset by peer`

**Comment by Raj002** [comment]
> [@Raj002](https://github.com/Raj002) You can follow the recommendations here https://projectreactor.io/docs/netty/release/reference/appendices.html#faq.connection-closed, they apply also for `Connection reset by peer`

I've tried to use the below code as well as the above provided code snippet @mehedihasan03 . But, the issue still persist.

@Bean
public WebClient customWebClient() {
    final ConnectionProvider provider = ConnectionProvider.builder("webclient-provider")
        .maxConnections(500)
        .maxIdleTime(Duration.ofSeconds(600))
        .maxLifeTime(Duration.ofSeconds(600))
        .pendingAcquireTimeout(Duration.ofSeconds(60))
        .evictInBackground(Duration.ofSeconds(120))
        .build();

    final HttpClient httpClient = HttpClient.create(provider).compress(true);

    return WebClient.builder()
        .clientConnector(new ReactorClientHttpConnector(httpClient))
        .build();
}

**Comment by violetagg** [comment]
@Raj002 Please use [Gitter](https://gitter.im/reactor/reactor-netty) or [stackoverflow.com](https://stackoverflow.com/questions/tagged/reactor-netty) for questions or open a new issue with a reproducible example. Thanks!

**Comment by SahajdeepSinghKharbanda** [comment]
Hi @violetagg @RitikaDangal,

I’m seeing intermittent "connection reset by peer" errors with a few of our third‑party integrations. Our setup is:
1. Java 17
2. Spring Boot 2.6.6
3. Reactor Netty 0.9.12.RELEASE and reactor‑netty‑http 1.0.17
4. Idle‑connection timeout on our load balancer / NGINX: 30 seconds

I tried using provided solution and added following properties only as I want to keep my connections unbounded.

```
ConnectionProvider provider = ConnectionProvider.builder("fixed")
                .maxIdleTime(Duration.ofSeconds(20))
                .evictInBackground(Duration.ofSeconds(120))
                .build();
HttpClient client = HttpClient.create(provider);
```

This stopped the "connection reset by peer" errors, but I then started getting "handshake timed out after 10000ms" errors. I also verified that the default TLS version for Java 17 is v1.3 (with fallback to v1.2). So I tried explicitly forcing TLS v1.2:

```
HttpClient client = HttpClient.create()
                .headers(headers -> headers.add(HttpHeaders.CONNECTION, "keep-alive"))
                .secure(sslContextSpec -> {
                    try {
                        sslContextSpec.sslContext(SslContextBuilder.forClient().protocols("TLSv1.2").build());
                    } catch (SSLException e) {
                        throw new RuntimeException(e);
                    }
                });
```

This fixed the “connection reset by peer” issue but still resulted in "handshake timed out after 10000ms" errors. I wanted to understand that how are TLS version settings related to the ConnectionProvider’s idle‑time settings, and why am I now seeing handshake timeouts with both approaches and how can I resolve this issue?

**Comment by violetagg** [comment]
@SahajdeepSinghKharbanda Please use [Gitter](https://gitter.im/reactor/reactor-netty) or [stackoverflow.com](https://stackoverflow.com/questions/tagged/reactor-netty) for questions or open a new issue with a reproducible example. Thanks!
