### ISSUE TITLE
Provide a util method to configure the prefix for metrics

### ISSUE THREAD

**Issue by JamesChenX** [reactor/reactor-netty#1775]
## Motivation

It's cumbersome to create a new class extending `MicrometerChannelMetricsRecorder` just for a custom prefix.

## Desired solution

```java
            Connection connection = TcpClient.create()
                    .host(server.host())
                    .port(server.port())
                    .metrics(true, "my-custom-prefix") // what we want
                    .handle((in, out) -> Mono.never())
                    .connectNow();
````

**Comment by violetagg** [comment]
@JamesChenX Would you like to provide a PR?

**Comment by JamesChenX** [comment]
@violetagg Sure.

**Comment by violetagg** [comment]
Closing this issue as the functionality can be implemented with the current API 
`.metrics(boolean, () -> ChannelMetricsRecorder)`
