### ISSUE TITLE
java.lang.OutOfMemoryError: GC overhead limit exceeded using Spring WebClient with netty HttpClient and SslContext

### ISSUE THREAD

**Issue by davide1995** [reactor/reactor-netty#1779]
## Context
I am working on a project involving the real-time operation of an application. One of the many functionalities is to invoke an endpoint every x seconds and store the return value for a possible future control.

## Technical Context
The problem with the garbage collector occurs when I secure the HttpClient via an SslContext:
`httpClient.secure(t -> t.sslContext(sslContext))`
Now you may wonder why I need that line of code. As long as the endpoint is a verified address such as https://badssl.com/, there would be no need to insert that line. However, when the url is e.g. https://expired.badssl.com/, that line is needed because otherwise an exception would be thrown e.g. `java.security.cert.CertificateExpiredException`

## Expected Behavior
Whenever the endpoint is invoked, irrespective of time, it must provide a response without any particular delay from the previous request.
Profiling (setting -Xmx24m)`noGarbageCollectorProblemOccurs()` method:
![gc2](https://user-images.githubusercontent.com/21131407/129970288-cd8e35ff-7188-4a64-999c-ec5dc042146a.png)
After 15 minutes, java heap space

## Actual Behavior
When the application is running, an error is generated on the garbage collector after a while.
Profiling (setting -Xmx24m) `garbageCollectorProblemOccurs1()` method:
![gc](https://user-images.githubusercontent.com/21131407/129967833-cefda210-f754-45c3-850a-1e9cc1de9610.png)
Same situation happens with `garbageCollectorProblemOccurs2()` method.

## Steps to Reproduce
I created a mini-project that can be easily imported into IntelliJ to demonstrate the situation.

[netty-gc-problem.zip](https://github.com/reactor/reactor-netty/files/7009601/netty-gc-problem.zip)

- Download the project
- Open the file TestMeService.java
- Play between the lines defined in the init() method and read the related comments
- Start the application

To speed up the time before a gc error occurs, I modified the maximum capacity of the heap space by setting the parameter -Xmx12m. Increasing this parameter only postpones the problem since the heap space keeps filling up and the garbage collector cannot empty it.
Once you start the application, in the console you will notice that the logs are written more and more slowly in the console before arriving at a `java.lang.OutOfMemoryError: GC overhead limit exceeded`. On my machine it comes after ~ 20 seconds and ~ 15 invocations.

## Possible Solution
Currently, the fix I have in production is a cron job that restarts the backend every 24 hours in order to free up memory not freed by the garbage collector.

## Your Environment
* Reactor version(s) used: See pom file
* Other relevant libraries versions (eg. `netty`, ...): See pom file
* JVM version (`java -version`): 1.8.0_201
* OS and version (eg. `uname -a`): Darwin Kernel Version 20.3.0

**Comment by violetagg** [comment]
@davide1995 On every request you always create a new `WebClient`, which means that you do not reuse neither `SslContext` nor the connection pool nor any other resource that otherwise will be shared when one and the same instance for `WebClient` is used. This is similar to the report here #1054

**Comment by davide1995** [comment]
@violetagg Hi. Thank you very much for your prompt reply. I will try to adapt my solution according to the issue you linked and comment this issue regarding the situation

**Comment by davide1995** [comment]
Well, I moved the creation of the `SslContext` out of the method and it works. I no longer have any memory leak problem.

Actual code:
```
public class NetworkConnection {

    SslContextBuilder sslCtxBuilder = SslContextBuilder.forClient().trustManager(InsecureTrustManagerFactory.INSTANCE);

    public WebClient buildWebClient(String url, boolean shouldTrust) {

        HttpClient httpClient = HttpClient.create();
        if (shouldTrust) {
            httpClient = httpClient.secure(t -> t.sslContext(sslCtxBuilder));
        }

        try {
            return WebClient.builder()
                    .baseUrl(url)
                    .clientConnector(new ReactorClientHttpConnector(httpClient))
                    .build();
        } catch (Exception e) {
            log.error("WebClient Error", e);
        }
        return null;
    }
}
```

What continues to irritate me is why even if I keep creating a new `WebClient` each time, it is not removed by Java's garbage collector. The fact is that you also do not provide a method such as `close()` available to call on the `WebClient`. I agree that the pattern that I used does not reflect the documentation you provide, but providing a `close()` method on the `WebClient` class would help the garbage collector to inform him that the resource is now free and ready to be freed from memory. As soon as I encountered the problem, as a developer, I immediately looked to see if the `WebClient` had a `close()` method. What do you think about implementing a `close()` method that allows you to free the resources of any `SslContext` used?

**Comment by violetagg** [comment]
@davide1995 please create a feature request for `close`. I still think that you have to share the `WebClient`, but that's up to you.
