### ISSUE TITLE
Want guidelines to implement an application layer protocol library

### ISSUE THREAD

**Issue by bromine0x23** [reactor/reactor-netty#1791]
I want to implement a reactor-netty based application layer protocol library that provides classes similar to `HttpServer` and `HttpClient`, but there are so many classes and methods involved that it's confusing me.

Are there any guidelines here for doing this job? Maybe a startup step, or some architecture notes.

Implementing the protocol handler is not difficult for me, the main question is how classes such as `TcpClient`, `TcpClientConfig`, `TcpClientConnect` collaborate with each other.

**Comment by violetagg** [comment]
@bromine0x23 Unfortunately for the time being we cannot provide you such guidelines.

> Implementing the protocol handler is not difficult for me, the main question is how classes such as TcpClient, TcpClientConfig, TcpClientConnect collaborate with each other.

Let's discuss this on [Gitter](https://gitter.im/reactor/reactor-netty).

**Comment by violetagg** [comment]
Closing this in favour of #916
