### ISSUE TITLE
reactor-netty-http dependency update io.netty 4.1.66.Final+

### ISSUE THREAD

**Issue by altfatterz** [reactor/reactor-netty#1795]
JFrog XRay reported High Security vulnerability for using 4.1.65.Final for issue already fixed in 4.1.66.Final

https://github.com/netty/netty/pull/11429

Could you upgrade to at least to io.netty 4.1.66.Final ?

**Comment by violetagg** [comment]
@altfatterz Please check https://github.com/reactor/reactor-netty/releases, the latest 1.0.10 and 0.9.22.RELEASE depend on 4.1.66.Final
