### ISSUE TITLE
HTTP client metrics - HTTP2 pool name should include underlying connection provider name

### ISSUE THREAD

**Issue by crankydillo** [reactor/reactor-netty#1800]
We leverage almost all of your micrometer-collected metrics.  We name the connection providers and this gives us a nice view of what's going on for our various clients (since you set create tag name=connProviderName).  We're just starting with HTTP2 and would like to have a view of both the underlying pool (that we named) and HTTP2 pool that sits on top of it.  However, the HTTP2 connection provider is named 'HTTP2'.  I'm actually not sure what the behavior is when you have more, but what we were thinking is it should be something like `name="http2." + underlyingConnProviderName`.

## Motivation

We need to monitor all the client pools so that we understand the behavior of the clients.

This will likely become even more important to us if you start adding metrics like 'open.streams' to an HTTP2 'connection'.

**Comment by violetagg** [comment]
@crankydillo Currently HTTP/2 pool does not expose any metrics. There is an enhancement for reporting active streams but it is still not implemented #1328. What kind of other metrics do you need from HTTP/2 that cannot be obtained from the HTTP/1.1 pool?

**Comment by crankydillo** [comment]
I just pretty much wrote the same thing for my team:)  The only value I can currently think of is that it helps to verify your implementation!  Anyhow, I'm personally fine with this being tied to #1328.  If someone on my team feels differently, we'll report back.

**Comment by violetagg** [comment]
Ok let me close this as duplicate, we can reopen it, if it is needed.

**Comment by crankydillo** [comment]
Hmm, I viewed #1328 as related, but orthogonal.  But I can drop a comment there that reflects the desire above.
