### ISSUE TITLE
HTTP/2 maxLifeTime of the connection

### ISSUE THREAD

**Issue by AmandeepSingh97** [reactor/reactor-netty#1818]
While testing with maxLifeTime settings restrictions in the connection provider, it is observed that HTTP2 connections are not recycled when the connection is actively used for serving requests.

## Expected Behavior

HTTP/2 connection should not accept new streams after the maxLifeTime has been reached.

## Actual Behavior

HTTP/2 connection is actively used if there are incoming streams and maxLifeTime is not respected.

## Steps to Reproduce

Reactor netty testcase which depicts the [behaviour](https://github.com/AmandeepSingh97/reactor-netty/blob/http2maxlifetime/reactor-netty-http/src/test/java/reactor/netty/http/client/ConnectionPoolTests.java#L433)

## Your Environment

* Reactor version(s) used: 1.0.10
* Other relevant libraries versions (eg. `netty`, ...): 4.1.66.Final
* JVM version (`java -version`): openjdk 11.0.10
* OS and version (eg. `uname -a`): 19.6.0 Darwin Kernel Version

**Comment by violetagg** [comment]
A change about this issue is available in 1.0.14-SNAPSHOT. It will be great if you are able to test it.

**Comment by AmandeepSingh97** [comment]
> A change about this issue is available in 1.0.14-SNAPSHOT. It will be great if you are able to test it.

Sure @violetagg Me and my team will test it out and get back with the results.

**Comment by dnagarajan89** [comment]
@violetagg Thanks for addressing this issue. We have validated with the test case that we have as well as the [reproducer](https://github.com/AmandeepSingh97/reactor-netty/blob/http2maxlifetime/reactor-netty-http/src/test/java/reactor/netty/http/client/ConnectionPoolTests.java#L433) that is shared in this issue earlier and we observed that the HTTP/2 connection is now respecting the maxLifeTime configuration.

**Comment by violetagg** [comment]
> @violetagg Thanks for addressing this issue. We have validated((with the latest SNAPSHOT version) with the test case that we have as well as the [reproducer](https://github.com/AmandeepSingh97/reactor-netty/blob/http2maxlifetime/reactor-netty-http/src/test/java/reactor/netty/http/client/ConnectionPoolTests.java#L433) that is shared in this issue earlier and we observed that the HTTP/2 connection is now respecting the maxLifeTime configuration.

thanks
