### ISSUE TITLE
Memory leak when Circuit Breaker is being opened in reactive WebClient

### ISSUE THREAD

**Issue by ssalamov** [reactor/reactor-netty#1825]
Dear friends, could you please help me with this issue - for any suggestion I'd be grateful.

Currently we are experiencing memory leak in our system. As you see from screenshots within ~45 minutes performance tests run almost in each instance memory (committed heap, used heaps) heats max. We simulated Circuit Breaker (later CB) to be opened with one of the downstream API. Here are the code bases how we call aforementioned rest APIs from the same host and web client instance but with the different CB instances:

```
private Mono<EcomAvailabilityResponse> loadAvailability(EcomAvailabilityRequest request) {
        return webClient
                .method(HttpMethod.POST)
                .uri(uriBuilder -> uriBuilder
                        .scheme("https").host(HOST)
                        .replacePath("/v1/availability")
                        .build())
                .bodyValue(request)
                .retrieve()
                .bodyToMono(EcomAvailabilityResponse.class)
                .transformDeferred(availabilityRequestResilience::apply)
                .transformDeferred(CircuitBreakerOperator.of(availabilityCircuitBreaker))
                .doOnError(error -> log.warn("Exception during availability query, use fallback. Exception from ecomavailability: {}", error.toString()))
                .onErrorReturn(EcomAvailabilityResponse.fallback(request.getProductIds()))
                .contextWrite(context -> context.put(PROVIDER_HOST_LABEL, AVAILABILITY_CALL_NAME));
    }

```

```
private Mono<EcomSiteRangeResponse> loadSiteRange(EcomSiteRangeRequest request) {
        return webClient
                .method(HttpMethod.POST)
                .uri(uriBuilder -> uriBuilder
                        .scheme("https").host(HOST)
                        .replacePath("/v1/range")
                        .build())
                .bodyValue(request)
                .retrieve()
                .bodyToMono(EcomSiteRangeResponse.class)
                .transformDeferred(siteRangeRequestResilience::apply)
                .transformDeferred(CircuitBreakerOperator.of(circuitBreakerSiteRange))
                .doOnError(error -> log.warn("Exception during Ecom site range query, use fallback. Exception from ecomavailability: {}", error.toString()))
                .onErrorMap(EcomAvailabilityCommunicationException::new)
                .onErrorReturn(EcomSiteRangeRequest.fallback(request.getProductIds()))
                .contextWrite(context -> context.put(PROVIDER_HOST_LABEL, SITE_RANGE_CALL_NAME));
    }

```
Surprisingly when we comment below code parts memory leak doesn't happen: 

`//.transformDeferred(CircuitBreakerOperator.of(availabilityCircuitBreaker))`
`//.transformDeferred(CircuitBreakerOperator.of(circuitBreakerSiteRange))`

Used frameworks:

spring web flux: 5.3.8
reactor-netty version: 1.0.10
io.github.resilience4j: 1.7.1

<img width="697" alt="Screenshot 2021-09-25 at 16 26 18" src="https://user-images.githubusercontent.com/39103746/134775176-94f7e173-bf1b-4066-b93e-18c4a087e753.png">

Wondering if the resilience4j CB has any problem with the reactive WebClient integration?

Regards,
Samir Salamov

**Comment by ssalamov** [comment]
> 403s

**Comment by violetagg** [comment]
@ssalamov 
> Wondering if the resilience4j CB has any problem with the reactive WebClient integration?

I cannot comment about this integration, please reach its community.

**Comment by violetagg** [comment]
@ssalamov Based on your findings in https://github.com/resilience4j/resilience4j/issues/1546 I'm gonna close this issue. If it appears to be an issue in Reactor Netty, we can reopen it.
