### ISSUE TITLE
HttpClient metrics are bound to micrometer via PooledByteBufAllocator

### ISSUE THREAD

**Issue by simondaudin** [reactor/reactor-netty#1847]
Hello :hand: 
I want to use reactor-netty given metrics and integrate them within our metrics system, without using micrometer. We chose ot to have micrometer in our depencies.

## Expected Behavior
I should be able to use reactor-netty metrics without depending on micrometer.

## Actual Behavior
The initialization failed in `ByteBufAllocatorMetrics.registerMetrics` (or UnpooledByteBufAllocator) due to dependency over micrometer `Gauge`.

## Steps to Reproduce
- Use `ConnectionProvider.metrics(true, () -> myMetricsProvider)` & `HttpClient.metrics(true, () -> myMetricsProvider)`
- Do not have micrometer dependency available
- Initialization error

## Possible Solution
Maybe being able to provide a consumer of `PooledByteBufAllocatorMetric` being not the reactor-netty one `ByteBufAllocatorMetrics`.
Or detach ByteBufAllocatorMetrics activation from `TransportConfig.metricsRecorder` https://github.com/reactor/reactor-netty/blob/ab8cb1ef5dceb6c047516efe21afbd479aade0ad/reactor-netty-core/src/main/java/reactor/netty/transport/TransportConfig.java#L377

## Your Environment
* Reactor version(s) used: 1.0.11

**Comment by egorlitvinenko** [comment]
@violetagg
Am I correct, that if there is no micrometer dependency, we do not see metrics from HttpClient metrics are bound to micrometer via PooledByteBufAllocator at all?
Is there a way to trace TransportConfig?
Could we use customize it through https://github.com/reactor/reactor-netty/blob/cab107140ece193ce703a6fbc61645ff02dc0a3d/reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServer.java#L593 ?

**Comment by violetagg** [comment]
@egorlitvinenko Yes that's correct. You can register your metrics very easily - you can take the `ByteBufAllocator` and publish where you need the metrics that it provides.

**Comment by violetagg** [comment]
you need something like this

```
HttpServer httpServer = HttpServer.create()
		.doOnBound(server -> {
			ByteBufAllocator alloc = server.channel().alloc();
			if (alloc instanceof PooledByteBufAllocator) {
				PooledByteBufAllocatorMetric metrics = ((PooledByteBufAllocator) alloc).metric();
			}
		});
```

**Comment by egorlitvinenko** [comment]
@violetagg Great, thank you, I'll try it.
