### ISSUE TITLE
RST Problem solving

### ISSUE THREAD

**Issue by 1ssqq1lxr** [reactor/reactor-netty#1849]
Hello, I use the server developed by reactor netty. During pressure measurement, when a large number of connections are connected in an instant, the server returns RST errors to a small number of clients, and the server has no exception log. How should I deal with this situation?

Connection reset by peer: /127.0.0.1:1884

Using native netty does not have this problem

**Comment by violetagg** [comment]
@@1ssqq1lxr I'm closing this one, if you are able to provide the requested information we can reopen it.

**Comment by 1ssqq1lxr** [comment]
ok， thanks



---Original---
From: "Violeta ***@***.***&gt;
Date: Mon, Nov 1, 2021 15:32 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [reactor/reactor-netty] RST Problem solving (#1849)




 
@@1ssqq1lxr I'm closing this one, if you are able to provide the requested information we can reopen it.
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
