### ISSUE TITLE
QuicOperations should extend ChannelOperations<UdpInbound, UdpOutbound>

### ISSUE THREAD

**Issue by linux-china** [reactor/reactor-netty#1858]
Now the QuicOperations is different with UdpOperations, HttpOperations,  and not `extends ChannelOperations<UdpInbound, UdpOutbound>` .  

To implement the QUIC transport for RSocket with following code:  

```java
return quicServer
                .doOnConnection(
                        c -> {
                            c.addHandlerLast(new RSocketLengthCodec(maxFrameLength));
                            acceptor.apply(new QuicDuplexConnection(c))
                                    .then(Mono.<Void>never())
                                    .subscribe(c.disposeSubscriber());
                        })
                .bind()
                .map(CloseableChannel::new);
```

receive() in QuicDuplexConnection as following: 

```
    public Flux<ByteBuf> receive() {
        return connection.inbound().receive().map(FrameLengthCodec::frame);
    }
```

`QuicOperations.inbound() ` can not receive any ByteBuf because it use reactor.netty.Connection default method as following: 

```java
      default NettyInbound inbound() {
		return ReactorNetty.unavailableInbound(this);
	}
```

**Comment by linux-china** [comment]
@violetagg  Got, and I will take a look.   rsocket-transport-quic is here  https://github.com/linux-china/rsocket-transport-quic/blob/master/src/main/java/io/rsocket/transport/quic/server/QuicServerTransport.java   Still not lucky to make it work on server side.  Maybe I did some stupid things :).   

![Snip20211016_31](https://user-images.githubusercontent.com/46711/137602104-5650b2f3-6380-44e2-9eb7-00f0f252822a.png)

**Comment by violetagg** [comment]
@linux-china Let's continue the discussion about integration in RSocket here https://github.com/rsocket/rsocket-java/issues/1019
If something is needed on Reactor Netty side we can address it.
