### ISSUE TITLE
Proxy settings via system properties not working with nonProxyHosts and wildcard

### ISSUE THREAD

**Issue by Pieter-Beckers** [reactor/reactor-netty#1861]
## Expected Behavior
Usage of below example should work.

## Actual Behavior

It gives the following exception `java.util.regex.PatternSyntaxException: Dangling meta character '*' near index 0
*.local.com|10.*`

## Steps to Reproduce

If we setup a WebClient with ReactorClientHttpConnector and httpClient with proxyWithSystemProperties, an exception is thrown if the nonProxyHosts has a wildcard.

```java
@Test
public void repoCase() {
		System.setProperty("http.proxyHost", "http://localhost");
		System.setProperty("http.proxyPort", "80");
		System.setProperty("http.nonProxyHosts", "*.local.com|10.*");
		HttpClient httpClient = HttpClient.create().proxyWithSystemProperties();
		ReactorClientHttpConnector connector = new ReactorClientHttpConnector(httpClient);
		WebClient webClient = WebClient.builder().clientConnector(connector).build();
}
```

## Your Environment

* Reactor version(s) used: 1.0.11
* Other relevant libraries versions (eg. `netty`, ...):
* JVM version (`java -version`): 11
* OS and version (eg. `uname -a`):

**Comment by SanderKleykens** [comment]
`reactor.netty.transport.ProxyProvider#createHttpProxyFrom` gets the nonProxyHosts system property and then plugs it into `reactor.netty.transport.ProxyProvider.Builder#nonProxyHosts`, which expects a regex. 
The pattern used in `http.nonProxyHosts` is not compatible with regex as @Pieter-Beckers said.

Instead, `reactor.netty.transport.ProxyProvider#createHttpProxyFrom` should use `reactor.netty.transport.ProxyProvider.RegexShouldProxyPredicate#fromWildcardedPattern` and `reactor.netty.transport.ProxyProvider.Builder#nonProxyHostsPredicate`.

I've written a fix for this in 0335fde1e. I'll open a PR for this.
