### ISSUE TITLE
Implement additional metrics from reactor-pool

### ISSUE THREAD

**Issue by epicoxymoron** [reactor/reactor-netty#1872]
[reactor-pool supports](https://github.com/reactor/reactor-pool/blob/main/src/main/java/reactor/pool/InstrumentedPool.java) metrics beyond those which reactor-netty understands: `#getMaxAllocatedSize()` and `#getMaxPendingAcquireSize()`.  It would be great if these could be made available to [reactor-netty's ConnectionPoolMetrics](https://github.com/reactor/reactor-netty/blob/main/reactor-netty-core/src/main/java/reactor/netty/resources/ConnectionPoolMetrics.java).

## Motivation
I would like to monitor connection pool saturation.  I'm absolutely open to other ways of doing this, but first instinct is to monitor the ratio of active connections to the connection pool limit; I have a gauge only for the former.  If a gauge were made available for the latter, I could monitor both and get the ratio I'm looking for.

I don't have a use case for a gauge on the max pending acquire size, so I'll leave it to the project to consider whether adding that makes sense.

## Desired solution
The ConnectionPoolMetrics interface would be extended with the new field(s), and [DelegatingConnectionPoolMetrics](https://github.com/reactor/reactor-netty/blob/main/reactor-netty-core/src/main/java/reactor/netty/resources/DelegatingConnectionPoolMetrics.java) would be updated to add the new field(s) from the delegate.

## Considered alternatives
1. Fill the "max allocated size" in as a constant in my monitoring; this is problematic because when the true value changes, the monitoring system has to be updated separately, which is obviously error-prone.

## Additional context
None.

**Comment by violetagg** [comment]
@epicoxymoron Do you configure the `ConnectionProvider` by yourself? Basically `#getMaxAllocatedSize()` is `maxConnections` configuration https://github.com/reactor/reactor-pool/blob/1fc4387fa7863c65b53b9bebc19a8f306465dd47/src/main/java/reactor/pool/AbstractPool.java#L99.
`#getMaxPendingAcquireSize()` is `pendingAcquireMaxCount` configuration https://github.com/reactor/reactor-pool/blob/1fc4387fa7863c65b53b9bebc19a8f306465dd47/src/main/java/reactor/pool/AbstractPool.java#L104

**Comment by epicoxymoron** [comment]
Yes, I do.  I understand where the values are coming from.

My problem is that I want to monitor saturation as a percentage of `(establishedConnections / maxAllowedConnections)` to get a sense of if I'm nearing any pool limits.  I can currently monitor `pendingAcquireSize` to see if my pool is _fully_ saturated, but I would only notice that once it's too late; I'd like the early warning that we're getting close to the limits.

I can go into my monitoring system and hard-code `maxAllowedConnections` to some constant, but I'd rather there be an exposed gauge for two reasons:

1. When I change the application configuration, I can easily forget to update the monitoring system, leading to inaccurate system monitoring.  In large organizations, it may be the case that those systems are managed by different people/groups, even.
2. I'm setting up monitors across multiple applications; by having `maxAllowedConnections` exposed as a metric, I can tie into it in a standardized way across all the monitors, rather than having to set it for hundreds of applications.  It's just easier for me to work with.

I can of course create my _own_ in-app gauge for this purpose and tie into it, but snooping through what reactor-pool's`InstrumentedPool.PoolMetrics` already has made me think that the reactor-netty project might be open to this enhancement.

**Comment by epicoxymoron** [comment]
I'll add one more bit: the tags for the `maxAllowedConnections` gauge should match those of the other gauges.  Reproducing those values from application code feels a little daunting, whereas you have ready access to those already.

**Comment by violetagg** [comment]
@epicoxymoron Ok I understand, adding this to `1.0.x` backlog and marking it as `help wanted`.

**Comment by violetagg** [comment]
@epicoxymoron PTAL PR #1897
