### ISSUE TITLE
program use HttpClient listen more udp port

### ISSUE THREAD

**Issue by ctlove0523** [reactor/reactor-netty#1915]
When use HttpClient do request if the host is a name,no matter name can resolveed or not the program listen max six udp port in windows system,four udp port in Linux system.

## Steps to Reproduce
~~~java
Mono.defer(() -> HttpClient.create(ConnectionProvider.newConnection())
	.host("xx")
	.port(80)
	.baseUrl("/")
	.get()
	.response())
	.repeat(Integer.MAX_VALUE)
	.blockLast();
~~~
## netstat cmd result:

Linux：
![image](https://user-images.githubusercontent.com/9432235/144527563-0e52303b-94a7-4e0a-a5a8-6629a326cbad.png)

Windows:
![image](https://user-images.githubusercontent.com/9432235/144527611-94fa94fe-d1b8-4d31-adae-1149402ab736.png)

Reactor version(s) used: 1.0.10

**Is this normal or not?**

**Comment by ctlove0523** [comment]
netty

**Comment by qqhai007** [comment]
Has this problem been solved, please,  and how?
