### ISSUE TITLE
request help: how to handle the cross request

### ISSUE THREAD

**Issue by tzssangglass** [reactor/reactor-netty#1916]
## Motivation

hi, developers, I ran into a particular problem while working on a project with reactor-netty.

![runner2](https://user-images.githubusercontent.com/30819887/144559802-9a8a922e-7866-4cc1-bf37-1b7eaa151624.png)

I would like to know if there is a way to do what is represented in the picture.

thanks.

**Comment by simonbasle** [comment]
As stated in the contributing guidelines, [StackOverflow](https://stackoverflow.com/questions/tagged/reactor-netty) is the right place to ask questions, but here I go:

There's no direct explicit support for this _using the `NettyOutbound`_. This is more of an application-level concern: nothing prevents you from having a "client" on the server side that call the "service". That can be part of A's response chain.

If you have a lot of such use cases, I would look at the [RSocket protocol](https://rsocket.io) which supports bi-directional communications specifically.
