### ISSUE TITLE
maxLifeTime not honoured

### ISSUE THREAD

**Issue by owennewo** [reactor/reactor-netty#1918]
I'm making use of WebClient that is backed by ReactorClientHttpConnector

I'm talking to a local docker/nginx container with `keepalive_time 2s;`.  This causes a goaway frame to be sent to connections older than 2s.  This server is supposed to represent a GCP service that does something similar after 3600s.

I'm making about 20 req/s to this service and when server sends goaway frame I'm seeing a small percentage of my requests get trashed (`PrematureCloseException: Connection has been closed BEFORE response, while sending request body`).  This seems reasonable.

There are probably a few different ways to avoid this.  My current approach is to:
`System.setProperty(POOL_MAX_LIFE_TIME, "1800")`

This causes netty client to initiate the socket teardown and hence no GOAWAY frame from server.  This seems to work (no lost requests).

Rather than set a system property I then tried to specify maxLifeTime through a connectionProvider but it doesn't seem to honour the setting - the trashed requests return indicating the client is not tearing down the connections.
```
   // to avoid self signed cert error
    val sslContext = SslContextBuilder
        .forClient()
        .applicationProtocolConfig(
            ApplicationProtocolConfig(
            ApplicationProtocolConfig.Protocol.ALPN,
            ApplicationProtocolConfig.SelectorFailureBehavior.NO_ADVERTISE,
            ApplicationProtocolConfig.SelectedListenerFailureBehavior.ACCEPT,
            ApplicationProtocolNames.HTTP_2,
            ApplicationProtocolNames.HTTP_1_1)
        )
        //.ciphers(HTTP2_CIPHERS, SupportedCipherSuiteFilter.INSTANCE)
        .trustManager(InsecureTrustManagerFactory.INSTANCE)
        .build()
        
    val provider = ConnectionProvider.builder("my-provider")
        .maxConnections(DEFAULT_POOL_MAX_CONNECTIONS)
        .pendingAcquireMaxCount(500)
        .pendingAcquireTimeout(Duration.ofMillis(DEFAULT_POOL_ACQUIRE_TIMEOUT))
        .maxLifeTime(Duration.ofMillis(1000))
        .metrics(true)
        .evictInBackground(Duration.ofSeconds(1))
        .build()

    val httpClient: HttpClient = HttpClient.create(provider)
        .option(ChannelOption.CONNECT_TIMEOUT_MILLIS, 50000)
        .responseTimeout(Duration.ofMillis(50000))
        .protocol(HttpProtocol.H2)
        .wiretap("reactor.netty.http.client.HttpClient", LogLevel.DEBUG, AdvancedByteBufFormat.TEXTUAL)
        .doOnConnected { conn ->
//            conn.addHandlerFirst(GoAwayFrameHandler())
            conn.addHandlerLast(ReadTimeoutHandler(5000, TimeUnit.MILLISECONDS))
                .addHandlerLast(WriteTimeoutHandler(5000, TimeUnit.MILLISECONDS))
            }
        .secure { t: SslProvider.SslContextSpec -> t.sslContext( sslContext )
        }

    val webClient = WebClient.builder()
        .clientConnector(ReactorClientHttpConnector(httpClient))
        .defaultHeader(HttpHeaders.CONTENT_TYPE, MediaType.APPLICATION_JSON_VALUE)
        .defaultHeader(HttpHeaders.ACCEPT, MediaType.APPLICATION_JSON_VALUE)
        .build()

    val response = client
        .post()
        .uri("https://LHG2TR73:8443/payload.json")
        .retrieve().bodyToMono(String::class.java).block()
```

There is a clue in the logs.  Two providers get created (why?).
```
13:07:23.259 [main] DEBUG r.n.r.PooledConnectionProvider - Creating a new [http2] client pool [PoolFactory{evictionInterval=PT0S, leasingStrategy=fifo, maxConnections=16, maxIdleTime=-1, maxLifeTime=-1, metricsEnabled=false, pendingAcquireMaxCount=-1, pendingAcquireTimeout=45000}] for [LHG2TR73:8443]
13:07:23.277 [main] DEBUG r.n.r.PooledConnectionProvider - Creating a new [my-provider] client pool [PoolFactory{evictionInterval=PT1S, leasingStrategy=fifo, maxConnections=16, maxIdleTime=-1, maxLifeTime=1000, metricsEnabled=true, pendingAcquireMaxCount=500, pendingAcquireTimeout=45000}] for [LHG2TR73:8443]
```
Only one provider has my maxLifeTime set.  The other one is created by resolverInternal during a subscribe lambda in HttpClientConnect
https://github.com/reactor/reactor-netty/blob/026fb3c938ec1cba441ec7427f3eefd54d9336e3/reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientConnect.java#L264
This lambda goes on to call HttpResources.get() which supplies null as a provider arg here. 
https://github.com/reactor/reactor-netty/blob/026fb3c938ec1cba441ec7427f3eefd54d9336e3/reactor-netty-http/src/main/java/reactor/netty/http/HttpResources.java#L98

I expect setting maxLifeTime to be equivalent to setting system property.  

## Your Environment
* Reactor version(s) used: 1.0.10
* Other relevant libraries versions (eg. `netty`, ...): 4.1.67.Final
* JVM version (`java -version`):  11.0.8.10
* OS and version (eg. `uname -a`): windows 10

**Comment by violetagg** [comment]
@owennewo Isn't this issue duplicate for this #1818?

**Comment by owennewo** [comment]
Duplicate of #1818
Thanks @violetagg
