### ISSUE TITLE
allowDuplicateContentLengths for Reactor Netty 0.9.x users

### ISSUE THREAD

**Issue by kdevkr** [reactor/reactor-netty#1942]
https://github.com/spring-cloud/spring-cloud-gateway/issues/2465#issuecomment-997227058

Due to the above problem, I would like to activate the allowDuplicateContentLengths option to treat the content-length header with the same value as a single value.

I checked **v0.9.25.RELEASE**, that the last planned release of Reactor Netty in the **Dysprosium** Release Train.
but, this feature add from [v1.0.8](https://github.com/reactor/reactor-netty/releases/tag/v1.0.8).

Is there a reason why this change was released only for 1.0.x users as it could have been added enough in the Dysprolium Release Train?

For 0.9.x users too, i hope it will be released so that `allowDuplicateContentLengths` can be applied.

**Comment by violetagg** [comment]
@kdevkr Reactor Netty 0.9.x series has reached EOL, please upgrade to a newer version.
