### ISSUE TITLE
Calling HttpResources.reset() breaks Http2Resources

### ISSUE THREAD

**Issue by ebradshaw** [reactor/reactor-netty#1943]
## Issue

Http2 requests via the HttpClient leverage the Http2Resources static get() interface, which on the first call atomically instantiates Http2Resources by wrapping HttpResources.get().   This all works fine until HttpResources is reset, which leaves Http2Resources holding on to a broken/disposed HttpResources instance.   In particular, the reset HttpResources object holds on to a disposed AddressResolverGroup.

## Possible Solution

An easy fix would be to add a public static reset() on Http2Resources and broaden the accessibility of Http2Resources, but this might not be the cleanest approach.  Alternatives welcome.

**Comment by violetagg** [comment]
I'm gonna work on this one.

**Comment by violetagg** [comment]
@ebradshaw The fix is available in 1.0.16-SNAPSHOT. It will be great, if you can test it.
