### ISSUE TITLE
when httpclient set protol h2c and http11, then get connection prematurely closed before response or while sending request body.

### ISSUE THREAD

**Issue by sodaRyCN** [reactor/reactor-netty#1951]
**Expected Behavior**
the following two process both are ok, when netty httpclient set protocol h2c and http11.
1.grpc client ----> spring-cloud-gateway (use netty httpclient) ----> grpc server
2.normal http client ----> spring-cloud-gateway (use netty httpclient) ----> normal http server

In process 1:
when set netty httpclient protocol only H2C，the above process is ok. 
but set netty httpclient protocol H2C and http11, **ALL request  get PrematureCloseException**;
Not yet tested process 2;

**build HTTPClient customizer**
`@Bean
@DependsOn(value = {"eventLoopInit"})
public HttpClientCustomizer httpClientCustomizer() {
        return httpClient -> httpClient.runOn(LoopResources.colocate(clientEventLoopGroup)).protocol(HttpProtocol.H2C,HttpProtocol.HTTP11).noSSL();
}`

**spring cloud gateway use httpclient request grpc server**
`
httpclient.headers(headers -> {
            .....
        }).request(method).uri(url).send((req, nettyOutbound) -> {
            xxxx
        }).responseConnection((res, connection) -> {xxxx});
`

**http client pool config**
`spring:
  cloud:
    gateway:
      metrics:
        enabled: true
      httpclient:
        connect-timeout: 10000
        response-timeout: 30000
        pool:
          max-idle-time: 30000
          max-life-time: 30000`

I have read some issue like [#issue 1092](https://github.com/reactor/reactor-netty/issues/1092)
and get tcpdump log. **but I don't understand why the difference with different protocol configuration.**

172.21.1.74:5531 is grpc server
172.21.8.41 is spring-cloud-gateway

set h2c and http11
![企业微信截图_16400787462389](https://user-images.githubusercontent.com/35725024/146907624-253ff2e5-8590-49d0-8e94-b9194c9804ca.png)

![image](https://user-images.githubusercontent.com/35725024/146907734-b4afd65d-b258-424a-aadb-e12d60a2aa21.png)

only set h2c
![企业微信截图_16400793341912](https://user-images.githubusercontent.com/35725024/146907047-ef901237-e8e3-41d1-a365-228a931d6838.png)

it's seem like when set h2c and http1, httpclient invoke grpc server use http1.1. 

**Environment**:
reactor-netty: 1.0.14
netty: 4.1.70.Final
spring cloud gateway: 3.1.0.RELEASE
spring: 5.3.13
spring-boot:2.6.0
JVM version (javar -version): jdk 1.8

**Comment by violetagg** [comment]
@sodaRyCN Can you provide a complete minimal sample (something that we can unzip or git clone, build, and deploy) that reproduces the problem.

**Comment by sodaRyCN** [comment]
> @sodaRyCN Can you provide a complete minimal sample (something that we can unzip or git clone, build, and deploy) that reproduces the problem.

yeah. I would as soon as possilble provide a demo.

**Comment by sodaRyCN** [comment]
@violetagg 
[demo for reproduces the problem](https://github.com/sodaRyCN/issue/tree/main/reactor-netty/1951)

please read readme.md first. 

I sincerely look forward to your reply

**By the way：**
According to the tcpdump log and read some reactor-netty and grpc-java source code today, I guess the reason may be that the grpc server does not support the H2C protocol. I also mentioned the relevant [issue](https://github.com/grpc/grpc-java/issues/8778) in grpc-java, but I haven't received a reply

**Comment by sodaRyCN** [comment]
@violetagg 
I have get the grpc-java's [reply](https://github.com/grpc/grpc-java/issues/8778) : grpc-java server not support h2c, but  support plaintext HTTP/2. **so any way to make httpclient use H2 plaintext?**

**Comment by violetagg** [comment]
@sodaRyCN  Here is their reply https://github.com/grpc/grpc-java/issues/8778#issuecomment-999833890

```
To be clear, the grpc java server supports plaintext HTTP/2, just not the HTTP/1 to HTTP/2 upgrade. The API on client-side was before we knew whether it'd be important and was in case it was needed for compatibility with a proxy.
```

This means that you have to configure the client with `H2C` and not `H2C` AND `HTTP/1.1`. The later will try HTTP/1 to HTTP/2 upgrade.
