### ISSUE TITLE
My TCP program always throws error IO after running for a long time netty. channel. Stacklessclosedchannelexception how to solve this problem? Use version 1.0.10

### ISSUE THREAD

**Issue by 1ssqq1lxr** [reactor/reactor-netty#1959]
## Steps to Reproduce

```java
@Test
public void repoCase() {

}
```

## Your Environment

* Reactor version(s) used:
* Other relevant libraries versions (eg. `netty`, ...):
* JVM version (`java -version`):
* OS and version (eg. `uname -a`):

**Comment by ctlove0523** [comment]
@1ssqq1lxr can you post simple code to reproduct this issue?

**Comment by violetagg** [comment]
@1ssqq1lxr I'm closing this one. We need more information in order to investigate further.
