### ISSUE TITLE
HttpClient doesn't read inbound data from some channels obtained from connection pool

### ISSUE THREAD

**Issue by alexmaddriver** [reactor/reactor-netty#196]
### Expected behavior
HttpClient is able to process inbound data.

### Actual behavior
Sometimes HttpClient does not read inbound data from connections obtained from connection pool. Because of this it fails to process replies causing those waiting for them to freeze.

### Steps to reproduce
The problematic channels are those which last processed message was FullHttpResponse type. When such channel is returned back to connection pool its auto-read property is set to false, which in turn freezes read operations for subsequent requests re-using it.

HttpClientOperations class:

			if (msg instanceof FullHttpResponse) {
				super.onInboundNext(ctx, msg);
				onHandlerTerminate();
			}

With the following fix it starts working as expected:

			if (msg instanceof FullHttpResponse) {
				super.onInboundNext(ctx, msg);
				channel().config().setAutoRead(true);
				onHandlerTerminate();
			}

### Reactor Netty version
reactor-netty-0.7.1.BUILD-SNAPSHOT and earlier

**Comment by smaldini** [comment]
that's interesting we'll investigate - Besides you win the best issue finder award of the month - it probably translates in beer points if you meet any of us !

**Comment by alexmaddriver** [comment]
Nice to know :) Lets do it once you gonna be around Eastern Europe.

We just went in production with the reactor-netty on board and crossing our fingers it works smoothly.
Now the most annoying issue for us is https://github.com/reactor/reactor-netty/issues/177. Hope we manage to nail it down during this week. Any hints are appreciated.

**Comment by smaldini** [comment]
Would you be able to capture debug logs (with slf4j and any bridge, put reactor.ipc.netty in DEBUG) in a file you could send ?

**Comment by violetagg** [comment]
I'm trying to recreate the issue but still no success

```
	@Test
	public void testIssue196() throws Exception {
		NettyContext server =
				HttpServer.create(opt -> opt.host("localhost"))
				          .newHandler((req, res) -> res.status(500)
				                                       .sendByteArray(Flux.just("Test".getBytes())))
				          .block(Duration.ofSeconds(100));

		HttpClient client =
				HttpClient.create(opt -> opt.connectAddress(() -> server.address())
				                            .poolResources(PoolResources.fixed("test", 1))
				                            .afterNettyContextInit(
				                                    ctx -> ctx.channel()
				                                              .pipeline()
				                                              .addAfter(NettyPipeline.HttpCodec, "aggr",
				                                                        new HttpObjectAggregator(1024))));

		StepVerifier.create(Flux.range(0, 1000)
		                        .flatMap(i ->
		                                client.get("/", req -> req.failOnServerError(false))
		                                      .flatMap(res -> {
		                                               res.dispose();
		                                               return Mono.just(res.status().code());
		                                      })
		                                      .onErrorReturn(999))
		                        .count())
		            .expectNext(1000L)
		            .expectComplete()
		            .verify(Duration.ofSeconds(100));

	}
```

If you can provide more information for the scenario and as Stephane asked if you are able to provide the logs it will be very helpful.

**Comment by alexmaddriver** [comment]
Hi! I am traveling this week, will do my best to look into it and provide you with the logs on Wednesday.

**Comment by lhotari** [comment]
Ratpack has this type of handling for idle connections in the pool: https://github.com/ratpack/ratpack/commit/99e33cf885c47822946e3efac865286e394024c4 (latest [IdlingConnectionHandler](https://github.com/ratpack/ratpack/blob/master/ratpack-core/src/main/java/ratpack/http/client/internal/IdlingConnectionHandler.java) contains an improvement to call `ReferenceCountUtil.release`) . 
Besides enabling auto read, it will close the channel if anything is received on the channel or an error occurs. I wonder if similar handling would make sense in Reactor Netty's `ChannelPoolHandler` class which is `reactor.ipc.netty.resources.DefaultPoolResources.Pool`?

**Comment by violetagg** [comment]
Hi,

I found some possible use case when `DefaultFullHttpResponse` is returned and the operations are hanging.

The use case is specific for the returned code `205 Reset Content`
According to [RFC 7231](https://tools.ietf.org/html/rfc7231#page-53) the server can handle `205 Reset Content` following the rules:
```
   In other words, a server MUST do one of the following for a 205
   response: a) indicate a zero-length body for the response by
   including a Content-Length header field with a value of 0; b)
   indicate a zero-length payload for the response by including a
   Transfer-Encoding header field with a value of chunked and a message
   body consisting of a single chunk of zero-length; or, c) close the
   connection immediately after sending the blank line terminating the
   header section.
```

The current Reactor Netty **server** implementation handles `205 Reset Content` following `a)` option, but for example the pure Netty **server** handles `205 Reset Content` following `b)` option.

So if the server that you are using is not Reactor Netty but other that handles `205 Reset Content` following `b)` option then you are facing Netty's HttpObjectDecoder issue: https://github.com/netty/netty/pull/7397

Can you check what kind of responses you have when the issue happens?

I prepared a test case (#217), you can see the following exception happening and the operations are hanging.

```
15:17:01.223 [reactor-http-nio-6] DEBUG r.i.n.c.ChannelOperationsHandler - Decoding failed: DefaultFullHttpResponse(decodeResult: failure(java.lang.IllegalArgumentException: invalid version format: 0), version: HTTP/1.0, content: UnpooledByteBufAllocator$InstrumentedUnpooledUnsafeHeapByteBuf(ridx: 0, widx: 0, cap: 0))
HTTP/1.0 999 Unknown : 
java.lang.IllegalArgumentException: invalid version format: 0
	at io.netty.handler.codec.http.HttpVersion.<init>(HttpVersion.java:121) ~[netty-codec-http-4.1.17.Final.jar:4.1.17.Final]
	at io.netty.handler.codec.http.HttpVersion.valueOf(HttpVersion.java:76) ~[netty-codec-http-4.1.17.Final.jar:4.1.17.Final]
	at io.netty.handler.codec.http.HttpResponseDecoder.createMessage(HttpResponseDecoder.java:118) ~[netty-codec-http-4.1.17.Final.jar:4.1.17.Final]
	at io.netty.handler.codec.http.HttpObjectDecoder.decode(HttpObjectDecoder.java:219) ~[netty-codec-http-4.1.17.Final.jar:4.1.17.Final]
	at io.netty.handler.codec.http.HttpClientCodec$Decoder.decode(HttpClientCodec.java:202) ~[netty-codec-http-4.1.17.Final.jar:4.1.17.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489) ~[netty-codec-4.1.17.Final.jar:4.1.17.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428) ~[netty-codec-4.1.17.Final.jar:4.1.17.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265) ~[netty-codec-4.1.17.Final.jar:4.1.17.Final]

```

Regards,
Violeta

**Comment by violetagg** [comment]
I'm closing this one.
If you are able to provide some reproducible scenario you can reopen it.
