### ISSUE TITLE
NimbusReactiveJwtDecoder bean not used to pass via proxy instead of default WebClient

### ISSUE THREAD

**Issue by haythamdahri** [reactor/reactor-netty#1969]
I have a NimbusReactiveJwtDecoder that is not used in OAuth2 flow to check token signature (**oauth2Login**).
The application must pass via a proxy to achieve the url in the server.
The custom webClient uses proxy to get access token but exception of timeout is thrown when trying to achieve jwk set uri.

## Expected Behavior

Custom WebClient with proxy must be used in NimbusReactiveJwtDecoder instance
## Actual Behavior

NimbusReactiveJwtDecoder bean is not used
## Steps to Reproduce

```java
@Bean
    public NimbusReactiveJwtDecoder nimbusReactiveJwtDecoder(
            @Qualifier("proxyWebClient") WebClient webClient,
            @Value("${spring.security.oauth2.client.provider.company.jwk-set-uri}") final String jwkUrl
    ) {
        NimbusReactiveJwtDecoder.JwkSetUriReactiveJwtDecoderBuilder jwkSetUriReactiveJwtDecoderBuilder = NimbusReactiveJwtDecoder
                .withJwkSetUri(jwkUrl)
                .jwsAlgorithm(SignatureAlgorithm.RS256)
                .webClient(webClient);
        return jwkSetUriReactiveJwtDecoderBuilder.build();
    }
```
Security config
```java
// OAuth2 login
  http.oauth2Login(oauth2 -> oauth2
          .authenticationMatcher(new PathPatternParserServerWebExchangeMatcher("/login/oauth2/code/{registrationId}"))
          .authenticationSuccessHandler(this.reactiveConnectSuccessHandler)
          .authenticationFailureHandler(this.reactiveFailureHandler)
          .authorizedClientService(new InMemoryReactiveOAuth2AuthorizedClientService(companyClientRegistrationRepository))
          .clientRegistrationRepository(companyClientRegistrationRepository)
          .authorizedClientRepository(authorizedClientRepository())
  )
  .build();
```

## Your Environment

* Reactor version(s) used: 0.9.20.RELEASE
* Other relevant libraries versions (eg. `netty`, ...):
* JVM version (`java -version`): 8
* OS and version (eg. `uname -a`): CentOS

**Comment by haythamdahri** [comment]
@violetagg Can you please explain what is the reason behind my issue?
I can't see the solution while you changed the status.

Thank you

**Comment by violetagg** [comment]
@haythamdahri You closed the issue.
Also Reactor Netty does not provide any functionality related to `@Bean`. At all I don't see how this is related to Reactor Netty project.
