### ISSUE TITLE
Error when HttpServer is configured with HTTP/1.1 and HTTP/2 with an idleTimeout

### ISSUE THREAD

**Issue by raycoarana** [reactor/reactor-netty#1990]
## Expected Behavior

Setup a HttpServer with both HTTP/1.1 and HTTP/2 support without SSL, when setting an idleTimeout, it should apply the
`IdleTimeoutHandler`.

## Actual Behavior

Requests fails due to be unable to add the `IdleTimeoutHandler` before the `reactor.left.httpCodec` as it does not exists.

```
java.util.NoSuchElementException: reactor.left.httpCodec
	at io.netty.channel.DefaultChannelPipeline.getContextOrDie(DefaultChannelPipeline.java:1073)
	at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:248)
	at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:237)
	at reactor.netty.http.server.HttpTrafficHandler$IdleTimeoutHandler.addIdleTimeoutHandler(HttpTrafficHandler.java:509)
	at reactor.netty.http.server.HttpTrafficHandler.channelActive(HttpTrafficHandler.java:133)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:230)
```

Checking the code seems that it is wrapped inside `CleartextHttp2ServerUpgradeHandler` when it is build at `HttpServerConfig.configureHttp11OrH2CleartextPipeline`.

https://github.com/reactor/reactor-netty/blob/81f73f7afd7291137e59a7a8ce3f9575600e6b15/reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerConfig.java#L495-L512

## Steps to Reproduce

I setup a little project here that reproduces the issue: https://github.com/raycoarana/reactor-netty-http2-idle-timeout

## Possible Solution

From what I see, it could be fixed by changing the code that adds the handler, it needs to see which handler is added to use to proper one (NettyPipeline.HttpCodec or NettyPipeline.H2CUpgradeHandler), depending on which one exists, the change to apply here:

https://github.com/reactor/reactor-netty/blob/45190a1c0697bc91d6ef928196ec42e032263727/reactor-netty-http/src/main/java/reactor/netty/http/server/HttpTrafficHandler.java#L507-L513

Could be rewrite the method to something like:

```java
static void addIdleTimeoutHandler(ChannelPipeline pipeline, @Nullable Duration idleTimeout) {
	if (idleTimeout != null) {
		String baseName = pipeline.get(NettyPipeline.HttpCodec) != null ? NettyPipeline.HttpCodec : NettyPipeline.H2CUpgradeHandler;
		pipeline.addBefore(baseName,
		                   NettyPipeline.IdleTimeoutHandler,
		                   new IdleTimeoutHandler(idleTimeout.toMillis()));
	}
}
```

But I don't have fully context of the project, so maybe another solution could be better.

## Your Environment

* Reactor-Netty version(s) used: 1.0.15
* JVM version: OpenJDK 17 (build 17+35-2724)
* OS and version: macOS Monterey 12.1

**Comment by violetagg** [comment]
@raycoarana Would you like to create a PR?

**Comment by raycoarana** [comment]
I could do it, sure!

**Comment by raycoarana** [comment]
@violetagg done in #1994
