### ISSUE TITLE
Consider removing default transfer-encoding header?

### ISSUE THREAD

**Issue by PedroAlvarado** [reactor/reactor-netty#2]
On the NettyHttpChannel class, we by default set the transfer-encoding header to chunked. This means that consumers need to call responseTransfer() or removeTransferEncodingChunked() to disable this behavior. Should we instead let the client decide whether they want to set the transfer-encoding or not?

At the moment, the spring-web-reactive class ReactorServerHttpResponse never calls responseTransfer() or removeTransferEncodingChunked() so all reactive based responses produced by spring-web are forced to include the transfer-encoding which should be an optional behavior. 

Alternatively, we could consider updating spring-web's ReactorServerHttpResponse to call responseTransfer() or removeTransferEncodingChunked() to disable transfer-encoding in the presence of the conten-length header.

https://github.com/reactor/reactor-netty/blob/master/src/main/java/reactor/ipc/netty/http/NettyHttpChannel.java#L91

https://github.com/spring-projects/spring-framework/blob/master/spring-web/src/main/java/org/springframework/http/server/reactive/ReactorServerHttpResponse.java#L87

p.s. I've created https://jira.spring.io/browse/SPR-14643 to potentially address this issue upstream.

**Comment by smaldini** [comment]
Should be fixed also in Spring by now but we have added a few cases where chunkd transfer is auto removed, e.g. body-less requests and we'll expand more on this with the major 0.6 api/internal updates.

**Comment by rstoyanchev** [comment]
@smaldini we still [have a workaround](https://github.com/spring-projects/spring-framework/blob/2633b4e9ece819619e18bf162f0d984410222697/spring-web/src/main/java/org/springframework/http/server/reactive/ReactorServerHttpResponse.java#L87). Can you clarify if we can remove that?

**Comment by smaldini** [comment]
My take on this is that it should be up to you to remove it all the time if you usually set single response writer (and deferred content length setting) as a default.
What we try to do is simply avoid chunked encoding ourself before writing the headers if we detect content-length and its still here. Chunked encoding is a viable default in HTTP 1.1 which considers mandatory its support, it is just useless to send an empty body in chunked encoding like informational status response and more overhead than knowing the size and using content length.

**Comment by rstoyanchev** [comment]
Okay I've removed that workaround. Thanks.
