### ISSUE TITLE
No way to set sub-protocols on WebSocket client

### ISSUE THREAD

**Issue by rstoyanchev** [reactor/reactor-netty#20]
`HttpClientOperations` delegates to `withWebSocketSupport` which accepts sub-protocols but that's not exposed. Publicly `HttpClientRequest` only has `sendWebSocket()`.

`HttpClientResponse` has `receiveWebSocket` which does accept sub-protocols but that makes no sense on a response since it is a request header.

**Comment by simonbasle** [comment]
API to be opened, and behavior of Netty to be tested (does it reject if wrong subprotocol is used?)

**Comment by rstoyanchev** [comment]
Netty does support sub-protocols if that's what you mean. We have tests with RxNetty.
