### ISSUE TITLE
PrematureCloseException when doing Multipart uploads to an Actix Server

### ISSUE THREAD

**Issue by DevYukine** [reactor/reactor-netty#2010]
We currently have an Actix Server doing image manipulation and a Spring Webflux API which uses WebClient (which uses Reactor-Netty under the hood) to make a request to said Actix Server on certain routes.

Every now and then (approximately every ~10-20 requests) we get a 500 Response with the below mentioned error

After trying to google that Error nothing really seems to be our issue or help solving this and we tried multiple times changing Actix or WebClient configuration settings without success

2 of my colleagues were also able to fully reproduce this issue locally on there machines.

                     

## Expected Behavior
No error after ~10 requests

especially because after trying ~1k times with curl & Insomnia i never seen this issue once so i heavily assume its a netty issue as other http clients don't show such errors

## Actual Behavior
Every ~10 requests we see following error pop up

https://www.toptal.com/developers/hastebin/aseraxiqam.kt

This issue also only happens on multipart uploads, we have a JSON route also using WebClient with netty under the hood which works 100% of the time and doesn't throw this issue (with the same Actix Server)

## Steps to Reproduce
I made a minimal repo which contains a basic Actix server which just returns the uploaded image and a kotlin spring application which does a multipart request to that actix server with spring webflux starter and WebClient using Netty under the hood here https://github.com/DevYukine/Netty_Actix_Issue

To reproduce the issue
1. Start the Actix Server (runs on port 9015 by default)
2. Start the Spring Server (runs on port 8080 by default)
3. Make few (10-20) POST request (in Insomnia, Postman or curl) to http://localhost:8080

You should be able to see 500's with error logs to the console about the described issue

if you need anything more i will surely provide all needed logs/info 👍 

## Possible Solution
No idea to be fair but from the Actix logs i can judge that the request doesn't even reach the actix server so i assume it has something to do with keep alive connections maybe?

## Your Environment

* Reactor version(s) used: reactor-core 3.4.14 (reactor-netty-core 1.0.15)
* Other relevant libraries versions (eg. `netty`, ...): spring-boot-starter-webflux 2.6.3
* JVM version (`java -version`): OpenJDK 16
* OS and version (eg. `uname -a`): Windows 10

**Comment by violetagg** [comment]
@DevYukine 
Obtain a [TCP dump](https://en.wikipedia.org/wiki/Tcpdump) and check which peer sends a FIN/RST signal.
You can find the client port from the exception e.g. 

```
[<connection-id>, L:/HOST:<client-port> ! R:HOST:9015] The connection observed an error

reactor.netty.http.client.PrematureCloseException: Connection prematurely closed BEFORE response
```

https://projectreactor.io/docs/netty/release/reference/index.html#faq.connection-closed

**Comment by violetagg** [comment]
@DevYukine I'm closing this one, we can reopen it, if it is needed.

**Comment by DevYukine** [comment]
@violetagg Hey sorry, i totally forgot about this 😅 

I can provide a tcp dump but i can't read it myself (no idea whats going on there tbh), also might not be helpful but as the issue is not instantly there but every 3rd or 4th+ request the tcp dump would contain more than 1 request, unsure if this makes it worthless or not, if it does then i still provided a repo which 100% reproduces the issue for me so that might also be an option to look into

**Comment by violetagg** [comment]
@DevYukine I tried the provided example. On the Spring server I'm seeing this exception:


```
2022-02-12 07:08:45.825  WARN 32757 --- [or-http-epoll-1] r.netty.http.client.HttpClientConnect    : [80d19ac9-2, L
:/127.0.0.1:47380 ! R:localhost/127.0.0.1:9015] The connection observed an error
reactor.netty.http.client.PrematureCloseException: Connection prematurely closed BEFORE response
```

In the TCP dump I'm seeing that the Actix server is closing the connection:

![Screenshot 2022-02-12 at 9 22 28](https://user-images.githubusercontent.com/696661/153701594-47f5d0d8-f63c-4af8-bf2d-5ea6215d26f9.png)

**Comment by DevYukine** [comment]
@violetagg Hey thanks for taking a look, what does that exactly mean? and why does this not happen on other http clients i'm using? (i switched out netty fully for my multipart upload which fixed the issue but i would love to use the reactive spring client for everything ofc)

If this is an actix issue, should i report this to the Actix devs or is this an configration issue? im sorry but your reply doesn't really give me any help on what to do from here

**Comment by violetagg** [comment]
@DevYukine

> Hey thanks for taking a look, what does that exactly mean?

The TCP dump above shows that Actix server closes the connection

> If this is an actix issue, should i report this to the Actix devs or is this an configration issue?

I cannot comment on this

**Comment by DevYukine** [comment]
@violetagg this still doesn't really help me, how comes other http libraries work as expected while reactive spring client (using netty under the hood) doesn't? (currently switched to okhttp), i'm only getting it on multipart as well while not getting any issues for json based requests (using the same actix server), i really can't see how this is not a netty issue 🤔

**Comment by violetagg** [comment]
@DevYukine Spring WebClient multipart implementation in not provided by Reactor Netty/Netty but by Spring Framework.
