### ISSUE TITLE
flush behavior

### ISSUE THREAD

**Issue by robertroeser** [reactor/reactor-netty#203]
Currently there seems to be two modes for flushing. One is flushing on each write, and the other is flush at the end of stream. This lead two a couple problems. The first is a stream of data that doesn't end is never flushed, and the send is that you end up with a bunch of writes and flushes. I did some experimenting with RSocket, and came up with a good in-between solution. I was able to get roughly 15k more RPS with similar latency to writeAndFlush for a perf test we have. What I did was on each emit I attempted to schedule a flush - something along these lines:
```
// Code Writing to Netty
ChannelFuture write = channel.write(o);
if (!channel.isWritable()) {
  channel.flush();
} else {
    if (scheduledFlush == 0) {
      scheduleFlush(channel);
    }
}

return FutureMono.from(write);
...
// Method attempts to schedule a flush on the Netty event loop
void scheduleFlush(Channel channel) {
    if (SCHEDULED_FLUSH.compareAndSet(this, 0, 1)) {
      channel
          .eventLoop()
          .execute(
              () -> {
                channel.flush();
                SCHEDULED_FLUSH.set(ChannelOperationsHandler.this, 0);
              });
    }
  }
```
The SCHEDULED_FLUSH variable acted as a guard so if there was multiple writes at the same time flush was only called once.  I don't know if this is ideal for behavior for all scenarios but it seemed to work well for what I was doing.  It would be nice have something like this be an optional, or be able to plugin your own version of ChannelOperationsHandler so you could do custom implementations for your use case. Maybe there is a way to do that now, but it seemed like the ChannelOperationsHandler was created instead another class, and then handed 'this'

**Comment by smaldini** [comment]
Actually ignore that i just read that you do that on every write that is writeable ! Interesting

**Comment by smaldini** [comment]
I see @violetagg is actually already on the case ! https://github.com/violetagg/reactor-netty/commit/375855ac56fa2a4bcd81ca41fc2a220033ac6f1f

**Comment by violetagg** [comment]
Can you please take a look and give us feedback about the new behavior?

Thanks, Violeta
