### ISSUE TITLE
TLS Encrypted Client Hello (ECH)

### ISSUE THREAD

**Issue by glennosss** [reactor/reactor-netty#2086]
Add support for ECH when Netty supports - for more information see: https://github.com/netty/netty-incubator-codec-http3/issues/190

**Comment by violetagg** [comment]
@glennosss I see the issue is opened for Netty HTTP/3 codec. This feature request is for Reactor Netty HTTP/3 support, isn't it?

**Comment by glennosss** [comment]
Encrypted Client Hello (ECH) is applicable to TLS 1.3 (and all future version of TLS) - as such, it's applicable to HTTP/1.1, HTTP/2 and HTTP/3. I probably shouldn't have opened the issue against the Netty HTTP/3 codec, but I thought that's probably where the most active development was.

So technically this is a request for eventual Reactor Netty HTTP/1.1/2/3 support.

My apologies if I've raised this request too eagerly, but there are a lot of important features relevant to proper HTTP/3 support and I thought it was good idea to start putting these issues on peoples radars.

**Comment by violetagg** [comment]
So may be the feature request above should be for Netty project (not only HTTP/3 codec) https://github.com/netty/netty

I'm adding this to General Backlog, once we have a solution in Netty we can discuss with which version we can provide something.

**Comment by glennosss** [comment]
FYI This work as been completed on the netty end - https://github.com/netty/netty-incubator-codec-http3/issues/190
