### ISSUE TITLE
netty send fin before response. error message: Connection closed  DURING response

### ISSUE THREAD

**Issue by SurelySomeday** [reactor/reactor-netty#2089]
I use netty as a gateway proxy to access the background service, and the interface of this service will delay the return of data, if the data is read within 15 seconds, the data will be returned, and if there is no data in 15 seconds, it will directly return a success ID. In a real scenario, a large number of requests will return in 15 seconds. Originally, there would be a lot of "Connection closed DURING response" in the netty 0.9.7 version, and later after upgrading netty to 1.0.16, there would be no "Connection closed DURING response", but a large number of requests would return after more than 15 seconds (the background will inevitably return data at 15 seconds, But in reality, we found that a large number of requests exceeded 15 seconds or even reached 30 seconds). Later I tried to turn off netty's pool, and now all requests can be returned in 15 seconds, but there are still intermittent exceptions. The screenshot of the tcp capture below is the exception information I got. Yes my system has the "tcp_tw_recycle" option turned on, is it related to it?

## Expected Behavior

![1646834276(1)](https://user-images.githubusercontent.com/32257480/157456055-efd54f93-c005-497e-bcbe-439be30fb7db.png)

## Actual Behavior

![1646834322(1)](https://user-images.githubusercontent.com/32257480/157456184-9a87ad31-ab28-49f4-8cad-25e4c7899bc5.png)

## Steps to Reproduce

```java
@Test
public void repoCase() {

}
```

## Your Environment

* Reactor version(s) used: 1.0.16
* Other relevant libraries versions (eg. `netty`, ...):  1.0.16
![1646835262(1)](https://user-images.githubusercontent.com/32257480/157458919-90f6e11f-050b-4bc6-ae2a-a29ce378620e.png)

* JVM version (`java -version`): 1.8
* OS and version (eg. `uname -a`):  centos7

**Comment by SurelySomeday** [comment]
@violetagg  First of all thank you for replying to my question. Sorry, since the accessing background service can not provide sample code for the time being, it is impossible to construct a perfect sample to reproduce, and then try to communicate with them to obtain the corresponding code to help reproduce the exception. After closing pool, no problems have been found so far. As for the "RST" on the screenshot after testing, I guess it should be that the client closes the program, so it will send "fin" to close the link, but the background service did not respond to "fin" but sent a packet, so there was an exception the packet needed to send "RST" to reset the link, I don't know if this understanding is correct?. I have a question about this, if the interface of the background service takes 15 seconds to return, will the TCP link be reused during this 15 seconds?

**Comment by violetagg** [comment]
@SurelySomeday Without having a proper description/code of the use case it is hart to guess just based on tcp dumps.

> I have a question about this, if the interface of the background service takes 15 seconds to return, will the TCP link be reused during this 15 seconds?

Can you elaborate more on this?

**Comment by SurelySomeday** [comment]
@violetagg  Sorry, I mean that there were some problems in the process of translating "connection". It is true that it is difficult to find the problem if it cannot be reproduced, and you can close the problem first. If I get a code that can be reproduced, I'll ask you again. Thank you.

**Comment by violetagg** [comment]
@SurelySomeday While you are investigating the issue if you need some help you can use [Gitter](https://gitter.im/reactor/reactor-netty) for real time discussions with the community.
Let me close this for now, we can reopen it at any time.

**Comment by haitun521** [comment]
@SurelySomeday hi, I met the same problem as you, how did you solve it?

**Comment by haitun521** [comment]
@SurelySomeday hi, I met the same problem as you, how did you solve it?

**Comment by SurelySomeday** [comment]
> @SurelySomeday hi, I met the same problem as you, how did you solve it?

I didn't find the cause of the problem. I tried to configure that closing the connection pool can temporarily solve the problem. You can also try it.
`spring.cloud.gateway.httpclient.pool.type=DISABLED`

**Comment by haitun521** [comment]
@SurelySomeday thanks
