### ISSUE TITLE
Problem with import packages

### ISSUE THREAD

**Issue by janvdbergh** [reactor/reactor-netty#209]
We are using reactor-netty in an OSGi container (Felix). However the Import-Package version of javax.annotation is incorrect. The correct version of the javax.annotation API is 1.0.0.

### Expected behavior
The version of javax.annotation in the Import-Package statement in MANIFEST.MF is equal to [1.0,2) or not specified.
Since this dependency is only required at compile time, it can also be removed or made optional.

### Actual behavior
The version is automatically set by the version of the com.google.code.findbugs:jsr305 dependency, which is 3.0.2. 

### Steps to reproduce
Build the code.
Look at the produced MANIFEST.MF file.

### Reactor Netty version
0.7.1.RELEASE

### JVM version (e.g. `java -version`)
java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)

### OS version (e.g. `uname -a`)
Darwin Jans-MacBook-Pro.local 17.2.0 Darwin Kernel Version 17.2.0: Fri Sep 29 18:27:05 PDT 2017; root:xnu-4570.20.62~3/RELEASE_X86_64 x86_64

**Comment by janvdbergh** [comment]
Any idea when we could expect a release of version 0.7.2? We are waiting on it for our own releases.

**Comment by violetagg** [comment]
0.7.2.RELEASE is out so you should be able to use it.
