### ISSUE TITLE
Make no assumption of the threading context

### ISSUE THREAD

**Issue by CleverChuk** [reactor/reactor-netty#2096]
This [line ](https://github.com/reactor/reactor-netty/blob/37768027aaf14830f1b166a6f76cd908ccfd082c/reactor-netty-core/src/main/java/reactor/netty/channel/FluxReceive.java#L283) assumes that  line 279 continues on the same thread. However that is not always true and results in the buffer being released before the user code could process it.

## Motivation

This is a pretty bad assumption because one of the selling point of project reactor is to allow you to chose where your processing runs. Line 283 can free the buffer before the processing actually starts in the user code if the user switches thread context. This can lead to hard to find bug in the user code.

## Desired solution

So my suggestion flows from the same vein of reasoning in Netty which states that the last component to use a ByteBuf is responsible for freeing it. Therefore we should defer that responsibility to the user code if we're indeed giving a ByteBuf instead of non-reference counted types.

## Considered alternatives

Well, just run on reactor-netty threads and don't switch context.

**Comment by violetagg** [comment]
@CleverChuk If you `retain` the buffer in `onNext` event, you should be able to continue to use the `ByteBuf`. Did you try that?

**Comment by CleverChuk** [comment]
That throws  [IllegalReferenceCountException](https://github.com/netty/netty/blob/d34212439068091bcec29a8fad4df82f0a82c638/common/src/main/java/io/netty/util/internal/ReferenceCountUpdater.java#L123)

**Comment by violetagg** [comment]
@CleverChuk Can you please provide an example?

**Comment by CleverChuk** [comment]
@violetagg 
Hope this helps
```
class Handler{
 public void handle(ByteBuf buffer){
   buffer.retain(); // this throws
   // read and process
 }

 pubic void onConnect(Connection connection){
  connection.inbound()
    .receiveObject()
    .publishOn(Schedulers.boundedElastic())
    .cast(ByteBuf.class)
    .doOnNext(this::handle)
    .subscribeOn(Schedulers.boundedElastic())
    .subscribe()
 }
}
```

**Comment by violetagg** [comment]
@CleverChuk Do you think the code below will work for your use case? Please note that `doOnNext` is considered a side-effect operator and you should use it only for logging etc.

```
connection.inbound()
          .receive()
          .retain()
          .publishOn(Schedulers.boundedElastic())
          // At this point the ByteBuf.retain() is invoked and the application has to invoke
          // ByteBuf.release(), once the ByteBuf processing is done
          .doOnNext(byteBuf -> {
              System.out.println(byteBuf.toString(Charset.defaultCharset()));
              byteBuf.release();
          })
          .subscribeOn(Schedulers.boundedElastic())
          .subscribe();
```

**Comment by CleverChuk** [comment]
@violetagg 
Yes, that would do it thanks. Also, thanks for pointing out the doOnNext misuse.
