### ISSUE TITLE
Add support for HTTP 1.0

### ISSUE THREAD

**Issue by sdeleuze** [reactor/reactor-netty#21]
As discussed recently about the issue raised on https://jira.spring.io/browse/SPR-14964, a very simple `ab -n 1 -c 1 http://localhost:8082/items/10` on Spring + Reactor Netty based server block forever likely because Reactor Netty does not support HTTP 1.0.

**Comment by sdeleuze** [comment]
See RxNetty feedback which supports that but only explicitly https://github.com/ReactiveX/RxNetty/issues/575#issuecomment-271790006

**Comment by bclozel** [comment]
Someone also reported that Reactor Netty doesn't support `"Connection: close"` request headers in this case.

See [SPR-16309](https://jira.spring.io/browse/SPR-16309).

**Comment by johnny** [comment]
I cannot reproduce this issue anymore. Has this been closed?

**Comment by violetagg** [comment]
@Johnny I have to check this, we didn't work on that.

**Comment by sdeleuze** [comment]
Indeed I can't reproduce it anymore so closing this issue.
