### ISSUE TITLE
Cipher order isn't respected when using 'netty-tcnative-boringssl-static'

### ISSUE THREAD

**Issue by glennosss** [reactor/reactor-netty#2101]
Cipher order is respected for `SslProvider.JDK`, however when we use the `SslProvider.OPENSSL` provider with `netty-tcnative-boringssl-static` then the client order is still followed. Then can be seen very easily using [wireshark](https://www.wireshark.org/).

Example code;
```
    private static final SslProvider PROVIDER = SslProvider.OPENSSL; // i.e. BoringSSL.
    //private static final SslProvider PROVIDER = SslProvider.JDK;

    private static final String[] PROTOCOLS = new String[] {
            SslProtocols.TLS_v1_3,
            SslProtocols.TLS_v1_2
    };

    private static final String[] CIPHERS = new String[] { // Note: ciphers in order of priority.
            // TLS 1.3 ciphers - warning: BoringSSL doesn't allow disabling of TLS1.3 ciphers because to be compliant you're meant to have support for all of them.
            "TLS_AES_256_GCM_SHA384",
            "TLS_AES_128_GCM_SHA256",
            "TLS_CHACHA20_POLY1305_SHA256",

            // TLS 1.2 ciphers
            "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
            "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256", // Required by HTTP/2 spec!
            "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256"
    };

    private static final String[] ALPN_PROTOCOLS = new String[] {ApplicationProtocolNames.HTTP_2, ApplicationProtocolNames.HTTP_1_1}; // Names as per ALPN spec

    protected static SslContext getSslContext(File cert, File key) throws SSLException {
        if (PROVIDER == SslProvider.OPENSSL) {
            OpenSsl.ensureAvailability();
        }
        SslContextBuilder builder = SslContextBuilder.forServer(cert, key);
        builder.sslProvider(PROVIDER);
        builder.protocols(PROTOCOLS);
        builder.ciphers(Arrays.asList(CIPHERS));
        builder.applicationProtocolConfig(new ApplicationProtocolConfig(Protocol.ALPN,
                SelectorFailureBehavior.NO_ADVERTISE, SelectedListenerFailureBehavior.ACCEPT,
                ALPN_PROTOCOLS));
        return builder.build();
    }
```

The relevant BoringSSL code is I believe: https://boringssl.googlesource.com/boringssl/+/refs/heads/chromium-stable/ssl/handshake_server.cc#350
```
  if (ssl->options & SSL_OP_CIPHER_SERVER_PREFERENCE) {
    // Use server order
  } else {
    // Use client order
  }
```

I've confirmed the `io.netty.internal.tcnative.SSL.SSL_OP_CIPHER_SERVER_PREFERENCE` flag is set using `io.netty.internal.tcnative.SSLContext.setOptions(ctx, options)`. Also tried setting `SSL.SSL_OP_CIPHER_SERVER_PREFERENCE` on/off manually, but this doesn't change the behaviour.

This potentially appears to be a known issue - https://github.com/netty/netty/issues/9140 - which describes the issue as BoringSSL issue. However personally I don't see how this could be a BoringSSL issue.

Any help or assistance in tracing this down would be greatly appreciated.

**Comment by glennosss** [comment]
For those who are interested, Chrome presently sends the following ciphers in the `ClientHello`;
```
Cipher Suites (16 suites)
    Cipher Suite: Reserved (GREASE) (0xeaea)
    Cipher Suite: TLS_AES_128_GCM_SHA256 (0x1301)
    Cipher Suite: TLS_AES_256_GCM_SHA384 (0x1302)
    Cipher Suite: TLS_CHACHA20_POLY1305_SHA256 (0x1303)
    Cipher Suite: TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256 (0xc02b)
    Cipher Suite: TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 (0xc02f)
    Cipher Suite: TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384 (0xc02c)
    Cipher Suite: TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 (0xc030)
    Cipher Suite: TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256 (0xcca9)
    Cipher Suite: TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256 (0xcca8)
    Cipher Suite: TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA (0xc013)
    Cipher Suite: TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA (0xc014)
    Cipher Suite: TLS_RSA_WITH_AES_128_GCM_SHA256 (0x009c)
    Cipher Suite: TLS_RSA_WITH_AES_256_GCM_SHA384 (0x009d)
    Cipher Suite: TLS_RSA_WITH_AES_128_CBC_SHA (0x002f)
    Cipher Suite: TLS_RSA_WITH_AES_256_CBC_SHA (0x0035)
```

When using the source code above (which specified `TLS_AES_256_GCM_SHA384` first), we expect the server to select the `TLS_AES_256_GCM_SHA384` cipher. However when looking at the `ServerHello` response, only SslProvider.JDK does this. SslProvider.OPENSSL with 'netty-tcnative-boringssl-static' wrongly selects the first client preference of `TLS_AES_128_GCM_SHA256`.

**Comment by glennosss** [comment]
My performance testing shows;

- HTTP/2 is faster than HTTP/1.1 (sometimes as much as twice as fast)
- AES is 3 times faster than CHACHA20_POLY1305 on servers (i.e. non-mobile devices)
- **_However importantly:_** Java 17 (SslProvider.JDK) and BoringSSL (SslProvider.OPENSSL) are roughly equivalent in terms of performance.

Kind of seems like it doesn't make much of a difference any more? (since Java 9 performance seems to have become roughly comparable)

So given all of this should I be using Java 17 (SslProvider.JDK) or BoringSSL (SslProvider.OPENSSL)?

**Comment by violetagg** [comment]
@glennosss Can you specify the Reactor Netty issue?

**Comment by violetagg** [comment]
@glennosss Can you specify the Reactor Netty issue?

**Comment by glennosss** [comment]
This isn't a Reactor Netty specific issue - but it affects every Reactor Netty implementation.

It's clearly a bad thing that developers are setting a cipher priority order with the strong belief it will be honoured - but in actual fact due to a bug in either Netty's SslContext, 'netty-tcnative-boringssl-static' or in BoringSSL itself the client is able to override this order.

I was looking for 2 things from the Reactor Netty community;

- Recommendations on Java 17 (SslProvider.JDK) vs BoringSSL (SslProvider.OPENSSL)
- Support in getting this issue escalated, investigated and involved. I took the issue as far as I could without actually recompiling the BoringSSL library myself.

**Comment by violetagg** [comment]
I'm closing this issue as it is Netty related.
