### ISSUE TITLE
AccessLog's logger name does not match fully qualified name of the class

### ISSUE THREAD

**Issue by hennr** [reactor/reactor-netty#2111]
I was a bit confused to see, that I couldn't jump for my logback config in my IDE to the AccessLog class while I configured it like this:

    <logger name="reactor.netty.http.server.AccessLog" level="INFO" additivity="false">
        <appender-ref ref="async"/>
    </logger>

(as described in the docs here: https://cloud.spring.io/spring-cloud-gateway/multi/multi__reactor_netty_access_logs.html)

A look into the actual class reveals, that the logger name is reactor.netty.http.server.AccessLog while the fully qualified name would be reactor.netty.http.server.**logging**.AccessLog

Relevant source:
https://github.com/reactor/reactor-netty/blob/43169a9db51cdb20d262c1435d02abce3c46edf1/reactor-netty-http/src/main/java/reactor/netty/http/server/logging/AccessLog.java#L34

Is this by intention or could this be aligned?

FYI @mle-enso

**Comment by hennr** [comment]
@aneveu Do you remember anything about this logger's name per chance?

**Comment by violetagg** [comment]
@hennr The logger name is intentionally not following the package for the class.
