### ISSUE TITLE
an idea to support dynamic https like (caddy server)   

### ISSUE THREAD

**Issue by ashraf-revo** [reactor/reactor-netty#2156]
## Motivation
i hope if we could support  tls lazy load certificates by domain
this might help us in renew the certificates (using letsencrypt or other)
support dynamic https like (caddy server)
see https://caddyserver.com/docs/quick-starts/https
## Desired solution
add function to load certificates by domain as key 
we could implment this function to renew or generate ssl certificate

**Comment by violetagg** [comment]
@ashraf-revo Are you interested in providing a PR?

**Comment by ashraf-revo** [comment]
@violetagg if you guide me, i will appreciate that very well , it will be my first pr in open source

**Comment by ashraf-revo** [comment]
@violetagg after check the code i found that it could be done if we create new method `SniProvider.newSniHandler `
that use the `io.netty.handler.ssl.SniHandler` not `reactor.netty.tcp.SniProvider.AdvancedSniHandler` because it not use the power of `AsyncMapping<String, SslContext>`
