### ISSUE TITLE
TCP keeplive configuration not working 

### ISSUE THREAD

**Issue by idikshit** [reactor/reactor-netty#2167]
Hi, 

We are trying to configure TCP keep alive settings in our Netty server customizer as depicted below.

```
`LoopResources resource = LoopResources.create("ingress-h2c");
		ReactorResourceFactory reactorResourceFactory = new ReactorResourceFactory();
		reactorResourceFactory.setLoopResources(resource);
		reactorResourceFactory.setUseGlobalResources(false);
		factory.setResourceFactory(reactorResourceFactory);
		factory.setPort(port);
```
		
		if(keepAliveEnabled && Epoll.isAvailable()) {
			factory.addServerCustomizers(builder -> builder.option(ChannelOption.SO_KEEPALIVE, true)
					.option(EpollChannelOption.TCP_KEEPIDLE,keepAliveIdleTime)
					.option(EpollChannelOption.TCP_KEEPCNT,keepAliveCount)
					.option(EpollChannelOption.TCP_KEEPINTVL,keepAliveInterval));
                 }`  

Configurations

Keep alive idle time - 20 seconds
keep alive count - 1000
keep alive interval - 10 seconds

Expected behavior - TCP keep alive should be generated on idle connection. 
Observed behavior - TCP keep alive is not generated after configured idle time / interval.

Dependencies

Reactor Netty version - 1.0.16
Spring boot version - 2.6.3
Java version - 17
Spring cloud gateway version - 3.0.5
Netty version - 4.1.73.Final
OS - Cent OS / Linux

PFA attached network trace, the following filter can be used to filter packets. tcp.port==8081
[keepAlive.zip](https://github.com/reactor/reactor-netty/files/8562461/keepAlive.zip)

**Comment by violetagg** [comment]
@idikshit Can you provide some reproducible example?

**Comment by violetagg** [comment]
@idikshit With this configurations you should see something like this

`Unknown channel option 'SO_KEEPALIVE' for channel`

In order to have `SO_KEEPALIVE` on the server you need to use `childOption(...)` instead of `option(...)`

Can you try with this configuration?

**Comment by Onlyheree** [comment]
#

**Comment by idikshit** [comment]
@violetagg I have changed the configuration to use `childOption(...)` for all the settings
1. SO_KEEPALIVE
2. TCP_KEEPIDLE
3. TCP_KEEPINTVL
4. TCP_KEEPCNT

```
factory.addServerCustomizers(builder -> builder.childOption(ChannelOption.SO_KEEPALIVE, true)
					.childOption(EpollChannelOption.TCP_KEEPIDLE,keepAliveIdleTime)
					.childOption(EpollChannelOption.TCP_KEEPCNT,keepAliveCount)
					.childOption(EpollChannelOption.TCP_KEEPINTVL,keepAliveInterval));
```

I still see the logs with message 

```
Unknown channel option 'SO_KEEPALIVE'
Unknown channel option 'io.netty.channel.epoll.EpollChannelOption#TCP_KEEPCNT'
Unknown channel option 'io.netty.channel.epoll.EpollChannelOption#TCP_KEEPINTVL'
Unknown channel option 'io.netty.channel.epoll.EpollChannelOption#TCP_KEEPIDLE'
```

But at the same time I see keep alive packets captured in network trace. Is this the expected behavior?

Also If I use `childOption(..)`  only for 'SO_KEEPALIVE' setting then in that case TCP keep alives are not getting generated and the log still appears.

**Comment by violetagg** [comment]
@idikshit In the logs what's the thead's name `reactor-netty-nio` or `reactor-netty-epoll`?

> Also If I use childOption(..) only for 'SO_KEEPALIVE' setting then in that case TCP keep alives are not getting generated and the log still appears.

When you enable only 'SO_KEEPALIVE' then the rest of the settings are OS specific - typically the idle time is 2 hours. See this https://en.wikipedia.org/wiki/Keepalive

**Comment by idikshit** [comment]
@violetagg  These logs show up during application boot-up on "main" thread
```
{"instant":{"epochSecond":1651145452,"nanoOfSecond":496553391},"thread":"main","level":"WARN","loggerName":"reactor.netty.transport.TransportConnector","message":"[64aab070] Unknown channel option 'SO_KEEPALIVE' for channel '[id: 0x64aab070]'","endOfBatch":false,"loggerFqcn":"org.apache.logging.slf4j.Log4jLogger","contextMap":{},"threadId":1,"threadPriority":5,"messageTimestamp":"2022-04-28T11:30:52.496+0000","ocLogId":"${ctx:ocLogId}","pod":"${ctx:hostname}","processId":"1","instanceType":"prod","ingressTxId":"${ctx:ingressTxId}"}
{"instant":{"epochSecond":1651145452,"nanoOfSecond":497588162},"thread":"main","level":"WARN","loggerName":"reactor.netty.transport.TransportConnector","message":"[64aab070] Unknown channel option 'io.netty.channel.epoll.EpollChannelOption#TCP_KEEPCNT' for channel '[id: 0x64aab070]'","endOfBatch":false,"loggerFqcn":"org.apache.logging.slf4j.Log4jLogger","contextMap":{},"threadId":1,"threadPriority":5,"messageTimestamp":"2022-04-28T11:30:52.497+0000","ocLogId":"${ctx:ocLogId}","pod":"${ctx:hostname}","processId":"1","instanceType":"prod","ingressTxId":"${ctx:ingressTxId}"}
{"instant":{"epochSecond":1651145452,"nanoOfSecond":497926062},"thread":"main","level":"WARN","loggerName":"reactor.netty.transport.TransportConnector","message":"[64aab070] Unknown channel option 'io.netty.channel.epoll.EpollChannelOption#TCP_KEEPINTVL' for channel '[id: 0x64aab070]'","endOfBatch":false,"loggerFqcn":"org.apache.logging.slf4j.Log4jLogger","contextMap":{},"threadId":1,"threadPriority":5,"messageTimestamp":"2022-04-28T11:30:52.497+0000","ocLogId":"${ctx:ocLogId}","pod":"${ctx:hostname}","processId":"1","instanceType":"prod","ingressTxId":"${ctx:ingressTxId}"}
{"instant":{"epochSecond":1651145452,"nanoOfSecond":498283710},"thread":"main","level":"WARN","loggerName":"reactor.netty.transport.TransportConnector","message":"[64aab070] Unknown channel option 'io.netty.channel.epoll.EpollChannelOption#TCP_KEEPIDLE' for channel '[id: 0x64aab070]'","endOfBatch":false,"loggerFqcn":"org.apache.logging.slf4j.Log4jLogger","contextMap":{},"threadId":1,"threadPriority":5,"messageTimestamp":"2022-04-28T11:30:52.498+0000","ocLogId":"${ctx:ocLogId}","pod":"${ctx:hostname}","processId":"1","instanceType":"prod","ingressTxId":"${ctx:ingressTxId}"}
```

> When you enable only SO_KEEPALIVE then the rest of the settings are OS specific - typically the idle time is 2 hours. See this https://en.wikipedia.org/wiki/Keepalive 

So i believe i need to specify all other setting with `childOption(...)` in order to override default OS specific configuration?

**Comment by violetagg** [comment]
> @violetagg These logs show up during application boot-up on "main" thread
> 
> ```
> {"instant":{"epochSecond":1651145452,"nanoOfSecond":496553391},"thread":"main","level":"WARN","loggerName":"reactor.netty.transport.TransportConnector","message":"[64aab070] Unknown channel option 'SO_KEEPALIVE' for channel '[id: 0x64aab070]'","endOfBatch":false,"loggerFqcn":"org.apache.logging.slf4j.Log4jLogger","contextMap":{},"threadId":1,"threadPriority":5,"messageTimestamp":"2022-04-28T11:30:52.496+0000","ocLogId":"${ctx:ocLogId}","pod":"${ctx:hostname}","processId":"1","instanceType":"prod","ingressTxId":"${ctx:ingressTxId}"}
> {"instant":{"epochSecond":1651145452,"nanoOfSecond":497588162},"thread":"main","level":"WARN","loggerName":"reactor.netty.transport.TransportConnector","message":"[64aab070] Unknown channel option 'io.netty.channel.epoll.EpollChannelOption#TCP_KEEPCNT' for channel '[id: 0x64aab070]'","endOfBatch":false,"loggerFqcn":"org.apache.logging.slf4j.Log4jLogger","contextMap":{},"threadId":1,"threadPriority":5,"messageTimestamp":"2022-04-28T11:30:52.497+0000","ocLogId":"${ctx:ocLogId}","pod":"${ctx:hostname}","processId":"1","instanceType":"prod","ingressTxId":"${ctx:ingressTxId}"}
> {"instant":{"epochSecond":1651145452,"nanoOfSecond":497926062},"thread":"main","level":"WARN","loggerName":"reactor.netty.transport.TransportConnector","message":"[64aab070] Unknown channel option 'io.netty.channel.epoll.EpollChannelOption#TCP_KEEPINTVL' for channel '[id: 0x64aab070]'","endOfBatch":false,"loggerFqcn":"org.apache.logging.slf4j.Log4jLogger","contextMap":{},"threadId":1,"threadPriority":5,"messageTimestamp":"2022-04-28T11:30:52.497+0000","ocLogId":"${ctx:ocLogId}","pod":"${ctx:hostname}","processId":"1","instanceType":"prod","ingressTxId":"${ctx:ingressTxId}"}
> {"instant":{"epochSecond":1651145452,"nanoOfSecond":498283710},"thread":"main","level":"WARN","loggerName":"reactor.netty.transport.TransportConnector","message":"[64aab070] Unknown channel option 'io.netty.channel.epoll.EpollChannelOption#TCP_KEEPIDLE' for channel '[id: 0x64aab070]'","endOfBatch":false,"loggerFqcn":"org.apache.logging.slf4j.Log4jLogger","contextMap":{},"threadId":1,"threadPriority":5,"messageTimestamp":"2022-04-28T11:30:52.498+0000","ocLogId":"${ctx:ocLogId}","pod":"${ctx:hostname}","processId":"1","instanceType":"prod","ingressTxId":"${ctx:ingressTxId}"}
> ```
> 
>  > When you enable only SO_KEEPALIVE then the rest of the settings are OS specific - typically the idle time is 2 hours. See this https://en.wikipedia.org/wiki/Keepalive
> 
> So i believe i need to specify all other settings for keep alive interval, count and idleTime with `childOption(...)` as well in order to override default OS specific configuration?

yes

**Comment by idikshit** [comment]
Thankyou

**Comment by violetagg** [comment]
@idikshit Testing on CentOS 7 with open JDK 17 I do not see any warning about the 4 child options and the keep alive works as expected.
