### ISSUE TITLE
Recording metrics could cause errors in operational code

### ISSUE THREAD

**Issue by ChristianLMI** [reactor/reactor-netty#2187]
## Motivation
I recently ran into an issue where an exception thrown in Micrometer caused my request to break. The actual issue I ran into is not in reactor although reactor was used. However as reactor uses Micrometer as well and e.g. [here|https://github.com/reactor/reactor-netty/blob/main/reactor-netty-core/src/main/java/reactor/netty/channel/AbstractChannelMetricsHandler.java] there also doesn't seem to be any protection of the main functionality against errors in metrics recording, this might be good to look at in reactor as well.

## Desired solution
IMHO metrics should be of lower priority than production results. Therefor a failing metric registration should write a log entry but not abort the current operation.

## Additional context
In my case a misconfigured a MeterFilter that caused NullPointerExceptions when recording a filtered metric.

**Comment by violetagg** [comment]
@ChristianLMI Would you like to provide a PR?

**Comment by ChristianLMI** [comment]
I'll try to find some time to at least get a first step done. However as I'm not too familiar with the project I might miss edges ;)

**Comment by violetagg** [comment]
@ChristianLMI It will be great if you can find time. If you decide to work on this please do the changes against `1.0.x` branch.

The classes that need to have this enhancement are:
`reactor-netty-core`
- reactor.netty.channel.AbstractChannelMetricsHandler
- reactor.netty.channel.ChannelMetricsHandler
- reactor.netty.channel.ContextAwareChannelMetricsHandler
- reactor.netty.transport.AddressResolverGroupMetrics

`reactor-netty-http`
- reactor.netty.http.client.AbstractHttpClientMetricsHandler
- reactor.netty.http.client.ContextAwareHttpClientMetricsHandler
- reactor.netty.http.server.AbstractHttpServerMetricsHandler
- reactor.netty.http.server.ContextAwareHttpServerMetricsHandler

**Comment by ChristianLMI** [comment]
I created a PR. However now I need to figure out how to get an approval for the CLA.
