### ISSUE TITLE
Default WebClient doesn't re-use connections

### ISSUE THREAD

**Issue by tsgautier** [reactor/reactor-netty#219]
### Expected behavior
The same WebClient created with a base url should default to using a connection pool and re-use connections

### Actual behavior
The WebClient does not re-use existing connections but closes them instead

### Steps to reproduce
**build.gradle**
```
buildscript {
    ext {
        springBootVersion = '2.0.0.M6'

        junitPlatformVersion = '1.0.0'
        junitJupiterVersion = '5.0.0'
    }
    repositories {
        mavenCentral()
        maven { url "https://repo.spring.io/snapshot" }
        maven { url "https://repo.spring.io/milestone" }
    }
    dependencies {
        classpath group: 'org.springframework.boot', name: 'spring-boot-gradle-plugin', version: springBootVersion
        classpath group: 'org.junit.platform', name: 'junit-platform-gradle-plugin', version: junitPlatformVersion
    }
}

apply plugin: 'java'
apply plugin: 'org.springframework.boot'
apply plugin: 'io.spring.dependency-management'
apply plugin: 'org.junit.platform.gradle.plugin'

sourceCompatibility = 1.8

repositories {
    mavenCentral()
    maven { url "https://repo.spring.io/snapshot" }
    maven { url "https://repo.spring.io/milestone" }
}

dependencies {
    compile('org.springframework.boot:spring-boot-starter-webflux')

    testCompile("org.springframework.boot:spring-boot-starter-test") {
        exclude group: 'junit', module: 'junit'
    }

    testCompile group: 'org.junit.jupiter', name: 'junit-jupiter-api', version: junitJupiterVersion
    testRuntime group: 'org.junit.jupiter', name: 'junit-jupiter-engine', version: junitJupiterVersion

}
```

**src/test/java/demo/ReactorTests.java**
```
package demo;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.junit.jupiter.api.BeforeEach;

import org.springframework.web.reactive.function.client.WebClient;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.ComponentScan;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.context.SpringBootTest.WebEnvironment;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit.jupiter.SpringExtension;

import java.util.concurrent.atomic.AtomicInteger;
import reactor.core.publisher.Mono;

import static org.assertj.core.api.Assertions.assertThat;

@SpringBootTest(webEnvironment=WebEnvironment.DEFINED_PORT)
@ContextConfiguration
@ExtendWith(SpringExtension.class)
public class ReactorTests {
  static AtomicInteger counter = new AtomicInteger();

  Mono<Boolean> get(WebClient c) {
      return c.get().uri("/test").exchange().flatMap(r -> r.bodyToMono(Void.class)).then(Mono.just(true));
  }

  @Test
  public void testConnections() throws Exception {
      WebClient c = WebClient.create("http://localhost:8080");

      get(c)
      .then(get(c))
      .then(get(c))
      .then(get(c))
      .then(get(c))
      .block();

      assertThat(counter.get()).isEqualTo(5);
  }

  @SpringBootApplication
  @RestController
  static class Controller {
      @GetMapping("/test")
      String test() {
          counter.getAndIncrement();
          return "ok";
      }
  }
}
```

### Reactor Netty version
0.7.1.RELEASE
### JVM version (e.g. `java -version`)
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

### OS version (e.g. `uname -a`)
Darwin tgautier-Mac 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64

**Comment by tsgautier** [comment]
In my tests, changing r.bodyToMono(Void.class) to r.bodyToMono(String.class) seems to have an effect on how many connections are used. 

In the former, no connections are re-used.

In the latter, I get two connections, one with two requests, and the other with three.  That could be a timing thing perhaps.  

The fact is that r.bodyToMono(Void.class) does not seem to work.  And the docs explicitly say to use it if you are not interested in the body to ensure that the body memory does not leak.

**Comment by violetagg** [comment]
Hi,

When you need to report an issue with Spring Framework you should do it here
https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss

However here is the change that introduces `bodyTo**` with `Void`. It is stated that the connection will be closed instead of consuming the whole response body.
https://github.com/spring-projects/spring-framework/commit/126ac849e5592f65d742d1f23bf891e1a115af01

Regards,
Violeta

**Comment by tsgautier** [comment]
Violeta,

Thank you for digging that commit up.  It explains the behavior I am seeing.  And with that commit message I understand now why the behavior is implemented as it is.  I think at this point it's a docs bug.  I have filed it in the appropriate place per your suggestion at https://jira.spring.io/browse/SPR-16200.

I think you may close this issue.  

Thanks,
Taylor
