### ISSUE TITLE
Support X-Forwarded-* headers

### ISSUE THREAD

**Issue by bclozel** [reactor/reactor-netty#220]
When an application sits behind an HTTP proxy terminating the TLS connection, the proxy sets `X-Forwarded-*` to tell the server about the original request: host, port, and protocol information.

Most servers (Tomcat, Undertow and Jetty) deal with that in their own codebase since it involves wrapping/changing the request information at a low level.

Could Reactor Netty support an HttpServerOption for enabling such a feature?

This should be disabled by default, as this could lead to attackers spoofing their peer address if there is no proxy in front of the application or if the proxy does not clean those incoming headers.

**Comment by nebhale** [comment]
I wonder if it should also follow some of the Tomcat conventions (not sure about how the other two act) regarding [internal proxies](https://tomcat.apache.org/tomcat-8.5-doc/api/org/apache/catalina/valves/RemoteIpValve.html).

**Comment by violetagg** [comment]
Fixed by PR #249 
Extended support will be covered by #259
