### ISSUE TITLE
HttpClient doesn't follow the "log or rethrow" best practice

### ISSUE THREAD

**Issue by ptrts** [reactor/reactor-netty#2224]
When requesting with HttpClient, if the server closes the connection before sending a response, then both a warning is logged and an error is issued

## Expected Behavior

It should either catch the error and log it without passing it along or pass it along logging it as TRACE, DEBUG or without logging it whatsoever

## Actual Behavior

It both logs a warning and passes the error along

## Steps to Reproduce

Clone this
https://github.com/ptrts/reactor-netty-http-bug

Launch app.Main.main()

You'll see logging both from reactor-netty-http and from app.Main having caught the error

## Environment

io.projectreactor.netty:reactor-netty:1.0.19

**Comment by violetagg** [comment]
@ptrts Critical exceptions are intentionally logged with `WARN`. This is because if you decide not to handle the errors you will still be able to see the warning and take some actions, on the other hand if you decide to handle the errors you can always set your logging level to `ERROR`.

**Comment by violetagg** [comment]
@ptrts Critical exceptions are intentionally logged with `WARN`. This is because if you decide not to handle the errors you will still be able to see the warning and take some actions, on the other hand if you decide to handle the errors you can always set your logging level to `ERROR`.
