### ISSUE TITLE
HttpClient's logging depends on ContextHandler's logger

### ISSUE THREAD

**Issue by unlimitedsola** [reactor/reactor-netty#227]
discussed in: https://github.com/spring-projects/spring-boot/issues/11119

**Comment by smaldini** [comment]
Tracking in 0.8 with API refactor

**Comment by smaldini** [comment]
we know have an explicit wiretap() API to enable it separately from logging level in 0.8

**Comment by violetagg** [comment]
Fixed by #262 
a new API is introduced in 0.8
`(Tcp|Udp|Http)Client/Server#wiretap`
