### ISSUE TITLE
NettyContext#addDecoder recursion

### ISSUE THREAD

**Issue by rstoyanchev** [reactor/reactor-netty#23]
The default method implementation of [NettyContext#addDecoder(String, ChannelHandler)](https://github.com/reactor/reactor-netty/blob/217c352aa926975f10aea1b2b7ada1c3889c3af1/src/main/java/reactor/ipc/netty/NettyContext.java#L87) recurses back to itself.

**Comment by simonbasle** [comment]
The code in `ChannelOperations` could be made into a static helper and used as the default body.
