### ISSUE TITLE
Some http server reactor metrics are not pegging

### ISSUE THREAD

**Issue by santoshpanigrahi1990** [reactor/reactor-netty#2305]
I am using Spring boot and reactor netty in my spring boot app. I tried to capture reactor netty metrics. I sent request to my application. After sending requests, some reactor metrics were pegging(e.g.- reactor_netty_http_server_connections_total ). 

But  I unable to see below metrics. 
- **reactor.netty.http.server.data.received**
- **reactor.netty.http.server.data.sent**
- **reactor.netty.http.server.errors**
- **reactor.netty.http.server.data.received.time**
- **reactor.netty.http.server.data.sent.time**
- **reactor.netty.http.server.response.time**

I have shared the code snippet I have used. Please verify the code snippet if I had done anything wrong.

**Code Snippet**
---------------
```
LoopResources resource = LoopResources.create("test-h2c");        
ReactorResourceFactory reactorResourceFactory = new ReactorResourceFactory();        
reactorResourceFactory.setLoopResources(resource);        
reactorResourceFactory.setUseGlobalResources(false);        
factory.setResourceFactory(reactorResourceFactory);        

// Set Port and enable HTTP/2        
Http2 h2 = new Http2();        
h2.setEnabled(true);        
factory.setPort(httpPort);        
factory.setHttp2(h2);        

if (Epoll.isAvailable()) {        
    EventLoopGroup boss = new EpollEventLoopGroup(Runtime.getRuntime().availableProcessors());        
    factory.addServerCustomizers(httpServer -> httpServer.runOn(boss));        

    factory.addServerCustomizers(httpServer ->        
            httpServer.option(ChannelOption.SO_KEEPALIVE, true)        
                    .option(EpollChannelOption.TCP_KEEPIDLE, keepAliveIdleTime)        
                    .option(EpollChannelOption.TCP_KEEPCNT, keepAliveProbe)        
                    .option(EpollChannelOption.TCP_KEEPINTVL, keepAliveInterval));        

}        
```

// HTTP 2.0 settings        
```
Consumer<Builder> h2Settings = s -> s.maxConcurrentStreams(settingsMaxConcurrentStreams);        
factory.addServerCustomizers(httpServer -> httpServer.http2Settings(h2Settings));        
       
        
factory.addServerCustomizers(httpServer -> 		
httpServer.metrics(true, s -> s)		
		.option(ChannelOption.SO_KEEPALIVE, true).option(EpollChannelOption.TCP_KEEPIDLE, keepAliveIdleTime)		
		.option(EpollChannelOption.TCP_KEEPCNT, keepAliveProbe)		
		.option(EpollChannelOption.TCP_KEEPINTVL, keepAliveInterval));		
        
factory.addServerCustomizers(httpServer -> httpServer.idleTimeout(Duration.ofMillis(idleTimeout)));        
factory.addServerCustomizers(builder -> builder.protocol(HttpProtocol.H2C, HttpProtocol.HTTP11));        
factory.setShutdown(Shutdown.GRACEFUL);        
```

Thanks in advance.

<br class="Apple-interchange-newline">
</body>
</html>

<br class="Apple-interchange-newline">
</body>
</html>

## Your Environment

* Reactor version(s) used:
* netty version:1.0.16
* Java -version: 17.0.3.1
* Spring boot version: 2.6.7

**Comment by violetagg** [comment]
@santoshpanigrahi1990 You need to update to at least version 1.0.17 where we added metrics for HTTP/2. See the release notes https://github.com/reactor/reactor-netty/releases/tag/v1.0.17

**Comment by violetagg** [comment]
@santoshpanigrahi1990 I'm closing this one. We can reopen it if it is needed.

**Comment by santoshpanigrahi1990** [comment]
Thank you. 
Metrics are coming in 1.0.17 version.
