### ISSUE TITLE
HttpServerResponse.send(publisher).then() does not propagate error signals

### ISSUE THREAD

**Issue by rstoyanchev** [reactor/reactor-netty#231]
### Expected behavior
When writing with `HttpServerResponse.send(publisher).then()`, if the writing `Publisher` completes with an error, the error should be observed from the subscriber side.

### Actual behavior
The subscriber receives onComplete instead of onError.

### Steps to reproduce
I observed this while experimenting with the sample for [this issue](https://jira.spring.io/browse/SPR-16051). The writing to the response is in the [ReactorServerHttpResponse](https://github.com/spring-projects/spring-framework/blob/7368f58518303a1fc0b7c64e4acb3d249b8f7cc5/spring-web/src/main/java/org/springframework/http/server/reactive/ReactorServerHttpResponse.java#L76). Only onComplete flows out of that.

### Reactor Netty version
0.7.2

### JVM version (e.g. `java -version`)
1.8

### OS version (e.g. `uname -a`)
Linux/Ubuntu

**Comment by rstoyanchev** [comment]
Could we prioritize this issue to be addressed soon, i.e. leaving time before 0.7.3? The actual scenario I'm interested in testing, based on [SPR-16051](https://jira.spring.io/browse/SPR-16051), is the effect of propagating a write publisher error after the response has been committed, but the issue here gets in the way.

**Comment by violetagg** [comment]
I'm on it

**Comment by rstoyanchev** [comment]
Fix confirmed.
