### ISSUE TITLE
How to debug http request & responses with body in a human readable way

### ISSUE THREAD

**Issue by thekalinga** [reactor/reactor-netty#233]
Currently if we try to log the request & response, the libray logs the request & response bodies in a machine readable way (I'm not sure what the format is). I am not sure which library can be used to view these logged requests & responses in a human readable way. Would be great if the request can be logged in a human readable way directly instead of using special tools.

### Expected behavior
Ability to view http request & response in a readable & developer friendly way

### Actual behavior
Some hex structure (not sure what this format is) is getting logged instead

```
         +-------------------------------------------------+
         |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
+--------+-------------------------------------------------+----------------+
|00000000| 47 45 54 20 2f 53 65 61 72 63 68 5f 47 43 2e 61 |GET /Search_GC.a|
|00000010| 73 70 78 20 48 54 54 50 2f 31 2e 31 0d 0a 75 73 |spx HTTP/1.1..us|
|00000020| 65 72 2d 61 67 65 6e 74 3a 20 52 65 61 63 74 6f |er-agent: Reacto|
|00000030| 72 4e 65 74 74 79 2f 30 2e 37 2e 32 2e 52 45 4c |rNetty/0.7.2.REL|
|00000040| 45 41 53 45 0d 0a 68 6f 73 74 3a 20 63 65 6f 6b |EASE..host: ceok|
|00000050| 61 72 6e 61 74 61 6b 61 2e 6b 61 72 2e 6e 69 63 |arnataka.kar.nic|
|00000060| 2e 69 6e 0d 0a 61 63 63 65 70 74 3a 20 2a 2f 2a |.in..accept: */*|
|00000070| 0d 0a 61 63 63 65 70 74 2d 65 6e 63 6f 64 69 6e |..accept-encodin|
|00000080| 67 3a 20 67 7a 69 70 0d 0a 63 6f 6e 74 65 6e 74 |g: gzip..content|
|00000090| 2d 6c 65 6e 67 74 68 3a 20 30 0d 0a 0d 0a       |-length: 0....  |
+--------+-------------------------------------------------+----------------+
```

### Steps to reproduce
Enable debugging for package reactor.ipc.netty

### Reactor Netty version
0.7.2.RELEASE

### JVM version (e.g. `java -version`)
JRE: 1.8.0_152-release-1024-b6 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.4.0-34-generic

### OS version (e.g. `uname -a`)
Linux 4.4.0-34-generic #53~14.04.1-Ubuntu SMP x86_64 x86_64 x86_64 GNU/Linux

**Comment by asarkar** [comment]
@thekalinga FWIW, if it helps, I'm doing the following:

```
WebClient.builder()
.filter((request, next) -> {
    log.info(">> {} {}", request.method(), request.url());
    logHeadersIfDebugEnabled(request.headers(), true);

    return next.exchange(request)
      .doOnNext(r -> {
          log.info("<< {} {}", r.statusCode().value(), r.statusCode().getReasonPhrase());
          logHeadersIfDebugEnabled(r.headers().asHttpHeaders(), false);
      });
})
```

Put this in a `WebClientFactory`.

**Comment by rstoyanchev** [comment]
It's not accurate to say the output is not human readable. You can clearly see the text in the right-hand column. That said I agree there should be an intermediate level of logging, that doesn't show individual bytes, is easier to read, and more compact. The current output is very verbose and quickly fills up log files, so it should be left as the most detailed level.

**Comment by vguna** [comment]
Although it helps when debugging in detail like encoded/not visible characters, but to be honest: most of the time you don't need such details :). The simple (e.g. JSON) payload is enough most of the time. It's also cumbersome to copy&paste from such output. So I would love to have an option to simply switch.

@thekalinga : this does not log the body, right?

**Comment by thekalinga** [comment]
@vguna It does log everything as far as I remmeber

**Comment by bclozel** [comment]
I'd like to turn this "question" issue into an enhancement request.

I really like this detailed format, and I think it's the best for debugging HTTP issues. But when looking at multiple requests from the same `HttpClient`, it feels like this gives too much information and that we should have an intermediate level. [Other people on StackOverflow are discussing this issue](https://stackoverflow.com/questions/47596571/readable-debug-logging-for-http-requests-with-spring-webclient).

What about the following:
* keep this detailed information at the `TRACE` level
* have a `DEBUG` level logging feature that writes less detailed information

If we decide to go ahead with this, there are still a few questions to answer:
* how should we keep track of things in case of concurrent requests?
* raw HTTP info and headers should be displayed, but what about large/streaming messages?
* should there be a best-effort solution for formatting payloads (such as JSON content)?

**Comment by edeandrea** [comment]
Just to add on here as well. This type of debugging/logging is also really helpful when writing tests. For example, when using Spring's `MockMvc` it can print out the contents of the request/response so that its very easy to find what is causing test failures. With `WebClient` it doesn't seem so trivial to get similar output (maybe its there and I just don't know where it is - I'm no reactive expert by any means).

**Comment by marchev** [comment]
Are there any plans for this enhancement to be implemented?

**Comment by violetagg** [comment]
@marchev It is scheduled for 0.8.x but for sure not for 0.8.4. Are you interested in providing a PR with that functionality?

**Comment by dharezlak** [comment]
For reactor-netty 0.8.3 the hex structure is no longer printed when I set the following in my spring boot application (only URL and headers are printed):
```
logging.level.reactor.netty = trace
```
Is it possible to still see the request and response bodies somehow?

**Comment by violetagg** [comment]
@dharezlak Use the code below

```
@Component
public class MyNettyWebServerCustomizer
        implements WebServerFactoryCustomizer<NettyReactiveWebServerFactory> {
    @Override
    public void customize(NettyReactiveWebServerFactory factory) {
        factory.addServerCustomizers(httpServer -> httpServer.wiretap(true));
    }
}
```

**Comment by developerworks** [comment]
set `logging.level.reactor.netty=trace`
and add above `NettyWebServerCustomizer` as a bean, just print the parts of headers like this in the console:

```
         +-------------------------------------------------+
         |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
+--------+-------------------------------------------------+----------------+
|00000000| 48 54 54 50 2f 31 2e 31 20 32 30 30 20 4f 4b 0d |HTTP/1.1 200 OK.|
|00000010| 0a 43 6f 6e 74 65 6e 74 2d 54 79 70 65 3a 20 61 |.Content-Type: a|
|00000020| 70 70 6c 69 63 61 74 69 6f 6e 2f 6a 73 6f 6e 3b |pplication/json;|
|00000030| 63 68 61 72 73 65 74 3d 55 54 46 2d 38 0d 0a 43 |charset=UTF-8..C|
|00000040| 6f 6e 74 65 6e 74 2d 4c 65 6e 67 74 68 3a 20 31 |ontent-Length: 1|
|00000050| 35 32 37 0d 0a 0d 0a                            |527....         |
+--------+-------------------------------------------------+----------------+
```

How to print full headers ?

**Comment by violetagg** [comment]
@developerworks These are all the headers. They end with `0d 0a 0d 0a` as by spec.

**Comment by TheConen** [comment]
How do I use this new human readable logging? I'm using Spring with WebFlux and setting 

`logging.level.reactor.netty.http.client.HttpClient =  DEBUG`

in my `application.properties` gives me the Hex debug with `wiretap(true)` on my `WebClient`. What do I need to change to get the new human readable logging?

**Comment by violetagg** [comment]
@TheConen You can use the code below. I'm in a process of adding an example to the reference documentation #1397

`wiretap(java.lang.String category, io.netty.handler.logging.LogLevel level, AdvancedByteBufFormat format)`

**Comment by TheConen** [comment]
Thank you, I got this to work with using
```wiretap("reactor.netty.http.client.HttpClient", LogLevel.DEBUG, AdvancedByteBufFormat.TEXTUAL)```

Full code example in case anyone else finds this and needs it:

```
private WebClient webClient = WebClient.builder()
            .clientConnector(new ReactorClientHttpConnector(
                    HttpClient.create().wiretap("reactor.netty.http.client.HttpClient", LogLevel.DEBUG, AdvancedByteBufFormat.TEXTUAL)
            ))
            .baseUrl("http://example.com")
            .build();
```
In `application.properties`:
`logging.level.reactor.netty.http.client.HttpClient =  DEBUG`

**Comment by violetagg** [comment]
@TheConen The first argument is any logger that is convenient to you it is not needed to be exactly `reactor.netty.http.client.HttpClient`

**Comment by lackovic** [comment]
> @TheConen The first argument is any logger that is convenient to you it is not needed to be exactly `reactor.netty.http.client.HttpClient`

Can you make some examples? I tried with `org.apache.logging.log4j.Logger` and `java.util.logging.Logger` but neither of them produced any output.

**Comment by TheConen** [comment]
The way I understood it is that it is supposed to be the category/package where you want to enable logs - I wanted to enable logs for the HttpClient, so it is `reactor.netty.http.client.HttpClient`. But honestly, I have no idea, I did some trial and error, found something that worked for me and was happy with it. I was very confused about that, too, because the documentation doesn't mention what a `category` is supposed to be. 

The [Javadoc](https://projectreactor.io/docs/netty/release/api/reactor/netty/transport/Transport.html#wiretap-java.lang.String-io.netty.handler.logging.LogLevel-reactor.netty.transport.logging.AdvancedByteBufFormat-) calls it `category`, while the [documentation](https://projectreactor.io/docs/netty/snapshot/reference/index.html#_wire_logger_2) calls it `logger-name`. Since neither of them explains what it is supposed to be, at first I thought it can be anything you choose (basically, choosing a name like `MyLogger`), but that's obviously not the case and what you choose there seems to be directly correlated to the package that will be logged.

**Comment by violetagg** [comment]
@lackovic @TheConen
Let's take the example from the documentation
https://projectreactor.io/docs/netty/snapshot/reference/index.html#_wire_logger_2

The code is here 
https://github.com/reactor/reactor-netty/blob/8a87ab297166d03cd1ab492842f11b421589f106/reactor-netty-examples/src/main/java/reactor/netty/examples/documentation/http/client/wiretap/custom/Application.java#L27

If I configure here https://github.com/reactor/reactor-netty/blob/master/reactor-netty-examples/src/main/resources/logback.xml the log level to DEBUG for this particular logger `logger-name`

`<logger name="logger-name" level="DEBUG" />`

Then I will be able to see the following when running the example

```
...
19:22:02.327 [reactor-http-nio-2] DEBUG logger-name - [id: 0x8f749251, L:/XXX - R:example.com/93.184.216.34:80] WRITE: 110B GET / HTTP/1.1
user-agent: ReactorNetty/1.0.4-SNAPSHOT
host: example.com
accept: */*
content-length: 0
...
```

**Comment by TheConen** [comment]
I'm using Spring Boot and Lombok, so I don't have a XML configuration where I define logger names. For me it came down to `category` / `logger-name` being equal to the package name of the HttpClient if I want to log HttpClient stuff.

**Comment by violetagg** [comment]
@TheConen for Spring Boot you have `logging.level.logger-name=DEBUG` in your `application.properties file.

**Comment by TheConen** [comment]
Ah, I see - I was using 
`logging.level.reactor.netty.http.client.HttpClient =  DEBUG`
and 
`.wiretap("reactor.netty.http.client.HttpClient", LogLevel.DEBUG, AdvancedByteBufFormat.TEXTUAL);`

So if I were to use
`logging.level.mylogger =  DEBUG`
and 
`.wiretap("mylogger", LogLevel.DEBUG, AdvancedByteBufFormat.TEXTUAL);`

I would get the exact same result - a log of all HTTP requests made on that HttpClient?

@lackovic Does that help you?

**Comment by violetagg** [comment]
> I would get the exact same result - a log of all HTTP requests made on that HttpClient?

yep

**Comment by TheConen** [comment]
Thanks a lot, now I actually understand what I did - seems like I initially got it to work by chance and trial and error.

**Comment by lackovic** [comment]
@TheConen @violetagg that was helpful, thank you both (I am also using _Spring Boot_ and _Lombok_).

**Comment by dnedealcov** [comment]
I'm struggling to get a whole body from the requests/responses since earlier netty.HttpClient versions. 

The below indeed return a body and some details. 
```
return HttpClient.create()
        .wiretap("client-logger", LogLevel.INFO, AdvancedByteBufFormat.TEXTUAL);
```

But for a reason the logger splits in to parts large bodies. Is there a way to set the logger to return the whole body? 

Thank you!

**Comment by violetagg** [comment]
> I'm struggling to get a whole body from the requests/responses since earlier netty.HttpClient versions.
> 
> The below indeed return a body and some details.
> 
> ```
> return HttpClient.create()
>         .wiretap("client-logger", LogLevel.INFO, AdvancedByteBufFormat.TEXTUAL);
> ```
> 
> But for a reason the logger splits in to parts large bodies. Is there a way to set the logger to return the whole body?
> 
> Thank you!

This feature is `wire` logger because it logs immediately the packages received from the wire, it is not meant to collect and store the data in the memory and then to log it.

**Comment by dnedealcov** [comment]
> > I'm struggling to get a whole body from the requests/responses since earlier netty.HttpClient versions.
> > The below indeed return a body and some details.
> > ```
> > return HttpClient.create()
> >         .wiretap("client-logger", LogLevel.INFO, AdvancedByteBufFormat.TEXTUAL);
> > ```
> > 
> > 
> > But for a reason the logger splits in to parts large bodies. Is there a way to set the logger to return the whole body?
> > Thank you!
> 
> @dnedealcov This feature is `wire` logger because it logs immediately the packages received from the wire, it is not meant to collect and store the data in the memory and then to log it.

This is strange because in earlier builds (before 1.0.3) you could provide your own logger class and override the format() method, to have your own formatted output. But, for a reason I do not understand you could format only the first part for the message received, while the second was formatted by the default logger. 
What I'm trying to say is that you could listen to the wire, gather the data and output it as you wish.

**Comment by dnedealcov** [comment]
And one more thing, HttpClient uses a Logger class of its own, which uses a ByteBuf (buffer), so why not have an Api to modify the buffers size/capacity?

**Comment by violetagg** [comment]
> This is strange because in earlier builds (before 1.0.3) you could provide your own logger class and override the format() method, to have your own formatted output. But, for a reason I do not understand you could format only the first part for the message received, while the second was formatted by the default logger.
> What I'm trying to say is that you could listen to the wire, gather the data and output it as you wish.

@dnedealcov Which release do you mean? - 0.9.x releases? or 1.0.0-1.0.2 releases?
Also did you use `wiretap` or you were adding your own `LoggingHandler`?

If you were adding your own `LoggingHandler` then you can still do that using `doOnChannelInit` callback.

**Comment by dnedealcov** [comment]
0.9.7.RELEASE to be exact. 

Client: 
`public HttpClient httpClient() {
    return HttpClient.create()
        .tcpConfiguration(
            tc -> tc.bootstrap(
                b -> BootstrapHandlers.updateLogSupport(b, new BPSHttpLogger(HttpClient.class))));
  }`

Logger: 
`public class MyHttpLogger extends LoggingHandler {

  public MyHttpLogger(Class<?> clazz) {
    super(clazz);
  }

  @Override
  protected String format(ChannelHandlerContext ctx, String event, Object arg) {
    if (arg instanceof ByteBuf) {
      ByteBuf msg = (ByteBuf) arg;
      return decode(
          msg, msg.readerIndex(), msg.readableBytes(), defaultCharset());
    }
    return super.format(ctx, event, arg);
  }`

This setup results in one part of the message goes through my format method and the other through the default .log();

**Comment by violetagg** [comment]
@dnedealcov Yep definitely you have to use `doOnChannelInit` callback (The code below is adding a handler to the bootstrap). 
https://projectreactor.io/docs/netty/release/api/reactor/netty/tcp/TcpClient.html#bootstrap-java.util.function.Function-

```
.tcpConfiguration(
tc -> tc.bootstrap(
b -> BootstrapHandlers.updateLogSupport(b, new MyHttpLogger(HttpClient.class))));
}
```

so you have to do 

```
doOnChannelInit((observer, channel, address) -> channel.addFirst(...))
```

**Comment by guicalman** [comment]
@dnedealcov Thank you so much for this answer, I am trying to add a custom LoggingHandler, but I couldn´t find the way of using the doOnChannelInit callback, could you please help me, giving an example of the syntax to replace the deprecated code show bellow.

`HttpClient httpClient = HttpClient
                .create()
                .tcpConfiguration(
                        tc -> tc.bootstrap(
                                b -> BootstrapHandlers.updateLogSupport(b, new CustomNettyLogger(HttpClient.class))));
`
Thank you so much for your help

> @dnedealcov Yep definitely you have to use `doOnChannelInit` callback (The code below is adding a handler to the bootstrap).
> https://projectreactor.io/docs/netty/release/api/reactor/netty/tcp/TcpClient.html#bootstrap-java.util.function.Function-
> 
> ```
> .tcpConfiguration(
> tc -> tc.bootstrap(
> b -> BootstrapHandlers.updateLogSupport(b, new MyHttpLogger(HttpClient.class))));
> }
> ```
> 
> so you have to do
> 
> ```
> doOnChannelInit((observer, channel, address) -> channel.addFirst(...))
> ```

**Comment by violetagg** [comment]
@guicalman With the example below

```
@Test
void test() {
	HttpClient.create()
		.doOnChannelInit((observer, channel, address) ->
				channel.pipeline()
					.addFirst(new LoggingHandler("reactor.netty.mylogger")))
		.get()
		.uri("http://example.com")
		.responseContent()
		.aggregate()
		.asString()
		.block();
}
```

I receive such log (the logger is the one that I specified above `reactor.netty.mylogger`)

```
08:42:37.811 [reactor-http-nio-2] DEBUG reactor.netty.mylogger - [id: 0xe48a5e55, L:/XXX:64122 - R:example.com/93.184.216.34:80] WRITE: 99B
         +-------------------------------------------------+
         |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
+--------+-------------------------------------------------+----------------+
|00000000| 47 45 54 20 2f 20 48 54 54 50 2f 31 2e 31 0d 0a |GET / HTTP/1.1..|
```

**Comment by asarkar** [comment]
Something tells me that so many comments on a closed ticket = documentation needs update.

**Comment by violetagg** [comment]
@asarkar We love PRs ;)

**Comment by guicalman** [comment]
@violetagg Thank you so much for the example, it worked perfectly fine for me!!!

> @guicalman With the example below
> 
> ```
> @Test
> void test() {
> 	HttpClient.create()
> 		.doOnChannelInit((observer, channel, address) ->
> 				channel.pipeline()
> 					.addFirst(new LoggingHandler("reactor.netty.mylogger")))
> 		.get()
> 		.uri("http://example.com")
> 		.responseContent()
> 		.aggregate()
> 		.asString()
> 		.block();
> }
> ```
> 
> I receive such log (the logger is the one that I specified above `reactor.netty.mylogger`)
> 
> ```
> 08:42:37.811 [reactor-http-nio-2] DEBUG reactor.netty.mylogger - [id: 0xe48a5e55, L:/XXX:64122 - R:example.com/93.184.216.34:80] WRITE: 99B
>          +-------------------------------------------------+
>          |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
> +--------+-------------------------------------------------+----------------+
> |00000000| 47 45 54 20 2f 20 48 54 54 50 2f 31 2e 31 0d 0a |GET / HTTP/1.1..|
> ```

**Comment by guicalman** [comment]
@violetagg I have an additional question. Now I am getting in the logs the jsons as Content-Encoding: gzip. Is ther a way to define de expected content encoding type, at the moment of creating httpClient?

> @guicalman With the example below
> 
> ```
> @Test
> void test() {
> 	HttpClient.create()
> 		.doOnChannelInit((observer, channel, address) ->
> 				channel.pipeline()
> 					.addFirst(new LoggingHandler("reactor.netty.mylogger")))
> 		.get()
> 		.uri("http://example.com")
> 		.responseContent()
> 		.aggregate()
> 		.asString()
> 		.block();
> }
> ```
> 
> I receive such log (the logger is the one that I specified above `reactor.netty.mylogger`)
> 
> ```
> 08:42:37.811 [reactor-http-nio-2] DEBUG reactor.netty.mylogger - [id: 0xe48a5e55, L:/XXX:64122 - R:example.com/93.184.216.34:80] WRITE: 99B
>          +-------------------------------------------------+
>          |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
> +--------+-------------------------------------------------+----------------+
> |00000000| 47 45 54 20 2f 20 48 54 54 50 2f 31 2e 31 0d 0a |GET / HTTP/1.1..|
> ```

**Comment by violetagg** [comment]
@guicalman Please ask your questions on [Gitter](https://gitter.im/reactor/reactor-netty)

**Comment by violetagg** [comment]
I updated the documentation with various lifecycle callbacks supported by the servers/clients #1481 
https://projectreactor.io/docs/netty/snapshot/reference/index.html#_lifecycle_callbacks_4

For any further questions please use [Gitter](https://gitter.im/reactor/reactor-netty)
Or a clarification in the documentation is needed please open another issue.

**Comment by dnedealcov** [comment]
Hi @violetagg , 

```
HttpClient.create()
		.doOnChannelInit((observer, channel, address) ->
				channel.pipeline()
					.addFirst(new LoggingHandler("reactor.netty.mylogger")))
```

Maybe I'm missing something, but the above does not work for me, as if the logger is not registered in the pipeline?  

`29-01-2021 09:51:22.754 [reactor-http-nio-2] DEBUG r.n.http.client.HttpClientOperations.debug` and not .mylogger

**Comment by violetagg** [comment]
@dnedealcov Please ask your questions on [Gitter](https://gitter.im/reactor/reactor-netty)

**Comment by jeff-miller** [comment]
Why are wiretap log values masked as "<filtered>"? How to unmask? For example:
user-agent: <filtered>
host: <filtered>

**Comment by jeff-miller** [comment]
github stripped out the important part of my comment. Trying again.

Why are wiretap log values masked as "`<filtered>`"? How to unmask? For example:
user-agent: `<filtered>`
host: `<filtered>`

**Comment by violetagg** [comment]
@jeff-miller You need configuration on the server/client to disable the filtering. See

https://projectreactor.io/docs/netty/release/api/reactor/netty/http/client/HttpClient.html#httpMessageLogFactory-reactor.netty.http.logging.HttpMessageLogFactory-
https://projectreactor.io/docs/netty/release/api/reactor/netty/http/server/HttpServer.html#httpMessageLogFactory-reactor.netty.http.logging.HttpMessageLogFactory-

**Comment by jeff-miller** [comment]
Thanks for the quick response. You are indicating that I need to supply a custom implementation of HttpMessageLogFactory? I've seen no mention of this in the many explanations of wiretap. I thought that all was need was:
wiretap("reactor.netty.http.client.HttpClient", LogLevel.DEBUG, AdvancedByteBufFormat.TEXTUAL) and reactor.netty.http.client.HttpClient=DEBUG

**Comment by violetagg** [comment]
@jeff-miller Are you asking specifically for wiretap or regular debug logs?

Wiretap is only for network debugging purposes and is disabled by default, it is not filtered. It is not recommended to be used in production exactly because it is not filtered.

Regular logs are filtered and if one decides to disable the filtering he/she needs to provide a custom `HttpMessageLogFactory`.

**Comment by jeff-miller** [comment]
I am attempting to use wiretap for debugging purposes while developing a feature in an app that uses WebClient. I don't intend to use it for production. I've found a few explanations for enabling wiretap but all of them result in filtered output. Some of the comments here and other places describe seeing the unfiltered output without any mention of custom HttpMessageLogFactory. I was hoping there was a simple way for the non netty expert to view request/response data.

**Comment by violetagg** [comment]
@jeff-miller can you share a snippet here? Or better continue on [Gitter](https://gitter.im/reactor/reactor-netty)

**Comment by jeff-miller** [comment]
I am not permitted to share any company source code. My attempt looks similar to the following from stackoverflow
[https://stackoverflow.com/a/65959769/912813](https://stackoverflow.com/a/65959769/912813)

```
HttpClient httpClient = HttpClient.create()
      .wiretap("reactor.netty.http.client.HttpClient", LogLevel.DEBUG, AdvancedByteBufFormat.TEXTUAL);
ClientHttpConnector conn = new ReactorClientHttpConnector(httpClient);   

WebClient client =  WebClient.builder()
            .clientConnector(conn)
            .build();
```

**Comment by violetagg** [comment]
Can you at least share the log so that I can tell whether it is wiretap or regular log? The point is that you use for wiretap `reactor.netty.http.client.HttpClient` which is one of our loggers and it might be that you are mixing these two.

**Comment by jeff-miller** [comment]
Security policies at my employer are very strict so I can't share the log output. 

The output looks similar to the stackoverflow example except the values are `<filtered>`. For example:
Host: `<filtered>`
User-Agent: `<filtered>`
Content-Type: `<filtered>`

The logger is log4j2 with reactor.netty.http.client set for DEBUG. If I set reactor.netty.http.client.HttpClient for DEBUG no output is generated.

**Comment by jeff-miller** [comment]
wiretap is false, nothing configured for log4j2 for reactor.netty.http.client.HttpClient, output has no debug logging
wiretap is false, log4j2 configured reactor.netty.http.client.HttpClient DEBUG, output has no debug logging
wiretap is true with logger name of zzz, log4j2 configured zzz for DEBUG, output has no debug logging

The only way to get debug output is configure log4j2 **_reactor.netty.http.client_** for DEBUG 
configuring log4j2 reactor.netty.http.client.**HttpClient** has no effect

I've tried 2 of the wiretap methods:
wiretap(true)
wiretap("reactor.netty.http.client.HttpClient", LogLevel.DEBUG, AdvancedByteBufFormat.TEXTUAL);

**Comment by violetagg** [comment]
Run this https://github.com/reactor/reactor-netty/blob/main/reactor-netty-examples/src/main/java/reactor/netty/examples/documentation/http/client/wiretap/custom/Application.java

enable log level debug for `logger-name` in the https://github.com/reactor/reactor-netty/blob/main/reactor-netty-examples/src/main/resources/logback.xml and run it again

**Comment by jeff-miller** [comment]
Application.java logs as expected as long as the following logger name is used:
wiretap("reactor.netty.http.client.HttpClient", LogLevel.DEBUG, AdvancedByteBufFormat.TEXTUAL);

Other logger names in Application.java do not produce _any_ debug output.

Application.java debug messages are from reactor.netty.http.client.HttpClient
vs.
My Spring Boot application running in Tomcat 10 container, debug messages are from reactor.netty.http.client.HttpClient**Operations**

I tried HttpClientOperations logger name but still had filtered output:
wiretap("reactor.netty.http.client.HttpClient**Operations**", LogLevel.DEBUG, AdvancedByteBufFormat.TEXTUAL);

**Comment by violetagg** [comment]
@jeff-miller Check out this branch https://github.com/reactor/reactor-netty/tree/logger-name-on-debug the only change that I did is in `logback.xml`

`<logger name="logger-name" level="DEBUG" />`

When running `reactor.netty.examples.documentation.http.client.wiretap.custom.Application` you will be able to see logs from `logger-name`

```
22:35:40.079 [reactor-http-nio-2] DEBUG logger-name - [3e8b1ce2-1, L:/IP:52252 - R:example.com:443] WRITE: 110B GET / HTTP/1.1
user-agent: ReactorNetty/1.1.6-SNAPSHOT
host: example.com
accept: */*
content-length: 0
```

**Comment by jeff-miller** [comment]
I was able to get similar result with Application.java but I need to use logger-name in both logback.xml and in 1st parameter to wiretap.

I was not able to reproduce in the web application. The web application always logs HttpClientOperations no matter what is used in wiretap or logback.xml:
16:37:04.303 [reactor-http-nio-3] DEBUG r.n.http.client.HttpClientOperations ...
