### ISSUE TITLE
Client should use GET not CONNECT with proxy when target URI is HTTP

### ISSUE THREAD

**Issue by micw** [reactor/reactor-netty#2349]
## Expected Behavior
When accessing an URI via proxy, the client should use "GET" for HTTP-Targets and CONNECT for HTTPS-Targets.

## Actual Behavior
The Client always uses CONNECT. This is technical valid but breaks things like proxy-side request filtering for Non-HTTP requests.

## Steps to Reproduce

Create a client with http proxy set to localhost:someport. Run netcat (nc -l -p someport). Query a http url through that client. Check what request is issued.

## Your Environment

* Reactor version(s) used: reactor-core-3.4.18, reactor-netty-core-1.0.19

**Comment by violetagg** [comment]
@micw Follow this issue https://github.com/netty/netty/issues/10475 in Netty project.
