### ISSUE TITLE
Revise HttpMetricsHandlerTests#testServerConnectionsRecorder

### ISSUE THREAD

**Issue by violetagg** [reactor/reactor-netty#2368]
This test is flaky and it is observed that it fails from time to time on the CI for all versions 1.0.x, 1.1.x, 2.0.x

**Comment by violetagg** [comment]
failure on 1.0.x publishing job https://github.com/reactor/reactor-netty/runs/7335349635?check_suite_focus=true#step:4:68

**Comment by pderop** [comment]
yes, same error on _1.0.x_, I will fix soon on 1.0.x and then merge to _main_ and _netty5_ branch.
