### ISSUE TITLE
Trace are not being injected in netty error logs

### ISSUE THREAD

**Issue by Jojoooo1** [reactor/reactor-netty#2398]
When an error in thrown the trace are not being injected in netty error logs.

![Screenshot from 2022-07-25 15-04-11](https://user-images.githubusercontent.com/17641873/180783972-023dc91d-3b7c-4be2-bd7c-2d2a6719cb28.png)

## Expected Behavior
Traces should be injected.

## Actual Behavior
Traces are not being injected.

## Your Environment
java: 17
spring-boot: 2.7.2
spring-boot-starter-webflux using reactor netty http 1.0.21
spring-cloud-starter-sleuth: 3.13.3

Also tried using reactor-netty-http-brave but without success.

**Comment by violetagg** [comment]
@Jojoooo1 Do you use Reactor Netty <-> Brave integration (https://github.com/reactor/reactor-netty/tree/1.0.x/reactor-netty-http-brave) or you use Sleuth integration?

**Comment by Jojoooo1** [comment]
@violetagg testei com sleuth e sleuth com reactor netty http brave

**Comment by violetagg** [comment]
> @violetagg testei com sleuth e sleuth com reactor netty http brave

I didn't get that. Can you explain more? If you do not use the Reactor Netty <-> Brave integration but Sleuth implementation then this issue has to be reported to Sleuth.

**Comment by Jojoooo1** [comment]
I thought it could have been used in parallel, just create an issue in sleuth repo, thanks @violetagg!
