### ISSUE TITLE
No way to shut down TcpClient resources

### ISSUE THREAD

**Issue by rstoyanchev** [reactor/reactor-netty#24]
Currently TcpClient is created as follows:
````java
ClientOptions clientOptions = ClientOptions.create();
clientOptions.loopResources(TcpResources.get()).poolResources(TcpResources.get());
options.accept(clientOptions);
return new TcpClient(clientOptions.duplicate());
````
Even if I provide my own resource through `ClientOptions` the global resources are created anyway and after that there is no way to shut them down since `dispose()` is empty and `_dispose()` is protected.

Please support the use case to create a `TcpClient` and then shut down **all** associated resources. If I provide my own resources it shouldn't trigger creation of global ones. There should also be some way to shut down global resources through an explicit method designed for that.  Consider for example that when running in a server like Tomcat on shutdown you get ugly messages about active threads.

It would also be very useful for `ClientOptions` to expose a way to expose what an option is currently set to so that I can also accept external options and add my own only if others are not provided -- same thing that `TcpClient#create` would have to do.

**Comment by smaldini** [comment]
Related to #15 and https://stackoverflow.com/questions/42069471/shutting-down-a-netty-tcpclient-channel-in-reactor-3-0-4
