### ISSUE TITLE
HTTP server should close the connection on error signal after response is committed

### ISSUE THREAD

**Issue by rstoyanchev** [reactor/reactor-netty#240]
This is a variation on #101 where it's too late to set the response to 500. In that case unless the connection is closed, the client will see a "successful" completion of the response.

I'm creating a separate issue based on suggestion from @smaldini that taking care of this would be easier and can be done independently.

**Comment by violetagg** [comment]
Can you provide some sample that shows the issue?

According to
https://github.com/reactor/reactor-netty/blob/master/src/main/java/reactor/ipc/netty/http/server/HttpServerOperations.java#L420
we attach `ChannelFutureListener.CLOSE` that should close the connection.

**Comment by rstoyanchev** [comment]
Simply write with a Flux like this:
```
Flux.just(1, 2, 3)
          .doOnNext(i -> {
            if (i == 3) {
              throw new RuntimeException("Random error");
            }
          })
          .map(...);
```
Using curl you will see it completes as normal (no connection closed before data fully read message) and also with wireshark you can see an HTTP response frame with the connection not closed.

**Comment by violetagg** [comment]
I have this test case #246 
Is that what you expect to happen?

**Comment by rstoyanchev** [comment]
Looks good. Thanks to #237 it can now be detected this way.

**Comment by violetagg** [comment]
Thanks, closing

**Comment by rstoyanchev** [comment]
Fix confirmed.
