### ISSUE TITLE
Http2AllocationStrategy may report incorrect permitGranted

### ISSUE THREAD

**Issue by Tripplesixty** [reactor/reactor-netty#2400]
The new Http2AllocationStrategy introduced a function that returns `permitGranted()`. The function as implemented appears to return the number of available permits, not the current number granted.  I could be reading this wrong, but it seems as if the logic is inverted. This may cause a bug in the `Http2Pool.java` code when calculating connection count bounds. 

The docs state the following:
https://github.com/reactor/reactor-netty/blob/6530f763b601b3c15a82109e7a1fc6c6c57120a1/reactor-netty-core/src/main/java/reactor/netty/resources/ConnectionProvider.java#L285-L290

The code is implemented as:
```
	@Override
	public int permitGranted() {
		return maxConnections - PERMITS.get(this);
	}
```

This code is used in `Http2Pool.java` 

Here: 
https://github.com/reactor/reactor-netty/blob/6530f763b601b3c15a82109e7a1fc6c6c57120a1/reactor-netty-http/src/main/java/reactor/netty/http/client/Http2Pool.java#L372-L398

And Here:
https://github.com/reactor/reactor-netty/blob/6530f763b601b3c15a82109e7a1fc6c6c57120a1/reactor-netty-http/src/main/java/reactor/netty/http/client/Http2Pool.java#L395-L402

## Expected Behavior
I'd expect the permitGranted() function to return the `PERMITS.get()`.

## Actual Behavior
The function returns `maxConnections - PERMITS.get(this)`

## Steps to Reproduce
I've observed problems with the H2 pooling strategy after high load scenarios, I end up seeing `PoolAcquireTimeoutException` on some hosts. Not sure if this is the cause yet, but spotted this as a possible suspect. 

## Possible Solution
```
	@Override
	public int permitGranted() {
		return PERMITS.get(this);
	}
```

## Your Environment
reactor-netty - 1.0.21
reactor-core - 3.4.20
netty - 4.1.79.Final
netty-tcnative-boringssl-static - 2.0.53.Final

openjdk version "11.0.7" 2020-04-14
Linux 5.2.9

**Comment by violetagg** [comment]
@Tripplesixty At the beginning PERMITS is initialed with `maxconnections` i.e. we **can** grand such number of permits, then when we invoke `getPermit` we decrease this value

https://github.com/reactor/reactor-netty/blob/3a90eba6447cf7b37cc87fab38e6121672a8fe92/reactor-netty-http/src/main/java/reactor/netty/http/client/Http2AllocationStrategy.java#L100

so `permitsGranted` is exactly `maxconnections` without those that we **can** grand isn't it?

**Comment by Tripplesixty** [comment]
Okay, I see what you are saying. I read the docs as this method returning the number of permits granted from the h2 pool, not the total number of h2 connections granted by the server. Thanks for clarification. I think this makes sense. We can close this report i think.
