### ISSUE TITLE
ContentType="application/x-www-form-urlencoded" is throwing Unsupported Media Type Error

### ISSUE THREAD

**Issue by jayapratha1** [reactor/reactor-netty#2415]
I have tried below code to process the request with contentType as "application/x-www-form-urlencoded".

       @RequestMapping(value = "/abcd", consumes = {"application/x-www-form-urlencoded"})
            public ResponseEntity handleRequest( RequestEntity<String> reqEntity,@RequestParam Map<String, String> params, @RequestHeader HttpHeaders httpHeaders) {

                logger.info("Request params received - " + params);
                logger.info("Request httpHeaders received - " + httpHeaders);

                return new ResponseEntity<>("{\"working\": \"Well\"}", HttpStatus.CREATED);
            }

But I am seeing below error
{
    "timestamp": "2022-08-03T10:28:35.801+00:00",
    "path": "/abcd",
    "status": 415,
    "error": "Unsupported Media Type",
    "message": null,
    "requestId": "492dfe63-192"
}

**Comment by violetagg** [comment]
@jayapratha1 Is it possible that you wanted to report this issue to another project? This code doesn't seem to be executable with Reactor Netty APIs

**Comment by violetagg** [comment]
@jayapratha1 Closing this issue. We can reopen it if you can provide an example with vanilla Reactor Netty.
