### ISSUE TITLE
Add native-image support

### ISSUE THREAD

**Issue by mhalbritter** [reactor/reactor-netty#2419]
While working on the [`session-redis-webflux` smoke test](https://github.com/spring-projects/spring-aot-smoke-tests/tree/main/session-redis-webflux), i discovered that there are reflection hints missing to get reactor-netty working. The test uses Lettuce as a redis client and webflux as web framework. The hints I had to add [were these](https://github.com/spring-projects/spring-aot-smoke-tests/blob/main/aot-smoke-test-third-party-hints/src/main/java/org/springframework/aot/smoketest/thirdpartyhints/ReactorNettyHints.java).

It would be nice if reactor-netty could ship these out of the box, for example as `META-INF/native-image/reflect-config.json` files.

I'm also not sure if these cover all use cases, but they are enough to let the sample pass.

Without these hints you see netty complaining about reaching the end of the pipeline without handling the message and then dropping it.

If you don't want these hints in your codebase, please let me know. I will then contribute the hints to the https://github.com/oracle/graalvm-reachability-metadata.

Thanks!

**Comment by violetagg** [comment]
Update: @mhalbritter and I found a strange behaviour related to `ChannelInboundHandlerAdapter` subclasses. More info https://github.com/oracle/graal/issues/4809

**Comment by violetagg** [comment]
@mhalbritter Yeah we have a lot + those in Netty - so we need to describe all of them? For Netty 4.1 where do we need to do that?
Also Is there some documentation or else where we can describe this because all custom Netty handlers will behave with poor performance if they do not do the same?
Isn't there another approach to achieve this or the only approach is to declare all handlers that we/Netty/users have?

**Comment by mhalbritter** [comment]
My take on that would be that all handlers that are defined in your codebase have reflection hints for them. These files usually reside in `META-INF/native-image/<group-id>/<artifact-id>`.

What documentation do you mean? For GraalVM side, there is [documentation on the `reflect-config.json` here](https://www.graalvm.org/22.2/reference-manual/native-image/dynamic-features/Reflection/). For Netty specifically I don't know of any documentation regarding native-image.

As of now, I don't see any other approach. If someone creates a netty handler and wants full performance, they have to provide reflection hints for native-image. In theory one could write a compiler plugin which generates this automatically. In an optimal world, Netty would not use that much reflection :D

**Comment by mhalbritter** [comment]
I don't quite understand. You're adding only hints for types in your codebase, right? What is the separation between netty4 and netty5? Are these branches in your codebase?

I would include all hints which are for your classes in your codebase. The graalvm-reachability-metadata is only for projects which don't want / aren't able to put GraalVM metadata in their codebase.

**Comment by violetagg** [comment]
> I don't quite understand. You're adding only hints for types in your codebase, right? What is the separation between netty4 and netty5? Are these branches in your codebase?
> 
> I would include all hints which are for your classes in your codebase. The graalvm-reachability-metadata is only for projects which don't want / aren't able to put GraalVM metadata in their codebase.

Reactor Netty uses handlers provided by Netty.
