### ISSUE TITLE
how fix this 

### ISSUE THREAD

**Issue by josecuervo2016** [reactor/reactor-netty#242]
### Steps to reproduce
https://pastebin.com/tzE15SxR
### JVM version (e.g. `java -version`)
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)

### OS version (e.g. `uname -a`)
Linux emeraldcraft 4.13.0-16-generic #19-Ubuntu SMP Wed Oct 11 18:35:14 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by violetagg** [comment]
Please provide more explanation directly in the issue.
Links temp to be not available in long term, but the explanation in the issue can be available for future references.

**Comment by josecuervo2016** [comment]
hello, my english is not very good I'm using translator haha, I do not know what you want to happen to you, I copy the report that the console throws at me, it does not do it all the time, when a user connects to the server, it spams me that error , I passed my version of java and linux, I do not know what else you need to provide you

**Comment by violetagg** [comment]
At least specify Reactor Netty version ...

**Comment by josecuervo2016** [comment]
Could you tell me what command or how do I fix that version of the Reactor Netty version?

**Comment by violetagg** [comment]
According to the stack trace you are using component `Waterfall-Bootstrap:1.12-SNAPSHOT` that provides Netty.

I'm closing this as we do not use this component at all.
