### ISSUE TITLE
websockt: Method WebSocketOutbound.sendString(Mono.just("asd11")).sendString(Mono.just("asd11")) is a problem

### ISSUE THREAD

**Issue by huchaogithup** [reactor/reactor-netty#2452]
We use httpclient.create().websocket(): set the handle method. when calling WebSocketOutbound.sendString(Mono..just ("asd11"). sendString.(Mono.just ("asd11")), an error occurred on the websock service side

## Expected Behavior
The service side accepts ”asd11“ and ”asd11“

## Actual Behavior
The service side accepts ”asd11“ and  an error occurred ”websocket: unexpected reserved bits 0x60“

```java
@Test
public void repoCase() {
           HttpClient.create().websocket().uri("ws://localhost:8080")
                .handle((req,resp)->{
                    return resp.sendString(Mono.just("asd11")).sendString(Mono.just("asd11"));
                }).blockLast();
}
```

## Possible Solution
WebSocketOutbound.sendString(Mono.just("asd11")) return  ReactorNetty.OutboundThen without "stringToWebsocketFrame"

* Reactor version(s) used:  reactor-netty-http-1.0.22.jar
* JVM version (`java -version`): jdk17
* OS and version (eg. `uname -a`): windows10

**Comment by pderop** [comment]
Hi @huchaogithup,

Chaining multiple send operations is discouraged and will not work as expected when send involves scalar or mono publishers, please check javadoc from NettyOutbound.

Now, could you clarify and indicate your use use ? it should be easy to do one single sendString call like _sendString(Flux.concat(…))_ or whatever ?

PS: I see you have created a PR (thank you for that), but as said, chaining/nesting send* calls is discouraged, so let's see if a reactive-chain can resolve your issue, thank you.

**Comment by huchaogithup** [comment]
This is because the client needs to send the first message after the websockt handshake is completed.  for example `        HttpClient.create().websocket().uri("ws://localhost:8080")
                .handle((req,resp)-> resp.sendString(Mono.just("fist message..."))
                            .sendString(req.receive().map(s->{
                                //todo Business processing
                            }))).blockLast();`

**Comment by huchaogithup** [comment]
Flux.concat(…)也是一种解决问题的方式，但是可能链式调用可能更符合一些习惯

**Comment by huchaogithup** [comment]
Flux. Concat (...) is also a way to solve the problem, but chain calling may be more consistent with some habits

**Comment by pderop** [comment]
Indeed, this use case seems to be easily addressed using Flux operators like Concat.
For the moment, I'm closing this issue (fee free to reopen if necessary). 
I need to discuss further on with the team and maybe we will clarify some part of the javadoc to not chain/nest send* methods.

For the moment, please use the Concat work around, or whatever, thank you.
