### ISSUE TITLE
H2OrHttp11Codec may cause ALPN to fail in HttpClient in certain circumstances 

### ISSUE THREAD

**Issue by j-bahr** [reactor/reactor-netty#2480]
## Expected Behavior

Under certain circumstances one may be required to talk to an HTTP proxy via TLS. When this happens a it's necessary to put a second SSLHandler at the head of the pipeline. This instance of the SslHandler will negotiate a secure session with the proxy. It's transparent to the rest of the http pipeline except when attempting to negotiate ALPN. 

```java
httpClient
.protocol(HttpProtocol.H2, HttpProtocol.HTTP11)
.doOnChannelInit(
            (observer, channel, remoteAddress) -> {
                channel
                    .pipeline()
                    .addFirst("proxy.sslhandler", proxySslContext.newHandler(channel.alloc()));
```

When the http client is configured to support support  HTTP 2 and HTTP1, the `H2OrHttp11Codec` *should* select the named `NettyPipeline.SslHandler` when trying to determine the negotiated protocol version. Selecting the SslHandler by name ensures we are checking the protocol negotiated with the remote endpoint not the local forward proxy. To do this I'd expect the `H2orHttp11Codec` to pull the SslHanlder by name, not by type. Asking for the handler by type will return the first SslHandler in the pipeline, causing ALPN selected protocol to be based on the protocol negotiated with the proxy, not the remote endpoint. 

## Actual Behavior

The actual behavior is shown below. We currently pull the SslHandler by type, which will always pull the first handler in the pipeline, the handler talking to the proxy. This can cause ALPN to select the wrong protocol when trying to talk H2 over a http 1.1 proxy.

**Current (incorrect) Code:**
```java
static final class H2OrHttp11Codec extends ChannelInboundHandlerAdapter {
 ....
		@Override
		public void channelActive(ChannelHandlerContext ctx) {
			SslHandler sslHandler = ctx.pipeline().get(SslHandler.class);		
			....
	}
```

## Steps to Reproduce
Unfortunately this requires a somewhat complex setup with a TLS based forward proxy that is not easy to setup or reproduce outside of my production environment. That being said, I have built a custom jar with the fix outlined below and verified it worked correct in my environment. The fix is fairly harmless and will continue to work as expect for all other standard workflows. 

## Possible Solution

**Expected Code:**
To fix this simply request the SslHandler by name, `NettyPipeline.SslHandler`, to get the right negotiated protocol. 
```java
static final class H2OrHttp11Codec extends ChannelInboundHandlerAdapter {
 ....
		@Override
		public void channelActive(ChannelHandlerContext ctx) {
			SslHandler sslHandler = ctx.pipeline().get(NettyPipeline.SslHandler);		
			....
	}
```

## Your Environment

* Reactor version(s) used: **Reactor netty 1.0.22, Reactor core 3.4.22**
* Other relevant libraries versions (eg. `netty`, ...): **Netty 4.1.79.Final**
* JVM version (`java -version`): **Java 11 & 17, Adoptium**
* OS and version (eg. `uname -a`): Linux 5.2.9 x86_64

**Comment by violetagg** [comment]
@j-bahr Thanks for the detailed analysis. Would you like to provide a PR?

**Comment by j-bahr** [comment]
@violetagg, a PR is up for review. Thanks for your consideration!
