### ISSUE TITLE
RAM usage increased with netty and webflux

### ISSUE THREAD

**Issue by namrta2046** [reactor/reactor-netty#2502]
```
Java version : oracle openjdk 1.8.0_311
Springboot version : 2.5.14
Netty version : 4.1.77.Final
```
We are executing flow with a sample application which takes the request and forming a response within the sample app and responding back to the client[not having any WebClient calls]. 
We are observing memory related issues while doing the performance testing for the same sample application where we have seen that heap is not growing. Though the overall RAM usage is growing. Therefore, we tried few VM arguments as following.

```
Scenario 1 - Xmx2048M -Xss1024K -Xms2048M 
Scenario 2 - Xmx2048M -Xss1024K -Xms2048M -Dio.netty.allocator.type=unpooled
Scenario 3 - Xmx2048M -Xss1024K -Xms2048M -XX:MaxDirectMemorySize=200m
```
 
All of the above scenarios having same behaviour where heap was within the range and not growing whereas RAM keeps on growing and getting the following exception - 

```
LEAK: ByteBuf.release() was not called before it's garbage-collected. See https://netty.io/wiki/reference-counted-objects.html for more information.
   Recent access records: 
   Created at:
      io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:403)
      io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:188)
      io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:179)
      io.netty.buffer.AbstractByteBufAllocator.buffer(AbstractByteBufAllocator.java:116)
      org.springframework.core.io.buffer.NettyDataBufferFactory.allocateBuffer(NettyDataBufferFactory.java:71)
      org.springframework.core.io.buffer.NettyDataBufferFactory.allocateBuffer(NettyDataBufferFactory.java:39)
      org.springframework.http.codec.json.AbstractJackson2Encoder.encodeValue(AbstractJackson2Encoder.java:240)
      org.springframework.http.codec.json.AbstractJackson2Encoder.lambda$encode$0(AbstractJackson2Encoder.java:150)
      reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:113)
```
      
Is there any VM argument or configuration required to be added to restrict the RAM usage.

**Comment by violetagg** [comment]
@namrta2046 Indeed the exception suggests that you have a memory leak. Please follow this [FAQ: How can I debug a memory leak](https://projectreactor.io/docs/netty/release/reference/index.html#faq.memory-leaks) in order to be able to gather more information.

**Comment by namrta2046** [comment]
Thankyou, with the help of link provided we were able to debug the memory leak and identified the issue.

**Comment by htejwani** [comment]
@namrta2046, can you please let me know what was the root cause of the issue and the fix?
