### ISSUE TITLE
Getting custom metric

### ISSUE THREAD

**Issue by strelchm** [reactor/reactor-netty#2552]
I have to make next netty metrics for all http requests of Spring Webflux app:

- time from receiving a request to being laid to the request pool
- waiting time for processing in the pool request

Can you please suggest idea - how I can get such metrics? May be with help of AOP? Or there are some listeners that can be used?

With honour, Michael

**Comment by violetagg** [comment]
@strelchm Can you please elaborate a bit more on the requirements? Also most probably you need this for 1.0.x version?

**Comment by violetagg** [comment]
@strelchm So you are targeting server metrics. Ok.

> but want some more information about http-request(events) in thread pool

I cannot get this ...

Reactor Netty doesn't use thread per request paradigm which is typical for blocking processing of the requests. Reactor Netty processes the requests in a non-blocking fashion and uses an even loop. Typically the number of the threads that we use is the number of the cores that you have.

**Comment by violetagg** [comment]
We do have metrics for how many connections are opened at any moment and how many of them are active (which basically represents the number of the requests that are in process at the moment).

**Comment by violetagg** [comment]
@strelchm `@RestController` this is something that is not provided by Reactor Netty...
Spring WebFlux uses I/O Handler functionality that Reactor Netty provides which mean once the request comes on a given connection Reactor Netty immediately do the the HTTP decoding and forward the request to the Spring WebFlux I/O Handler. 
You can monitor the event loop task queue if you think that there is some blocking operation that causes the event loop to slowly process the tasks.
Other than that there is a feature request #1433 for event loop task duration, but this is not only for requests but for every task that is pending in the event loop.

**Comment by strelchm** [comment]
> @strelchm You can monitor the event loop task queue if you think that there is some blocking operation that causes the event loop to slowly process the tasks

@violetagg  Can you please suggest how I can do this? I see one metric reactor.netty.eventloop.pending.tasks in docs. In other way, can we measure the time with aop or this is bad idea?

**Comment by violetagg** [comment]
@strelchm This one `reactor.netty.eventloop.pending.tasks` reports in Micrometer if you need something else you can follow the snippet here #1398

**Comment by strelchm** [comment]
@violetagg thanks much!

**Comment by violetagg** [comment]
@strelchm I'm closing this one. We can reopen it if something else is needed.
