### ISSUE TITLE
java.lang.ClassCastException: reactor.netty.internal.shaded.reactor.pool.decorators.GracefulShutdownInstrumentedPool$GracefulRef cannot be cast to reactor.netty.http.client.Http2Pool$Http2PooledRef

### ISSUE THREAD

**Issue by pandeyabhi1987** [reactor/reactor-netty#2571]
We want to use [disposeTimeout](https://projectreactor.io/docs/netty/release/api/reactor/netty/resources/ConnectionProvider.Builder.html#disposeTimeout-java.time.Duration-) to force the connection pool to close.

The line where exception is thrown -
https://github.com/reactor/reactor-netty/blob/main/reactor-netty-http/src/main/java/reactor/netty/http/client/Http2ConnectionProvider.java#L397

`String applicationProtocol = ((Http2Pool.Http2PooledRef) pooledRef).slot.applicationProtocol;`

Expected Behavior
Graceful shutdown for the connection pools, with this grace period timeout

**Actual Behavior**
`reactor.netty.internal.shaded.reactor.pool.decorators.GracefulShutdownInstrumentedPool$GracefulRef cannot be cast to reactor.netty.http.client.Http2Pool$Http2PooledRef;`

Your Environment
Reactor version(s) used: reactor-netty  1.1.0,  reactor-core 3.5.0

**Comment by berngp** [comment]
Thanks for applying the fix so quickly @violetagg !
