### ISSUE TITLE
Missing tracing information in spring-cloud-sleuth without reactor-netty-http-brave

### ISSUE THREAD

**Issue by bergerst** [reactor/reactor-netty#2581]
This report is based on https://github.com/spring-cloud/spring-cloud-sleuth/issues/2233 where I was told to create an issue in this project. @violetagg was involved in the discussion.

When using spring-cloud-gateway in combination with spring-cloud-sleuth and Zalando Logbook, some logs are missing traceIds and spanIds.

Using reactor-netty-http-brave is the only known fix for this problem: https://docs.spring.io/spring-cloud-sleuth/docs/current/reference/htmlsingle/spring-cloud-sleuth.html#sleuht-http-client-logbook-with-webclient

But those classes will be removed with version 2.0, so a new solution is needed.

## Expected Behavior
All Logbook logs should contain traceIds and spanIds.

## Actual Behavior

When incoming requests are received on the HttpServer side or incoming responses are received on the HttpClient side, the traceIds and spanIds aren't part of the current logging context yet, therefore the Logbook logs don't contain them.

```
2022-11-17 14:50:12.652 TRACE [,,] 1928 --- [ctor-http-nio-1] org.zalando.logbook.Logbook              : Incoming Request: fb33a3d1ca71c2b9
2022-11-17 14:50:12.654 TRACE [,fdd5ee36b38005aa,fdd5ee36b38005aa] 1928 --- [ctor-http-nio-1] org.zalando.logbook.Logbook              : Outgoing Request: f52b4ee22c5e1215
2022-11-17 14:50:12.660 TRACE [,,] 1928 --- [ctor-http-nio-1] org.zalando.logbook.Logbook              : Incoming Response: f52b4ee22c5e1215
2022-11-17 14:50:12.662 TRACE [,fdd5ee36b38005aa,fdd5ee36b38005aa] 1928 --- [ctor-http-nio-1] org.zalando.logbook.Logbook              : Outgoing Response: fb33a3d1ca71c2b9
```

## Steps to Reproduce
Example project: https://github.com/bergerst/gateway-tracing-example

## Your Environment

* Reactor version(s) used: 2022.0.0 (1.1.0)
* Other relevant libraries versions (eg. `netty`, ...): Netty 4.1.84.Final, spring-cloud-sleuth 3.1.5, spring-cloud-gateway 3.1.4, Logbook 2.14.0
* JVM version (`java -version`): 8 and 17
* OS and version (eg. `uname -a`): Windows Server 2016

**Comment by violetagg** [comment]
@bergerst We discussed again with @marcingrzejszczak the use case here: the old Sleuth implementation and the new Observation API and this is not designed to work together. You either use the old Sleuth with Reactor Netty 1.0.x (which is supported for Spring Boot 2.x) or you use the new Observation API with Reactor Netty 1.1.x (Spring Boot 3)

**Comment by bergerst** [comment]
Does this mean that a future spring-cloud-sleuth version will support the Observation API?

**Comment by violetagg** [comment]
> Does this mean that a future spring-cloud-sleuth version will support the Observation API?

@bergerst Please check this blog post https://spring.io/blog/2022/10/12/observability-with-spring-boot-3
