### ISSUE TITLE
WebClient in Tomcat on Kubernetes Memory Leak

### ISSUE THREAD

**Issue by lopenn01** [reactor/reactor-netty#2590]
We're trying to use `WebClient` in our microservice to get large data object from external backend service, and the microservice runs on Kubernetes cluster (I tested on both Docker Desktop Kubernetes or Azure Kubernetes). We're seeing the pod memory go up until the pod is killed and restarted 

## Expected Behavior
The pod should not be killed, and the memory usage should be similar or less than using the `RestTemplate`.

## Actual Behavior
When we make external service calls using Netty's `WebClient`, we're seeing the memory increases seemingly without limit. I used JCMD to check GC and get the heapdump. GC seems normal and there is no leak found from the heapdump. If I run the microservice as a standalone app, I confirmed the GC happened with VisualVM.

When I run the microservices on Docker Desktop Kubernetes, the memory is consistently going up until the instance is eventually killed without any outOfMemory errors.

## Steps to Reproduce
I've created sample projects for all the things I tried. The code is in [test-service-client](https://github.com/lopenn01/test-service-client). It has 3 branches.

The backend: [test-backend branch](https://github.com/lopenn01/test-service-client/tree/test-backend).  For testing purpose, I simplify the result that has about 8mb, 16mb, 24mb and 32mb bogus data. The actual external service returns a big object that contains different information. You can run "kubectl apply -f test-backend.yaml" to create the pod.
The Tomcat `WebClient`: [test-webclient-tomcat branch](https://github.com/lopenn01/test-service-client/tree/test-webclient-tomcat). The microservice runs with -Xmx250M. You can run "kubectl apply -f test-webclient-tomcat.yaml" to create the pod.
The Tomcat `RestTemplate`: [test-rest-template branch](https://github.com/lopenn01/test-service-client/tree/test-rest-template). The microservice runs with -Xmx250M. You can run "kubectl apply -f test-rest-template.yaml" to create the pod.

After you checkout the branch, you can run "gradle docker" to build the docker image and deploy the docker image to any kubernetes cluster. The pod memory resource is set to 320M. You can monitor the memory usage using Kubernetes Dashboard or "kubectl describe podMetrics <pod name>".

After the pods are deployed and port forward to a local port, I trigger the Tomcat WebClient service one at a time. The pod will be killed or restarted after 4 or 6 requests are completed.

```java
@Service
public class DataServiceImpl implements DataService {

  private static final Logger log = LoggerFactory.getLogger(DataServiceImpl.class);

  @Value("${app.source.url}")
  private String sourceUrl;

  @Autowired private WebClient webClient;

  public DataResult getData(String imageNo) {
    try {
      var httpHeaders = new HashMap<String, String>();
      var responseStr =
          webClient
              .get()
              .uri(sourceUrl + (StringUtils.hasText(imageNo) ? "/" + imageNo : ""))
              .headers(headers -> headers.setAll(httpHeaders))
              .retrieve()
              .bodyToMono(String.class)
              .block();

      if (StringUtils.hasText(responseStr)) {
        var result = new DataResult();
        result.setCode(DataResultCode.OK);
        result.setData(responseStr);
        return result;
      }
    } catch (Exception e) {
      log.error("Failed...", e);
      var result = new DataResult();
      result.setCode(DataResultCode.ERROR);
      result.setMessage(e.getMessage());
      return result;
    }
    return null;
  }
}
```
## Your Environment

* Reactor version(s) used: Spring Webflux 5.3.22, Reactor Core 3.4.23
* Reactor Netty version: 1.0.23
* JVM version (`java -version`): OpenJDK 64-Bit Server VM Temurin-11.0.16.1+1 (build 11.0.16.1+1, mixed mode)
* OS and version (eg. `uname -a`): Docker image adoptopenjdk/openjdk11

**Comment by violetagg** [comment]
@lopenn01 What do you use as a load runner? How many requests to the backend are you able to create with `RestTemplate` (blocking HTTP client) and how many requests to the backend are you able to create with `WebClient` (non-blocking HTTP client)?

**Comment by lopenn01** [comment]
> @lopenn01 `WebClient` by default works with pooled direct memory. https://netty.io/wiki/reference-counted-objects.html
> 
> You can switch it to HEAP only unpooled memory. You need to do the following:
> 
> 1. You need to switch to a special allocator
> 
> ```
> @Bean
> public WebClient webClient() {
>        ... 
>        return WebClient.builder()
>                        .clientConnector(new ReactorClientHttpConnector(HttpClient.create().compress(true)
>                                    .option(ChannelOption.ALLOCATOR, new PreferHeapByteBufAllocator(UnpooledByteBufAllocator.DEFAULT))))
>                        .exchangeStrategies(strategies).build();
> }
> ```
> 
> 2. Also you need to disable the Epoll and to run with NIO.
> 
> `-Dreactor.netty.native=false`
> 
> This is what my setup is:
> 
> `Container entrypoint set to [java, -Xmx250M, -noverify, -XX:TieredStopAtLevel=1, -XX:NativeMemoryTracking=summary, -XX:+UnlockDiagnosticVMOptions, -XX:+PrintNMTStatistics, -Dreactor.netty.native=false ...`
> 
> Please tell us the results.

I will test it using your suggested setting and get back to you.

Does the code for changing special allocator work the same as using this option `-Dio.netty.allocator.type=unpooled`?

**Comment by violetagg** [comment]
> Does the code for changing special allocator work the same as using this option -Dio.netty.allocator.type=unpooled?

No because we want to specify `unpooled` and `heap only`

**Comment by lopenn01** [comment]
@violetagg, I tested my code with those two suggested changes. The way I tested it is the same as before. I trigger the Tomcat WebClient, wait until it finishes and then next request. However, the pod got restart when I triggered the Tomcat WebClient at the 8th time.

**Comment by violetagg** [comment]
@lopenn01 Do you see any OOM in the logs?

Let's test with vanilla Reactor Netty instead of WebClient.
Do the following changes:

`WebclientApplication.java`

```
@Bean
public HttpClient httpClient() {
	return HttpClient.create().compress(true);
        		.option(ChannelOption.ALLOCATOR, new PreferHeapByteBufAllocator(UnpooledByteBufAllocator.DEFAULT));
}
```

`DataServiceImpl.java`

```
@Autowired private HttpClient httpClient;

public DataResult getData(String imageNo) {
    try {
      var httpHeaders = new HashMap<String, String>();
      var responseStr =
            httpClient
                .get()
                .uri(sourceUrl + (StringUtils.hasText(imageNo) ? "/" + imageNo : ""))
                .responseContent()
                .aggregate()
                .asString()
                .block();
...
```

**Comment by lopenn01** [comment]
> @lopenn01 Do you see any OOM in the logs?
No, I didn't OOM in the logs.

**Comment by violetagg** [comment]
> @lopenn01 Do you see any OOM in the logs?
> No, I didn't OOM in the logs.

Hmmm interesting, you should because you should be running with unpooled and heap only (not pooled direct memory anymore)

**Comment by lopenn01** [comment]
> > @lopenn01 Do you see any OOM in the logs?
> > No, I didn't OOM in the logs.
> 
> Hmmm interesting, you should because you should be running with unpooled and heap only (not pooled direct memory anymore)

I ran jcmd before I started testing. I confirmed that -Dreactor.netty.native=false is included.
8:
#
# JRE version: OpenJDK Runtime Environment Temurin-11.0.16.1+1 (11.0.16.1+1) (build 11.0.16.1+1)
# Java VM: OpenJDK 64-Bit Server VM Temurin-11.0.16.1+1 (11.0.16.1+1, mixed mode, tiered, compressed oops, serial gc, linux-amd64)

---------------  S U M M A R Y ------------

Command Line: -Xmx250M -Xverify:none -XX:TieredStopAtLevel=1 -XX:NativeMemoryTracking=summary -XX:+UnlockDiagnosticVMOptions -XX:+PrintNMTStatistics -Dio.netty.leakDetection.level=pa
ranoid -Dreactor.netty.native=false test-webclient.jar

Host: Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz, 8 cores, 327M, Ubuntu 20.04.5 LTS
Time: Thu Dec 15 18:36:20 2022 UTC elapsed time: 133.448967 seconds (0d 0h 2m 13s)

**Comment by lopenn01** [comment]
@violetagg, I just tested with vanilla Reactor Netty instead of WebClient. The pod also got restarted at the 8th request. Here is the pod log. I don't see any OOM before the pod restarted at 2022-12-15 20:46:52.903.

2022-12-15 20:41:18.376 DEBUG 7 --- [ctor-http-nio-4] r.n.http.client.HttpClientOperations     : [5593f3c6-1, L:/10.1.2.227:59042 - R:test-backend.example.svc.cluster.local/10.103.185.22:8080] Received response (auto-read:false) : [Content-Type=text/plain;charset=UTF-8, Date=Thu, 15 Dec 2022 20:41:18 GMT, content-length=25477110]
2022-12-15 20:41:18.377 DEBUG 7 --- [ctor-http-nio-4] r.n.r.DefaultPooledConnectionProvider    : [5593f3c6-1, L:/10.1.2.227:59042 - R:test-backend.example.svc.cluster.local/10.103.185.22:8080] onStateChange(GET{uri=/get-data, connection=PooledConnection{channel=[id: 0x5593f3c6, L:/10.1.2.227:59042 - R:test-backend.example.svc.cluster.local/10.103.185.22:8080]}}, [response_received])
2022-12-15 20:41:18.377 DEBUG 7 --- [ctor-http-nio-4] reactor.netty.channel.FluxReceive        : [5593f3c6-1, L:/10.1.2.227:59042 - R:test-backend.example.svc.cluster.local/10.103.185.22:8080] FluxReceive{pending=0, cancelled=false, inboundDone=false, inboundError=null}: subscribing inbound receiver
2022-12-15 20:41:18.470 DEBUG 7 --- [ctor-http-nio-4] r.n.http.client.HttpClientOperations     : [5593f3c6-1, L:/10.1.2.227:59042 - R:test-backend.example.svc.cluster.local/10.103.185.22:8080] Received last HTTP packet
2022-12-15 20:41:18.650 DEBUG 7 --- [ctor-http-nio-4] r.n.r.DefaultPooledConnectionProvider    : [5593f3c6, L:/10.1.2.227:59042 - R:test-backend.example.svc.cluster.local/10.103.185.22:8080] onStateChange(GET{uri=/get-data, connection=PooledConnection{channel=[id: 0x5593f3c6, L:/10.1.2.227:59042 - R:test-backend.example.svc.cluster.local/10.103.185.22:8080]}}, [response_completed])
2022-12-15 20:41:18.650 DEBUG 7 --- [ctor-http-nio-4] r.n.r.DefaultPooledConnectionProvider    : [5593f3c6, L:/10.1.2.227:59042 - R:test-backend.example.svc.cluster.local/10.103.185.22:8080] onStateChange(GET{uri=/get-data, connection=PooledConnection{channel=[id: 0x5593f3c6, L:/10.1.2.227:59042 - R:test-backend.example.svc.cluster.local/10.103.185.22:8080]}}, [disconnecting])
2022-12-15 20:41:18.650 DEBUG 7 --- [ctor-http-nio-4] r.n.r.DefaultPooledConnectionProvider    : [5593f3c6, L:/10.1.2.227:59042 - R:test-backend.example.svc.cluster.local/10.103.185.22:8080] Releasing channel
2022-12-15 20:41:18.650 DEBUG 7 --- [ctor-http-nio-4] r.n.resources.PooledConnectionProvider   : [5593f3c6, L:/10.1.2.227:59042 - R:test-backend.example.svc.cluster.local/10.103.185.22:8080] Channel cleaned, now: 0 active connections, 1 inactive connections and 0 pending acquire requests.
2022-12-15 20:42:18.545 DEBUG 7 --- [ctor-http-nio-4] r.n.r.DefaultPooledConnectionProvider    : [5593f3c6, L:/10.1.2.227:59042 ! R:test-backend.example.svc.cluster.local/10.103.185.22:8080] onStateChange(PooledConnection{channel=[id: 0x5593f3c6, L:/10.1.2.227:59042 ! R:test-backend.example.svc.cluster.local/10.103.185.22:8080]}, [disconnecting])


2022-12-15 20:46:52.903  INFO 8 --- [           main] com.example.demo.Application             : Starting Application using Java 11.0.16.1 on test-webclient-tomcat-5f4546d9d7-r62mb with PID 8 (/app/example/test-webclient.jar started by root in /app/example)
2022-12-15 20:46:52.908  INFO 8 --- [           main] com.example.demo.Application             : No active profile set, falling back to 1 default profile: "default"
2022-12-15 20:46:55.716  INFO 8 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8080 (http)
2022-12-15 20:46:55.742  INFO 8 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]

**Comment by violetagg** [comment]
@lopenn01 Can you add `doOnConnected` so that we can print the allocator? Also remove `-Dio.netty.leakDetection.level`.

```
            httpClient
                .doOnConnected(conn -> log.error("Allocator=" + conn.channel().alloc()))    <---- Prints the allocator
                .get()
                .uri(sourceUrl + (StringUtils.hasText(imageNo) ? "/" + imageNo : ""))
                .responseContent()
                .asString()
                .reduce((s, s2) -> s + s2)
                .block();
```

**Comment by lopenn01** [comment]
```
2022-12-15 21:33:11.560 ERROR 7 --- [ctor-http-nio-2] c.example.demo.service.DataServiceImpl   : Allocator=[io.netty.channel.PreferHeapByteBufAllocator@774f983f]
```

**Comment by lopenn01** [comment]
> @lopenn01 Can you add `doOnConnected` so that we can print the allocator? Also remove `-Dio.netty.leakDetection.level`.
```
2022-12-15 21:33:11.560 ERROR 7 --- [ctor-http-nio-2] c.example.demo.service.DataServiceImpl   : Allocator=[io.netty.channel.PreferHeapByteBufAllocator@774f983f]
```

**Comment by violetagg** [comment]
@lopenn01 I'm trying your sample on GKE and with vanilla Reactor Netty I'm not seeing the issue anymore. With WebClient I'm seeing OOM in the logs. What infrastructure do you use?

**Comment by lopenn01** [comment]
> @lopenn01 I'm trying your sample on GKE and with vanilla Reactor Netty I'm not seeing the issue anymore. With WebClient I'm seeing OOM in the logs. What infrastructure do you use?

I am testing on Docker Desktop Kubernetes. Let me test on Azure Kubernetes

**Comment by violetagg** [comment]
Also I updated Spring Boot to 2.7.6 so that I run with the latest releases.

**Comment by lopenn01** [comment]
@violetagg, I tested with vanilla Reactor Netty, Spring Boot 2.7.6 on Docker Desktop Kubernetes. I am able to trigger the service more than 30 times without any issue. Do you have issue with WebClient and Spring Boot 2.7.6?

**Comment by violetagg** [comment]
> Do you have issue with WebClient and Spring Boot 2.7.6?

On GKE I was seeing OOM in the logs

**Comment by AtzDT** [comment]
We are seeing the same behavior with the WebClient in Spring Boot 2.7.7.

**Comment by violetagg** [comment]
@lopenn01 @AtzDT Let me summarise the findings for this issue:
When `WebClient` is used with the default settings, one should take into account that `WebClient` by default uses pooled direct memory. One can control the direct memory size with `-XX:MaxDirectMemorySize`/`-Dio.netty.maxDirectMemory` (https://github.com/netty/netty/blob/4.1/common/src/main/java/io/netty/util/internal/PlatformDependent.java#L153-L160).
`Netty` uses pooled direct memory for performance reasons (https://netty.io/wiki/reference-counted-objects.html)

If unpooled heap memory is the desired configuration for `WebClient`, then one should configure the following options (explained in details in the comment https://github.com/reactor/reactor-netty/issues/2590#issuecomment-1344356550)
- `-Dreactor.netty.native=false`
- `ChannelOption.ALLOCATOR -> new PreferHeapByteBufAllocator(UnpooledByteBufAllocator.DEFAULT)`

I'm closing this one as I don't think there is anything that has to be fixed in Reactor Netty. We can reopen this issue it this is needed.

**Comment by lopenn01** [comment]
> I'm closing this one as I don't think there is anything that has to be fixed in Reactor Netty. We can reopen this issue it this is needed.

@violetagg, I tested WebClient using 2.7.7 and the following two options, and the pod restarted at the 6th requests.

- `-Dreactor.netty.native=false`
- `ChannelOption.ALLOCATOR -> new PreferHeapByteBufAllocator(UnpooledByteBufAllocator.DEFAULT)`

If the problem is not caused by Reactor Netty, should I file this issue to Spring Framework instead?

**Comment by violetagg** [comment]
@lopenn01 

> If the problem is not caused by Reactor Netty, should I file this issue to Spring Framework instead?

If you observer the issue with `WebClient` but not with vanilla `Reactor Netty` then yes please open an issue for `Spring Framework`.

**Comment by lopenn01** [comment]
@violetagg, thanks for your support and advise.

**Comment by thomas-grininger** [comment]
@lopenn01 If you open an issue with Spring Framework could you please also link this here?

We are experiencing a very similar problem.

**Comment by lopenn01** [comment]
I just submitted this [issue for Spring Framework (#29772) ](https://github.com/spring-projects/spring-framework/issues/29772).
