### ISSUE TITLE
reactor_netty metrics `uri` tag explosion

### ISSUE THREAD

**Issue by youzipi** [reactor/reactor-netty#2591]
we use spring-cloud-gateway,
recently i enable the actuator and metrics,
found that amount of metric tags increases quickly in production, and cause memory leak, pod restart.
some downstream business services provide routes with `pathVariable`.

## Steps to Reproduce

- enable metrics
- send request with different uri

metrics sample:
```
reactor_netty_http_client_data_sent_bytes_count{application="athena-dev",env="dev",remote_address="${my-biz-server}:80",uri="/base_info/41072166/is_new",} 1.0
reactor_netty_http_client_data_sent_bytes_sum{application="athena-dev",env="dev",remote_address="${my-biz-server}:80",uri="/base_info/41072166/is_new",} 0.0
```

## Possible Solution

option 1:
`http.client.requests.*` metrics provide a config: maximumAllowableTags, default=100

option 2:
like `http_server_*` metrics, 
unkown uri is mapped to `UNKNOWN`

I am willing to fix it.

## Your Environment

* Reactor version(s) used: 1.0.22
* Other relevant libraries versions (eg. `netty`, ...): `netty=4.1.79`, `spring-cloud-gateway=3.1.4`
* JVM version (`java -version`):
* OS and version (eg. `uname -a`):

**Comment by violetagg** [comment]
@youzipi When you enable the metrics what function do you provide for `uriTagValue` - `HttpClient#metrics(boolean enable, Function<String, String> uriTagValue)`

Please check the notice and the example in the reference documentation https://projectreactor.io/docs/netty/release/reference/index.html#_metrics_6

**Comment by youzipi** [comment]
@violetagg thanks, i found the upper limit config in comment of `reactor.netty.http.client.HttpClient#metrics(boolean, java.util.function.Function<java.lang.String,java.lang.String>)`

**Comment by violetagg** [comment]
> @violetagg thanks, i found the upper limit config in comment of `reactor.netty.http.client.HttpClient#metrics(boolean, java.util.function.Function<java.lang.String,java.lang.String>)`

Nice
Also we recommend always when possible to use templated uri for metrics - this can be achieved with `uriTagValue` function that can be provided with the API above.
