### ISSUE TITLE
How to configure read timeout?

### ISSUE THREAD

**Issue by noorulhaq** [reactor/reactor-netty#26]

**Comment by smaldini** [comment]
We have a connect timeout (TCP  connection timeout) in HttpClientOptions you pass to `HttpClient/HttpServer.create(options -> options.xxxx)`. Another default one is used for connection pooling (10s), so failing to acquire will error too. 
But we don't yet listen for idle read/connections, which you can do with Flux#receive().timeout(xxx, xxx)

**Comment by nkolosnjaji** [comment]
Hi, I'm having troubles with configuring this timeout. Which method are you referring in *HttpClientOptions* ?

**Comment by joshiste** [comment]
Am I wrong or isn't the `ChannelOption.SO_TIMEOUT` the same as a read timeout?

**Comment by lhotari** [comment]
@joshiste Netty uses `ChannelOption.SO_TIMEOUT` only for OIO transport so it's not applicable. (SO: https://stackoverflow.com/a/22897119)

**Comment by violetagg** [comment]
What about using Netty's functionality?
https://github.com/netty/netty/tree/4.1/handler/src/main/java/io/netty/handler/timeout

**Comment by danielra** [comment]
@smaldini When using the mentioned Flux#receive().timeout(xxx, xxx) approach, will the underlying (pooled) connection be closed / released upon timeout? Or is there a risk of exhausting the connection pool because the underlying connection(s) keep waiting to receive slow responses even though the application logic has moved on and won't actually care about the response?

**Comment by frko** [comment]
Due to the open state I wonder if the feature indeed was landed in version 0.8 or not.

We are quite eager to be able to use this feature within spring-cloud-gateway instead of hystrix or ribbon due to their deprecation with the last spring-cloud release.

**Comment by violetagg** [comment]
@frko Can't you use the Spring Gateway functionality? 
spring.cloud.gateway.httpclient.response-timeout

**Comment by frko** [comment]
I can but this will leak resources if the underlying connection isn't properly closed.

**Comment by violetagg** [comment]
https://projectreactor.io/docs/netty/release/reference/index.html#_lifecycle_callbacks
https://projectreactor.io/docs/netty/release/reference/index.html#_lifecycle_callbacks_2
