### ISSUE TITLE
Unable to use forwarded client IP in access log

### ISSUE THREAD

**Issue by MatthiasWinzeler** [reactor/reactor-netty#2603]
## Expected Behavior
It would be nice if the access log entries contain the forwarded client IP.

## Actual Behavior

When the `HttpServer` is configured to accept forwarded headers (i.e. `forwarded(true)`), the access log contains the IP of the peer that sent the http request (forwarded headers are not respected).

## Steps to Reproduce

Clone and run the app that enable forwarded headers and access logs:
https://github.com/MatthiasWinzeler/reactor-netty-forwarded-access-log

Then, fire a sample request containing a `Forwarded` header:

```bash
curl -v http://localhost:8080/hello -H 'Forwarded: for=192.0.2.60;proto=http;by=203.0.113.43'
/192.0.2.60:60365
```

You will notice that the server has successfully parsed the `Forwarded` header and set it on the `connectionInfo` which is printed as a response.

However, the access log will show the IP of the direct client (in this case 127.0.0.1):
```
[ INFO] (reactor-http-nio-2) 127.0.0.1 - - [06/Dec/2022:22:22:06 +0100] "GET /hello HTTP/1.1" 200 17 21
```

I see that we can pass our own `AccessLogFactory` so that we can customize the log format - however, this only has access to the `DefaultHttpRequest` and not the `ConnectionInfo`. So we'd have to parse the raw `Forwarded` request header again, and unfortunately the `Forwarded` parsing logic used within reactor-netty-http is not accessible.

## Possible Solution
- Could the access log by default respect the remote address from ConnectionInfo? Tomcat is doing a similar thing: https://stackoverflow.com/a/48180469 
- If not, could we make the `ConnectionInfo` accessible in the `AccessLogFactory` so that we can get the adjusted (real) client IP?

## Your Environment

* Reactor version(s) used: `2022.0.0`

Many thanks already in advance!

**Comment by pderop** [comment]
Hi @MatthiasWinzeler ,

Thanks for the reproducer demo, there is a PR in progress ... see #2606

**Comment by pderop** [comment]
Hi @MatthiasWinzeler ,

Can you confirm if what you need is to just have access to the remote address from the Forwarded header ? or do you also need  to get access to other attributes available from the Forwarded header, like the `proto` or `host`  attributes ?

thanks ?

**Comment by MatthiasWinzeler** [comment]
Hi @pderop 
Many thanks for the update - for us, the ability to use the `connectionInfo` within the access logging is sufficient.

**Comment by MatthiasWinzeler** [comment]
@pderop @violetagg this is really cool! do you have a planned release date for 1.0.26?

**Comment by violetagg** [comment]
> @pderop @violetagg this is really cool! do you have a planned release date for 1.0.26?

It is happening today

**Comment by MatthiasWinzeler** [comment]
hi @pderop 
many thanks for the fix!

we can confirm that it works - we use it as follows to be aligned with the default access log format:

```
AccessLog.create("{} - {} [{}] \"{} {} {}\" {} {} {}",
    Optional.ofNullable(args.connectionInformation())
            .map(ConnectionInformation::remoteAddress)
            .filter(InetSocketAddress.class::isInstance)
            .map(InetSocketAddress.class::cast)
            .map(InetSocketAddress::getHostString)
            .orElse("-"),
    args.user(),
    Optional.ofNullable(args.accessDateTime()).map(DateTimeFormatter.ISO_OFFSET_DATE_TIME::format).orElse("-"),
    args.method(), args.uri(), args.protocol(), args.status(),
    args.contentLength() > -1 ? args.contentLength() : "-", args.duration())
```
