### ISSUE TITLE
Reactor Netty adding content-length=0  header for 204 response code when HTTP/2

### ISSUE THREAD

**Issue by rudrajitgpt900** [reactor/reactor-netty#2620]
## Expected Behavior
A server MUST NOT send a Content-Length header field in any response
with a status code of 1xx (Informational) or 204 (No Content). A
server MUST NOT send a Content-Length header field in any 2xx
(Successful) response to a CONNECT request

## Actual Behavior
netty is adding content-length=0 header in 204 response

## Steps to Reproduce
Run a http request/response with response code 204

```java
 @Override
    @RequestMapping("/**")
    public ResponseEntity<?> handleReq(RequestEntity<byte[]> reqEntity,
                    @RequestHeader HttpHeaders reqHeaders) {
            HttpHeaders responseHeaderMap = new HttpHeaders();
            responseHeaderMap.set("abc11", "xyz11");
            responseHeaderMap.set("abc12", "xyz12");
            responseHeaderMap.set("abc13", "xyz13");
            responseHeaderMap.set("abc14", "xyz14");

            return (new ResponseEntity<byte[]>(responseHeaderMap, HttpStatus.NO_CONTENT));
    }
```

## Your Environment

* Reactor version(s) used:
* Other relevant libraries versions (eg. `netty`, ...): netty version 4.1.82
* JVM version (`java -version`): 17.0.5
* OS and version (eg. `uname -a`): Linux 4.14.35-1818.3.3.el7uek.x86_64

**Comment by violetagg** [comment]
@rudrajitgpt900 I created a small project based on the code that you provided and I cannot reproduce the issue.

https://github.com/violetagg/GH-2620

Request

`curl -X DELETE http://localhost:8080/ -v`

Response

```
> DELETE / HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/x.x.x
> Accept: */*

< HTTP/1.1 204 No Content
< abc11: xyz11
< abc12: xyz12
< abc13: xyz13
< abc14: xyz14
```

**Comment by rudrajitgpt900** [comment]
@violetagg You can check this on wireshark ,curl doesnt show this. Here is a sample screenshot captured 
![](https://files.slack.com/files-pri/T655JKQRX-F04G576BEBD/image.png)

**Comment by violetagg** [comment]
@rudrajitgpt900 I confirm that it is happening only with HTTP/2

**Comment by rudrajitgpt900** [comment]
Hi @violetagg  is there any way where we can make it not to add content-length=0 header in HTTP/2
 , any work around is there? also to highlight it happens with other methods having response 204, not just DELTE

**Comment by violetagg** [comment]
@rudrajitgpt900

How is you server configured:

- H2C
- HTTP/1 and H2C
- H2
- HTTP/1 and H2

**Comment by rudrajitgpt900** [comment]
@violetagg We use multiple servers, H2C and H2 both

**Comment by violetagg** [comment]
@rudrajitgpt900 As a workaround can you try the custom `ChannelHandler` below (just as an idea):

```
@Component
public class MyNettyWebServerCustomizer implements WebServerFactoryCustomizer<NettyReactiveWebServerFactory> {

	@Override
	public void customize(NettyReactiveWebServerFactory factory) {
		factory.addServerCustomizers(httpServer ->
				httpServer.doOnConnection(conn -> conn.addHandlerLast(MyCustomChannelHandler.INSTANCE)));
	}

	static final class MyCustomChannelHandler extends ChannelOutboundHandlerAdapter {

		static final MyCustomChannelHandler INSTANCE = new MyCustomChannelHandler();

		@Override
		public boolean isSharable() {
			return true;
		}

		@Override
		public void write(ChannelHandlerContext ctx, Object msg, ChannelPromise promise) {
			if (msg instanceof FullHttpResponse originalMsg) {
				if (originalMsg.status() == HttpResponseStatus.NO_CONTENT) {
					originalMsg.headers().remove(CONTENT_LENGTH);
				}
				ctx.write(originalMsg, promise);
			}
			else {
				ctx.write(msg, promise);
			}
		}
	}
}
```

**Comment by rudrajitgpt900** [comment]
@violetagg Hi, it seems to be working with the workaround you suggested . Just want to ensure that this workaround wont be causing any other issue. By when we can  expect official Netty Reactor  version with this fix available in it?
