### ISSUE TITLE
How to close or reset a http2 stream in Spring boot with embedded Netty server application?

### ISSUE THREAD

**Issue by anki0206** [reactor/reactor-netty#2621]
Our application runs on Springboot with embedded Netty server(enabled http2). And it exposes services via Rest Apis. On Rest Api call, we have a scenario where we wanted to ignore the http2 request without sending any response.

Our Environment: Reactor version(s) used: 
reactor-netty-http : 1.0.16 
JVM version (java -version): 17.0.1 
springBootVersion= 2.7.4

Do we have any support from Netty Server to close a http2 stream(request) without response?

Here is my code: 
GreetingController.java

```
public class GreetingController {
    private final GreetingService greetingService;
    public GreetingController(GreetingService greetingService) {
        this.greetingService = greetingService;
    }
    @GetMapping("/{name}")
    private Mono<String> greet(@PathVariable String name) {
        return greetingService.greet(name);
    }
 } 
```
DiscardOutBoundHandler.java
```
public class DiscardOutBoundHandler extends ChannelOutboundHandlerAdapter {

	@Override
	public void write(ChannelHandlerContext ctx, Object msg, ChannelPromise promise) throws Exception {
		System.out.println("Outbound Handler name: " + ctx.channel().pipeline().names());
        promise.channel().close();
	}

	@Override
	public void exceptionCaught(ChannelHandlerContext ctx, Throwable cause) { // (4)
		System.out.print("exceptionCaught call");
		cause.printStackTrace();
		ctx.close();
	}

}
```

NettyWebServerFactoryPortCustomizer,java

```
public class NettyWebServerFactoryPortCustomizer implements WebServerFactoryCustomizer<NettyReactiveWebServerFactory> {
    @Override
    public void customize(NettyReactiveWebServerFactory serverFactory) {
        Http2 h2 = new Http2();
        serverFactory.setHttp2(h2);
        serverFactory.addServerCustomizers(new PortCustomizer(8443));
        serverFactory.addServerCustomizers(
                httpServer -> httpServer.doOnChannelInit((connectionObserver, channel, remoteAddress) -> {
                    ChannelPipeline channelPipeline = channel.pipeline();
                    channelPipeline.addLast("encoder", new DiscardOutBoundHandler());
                }));

    }

    private static class PortCustomizer implements NettyServerCustomizer {

        private final int port;

        private PortCustomizer(int port) {
            this.port = port;
        }

        @Override
        public HttpServer apply(HttpServer httpServer) {
            return httpServer.port(port);
        }
    }
 }
```

**Comment by violetagg** [comment]
@anki0206

I'm a bit confused - from the provided code above it seems that you want to close the stream when you write some outbound data, while the question is: how to close a stream without writing anything.
Can you please clarify the scenario?

We would like to ask in the future to not cross post questions. Sometimes we need more information about the scenario and until we have such information we cannot answer the question. I see that you provided additional information in the question 11h ago. Sometimes we cannot answer immediately. Please bear with us.

Reference to the `stackoverflow` question https://stackoverflow.com/questions/74686926/how-to-close-or-reset-a-http2-stream-in-spring-boot-with-embedded-netty-server-a

**Comment by anki0206** [comment]
Apologies, to make you confuse but I just tried to give some idea what all changes I have tried to solve this problem. But still not able to  resolve it. I have used here ChannelOutBoundHandler to modify response as I don't want to send response .
Please help me How I can silently discard my response?

**Comment by violetagg** [comment]
@anki0206 Isn't it a solution for you if you return 500 Internal Server Error?

**Comment by anki0206** [comment]
Actually We don't want to send any response as We are sending more then 1000 request and out of 1000 we wanted to discard specific requests responses which can be more number so.

**Comment by violetagg** [comment]
@anki0206 Then may be something like the code below. However I will **strongly** recommend to research more about `WebFilter` because the code below is just an example how the native request can be accessed and I don't know how this will behave in your scenario. I don't recommend to go down to `Reactor Netty` API if something can be done with `Spring Framework` API.

```
@Component
public class MyFilter implements WebFilter {
	@Override
	public Mono<Void> filter(ServerWebExchange exchange, WebFilterChain chain) {
		ServerHttpRequest request = exchange.getRequest();
		if (request instanceof AbstractServerHttpRequest) {
			Object nativeRequest = ((AbstractServerHttpRequest) request).getNativeRequest();
			if (nativeRequest instanceof HttpServerRequest) {
				((HttpServerRequest) nativeRequest).withConnection(Connection::dispose);
			}
		}
		return chain.filter(exchange);
	}
}
```
