### ISSUE TITLE
When I read the http json data, a half packet request message occurs,

### ISSUE THREAD

**Issue by 1ssqq1lxr** [reactor/reactor-netty#2624]
## Expected Behavior
The body of the http request is complete

## Actual Behavior
When I read the http json data, a half packet request message occurs,

## Steps to Reproduce

```java
request
                .receive()
                .asString(StandardCharsets.UTF_8)
//                .map(this.toList(DashBoardConfig.class))
                .doOnNext(dashBoardConfigList -> {
                    ContextHolder
                            .getReceiveContext()
                            .getLogManager()
                            .printError(null, LogEvent.HTTP,dashBoardConfigList);
                }).then(response.then());
```

## Your Environment

* Reactor version(s) used:
* Other relevant libraries versions (eg. `netty`, ...):
* JVM version (`java -version`): jdk8
* OS and version (eg. `uname -a`):

**Comment by violetagg** [comment]
@1ssqq1lxr If you don't add a specific functionality related to json, Reactor Netty will not try to decode the incoming data.
What do you think about adding `JsonObjectDecoder` to the Netty pipeline. We have some examples in the tests - https://github.com/reactor/reactor-netty/blob/4da250f0aef4ef1cddd0d239b44925260cbaa549/reactor-netty-core/src/test/java/reactor/netty/tcp/TcpServerTests.java#L622

**Comment by 1ssqq1lxr** [comment]
> Okay, let me try

**Comment by 1ssqq1lxr** [comment]
> @1ssqq1lxr If you don't add a specific functionality related to json, Reactor Netty will not try to decode the incoming data. What do you think about adding `JsonObjectDecoder` to the Netty pipeline. We have some examples in the tests -
> 
> https://github.com/reactor/reactor-netty/blob/4da250f0aef4ef1cddd0d239b44925260cbaa549/reactor-netty-core/src/test/java/reactor/netty/tcp/TcpServerTests.java#L622

![image](https://user-images.githubusercontent.com/19258331/209267964-9dfe8475-60d3-4dcc-b373-31e0eb31b64f.png)
![image](https://user-images.githubusercontent.com/19258331/209268057-5a4bd9e5-5ae7-4db2-9c10-988f67e774e0.png)

There will still be one request for json to be parsed into two packages。

**Comment by 1ssqq1lxr** [comment]
> handle
The code for me to start HTTP is as follows. I did not use the handle method:

httpServer.port(httpConfig.getPort())

.route(new HttpRouterAcceptor(httpConfig))

.accessLog(httpConfig.isAccessLog())

.childOption(ChannelOption.TCP_NODELAY, true)

.option(ChannelOption.ALLOCATOR, PooledByteBufAllocator.DEFAULT)

.wiretap(false)

.bind()

I add the decoder in route. Is there any problem?

**Comment by violetagg** [comment]
@1ssqq1lxr Is it possible to provide some small complete example that I can use in order to understand better the issue?

**Comment by 1ssqq1lxr** [comment]
> @1ssqq1lxr Is it possible to provide some small complete example that I can use in order to understand better the issue?

 HttpServer.create().port(9999)
                .doOnConnection(connection -> connection.addHandlerLast(new JsonObjectDecoder()))
                .route(httpServerRoutes -> {
                    httpServerRoutes.post("/test/http",(httpServerRequest, httpServerResponse) -> {

                        return httpServerRequest
                                .receive()
                                .asString(StandardCharsets.UTF_8)
                                .flatMap(body -> {
                                    System.out.println(body);
                                    return httpServerResponse.then();
                                });
                    });
                })
                .accessLog(false)
                .childOption(ChannelOption.TCP_NODELAY, true)
                .option(ChannelOption.ALLOCATOR, PooledByteBufAllocator.DEFAULT)
                .wiretap(false)
                .bind().block();

Subcontracting may occur in the case of concurrent requests, resulting in incomplete json errors

**Comment by 1ssqq1lxr** [comment]
> > @1ssqq1lxr Is it possible to provide some small complete example that I can use in order to understand better the issue?
> 
> HttpServer.create().port(9999) .doOnConnection(connection -> connection.addHandlerLast(new JsonObjectDecoder())) .route(httpServerRoutes -> { httpServerRoutes.post("/test/http",(httpServerRequest, httpServerResponse) -> {
> 
> ```
>                     return httpServerRequest
>                             .receive()
>                             .asString(StandardCharsets.UTF_8)
>                             .flatMap(body -> {
>                                 System.out.println(body);
>                                 return httpServerResponse.then();
>                             });
>                 });
>             })
>             .accessLog(false)
>             .childOption(ChannelOption.TCP_NODELAY, true)
>             .option(ChannelOption.ALLOCATOR, PooledByteBufAllocator.DEFAULT)
>             .wiretap(false)
>             .bind().block();
> ```
> 
> Subcontracting may occur in the case of concurrent requests, resulting in incomplete json errors
  HttpServer.create().port(9999)
                .doOnConnection(connection -> connection.addHandlerLast(new JsonObjectDecoder()))
                .route(httpServerRoutes -> {
                    httpServerRoutes.post("/test/http",(httpServerRequest, httpServerResponse) -> {

                        return httpServerRequest
                                .receive()
                                .asString(StandardCharsets.UTF_8)
                                .flatMap(body -> {
                                    System.out.println(body);
                                    return httpServerResponse.then();
                                });
                    });
                })
                .accessLog(false)
                .childOption(ChannelOption.TCP_NODELAY, true)
                .option(ChannelOption.ALLOCATOR, PooledByteBufAllocator.DEFAULT)
                .wiretap(false)
                .bind().block();

**Comment by violetagg** [comment]
@1ssqq1lxr You need to switch to `addHandler(...)` instead of `addHandlerLast(...)` because `JsonObjectDecoder` needs additional functionality that will handle the HTTP data.

`.doOnConnection(connection -> connection.addHandler(new JsonObjectDecoder()))`

Can you try that?

**Comment by 1ssqq1lxr** [comment]
> @1ssqq1lxr You need to switch to `addHandler(...)` instead of `addHandlerLast(...)` because `JsonObjectDecoder` needs additional functionality that will handle the HTTP data.
> 
> `.doOnConnection(connection -> connection.addHandler(new JsonObjectDecoder()))`
> 
> Can you try that?

It seems that it is ok at present. I will continue to observe it for a while

**Comment by violetagg** [comment]
@1ssqq1lxr Let me close this one, we can reopen it if it is needed.

**Comment by 1ssqq1lxr** [comment]
ok



---Original---
From: "Violeta ***@***.***&gt;
Date: Tue, Jan 3, 2023 17:33 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [reactor/reactor-netty] When I read the http json data, a halfpacket request message occurs, (Issue #2624)




 
@1ssqq1lxr Let me close this one, we can reopen it if it is needed.
