### ISSUE TITLE
config IO_SELECT_COUNT 2,but the io select thread only one

### ISSUE THREAD

**Issue by abners** [reactor/reactor-netty#2625]
![image](https://user-images.githubusercontent.com/7392358/209269846-b05f6eaf-baee-4c71-8258-90dd1ebaf5dc.png)
I config the io select thread 2

## Expected Behavior

after application started,the io select thread should have 2

## Actual Behavior

there is only 1 io select thread 
![image](https://user-images.githubusercontent.com/7392358/209270007-3b80e56c-2788-4220-9839-b9f816ba8e4e.png)

No matter how many io select threads I configure，there‘s only have one io select thread actually

## Your Environment

* Reactor version(s) used:  reactory-netty 1.0.26
* netty 4.1.86
* Other relevant libraries versions (eg. `netty`, ...):
* spring cloud gateway: 3.1.4
* JVM version (`java -version`): 1.8
* OS and version (eg. `uname -a`): macos

**Comment by violetagg** [comment]
@abners Yes you are right, may be we need to clarify in the documentation that no more than 1 selector thread is used when there is a custom configuration.
Take a look here https://stackoverflow.com/questions/28665906/netty-boss-event-loop-and-executor, although the question is not about this, the answer explains very well the boss and worker `EventLoopGroup`.
Also this one https://stackoverflow.com/questions/28331809/netty-bootstrap-with-boss-group-or-with-just-with-workers-eventloopgroup explains when you may need boss `EventLoopGroup`.

**Comment by abners** [comment]
> 

ok，understand, thank you for your reply
