### ISSUE TITLE
Logging of AccessLog is broken for Buffering pipelined HTTP requests after versions upgrade

### ISSUE THREAD

**Issue by louchayaN** [reactor/reactor-netty#2628]
## Expected Behavior
Spring-cloud-gateway-server based on Reactor Netty is used. It just redirects requests to another services and does not have own REST api.
Sending of ordinary **'HHTP 1.1'** requests leads to **correct logging of AccessLog**.
reactor.netty.http.server.logging.AccessLogHandlerH1 works as expected
It is expected that sending of **'HTTP 1.1 Pipelining'** requests will be logged the same way

## Actual Behavior
But after updating of versions sending of **'HTTP 1.1 Pipelining'** leads to **incorrect logging of AccessLog**. 
For example 2 requests are sent in one pipeline. The log is:
`127.0.0.1 - - [26/dec/2022:19:47:43 +0200] "GET /test-api HTTP/1.1" 200 39 114`
**`127.0.0.1 - - [null] "null null null" 200 39 1672073263670`**
In the second log all information from the request is missing (nulls). And only the information from the response is present.

**The responses on 'HTTP 1.1 Pipelining' requests are retuned correct. The issue is only in logging of access logs.**

## Steps to Reproduce
- create simple Spring Boot application with spring-cloud-starter-gateway: 3.1.4
- enable AccessLog logging  (-Dreactor.netty.http.server.accessLogEnabled=true and logging configuration)
- configure spring cloud gateway request redirectation to any simple Tomcat service
-  run this Tomcat service with simple rest api
- send several HTTP 1.1 Pipelining requests to gateway. For examle, with org.apache.httpcomponents.core5 (https://github.com/apache/httpcomponents-core/blob/5.0.x/httpcore5/src/test/java/org/apache/hc/core5/http/examples/AsyncPipelinedRequestExecutionExample.java)

Code that reproduce steps can be found here:
https://github.com/louchayaN/access-log-bug

## Environment
* **bug is reproduced only during working with service as gateway** that redirects requests. If to add own REST api to the service and send 'HTTP 1.1 Pipelining' requests the acees logs are logged correctly.
* **this behaviour has appeared after migration** 
_spring-cloud-dependencies_ from Hoxton.SR10 to 2021.0.5
and accordinly
 _spring-cloud-starter-gateway_ from 2.2.7.RELEASE to 3.1.4 
 **_spring-boot-starter-reactor-netty_ from 2.3.8.RELEASE to 2.6.11**

## Notes
- Reactor netty qualifies http request as pipelining here: _reactor.netty.http.server.HttpTrafficHandler#channelRead (log 'Buffering pipelined HTTP request')_

**Comment by violetagg** [comment]
@louchayaN I'm gonna check this
