### ISSUE TITLE
Trace context is not propagated to Netty access logs

### ISSUE THREAD

**Issue by dameng58** [reactor/reactor-netty#2648]
Describe the bug
I'm using webflux + netty + spring cloud gateway + spring cloud sleuth to implement my gateway micro service.

webflux : 5.3.20
netty : 4.1.77.Final
spring cloud gateway :  3.1.2
spring cloud sleuth : 3.1.2

Sample:
when nginx sent a request to my gateway, and my gateway forward this request to other micso service, finally my gateway print access log.But in my access log, trace is null.

Start application with -Dreactor.netty.http.server.accessLogEnabled=true
![image](https://user-images.githubusercontent.com/31766257/212060579-c8c94b79-edab-4b64-a473-a5a8600ce999.png)

so , are there other configurations to be configured to solve this bug？

**Comment by dameng58** [comment]
And i have added reactor-netty-http-brave 1.0.24 in my pom, but it not work.

**Comment by dameng58** [comment]
@violetagg

**Comment by violetagg** [comment]
@dameng58 It seems that you can reproduce it, please provide a reproducible example.

**Comment by dameng58** [comment]
1、when i access a page, and the request will sent my gateway to forward offering service
![image](https://user-images.githubusercontent.com/31766257/212064241-75212bfc-fa6f-4595-be6c-7de3f0638017.png)
2、my gateway access.log:
![image](https://user-images.githubusercontent.com/31766257/212064550-89d8cf34-7e13-4ee6-aaa7-03e62786fcf3.png)
3、my offering service access.log:
![image](https://user-images.githubusercontent.com/31766257/212064690-1d952bcc-9d46-4d7b-ab40-8435b098690f.png)

my offering service is a springboot + tomcat + spring cloud sleuth, so it's ok.

**Comment by dameng58** [comment]
cloud u help me? @violetagg

**Comment by dameng58** [comment]
i find io.zipjin.brave 5.13.7 in my pom because of the use of brave.Tracer.
i get the trace id、 span id 、 parent id by brave.Tracer.currentSpan.

**Comment by violetagg** [comment]
@dameng58 I'm currently not able to reproduce your issue.

I generated one very simple application that demonstrates that the trace id is available for the access log.

https://github.com/violetagg/GH-2648

Request the application with `curl http://localhost:8080/get -v`
In the logs you can see
```
2023-01-12 14:44:00.901  INFO [,2041b2a475f17179,2041b2a475f17179] 31037 --- [ctor-http-nio-2] reactor.netty.http.server.AccessLog      : 127.0.0.1 - - [12/Jan/2023:14:44:00 +0200] "GET /get HTTP/1.1" 200 573 513
```

Check the project you may see some difference with your setup.

**Comment by dameng58** [comment]
@violetagg 
it works after i add the Bean of NettyServerCustomizer in my netty configuration.
![image](https://user-images.githubusercontent.com/31766257/212216461-dc6daea3-483f-4101-84f9-a4d791c3cb56.png)

thanks a lot.

**Comment by violetagg** [comment]
nice
