### ISSUE TITLE
Connection: keep-alive with Transfer-Encoding: chunked broken

### ISSUE THREAD

**Issue by joshiste** [reactor/reactor-netty#265]
It looks to me as if the chunked encoding in combination with keep-alive is broken using reactor-netty 0.7.3.

If this is not a reactor-netty issue but spring or spring boot, please let me know.

Sample steps to reproduce:
checkout https://github.com/joshiste/reactor-netty-issue
and run `mvn spring-boot:run`

run requests with keep-alive: `ab -n10 -l -c1 -k  http://localhost:8080/` --> broken
run request without keep-alive: `ab -n10 -l -c1  http://localhost:8080/` --> works

The exact dependency-versions are in `dependencies.txt` 

same example using tomcat works like a charm...

**Comment by violetagg** [comment]
Hi,

The issue here is that `ab` uses HTTP 1.0
#21 we need to introduce proper support for HTTP 1.0

As a workaround try to use wrk/wrk2 or other tool that supports HTTP 1.1

Regards,
Violeta

**Comment by joshiste** [comment]
I'm experiencing the same issue when using chrome!

**Comment by violetagg** [comment]
What are the steps that you follow when requesting via Chrome?

**Comment by joshiste** [comment]
Hmm I've a more complex application doing background fetches and after the fifth request the response just contains the headers and body is missing (figured out using tcpdump). When I set a `Connection: close` header everything is working...

**Comment by violetagg** [comment]
Can you provide some example?

**Comment by joshiste** [comment]
yeah I try to make sth up this weekend

**Comment by violetagg** [comment]
I'm closing this one, if you can provide reproducible example you can reopen the issue.

Regards,
Violeta
