### ISSUE TITLE
HttpClient adds Transfer-Encoding response header not sent by server in H2C mode

### ISSUE THREAD

**Issue by bclozel** [reactor/reactor-netty#2664]
This originally comes from a Spring Framework report: https://github.com/spring-projects/spring-framework/issues/29845
I've reduced the bug to a repro project that only involves a Tomcat server and Reactor Netty `HttpClient`.

In H2C mode only, the `HttpClient` considers that there is a  `transfer-encoding: chunked` response header, whereas it has never been sent by the server. I've checked that this header is indeed never sent by the server with curl and with an actual wireshark traffic capture session.

This could be a Reactor Netty issue, a Netty issue, a Tomcat issue or a combination of all of the above. The same behavior does not happen with an Undertow server or with a different choice of protocol.

This behavior can confuse clients since instead of having no response body at all, `HttpClient` considers that there is a body of length 0 (see the Spring Framework linked issue).

## Steps to Reproduce
Use the repro project here: https://github.com/bclozel/h2c-tomcat/tree/gh-29845

## Your Environment

* Reactor version(s) used: 2022.0.2
* JVM version (`java -version`): openjdk version "17.0.5" 2022-10-18 LTS
* OS and version (eg. `uname -a`): Darwin 22.2.0 Darwin Kernel Version 22.2.0: Fri Nov 11 02:08:47 PST 2022; root:xnu-8792.61.2~4/RELEASE_X86_64 x86_64

**Comment by violetagg** [comment]
@bclozel 

> This could be a Reactor Netty issue, a Netty issue, a Tomcat issue or a combination of all of the above. 

- Netty https://github.com/netty/netty/pull/13149
- Tomcat https://bz.apache.org/bugzilla/show_bug.cgi?id=66442

**Comment by bclozel** [comment]
Thanks a lot @violetagg !
