### ISSUE TITLE
followRedirect by predicate causes NullPointerException

### ISSUE THREAD

**Issue by gcorsaro** [reactor/reactor-netty#2670]
I want to follow the redirection applying some logic to keep track of redirected urls and also limit the number of redirections.
This is my code:

```
httpClient.followRedirect((req, res)-> {
		totalRedirects = res.redirectedFrom().length;
		log.debug("Redirect URL : " + res.resourceUrl());
		return totalRedirects<_maxRedirects;
```

Nevertheless when I use this approach I have a **NullPointerException** for each redirection step.
This exception come from line: 

> redirecting = new RedirectClientException(response.headers(), response.status()); 

in _reactor.netty.http.client.HttpClientOperations_ class

```
final boolean notRedirected(HttpResponse response) {
	if (isFollowRedirect() && followRedirectPredicate.test(this, this)) {
		if (log.isDebugEnabled()) {
			log.debug(format(channel(), "Received redirect location: {}"),
					httpMessageLogFactory().debug(HttpMessageArgProviderFactory.create(response)));
		}
		redirecting = new RedirectClientException(response.headers(), response.status());
		return false;
	}
	return true;
}
```

and

```
RedirectClientException(HttpHeaders headers, HttpResponseStatus status) {
	location = Objects.requireNonNull(headers.get(HttpHeaderNames.LOCATION));
	this.status = Objects.requireNonNull(status);
}
```
because of `location = Objects.requireNonNull(headers.get(HttpHeaderNames.LOCATION));` statement

No problem if I use `followRedirect(true)`

## Expected Behavior
Both approaches shouldn't raise any **NullPointerException**

## Actual Behavior
See above

## Possible Solution
Remove the check on Location header

## Your Environment
Spring boot 2.2.0-RELEASE

* Reactor version(s) used: 2022.0.2
* JVM version (`java -version`): java 8
* OS and version (eg. `uname -a`): Windows Server 2016

**Comment by violetagg** [comment]
@gcorsaro Your proposal is to `Remove the check on Location header`. Can you elaborate more on this? To what location should we redirect?

**Comment by gcorsaro** [comment]
@violetagg I was giving a look to the code and I noticed that when we use `followRedirect(true)` or `followRedirect(false)` it never goes inside the _if block_ of
```
if (isFollowRedirect() && followRedirectPredicate.test(this, this)) {
	if (log.isDebugEnabled()) {
		log.debug(format(channel(), "Received redirect location: {}"),
				httpMessageLogFactory().debug(HttpMessageArgProviderFactory.create(response)));
	}
	redirecting = new RedirectClientException(response.headers(), response.status());
	return false;
}
return true;
```
but it always return true.
Forget my suggestion which was based on a missing knowledge of the logic inside that block. 
However you can focus on my further investigation.
Thanks

**Comment by violetagg** [comment]
@gcorsaro I can see in the logs `Received redirect location:` when I execute the code below:

```
public class Application {

	public static void main(String[] args) {
		HttpClient client =
				HttpClient.create()
				          .followRedirect(true);

		client.get()
		      .uri("https://google.com")
		      .response()
		      .block();
	}
}
```

If I change to `.followRedirect(false)` configuration, then I do not see any more a redirection.

**Comment by gcorsaro** [comment]
@violetagg I might have not explained well what I meant. If you use `.followRedirect(boolean)` it works well without exceptions. Of course depending on the boolean value it follows or not the redirections.
We have the issue when we use the `.followRedirect(predicate)`. In that case there's the NullPointerException.
I have another clue, it seems that some headers are removed from the response when `.followRedirect(predicate)` is used.
I noticed because I have a snippet which tells me if the url points to an image or not (by checking the _Content-Type_ and, when I use the boolean version of followRedirect the header is there, if I use the predicate version the header disappears.
So I think the same situation happens for the **location** header, that's the reason of the NullPointerException.

**Comment by violetagg** [comment]
@gcorsaro Can you provide an example?

**Comment by gcorsaro** [comment]
Try this, you'll get the exception

```
.followRedirect((req, res)-> {
	return true;
})
```

**Comment by violetagg** [comment]
@gcorsaro yes see my comment above. When you use this with a predicate you are responsible to check whether or not this is a redirect. What we can fix in Reactor Netty is when NPE is thrown to log it and return the response and discard the result from the predicate. Is that what you are expecting?

**Comment by gcorsaro** [comment]
@violetagg do you mean that the _followRedirect_ is executed even if it's not a redirection?

**Comment by violetagg** [comment]
@gcorsaro Yes https://projectreactor.io/docs/netty/release/api/reactor/netty/http/client/HttpClient.html#followRedirect-java.util.function.BiPredicate-

```
Enables auto-redirect support if the passed [Predicate](https://docs.oracle.com/javase/8/docs/api/java/util/function/Predicate.html?is-external=true) matches.
```

**Comment by gcorsaro** [comment]
Ok clear, then, to answer your previous question, yes please. Don't throw the NPE and just return the response so the lifecycle can go ahead.
Many thanks for your support!
