### ISSUE TITLE
Headers not sent on WebSocket upgrade with 401 (UNAUTHORIZED) response

### ISSUE THREAD

**Issue by rstoyanchev** [reactor/reactor-netty#269]
### Expected behavior
After an authorization failure on a WebSocket upgrade request, the response status is set to 401 along with some authentication headers. The response completes.

### Actual behavior
The response never completes unless `response.sendHeaders()` is also called, which seems to be the case for WebSocket upgrade requests only, and not for HTTP requests where a call to `sendHeaders()` isn't necessary. 

### Steps to reproduce
During a WebSocket upgrade request, set the status to 401 and add some headers, but don't call `sendHeaders()`.

### Reactor Netty version
0.7.3

### JVM version (e.g. `java -version`)
Java 8

### OS version (e.g. `uname -a`)
Linux

This was originally reported in https://jira.spring.io/browse/SPR-16421.

**Comment by violetagg** [comment]
You should be able to test with the latest 0.7.4.BUILD-SNAPSHOT

**Comment by tsachev** [comment]
Thanks @violetagg it works now expected (without any workarounds) in my app.

**Comment by violetagg** [comment]
Thanks
