### ISSUE TITLE
RFC non complaince : RFC 7540 "Hypertext Transfer Protocol Version 2 (HTTP/2)" https://datatracker.ietf.org/doc/html/rfc7540

### ISSUE THREAD

**Issue by adhanoti** [reactor/reactor-netty#2702]
RFC behavior :

RFC7540 Section 8.1.2.3 : "All HTTP/2 requests MUST include exactly one
valid value for the ":method", ":scheme", and ":path" pseudo-header field,
unless it is a CONNECT request. An HTTP request that omits mandatory
pseudo-header fields is malformed."
RFC7540 Section 8.1.2.6 "Malformed requests or responses that are
detected MUST be treated as a stream error (Section 5.4.2) of type
PROTOCOL_ERROR"
RFC7540 Section 5.4.2 : "An endpoint that detects a stream error sends a
RST_STREAM frame (Section 6.4) that contains the stream identifier of the
stream where the error occurred. The RST_STREAM frame includes an error code
that indicates the type of error."

Actaul Issue - NRF is our network function.

Empty Path:
NRF does not reset the stream when :path pseudo-header field is empty
(without /).
See: 221003-114918_SBA_conformance_pseudoHeadersEmptyPath_172.19.124.pcap

Invalid Content-Length:
NRF sends RST_STREAM with CANCEL reason instead of PROTOCOL_ERROR when
content-length header is no correct for sent data.
See:
221003-114925_SBA_conformance_forbiddenHeadersContentLength_172.19.124.pcap

Invalid Connection-Specific header fields.
RFC7540 Section 8.1.2.2 "Connection-Specific Header Fields"
https://www.rfc-editor.org/rfc/rfc7540#section-8.1.2.2
Noted: Only valid connection-specific header field is "te" and must have
value of "trailers"

NRF does not reset stream when receiving a te header with a value other than
"trailers"
See:
221003-114929_SBA_conformance_forbiddenHeadersTE_172.19.124.pcap

NRF does not reset stream when receiving a request with other
connection-specific header fields.
See:
221003-114932_SBA_conformance_forbiddenHeadersTransferEncoding_172.19.124.pcap
for "transfer-encoding" and
221003-114939_SBA_conformance_forbiddenHeadersKeepAlive_172.19.124.pcap for
"keep-alive"

Also below behavior also non RFC complaince :

According :
- RFC7540 Section-8.1.2.6 : "A malformed request or response is one that is
an otherwise valid sequence of HTTP/2 frames but is invalid due to the
presence of extraneous frames, prohibited header fields, the absence of
mandatory header fields, or the inclusion of uppercase header field names."
- RFC7230 Section-3.2 , Section-3..2.6 and Section-1.2, which defines allowed
characters in header name and value fields

Netty version Used : 1.0.24
Reactor Netty Version : 1.0.24
Java version used : 17

Need to know whether Netty follow RFC 7540 and when the compliance will be available.

**Comment by violetagg** [comment]
@adhanoti Is it possible to try the latest `1.0.28` version? We do have some changes in the recent versions that might be relevant.

**Comment by adhanoti** [comment]
sure we will try, but can you please all the issues mentioned in
ticket addressed in 1.0.28 version.

Regards,
Ashish

**Comment by violetagg** [comment]
Below you can check the release notes

The issue that I was thinking about is #2623

https://github.com/reactor/reactor-netty/releases/tag/v1.0.25
https://github.com/reactor/reactor-netty/releases/tag/v1.0.26
https://github.com/reactor/reactor-netty/releases/tag/v1.0.27
https://github.com/reactor/reactor-netty/releases/tag/v1.0.28

**Comment by violetagg** [comment]
The latest version of the specification is https://datatracker.ietf.org/doc/html/rfc9113

**Comment by adhanoti** [comment]
@violetagg I have gone through the release notes which you shared and doesn't seems the issue mentioned is addressed. Can you please confirm when we will have those fixes addressed.

Regards,
Ashish

**Comment by violetagg** [comment]
@adhanoti ok then either please share how we can reproduce those or describe the scenario. If we can see the tcp dump it will help.

**Comment by adhanoti** [comment]
@violetagg : The issues are simple. attaching the pcap traces. 
[CNCES-8204.zip](https://github.com/reactor/reactor-netty/files/10791258/CNCES-8204.zip)

**Comment by violetagg** [comment]
@adhanoti Can you still update to the new releases? For example with version Reactor Netty 1.0.24/Netty 4.1.84.Final you are missing this fix https://github.com/netty/netty/commit/7127e6074c2f4b965305738d7756d196729b493e in Netty related to `te`.

**Comment by violetagg** [comment]
@adhanoti For the time being it seems the issues can be addressed directly in Netty. Please follow the Netty issue.
