### ISSUE TITLE
Reactor-netty memory leak causing direct buffer memory to increase 

### ISSUE THREAD

**Issue by arpit-hotstar** [reactor/reactor-netty#2729]
Problem that we saw with reator netty causing the direct buffer to go out of the memory with increasing time. we tried running the java application with jvm opts `-Dio.netty.leakDetection.level=paranoid`

Direct buffer increase :

 ![link](https://user-images.githubusercontent.com/114410166/226138552-f5a4740e-c319-4109-b71a-014e07c953d8.png)

We have not set any `maxDirectMemory` or  `MaxDirectMemorySize ` size explicitly, its using default values.

We got couple of memory leak via leak-detector, below are logs :[ Detailed logs link](https://drive.google.com/file/d/1r_fXASllZw0UMPQvhwo6tkMsJJl9griN/view?usp=share_link)

```
{"timestamp":"1679145850958","level":"ERROR","thread":"reactor-http-nio-5","logger":"io.netty.util.ResourceLeakDetector","message":"LEAK: ByteBuf.release() was not called before it's garbage-collected. See https://netty.io/wiki/reference-counted-objects.html for more information.\nRecent access records: \n
```

* Spring boot : 2.3.12-Release
* Reactor-netty version(s) used: 0.9.20-Release
* JVM version (`java -version`): 
openjdk 11.0.10 2021-01-19
OpenJDK Runtime Environment 18.9 (build 11.0.10+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.10+9, mixed mode, sharing)

Want to check, Is there any memory leak with reactor-netty 0.9.20 ? Or any way we can resolve this memory leak that observed with reactor-netty ?

Internal module version of reactor netty :  
```
 \- io.projectreactor.netty:reactor-netty:jar:0.9.20.RELEASE:compile
[INFO] |  |     +- io.netty:netty-handler:jar:4.1.65.Final:compile
[INFO] |  |     \- io.netty:netty-handler-proxy:jar:4.1.65.Final:compile
[INFO] |  |        \- io.netty:netty-codec-socks:jar:4.1.65.Final:compile
```

**Comment by violetagg** [comment]
@arpit-hotstar Please follow the description here https://projectreactor.io/docs/netty/release/reference/index.html#faq.memory-leaks and provided the additional information that you will obtain. This one `-Dio.netty.leakDetection.level=paranoid` is not enough.

Also I would say your Reactor Netty version is old and not supported anymore.

**Comment by violetagg** [comment]
@arpit-hotstar I'm closing the one. We can reopen it when you provide the requested information.
