### ISSUE TITLE
The number of file descriptor is continually increasing

### ISSUE THREAD

**Issue by timewizhan** [reactor/reactor-netty#2743]
As a service is operated for a long time, the number of file descriptor is continually increasing.
For reference, the service simply sends and receives requests
(The relevant indicators are shown in the figure below)

![image](https://user-images.githubusercontent.com/10267473/227581554-6415657b-b0e9-4ed2-8bfb-5d40d2bdc86d.png)

When I checked the file descriptors using 'netstat', most of them is that status was 'TIME_WAIT'.
And then, since I have constantly monitored for some days, I realized that the number of 'TIME_WAIT' is increasing faster than it is decreasing.

Have you ever had a case where the internal socket may not be closed?
If not, is it simply because of the high traffic?

related to: https://github.com/reactor/reactor-netty/issues/1163

## Your Environment

* Reactor version(s) used: 1.0.16
* Other relevant libraries versions (eg. `netty`, ...): netty 4.1.74.Final, Spring Boot 2.6.4
* JVM version (`java -version`): 
openjdk version "1.8.0_202"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_202-b08)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 1.8.0_202-b08, mixed mode)

**Comment by pderop** [comment]
Hi @timewizhan ,

TIME WAIT state is entered by an Active Closer (the party who first closes a connection / sends the first FIN).
So, if you observe some increasing number of TIME_WAIT sockets on the service machine, then I believe it's a symptom that your service is doing lots of short lived connections which are opened and closed very often and the close is done by your service.

There are few possibilities:

For example, if you are using reactor-netty HttpClient, and http/1.1:

- the service sends some HTTP/1.1 requests , but the server responds with a "Connection: close" header: this means that the connection is not persistent and will be closed by the HttpClient once the response is received (hence , explaining TIME_WAITs)
- or the service sends some HTTP/1.1 requests using "Connection: close" header, meaning that the connection is not persistent, so it is the same, the HttpClient will close the connection once the response is received
- or another example: your reactor-netty `ConnectionProvider` is configured with very low value for `maxIdleTime`, or `maxLifeTime`, or `maxLifeTime`, which would explain why connections are often closed by the service.

Now, I tested using the latest 1.0.30, or even using 1.0.16 version, and I don't observe any increasing TIME_WAITs connections.

So, I suggest to do the following:

- do a wireshark and confirm that the connections are closed by the service (it is the service which is sending the first FIN)
- from wireshark, if protocol used is HTTP/1.1, check if the connections are persistent. If there is a Connection: close header in either requests or responses, then it will explain why you observe some TIME_WAITs
- if you are using the reactor-netty HttpClient, check the configuration for `maxIdleTime`, or `maxLifeTime`, or `maxLifeTime`. If these parameters are configured with very low values, then increase the values
- with `lsof -i`, check that the TIME_WAIT connections really comes from your service, not for example from another script which could send many http requests using curl for example.

Then you will be able to make a first diagnostic. If none of the above can explain the presence of growing TIME_WAIT sockets, then I will need a reproducing scenario.

thanks.

**Comment by timewizhan** [comment]
Thanks a lot. :)

Based on your suggestion, I will check and monitor it.

**Comment by pderop** [comment]
@timewizhan ,

I'm closing this one, but if course, if you have some updates, don't hesitate to reopen this issue and we will look into it.
thanks
