### ISSUE TITLE
Memory leak in DefaultPooledConnectionProvider

### ISSUE THREAD

**Issue by Rainlone** [reactor/reactor-netty#2759]
I create ConnectionProvider like this：

```
 ConnectionProvider newConnectionProvider = ConnectionProvider.builder(name)
            .maxConnections(maxConnections)
            .pendingAcquireMaxCount(pendingAcquireMaxCount)
            .disposeInactivePoolsInBackground(Duration.ofMinutes(disposeInterval.get()), Duration.ofMinutes(inactiveInterval.get()))
            .pendingAcquireTimeout(Duration.ofMillis(pendingAcquireTimeout))
            .build();
```

I creative WebClient like this：

```
    private WebClient createWebClient(long timeout) {
        TransmitScene scene = TransmitScene.RTA;
        HttpClient httpClient = HttpClient.create(scene.getConnectionProvider())
            .observe(connectionHealthCheckObserver)
            .tcpConfiguration(tcpClient -> tcpClient.option(ChannelOption.SO_KEEPALIVE, true)
                .option(ChannelOption.TCP_NODELAY, true)
                .option(ChannelOption.CONNECT_TIMEOUT_MILLIS, scene.getConnectTimeout()))
            .responseTimeout(Duration.ofMillis(timeout));
        return WebClient.builder().clientConnector(new ReactorClientHttpConnector(httpClient)).build();
    }
```

This is high performance parallel interface, WebClient is created per request，because the url，header,address，might be different.
And then it happened OOM in production environment. We analyse heap-dump, the channelPools is a large object in memory.

![image](https://user-images.githubusercontent.com/52027380/229437788-c648bcd2-ab6a-4f87-b2a4-c7c660719ed0.png)

Can you help me?

## Expected Behavior

Normal running
## Actual Behavior

Happened OOM
## Steps to Reproduce

```java
@Test
public void repoCase() {

}
```

## Your Environment

* Reactor version(s) used:reactor-netty-core 1.0.17.RELEASE
* Other relevant libraries versions (eg. `netty`, ...):
* JVM version (`java -version`):1.8
* OS and version (eg. `uname -a`):

**Comment by violetagg** [comment]
@Rainlone Please check the documentation https://projectreactor.io/docs/netty/release/reference/index.html#_connection_pool_2

When you specify `disposeInactivePoolsInBackground` you need to know that this takes effect only when:

```
When this option is enabled, connection pools are regularly checked in the background, and those that are empty and been
inactive for a specified time become eligible for disposal. Connection pool is considered empty when there are no active
connections, idle connections and pending acquisitions. By default, this background disposal of inactive pools is disabled.
```

I don't see any setting like `maxIdleTime` etc. so most probably your connection pools are not *empty*. Can you please check this?

**Comment by violetagg** [comment]
> @violetagg I'm sorrey, the maxIdleTime,maxLifeTime,pendingAcquireTimeout,evictInBackground is not be configured , I only configure disposeInactivePoolsInBackground.
> May be because of this？

Yes, if the connection pool is not *empty* it won't be disposed. When you do not have settings for eviction then the connections will stay in the pool as idle connections which means that the pool is not empty.

**Comment by violetagg** [comment]
@Rainlone I'm closing this issue, if needed we can reopen it.
