### ISSUE TITLE
block() on ServerHttpRequest.getBody().buffer() hangs forever wher body exceeds 350bytes

### ISSUE THREAD

**Issue by myninjagos** [reactor/reactor-netty#277]
```
        @Bean
	public HttpHandler httpHandler(ApplicationContext applicationContext) {
		return (request, response) -> {
			List<DataBuffer> b =  request.getBody().buffer().blockFirst();
			here execution hangs
			....
		}
        }

```
this happens when sending data > 350bytes

**Comment by myninjagos** [comment]
please, consider that same behavior is, using:

```
	@Bean
	public RouterFunction<?> myRouterFunction() {
		return route(path("/api/**"), r -> {
			r.bodyToFlux(DataBuffer.class).buffer().blockFirst();
			here execution hangs
			...
		});
	}

```

**Comment by violetagg** [comment]
Hi,

I cannot reproduce this behaviour.
Please provide more information with an example if possible.
Also provide information for Spring Framework version, Reactor Netty version.
What kind of client do you use in order to send the data?

Regards,
Violeta

**Comment by myninjagos** [comment]
Hi,

my test is:
curl -X PUT \
  http://localhost:8282/api/v1.0/xyz \
  -H 'accept: application/json' \
  -H 'content-type: application/json' \
  -d '{"a": "012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890"}'

i have tested with chrome (swagger), firefox (swagger). postman and curl. 
curl is the only one that works. the other ones are not..

all these clients have something in common: Connection=[keep-alive]
and some others like:
Origin=[chrome-extension: //fhbjgbiflinjbdggehcddcbncdddomop],
Accept-Encoding=[gzip, deflate, br],
Accept-Language=[en-US, en;q=0.9]
cache-control=[no-cache]
postman-token=[d5e458d5-0dc5-f10a-bf09-34b6f484e8d6]

i will dig further and i will let you know.

spring-boot-starter-parent 
2.0.0.RC1
  --> spring-boot-starter
  --> spring-boot-starter-webflux

regards
Vassilis

**Comment by myninjagos** [comment]
Hi,
after a hard week back again but, unfortunately with bad news:)

i tested the curl posted above into four different machines: 3 inside my company network including mine and my home pc
all 3 failed again but, testing into my pc worked. 
that make me think that company infrastructure was the problem.
increasing the request body (>2K) the test failed again but with another error: NullPointerException
at request.getBody().buffer().blockFirst().size()

curl does not send the whole body and sends 100-Continue
at this point  request.getBody().buffer().blockFirst is null. 

can you please check with a larger input?
thank you for your time

ps
spring-boot-starter-parent --> 2.0.0.RC2

netty logs
|00000000| 50 55 54 20 2f 61 70 69 2f 76 31 2e 30 2f 64 72 |PUT /api/v1.0/dr|
|00000010| 61 77 73 2f 31 2f 31 20 48 54 54 50 2f 31 2e 31 |aws/1/1 HTTP/1.1|
|00000020| 0d 0a 48 6f 73 74 3a 20 6c 6f 63 61 6c 68 6f 73 |..Host: localhos|
|00000030| 74 3a 38 32 38 32 0d 0a 55 73 65 72 2d 41 67 65 |t:8282..User-Age|
|00000040| 6e 74 3a 20 63 75 72 6c 2f 37 2e 34 37 2e 30 0d |nt: curl/7.47.0.|
|00000050| 0a 41 63 63 65 70 74 3a 20 2a 2f 2a 0d 0a 63 6f |.Accept: */*..co|
|00000060| 6e 74 65 6e 74 2d 74 79 70 65 3a 20 61 70 70 6c |ntent-type: appl|
|00000070| 69 63 61 74 69 6f 6e 2f 6a 73 6f 6e 0d 0a 43 6f |ication/json..Co|
|00000080| 6e 74 65 6e 74 2d 4c 65 6e 67 74 68 3a 20 31 31 |ntent-Length: 11|
|00000090| 39 38 0d 0a 45 78 70 65 63 74 3a 20 31 30 30 2d |98..Expect: 100-|
**|000000a0| 63 6f 6e 74 69 6e 75 65 0d 0a 0d 0a             |continue....    |**

**Comment by violetagg** [comment]
we are working on an issue with 100-continue #293

**Comment by myninjagos** [comment]
thank you!

**Comment by violetagg** [comment]
Can you try the snapshot  version?
The snapshot contains the fix for 100-continue.

**Comment by myninjagos** [comment]
Hi,
just tried the snapshot version and the result is just the same for both cases

about #293, the main difference is that you can work with body after calling one of HttpServerRequest.receive... methods. 
ServerHttpRequest does not provide such an api

regards

**Comment by myninjagos** [comment]
we use webflux in two modes:
a) as a proxy for other rest services
b) RestController

so, the idea is to check request's path and if for example starts with /api/xyz proxy to http://... else, serve it as an ordinary RestController bean
for the first case first attempt was to use a RouterFunction

```
	@Bean
	public RouterFunction<?> myRouterFunction() {
		return route(RequestPredicates.path("/api/**"), r -> {
			ByteBuffer b = request.bodyToFlux(ByteBuffer.class).reduce(ByteBuffer::put).block();
			//do things with body ..
			return ServerResponse.ok().build();
		});
	}
```

can you please suggest another way?

thank you

**Comment by rstoyanchev** [comment]
For  once avoid blocking by creating a single processing chain:
```
@Bean
public RouterFunction<?> myRouterFunction() {
	return route(RequestPredicates.path("/api/**"), request ->
			request.bodyToFlux(ByteBuffer.class)
					.reduce(ByteBuffer::put)
					.flatMap(byteBuffer -> {
						//do things with body ..
						return ServerResponse.ok().build();
					}));
}
```
Also you are aware of Spring Cloud Gateway does this also using WebFlux, and you don't need to build your own?

**Comment by myninjagos** [comment]
you are right!

just for the record, i did the following

```
	@Bean
	public RouterFunction<?> myRouterFunction() {
		
		return route(RequestPredicates.path("/api/**"), r -> {
			DataBuffer buffer = new DefaultDataBufferFactory().allocateBuffer();
			
			return r.bodyToFlux(DataBuffer.class).flatMap(b -> {
				buffer.write(b);
				return Mono.empty();
			})
			.then(...do something with buffer);
		});
	}

```
thank you for your time

**Comment by rstoyanchev** [comment]
You need to be careful when using DataBuffer, since you need to release the buffers which [are pooled](https://docs.spring.io/spring/docs/current/spring-framework-reference/core.html#code-pooleddatabuffer-code). If your goal is to aggregate the body there is a convenient utility method for that, see `DataBufferUtils.join`.

**Comment by myninjagos** [comment]
DataBufferUtils.join(r.bodyToFlux(DataBuffer.class)).flatMap sounds better:)

many thanks
