### ISSUE TITLE
HttpServer read related timeouts

### ISSUE THREAD

**Issue by philsttr** [reactor/reactor-netty#2770]
## Motivation

Allow the HttpServer to eagerly close slow connections.

Slow connections can be a drag on a server, and can even be malicious.  It would be great if the http server could proactively close them.

## Desired solution

Three specific timeout configuration values for HttpServer.  Feel free to adjust the naming.
* `connectionTimeout` - The request URI line is not received in a specific amount of time for new connections.
* `readTimeout` - connection is established, the request URI is received, the full request headers/body has not completed, and the server has not received any data in a specific amount of time
* `requestTimeout` - connection is established, the request URI is received, but the full request headers/body has not fully completed within a specific amount of time

## Considered alternatives

It's probably possible to configure each of these by adding/removing various handlers to the channel at specific points.  But, I'm really hoping for easy config values, and a properly supported implementation.

## Additional context

These are somewhat similar to [Tomcat's `connectionTimeout` and `connectionUploadTimeout`](https://tomcat.apache.org/tomcat-10.1-doc/config/http.html#Standard_Implementation).

**Comment by violetagg** [comment]
@philsttr For which version do you need these configurations? 1.0.x or 1.1.x?

**Comment by philsttr** [comment]
1.1.x would be fine

**Comment by philsttr** [comment]
>We already have handshakeTimeout and idleTimeout, which should cover Tomcat's connectionTimeout and keepAliveTimeout.

Great!  I assume the `idleTimeout` takes effect before the first request and between requests, correct?

> For these two readTimeout and requestTimeout, my understanding is that the first is related to the different read operations while the second one is related for the whole request, is that correct?

Yes.

For `readTimeout`, think about a client that sends one character at a time 10s apart.  Setting the readTimeout to 9s should kill this connection.

For `requestTimeout`, think of that same client sending one character at a time 8s apart (thereby satisfying the new 9s readTimeout), but still taking foooorever to complete the full request.  I want this connection killed too.

**Comment by violetagg** [comment]
> Great! I assume the idleTimeout takes effect before the first request and between requests, correct?

Yes it is related to the very first request and between requests

> For readTimeout, think about a client that sends one character at a time 10s apart. Setting the readTimeout to 9s should kill this connection.

For requestTimeout, think of that same client sending one character at a time 8s apart (thereby satisfying the new 9s readTimeout), but still taking foooorever to complete the full request. I want this connection killed too.

Thanks for the confirmation

**Comment by violetagg** [comment]
@philsttr PTAL #2836
