### ISSUE TITLE
Sleuth TraceId missing in Netty HttpClient WRITE event if same 'reactor-http-nio' thread is used

### ISSUE THREAD

**Issue by syedyusufh** [reactor/reactor-netty#2793]
Lately after **Spring Boot 2.7.6** (corresponding netty release), Sleuth TraceId is missing in the **WRITE** event of our custom Logging Handler if same '**reactor-http-nio**' thread is used. First request using the new thread logs the traceId perfectly, subsequent request is missing the TraceId only for the **WRITE** event. **READ** event is fine.

We are currently on **Spring Boot 2.7.11** with latest Project Reactor and Sleuth dependencies.

```
HttpClient.create()
	.doOnRequest((request, connection) -> connection.addHandlerFirst(loggingHandler))
```

```
@Component
public class PayloadLogger extends LoggingHandler {

	@Autowired
	public PayloadLogger() {

		super(HttpClient.class, DEBUG, SIMPLE);
	}

  @Override
  protected String format(ChannelHandlerContext ctx, String event, Object arg) {

	if (arg instanceof ByteBufHolder byteBufHolder && StringUtils.equalsAny(event, WEBCLIENT_LOGGING_READ_EVENT, WEBCLIENT_LOGGING_WRITE_EVENT)) {

		var logMsg = byteBufHolder.content().toString(UTF_8);

		// WRITE
		if (WEBCLIENT_LOGGING_WRITE_EVENT.equals(event))
			return "Request Payload: " + logMsg;

		// READ
		if (WEBCLIENT_LOGGING_READ_EVENT.equals(event)) {
```

**Comment by violetagg** [comment]
@syedyusufh Can you please elaborate more why you think this is a Reactor Netty issue? Reactor Netty does not control Spring Sleuth implementation - when and how trace id is created and propagated.

**Comment by syedyusufh** [comment]
Thanks for the quick revert @violetagg 

Well, it is hard to tell if it is Netty or Sleuth issue clearly as the first request on the same thread works perfectly fine, only the subsequent requests on the same thread is having issue, that too ONLY for the WRITE event.

Please let me know if any additional information is required that can help further debug this behavior.

**Comment by violetagg** [comment]
@syedyusufh I think that this issue is better suited for Spring Sleuth project.

**Comment by syedyusufh** [comment]
Sure thing, please mark as Closed. Thanks
