### ISSUE TITLE
Keepalive doesn't seem to be working

### ISSUE THREAD

**Issue by esfomeado** [reactor/reactor-netty#2797]
I want to enable keepalives on my server to send a keepalive packet every x seconds.

I followed the documentation and did the following:

```java
    @Override
    public void customize( NettyReactiveWebServerFactory factory )
    {
        factory.addServerCustomizers( builder -> builder.childOption( ChannelOption.SO_KEEPALIVE, true )
                                                        .childOption( EpollChannelOption.TCP_KEEPIDLE, 3 )
                                                        .childOption( EpollChannelOption.TCP_KEEPCNT, 100 )
                                                        .childOption( EpollChannelOption.TCP_KEEPINTVL, 1 ) );
    }
```

In this case for testing purposes if it's idling for 3s we send a keepalive but looking at wireshark I never saw it happen.

## Expected Behavior

It should send a keepalive

## Actual Behavior

Keepalive is not send

## Steps to Reproduce

[netty-test.zip](https://github.com/reactor/reactor-netty/files/11414773/netty-test.zip)

## Your Environment

* Reactor version(s) used: 1.1.6
* Other relevant libraries versions (eg. `netty`, ...): Netty 4.1.91.Final
* JVM version (`java -version`): Java 17
* OS and version (eg. `uname -a`): Ubuntu 22.04

**Comment by pderop** [comment]
I'm sorry, but I cannot reproduce the issue using your reproducer sample project.

I have installed it on a linux Ubuntu 22.04.1, but it seems to work for me, however, I had to comment the `server.netty.idle-timeout=10` property in src/main/resources/application.properties: else, when I do a `telnet server_ip_addr 8080` command, the telnet is getting closed immediately after 10 milliseconds.
So, using a telnet command, I can see that some keep-alive probes are sent by the server to the telnet client:

telnet server-ip-addr 8080
is giving:

![Screenshot 2023-05-09 at 08 55 23](https://user-images.githubusercontent.com/650758/237024262-e6092dd4-001d-4953-98da-822b21af0b4a.jpg)

**Comment by esfomeado** [comment]
I will give it a try and I will let you know my findings.

**Comment by esfomeado** [comment]
@pderop I followed your steps but still doesn´t work for me so I´m assuming that is something on my side. Will investigate further and I will reopen this ticket once I have more details.
