### ISSUE TITLE
Netty tcnative 2.0.60 has small memory leak and should be upgraded to 2.0.61

### ISSUE THREAD

**Issue by j-bahr** [reactor/reactor-netty#2798]
Latest releases for reactor-netty depend on netty tcnative 2.0.60, which is marked bad by netty maintiners due to memory leak. Deps should be upgrade to 2.0.61 to avoid the memory leak.

The tcnative bug fix can be found here https://github.com/netty/netty-tcnative/commit/fd8fb2a4db697734edf9834559de5b9fcc4f0574

The netty PR showing required upgrade here here: https://fburl.com/spju5220

**Comment by violetagg** [comment]
@j-bahr Reactor Netty does not have dependency on Netty tcnative.

**Comment by j-bahr** [comment]
Hi @violetagg  thanks for the fast reply, can you help me understand why it's listed in the release notes?

<img width="763" alt="Screenshot 2023-05-09 at 1 50 26 PM" src="https://github.com/reactor/reactor-netty/assets/111525238/9e9335a5-4913-4ca1-b0c3-632d87c91629">

You have a PR that pulls in the latest version here https://github.com/reactor/reactor-netty/pull/2780/files?

It also seems to be a transitive dependency of netty itself? https://github.com/reactor/reactor-netty/blob/main/build.gradle#L103

Thanks!

**Comment by violetagg** [comment]
@j-bahr This is used only for testing purposes https://github.com/reactor/reactor-netty/blob/00a882c8507bd1a874dadad0ed2a21bff6dfa2e1/reactor-netty-http/build.gradle#L158

**Comment by violetagg** [comment]
@j-bahr Can you tell me which module has a transitive dependency from Netty to Netty tcnative?

**Comment by j-bahr** [comment]
I thought that it was pulled in from the uber jar `io.netty:netty-all:4.1.92.Final` but it appears that it is not. We must include this dep explicitly, I can pin my own version to known good release. Sorry for the confusion.

**Comment by violetagg** [comment]
@j-bahr yeah Reactor Netty doesn't depend on `netty-all`, we prefer only to depend on specific netty modules.

**Comment by violetagg** [comment]
I updated the version for our test dependency #2799
