### ISSUE TITLE
reactor-netty-http-1.0.19  - SSLEngine Closed Already

### ISSUE THREAD

**Issue by sholmes321** [reactor/reactor-netty#2823]
We are using reactor-netty-http-1.0.19 library for initializing a HttpClient in our pods for our Kubernetes cluster. We are seeing intermittent errors for "SSLEngine Closed Already". Restarting the pod seems to mitigate the issue, but it will still occur. 

Stack trace:
`... Error has been observed at the following site(s): 	|_ ⇢ at reactor.netty.FutureMono.deferFuture(FutureMono.java:69) 	|_ Mono.thenEmpty ⇢ at reactor.netty.ReactorNetty$OutboundThen.<init>(ReactorNetty.java:557) 	|_ ⇢ at reactor.netty.ReactorNetty$OutboundThen.then(ReactorNetty.java:602) 	|_ Flux.concat ⇢ at org.springframework.http.client.reactive.AbstractClientHttpRequest.doCommit(AbstractClientHttpRequest.java:135) 	|_ Flux.then ⇢ at org.springframework.http.client.reactive.AbstractClientHttpRequest.doCommit(AbstractClientHttpRequest.java:135)`

Do you know what might be the reason for the error and how we could fix it?

## Expected Behavior

Http connections should be being created on free connections in the pool.
## Actual Behavior

 Http connection that was already closed is being used again in the pool of connections.
## Steps to Reproduce

```java
@Test
public void repoCase() {

}
```

## Your Environment

* Reactor version(s) used:
* Other relevant libraries versions (eg. `netty`, ...): reactor-netty-http-1.0.19
* JVM version (`java -version`): 11
* OS and version (eg. `uname -a`):

**Comment by violetagg** [comment]
@sholmes321 You version is old. Try to update your components. We do have fixes for this issue in the newer version.

**Comment by sholmes321** [comment]
@violetagg Thanks for the response! 
Do you know what might be the root cause of this "SSLEngine closed already" in this old version?

**Comment by violetagg** [comment]
@sholmes321 Check this PR #2518

**Comment by violetagg** [comment]
@sholmes321 You can try this however I cannot say whether this is related to your use case or not.
