### ISSUE TITLE
The request forwarding is not effective.

### ISSUE THREAD

**Issue by sngths** [reactor/reactor-netty#2826]
I am using Reactor Netty server to implement request forwarding. The following code can print the received data, but it does not successfully return any response. The HTTP response body is empty. Can you please help me identify the reason? Below is my code:
<img width="1122" alt="1686281312469" src="https://github.com/reactor/reactor-netty/assets/13965505/c7c2adc3-22ef-4071-b415-e1ab38ea72bc">

**Comment by violetagg** [comment]
@sngths Thanks for getting in touch, but it feels like this is a question that would be better suited to [Gitter](https://gitter.im/reactor/reactor-netty). As mentioned in [README](https://github.com/reactor/reactor-netty/#getting-help), we prefer to use GitHub issues only for bugs and enhancements.
I see that you already opened a [Gitter thread](https://matrix.to/#/!rdZMIWMDXqzVEagqCt:gitter.im/$Fa-TCh9q7RkAhoEXL1P7VlRFmiXXhZduBVs3i_l78wc?via=gitter.im&via=matrix.org&via=mozilla.org), let's continue there.
