### ISSUE TITLE
reactor.core.Exceptions$ErrorCallbackNotImplemented: reactor.netty.internal.shaded.reactor.pool.PoolAcquireTimeoutException: Pool#acquire(Duration) has been pending for more than the configured timeout of 45000ms

### ISSUE THREAD

**Issue by 1ssqq1lxr** [reactor/reactor-netty#2834]
The client that creates a large number of websockets can only create around 9000 connections if an exception is thrown at this time

## Exception
2023-06-16 10:45:00 [parallel-9] ERROR reactor.core.publisher.Operators - Operator called default onErrorDropped
reactor.core.Exceptions$ErrorCallbackNotImplemented: reactor.netty.internal.shaded.reactor.pool.PoolAcquireTimeoutException: Pool#acquire(Duration) has been pending for more than the configured timeout of 45000ms
Caused by: reactor.netty.internal.shaded.reactor.pool.PoolAcquireTimeoutException: Pool#acquire(Duration) has been pending for more than the configured timeout of 45000ms
	at reactor.netty.internal.shaded.reactor.pool.AbstractPool$Borrower.run(AbstractPool.java:413)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```java
public class WebSocketSender implements Sender<WebSocketConfig> {


    private LoopResources loopResources;

    private final AtomicLong atomicLong = new AtomicLong(1);

    private List<Connection> connectionList = new ArrayList<>();

    private final ScheduledExecutorService executorService = Executors.newScheduledThreadPool(Runtime.getRuntime().availableProcessors());

    @Override
    public void start(WebSocketConfig config) {
        if (config.getThreads() == 0) {
            config.setThreads(Runtime.getRuntime().availableProcessors() * 2);
        }
        this.loopResources = LoopResources.create("websocket", 1, config.getThreads(), true);
        List<InetAddress> inetAddresses = this.batchCreateKInetAddress(config.getNetworks());
        this.createConnect(config, inetAddresses);
    }

    private void createConnect(WebSocketConfig config, List<InetAddress> inetAddresses) {
        int connectCount = config.getConnections();
        for (int i = 0; i < connectCount; i++) {
            int random = new Random().nextInt(1000000);
            int index = random % inetAddresses.size();
            HttpClient.create()
                        .runOn(this.loopResources)
                        .wiretap(false)
                        .bindAddress(() -> {
                            return new InetSocketAddress(inetAddresses.get(index), 0);
                        })
                        .websocket()
                        .uri(config.getUrl()+"/" + atomicLong.incrementAndGet())
                        .connect()
                        .subscribe(connection -> {
                            connectionList.add(connection);
                            executorService.scheduleAtFixedRate(()->{
                                connection.outbound()
                                            .sendString(Mono.just(config.getBody()))
                                            .then()
                                            
                                            .subscribe();

                            },0,config.getDelay(), TimeUnit.MILLISECONDS);
                        });
        }


    }

    private List<InetAddress> batchCreateKInetAddress(String[] networks) {
        List<InetAddress> inetAddresses = new ArrayList<>();
        for (int i = 0; i < networks.length; i++) {
            try {
                inetAddresses.add(InetAddress.getByName(networks[i]));
            } catch (UnknownHostException e) {
                //ignore
            }
        }
        return inetAddresses;

    }
}

```

## Your Environment
jdk8   reactor-netty 1.0.22

* Reactor version(s) used:
* Other relevant libraries versions (eg. `netty`, ...):
* JVM version (`java -version`):
* OS and version (eg. `uname -a`):

**Comment by violetagg** [comment]
@1ssqq1lxr Can you enable Reactor Netty logs and then provide logs with logger `reactor.netty.resources`?

When you use `HttpClient.create()` this creates a connection pool with 500 max connections and 1000 pending acquire requests. For more information check here https://projectreactor.io/docs/netty/release/reference/index.html#_connection_pool_2

**Comment by violetagg** [comment]
@1ssqq1lxr Were you able to collect the additional logs as we need them to proceed with the investigation.

**Comment by violetagg** [comment]
@1ssqq1lxr Let me close this. We can reopen it when you are able to provide the requested information.
