### ISSUE TITLE
reactor-netty Hooks.enableAutomaticContextPropagation() + context-propagation library support

### ISSUE THREAD

**Issue by SimonAlthoff** [reactor/reactor-netty#2849]
For debugging reasons I would like to apply some context IDs to the MDC when doing logging while in a reactor-netty reactive chain.
I enabled Hooks.enableAutomaticContextPropagation() and registered an ThreadLocalAccessor like described here:
https://spring.io/blog/2023/03/30/context-propagation-with-project-reactor-3-unified-bridging-between-reactive

However while this does work for a regular reactor chain, the ThreadLocal values are not being updated when doing this in a reactor-netty chain. The reactor context is forwarded correctly but it seems like the Scheduler hook to update the ThreadLocals is not called correctly.

Here is an example setup:

Using
java: 17
reactor-netty-core: 1.1.8
reactor-core: 3.5.7
context-propagation: 1.0.3

```
public static void main(String[] args) {

    Hooks.enableAutomaticContextPropagation();
    ContextRegistry.getInstance()
            .registerThreadLocalAccessor(new MdcAccessor());

    final HttpClient httpClient = HttpClient.create();

    httpClient.get()
            .uri("https://github.com/reactor/reactor-netty")
            .response()
            .tap(contextView -> new DefaultSignalListener<>() {
                @Override
                public void doFinally(final SignalType terminationType) throws Throwable {

                    System.out.println("reactor netty MDC: " + MDC.getCopyOfContextMap());
                }
            })
            .contextWrite(context -> context.put("MDC", Map.of("some-span", "test-span")))
            .block();

    MDC.clear();

    Mono.just("test")
            .tap(contextView -> new DefaultSignalListener<>() {
                @Override
                public void doFinally(final SignalType terminationType) throws Throwable {

                    System.out.println("reactor core MDC: " + MDC.getCopyOfContextMap());
                }
            })
            .contextWrite(context -> context.put("MDC", Map.of("some-span", "test-span")))
            .subscribeOn(Schedulers.newSingle("test"))
            .block();
}
```

Which produces:
```
reactor netty MDC: {}
reactor core MDC: {some-span=test-span}
```

**Comment by violetagg** [comment]
@SimonAlthoff This should be fixed once we have this feature implemented https://github.com/reactor/reactor-core/issues/3478

**Comment by SimonAlthoff** [comment]
Great! Thank you for the fast response.
