### ISSUE TITLE
ReactorHttpHandlerAdapter: Failed to get request URI: Illegal character in query at index Accept non encode query params.

### ISSUE THREAD

**Issue by nageshs28** [reactor/reactor-netty#2853]
Unlike TOMCAT, netty doesn't allow non urlencoded query parameters.
This functionality should be interesting for old and external application compliance.
I am not able to replace older stack due to this.

Motivation
Because of this lack, we still use embedded TOMCAT instead of reactor netty in spring boot projects (spring cloud gateway).

Desired solution
It would be appreciate to dispose a parameter like the "server.tomcat.relaxed-query-chars" to enumerate a list of allowed chars.

Considered alternatives
We have considered make a fork of reactor NETTY in order to allow non urlencoded query chars.

Additional context
Referred this https://github.com/reactor/reactor-netty/issues/1561 for workaround.

Error
o.s.h.s.r.ReactorHttpHandlerAdapter      : Failed to get request URI: Illegal character in query at index

**Comment by violetagg** [comment]
@nageshs28 I believe you are seeing Spring Framework issue https://github.com/spring-projects/spring-framework/issues/30475

For the time being Reactor Netty does not have any support for query processing.
We have a feature request #68 that is still not implemented.

**Comment by sabeurch** [comment]
What about using NettyServerCustomizer ?
Solution is here: https://stackoverflow.com/a/79238005/460705

**Comment by ahasgx** [comment]
the root cause is the class java.net.URI#URI(java.lang.String)  are not accepted a url parameter which with special characters,
use extension points of the WebServerFactoryCustomizer to decode the url which with special characters, it will be execute before org.springframework.http.server.reactive.ReactorHttpHandlerAdapter#apply() method and solve the problem
