### ISSUE TITLE
ReactorHttpHandlerAdapter: Failed to get request URI: Illegal character in query at index [Accept non encode query params]

### ISSUE THREAD

**Issue by nageshs28** [reactor/reactor-netty#2854]
Unlike TOMCAT, netty doesn't allow non urlencoded query parameters.
This functionality should be interesting for old and external application compliance.
I am not able to replace older stack due to this.

Motivation
Because of this lack, we still use embedded TOMCAT instead of reactor netty in spring boot projects (spring cloud gateway).

Desired solution
It would be appreciate to dispose a parameter like the "server.tomcat.relaxed-query-chars" to enumerate a list of allowed chars.

Considered alternatives
We have considered make a fork of reactor NETTY in order to allow non urlencoded query chars.

Additional context
Referred this https://github.com/reactor/reactor-netty/issues/1561 for workaround.

Error
o.s.h.s.r.ReactorHttpHandlerAdapter      : Failed to get request URI: Illegal character in query at index.

Idea is to accept query param in form {value}.

**Comment by violetagg** [comment]
I believe this issue is a duplicate for this #2853
