### ISSUE TITLE
reactor-tcp-nio-3 thread cpu 100%

### ISSUE THREAD

**Issue by skyfour** [reactor/reactor-netty#2865]
My project is to consume data from kafka and then use r2dbc to perform data operations on mysql. The current situation is that the cpu of the reactor tcp-nio3 thread runs 100%. I have subscribeOn or publishOn in many parts of the code, but it does not achieve the effect I want. Instead, I switch the thread to another Thread pool.so i don't know is r2dbc issue or reactor netty issue.

my sample code
<img width="658" alt="image" src="https://github.com/reactor/reactor-netty/assets/25677237/f0b7e9a1-0698-4f5c-b9d8-de36d1033786">

<img width="1710" alt="image" src="https://github.com/reactor/reactor-netty/assets/25677237/d4b7bd26-c3a5-4f6a-8869-8ebb358fed51">

**Comment by pderop** [comment]
Hi, @skyfour;

I think this issue has already been addressed, but in r2dbc-pool, not in reactor-netty.
now, what version of io.r2dbc:r2dbc-pool are you using ?

this [r2dbc-pool version](https://github.com/r2dbc/r2dbc-pool/releases) might resolve your problem, if you can upgrade to it, it's worth testing it, it contains this [r2dbc-pool fix](https://github.com/r2dbc/r2dbc-pool/issues/190) which should fix the single hot-cpu thread.

Now, if you can't upgrade to it, I think that there is a work around: in your application.yml, you can try to configure:

```
spring.r2dbc.pool.initial-size=0
```

this should resolve the issue, and all your reactor tcp-nio threads should be in use.

I'm closing this issue, if upgrading the r2dbc-pool version or applying the above work around does not fix your issue, please forward this issue to the r2dbc-pool github project.

thanks
