### ISSUE TITLE
The data submitted by the form form cannot be obtained through the receiveForm() method of the request

### ISSUE THREAD

**Issue by haiyanghan** [reactor/reactor-netty#2866]
The data submitted by the form form cannot be obtained through the receiveForm() method of the request

Both httpData.get() and httpData.getString() return null
---
code: 
![image](https://github.com/reactor/reactor-netty/assets/63851981/67dbdf76-84fc-4b30-9cdf-ddbb7d935f10)

**Comment by pderop** [comment]
the issue has been closed by the user, I have changed the status to invalid.

**Comment by haiyanghan** [comment]
@pderop problem still exists
After my test, I found that the collectList() method was executed after the receiveForm() method, and the problem reappeared

---
code: 
![image](https://github.com/reactor/reactor-netty/assets/63851981/3c151dda-71d1-4041-8e28-0aac67f02640)

**Comment by haiyanghan** [comment]
@pderop thanks
