### ISSUE TITLE
High cardinality in MicrometerHttpMetricsRecorder

### ISSUE THREAD

**Issue by anadhan** [reactor/reactor-netty#2884]
## Description

When recording micrometer metrics for server and client endpoints, if endpoint URIs have unique UUID, the caches created for each metric in [MicrometerHttpMetricsRecorder](https://github.com/reactor/reactor-netty/blob/main/reactor-netty-http/src/main/java/reactor/netty/http/MicrometerHttpMetricsRecorder.java) grow without expiration, causing high memory utilization and heap usage.

## Possible Solution

Either entries in the cache need to be expired or the MetricKey used as the map key needs to be less unique to avoid high cardinality.

## Your Environment

io.projectreactor.netty.reactor-netty-http:1.0.21
io.micrometer:micrometer-core:1.8.8
JDK 11

**Comment by pderop** [comment]
thanks for reporting here, but I think that there is already a mechanism that allows to avoid high cardinality in metrics, you need to use methods like [HttpClent.metrics(boolean enable, Function<String, String)](https://projectreactor.io/docs/netty/release/api/reactor/netty/http/client/HttpClient.html#metrics-boolean-java.util.function.Function-) or [HttpServer.metrics(boolean enable, Function<String, String)](https://projectreactor.io/docs/netty/release/api/reactor/netty/http/server/HttpServer.html#metrics-boolean-java.util.function.Function-) methods (please check the javadocs of these methods).

Also have a look at the `example` in documentation chapter 5.11 ([Http Server/Metrics](https://projectreactor.io/docs/netty/release/reference/index.html#_metrics_4)), and in chapter 6.12 ([Http Client/Metrics](https://projectreactor.io/docs/netty/release/reference/index.html#_metrics_6))

For instance, if your server can handle an Uri that is not fixed, like /test/foo/1, /test/foo/2, /test/foo/N ...

then you will need to use templated URIs as URI tags, something like:

```
            DisposableServer server =
                    HttpServer.create()
                            .metrics(true, s -> {
                              if (s.startsWith("/test/foo/")) {
                                  return "/test/foo/{n}";
                              }
                              return s;
                            })
                            ...
```

Also, you should apply upper limit for the meters with URI tag:

```
		Metrics.globalRegistry 
		       .config()
		       .meterFilter(MeterFilter.maximumAllowableTags("reactor.netty.http.server", "URI", 100, MeterFilter.deny()));
```

I am closing this issue, but feel free to reopen if needed.

thanks.
