### ISSUE TITLE
Error occurred: io.netty.handler.codec.http.DefaultHttpRequest (expected: io.netty.buffer.ByteBuf)

### ISSUE THREAD

**Issue by NKGUPTA26** [reactor/reactor-netty#2982]
```
private Mono<String> callThirdPartyApi(String lpc) throws SSLException {
        SslContext sslContext = SslContextBuilder
                .forClient()
                .trustManager(InsecureTrustManagerFactory.INSTANCE)
                .build();
        HttpClient httpClient = HttpClient.create()
                .protocol(HttpProtocol.H2)  // Specify HTTP/2 protocol
                .secure(sslSpec -> sslSpec.sslContext(sslContext));

        WebClient webClient = WebClient.builder()
                .clientConnector(new ReactorClientHttpConnector(httpClient)
                )
                .baseUrl("https://localhost:8081")
                .defaultHeader(HttpHeaders.CONTENT_TYPE, MediaType.APPLICATION_JSON_VALUE)
                .defaultHeader("Authorization", "Basic """)
                .build();

        Mono<String> resp = webClient.get()
                .uri("api/v1/endpoint")
                .retrieve()
                .bodyToMono(String.class)
                .doOnError(error -> {
                    // Log error or take remedial actions
                    System.out.println("Error occurred: " + error.getMessage());
                })
                .onErrorResume(e -> Mono.just("Fallback response in case of error"));

        resp.subscribe(System.out::println);
        return resp;

```

I am trying to make an http2 API calls to a third-party service which is also on the http2 protocol, whenever i am make the call i get the following error 
io.netty.handler.codec.UnsupportedMessageTypeException: io.netty.handler.codec.http.DefaultHttpRequest (expected: io.netty.buffer.ByteBuf)

Mono<String> resp = webClient.get() -> this line 

## Expected Behavior

ideally it should be able to call the service 

## Your Environment

* Reactor version(s) used: 4.1.33
* Other relevant libraries versions (eg. `netty`, ...): 
* JVM version (`java -version`): java 11
* OS and version (eg. `uname -a`): Mac OS Ventura

**Comment by violetagg** [comment]
@NKGUPTA26 Please specify the correct Reactor version. This `Reactor version(s) used: 4.1.33` is not correct. Please include either the full log or a reproducible example.

**Comment by violetagg** [comment]
@NKGUPTA26 I'm closing this issue. If you are able to provide the requested information, we can reopen it.
