### ISSUE TITLE
CI: Add GitHub Actions to Auto-Format Java Files according to Checkstyle configuration

### ISSUE THREAD

**Issue by SaptarshiSarkar12** [reactor/reactor-netty#2984]
## Motivation
This project has a code style defined in [`checkstyle.xml`](https://github.com/reactor/reactor-netty/blob/main/codequality/checkstyle.xml) file in the `codequality` directory. **Checking whether the code in the Pull Requests or branches follows the project's code style and applying fixes accordingly is a tedious work**.

## Desired solution
I want to use [`OpenRewrite's Gradle Plugin`](https://github.com/openrewrite/rewrite-gradle-plugin?tab=readme-ov-file) to automatically format the Java files using the Checkstyle configuration. I would also like to create a GitHub Actions to automatically run the formatter and push the changes to the branches or the PRs.

## Additional context
I have implemented this feature in an Open-Source project - [Drifty](https://github.com/SaptarshiSarkar12/Drifty/) and the GitHub Action also pushes the formatted files to the branches or PRs as you can see below :point_down:
![Screenshot from 2023-11-25 08-22-24](https://github.com/open-telemetry/opentelemetry-java/assets/105960032/a536e93d-adaa-4370-b2ad-0889a5fabb60)
**If this issue seems good to the maintainers and adds some value to the project, then, I would like to work on this issue.**

**Comment by violetagg** [comment]
@SaptarshiSarkar12 Thanks for getting in touch. The idea of having `checkstyle` is to help contributors prepare a PR that complies with the formatting rules of the project (and not only formatting rules I would say) and in general learn the project's code. In addition, having the correct formatting in place, when reviewing PRs, is in great help for the maintainers in the process of reviewing the changes. I do not think that having a CI that does the formatting afterwards is the ways we would like to go.

**Comment by SaptarshiSarkar12** [comment]
@violetagg Okay. Got it. Thank you :grin:!
