### ISSUE TITLE
Support for reconnecting to different host with TcpClient

### ISSUE THREAD

**Issue by rstoyanchev** [reactor/reactor-netty#302]
Based on an older request (originally https://github.com/reactor/reactor/issues/412), we still have an outstanding request to be able to reconnect to a different host. While the `retry` operator could be used with the current API, I'm not sure how to combine that with reconnecting to a different host. 

For more on the underlying motivation see https://jira.spring.io/browse/SPR-12452.

**Comment by smaldini** [comment]
Each retry will trigger a new `Supplier<InetSocketAddress>#get`. It is segregated so any stage downstream can safely retry without dealing with providing a new address. A Load Balancing supplier could be implemented as an extra facility.

**Comment by filiphr** [comment]
I didn't reply back into the SPR ticket. Honestly, I don't quite get what the older https://github.com/reactor/reactor/issues/412 issue is about. What I did now is to use my own implementation of the `Reactor2TcpClient` which supports the `Supplier<InetSocketAddress>`. And I have a round robin supplier (not sure whether that would scale, but I suppose if one is done it will retry the next one). I am talking about the 4.3.x branch. Haven't looked into 5.0. From my understanding of the code I've looked even the 4.3.x branch uses `Supplier<InetSocketAddress>` and it calls `#get` on each retry.

From what I could quickly see `ReactorNettyTcpClient` should be a replacement for the `Reactor2TcpClient`. With this one it seems it is easier to provide `ClientOptions.Builder` that would use a `Supplier<InetSocketAddress>`.

**Comment by rstoyanchev** [comment]
Ah, I see now. https://github.com/reactor/reactor/issues/412 was about an issue with the [Reconnect](https://github.com/reactor/reactor/blob/c8e659ee5b3d1ba2afcd2739774c316bcf2f4ba9/reactor-net/src/main/java/reactor/io/net/Reconnect.java#L43) strategy, passed into the `open` method, which ignored the IP address. What you're using is the `Supplier<InetSocketAddress>` on `TcpClientSpec`. Assuming you've confirmed that works, I'll update SPR-12452 and we can add your suggestion to 4.3.x.

**Comment by rstoyanchev** [comment]
Resolving this since it sounds like it should just work in the latest Reactor Netty.

**Comment by georgeyanev** [comment]
@rstoyanchev What is the proper way to configure TcpClient in order to reconnect to the same host in case the server has disconnected? I didn't find methods like `open` method or `Reconnect` interface in current `reactor-netty` code base.

**Comment by alexe13** [comment]
@georgeyanev I was struggling with reconnect too. Finally I made it work using observe() method, see following gist for example: https://gist.github.com/alexe13/c4afef6be7309447b690cfcd2cc60695
I'm not sure if this is the correct way to handle automatic reconnects, but reactor-netty documentation is pretty scarce so that's better than nothing I guess.

**Comment by georgeyanev** [comment]
That is interesting, I will try this. After all if there is no response here we have to manage it ourselves.

**Comment by violetagg** [comment]
@georgeyanev Something similar to the snippet above (provided by @alexe13) can be achieve with

https://github.com/reactor/reactor-netty/blob/master/src/main/java/reactor/netty/Connection.java#L282

See the test cases above.
