### ISSUE TITLE
Is it possible to be able to add custom labels to the metrics already being emitted

### ISSUE THREAD

**Issue by vpareek1308** [reactor/reactor-netty#3040]
I could not find a way to add custom static labels to the metrics that are emitted out-of-the-box. I want to differentiate the metrics if I have multiple beans of ConnectionProvider and want to analyse them seperately.

## Motivation
I am working on a project where multiple tenants are able to access my service and I do some data aggregator for them by making HTTP calls to some other services. Now if the traffic from one tenant spikes, I do not want the other tenants to be affected so I decided to make multiple beans as the number of tenants for me is always going to be less than 5 (worst case scenario). I want to see the metrics for these tenants separately, but I could not find a way to add a custom label to the out-of-the-box provided metrics by the library.

## Desired solution
Maybe there could be a way to add a custom label, with static values if not dynamic, that I can add at the time of bean creation, to the already emitted metrics.

## Additional context
Here is the code for the bean that I was creating to use the ConnectionProvider that I later used to create a bean of Webclient for my reactive application.
```kotlin
@Bean
fun connectionProvider(): ConnectionProvider {
    return ConnectionProvider
        // Other properties
        .metrics(true)
        // Other properties
        .build()
}
```

**Comment by violetagg** [comment]
@vpareek1308 Why don't you create every `ConnectionProvider` with a different name?

For example  if you have this code, you will be able to distinguish them using the `name` tag.

```
ConnectionProvider provider1 = ConnectionProvider.builder("provider1").metrics(true).build();
ConnectionProvider provider2 = ConnectionProvider.builder("provider2").metrics(true).build();

WebClient.builder()
		.clientConnector(new ReactorClientHttpConnector(HttpClient.create(provider1)))
		.build()
		.get()
		.uri("https://httpbin.org/get")
		.retrieve()
		.bodyToMono(String.class)
		.block();

WebClient.builder()
		.clientConnector(new ReactorClientHttpConnector(HttpClient.create(provider2)))
		.build()
		.get()
		.uri("https://httpbin.org/get")
		.retrieve()
		.bodyToMono(String.class)
		.block();
```

More about the `ConnectionProvider` metrics you can find here
https://projectreactor.io/docs/netty/release/reference/index.html#_metrics_6
https://projectreactor.io/docs/netty/release/reference/index.html#observability-metrics-total-connections

**Comment by vpareek1308** [comment]
@violetagg Thanks for the quick reply.

This fix makes sense, and I have added in my service for now. Maybe this can be added in the future if required. Let's close this issue for now.
