### ISSUE TITLE
default port based on PORT environment variable

### ISSUE THREAD

**Issue by tetsuhaut** [reactor/reactor-netty#3070]
In the file https://github.com/reactor/reactor-netty/blob/559b5efaa538d3d1157b832cae271cd13129fb45/reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientConnect.java#L704, the default port is found using
```
Integer.parseInt(System.getenv("PORT"))
```
1) I could not find this use of the PORT environment variable in the documentation
2) If the PORT environment variable is already defined, its definition will be used when this class is loaded. In particular, if the PORT environment variable content is not parsable as an int, like a string for instance, it will result in an exception.

I suggest you document that use of the PORT environment variable, add extra care when parsing it as it could be not parseable, and even add a log indicating you are using it for debug purpose.

**Comment by violetagg** [comment]
@tetsuhaut Would you like to provide a PR with the proposed changes?
