### ISSUE TITLE
Graceful shutdown of HttpClient

### ISSUE THREAD

**Issue by akshaysu** [reactor/reactor-netty#3071]
There is no proper documentation on how to release or close HttpClient handle.  The only way to do this is by `client.configuration().connectionProvider().dispose()` as explained in https://stackoverflow.com/questions/78032177/proper-way-to-close-reactor-netty-httpclient.

There is also a catch in the above approach that ConnectionProvider should not be shared with any other handle.  It would be good to provide a method on HttpClient interface to close the handle and release all the resources associated with the handle.

**Comment by akshaysu** [comment]
@violetagg thanks for the reply. Sorry, I'm new to the project reactor world. What do you mean by global LoopResources/ConnectionProvider?  The one provided by the library when HttpClient.create() is called?  Also, what happens when one uses ConnectionProivder.newConnection()? Do I need to dispose in this case?

**Comment by violetagg** [comment]
> What do you mean by global LoopResources/ConnectionProvider? The one provided by the library when HttpClient.create() is called?

Yes `HttpResources` is used when `HttpServer/HttpClient#create()` is invoked.

> Also, what happens when one uses ConnectionProivder.newConnection()

This is a `ConnectionProvider` that closes the connection after every request i.e. if you want to disable the connection pooling.

**Comment by akshaysu** [comment]
@violetagg If I create 2 httpclients using `HttpClient.create()` are they going to share same LoopReosurces and ConnectionProviders? If I just provide ConnectionProvider like `HttpClient.create(provider)` what is the behaviour? Are there any reference document I can dig into?
My question on ConnectionProvider.newConnection() is that does this share same resources with other httpclients? and do I need to dispose for newConnection also?

I'm using HttpClient in Database Handler for remote api call. When database is closed I need to release HttpClient also

**Comment by violetagg** [comment]
> @violetagg If I create 2 httpclients using `HttpClient.create()` are they going to share same LoopReosurces and ConnectionProviders?

Yes

> If I just provide ConnectionProvider like `HttpClient.create(provider)` what is the behaviour?

This particular `HttpClient` will run with the provided `ConnectionProvider`.

> Are there any reference document I can dig into?

Check this
https://projectreactor.io/docs/netty/release/reference/index.html#_connection_pool_2
and this
https://projectreactor.io/docs/netty/release/reference/index.html#_event_loop_group_2

> My question on ConnectionProvider.newConnection() is that does this share same resources with other httpclients? and do I need to dispose for newConnection also?

The connection created by this special `ConnectionProvider` is never pooled and is closed after the request/response processing i.e. you do not use any connection pooling.

**Comment by violetagg** [comment]
@akshaysu I updated the reference documentation.
