### ISSUE TITLE
proxy-authorization header is not propagated to proxy server

### ISSUE THREAD

**Issue by SushmaPradeep** [reactor/reactor-netty#3085]
HttpClient client = HttpClient.create()
.proxy(spec -> spec.type(ProxyProvider.Proxy.HTTP)
.host("proxy")
.port(8080)
.username("username")
.password(s-> "pwd"));

**Expected behavior**
when I set proxy with username and password, HttpProxyHandler is setting 'proxy-authorization' header. The request needs to carry this header as part of the request to proxy server.

**Actual behavior**
Even though the header is available in HttpProxyHandler, that is not propagated to proxy server.

Steps to reproduce
Create HttpClient and set up proxy and hit request.

Netty version reactor-netty 1.1.15
JVM version (e.g. java -version) 17

**Comment by SushmaPradeep** [comment]
Also, I need to avoid roundtrips (407 & 401 errors). To do so in apache there is a concept of PreemptiveAuthentication. Is there any similar concept to this in netty? If yes, could you please help me in configuring the same.

**Comment by violetagg** [comment]
@SushmaPradeep I'm looking at https://github.com/netty/netty/issues/13892, there is no need to open duplicate issues!

**Comment by violetagg** [comment]
@SushmaPradeep 

I have `squid` proxy configured with u/p. 

I have this application:

```
public class Application {

	public static void main(String[] args) {
		HttpClient client =
				HttpClient.create()
				          .wiretap(true)
				          .proxy(spec -> spec.type(ProxyProvider.Proxy.HTTP)
				                             .host("localhost")
				                             .port(3128)
				                             .username("test")
				                             .password(u -> "test"));

		String response =
				client.get()
				      .uri("https://example.com/")
				      .responseContent()
				      .aggregate()
				      .asString()
				      .block();

		System.out.println("Response " + response);
	}
}
```

When I'm executing this application I'm seeing a successful communication:

```
...
20:24:45.157 [reactor-http-nio-1] DEBUG reactor.netty.proxy - [c482d8cf] REGISTERED
...
20:24:45.160 [reactor-http-nio-1] DEBUG reactor.netty.proxy - [c482d8cf] CONNECT: localhost/127.0.0.1:3128
...
20:24:45.162 [reactor-http-nio-1] DEBUG reactor.netty.proxy - [c482d8cf, L:/127.0.0.1:58043 - R:localhost/127.0.0.1:3128] ACTIVE
20:24:45.165 [reactor-http-nio-1] DEBUG reactor.netty.proxy - [c482d8cf, L:/127.0.0.1:58043 - R:localhost/127.0.0.1:3128] WRITE, DefaultFullHttpRequest(decodeResult: success, version: HTTP/1.1, content: EmptyByteBufBE)
CONNECT example.com:443 HTTP/1.1
host: example.com:443
proxy-authorization: Basic dGVzdDp0ZXN0, 0B
20:24:45.167 [reactor-http-nio-1] DEBUG reactor.netty.proxy - [c482d8cf, L:/127.0.0.1:58043 - R:localhost/127.0.0.1:3128] FLUSH
...
20:24:45.321 [reactor-http-nio-1] DEBUG reactor.netty.proxy - [c482d8cf, L:/127.0.0.1:58043 - R:localhost/127.0.0.1:3128] READ: DefaultHttpResponse(decodeResult: success, version: HTTP/1.1)
HTTP/1.1 200 Connection established
20:24:45.321 [reactor-http-nio-1] DEBUG reactor.netty.proxy - [c482d8cf, L:/127.0.0.1:58043 - R:localhost/127.0.0.1:3128] READ, EmptyLastHttpContent, 0B
...
```

I'm not seeing any `407` error.

**Comment by violetagg** [comment]
@SushmaPradeep I'm closing this one. We can reopen it if it is needed.

**Comment by SushmaPradeep** [comment]
@violetagg I'm using Hoverfly as proxy server. And I can't see proxy-authorization header.

Please find the below logs:

request={body=, destination=localhost:8094, **headers**={Accept=[text/plain, application/json, application/*+json, */*], Accept-Encoding=[gzip, x-gzip, deflate], B3=[65dc9b4f308cd1148f70dd79c23841f2-c339dd05d8e4e80e-0], Content-Length=[0], User-Agent=[Apache-HttpClient/5.2.3 (Java/17.0.10)]}, method=GET, path=/api/v1/message, query={}, scheme=http}

**Comment by violetagg** [comment]
@SushmaPradeep The user agent in this request is not Reactor Netty?

`User-Agent=[Apache-HttpClient/5.2.3 (Java/17.0.10)]`
