### ISSUE TITLE
Support for Spengo auth scheme support for netty HttpClient similar to Apache HttpClient

### ISSUE THREAD

**Issue by naveenyamsani** [reactor/reactor-netty#3091]
We need to connect to some component via proxy, and this proxy works by kerberos auth. We need to do something like below:

CredentialsProvider credsr = new BasicCredentialsProvider();
    credsProvider.setCredentials(new AuthScope(null, -1, null), use_jaas_creds);
    Registry<AuthSchemeProvider> authSchemeRegistry = RegistryBuilder.<AuthSchemeProvider>create().register(AuthSchemes.SPNEGO, new SPNegoSchemeFactory(true)).build();
    CloseableHttpClient httpclient = HttpClients.custom()
        // set our proxy - httpclient doesn't use ProxySelector
        .setRoutePlanner(new DefaultProxyRoutePlanner(proxy))
        .setDefaultAuthSchemeRegistry(authSchemeRegistry)
        .setDefaultCredentialsProvider(creds).build();

We are not seeing any solution to run something like above Please help

**Comment by violetagg** [comment]
This is duplicate to #3079

**Comment by naveenyamsani** [comment]
@violetagg is there a Support for Spengo auth scheme support for netty HttpClient similar to Apache HttpClient?
