### ISSUE TITLE
CompletableFuture is cancelled because Netty is closing the connection channel

### ISSUE THREAD

**Issue by rohitrajwani** [reactor/reactor-netty#3103]
I am building an application that relays the request to server asynchronously. For scenarios where multiple requests are sent per second, I see that the CompletableFuture.whenComplete method is not being invoked for some of the requests even though all requests are getting success responses and it can be clearly seen that the complete method is called.

Upon checking the exception logs it seems like for the failure messages Netty is closing the channel, which is causing to cancel the CompletableFuture. This functionality to cancel the future was added in reactor core in the commit: [https://github.com/reactor/reactor-core/pull/3146](https://github.com/reactor/reactor-core/pull/3146)
addressing the mentioned issue: [https://github.com/reactor/reactor-core/issues/3138](https://github.com/reactor/reactor-core/issues/3138)

The behaviour is fine for reactor-core versions prior to this (i.e. working fine for 3.4.22 and below). 
I have tried using latest versions of reactor-core and reactor-netty, but still facing the same issue.

It is clearly visible in the stack trace that MonoCompletionStage$1.cancel is called which was added to address the above mentioned issue on reactor-core. 
But the concern is what is making the channel inactive for Netty, which is resulting in cancelling the CompletableFuture. 

Exception logs:
java.util.concurrent.CancellationException\n\tat java.base/java.util.concurrent.CompletableFuture.cancel(CompletableFuture.java:2478)\n\tat reactor.core.publisher.MonoCompletionStage$1.cancel(MonoCompletionStage.java:60)\n\tat reactor.core.publisher.Operators.terminate(Operators.java:1277)\n\tat reactor.core.publisher.MonoFlatMap$FlatMapMain.cancel(MonoFlatMap.java:187)\n\tat reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.cancel(FluxOnAssembly.java:654)\n\tat reactor.core.publisher.Operators$MultiSubscriptionSubscriber.drainLoop(Operators.java:2254)\n\tat reactor.core.publisher.Operators$MultiSubscriptionSubscriber.drain(Operators.java:2222)\n\tat reactor.core.publisher.Operators$MultiSubscriptionSubscriber.cancel(Operators.java:2034)\n\tat reactor.core.publisher.Operators.terminate(Operators.java:1277)\n\tat reactor.core.publisher.MonoFlatMap$FlatMapInner.cancel(MonoFlatMap.java:272)\n\tat reactor.core.publisher.MonoFlatMap$FlatMapMain.cancel(MonoFlatMap.java:188)\n\tat reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.cancel(FluxOnAssembly.java:654)\n\tat reactor.core.publisher.FluxDoOnEach$DoOnEachSubscriber.cancel(FluxDoOnEach.java:113)\n\tat reactor.core.publisher.FluxPeek$PeekSubscriber.cancel(FluxPeek.java:153)\n\tat reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.cancel(FluxOnAssembly.java:654)\n\tat reactor.core.publisher.Operators$MultiSubscriptionSubscriber.drainLoop(Operators.java:2254)\n\tat reactor.core.publisher.Operators$MultiSubscriptionSubscriber.drain(Operators.java:2222)\n\tat reactor.core.publisher.Operators$MultiSubscriptionSubscriber.cancel(Operators.java:2034)\n\tat reactor.core.publisher.Operators$MultiSubscriptionSubscriber.drainLoop(Operators.java:2254)\n\tat reactor.core.publisher.Operators$MultiSubscriptionSubscriber.drain(Operators.java:2222)\n\tat reactor.core.publisher.Operators$MultiSubscriptionSubscriber.cancel(Operators.java:2034)\n\tat reactor.core.publisher.Operators$MultiSubscriptionSubscriber.drainLoop(Operators.java:2254)\n\tat reactor.core.publisher.Operators$MultiSubscriptionSubscriber.drain(Operators.java:2222)\n\tat reactor.core.publisher.Operators$MultiSubscriptionSubscriber.cancel(Operators.java:2034)\n\tat reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.cancel(MonoPeekTerminal.java:144)\n\tat reactor.core.publisher.Operators$MultiSubscriptionSubscriber.drainLoop(Operators.java:2254)\n\tat reactor.core.publisher.Operators$MultiSubscriptionSubscriber.drain(Operators.java:2222)\n\tat reactor.core.publisher.Operators$MultiSubscriptionSubscriber.cancel(Operators.java:2034)\n\tat reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.cancel(MonoIgnoreThen.java:143)\n\tat reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.cancel(MonoPeekTerminal.java:144)\n\tat reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.cancel(MonoPeekTerminal.java:144)\n\tat reactor.core.publisher.Operators.terminate(Operators.java:1277)\n\tat reactor.netty.channel.ChannelOperations.terminate(ChannelOperations.java:474)\n\tat reactor.netty.http.server.HttpServerOperations.onInboundClose(HttpServerOperations.java:677)\n\tat reactor.netty.channel.ChannelOperationsHandler.channelInactive(ChannelOperationsHandler.java:73)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:305)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:281)\n\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:274)\n\tat io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1405)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:301)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:281)\n\tat io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:901)\n\tat io.netty.handler.codec.http2.AbstractHttp2StreamChannel$Http2ChannelUnsafe$2.run(AbstractHttp2StreamChannel.java:737)\n\tat io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)\n\tat io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)\n\tat io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)\n\tat io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:403)\n\tat io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)\n\tat io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)\n\tat io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)\n\tat java.base/java.lang.Thread.run(Thread.java:833)\n

I am not sure what is triggering the condition on netty side that is closing the channel, 
is there a behaviour change that needs to taken care?

Also, can this be avoided by adding some handlers in my application code?

## Expected Behavior

The CompletableFuture is not cancelled and completes normally which should call the whenComplete callback.

## Actual Behavior

The CompletableFuture is cancelled by Netty even after the complete method is called on the CompletableFuture.

## Your Environment

* Reactor version(s) used: 
reactor-netty: 1.0.39
reactor-core: 3.4.23 (verified till latest version i.e. 3.6.3, the issue persists)
Spring-Boot: 2.7.18
* JVM version (`java -version`): 17.0.10
* OS and version (eg. `uname -a`): Linux

**Comment by violetagg** [comment]
@rohitrajwani The cancelation is trigger because the connection was closed

From your stack trace 

```
...
reactor.netty.channel.ChannelOperations.terminate(ChannelOperations.java:474)\n\tat reactor.netty.http.server.HttpServerOperations.onInboundClose(HttpServerOperations.java:677)\n\tat 
...
```

**Comment by rohitrajwani** [comment]
Thanks for the response @violetagg 

I wonder what is causing it, because all other things same
- The client is same
- The traffic scenario and rate is same
It's just that when I am switching the reactor-core from 3.4.22 to a 3.4.23+ versions, this is happening. 
Seeing the changelog for 3.4.23 [https://github.com/reactor/reactor-core/pull/3146](https://github.com/reactor/reactor-core/pull/3146) 
I am suspecting the future is getting cancelled.

1. Is there a way to evaluate the reason for closure of connection/stream?
2. Can this be caught in the application to handle such closures gracefully?

**Comment by violetagg** [comment]
@rohitrajwani  Please provide either logs/tcpdump or a reproducible example.

**Comment by jryan128** [comment]
I'm seeing a very similar issue, and it's almost impossible to track down what is actually doing the cancelling. For us it's related to using cassandra/scylla
