### ISSUE TITLE
springcloud gateway  netty pool config

### ISSUE THREAD

**Issue by zxltmjzyt** [reactor/reactor-netty#3122]
![image](https://github.com/reactor/reactor-netty/assets/158263667/50ce640b-d957-4166-9956-60f07bf10b15)
how to config nettypool in springcloud gateway  yml , like the pic not work 

![image](https://github.com/reactor/reactor-netty/assets/158263667/85b9c994-2e57-402f-bb38-e54c85dff49a)

**Comment by violetagg** [comment]
Please contact Spring Cloud Gateway maintainers.
