### ISSUE TITLE
Mutable NewConnectionProvider

### ISSUE THREAD

**Issue by dimitaracev** [reactor/reactor-netty#3149]
## Motivation

On a project that I'm currently working on, we need to export metrics to Prometheus and this is easily done for the `PooledConnectionProvider` through the `ConnectionProvider.builder(..).metrics(true)`. We also use a `NewConnectionProvider`  in certain situations where we always require new connections so no connection gets reused from the pool.  Instantiating a `ConnectionProvider` through the `ConnectionProvider.newConnection()` method returns a `NewConnectionProvider` but unfortunately that implementation does not override the `ConnectionProvider#mutate()` method and instead returns the default `null` value. This means that there is no way to add metrics to this type of `ConnectionProvider`.
## Desired solution

To be able to add metrics to a `NewConnectionProvider`, and the `mutate` method seems like a solution.
## Considered alternatives

Creating our own `NewConnectionProvider` with a `mutate` method implemented, based on the one provided by Netty.
## Additional context

Note: Happy to create a PR for this.

**Comment by violetagg** [comment]
@dimitaracev Can you please elaborate more? What kind of statistics do you need? Currently `mutate` is not implemented because it is not applicable for `NewConnectionProvider`, as it doesn't use a builder.

**Comment by dimitaracev** [comment]
@violetagg Thanks for the response and sorry for the late reply. I basically just need to enable the metrics for the `NewConnectionProvider` just as one can with `ConnectionProvider.builder().metrics(true)`.  I'm currently using the default implementation for Metrics `MicrometerPooledConnectionProviderMeterRegistrar` when creating my own `ConnectionProvider`. I would be beneficial to have the same metrics when creating ` NewConnectionProvider`.

**Comment by violetagg** [comment]
@dimitaracev Looking at these `MicrometerPooledConnectionProviderMeterRegistrar` only `total` and `active` are related to this `ConnectionProvider`. Is that what you need?

**Comment by violetagg** [comment]
Then why don't you use `.doOnConnected` event and report your own metrics about active connections?

**Comment by dimitaracev** [comment]
I guess that would work but would still defer from the `MicrometerPooledConnectionProviderMeterRegistrar` which I would like to keep for both so they behave the same whether a `NewConnectionProvider` is used or not. I will try and see how the above suggestion would work. Thanks!

**Comment by violetagg** [comment]
ok keep me posted for the results
