### ISSUE TITLE
GET request hung when body is large(~1M)

### ISSUE THREAD

**Issue by smaldini** [reactor/reactor-netty#316]
Investigating Spring Cloud Gateway reported issue https://github.com/spring-cloud/spring-cloud-gateway/issues/262

**Comment by spencergibb** [comment]
Potentially related https://github.com/spring-cloud/spring-cloud-gateway/issues/247#issuecomment-377081927

**Comment by spencergibb** [comment]
Logs for gateway 262
https://gist.github.com/spencergibb/df8d3a4413bc7c4eac4472c1a552f84d

**Comment by aveiros** [comment]
https://github.com/spring-cloud/spring-cloud-gateway/issues/247#issuecomment-379593417

hope this can help

**Comment by violetagg** [comment]
with fix provided by #327 the reported issue here https://github.com/spring-cloud/spring-cloud-gateway/issues/262 does not exist anymore

**Comment by spencergibb** [comment]
@violetagg I'm still seeing it with 
```
    compile('io.projectreactor:reactor-core:3.1.6.RELEASE')
    compile('io.projectreactor.ipc:reactor-netty:0.7.7.BUILD-SNAPSHOT')
```

**Comment by violetagg** [comment]
which test should I use?

**Comment by smaldini** [comment]
Verified by @spencergibb
