### ISSUE TITLE
IllegalArgumentException: Failed to parse a port from request

### ISSUE THREAD

**Issue by lennartblom** [reactor/reactor-netty#3206]
**Rather a question, than a bug:**

During updating spring boot reactive and implicit update of `reactor-netty`  from `1.0.21` to `1.1.13` we are discovering some app behaviour changes.

**We are receiving:**
```
2024-04-26 12:11:31.825 CEST  WARN requestId=NA x-correlation-id=NA 68692 --- [ctor-http-nio-3] r.n.http.server.HttpServerOperations     : [6cd81bef, L:/127.0.0.1:8080 - 
Decoding failed: REQUEST(decodeResult: failure(java.lang.IllegalArgumentException: Failed to parse a port from https://cdn-sharing-stage.cloudprovider.com/)
```

**When doing a PUT request:**
```

PUT /request/path/urn:aaid:sc:US:0ce812ab-effb-430f-a812-abeffb530f7b HTTP/1.1
x-forwarded-for: 193.104.215.11,10.76.168.250
x-forwarded-port: 443
x-forwarded-proto: https
x-forwarded-host: https://cdn-sharing-stage.cloudprovider.com/
x-forwarded-request-uri: /primary/id/urn:aaid:sc:US:87a78ef7-a4fc-3a84-a446-
```

When setting `server.forward-headers-strategy=native` inside the test properties, we can identify this 400 error locally as well. And not only inside our integration test pipeline.

Are there some new configuration properties, which can mitigate this validation issue?

## Expected Behavior

Success code
## Actual Behavior

400 response before reaching application code. 

* Reactor version(s) used: 1.1.13
* Other relevant libraries versions (eg. `netty`, ...):
* JVM version (`java -version`):
* OS and version (eg. `uname -a`):

**Comment by violetagg** [comment]
@lennartblom This is not valid `x-forwarded-host: https://cdn-sharing-stage.cloudprovider.com/` ...

The header value should be the `domain name` (https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-Host), while here the `scheme` is also added to the value.

**Comment by lennartblom** [comment]
Check, got it! Seems like something changed for "DEFAULT" behaviour during the spring / Netty update. 

Thanks a lot!
We configured our environment to `server.forward-headers-strategy=NONE` and validation is no longer done by Netty. Issue can be deferred. :) Sorry for your troubles!
