### ISSUE TITLE
Metrics not disposed for `GracefulShutdownInstrumentedPool`

### ISSUE THREAD

**Issue by rs017991** [reactor/reactor-netty#3226]
When working with various ConnectionProvider/MetricRegistrar arrangements, I am able to verify deRegistration of Metrics when I dispose the provider, but only if I do not set anything for `disposeTimeout`. Once I add that, it loses the ability to deregister its Metrics.

## Expected Behavior
`ConnectionProvider` Metrics should be deRegistered on dispose, regardless of `disposeTimeout` use.

## Actual Behavior
When adding `disposeTimeout` to a `ConnectionProvider`, Metrics are no longer deRegistered when the `ConnectionProvider` is disposed

## Steps to Reproduce
Can reproduce this problem with a tweak to an existing `reactor-netty-core` test:
[Add to `ConnectionProvider` setup in `PooledConnectionProviderDefaultMetricsTest.testConnectionPoolPendingAcquireSize`](https://github.com/rs017991/reactor-netty/commit/6125294e327ecabe579603456134a9f6d093bd39):
```java
.disposeTimeout(Duration.ofSeconds(1))
```

## Possible Solution
In `PooledConnectionProvider`, I see that Metric cleanup is only performed in `onErrorResume` for the `GracefulShutdownInstrumentedPool` block:
https://github.com/reactor/reactor-netty/blob/dd0c42d725e93f8da6cd2d053af8d9fde083382b/reactor-netty-core/src/main/java/reactor/netty/resources/PooledConnectionProvider.java#L201-L208
whereas in the de facto `else` it is done unconditionally:
https://github.com/reactor/reactor-netty/blob/dd0c42d725e93f8da6cd2d053af8d9fde083382b/reactor-netty-core/src/main/java/reactor/netty/resources/PooledConnectionProvider.java#L220-L223

Perhaps GracefulShutdownInstrumentedPool is supposed to perform the deRegistration on its own happy path, but I see nothing like that in its implementation. Without knowing how it was intended to work, not sure else I can glean...

## Your Environment

* Reactor version(s) used: encountered in `1.1.18`; reproduction was just done against `main`
* JVM version: `21`
* OS and version: `Windows 11`

**Comment by violetagg** [comment]
@rs017991 Thanks for the report and the reproducible example. I confirm that this is an issue and it will be fixed for the next release.
