### ISSUE TITLE
Support SocketAddress for proxies

### ISSUE THREAD

**Issue by AlexProgrammerDE** [reactor/reactor-netty#3242]
Currently proxies are required to be InetSocketAddress, but netty allows any SocketAddress to be used as a proxy.
This can be seen in in the ProxyProvider class:

https://github.com/reactor/reactor-netty/blob/ed7c9644b040aff54cecccdcdcd554193c27c97a/reactor-netty-core/src/main/java/reactor/netty/transport/ProxyProvider.java#L429

## Motivation

I'm interested in using UnixDomainSocket for proxies instead of InetSocketAddress.

## Desired solution

Extend the functionality of the proxy provider class to allow passing a SocketAddress instead of a InetSocketAddress to a proxy.
I've made a rough example how that could be made in a fork of mine: https://github.com/AlexProgrammerDE/reactor-netty/commit/a76c01d563afbad4112153fce48b04afbafe49bd
It tries to keep backwards support until the next major release is made.
I'd recommend the maintainers use my commit as a reference.

## Considered alternatives

Support UnixDomainSocket instead, but it's probably easier to just support SocketAddress directly to allow other future implementations of that class.

**Comment by violetagg** [comment]
@AlexProgrammerDE Are you interested in providing a PR? Which Reactor Netty version should enable this (1.1.x or 1.2.x)?

**Comment by AlexProgrammerDE** [comment]
Opened at https://github.com/reactor/reactor-netty/pull/3243
I think 1.2.x works.
