### ISSUE TITLE
Added configuration to disable dns using TransportConnector

### ISSUE THREAD

**Issue by llchry** [reactor/reactor-netty#3245]
## Motivation

Now Netty will bind a udp port when new DNSNameResolver, when using TransportConnector.connect method, it will trigger a new port binding. However, during actual connection, the system determines whether parsing is required and then connects to the corresponding address. 
https://github.com/reactor/reactor-netty/blob/fcbdbb736a99987e732d7604566a623b0af3fd2c/reactor-netty-core/src/main/java/reactor/netty/transport/TransportConnector.java#L316

## Desired solution

Is it possible to provide a configuration similar to a switch to disable DNS functionality?

## Considered alternatives

Hope some suggestions.

## Additional context

The Netty PR:
[DnsNameResolver: Allways call bind() during bootstrap #13817](https://github.com/netty/netty/pull/13817)

**Comment by violetagg** [comment]
@llchry Please elaborate more on the topic.

Reactor Netty by default runs with only on DNS resolver so you should have only once this binding. Do you observes something different.

When one provides a custom DNS resolver, we always recommend that this resolver is shared.

If you need completely to disable the DNS resolver, you can configure the `HttpClient` like this:

```
HttpClient.resolver(NoopAddressResolverGroup.INSTANCE)
```

**Comment by llchry** [comment]
> @llchry Please elaborate more on the topic.
> 
> Reactor Netty by default runs with only one DNS resolver so you should have only once this binding. Do you observe something different?
> 
> When one provides a custom DNS resolver, we always recommend that this resolver is shared.
> 
> If you need completely to disable the DNS resolver, you can configure the `HttpClient` like this:
> 
> ```
> HttpClient.resolver(NoopAddressResolverGroup.INSTANCE)
> ```

What I observed is that there is one DnsNameResolver per thread, so there will be more than ten listeners in the http service.

I try to solve it in this way, thank you very much.
