### ISSUE TITLE
Webclient active connection is struck - Direct buffer memory increase

### ISSUE THREAD

**Issue by ajaykc5** [reactor/reactor-netty#3254]
We are having issues with spring webclient active connections. It stays flat for most part of the day but it increases all of sudden and it results in increasing direct buffer memory as well. And eventually we are running out of buffer memory & we are restarting our service once i a week to come out of this issue. We tried replicating on lower env by putting more load but it never worked & we are not using exchange at any part of the code. Need help in identifying why the active connections are increasing. Please find the HttpClient & Webclient config here

```
private final WebClient webClient;

public WebClient(@Value("${application.test.baseUrl}") String locationApiBaseUrl,
    		@Value("${application.test.maxInMemorySize}") Integer maxInMemorySize) {
      HttpClient httpClient = HttpClient.create(ConnectionProvider.builder("TestWebClient")
          .maxConnections(500)
          .pendingAcquireMaxCount(75)
          .metrics(true)
                      .build()
      )
          .wiretap(false)
          .secure()
          .keepAlive(false)
          .metrics(true, Function.identity())
          .responseTimeout(Duration.ofMinutes(5)); 
      
      this.webClient = WebClient.builder()
        		.codecs(configurer -> configurer.defaultCodecs().maxInMemorySize(maxInMemorySize
        				* 1024 * 1024))
            .clientConnector(new ReactorClientHttpConnector(httpClient))
        		.baseUrl(locationApiBaseUrl).build();
    }
```

maxInMemorySize is 2 MB

## Expected Behavior
Active connection shouldn't increase all the time

## Actual Behavior
Active connections & direct buffer memory is increasing.

## Steps to Reproduce
Unable to reproduce on lower env. Happens only in Production

## Possible Solution
Restarting service when ever buffer memory is exhausted/ running out of connections 

## Your Environment
PROD

* Reactor version(s) used: 1.0.39
* Spring boot: 2.7.18
* JVM version (`java -version`): jdk-jre17_alpine-3.17
* OS and version (eg. `uname -a`): Linux

**Comment by violetagg** [comment]
@ajaykc5 I would say that this configuration is very strange ...

```
      HttpClient httpClient = HttpClient.create(ConnectionProvider.builder("TestWebClient")
          .maxConnections(500)
          .pendingAcquireMaxCount(75)
          .metrics(true)
                      .build()
      )
          .wiretap(false)
          .secure()
          .keepAlive(false)
          .metrics(true, Function.identity())
          .responseTimeout(Duration.ofMinutes(5)); 
```

Why do you configure a connection pool when you say that keep-alive is false? Basically this configuration means `disable the connection pool`.

**Comment by ajaykc5** [comment]
@violetagg - Thanks for the reply.
Yeah wanted to limit the connections. Do you think this is the root cause of active connection being struck?
FYI - Earlier we were using connection pool (keepAlive as true) but still had same behavior.

**Comment by violetagg** [comment]
@ajaykc5 Based only on the shared configuration I cannot say what might be the issue. Please provide a sample how you use it and if possible logs from the time when the issue happened.

**Comment by ajaykc5** [comment]
Using the above webClint config we are making http calls. As I said earlier most of the times the active connections stays flat but only during certain times the connections are spiking up. Pls find a example of how are calling it 

 public Flux<Test> test(Integer test1) {
        return webClient.get().uri(url).retrieve()
                .onStatus(HttpStatus::is4xxClientError, clientResponse ->{
                            return Mono.error(new VisualSpaceException(HttpStatus.NOT_FOUND.toString(),clientResponse.statusCode()));
                        }
                )
                .onStatus(HttpStatus::is5xxServerError, clientResponse -> {
                            return Mono.error(new TestException(HttpStatus.INTERNAL_SERVER_ERROR.toString(),clientResponse.statusCode()));
                        }
                ).bodyToFlux(Test.class);
    }

**Comment by ajaykc5** [comment]
@violetagg  - As I said earlier we are unable to reproduce in lower env. 
In lower env reactor_netty_connection_provider_active_connections always stays **zero**. But in PROD we see this is increasing gradually.
Is there a way to know if a request is processed successfully and still active connection is not release?
Is there a way to know from which web client call, it is getting originated?

**Comment by violetagg** [comment]
> @violetagg - As I said earlier we are unable to reproduce in lower env. In lower env reactor_netty_connection_provider_active_connections always stays **zero**. But in PROD we see this is increasing gradually. Is there a way to know if a request is processed successfully and still active connection is not release? Is there a way to know from which web client call, it is getting originated?

Usually with logs it is possible to trace the problem. But without logs or reproducible scenario I'm not able to guess if there is a problem and where it is.

**Comment by ajaykc5** [comment]
@violetagg  - We are seeing definitely seeing problem. Could you pls let us know how do we trace a connection which is active for more than 5 mins (X mins) or a connection which is not released even after successful response?

**Comment by violetagg** [comment]
> @violetagg - We are seeing definitely seeing problem. Could you pls let us know how do we trace a connection which is active for more than 5 mins (X mins) or a connection which is not released even after successful response?

With `reactor.netty.resources`  we can trace how the connection is acquired/returned to the pool.
With `reactor.netty.http.client` we can trace the request/response.

**Comment by ajaykc5** [comment]
@violetagg  - Could you pls add few more details or point me to documentation of how to track?

**Comment by violetagg** [comment]
@ajaykc5 When you enable the loggers above you will be able to see something like the logs below (typically if the connection is keep-alive, you will see how a connection is acquired from the pool, but as in your case the keep-alive is disabled you should see the log below that you always establish a new connection):

```
21:50:18.298 [reactor-http-nio-2] DEBUG r.n.r.PooledConnectionProvider - [88f7ffec] Created a new pooled channel, now: 0 active connections, 0 inactive connections and 0 pending acquire requests.
21:50:18.468 [reactor-http-nio-2] DEBUG r.n.r.PooledConnectionProvider - [88f7ffec, L:XXXX - R:YYYY] Channel connected, now: 1 active connections, 0 inactive connections and 0 pending acquire requests.
21:50:18.744 [reactor-http-nio-2] DEBUG r.n.r.DefaultPooledConnectionProvider - [88f7ffec, L:XXXX - R:YYYY] onStateChange(PooledConnection{channel=[id: 0x88f7ffec, L:XXXX - R:YYYY]}, [connected])
21:50:18.748 [reactor-http-nio-2] DEBUG r.n.r.DefaultPooledConnectionProvider - [88f7ffec-1, L:XXXX - R:YYYY] onStateChange(GET{uri=null, connection=PooledConnection{channel=[id: 0x88f7ffec, L:XXXX - R:YYYY]}}, [configured])
21:50:18.750 [reactor-http-nio-2] DEBUG r.n.r.DefaultPooledConnectionProvider - [88f7ffec-1, L:XXXX - R:YYYY] onStateChange(GET{uri=/, connection=PooledConnection{channel=[id: 0x88f7ffec, L:XXXX - R:YYYY]}}, [request_prepared])
21:50:18.753 [reactor-http-nio-2] DEBUG r.n.r.DefaultPooledConnectionProvider - [88f7ffec-1, L:XXXX - R:YYYY] onStateChange(GET{uri=/, connection=PooledConnection{channel=[id: 0x88f7ffec, L:XXXX - R:YYYY]}}, [request_sent])
21:50:18.883 [reactor-http-nio-2] DEBUG r.n.r.DefaultPooledConnectionProvider - [88f7ffec-1, L:XXXX - R:YYYY] onStateChange(GET{uri=/, connection=PooledConnection{channel=[id: 0x88f7ffec, L:XXXX - R:YYYY]}}, [response_received])
21:50:18.885 [reactor-http-nio-2] DEBUG r.n.r.DefaultPooledConnectionProvider - [88f7ffec, L:XXXX - R:YYYY] onStateChange(GET{uri=/, connection=PooledConnection{channel=[id: 0x88f7ffec, L:XXXX - R:YYYY]}}, [response_completed])
21:50:18.885 [reactor-http-nio-2] DEBUG r.n.r.DefaultPooledConnectionProvider - [88f7ffec, L:XXXX - R:YYYY] onStateChange(GET{uri=/, connection=PooledConnection{channel=[id: 0x88f7ffec, L:XXXX - R:YYYY]}}, [disconnecting])
21:50:18.885 [reactor-http-nio-2] DEBUG r.n.r.DefaultPooledConnectionProvider - [88f7ffec, L:XXXX - R:YYYY] Releasing channel
```

**Comment by ajaykc5** [comment]
Thanks for sharing. But we will be getting 1000s of requests every hour. How do we track the connection which is not releasing the channel?
As I said earlier when we tried testing on lower environment. All the API's are releasing channels.

**Comment by violetagg** [comment]
@ajaykc5 Do you observe some exceptions or you only see that the connections are active?
You should at least see exception that you cannot acquire anymore.

**Comment by ajaykc5** [comment]
We don't see any exceptions .. the active connections & direct buffer keeps spiking up and eventually we will run out of direct buffer memory and we have to restart our service. But one thing to note is the direct buffer memory increases when ever active connection increases, it's directly proportional.

**Comment by violetagg** [comment]
@ajaykc5 So you do not observe any exception, neither exception that the connection pool is full nor memory leak.

From your description it seems that at some point you have high load and your memory settings are not able to handle this load.

> But one thing to note is the direct buffer memory increases when ever active connection increases, it's directly proportional.

Isn't this expected the more active connections you have the more memory you will need to handle them (I still don't know your application and what you keep in the memory per request)

Can you try locally to run some load tests and in the same time to reduce the memory configurations, so that eventually you will hit OOM?
Check this FAQ how to do it - https://projectreactor.io/docs/netty/release/reference/index.html#faq.memory-leaks
