### ISSUE TITLE
Content-Length set for GET/HEAD requests

### ISSUE THREAD

**Issue by sappo** [reactor/reactor-netty#3292]
The HttpClientOperations newFullBodyMessage forces the Content-Length Header with value 0. This is not RFC 7230 compliant and thus is blocked e.g. by AWS ELB in Strictest mode.

## Expected Behavior
No Content-Length Header for GET/HEAD requests

## Actual Behavior
Content-Length header with value 0 is set for GET/HEAD requests

## Steps to Reproduce
Any request send vua HttpClientOperations

## Possible Solution
Don't set Content-Length header for GET/HEAD requests 

## Your Environment
* Reactor version(s): 3.6.6
* reactor-netty: 1.1.19
* JVM version (`java -version`): 17

**Comment by violetagg** [comment]
This is duplicate to #2900
