### ISSUE TITLE
Review calls to channel.write vs channelContextHandler.write

### ISSUE THREAD

**Issue by smaldini** [reactor/reactor-netty#331]
Channel.write adds an extra stack line and might evolve in Netty 5 to be fully dispatched to eventLoop. ChannelContextHandler will be safe when called from a netty event loop. Part of the investigation will be to evaluate if ChannelOperationHandler need to use eventLoop directly or append a publishOn(Scheduler.from(eventLoop)) to every written Publisher.

**Comment by violetagg** [comment]
Check `channel.write` vs `channelContextHandler.write`
http://normanmaurer.me/presentations/2014-facebook-eng-netty/slides.html#29.0

`ChannelOperationHandler` is not involved in the outbound operations anymore.

**Comment by violetagg** [comment]
I checked this and `channel.write` vs `channelContextHandler.write` is OK
