### ISSUE TITLE
Client sockets are not re-used when explicit EventLoopGroup is passed

### ISSUE THREAD

**Issue by prakashgayasen** [reactor/reactor-netty#3316]
- TcpClient provides 2 methods to setup connections on eventloops: runOn(EvenLoopGroup) & runOn(LoopResources). [Code](https://github.com/reactor/reactor-netty/blob/main/reactor-netty-core/src/main/java/reactor/netty/tcp/TcpClient.java#L307)
 - LoopResources is a FunctionalInterface and it is created with a lambda: [Code](https://github.com/reactor/reactor-netty/blob/main/reactor-netty-core/src/main/java/reactor/netty/transport/Transport.java#L235)
 - If we pass eventLoopGroup to TcpClient, a new instance of LoopResouce is created with each call from the lambda. 
 - Reactor ClientTransport uses a HashMap with LoopResources in key to cache DNSResolver which creates a unique client socket: [Code](https://github.com/reactor/reactor-netty/blob/main/reactor-netty-core/src/main/java/reactor/netty/transport/ClientTransportConfig.java#L248)
 - Since LoopResources changes with every call, the code creates a new dnsResolver leading to a new client socket with each call.

## Expected Behavior

Client sockets should limit to EventLoopGroup size. 
## Actual Behavior

Client socket count keeps increasing with each connectNow() call.
## Steps to Reproduce

```java
@Test
public void repoCase() {
	LoopResources loopResources = LoopResources.create("test", -1, 80, true, false);
	for(int i=0;i<=400;i++) {
        TcpClient.create()
            .remoteAddress(
                () -> new DomainSocketAddress("/tmp/test.sock"))
            .runOn(loopResources)                     // Works
            // .runOn(loopResources.onClient(true))       // Does not work
            .connectNow();
            Thread.sleep(1000);
    }
}
```
Count sockets using: `ss -lunp | grep java | wc -l `. This number increases when eventLoopGroup is used.
## Possible Solution

 - Hash function works with eventLoopGroup(instead of loopResources) in cases eventloopGroup is passed to TcpClient
## Your Environment

* Reactor version(s) used: v1.1.17

**Comment by violetagg** [comment]
@prakashgayasen Thanks for the detailed description and the test case. PR #3321 should be fixing this.
