### ISSUE TITLE
Potential memory leak

### ISSUE THREAD

**Issue by sdeleuze** [reactor/reactor-netty#333]
This issue is a follow-up of [SPR-16633](https://jira.spring.io/browse/SPR-16633) originally reported on Spring WebFlux side. The [original repro project](https://github.com/tkp1n/webflux-leak-demo) had some leak that are likely now to be fixed.

@violetagg mentioned the thread cleanup mechanism in Netty was[ changed with version 4.1.20](https://github.com/netty/netty/commit/e329ca1cf3cecd41c9cf1a5a7be369a65f002ab5). With the new approach the cleanup happens when a Thread is collected (see [ObjectCleaner.java#L54](https://github.com/netty/netty/blob/4.1/common/src/main/java/io/netty/util/internal/ObjectCleaner.java#L54) and [ObjectCleaner.java#L134](https://github.com/netty/netty/blob/4.1/common/src/main/java/io/netty/util/internal/ObjectCleaner.java#L134)).

So there is maybe something to adapt in Reactor Netty about that. Feel free to complete with your analyze of the issue @violetagg.

**Comment by violetagg** [comment]
The `ObjectCleaner` usage was removed in Netty 4.1.26.Final, `finalize()` is used instead.
0.7.9.BUILD-SNAPSHOT is updated to Netty 4.1.27.Final
