### ISSUE TITLE
 A pooled `ByteBuf` received from the HTTP request should only be released once rather than twice

### ISSUE THREAD

**Issue by JamesChenX** [reactor/reactor-netty#3347]
## Expected Behavior

 A pooled `ByteBuf` received from the HTTP request should only be released once rather than twice if an exception occurs.
See the following code for details.

## Actual Behavior

The pooled `ByteBuf` may be released twice by accident.
The first release: 
![image](https://github.com/reactor/reactor-netty/assets/44962329/7d8152f8-d3f1-491e-8870-d32461a34962)
Once the pooled buffer is released to 0, it will be recycled by Netty and may be reused by another Thread, so its reference count becomes 1 again.

The second release:
![image](https://github.com/reactor/reactor-netty/assets/44962329/b4d197a0-ec5c-4c36-ab44-9f58e518e02d)
If the buffer has been reused by another thread, the code will release the pooled buffer that belongs to another thread by accident.

## Steps to Reproduce

```java
@Test
public void repoCase() {
     HttpServer
                .create()
                .port(8080)
                .handle((req, res) -> {
                    req.receive()
                            .doOnNext(buffer -> {
                                // The pooled buffer may be released twice by reactor-netty by accident.
                                throw new RuntimeException(MessageFormat.format("Received: {0}", byteBuf.toString(java.nio.charset.StandardCharsets.UTF_8)));
                            })
                            .subscribe();
                    return Mono.never();
                })
                .bindNow()
                .onDispose()
                .block();
}
```

## Possible Solution

Don't guess if a buffer can be released or not by checking its reference count, but follow the design of the buffer lifecycle responsibility chain (Once the caller has passed the buffer to the callee, the callee is responsible for the buffer lifecycle).

## Your Environment

* Reactor version(s) used: 1.1.20

**Comment by violetagg** [comment]
> Don't guess if a buffer can be released or not by checking its reference count, but follow the design of the buffer lifecycle responsibility chain (Once the caller has passed the buffer to the callee, the callee is responsible for the buffer lifecycle).


In Reactor Netty we have the following as a design decision:
Reactor Netty always releases the buffer, if the consumer wants to keep the buffer alive it must call `retain`, see my explanation here https://github.com/reactor/reactor-netty/issues/1372#issuecomment-723478096

**Comment by JamesChenX** [comment]
Thanks for your explanation!
After code review and tests, the problem will not happen in a real application as Netty uses a thread-local buffer allocator (i.e. `io.netty.buffer.PooledByteBufAllocator#threadCache`).
