### ISSUE TITLE
io.netty.handler.codec.DefaultHeaders.remove(DefaultHeaders.java 1074) java.lang.NullPointerException : Cannot read field ""hash"" because ""e"" is null

### ISSUE THREAD

**Issue by jeffcf** [reactor/reactor-netty#3363]
Springboot 3.2 webflux netty server will throw NPE error when receiving http header except Expect: 100-continue. (
Sometimes, not every time)

Exception :
io.netty.handler.codec.DefaultHeaders.remove0(DefaultHeaders.java 1074) java.lang.NullPointerException : Cannot read field ""hash"" because ""e"" is null

![image](https://github.com/user-attachments/assets/84504e55-503d-4348-bdec-630ee48788a8)

-----------------------------------------------------------------------------------------------------------

## Expected Behavior

![image](https://github.com/user-attachments/assets/1692cc8d-01af-4432-9499-451ea8a46f0c)

use jmeter call http://127.0.0.1:8080/rest
http header
--> Expect: 100-continue

![image](https://github.com/user-attachments/assets/155d4ed0-b184-4f2c-8503-2a753ddad44c)

-----------------------------------------------------------------------------------------------------------
## Actual Behavior

This bug can be reproduced when the http header has Except:100-continue.
Use jmeter or  .net http client (some version default add Except:100-continue to http header) to perform a stress test. Netty NPE errors will appear in about 2-5 minutes.

-----------------------------------------------------------------------------------------------------------

## Steps to Reproduce

[new-netty-gw.zip](https://github.com/user-attachments/files/16339888/new-netty-gw.zip)

http header
--> Expect: 100-continue
![image](https://github.com/user-attachments/assets/f85759f9-27c5-429a-a7e2-ae427100ef8c)

http body
{
"HEADER" : {
"APID": "XX",
"APID": "XX"
},
"BODY" : {
"BOOK_NAME" : "test"
}
}
![image](https://github.com/user-attachments/assets/4d29a7dc-cce9-48c6-a6b3-44deeab0cd56)

error
![image](https://github.com/user-attachments/assets/89f99e33-f703-402a-8c96-d48cb79a8ed6)

-----------------------------------------------------------------------------------------------------------
## Your Environment
* Reactor version(s) used:
netty-codec-4.1.109Final.jar

* Other relevant libraries versions (eg. `netty`, ...):
SpringBoot 3.2 with WebFlux

* JVM version (`java -version`):
JDK 17

* OS and version (eg. `uname -a`):
WINDOWS 10  or  docker alpine

**Comment by violetagg** [comment]
@jeffcf I think that this PR #3362 should be fixing the issue. Are you able to test the SNAPSHOT version?
Depending on you version you can try `1.0.48-SNAPSHOT` or `1.1.22-SNAPSHOT`

**Comment by jeffcf** [comment]
@violetagg Test fails, NPE errors keep happening.

1.1.2-SNAPSHOT

**Comment by violetagg** [comment]
@jeffcf `1.1.2-SNAPSHOT` or `1.1.22-SNAPSHOT`?

**Comment by jeffcf** [comment]
> @jeffcf `1.1.2-SNAPSHOT` or `1.1.22-SNAPSHOT`?

1.1.2-SNAPSHOT

**Comment by violetagg** [comment]
so you need 1.1.22-SNAPSHOT

**Comment by jeffcf** [comment]
Sorry,

1.1.22.SNAPSHOT

![20240723_163919](https://github.com/user-attachments/assets/016ce138-f315-40a6-b3f2-119427416b5c)

**Comment by violetagg** [comment]
@jeffcf about thread group configuration. Take a look at the picture below and tell me your configurations.
<img width="1012" alt="Screenshot 2024-07-23 at 12 55 01" src="https://github.com/user-attachments/assets/e6f04328-c175-404f-a175-7f0ace73acaa">

**Comment by jeffcf** [comment]
@violetagg 
![20240723_182653](https://github.com/user-attachments/assets/eaf22cda-bf75-4884-a203-f5f330cdd2fe)

**Comment by violetagg** [comment]
@jeffcf I do see the problem with the released version, but not with snapshot. Instead of the way that you use for updating the SNAPSHOT, can you use this way. This guarantees that all Reactor binaries will be SNAPSHOT.

```
<properties>
	...
	<reactor-bom.version>2023.0.8-SNAPSHOT</reactor-bom.version>
</properties>
```

**Comment by jeffcf** [comment]
@violetagg 
Use the following pom.xml for testing. It seems that NPE does not appear currently (use the same jmeter test case).

How should I switch to the release version next?

thank you for your help

`<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>3.2.5</version>
		<relativePath /> 
	</parent>

	<groupId>com.jeff</groupId>
	<artifactId>gw-netty</artifactId>
	<version>1.0.0</version>
	<name>gw-netty</name>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<project.reporting.outputEncoding>UTF-8
		</project.reporting.outputEncoding>
		<java.version>17</java.version>
		<reactor-bom.version>2023.0.8-SNAPSHOT</reactor-bom.version>
	</properties>


	<repositories>
		<repository>
			<id>spring-snapshots</id>
			<name>Spring Snapshot Repository</name>
			<url>https://repo.spring.io/snapshot</url>
		</repository>
	</repositories>
	
	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter</artifactId>
			<exclusions>
				<exclusion>
					<groupId>org.springframework.boot</groupId>
					<artifactId>spring-boot-starter-logging</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-log4j2</artifactId>
		</dependency>
		<dependency>
		    <groupId>org.springframework.boot</groupId>
		    <artifactId>spring-boot-starter-test</artifactId>
		    <scope>test</scope>
		</dependency>	
					
		<dependency>
			<groupId>com.lmax</groupId>
			<artifactId>disruptor</artifactId>
			<version>3.4.2</version>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-autoconfigure</artifactId>
		</dependency>
		
		
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-webflux</artifactId>
		</dependency>

		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
			<scope>provided</scope>
		</dependency>

	</dependencies>

	
	<build>
		<finalName>netty-gw</finalName>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>
</project>`

**Comment by violetagg** [comment]
@jeffcf That's good new! The next release is scheduled for 13.08.

**Comment by jeffcf** [comment]
@violetagg 

After release, which version number should I use?  (13.08.)

<reactor-bom.version>2023.0.**9**</reactor-bom.version>   ????

thanks

**Comment by violetagg** [comment]
> @violetagg
> 
> After release, which version number should I use? (13.08.)
> 
> <reactor-bom.version>2023.0.**9**</reactor-bom.version> ????
> 
> thanks

yes
