### ISSUE TITLE
reactor.netty.http.client.PrematureCloseException: Connection has been closed BEFORE response, while sending request body

### ISSUE THREAD

**Issue by DangNguyenTH4** [reactor/reactor-netty#3372]
Sometimes I got this problem after I upgraded my spring cloud gateway version from 2.6.12 to 3.3.1
	
reactor.netty.http.client.PrematureCloseException: Connection has been closed BEFORE response, while sending request body
 
Do I need others config or how can I trace this issue?

**Comment by violetagg** [comment]
@DangNguyenTH4 Please follow this FAQ and provide the TCP dump
https://projectreactor.io/docs/netty/release/reference/index.html#faq.connection-closed

**Comment by DangNguyenTH4** [comment]
Thanks @violetagg 
My two services were deployed in K8S cluster, and this issue did not happen frequently.
I'll try to provide TCP dump asap
