### ISSUE TITLE
Getting timeout exception

### ISSUE THREAD

**Issue by aravindMylsamy** [reactor/reactor-netty#3382]
```java
return webClient
                .get().uri(url)
                .headers { h ->
                    headers.map {
                        h.set(it.key, it.value)
                    }
                }
                .retrieve()
                .bodyToMono(returnType)
                .timeout(requestTimeout ?: defaultRequestTimeout)
                .onErrorMap(this::handleError)
```
Getting below error while doing an api call and it is happening randomly

`java.util.concurrent.TimeoutException: Did not observe any item or terminal signal within 180000ms in flatMap`

**Comment by violetagg** [comment]
@aravindMylsamy Please check the documentation https://projectreactor.io/docs/netty/release/reference/index.html#http-client-timeout
This type of timeout corresponds to the whole operation - starting from connection establishment, TLS handshake etc.
If you need only response timeout consider using the other options.
