### ISSUE TITLE
ByteBufFlux skipping bytes when reading from file channel

### ISSUE THREAD

**Issue by Melozzola** [reactor/reactor-netty#34]
in the [ByteBufFlux.java](https://github.com/reactor/reactor-netty/blob/master/src/main/java/reactor/ipc/netty/ByteBufFlux.java) line 144 the code is erroneously updating the file channel read position after reading a chunk. The position is already updated during the read (line 140) so there is no need to update it again.
The current buggy implementation is skipping bytes as a result.

You can have a look at my fork [here](https://github.com/Melozzola/reactor-netty/tree/issue-34), specifically the [ByteBufFluxTest.java](https://github.com/Melozzola/reactor-netty/blob/issue-34/src/test/java/reactor/ipc/netty/ByteBufFluxTest.java) which is replicating the bug and the [ByteBufFlux.java](https://github.com/Melozzola/reactor-netty/blob/issue-34/src/main/java/reactor/ipc/netty/ByteBufFlux.java) where I added the comment above the buggy line.

I can fix the bug and create a pull request if you wish.

**Comment by smaldini** [comment]
That would be awesome, we try to release a 0.6.1 asap and your report is a perfect good report !
