### ISSUE TITLE
How Effective is the LIFO Strategy in Reactor Netty's Connection Pool for Multi-Host WebClient Scenarios?

### ISSUE THREAD

**Issue by sinbom** [reactor/reactor-netty#3408]
I'm working with Reactor Netty and have configured maxIdleTimeout to minimize connection drops during network communication. The LIFO (Last In, First Out) strategy is designed to efficiently manage connections by reusing the most recently used connection. My understanding is that if the most recent connection drops, it might indicate that earlier connections could also be stale, which helps in managing the connection pool more effectively.

However, I'm dealing with a scenario where multiple WebClient instances share the same connection pool while communicating with different external servers

When the connection pool is shared across multiple hosts, a dropped LIFO connection doesn’t necessarily mean that all connections to other hosts are also disconnected. This makes me question whether the LIFO strategy is still effective in such a multi-host environment, as the assumptions around connection reuse might not hold. In this case, if LIFO is used and the most recent connection is dropped, previous connections may also be considered stale and closed. This could lead to an undesirable situation where valid connections to other hosts are terminated unnecessarily, making LIFO not effective.

Is the LIFO strategy still efficient when the connection pool is shared across multiple WebClient instances communicating with different external hosts, or is the effectiveness of LIFO based on the assumption that separate connection pools are used?

**Comment by violetagg** [comment]
> However, I'm dealing with a scenario where multiple WebClient instances share the same connection pool while communicating with different external servers

> When the connection pool is shared across multiple hosts, a dropped LIFO connection doesn’t necessarily mean that all connections to other hosts are also disconnected.

Most probably you are using one and the same `ConnectionProvider` and not one and the same `connection pool`?
The `ConnectionProvider` is responsible to create `connection pools`. Every `connection pool` is created per remote host (a remote host implies the combination of a hostname and its associated port number)
Please check the documentation https://projectreactor.io/docs/netty/release/reference/index.html#_connection_pool_2
