### ISSUE TITLE
crash occasionally with G1ParScanThreadState::copy_to_survivor_space

### ISSUE THREAD

**Issue by finalch** [reactor/reactor-netty#3409]
## Expected Behavior
no crash
## Actual Behavior
two hs_err_pid.log:
[hs_err_pid53335.log](https://github.com/user-attachments/files/16745227/hs_err_pid53335.log)
[hs_err_pid84685.log](https://github.com/user-attachments/files/16745236/hs_err_pid84685.log)

## Possible Solution
upgrade reactor-netty?

## Your Environment

* Reactor version(s) used: 
0.9.7-RELEASE
* JVM version (`java -version`):
java version "11.0.7" 2020-04-14 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.7+8-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.7+8-LTS, mixed mode)
* OS and version (eg. `uname -a`):
Linux  4.14.0_1-0-0-43 #1 SMP Wed Aug 18 10:05:21 CST 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by violetagg** [comment]
@finalch Reactor Netty version `0.9.7-RELEASE` is not supported. Please update to a supported version: https://github.com/reactor/.github/blob/main/SUPPORT.adoc#support-timeline

**Comment by finalch** [comment]
> @finalch Reactor Netty version `0.9.7-RELEASE` is not supported. Please update to a supported version: https://github.com/reactor/.github/blob/main/SUPPORT.adoc#support-timeline

get it
