### ISSUE TITLE
The EpollSocketChannel object is too large to be reclaimed by the jvm

### ISSUE THREAD

**Issue by userlaojie** [reactor/reactor-netty#3416]
Hello, we are revamping our system with spring-webflux. After the service was started in a Linux environment, it was found that the memory kept increasing, and the memory was never reclaimed by the jvm. After pulling the service dump file, we suspected that the webclient connection pool was cross-referenced, resulting in the EpollSocketChannel object not being reclaimed.
Please help to check whether there is any problem with webclient configuration, or you can check it from other aspects. Thank you.

This is MAT after analyzing a single object over 80M.
![image](https://github.com/user-attachments/assets/42b8c39f-055c-4898-a8fe-ed9fac3c185f)
![image](https://github.com/user-attachments/assets/ae85ece0-c5de-4dcb-9407-a6e67b3c3721)

This is the jvm memory monitoring usage.
![image](https://github.com/user-attachments/assets/d4a196b9-f217-48fe-bb69-c79e69c836c4)

## Steps to Reproduce

The webclient configuration parameters are as follows:
```java
@Slf4j
@Configuration
public class WebClientConfig {
    @Data
    @ConfigurationProperties(prefix = "business.webclient")
    @Configuration
    static class WebClientConnectionConfig {
        private int pendingAcquireTimeout = 50;
        private int maxConnections = 32;
        private int pendingAcquireMaxCount = 1000;
        private long maxIdleTime = 10000;
        private long maxLifeTime = -1;
        private int connectTimeout = 2000;
        private long responseTimeout = 3000;
        private long writeTimeout = 10000;
        private long evictionIntervalTime = 120000;

        @Override
        public String toString() {
            return "WebClientConnectionConfig{" +
                    "pendingAcquireTimeout=" + pendingAcquireTimeout +
                    ", maxConnections=" + maxConnections +
                    ", pendingAcquireMaxCount=" + pendingAcquireMaxCount +
                    ", maxIdleTime=" + maxIdleTime +
                    ", maxLifeTime=" + maxLifeTime +
                    ", connectTimeout=" + connectTimeout +
                    ", responseTimeout=" + responseTimeout +
                    ", writeTimeout=" + writeTimeout +
                    ", evictionIntervalTime=" + evictionIntervalTime +
                    '}';
        }
    }

    @Bean
    public HttpClient httpClient(@Qualifier("webClientConfig.WebClientConnectionConfig")final WebClientConnectionConfig config) throws SSLException {
        log.info("webClientConfig.WebClientConnectionConfig:{}", config.toString());
        ConnectionProvider provider = ConnectionProvider.builder("biz-http-client")
                .pendingAcquireTimeout(Duration.ofMillis(config.getPendingAcquireTimeout()))
                .maxConnections(config.getMaxConnections())
                .maxIdleTime(Duration.ofMillis(config.getMaxIdleTime()))
                .maxLifeTime(Duration.ofMillis(config.getMaxLifeTime()))
                .pendingAcquireMaxCount(config.getPendingAcquireMaxCount())
                .evictInBackground(Duration.ofMillis(config.getEvictionIntervalTime()))
                .build();

        SslContext context = SslContextBuilder.forClient().trustManager(InsecureTrustManagerFactory.INSTANCE).build();

        return HttpClient.create(provider)
                .option(ChannelOption.CONNECT_TIMEOUT_MILLIS, config.getConnectTimeout())
                .responseTimeout(Duration.ofMillis(config.getResponseTimeout()))
                .doOnConnected(conn -> conn.addHandlerLast(new WriteTimeoutHandler(config.getWriteTimeout(), TimeUnit.MILLISECONDS)))
                .secure(t->t.sslContext(context));
    }

    @Bean
    public WebClient webClient(@Qualifier("httpClient")final HttpClient httpClient) {
        WebClient.Builder builder = WebClient.builder();
        DefaultUriBuilderFactory factory = new DefaultUriBuilderFactory();
        factory.setEncodingMode(DefaultUriBuilderFactory.EncodingMode.NONE);

        return builder
                .clientConnector(new ReactorClientHttpConnector(httpClient))
                .codecs(configurer -> {configurer.defaultCodecs()
                        .jackson2JsonEncoder(new Jackson2JsonEncoder(JsonUtils.getMapper()
                                .setSerializationInclusion(JsonInclude.Include.NON_NULL), MediaType.APPLICATION_JSON));
                })
                .defaultHeader("Content-Type", "application/json; charset=UTF-8")
                .uriBuilderFactory(factory)
                .build();
    }
}
```

## Possible Solution

I have two considerations. The first is that ByteBuf references are not released in epoll model, and the second is that webclient connection pool has configuration problems.

## Your Environment

* Reactor version(s) used:1.1.20
* Other relevant libraries versions (eg. `netty`, ...):
```
<dependency>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-starter-webflux</artifactId>
	<version>3.2.7</version>
</dependency>
```
* JVM version (`java -version`):OpenJDK
* system version (eg. `uname -a`):CentOS Linux 7 (Core)

**Comment by userlaojie** [comment]
This is jstat GC statistics, and the number of cgc and ygc is almost the same.
![image](https://github.com/user-attachments/assets/00fdc2ce-ddf9-48a4-ad1f-ae24ee2de2a1)

**Comment by kzander91** [comment]
I believe we have the same issue on reactor-netty 1.1.22, Netty 4.1.112, Spring Boot 3.3.3:
![grafik](https://github.com/user-attachments/assets/ae6fe8cb-ae50-44f8-aee4-e2dff576e73c)

`EpollSocketChannel` objects are not being garbage-collected.
I looked into some of these instances and they all seem to be referenced by invalidated pooled connections:
![grafik](https://github.com/user-attachments/assets/cc541cea-2c34-45aa-aef2-58824c9a094f)

Have recent releases changed anything w.r.t. pool entry invalidation?

**Comment by lfs1985** [comment]
We have the same issue.
Reactor version(s) used:1.1.20
Spring Boot: 3.2.7
JVM version (java -version):OpenJDK 17
EpollSocketChannel is more than 1.27G，but not  being garbage-collected。

**Comment by userlaojie** [comment]
Ok, we will try to reproduce the scene locally with the jmeter pressure test interface, which will take a day

**Comment by kzander91** [comment]
@userlaojie any luck so far? I myself have been unable to reliably reproduce it.
The tricky thing is that even in my production application, the leak doesn't always happen.
Sometimes it starts leaking until a crash, then, after the reboot, everything is fine for many days.

Considering that in [my heap dump](https://github.com/reactor/reactor-netty/issues/3416#issuecomment-2337449383), the pool refs are all in `STATE_INVALIDATED`, maybe its related to connections being closed abnormally?

**Comment by vitjouda** [comment]
Hi, I strongly believe you came across the same problem as I did, please check [my issue](https://github.com/reactor/reactor-netty/issues/3367) if you observe the same behavior.

**Comment by userlaojie** [comment]
抱歉，同样的我们无法在本地复现这种情况，我们最新进度是尽可能的去除会导致http连接未释放因素，比如说去除micrometer使用，不使用自定义MeterRegistry.
以下即为最新监控数据，部分pod依然存在内存过高情况：
channel-qrcode-pay-7686b6d777-5pjgj
![image](https://github.com/user-attachments/assets/6ad64700-8515-49c8-af83-6536601ea9dc)
channel-qrcode-pay-6959cf9bb4-b5zst
![image](https://github.com/user-attachments/assets/d4179fad-d4c6-48a3-a1f7-8aa4345feafc)

**Comment by vitjouda** [comment]
Hi, I managed to replicate part of the problem and currently discussing it on gitter. If you have the same problem, there are 2 ways how to mitigate it at the moment. Either replace reactor-netty with different, WebClient supported library (we used Apache HttpClient 5, works well), or if you can handle it disable connection keepAlive. In our case, both options eliminate the leak. Of course disabling keepalive is not great and a long-term solution, but you can at least verify if its the same problem. Performance hit will depend on your use case.

**Comment by violetagg** [comment]
I'm working on a fix for an issue that I found with the reproducer that @vitjouda provided on Gitter

**Comment by violetagg** [comment]
@userlaojie @vitjouda #3459 should be addressing this issue. If you are able to test the snapshot version, it will be great!

**Comment by vitjouda** [comment]
Hi, I am going to deploy the snapshot and let it sit for a day or 2 and report back. Thank you for the fix.

**Comment by vitjouda** [comment]
Hi again, I tested the snapshot and it looks good! Thank you for the fix :)
