### ISSUE TITLE
System environment variable option to configure the `ConnectionProvider's evictInBackground` setting

### ISSUE THREAD

**Issue by syedyusufh** [reactor/reactor-netty#3440]
1. Why isn't there a system environment variable option to configure the `ConnectionProvider's evictInBackground` setting as how it is available for the other settings?

2. Will setting the below 2 have an effect on the `maxIdleTime` and `maxLifeTime` though there isn't an `evictInBackground` thread configured to run the cleanup?

```
long DEFAULT_POOL_MAX_IDLE_TIME = Long.parseLong(System.getProperty(ReactorNetty.POOL_MAX_IDLE_TIME, "-1"));

long DEFAULT_POOL_MAX_LIFE_TIME = Long.parseLong(System.getProperty(ReactorNetty.POOL_MAX_LIFE_TIME, "-1"));
```

Please suggest.

**Comment by violetagg** [comment]
> 1. Why isn't there a system environment variable option to configure the `ConnectionProvider's evictInBackground` setting as how it is available for the other settings?

We exposed only the core configurations as system properties (although we do not recommend system properties for configuring `ConnectionProvider`).
Why we do not recommend system properties - the system property will configure all `ConnectionProvider`s in one JVM if they do not override this configuration. What this means:
Let say that you have system property for configuring max idle timeout. For your use case this configuration is something that you need. Now let say that you use a third party library that uses Reactor Netty and relies that the is no max idle timeout by default (i.e. it does not disable explicitly max idle timeout). Once you set a system property with some max idle timeout it will be applied to this third party library also and its behaviour might become not as expected.

> 2. Will setting the below 2 have an effect on the `maxIdleTime` and `maxLifeTime` though there isn't an `evictInBackground` thread configured to run the cleanup?

By default `maxIdleTime` and `maxLifeTime` are checked when a connection is released to/ acquired from the connection pool.
If you enable `evictInBackground`, in addition to the above there will be also a background process that will check these timeouts.

> 
> ```
> long DEFAULT_POOL_MAX_IDLE_TIME = Long.parseLong(System.getProperty(ReactorNetty.POOL_MAX_IDLE_TIME, "-1"));
> 
> long DEFAULT_POOL_MAX_LIFE_TIME = Long.parseLong(System.getProperty(ReactorNetty.POOL_MAX_LIFE_TIME, "-1"));
> ```
> 
> Please suggest.

**Comment by syedyusufh** [comment]
Thanks @violetagg  for the very detailed explanation. We can close this issue.
