### ISSUE TITLE
Websocket client NettyContext.dispose() does not change disposed state

### ISSUE THREAD

**Issue by mostroverkhov** [reactor/reactor-netty#345]
### Expected behavior
Client `NettyContext.dispose()` should eventually lead to
* `NettyContext.onClose()` completion
* `NettyContext.isDisposed() = true` 
### Actual behavior
* `NettyContext.onClose()` is not completed
* `NettyContext.isDisposed() = false` 

### Steps to reproduce
[snippet](https://gist.github.com/mostroverkhov/d4818a37fe1bb20f0a6e725919349a41)

### Reactor Netty version
`0.7.6.RELEASE`
### JVM version (e.g. `java -version`)

```
java version "1.8.0_171"
Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.171-b11, mixed mode)
```
### OS version (e.g. `uname -a`)
```
Linux desktop 4.4.0-116-generic #140~14.04.1-Ubuntu SMP Fri Feb 16 09:25:20 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by mostroverkhov** [comment]
originally reported in https://github.com/rsocket/rsocket-java/issues/492

**Comment by mostroverkhov** [comment]
@violetagg I have tested proposed change on current master, and see `NettyContext.isDisposed()` true even without calling dispose() - expected It to be false before dispose and true after. Also `onClose()` still not triggered

**Comment by violetagg** [comment]
@mostroverkhov this is because the `server` sends the `CloseWebSocketFrame`
you have this

```
httpServer = HttpServer.create(0)
                .newHandler((in, out) -> out.sendWebsocket((i, o) -> o.sendString(
                        Mono.just("test"))))
                .block(Duration.ofSeconds(30));
```

which means once the `Mono` completes the `server` will send `CloseWebSocketFrame`
and you can see in the logs the following

```
06:56:36.529 [reactor-http-nio-6] DEBUG r.ipc.netty.http.server.HttpServer - [id: 0xde242ff5, L:/127.0.0.1:59936 - R:/127.0.0.1:59937] WRITE: 6B
         +-------------------------------------------------+
         |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
+--------+-------------------------------------------------+----------------+
|00000000| 81 04 74 65 73 74                               |..test          |
+--------+-------------------------------------------------+----------------+
06:56:36.530 [reactor-http-nio-6] DEBUG r.ipc.netty.http.server.HttpServer - [id: 0xde242ff5, L:/127.0.0.1:59936 - R:/127.0.0.1:59937] FLUSH
06:56:36.531 [reactor-http-nio-6] DEBUG r.i.n.c.ChannelOperationsHandler - [id: 0xde242ff5, L:/127.0.0.1:59936 - R:/127.0.0.1:59937] Writing object CloseWebSocketFrame(data: UnpooledByteBufAllocator$InstrumentedUnpooledUnsafeHeapByteBuf(ridx: 0, widx: 0, cap: 0))
```

because of this you see that the `context` is disposed

if you change the test to

```
.newHandler((in, out) -> out.options(sendOptions -> sendOptions.flushOnEach())
                        .sendWebsocket((i, o) -> o.sendString(
                                Flux.interval(Duration.ofSeconds(1))
                                        .map(aLong -> aLong+""))))
```

then the `server` will not send `CloseWebSocketFrame`
and when you invoke `dispose` then the `client` will do that and will close the connection
for `onClose` you might be right I have to check that

**Comment by mostroverkhov** [comment]
So that's because my output stream completed to early - got it. Modified my example a bit and `isDisposed()` working as expected. Looking forward for `onClose`.

**Comment by violetagg** [comment]
thanks for testing
fix committed
