### ISSUE TITLE
Question: Half Closed Connections

### ISSUE THREAD

**Issue by Melozzola** [reactor/reactor-netty#35]
I'm wondering if there is a way in reactor-netty to shut down the output (from the client to the server) once the data has been written to the channel. Shutting down the output means calling [SocketChannel#shutdownOutput()](https://docs.oracle.com/javase/8/docs/api/java/nio/channels/SocketChannel.html#shutdownOutput--)

Essentially I have a Publisher<ByteBuf> that is producing the data to send. Shutting down the output when the Publisher finishes might be too early because there might be pending writes. Is there a way to intercept when all the writes have been completed?
My TCP server (on which I don't have control) is waiting for the shut shutdownOutput() signal before starting sending the response.

**Comment by smaldini** [comment]
We should be able to do that indeed - that seems in fact a miss from TCP client and even Http client depending on it!

**Comment by Melozzola** [comment]
Thanks guys for the REACTIVE response :-)
Do you have any idea when 0.6.2.RELEASE will be released? Just a rough estimation like in the next 2/3 months?

**Comment by smaldini** [comment]
Like in reactor-core the ideal goal is to bring a patch every month or so. I'd expect a new version in March for instance before Spring 5 RC1 possibly.

**Comment by Fetsivalen** [comment]
Hi,
Is there any plans to support half-closed state? 
Or maybe some recomended workaraund exists?

**Comment by violetagg** [comment]
@Fetsivalen Did you try the latest release?

**Comment by violetagg** [comment]
@Melozzola @Fetsivalen tested this with the latest 0.9.x and it is working
the test case a40c949

**Comment by Fetsivalen** [comment]
@violetagg I missed that option. Thanks, i't looks like it will cover my case.
