### ISSUE TITLE
Number values not posting correctly

### ISSUE THREAD

**Issue by letkemanpete78** [reactor/reactor-netty#352]
Here is the code https://github.com/letkemanpete78/Greetings which is modified copy of
https://spring.io/guides/gs/handling-form-submission/. I simply added a second number value to the model and duplicated the form inputs. Kotlin version of the code provided as well, but it is not active.
The problem shows itself with these lines of code:
```
Logger.getGlobal().info(greeting.getContent().toString());
Logger.getGlobal().info(String.valueOf(greeting.getId()));
Logger.getGlobal().info(String.valueOf(greeting.getNumX()));
```
Notice that the numeric values are not all treated the same way as the character values. 
It was my understanding that the submitted values should return a comma separated list.

**Comment by rstoyanchev** [comment]
> It was my understanding that the submitted values should return a comma separated list.

List of what? You're binding to a long, which of course cannot represent multiple values, and all you're getting is the first value. Changing to `List<Long>` or `long[]` works as expected, but then you also need to update the view to show `id[0]`, `id[1]`, etc.

At any rate, this the issue tracker, and not a place for asking howto questions. Furthermore the question is related to Spring WebFlux, and the is the issue tracker for Reactor Netty.
