### ISSUE TITLE
Potentialy leak

### ISSUE THREAD

**Issue by GenCloud** [reactor/reactor-netty#3527]
Found a potential memory leak in the MicrometerHttpClientMetricsRecorder handler, namely - uri is denormalized with arguments in the path or query arguments. Timer cache will always write a new value to the same path with different arguments in it.

## Expected behavior
Path normalization should occur (snapshot at the stage of passing the URI object/UriComponentsBuilder/just a string with common argument designations) and initialization of 1 timer instance per 1 path

## Actual behavior
The path is passed as is and due to the large amount of variability of arguments, the cache swells and causes OOM.
/api/v1/SYSTEM_32?param_b=123
/api/v1/SYSTEM_32/action?param_b=123

## Minimum steps to reproduce
**details omitted, semantics preserved, requests with different arguments over 1 million per day
```java
    public static void main(String[] args) {
        final WebClient client = WebClient.builder()
                .clientConnector(
                        new ReactorClientHttpConnector(
                                HttpClient.create()
                                        .metrics(true, Function.identity())
                        )
                )
                .build();

        final URI uri = UriComponentsBuilder
                .fromUriString("http://localhost")
                .path("/api/v1/{id}/action")
                .queryParam("pageSize", "100")
                .buildAndExpand(ThreadLocalRandom.current().nextInt())
                .encode()
                .toUri();

        client.get()
                .uri(uri)
                .attribute("notWarn404", true)
                .retrieve()
                .bodyToMono(String.class)
                .subscribe();
    }
```

## Possible solution
snapshot at the stage of passing the URI object/UriComponentsBuilder/just a string with common argument notations
```
/api/v1/SYSTEM_32?param_b=123 -> /api/v1/{param_a}?param_b={value_b}
/api/v1/SYSTEM_32/action?param_b=123 -> /api/v1/{param_a}/action?param_b={value_b}
```

## Your environment
Reproduce it on all versions.
Spring WebFlux 3.1.4
Reactor Netty 1.1.11

**Comment by violetagg** [comment]
@GenCloud Thanks for getting in touch!

Please check the notes here:
* https://projectreactor.io/docs/netty/release/api/reactor/netty/http/client/HttpClient.html#metrics-boolean-java.util.function.Function-
* https://projectreactor.io/docs/netty/release/reference/http-client.html#metrics

In the logs you should have:

```
Metrics are enabled with [uriTagValue=Function#identity]. It is strongly recommended to provide template-like form for the URIs. Without a conversion to a template-like form, each distinct URI leads to the creation of a distinct tag, which takes a lot of memory for the metrics.
```

**Comment by GenCloud** [comment]
This logic may be too redundant if you take a large number of argument names into account. At the same time, it is necessary to collect metrics for all routes, which does not go away. And limiting the number of timers is also not an option.

**Comment by violetagg** [comment]
@GenCloud It is up to the user to decide what kind of templating needs to be used, Reactor Netty cannot decide this.

**Comment by violetagg** [comment]
@GenCloud As I explained about it is not Reactor Netty responsibility to decide how to interpret and template the uri.
