### ISSUE TITLE
An improved simple / detailed string for ClientOptions

### ISSUE THREAD

**Issue by filiphr** [reactor/reactor-netty#353]
Recently support for clustered of STOMP endpoint addresses was added to the Spring Websocket Broker relay ([SPR-12452](https://jira.spring.io/browse/SPR-12452)).

Which means that it is possible to provide round robin or some more complex address supplier to the `ReactorNettyTcpClient` in `spring-websocket`

```java
Consumer<ClientOptions.Builder<?>> builderConsumer = builder -> {
        builder.connectAddress(()-> {
        // Select address to connect to ...
    });
};
```

This lead to [SPR-16801](https://jira.spring.io/browse/SPR-16801) in order to get better information logging from the `StompBrokerRelayMessageHandler`. I think that we agreed with @rstoyanchev that delegating to the underlying `TcpClient#toString()` makes the most sense to provide the best possible information in case custom `TcpClient` is used.

After investigating a bit I noticed that the [`TcpClient#toString()`](https://github.com/reactor/reactor-netty/blob/master/src/main/java/reactor/ipc/netty/tcp/TcpClient.java#L153) actually calls the `ClientOptions#asSimpleString()` whose implementation looks like:

```
StringBuilder s = new StringBuilder();
if (getAddress() == null) {
    s.append("connecting to no base address");
}
else {
    s.append("connecting to ").append(getAddress());
}
if (proxyOptions != null) {
     s.append(" through ").append(proxyOptions.getType()).append(" proxy");
}
return s.toString();
```

Where `getAddress()` actually invokes the `Supplier` for the address. Which leads to the fact that if I have a round robin supplier the information provided by the `asSimpleString()` and `asDetailedString()` is really harmful as it assumes that the `Supplier` supplies with the same address on each call, which in our case is not like that.

What I can propose is to do some memoization in `ClientOptions#getAddress()` and store the last supplied address and use that address in the already mentioned methods. This in my opinion would be "more" correct than the current implementation (in case of a custom `Supplier`).

**Comment by rstoyanchev** [comment]
The `ClientOptions.Builder` is going away in 0.8. Nevertheless, bottom line is that when logging the address, extra care should be taken for when a custom `Supplier` is configured, since that may return a different address each time it is called.

**Comment by filiphr** [comment]
Good to know about the `ClientOptions.Builder`. Is it already out? I can go through the code and give some ideas with the new code. I guess 0.8 would come in Spring 5.1 and Boot 2.1? 

Is there a possibility to do something for 0.7.x so we can get that in Spring 5.0 and Boot 2.0?

**Comment by violetagg** [comment]
Check this issue against master

**Comment by violetagg** [comment]
@filiphr @rstoyanchev This is not applicable any more - the implementation was changed
