### ISSUE TITLE
How to config metricsEnabled=true in pool

### ISSUE THREAD

**Issue by sunyuanfeng** [reactor/reactor-netty#3556]
reactor-netty-0.9.10.RELEASE

I want to config metricsEnabled is true, but I can not do it. 
How to do it for springboot project?

**Comment by violetagg** [comment]
Thanks for getting in touch, but your Reactor Netty version is not supported anymore. Please update to a supported version (more info [here](https://github.com/reactor/.github/blob/main/SUPPORT.adoc#support-timeline))
