### ISSUE TITLE
DisposableServer.isDisposed() doesn't work

### ISSUE THREAD

**Issue by smaldini** [reactor/reactor-netty#360]
Seems like server selector channel never changes active state after close:
```
//some server
server.isDisposed();; //false
server.channel().isActive(); //true
server.channel().isOpen(); //true

//stopping
server.dispose();

//later
server.isDisposed();; //false
server.channel().isActive(); //true
server.channel().isOpen(); //false
```

**Comment by smaldini** [comment]
cc @nebhale

**Comment by SyedMuhammadSufyian** [comment]
Is this bug still relevant ?

**Comment by violetagg** [comment]
I cannot reproduce this with the current `1.0.4-SNAPSHOT` version. Test case will be added with PR #1501 in order to ensure that `DisposableServer.isDisposed()` works as expected.
