### ISSUE TITLE
block（） spring webflux ServerHttpRequest get body 

### ISSUE THREAD

**Issue by yu199195** [reactor/reactor-netty#364]
### Actual behavior
public abstract class AbstractGatewayWebFilter implements WebFilter {

    @Override
    public Mono<Void> filter(final ServerWebExchange exchange, final WebFilterChain chain) {
        final ServerHttpResponse response = exchange.getResponse();
        final List<DataBuffer> collect = exchange.getRequest().getBody().toStream().
                collect(Collectors.toList());
        response.getHeaders().setContentType(MediaType.APPLICATION_JSON_UTF8);
        return doFilter(exchange, chain).switchIfEmpty(Mono.just(false))
                .flatMap(filterResult -> filterResult ? chain.filter(exchange) : doDenyResponse(exchange));
    }
### Steps to reproduce
 final List<DataBuffer> collect = exchange.getRequest().getBody().toStream().
                collect(Collectors.toList());
this block in webflux
### Reactor Netty version
spring webflux 2.0 
### JVM version (e.g. `java -version`)
1.8

**Comment by violetagg** [comment]
Hi,

For questions, discussions, use the channels below:

Reactor Netty -> https://gitter.im/reactor/reactor
Spring Boot -> https://gitter.im/spring-projects/spring-boot
Spring Framework -> https://spring.io/questions

Regards,
Violeta
