### ISSUE TITLE
in spring webflux post size more then 8kb,it not work

### ISSUE THREAD

**Issue by yu199195** [reactor/reactor-netty#365]
hi, i use spring5 webflux

when post request body more then 8kb ，it was miss filed，

help me。。。

**Comment by violetagg** [comment]
Please specify the concrete Spring Framework version

**Comment by yu199195** [comment]
i use spring boot 2.0 spring framework version 5.0.4

**Comment by yu199195** [comment]
httpServer ：
  @Bean
    public HttpServer httpServer() {
        return HttpServer.create(builder -> {
            builder.maxChunkSize(8192 * 8);
            builder.maxHeaderSize(8192 * 8);
            builder.initialBufferSize(256);
            builder.maxInitialLineLength(8192);
            builder.port(8080);
        });

    }
but it not work

**Comment by violetagg** [comment]
@yu199195 we have fixes that are included in Spring Framework 5.0.6 so please try with that version.

**Comment by yu199195** [comment]
http post too long, Is it needed  HttpObjectAggregator

**Comment by violetagg** [comment]
@yu199195 can you describe a bit more the use case that you have? Do you really want the whole request body in the memory? Can't you work with the request body chunks?

**Comment by rstoyanchev** [comment]
The example method has has multiple issues, but before we even get there, it does not even compile due to "Missing return statement".

**Comment by yu199195** [comment]
I want to in webfilter  get request body。
now I met this problem：
when  request body is too large，more then 1024b
the first request：
 final Flux<DataBuffer> body = exchange.getRequest().getBody();
this DataBuffer  body  size is 555.
The second request：
final Flux<DataBuffer> body = exchange.getRequest().getBody(); is true。

Is there a limit to the length of the post request by netty?
help me。。

**Comment by bclozel** [comment]
Closing in favour of [the StackOverflow question](https://stackoverflow.com/questions/50626367/spring-webflux-how-get-request-body-in-webfilter) (which is better suited for questions in the first place).
