### ISSUE TITLE
Make more data accessible from the `DefaultServerWebExchange` object

### ISSUE THREAD

**Issue by jmcshane** [reactor/reactor-netty#366]
### Expected behavior

Provide some mechanism to access Netty `HttpRequest` and  `HttpResponse` from the `DefaultServerWebExchange`.

It appears that this would require adding methods to the `HttpOperations` class or increasing visibility of `HttpServerOperations`.

Another option that would work in my use case would be to provide more getters in the high level `HttpOperations` class that reach into the native objects themselves. Key information that is not available at this time are the request protocol and the status code of the exchange during the `doAfterSuccessOrError` phase.

### Actual behavior

Currently, getting at these underlying native objects requires reflection or creating a class in a `reactor.ipc.netty.http.server` package myself which casts to the `HttpServerOperations` class.

### Steps to reproduce

What I am currently doing to access the native response/request object:

```
((HttpServerOperations)((AbstractServerHttpResponse)
                exchange.getResponse()).getNativeResponse())
                .nettyResponse
```

Status code is unset in `exchange.getResponse()`:

```
        System.out.println(exchange.getResponse().getStatusCode());
        int code =  ((HttpServerOperations)((AbstractServerHttpResponse)
                exchange.getResponse()).getNativeResponse())
                .nettyResponse.status().code();
        System.out.println(code);
```

Output:

```
null
200
```

### Reactor Core version

0.7.7.RELEASE

### JVM version (e.g. `java -version`)

```
java version "9.0.1"
Java(TM) SE Runtime Environment (build 9.0.1+11)
```
### OS Version

```
17.5.0 Darwin Kernel Version 17.5.0: Fri Apr 13 19:32:32 PDT 2018; root:xnu-4570.51.2~1/RELEASE_X86_64 x86_64
```

**Comment by rstoyanchev** [comment]
Is there anything missing in Spring WebFlux that requires such access to the Netty request or response? They're not meant to be accessed that way.

**Comment by jmcshane** [comment]
@rstoyanchev the status code is my main concern. I haven't found a time in the lifecycle of the "call" `Mono<Void>` object where this is set on the `AbstractServerHttpResponse` class from spring-webflux, whereas it appears to be set successfully within the native response.

I have not been able to access the http version (obviously most often `HTTP/1.1`) for the request from any other source besides the native request either.

**Comment by rstoyanchev** [comment]
it doesn't sound like a good reason to change anything, or expose the Netty response. The question rather is what are you trying to do? Show a little more detail of how you handle the request (annotated controller, handler function), and what you've tried, or what you're not sure about.

**Comment by violetagg** [comment]
Closing as there is no response from the author.
Also for questions, discussions etc. it is better to use the channels below:
Reactor Netty -> https://gitter.im/reactor/reactor
Spring Boot -> https://gitter.im/spring-projects/spring-boot
Spring Framework -> https://spring.io/questions
