### ISSUE TITLE
Expose read-only port/address when server binding errors

### ISSUE THREAD

**Issue by bclozel** [reactor/reactor-netty#368]
With the new `HttpServer` and `DisposableServer` API in Reactor Netty 0.8, we seem to be missing a way to get the port information from the server itself.

It is available from `DisposableServer`, but we can't get that information in case the server could not bind (in that case, `DisposableServer` is null and we're getting back an exception).

This issue is basically a new instance of #66, which was being used by Spring Boot so far.

**Comment by rstoyanchev** [comment]
Along similar lines, there used to be a way to check if loopResources or poolResources were registered, which was originally requested in #24, the last paragraph:

> It would also be very useful for ClientOptions to expose a way to expose what an option is currently set to so that I can also accept external options and add my own only if others are not provided -- same thing that TcpClient#create would have to do.

So far [this was used](https://github.com/smaldini/spring-framework/blob/37b0ed9fcb74c42dd6a8de24834d5ac7e75392f6/spring-messaging/src/main/java/org/springframework/messaging/tcp/reactor/ReactorNettyTcpClient.java#L134-L137) in a constructor that customizes options without setting and shutting down resources.

**Comment by violetagg** [comment]
@rstoyanchev There are only two constructors 
`public ReactorNettyTcpClient(String host, int port, ReactorNettyCodec<P> codec)`
and
`public ReactorNettyTcpClient(TcpClient tcpClient, ReactorNettyCodec<P> codec)`
Do you still have this requirement?

**Comment by violetagg** [comment]
@bclozel can you take a look at the PR and tell us whether this will help?

**Comment by bclozel** [comment]
It would help a bit, but I'd still need to parse the exception message to get the local address. Could you add a getter to expose that information directly on the exception itself?

**Comment by violetagg** [comment]
I added a getter for the local address.

**Comment by bclozel** [comment]
Perfect, thanks!

**Comment by violetagg** [comment]
New PR #398
