### ISSUE TITLE
Reactor Netty is slower to start than Tomcat

### ISSUE THREAD

**Issue by sdeleuze** [reactor/reactor-netty#376]
This is not obvious with Spring Boot but [Spring Fu minimal webapp benchmarks](https://github.com/spring-projects/spring-fu/tree/master/samples/minimal-webapp) seems to indicate than Reactor Netty is slower to start than Tomcat.

**Rector Netty:**
 Application started in 0.609 seconds (JVM running for 0.879)
 Application started in 0.676 seconds (JVM running for 0.97)
 Application started in 0.672 seconds (JVM running for 0.958)

**Tomcat:**
 Application started in 0.440 seconds (JVM running for 0.709)
 Application started in 0.440 seconds (JVM running for 0.723)
 Application started in 0.445 seconds (JVM running for 0.72)

This should maybe be explored and optimized.

To run Spring Fu minimal webapp with Reactor Netty:
```
git clone https://github.com/spring-projects/spring-fu.git
./gradlew clean build
java -XX:TieredStopAtLevel=1 -noverify -jar target/demo-startup-kotlin-0.0.1-SNAPSHOT.jar
```

To use Tomcat, update `samples/minimal-webapp/build.gradle.kts` with:
```
dependencies {
	implementation(project(":modules:webflux-tomcat"))
	testImplementation(project(":modules:webflux-netty"))
	testImplementation(project(":modules:test"))
}
```
And `Application.kt` with `server(tomcat())`.

To use Undertow, update `samples/minimal-webapp/build.gradle.kts` with:
```
dependencies {
	implementation(project(":modules:webflux-undertow"))
	testImplementation(project(":modules:webflux-netty"))
	testImplementation(project(":modules:test"))
}
```
And `Application.kt` with `server(undertow())`.

**Comment by violetagg** [comment]
Is it correct that this is with Reactor Netty 0.7.x and not the current master?

**Comment by sdeleuze** [comment]
Nope, this is using Reactor Netty `0.8.BUILD-SNAPSHOT` builds since Spring Fu depends on Spring Framework 5.1 snapshots.

**Comment by smaldini** [comment]
Linked to #382

**Comment by sdeleuze** [comment]
@violetagg I will be on PTO next week so I won't be able to do these test, but I suggest to test with `4.1.26.Final-SNAPSHOT` as it fix the thread started in initializer issue. Also in your tests Reactor Netty is still significantly slower than Tomcat, right?

**Comment by violetagg** [comment]
With the latest snapshot these are the measurements:

Reactor Netty
```
Application started in 0.293 seconds (JVM running for 0.608)
Application started in 0.294 seconds (JVM running for 0.599)
Application started in 0.286 seconds (JVM running for 0.591)
Application started in 0.289 seconds (JVM running for 0.596)
```

Tomcat
```
Application started in 0.443 seconds (JVM running for 0.735)
Application started in 0.443 seconds (JVM running for 0.74)
Application started in 0.443 seconds (JVM running for 0.741)
Application started in 0.447 seconds (JVM running for 0.742)
```

**Comment by sdeleuze** [comment]
Amazing, huge improvement!
