### ISSUE TITLE
Error on create HTTP/2 Request with 0.8.0.BUILD-SNAPSHOT version 

### ISSUE THREAD

**Issue by enricosecondulfo** [reactor/reactor-netty#387]
Hello guys,
i'm trying to create a get request to a http/2 server with `reactor-netty` version 0.8.0.BUILD-SNAPSHOT, but i receive the same error

> Exception in thread "main" java.lang.NullPointerException 	at
> reactor.netty.tcp.SslProvider.<init>(SslProvider.java:309) 	at
> reactor.netty.tcp.SslProvider$Build.build(SslProvider.java:473) 	at
> reactor.netty.tcp.TcpClientSecure.secure(TcpClientSecure.java:37) 	at
> reactor.netty.tcp.TcpClient.secure(TcpClient.java:493) 	at
> reactor.netty.http.client.HttpClientSecure.tcpConfiguration(HttpClientSecure.java:57)
> 	at reactor.netty.http.client.HttpClient.request(HttpClient.java:573)
> 	at reactor.netty.http.client.HttpClient.get(HttpClient.java:454) 	at
> ApplicationKt.main(Application.kt:36)

The `Kotlin` code i used is the following

    class Test

    fun main(args: Array<String>) {

	val trustManagerFactory: TrustManagerFactory = 
	TrustManagerFactory.getInstance("SunX509")
	val trustStore: KeyStore = KeyStore.getInstance("JKS")

	trustStore.load(Test::class.java.getResourceAsStream("MyClient.jks"), 
	"*************".toCharArray())
	trustManagerFactory.init(trustStore)

	val sslContext: SslContext = SslContextBuilder
	.forClient()
	.trustManager(trustManagerFactory)
	.build()

	val sslProviderBuilder: SslProvider.Builder = SslProvider
	.builder()
	.sslContext(sslContext)

    ConnectionProvider.fixed("test", 1000)

	HttpClient
	.create(ConnectionProvider.fixed("test", 1000))
	.secure { sslProviderBuilder }
	.get()
	.uri("https://localhost:8000/ping")
	.response()
	.block()
    }

**Comment by violetagg** [comment]
Hi,

I'll add `null` check, however I don't think the example is correct.
The `secure` method accept `Consumer`.
The same example if written on Java cannot be compiled.
So try the change below.

```
HttpClient
.create(ConnectionProvider.fixed("test", 1000))
.secure {t -> t.sslContext(sslContext)}
.get()
.uri("https://localhost:8000/ping")
.response()
.block()
}
```
