### ISSUE TITLE
Configure timeout options on HttpClient with new API

### ISSUE THREAD

**Issue by bclozel** [reactor/reactor-netty#390]
With the new `HttpClient`/`TcpClient` configuration APIs, I've tried customizing the timeout options for the HTTP client.

While I can change the connection timeout like this:

```java
TcpClient tcpClient = TcpClient.create();
tcpClient.configure()
	.option(ChannelOption.CONNECT_TIMEOUT_MILLIS, 1000);
HttpClient httpClient = HttpClient.from(tcpClient);
```

I cannot find a way to configure the read and write timeouts, as it was previously explained in this [StackOverflow answer](https://stackoverflow.com/a/49140846/22982). Is there still a way (or an easier way) to configure that part of the `HttpClient`?

**Comment by violetagg** [comment]
@bclozel You can configure the timeouts like the sample below:

```
TcpClient tcpClient =
        TcpClient.create()
                        .option(ChannelOption.CONNECT_TIMEOUT_MILLIS, 1000)
                        .doOnConnected(connection ->
                                connection.addHandlerLast(new ReadTimeoutHandler(10))
                                                   .addHandlerLast(new WriteTimeoutHandler(10)));
HttpClient httpClient = HttpClient.from(tcpClient);
```

**Comment by bclozel** [comment]
Thanks a lot @violetagg !
