### ISSUE TITLE
Mono from sendWebSocket completes at the end of the session

### ISSUE THREAD

**Issue by rstoyanchev** [reactor/reactor-netty#393]
Not sure 100% if this is an issue or expected behavior but according to the Javadoc for `HttpServerResponse#sendWebSocket` it returns "a Mono completing when upgrade is confirmed". Instead the Mono seems to complete only after WebSocket session handling completes.

This comes through an issue reported against Spring Session and then the Spring Framework https://jira.spring.io/browse/SPR-17051 where a WebSocket handshake request completes at the end of the WebSocket connection (i.e. much later) and saves an already invalidated WebSession causing havoc.

**Comment by rstoyanchev** [comment]
I would prefer if it worked as Javadoc says. 

The handshake/upgrade is associated with an `HttpHandler` (or a `BiFunction<HttpServerRequest, HttpServerResponse, Mono<Void>>` in Reactor Netty) while the the WebSocket session is associated with a `WebSocketHandler` (or a `BiFunction<? super WebsocketInbound, ? super WebsocketOutbound, ? extends Publisher<Void>>` in Reactor Netty). 

The two have different lifecycles and duration (short vs potentially very long) and different potential outcomes (e.g. successful upgrade but error in websocket session). Combining the two like that leads to strange results like attempting to save an already invalidated `WebSession` (because user logged out in another tab) because the WebFilter chain was held up for the entire duration of the WebSocket session.

**Comment by yu199195** [comment]
ues spring webflux websocket ，Just one big request ，AbstractChannelHandlerContext CPU 100%
