### ISSUE TITLE
HttpClient.create() shares SSL configuration across multiple instances

### ISSUE THREAD

**Issue by mp911de** [reactor/reactor-netty#407]
### Expected behavior

Calling `HttpClient.create().secure(Consumer)` (and `HttpClient.create()`) should apply SSL config only for the underlying instance independently from earlier client instances.

### Actual behavior

`HttpClient.create().secure(…)` does not apply SSL context (from `SslContextBuilder`) to the newly created instance.

Using a dedicated `ConnectionProvider` (such as `ConnectionProvider.fixed()`) mitigates the issue.

### Steps to reproduce

```java
HttpClient client = HttpClient.create();
// Interact with client to initialize connection provider.

SslContextBuilder sslContextBuilder = SslContextBuilder.forClient();

// provide a specific SSL config such as client certificates.
HttpClient otherClient = HttpClient.create().secure(builder -> {
			builder.sslContext(sslContextBuilder);
});

// access TLS-secured resource
```

### Reactor Netty version

0.8.0.M1

### JVM version (e.g. `java -version`)

1.8.0

### OS version (e.g. `uname -a`)

MacOS X

**Comment by smaldini** [comment]
Probably Related to #90

**Comment by violetagg** [comment]
@mp911de Can you test PR #449

**Comment by mp911de** [comment]
The issue still persists. Looking at the patch, the code compares host and port to decide whether the pool is suitable. In my case, I'm providing a different SSL configuration that uses the same host/port.

**Comment by violetagg** [comment]
@mp911de Can you test the latest snapshot?

**Comment by violetagg** [comment]
thanks 👍
