### ISSUE TITLE
Shutting down a netty TcpClient channel in Reactor 3.0.4

### ISSUE THREAD

**Issue by jakobklein** [reactor/reactor-netty#41]
tcpClient.shutdown() was removed from the API and now a TcpClient connection cannot be closed properly.
Find a detailed description on:
https://stackoverflow.com/questions/42069471/shutting-down-a-netty-tcpclient-channel-in-reactor-3-0-4

Attachment:
I put together a minimal client-server-testcase illustrating the scenario described on stackoverflow.

[reactorDisconnectTest.zip](https://github.com/reactor/reactor-netty/files/772446/reactorDisconnectTest.zip)

**Comment by jakobklein** [comment]
related to https://github.com/reactor/reactor-netty/issues/15

**Comment by simonbasle** [comment]
@jakobklein does [this commit](https://github.com/reactor/reactor-netty/commit/d9d956393428977b75939b95a1e538aadefe6de5) fix the issue for you?

**Comment by jakobklein** [comment]
Thx for your notice. I'll have a look probably next week.

**Comment by jakobklein** [comment]
Cannot confirm. Cannot test it. TcpClient seems to have some dependency-issues in 0.7.0.M1

`TcpClient.create(60021);`
works with 
  **reactor-core:3.0.7.RELEASE, reactor-netty:0.6.4.RELEASE**

But with 
	**reactor-core:3.0.7.RELEASE, reactor-netty:0.7.0.M1**
it throws
`	java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: reactor/core/CoreSubscriber`
and with 
	**reactor-core:3.1.0.M3, reactor-netty:0.7.0.M1**
it throws
`	java.lang.NoClassDefFoundError: io/netty/buffer/PooledByteBufAllocator`

**Comment by violetagg** [comment]
Hi,

Can you verify that Netty version that is in use is `4.1.13.Final`?

Thanks,
Violeta

**Comment by jakobklein** [comment]
### Verified:
\.m2\repository\io\projectreactor\reactor-core\3.1.0.M3\reactor-core-3.1.0.M3.jar
\.m2\repository\org\reactivestreams\reactive-streams\1.0.1-RC2\reactive-streams-1.0.1-RC2.jar
\.m2\repository\io\projectreactor\ipc\reactor-netty\0.7.0.M1\reactor-netty-0.7.0.M1.jar
\.m2\repository\io\netty\netty-codec-http\4.1.13.Final\netty-codec-http-4.1.13.Final.jar
\.m2\repository\io\netty\netty-codec\4.1.13.Final\netty-codec-4.1.13.Final.jar
\.m2\repository\io\netty\netty-handler\4.1.13.Final\netty-handler-4.1.13.Final.jar
\.m2\repository\io\netty\netty-buffer\4.1.13.Final\netty-buffer-4.1.13.Final.jar
\.m2\repository\io\netty\netty-transport\4.1.13.Final\netty-transport-4.1.13.Final.jar
\.m2\repository\io\netty\netty-resolver\4.1.13.Final\netty-resolver-4.1.13.Final.jar
\.m2\repository\io\netty\netty-handler-proxy\4.1.13.Final\netty-handler-proxy-4.1.13.Final.jar
\.m2\repository\io\netty\netty-codec-socks\4.1.13.Final\netty-codec-socks-4.1.13.Final.jar
\.m2\repository\io\netty\netty-transport-native-epoll\4.1.13.Final\netty-transport-native-epoll-4.1.13.Final.jar
\.m2\repository\io\netty\netty-common\4.1.13.Final\netty-common-4.1.13.Final.jar
\.m2\repository\io\netty\netty-transport-native-unix-common\4.1.13.Final\netty-transport-native-unix-common-4.1.13.Final.jar
\.m2\repository\io\projectreactor\ipc\reactor-ipc\0.7.0.M1\reactor-ipc-0.7.0.M1.jar
\.m2\repository\junit\junit\4.12\junit-4.12.jar
\.m2\repository\org\hamcrest\hamcrest-core\1.3\hamcrest-core-1.3.jar

**Comment by violetagg** [comment]
Can you provide some test that reproduces `java.lang.NoClassDefFoundError: io/netty/buffer/PooledByteBufAllocator`?

Did you try to clean the maven repo and to rebuild?

Thanks,
Violeta

**Comment by jakobklein** [comment]
Cleaning the maven cache was the key. Thx for your hint.

I still need a workaround on server-side to make sure the channel was closed. I added this on stackoverflow.

But I can approve that the API is clearer and easier to use now. So you may close this issue.
