### ISSUE TITLE
Allow users to specify what type of cookie decoders are used

### ISSUE THREAD

**Issue by thekalinga** [reactor/reactor-netty#412]
### Expected behavior
User should be allowed to use either `ClientCookieDecoder.STRICT` (or) `ClientCookieDecoder.LAX` (and server variants) decoder of his choice when using `HttpClient`(may be `HttpServer`)

Some servers does not respond with complaint `RFC6265` complaint cookies & current implementation forces everyone to use only `RFC6265` complaint cookie decoders & it is not a wise decision as servers are not in the control of clients

### Actual behavior
The library forces everyone to use just `ClientCookieDecoder.STRICT` inside `Cookies` class

### Steps to reproduce

Take a look at

https://github.com/reactor/reactor-netty/blob/v0.8.0.M1/src/main/java/reactor/netty/http/Cookies.java#L99

and 

https://github.com/reactor/reactor-netty/blob/v0.8.0.M1/src/main/java/reactor/netty/http/Cookies.java#L108

### Reactor Netty version

0.8.0.M1

### JVM version (e.g. `java -version`)

NA

### OS version (e.g. `uname -a`)

NA

**Comment by violetagg** [comment]
Please check #418 whether the API is sufficient.
Thanks.

**Comment by thekalinga** [comment]
@violetagg Sorry, I completely forgot to respond. Yes.. the new API allows us to customise the codec configuration

Thanks
