### ISSUE TITLE
hello ，How can I handle the 301 redirect of the server, can I get the redirected data directly, or does it still exist?

### ISSUE THREAD

**Issue by switchYello** [reactor/reactor-netty#423]

**Comment by violetagg** [comment]
For questions please ask on [Gitter](https://gitter.im/reactor/reactor)

Teke a look here for an example https://github.com/reactor/reactor-netty/blob/0.7.x/src/test/java/reactor/ipc/netty/http/client/HttpRedirectTest.java#L84
