### ISSUE TITLE
ReactorNettyWebSocketClient socket closes after subscribe

### ISSUE THREAD

**Issue by Ben-Mark** [reactor/reactor-netty#426]
### Expected behavior
Expecting ReactorNettyWebSocketClient to keep the socket open

### Actual behavior
I'm connecting to a remote server which isn't neety/reactor/java related
with jetty, the socket stays open
but with ReactorNettyWebSocketClient  the socket closes right after I send and receive the payload

### Steps to reproduce

        MonoProcessor<JsonNode> output = MonoProcessor.create();
        WebSocketClient client = new ReactorNettyWebSocketClient();
        Mono<Void> sessionMono = client.execute(URI.create("ws://localhost:8188"),
               session -> {

                    return session.send(Mono.just(session.textMessage(payloadToSend)))
                            .thenMany(session.receive()
                                   // .timeout(Duration.ofDays(1))
                                    .map(WebSocketMessage::getPayloadAsText)
                                    .map(jsonStringify -> jsonMapper.deserialize(jsonStringify, JsonNode.class))
                                    .subscribeWith(output)
                                    .then())
                            .then();
                });
        return output.doOnSubscribe(s -> sessionMono.subscribe());

### Reactor Netty version

springBootVersion = '2.0.4.RELEASE'

### JVM version (e.g. `java -version`)

java 8 
java version "1.8.0_172"

### OS version (e.g. `uname -a`)
mac osx highsierra

**Comment by violetagg** [comment]
@Ben-Mark What is exactly the use case that you want to achieve? The example above is working in this way because you use `MonoProcessor` which will cancel the inbound connection.

**Comment by Ben-Mark** [comment]
My use-case is to communicate via socket to another server where that is a media server which needs its sessions to be alive
Once the socket breaks , the inner session is lost.
Therefore I need all socket connections to stay open, any clue on how to achieve that will be blessed
Thanks.

**Comment by Ben-Mark** [comment]
Hi, is there any update or anything that I can help with regarding this issue?

**Comment by smaldini** [comment]
You should not subscribe MonoProcessor (otherwise called "FirstProcessor") that would cancel the flow it subscribes to at the first signal it receives.
2 Solutions: 
- Use `doOnNext(output::onNext)`, note that after the first json the other json would be ignored in this example
- Use `ReplayProcessor` instead and if you consume your output for the first value : `output.next().subscribe(json -> dosomething(json))`

**Comment by smaldini** [comment]
I will close this for now but don't hesitate to re-open.
