### ISSUE TITLE
Provide more options for customising the access log

### ISSUE THREAD

**Issue by violetagg** [reactor/reactor-netty#436]

**Comment by jkubrynski** [comment]
Is there any idea of this customization? Should it be on a code-level or just a string format parsed by the AccessLog ?

**Comment by sonofelice** [comment]
I also have the same problem. I want to add some info from httpServeletRequest, like the access log of tomcat.How can I customize the log format?

**Comment by sonofelice** [comment]
Is there any progress here?

**Comment by jkubrynski** [comment]
I offered a PR, but there is no decision on how this customization should look like. Programmatic or string pattern

**Comment by sonofelice** [comment]
I did not find your pr link. Would you like put the link here?

**Comment by sonofelice** [comment]
> I offered a PR, but there is no decision on how this customization should look like. Programmatic or string pattern

I did not find your pr link. Would you like put the link here?

**Comment by naturallight** [comment]
Is there any update?

**Comment by ek-ex** [comment]
Could you also include the request headers to this enhancement ? Thank you

**Comment by violetagg** [comment]
Fixed with #1357
