### ISSUE TITLE
Is this a good way to execute blocking code in reactor-netty + webflux?

### ISSUE THREAD

**Issue by mmanciop** [reactor/reactor-netty#443]
I need to mix blocking and non-blocking code (*sigh*). I came up with https://github.com/mmanciop/webflux-blocking-example, which *seems* to work fine, at least in terms of threads.

I'd love to hear from the reactor experts if this approach is actually OK, or is there are hidden pitfalls I am missing.

**Comment by CinnamonBagels** [comment]
[The documentation](https://projectreactor.io/docs/core/release/reference/#faq.wrap-blocking) provides a good example on how to wrap blocking code

From your example, your code could look something like this:
```java
return Mono.fromCallable(() -> {
  Thread.sleep(2000);
  //...
})
.subscribeOn(Schedulers.elastic()) 
.publishOn(REACTOR_HTTP_NIO_SCHEDULER)
.then(Mono.just("Delayed Greetings"));
```

**Comment by mmanciop** [comment]
I cleaned up the code and added some comments, hoping to bring the point across better.

**Comment by crankydillo** [comment]
@mmanciop The reactor-core guidance above has changed to suggesting a bound elastic scheduler, which alleviates one of your concerns.  Apologies, but I didn't really think much about your restated question:)

**Comment by mmanciop** [comment]
@crankydillo thanks for the pointer. I am closing this issue, my question is answered.
