### ISSUE TITLE
Newly created pooled connection forwards the wrong connection to the Mono

### ISSUE THREAD

**Issue by smaldini** [reactor/reactor-netty#447]
Detected while upgrading RSocket to 0.8. If the thread pool of the client is 1, the current PooledConnectionProvider#run was going to invoke the last sink.success() before connection gets transformed via ChannelOperationHandler#channelActive.

**Comment by smaldini** [comment]
Should be fixed by https://github.com/reactor/reactor-netty/commit/935ddef4c68031571bb27b964b789465413373e2 - waiting confirmation @OlegDokuka

**Comment by OlegDokuka** [comment]
Fixed my issue. We can close
