### ISSUE TITLE
Changing the Order of the Spring Security WebFilter

### ISSUE THREAD

**Issue by fifothekid** [reactor/reactor-netty#448]
Changing the Order of the Spring Security WebFilter

I have an API Gateway implemented using Spring Cloud Gateway that uses Spring Security. Spring Security for WebFlux is implemented as a WebFilter right at the beginning of the filter chain. So after successful authentication the request would be forwarded to Spring Cloud Gateway's RoutePredicateHandlerMapping, which would try to deduce the destination based on the URL pattern, and then it would go to a FilteringWebHandler to execute the other filters of Spring Cloud Gateway.

My problem is the following: I have implemented a customized authentication algorithm which uses query string and header variables as credentials for authentication according to the requirements of the project, an this is working without any problem. The problem occurred when we needed to add a small customization for the authentication algorithm that is path independent. When the request reaches the WebFilter of Spring Security, pattern matching is not yet done so I do not know which application does it point to, for example:

app1:

-Path: /app1/**

app2:

-Path: /app2/**

Which means that instead of having authentication -> route mapping -> filtering web handler I should do route mapping -> authentication -> filtering web handler. Not that these three components are not similar, one of them is a filter another is a mapper and the last one is web handler. Now I know how to customize them but the problem is that I do not know how to intercept the Netty server building process in order to change the order of these operations. I need to wait for the building process to end and alter the content of the server before it starts. How can I do that?

**Comment by violetagg** [comment]
Hi,

Please use the proper channel for Spring Framework questions
https://stackoverflow.com/questions/52637351/changing-the-order-of-the-spring-security-webfilter

Regards,
Violeta
