### ISSUE TITLE
Improve Pipeline configuration

### ISSUE THREAD

**Issue by smaldini** [reactor/reactor-netty#454]
We have noted with @violetagg that creating keys for PooledConnectionProvider can be challenging because of the pipeline configuration matching. For instance, a previous connection can require what we call "static" handlers such as ssl, log or proxy, while the next acquired connection will not. This part is mostly fine, the problem is when specific transport add their own handler like HttpClient with compression or http codec itself. A next acquired connection could or could not reuse these handler and should be differentiated as 2 different connections in that case.

We should review current infrastructure to make this choice easier and clearer for maintenance except of adding custom code in various places, eventually combined with Connection#addHandler to have limited handler lifecycle.

**Comment by violetagg** [comment]
This was addressed with Reactor Netty 1.0.0 GA, every transport configuration provides a `channelHash` implementation
https://projectreactor.io/docs/netty/release/api/reactor/netty/transport/TransportConfig.html#channelHash--
Closing this issue.
