### ISSUE TITLE
Logging NPE

### ISSUE THREAD

**Issue by magnusp** [reactor/reactor-netty#471]
### Expected behavior
Using ConsoleAppender debug or log4j2 trace should not NPE (maybe?)

### Actual behavior
Default ConsoleAppender NPE on debug. Adding Log4j2 on trace level seems to hide the NPE in the stacktrace, but the "java.lang.Exception: ChannelOperation terminal stack" is still sent to output.

### Steps to reproduce
Gist with [output, testcase. gradle dependencies and log4j2.properties](https://gist.github.com/magnusp/c0e0027a020e9e2a86e69c60248df5f7)

### Reactor Netty version
Californium-SR1, 0.8.1-RELEASE

### JVM version (e.g. `java -version`)
openjdk version "11.0.1" 2018-10-16
OpenJDK Runtime Environment 18.9 (build 11.0.1+13)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.1+13, mixed mode)

### OS version (e.g. `uname -a`)
Windows 10

**Comment by violetagg** [comment]
@magnusp The issue is in Reactor Core's `ConsoleLogger`/`JdkLogger` - https://github.com/reactor/reactor-core/pull/1396

Log4j2 does not hide the NPE

Log message with Logback is:
```
12:10:36.766 [reactor-http-nio-5] DEBUG reactor.netty.ReactorNetty - [id: 0xcd3be55a, L:/0:0:0:0:0:0:0:1:64487 ! R:/0:0:0:0:0:0:0:1:8080] Non Removed handler: reactor.left.httpAggregator, context: null, pipeline: DefaultChannelPipeline{(reactor.left.loggingHandler = io.netty.handler.logging.LoggingHandler), (ws-decoder = io.netty.handler.codec.http.websocketx.WebSocket13FrameDecoder), (ws-encoder = io.netty.handler.codec.http.websocketx.WebSocket13FrameEncoder), (reactor.right.reactiveBridge = reactor.netty.channel.ChannelOperationsHandler)}
```

Log message with Log4j2 is:
```
[DEBUG] 2018-10-20 12:08:13.075 [reactor-http-nio-5] ReactorNetty - [id: 0xed156691, L:/0:0:0:0:0:0:0:1:64437 ! R:/0:0:0:0:0:0:0:1:8080] Non Removed handler: reactor.left.httpAggregator, context: null, pipeline: DefaultChannelPipeline{(reactor.left.loggingHandler = io.netty.handler.logging.LoggingHandler), (ws-decoder = io.netty.handler.codec.http.websocketx.WebSocket13FrameDecoder), (ws-encoder = io.netty.handler.codec.http.websocketx.WebSocket13FrameEncoder), (reactor.right.reactiveBridge = reactor.netty.channel.ChannelOperationsHandler)}
```

After applying the fix in the PR the log message in the console is:
```
[DEBUG] (reactor-http-nio-5) [id: 0x35eeddf5, L:/0:0:0:0:0:0:0:1:49857 ! R:/0:0:0:0:0:0:0:1:8080] Non Removed handler: reactor.left.httpAggregator, context: null, pipeline: DefaultChannelPipeline{(reactor.left.loggingHandler = io.netty.handler.logging.LoggingHandler), (ws-decoder = io.netty.handler.codec.http.websocketx.WebSocket13FrameDecoder), (ws-encoder = io.netty.handler.codec.http.websocketx.WebSocket13FrameEncoder), (reactor.right.reactiveBridge = reactor.netty.channel.ChannelOperationsHandler)}
```

The expected result is `context: null`

**Comment by simonbasle** [comment]
as this impact core's 3.1.x version, the above PR has been closed and is being redone. See https://github.com/reactor/reactor-core/issues/1403.
