### ISSUE TITLE
Log Remote IP address in the access log

### ISSUE THREAD

**Issue by hota911** [reactor/reactor-netty#476]
If a server is running behind a load balancer, the remote client IP address is not logged in access log.  I'd like to have an option to log the IP address stored in `X-Forwarded-For` header if it exists, otherwise the client IP address.

Maybe this could be addressed in #436, but I'm filing this issue for the specific need.

**Comment by LyStormrage** [comment]
I had the same problem，it's always nginx server ip address. And I can't customize the format

**Comment by jkubrynski** [comment]
Is there any progress here? If no, are you open for pull requests?

**Comment by violetagg** [comment]
@jkubrynski Sure we are OK with pull requests. If you have an idea for a pull request go for it.

**Comment by violetagg** [comment]
Fixed with #1357
