### ISSUE TITLE
HTTP2 with HTTP1 : HTTP1 is always used

### ISSUE THREAD

**Issue by vincent-wuhrlin** [reactor/reactor-netty#484]
### Expected behavior
I have configured Netty Reactor with Spring Boot and HTTP2. All is working fine, thanks for these awesome frameworks. However, it's impossible to use HTTP2 with HTTP1 (TLS), because in this case, only HTTP1 is always used and prior to HTTP2.

It is possible to use HTTP2 and HTTP1 together, and fallback to HTTP1 only if client doesn't support it ?

Thanks you for your help.

#### HTTP 2
I have configured **ReactiveWebServerFactory**, and when i enabled only HTTP2, all is working fine, logs (curl / server) are below :
[http2 only - server.log](https://github.com/reactor/reactor-netty/files/2521841/http2.only.-.server.log)
[http2 only - client.log](https://github.com/reactor/reactor-netty/files/2521842/http2.only.-.client.log)

#### HTTP 2 + HTTP 1
My objective is to fallback to HTTP1 if browser doesn't support HTTP2.
I have configured **ReactiveWebServerFactory**, and added HTTP1 in protocols list.
All is working fine, but HTTP1 is always used, and HTTP2 never enabled, even with curl flag **--http2**. Logs (curl / server) are below :
[http1.1 + http2 - client.log](https://github.com/reactor/reactor-netty/files/2521889/http1.1.%2B.http2.-.client.log)
[http1.1 + http2 - server.log](https://github.com/reactor/reactor-netty/files/2521890/http1.1.%2B.http2.-.server.log)

### Steps to reproduce
Simply create an HTTP Server with Spring boot and customize **ReactiveWebServerFactory** :
```
NettyReactiveWebServerFactory factory = new NettyReactiveWebServerFactory();
...
factory.addServerCustomizers(httpServer ->
{
    return httpServer.protocol(HttpProtocol.HTTP11, HttpProtocol.H2);
});
```

### Reactor Netty version
0.8.1.RELEASE

### JVM version (e.g. `java -version`)
java version "10.0.2" 2018-07-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.2+13)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.2+13, mixed mode)

### OS version (e.g. `uname -a`)
Darwin MBP-de-Vincent 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64

**Comment by smaldini** [comment]
Good catch we didnt use application protocol selection in that case, should be fixed in the release today.

**Comment by smaldini** [comment]
Also for H2 vs H2C make sure you configure SSL somewhere : 

```java
SelfSignedCertificate cert = new SelfSignedCertificate();
		SslContextBuilder serverOptions = SslContextBuilder.forServer(cert.certificate(), cert.privateKey());

	DisposableServer server =
				HttpServer.create()
				          .protocol(HttpProtocol.H2, HttpProtocol.HTTP11)
				          .secure(ssl -> ssl.sslContext(serverOptions))
				          .port(8080)
				          .handle((req, res) -> res.sendString(Mono.just("Hello")))
				          .wiretap(true)
				          .bindNow();

		new CountDownLatch(1).await();
		server.disposeNow();
	}

	@Test
	@Ignore
	public void testIssue395() throws Exception {
		BiFunction<HttpServerRequest, HttpServerResponse, Mono<Void>> echoHandler =
				(req, res) -> res.send(req.receive().map(ByteBuf::retain)).then();

		SelfSignedCertificate cert = new SelfSignedCertificate();
		SslContextBuilder serverOptions = SslContextBuilder.forServer(cert.certificate(), cert.privateKey());
		DisposableServer server =
				HttpServer.create()
				          .secure(ssl -> ssl.sslContext(serverOptions))
				          .protocol(HttpProtocol.H2)
				          .handle(echoHandler)
				          .port(8080)
				          .wiretap(true)
				          .bindNow();

		new CountDownLatch(1).await();
		server.disposeNow();
	}

	@Test
	@Ignore
	public void testHttp1or2Secure() throws Exception {
		SelfSignedCertificate cert = new SelfSignedCertificate();
		SslContextBuilder serverOptions = SslContextBuilder.forServer(cert.certificate(), cert.privateKey());

		DisposableServer server =
				HttpServer.create()
				          .protocol(HttpProtocol.H2, HttpProtocol.HTTP11)
				          .secure(ssl -> ssl.sslContext(serverOptions))
				          .port(8080)
				          .handle((req, res) -> res.sendString(Mono.just("Hello")))
				          .wiretap(true)
				          .bindNow();

		new CountDownLatch(1).await();
		server.disposeNow();
	}

	@Test
	public void testHttpNoSslH2Fails()  {
		StepVerifier.create(
			HttpServer.create()
			          .protocol(HttpProtocol.H2)
			          .handle((req, res) -> res.sendString(Mono.just("Hello")))
			          .wiretap(true)
			          .bind()
		).verifyErrorMessage("Configured H2 protocol without TLS. Use" +
				" a clear-text h2 protocol via HttpServer#protocol or configure TLS" +
				" via HttpServer#secure");
	}

	@Test
	public void testHttpSslH2CFails()  throws Exception {
		SelfSignedCertificate cert = new SelfSignedCertificate();
		SslContextBuilder serverOptions = SslContextBuilder.forServer(cert.certificate(), cert.privateKey());

		StepVerifier.create(
			HttpServer.create()
			          .protocol(HttpProtocol.H2C)
			          .secure(ssl -> ssl.sslContext(serverOptions))
			          .handle((req, res) -> res.sendString(Mono.just("Hello")))
			          .wiretap(true)
			          .bind()
		).verifyErrorMessage("Configured H2 Clear-Text protocol with TLS. Use the non clear-text h2 protocol via HttpServer#protocol or disable TLS via HttpServer#tcpConfiguration(tcp -> tcp.noSSL())");
	}

	@Test(expected = IllegalArgumentException.class)
	public void testIssue387() {
		HttpServer.create()
		          .secure(sslContextSpec -> System.out.println())
		          .bindNow();
	}
}
```
