### ISSUE TITLE
Elevated log level

### ISSUE THREAD

**Issue by nebhale** [reactor/reactor-netty#487]
In `reactor-netty` 0.8.1.RELEASE (Californium-SR2) there are at least two log messages at WARN that should have a lower level:

```
WARN main reactor.netty.tcp.TcpResources [tcp] resources will use the default LoopResources: DefaultLoopResources {prefix=reactor-tcp, daemon=true, selectCount=8, workerCount=8}
WARN main reactor.netty.tcp.TcpResources [tcp] resources will use the default ConnectionProvider: PooledConnectionProvider {name=tcp, poolFactory=reactor.netty.resources.ConnectionProvider$$Lambda$426/799260198@4287d447}
```

**Comment by violetagg** [comment]
@nebhale Hi Ben this is a result of the following requirement #416 This is a warning that the default LoopResource and ConnectionProvider will be used.
@rstoyanchev :point_up_2:

**Comment by nebhale** [comment]
I understand the request, but that's disappointing.  As I don't think that using the defaults is a WARN-worthy log message (I'd expect "default" behavior to be safe, not something you need to be warned about) I'll need to crank my configuration to `ERROR` for that logger losing any "real" warnings that might be generated.

**Comment by rstoyanchev** [comment]
I agree with Ben, the defaults shouldn't be a WARN, possibly INFO at most. 

The request for the WARN was for any changes to the default since that releases the previous resources, which may disrupt others who were trying to use the global.
