### ISSUE TITLE
WebClient posting multiple duplicate HTTP requests

### ISSUE THREAD

**Issue by praveenk007** [reactor/reactor-netty#492]
Hi,

I am using spring-boot v2.0.0.M6. I have to make several async post requests to my other application which is on Play framework. Somehow WebClient is making duplicate requests.
Please check this link for detailed explanation on this issue.
https://stackoverflow.com/questions/53129956/springboot-v2-0-0-m6-webclient-making-multiple-duplicate-http-post-calls

**Comment by violetagg** [comment]
Hi,

Please try the latest releases - 2.0.6.RELEASE or 2.1.0.RELEASE.
Also please do not cross post, this repository is for Reactor Netty project, for Spring Framework (Web Client) use this https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#create-a-ticket

Regards,
Violeta
