### ISSUE TITLE
How to control max header size for http client

### ISSUE THREAD

**Issue by tony-clarke-amdocs** [reactor/reactor-netty#531]
The http server as an ability to set the max http header size (defaults to 8K). 
It is not clear if there is a limit on the client side and if there is a limit how to change that limit?

**Comment by violetagg** [comment]
@tony-clarke-amdocs Just to clarify the request here. The requirement is for the response coming from the server correct? For the requests sent to the server there is no limit.

**Comment by tony-clarke-amdocs** [comment]
@violetagg Don't we want to be able to control the size in request and the response. But if there is no limit from the client to the server then the priority of this is lower.

**Comment by violetagg** [comment]
An API is added for controlling the settings of the incoming responses. For the outgoing requests there is no limitation.
