### ISSUE TITLE
Add DNS resolver observer, and options for client

### ISSUE THREAD

**Issue by smaldini** [reactor/reactor-netty#538]
We should be able to provide TcpClient options for DNS resolution in addition to custom resolver as in #501 : 
- DNS resolution timeout
- DNS positive/negative TTL
- [?] Internal cache eviction period
- doOnResolvedAddress

**Comment by PyvesB** [comment]
It would indeed be very handy to be able to fine-tune some of the DNS resolution settings!

In addition to the points listed above, I would suggest adding the ability to "manually" evict from the internal cache. For example, some content delivery networks recommend to re-resolve DNS on certain types of status codes (e.g. 500 internal server error). Client code could build simple logic around such error cases and force DNS re-resolution on subsequent attempts of the same request.

**Comment by violetagg** [comment]
Reactor Netty now uses Netty DNS Resolver #1252

**Comment by PyvesB** [comment]
Thanks for looking into this @violetagg !
