### ISSUE TITLE
HttpClient: impossible to send POST request with Content-Length header

### ISSUE THREAD

**Issue by chemist777** [reactor/reactor-netty#550]
### Expected behavior
I want to send POST request with known(fixed) `Content-Length` header.
```java
httpClient
.headers(headers -> {
    headers.set(HttpHeaderNames.CONTENT_LENGTH, 123);
})
.post()
.uri("/some")
.send(Mono.just(buffer))
```
### Actual behavior
`Content-Length` header is removed from the POST request and `Content-Encoding: chunked` is set.

### Reactor Netty version
0.8.3.RELEASE

**Comment by violetagg** [comment]
#548 Please try 0.8.4.BUILD-SNAPSHOT
