### ISSUE TITLE
HttpClient#chunkedTransfer(false) only works when "Content-Length" is set.

### ISSUE THREAD

**Issue by dantesun** [reactor/reactor-netty#553]
I am not sure it's an expected behavior or not. But I found that `HttpClient#chunkedTransfer(false)` actually only works if `Content-Length` is explicitly set by user. Because `transfer-encoding: chunked` is re-inserted by `HttpClientOperations#sendObject`. Here is the code:

```
public NettyOutbound sendObject(Publisher<?> dataStream) {
		if (!HttpUtil.isTransferEncodingChunked(nettyRequest) &&
				!HttpUtil.isContentLengthSet(nettyRequest) &&
				!method().equals(HttpMethod.HEAD) &&
				!hasSentHeaders()) {
			HttpUtil.setTransferEncodingChunked(nettyRequest, true);
		}
		return super.sendObject(dataStream);
	}
```

version: 0.8.3.RELEASE

**Comment by violetagg** [comment]
@dantesun May be you observe the issue that is fixed with #548 
Can you test with `0.8.4.BUILD-SNAPSHOT`?

**Comment by violetagg** [comment]
@dantesun Do you expect an exception to be returned in this use case?
https://tools.ietf.org/html/rfc7230#section-3.3.2
```
A user agent SHOULD send a Content-Length in a request message when
   no Transfer-Encoding is sent and the request method defines a meaning
   for an enclosed payload body.  For example, a Content-Length header
   field is normally sent in a POST request even when the value is 0
   (indicating an empty payload body).  A user agent SHOULD NOT send a
   Content-Length header field when the request message does not contain
   a payload body and the method semantics do not anticipate such a
   body.
```

**Comment by dantesun** [comment]
Actually, It would be better reactor-netty set the content-length automatically if possible. Adding content-length header manually is not user-friendly....

**Comment by violetagg** [comment]
@dantesun How we can calculate the `Content-Length`? We do that for `GET` requests
https://github.com/reactor/reactor-netty/blob/master/src/main/java/reactor/netty/http/client/HttpClientOperations.java#L801
, but these use case is a rare use case and the expected body is not big.

**Comment by dantesun** [comment]
> @dantesun How are we able to calculate the `Content-Length`? We do that for `GET` requests
> https://github.com/reactor/reactor-netty/blob/master/src/main/java/reactor/netty/http/client/HttpClientOperations.java#L801
> , but this use case is a rare use case and the expected body is not big.

Yes you are right. I think throwing an exception when `HttpClient#chunkedTransfer(false)` without a  `Content-Length` is a better solution. Just as you mentioned earlier.

**Comment by violetagg** [comment]
@dantesun Here is our proposal: We will deprecate `HttpClient#chunkedTransfer`, so by default `Transfer-Encoding: chunked` will be applied for those HTTP methods for which a request body is expected. If the user wants to disable that setting then the user can provide `Content-Length` via request headers and thus `Transfer-Encoding` will be removed. Wdyt?

**Comment by dantesun** [comment]
I am totally fine with this. It would be better if a document explains this behavior. When will the reactor-netty reference guide be released?
