### ISSUE TITLE
HTTP client - Fixed connection pool + big response payloads + concurrent requests = unresponsive computer

### ISSUE THREAD

**Issue by crankydillo** [reactor/reactor-netty#556]
Using reactor-netty to make a bunch of concurrent requests causes my macbook to become unresponsive.

### Expected behavior
I expect all the request to complete in a timely manner.

### Actual behavior
My macbook becomes totally unresponsive.  I have to hard reboot.  Colleagues have reproduced on their system.

### Steps to reproduce
Follow the instructions [here](https://github.com/sharathsrinivasa/httpclientbenchmark/issues/6).

### Reactor Netty version
0.8.3

### JVM version (e.g. `java -version`)
$ java -version
java version "1.8.0_162"
Java(TM) SE Runtime Environment (build 1.8.0_162-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.162-b12, mixed mode)

### OS version (e.g. `uname -a`)
$ uname -a
Darwin LM-AUN-00873781 16.7.0 Darwin Kernel Version 16.7.0: Sun Oct 28 22:30:19 PDT 2018; root:xnu-3789.73.27~1/RELEASE_X86_64 x86_64

**Comment by violetagg** [comment]
@crankydillo Can you also tell us `CONNECT_TIMEOUT` and `READ_TIMEOUT`. Thanks

**Comment by violetagg** [comment]
hope these are the correct settings https://github.com/sharathsrinivasa/httpclientbenchmark/blob/master/benchmarkcommon/src/main/java/com/ss/benchmark/httpclient/common/BenchmarkCommon.java#L17

**Comment by crankydillo** [comment]
Yes, those constants come from that class.  I thought I removed those, but I guess I didn't.  Basically, I wrote that `main` method within the [ReactorNetty test-thats-a-performance-test](https://github.com/sharathsrinivasa/httpclientbenchmark/blob/master/reactornettybenchmark/src/test/java/com/ss/benchmark/httpclient/reactornetty/ReactorNettyHCPerformanceTests.java).

**Comment by crankydillo** [comment]
We're going to handle this in another way.

**Comment by smaldini** [comment]
I think the issue stands in general as we are fixing the builder API incurring a significant overhead, micro optimizations of the sending/receiving will follow but it is certainly a situation we want to improve.

**Comment by smaldini** [comment]
Should be linked to #577

**Comment by smaldini** [comment]
Also linking to #568 and #578

**Comment by violetagg** [comment]
@crankydillo Can you test the latest 0.8.8.RELEASE?

**Comment by violetagg** [comment]
We did several improvements in the API and the internal implementation in 0.8.x, 0.9.x and 1.0.x
I'm closing this one.

**Comment by crankydillo** [comment]
> @crankydillo Can you test the latest 0.8.8.RELEASE?

Hi @violetagg .  Apologies for this ridiculously late response, but we are not currently suffering from this.  We're using 1.0.3 and 1.0.8 currently.
