### ISSUE TITLE
Reports of slower than expected large POST body requests

### ISSUE THREAD

**Issue by smaldini** [reactor/reactor-netty#577]
A few users have reported negative observations about how large bodies (or at least greater than 10KB) disproportionally influence request time. It could be assumed the same is true in the other way as a server replies a relatively large body as well.

Might depend on #524 to assist in the investigation.

**Comment by violetagg** [comment]
@smaldini Is this still valid after 0.8.8.RELEASE?

**Comment by xuxiao1987** [comment]
hi，Has the problem been solved?

**Comment by violetagg** [comment]
We did several improvements in the API and the internal implementation in 0.8.x, 0.9.x and 1.0.x
I'm closing this one.
