### ISSUE TITLE
Scheduler worker in group main failed with StackOverflowError

### ISSUE THREAD

**Issue by gxl191911** [reactor/reactor-netty#580]
2019-01-18 09:00:31.230 ERROR 26 --- [      elastic-3] reactor.core.scheduler.Schedulers        : Scheduler worker in group main failed with an uncaught exception
java.lang.StackOverflowError: null
	at java.base/java.util.stream.Streams$ConcatSpliterator.estimateSize(Streams.java:743) ~[na:na]
	at java.base/java.util.stream.Streams$ConcatSpliterator.estimateSize(Streams.java:743) ~[na:na]

**Comment by gxl191911** [comment]
> 2019-01-18 09:00:31.230 ERROR 26 --- [ elastic-3] reactor.core.scheduler.Schedulers : Scheduler worker in group main failed with an uncaught exception
> java.lang.StackOverflowError: null
> at java.base/java.util.stream.Streams$ConcatSpliterator.estimateSize(Streams.java:743) ~[na:na]
> at java.base/java.util.stream.Streams$ConcatSpliterator.estimateSize(Streams.java:743) ~[na:na]

 update to 'Bismuth-SR15' for resolve 'client close premature',but now have a new erroe.

**Comment by violetagg** [comment]
@gxl191911 Can you provide some reproducible scenario or at least describe what you are trying to achieve?

**Comment by gxl191911** [comment]
> Can you provide some reproducible scenario or at least describe what you are trying to achieve?

I use spring cloud gateway,but after some days, this error  will reproduce.
And unrepeatable at this time。
My current solution is to adjust the virtual stack size of jvm，ready to observe for a while。
