### ISSUE TITLE
Lower log level of "[:array:] The connection observed an error"

### ISSUE THREAD

**Issue by intarabang** [reactor/reactor-netty#582]
The remote service closing the connection can happen for various reasons that we cannot do much about. Should we consider lowering the log level of the above to possibly a WARN, especially in the case of errors:
* reactor.netty.http.client.HttpClientOperations$PrematureCloseException: Connection prematurely closed BEFORE response
* javax.net.ssl.SSLException: SSLEngine closed already

On our side, there's nothing to do except implement retries in calling the remote service and notify if we've exhausted them.

### Reactor Netty version
0.8.4.RELEASE

**Comment by violetagg** [comment]
@intarabang Can you try 0.8.5.BUILD-SNAPSHOT and see whether you still will experience these exceptions?
