### ISSUE TITLE
ChannelOperations#sendObject(object) leaks for long-lived connections

### ISSUE THREAD

**Issue by tkp1n** [reactor/reactor-netty#585]
With the introduction of `ReactorNetty.safeRelease` in 0935bfc1fbcdd2068d111d77f897f06a0be3720c a potential memory leak was introduced to `ChannelOperations`. If a connection is kept open for an extended period of time, the subscriptions to `onTerminate()` add up and can never be collected until the connection terminates.

https://github.com/reactor/reactor-netty/blob/799d5a26f85935404e231471cce06383cf630b6f/src/main/java/reactor/netty/channel/ChannelOperations.java#L235-L240

This issue can be avoided if `ChannelOperations#sendObject(Publisher<? extends ByteBuf>)` is used instead of `ChannelOperations#sendObject(object)`.

If this is by design, the documentation should reflect this potentially unwanted behavior. Otherwise it might be better if the following line is dropped:

https://github.com/reactor/reactor-netty/blob/799d5a26f85935404e231471cce06383cf630b6f/src/main/java/reactor/netty/channel/ChannelOperations.java#L237

**Comment by violetagg** [comment]
@tkp1n Do you experience a real memory leak? This `ReactorNetty.safeRelease` will be invoked only in use cases like `Content-Length: 0` (the message will not be sent) or we have some errors while trying to send the message (but in this case the connection most probably will be closed) (see #554). Netty always releases the object when it is outbound message (https://netty.io/wiki/reference-counted-objects.html#outbound-messages)
