### ISSUE TITLE
Flux<String> decoded into 1 string

### ISSUE THREAD

**Issue by urferr** [reactor/reactor-netty#589]
### Expected behavior
28.01.2019 17:39:23.376 DEBUG [reactor-http-nio-4] org.springframework.web.HttpLogging:142 - [e84fb85] Decoded [[Hello World1!, Hello World2!, Hello World3!, Hello World4!, Hello World5!]]

### Actual behavior
28.01.2019 17:39:23.412 DEBUG [reactor-http-nio-4] org.springframework.web.HttpLogging:142 - [3804a9a8] Decoded "Hello World1!Hello World2!Hello World3!Hello World4!Hello World5!"

### Steps to reproduce
create a server message reurning a Flux<String> with several strings inside, 
i.e. 
return Flux.just("Hello World1!", "Hello World2!", "Hello World3!", "Hello World4!", "Hello World5!");

create a consumer and print the content of the Flux
i.e.
myFlux.subscribe(theString -> System.out.println(" - " + theString));

=> only one element is printed containing all the strings concatenated
i.e.
 - Hello World1!Hello World2!Hello World3!Hello World4!Hello World5!
instead of
 - Hello World1!
 - Hello World2!
 - Hello World3!
 - Hello World4!
 - Hello World5!

### Reactor Netty version
0.8.4.RELEASE

### JVM version (e.g. `java -version`)
11.0.2

### OS version (e.g. `uname -a`)
Windows 10 Pro, Version 1709, OSbuild 16299.904

**Comment by violetagg** [comment]
@urferr 

> create a consumer and print the content of the Flux

Is the consumer a client, I mean do you send the message over network?

**Comment by violetagg** [comment]
@urferr You cannot control the packages over the wire. It depends on when the network buffers will be filled and flushed (by default the `SO_SNDBUF` is 1MB - https://github.com/reactor/reactor-netty/blob/master/src/main/java/reactor/netty/tcp/TcpServerBind.java#L131).
However if you want, you can apply a decoder on the client side such as 
https://netty.io/4.1/api/io/netty/handler/codec/DelimiterBasedFrameDecoder.html
https://netty.io/4.1/api/io/netty/handler/codec/LineBasedFrameDecoder.html

**Comment by urferr** [comment]
i tink we do not understand each other. My problem is, that i pass a Flux which has been created based on 5 string inside and when it arrives on the client it contains only one string which is the concatenation of the initial 5 strings. Why should this be a problem of buffer size? And also it works fine if i use a Flux<Message> where Message is a class just containing a String attribute. If i put 5 messages into the Flux onto the server side i get 5 messages on the client side. So the problems only hapens with Flux<String>

creation of the Flux on the server side:
Flux.just("Hello World1!", "Hello World2!", "Hello World3!", "Hello World4!", "Hello World5!")

**Comment by violetagg** [comment]
@urferr You can enable the `wire logger` so that you can see how the packages are transported over the wire and how they are received on the client side.

Add the component below to your application and enable logging `logging.level.reactor.netty=debug`

```
@Component
public class MyNettyWebServerCustomizer
        implements WebServerFactoryCustomizer<NettyReactiveWebServerFactory> {
    @Override
    public void customize(NettyReactiveWebServerFactory factory) {
        factory.addServerCustomizers(httpServer -> httpServer.wiretap(true));
    }
}
```

**Comment by rstoyanchev** [comment]
Indeed, when text is received as raw bytes, [StringDecoder](https://github.com/spring-projects/spring-framework/blob/master/spring-core/src/main/java/org/springframework/core/codec/StringDecoder.java) aggregates until it encounters a delimiter (`\r\n` or `\n` by default). There is no other way to avoid split character issues with decoding.

**Comment by urferr** [comment]
It seems not only to be a problem in the StringDecoder of spring, also if i call the server directly with curl or from chrome browser i get the same result, the different strings are always concatenated into one

**Comment by rstoyanchev** [comment]
Again, it is not a "problem" :)

**Comment by karlnicholas** [comment]
It certainly seems to be a problem to me. All this webflux is supposed to make my life easier but here is cannot simply define a Flux of Strings to be processed. Seems lacking.

**Comment by rstoyanchev** [comment]
@karlnicholas thanks for your comment but I can't respond to your similar and yet slightly different use case. Typically it's not helpful to comment on closed issues because some things may have changed, and each case needs to be considered in more detail unless it is 100% identical which is usually not that easy to confirm unless you are the original reporter.

**Comment by kylooh** [comment]
I found the simplest way to solve this problem, is translate `Flux<String>` to `Flux<Any>`, then it will be treated as Json Array

**Comment by selvaebi** [comment]
if i have a QueryMapping for graphql it works perfectly fine , if I switch to @Getmapping it is concatenating into single string.
