### ISSUE TITLE
Lower log level of connection errors from ERROR

### ISSUE THREAD

**Issue by nidhi7** [reactor/reactor-netty#590]
This is a request to lower the below referenced log statement from error to info or warn. We have a retry logic in case of such errors and want the error to be logged only once after the last retry and not multiple times as it affects the error alarms that we get.

 https://github.com/reactor/reactor-netty/blob/883c138e76dbfcdbb2e5a2c789a3be26776b5c38/src/main/java/reactor/netty/http/client/HttpClientConnect.java#L388

### Reactor netty version: 
0.8.4

**Comment by violetagg** [comment]
duplicate #582
