### ISSUE TITLE
Document encoding/decoding API and Spring 5 codecs

### ISSUE THREAD

**Issue by gembin** [reactor/reactor-netty#6]
```xml
<dependency>
        <groupId>io.projectreactor.ipc</groupId>
	<artifactId>reactor-netty</artifactId>
	<version>0.5.2.RELEASE</version>
</dependency>
```

```java
WARNING: An exception 'java.lang.NoClassDefFoundError: reactor/ipc/codec/Codec' [enable DEBUG level for full stacktrace] was thrown by a user handler's exceptionCaught() method while handling the following exception:
java.lang.NoClassDefFoundError: reactor/ipc/codec/Codec
	at reactive.net.Netty.lambda$0(Netty.java:26)
	at reactor.ipc.netty.common.NettyChannelHandler.channelActive(NettyChannelHandler.java:104)
```

**Comment by tokuhirom** [comment]
@smaldini I guess this issue was fixed on github master.
Could you release new version?

**Comment by gembin** [comment]
@smaldini  ping

**Comment by smaldini** [comment]
0.6 won't use anymore codecs since Spring 5 will provide its own codecs and we only expose netty ByteBuf directly (no more reactor proprietary buffer abstraction). To fill some gap such as length-frame decoding we directly support Netty own mature codecs and are improving the API around this for 0.6.

**Comment by smaldini** [comment]
Which codec are you needing that is not part of netty codec collections, you can add a decoder via ```NettyContext#addDecoder(ChannelHandler)``` and ```NettyContext#addHandler(ChannelHandler)```, e.g.
https://github.com/reactor/reactor-netty/blob/master/src/test/java/reactor/ipc/netty/http/HttpServerTests.java#L113

**Comment by violetagg** [comment]
Adding Netty encoders/decoders is documented in the reference documentation.
https://projectreactor.io/docs/netty/release/reference/index.html
For Spring related encoders/decoders consult with Spring documentation
https://docs.spring.io/spring/docs/current/spring-framework-reference/web-reactive.html#spring-webflux
Closing this issue.
