### ISSUE TITLE
Improve handling for pooled connection when server responds with "Connection: close" 

### ISSUE THREAD

**Issue by rstoyanchev** [reactor/reactor-netty#632]
This is based on https://github.com/spring-projects/spring-framework/issues/22464.

Using `WebClient` with Reactor Netty and making two inter-dependent requests to https://nominatim.openstreetmap.org, the second request results in:

```
PrematureCloseException: Connection prematurely closed BEFORE response
```

On the first request the server returns:
```
Upgrade: h2
Connection: Upgrade, close
```

The problem goes away if connection pooling is not used with `HttpClient.newConnection()`.

If a server indicates it will close the connection via `"Connection: Close"` and the client is using connection pooling, perhaps the connection should be removed from the pool, and a warning or error message logged? Or perhaps the connection can be marked and closed if an attempt is made to use it again in order to raise a more helpful error?

**Comment by violetagg** [comment]
While we are waiting (https://github.com/netty/netty/pull/8924) for Netty 4.1.35.Final, we will provide a workaround in Reactor Netty

**Comment by violetagg** [comment]
Workaround is removed and Netty updated to 4.1.35.Final
