### ISSUE TITLE
Memory Leak using WebClient

### ISSUE THREAD

**Issue by joshfix** [reactor/reactor-netty#633]
I am running Spring Boot 2.1.3 (reactory-netty 0.8.5).  I have an app that grabs a file from AWS containing nearly 1.5 million lines and does some processing.  Each line represents a single metadata record.  For each record, I need make a GET call to a remote service to see if that record has already been processed, another GET call to retrieve an HTML page for that record that contains links to even more detailed metadata, another GET call to one of those links, and finally, a POST to another API to create a final record in another service.  The code declares 3 different `WebClient`s in 3 different classes.

Shortly after execution, the app will start detecting leaks:

> Recent access records: 
> #1:
> 	io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:286)
> 	io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253)
> 	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
> 	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
> 	io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
> 	io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1436)
> 	io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1203)
> 	io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1247)
> 	io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502)
> 	io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441)
> 	io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278)
> 	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
> 	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
> 	io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
> 	io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408)
> 	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
> 	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
> 	io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930)
> 	io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
> 	io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:677)
> 	io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:612)
> 	io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:529)
> 	io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:491)
> 	io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
> 	java.lang.Thread.run(Thread.java:748)
> #2:
> 	io.netty.buffer.AdvancedLeakAwareByteBuf.forEachByte(AdvancedLeakAwareByteBuf.java:670)
> 	io.netty.handler.codec.http.HttpObjectDecoder$HeaderParser.parse(HttpObjectDecoder.java:801)
> 	io.netty.handler.codec.http.HttpObjectDecoder.readHeaders(HttpObjectDecoder.java:601)
> 	io.netty.handler.codec.http.HttpObjectDecoder.decode(HttpObjectDecoder.java:227)
> 	io.netty.handler.codec.http.HttpClientCodec$Decoder.decode(HttpClientCodec.java:202)
> 	io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502)
> 	io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441)
> 	io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278)
> 	io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253)
> 	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
> 	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
> 	io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
> 	io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1436)
> 	io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1203)
> 	io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1247)
> 	io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502)
> 	io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441)
> 	io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278)
> 	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
> 	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
> 	io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
> 	io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408)
> 	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
> 	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
> 	io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930)
> 	io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
> 	io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:677)
> 	io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:612)
> 	io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:529)
> 	io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:491)
> 	io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
> 	java.lang.Thread.run(Thread.java:748)
> #3:
> 	Hint: 'reactor.left.httpCodec' will handle the message from this point.
> 	io.netty.channel.DefaultChannelPipeline.touch(DefaultChannelPipeline.java:116)
> 	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
> 	io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
> 	io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1436)
> 	io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1203)
> 	io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1247)
> 	io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502)
> 	io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441)
> 	io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278)
> 	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
> 	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
> 	io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
> 	io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408)
> 	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
> 	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
> 	io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930)
> 	io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
> 	io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:677)
> 	io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:612)
> 	io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:529)
> 	io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:491)
> 	io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
> 	java.lang.Thread.run(Thread.java:748)
> #4:
> 	io.netty.buffer.AdvancedLeakAwareByteBuf.internalNioBuffer(AdvancedLeakAwareByteBuf.java:736)
> 	io.netty.handler.ssl.SslHandler.toByteBuffer(SslHandler.java:1446)
> 	io.netty.handler.ssl.SslHandler.access$300(SslHandler.java:166)
> 	io.netty.handler.ssl.SslHandler$SslEngineType$3.unwrap(SslHandler.java:296)
> 	io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1301)
> 	io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1203)
> 	io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1247)
> 	io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502)
> 	io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441)
> 	io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278)
> 	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
> 	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
> 	io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
> 	io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408)
> 	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
> 	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
> 	io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930)
> 	io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
> 	io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:677)
> 	io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:612)
> 	io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:529)
> 	io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:491)
> 	io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
> 	java.lang.Thread.run(Thread.java:748)
> #5:
> 	io.netty.buffer.AdvancedLeakAwareByteBuf.nioBufferCount(AdvancedLeakAwareByteBuf.java:706)
> 	io.netty.handler.ssl.SslHandler.toByteBuffer(SslHandler.java:1446)
> 	io.netty.handler.ssl.SslHandler.access$300(SslHandler.java:166)
> 	io.netty.handler.ssl.SslHandler$SslEngineType$3.unwrap(SslHandler.java:296)
> 	io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1301)
> 	io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1203)
> 	io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1247)
> 	io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502)
> 	io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441)
> 	io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278)
> 	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
> 	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
> 	io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
> 	io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408)
> 	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
> 	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
> 	io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930)
> 	io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
> 	io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:677)
> 	io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:612)
> 	io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:529)
> 	io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:491)
> 	io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
> 	java.lang.Thread.run(Thread.java:748)
> Created at:
> 	io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:339)
> 	io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:185)
> 	io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:176)
> 	io.netty.buffer.AbstractByteBufAllocator.buffer(AbstractByteBufAllocator.java:113)
> 	io.netty.handler.ssl.SslHandler.allocate(SslHandler.java:1914)
> 	io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1296)
> 	io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1203)
> 	io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1247)
> 	io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502)
> 	io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441)
> 	io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278)
> 	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
> 	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
> 	io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
> 	io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408)
> 	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
> 	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
> 	io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930)
> 	io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
> 	io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:677)
> 	io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:612)
> 	io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:529)
> 	io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:491)
> 	io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
> 	java.lang.Thread.run(Thread.java:748)
> 

### Steps to reproduce
I have created a sample application that will reproduce the issue.  It's a bit ugly as I've chopped up my real app to get it down to a standalone version without other dependencies.  It is available here:

https://github.com/joshfix/landsat-harvester

### Reactor Netty version
0.8.5

### JVM version (e.g. `java -version`)
java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)

### OS version (e.g. `uname -a`)
OS X
Darwin Joshuas-MBP 18.2.0 Darwin Kernel Version 18.2.0: Thu Dec 20 20:46:53 PST 2018; root:xnu-4903.241.1~1/RELEASE_X86_64 x86_64

**Comment by joshfix** [comment]
Forgot to mention, if I replace all WebClient instances with RestTemplate calls, the problem goes away.  But if I leave in any one single WebClient call, the issue resurfaces.  I have multiple other apps using WebClient and have never experienced this issue before.

**Comment by dave-fl** [comment]
The leak looks like its in your exchange call.

https://github.com/joshfix/landsat-harvester/blob/master/src/main/java/com/boundlessgeo/stac/harvester/v2/StacClient.java#L96

You must consume the response.

**Comment by violetagg** [comment]
@joshfix I agree with @dave-fl findings. You just consume the status code and do not dispose/consume the response body

**Comment by violetagg** [comment]
Closing this. @joshfix please fix your example and if you still see memory leaks we will reopen this issue.
