### ISSUE TITLE
Http/2 Client Support

### ISSUE THREAD

**Issue by enricosecondulfo** [reactor/reactor-netty#639]
Are there any examples of connection to a server with http/2 support?

Thanks

**Comment by violetagg** [comment]
@enricosecondulfo There is not support in 0.8.x

**Comment by violetagg** [comment]
#104
#391
#399

**Comment by MilgoTest** [comment]
Any plans to implement HTTP/2 support on client side?

**Comment by patpatpat123** [comment]
Hello,

Cheering for you here. Any update?
Just saying, but our team refactored 20+ micro services from Webflux http to Webflux http2 + https with ssl.

Then, we started to refactor our gateway service, which is in front of our 20+ micro services, to realize http2 is not possible :'D

Thank you!

**Comment by Jovons** [comment]
I think H2 is coming soon. saw some code there, just all commented. Really wish it is not H2 only, it should support H2C as well! Not all H2 connections are in non-trust-worthy network. For micro-services it is import for us to debug H2C messages between services.

**Comment by AugustoSansoni** [comment]
Do you have any plan about the date next version of reactor netty will be published with this enhancement ?

**Comment by YeTingGe** [comment]
When does reactor-netty going to support H2C client ?
For us, as we will have a proxy(HA proxy/Nginx) running between our application and outside service, we're really hoping use same thing for both server(webflux + reactory netty) and client(reactor netty web client).
At this time, we have to use vert.x netty web client to support h2c

**Comment by umutuzgur** [comment]
This would be great to have. We are also waiting for this

**Comment by phan-pivotal** [comment]
Waiting for this, too.

**Comment by fcnorman** [comment]
Would really love to see this.

**Comment by spencergibb** [comment]
Gateway needs this as well

**Comment by anilgursel** [comment]
@violetagg When is 1.0.0.M1 targeted for? Is the HTTP/2 work is already in progress? Wondering if we can help to speed it up.

**Comment by violetagg** [comment]
@anilgursel I'll start working on HTTP/2 for HTTP client this week.

**Comment by anilgursel** [comment]
That's great!  We will try once available.

**Comment by cj848** [comment]
I am curious as to how this is progressing. I am looking forward to resolving this issue quickly.

**Comment by violetagg** [comment]
Hopefully this week I'll prepare a draft PR for this enhancement.
