### ISSUE TITLE
Connections should be acquired on send, not on subscribe

### ISSUE THREAD

**Issue by nebhale** [reactor/reactor-netty#64]
Currently, connections are acquired from the pool (or opened in non-pooling scenarios) on subscription.  This means that the connection is either unusable by other flows or consuming resources during a period of time that it is not in use.  I'd like to see connections acquired on send instead of subscribe.

It may seem like this distinction is quite small in practical terms, but the Cloud Foundry Java Client has a number of extended flows, nested flows, etc. where a connection is acquired on subscription, but continuing up the flow, another connection is also acquired for a different request.  This means that the first (lower) connection sits idle, but unusable until the first connection has returned.  Worse even than that though, is in small pool sizes (say one connection), there is a deadlock as the second (higher) connection attempts to acquire a connection currently reserved by the first (lower) and it will never be able to do so.

I believe that it's a reasonable (if slow) requirement that any flow written should be able to use a one-connection pool successfully.

**Comment by nebhale** [comment]
This is probably related to an issue we just diagnosed where errors generated on the outbound never closed the connection that had been opened previously.  Changing when the connection is opened will probably help with this issue.

**Comment by smaldini** [comment]
Closing for now since we have a new lifecyle API, we might need to re-open in more details but given the API refactor to avoid nesting, it might make less sense. We could still provide an explicit Client API for this tho (we currently do with HttpClient#headers(Consumer<HttpHeaders>))
