### ISSUE TITLE
onComplete of All Data Received Signal Available Without Receive

### ISSUE THREAD

**Issue by nebhale** [reactor/reactor-netty#65]
Given the code

```
AtomicLong startTimeHolder = new AtomicLong();

httpClient.get(uri)
            .log("stream.beforeTiming")
            .doOnSubscribe(s -> startTimeHolder.set(System.currentTimeMillis()))
            .doFinally(signal -> System.out.println(System.currentTimeMillis() - startTimeHolder.get()))
            .log("stream.afterTiming")
```

notification of all "completion-style" events (`doOnSuccess()`, `doOnTerminate()`, `doAfterTerminate()`, and `doFinally()`) happen before the last of the data is passed to an subscriber to `.receive()`.  You can see an example of this [here](https://gist.github.com/nebhale/96fad644bcb6903837b5ced80bd037d5#file-complete-too-early-log-L402) where `onComplete()` is signaled followed by quite a lot more data.

Now, I'm not sure that this is strictly wrong.  The `Mono<HttpClient>` is clearly done sending items, so it makes a certain kind of sense.  However, this makes it exceeding difficult for any party other than the final subscriber of the _actual_ data to get this information.

There should be a way for the caller of the `HttpClient` operations (`.get()` et al) to be signaled when all data has been received.

**Comment by simonbasle** [comment]
@nebhale do you have a more specific use-case? As you said, the `Mono<HttpClientResponse>` does indeed complete based on the reception of the response headers, aka the _request_ has been done.

There are several caveats that make your feature request impractical. Most notably, waiting for the `receiveContent()` to complete before emitting the response would make the body of the response unusable: 
 - the `FluxReceiver` will `release()` http content as it is emitted
 - it only allows one subscription

So the idiomatic way of working with the response would be to `flatMap` to `receiveContent()` and deal with the content (before it is released).

That said, if you're only interested in the headers or status code, but you only want to evaluate those once the response has completed, you could now use `delayUntil(HttpClientResponse::receiveContent)`.

How does that sound?

**Comment by simonbasle** [comment]
🤔 for the purpose of this kind of measurements, closer to the wire, I wonder if a workaround could be to add a special netty handler to the pipeline that does the timings. Did you explore that solution by any chance?

**Comment by nebhale** [comment]
I did not because I'm a `reactor-netty` user 😉. It means that I have to drop to a non-blocking, but *non-reactive* API which seems onerous for a `reactor-netty` user.  I chose to use a higher-level API in part because I didn't want to write to Netty's API.  I find Reactor so much better and easier to use, that something as simple as intercepting first and last byte shouldn't require abandoning it.

**Comment by violetagg** [comment]
@nebhale @simonbasle I believe this can be achieved with the lifecycle callbacks.
https://projectreactor.io/docs/netty/snapshot/reference/index.html#_lifecycle_callbacks_4
