### ISSUE TITLE
Spring stomp client does not always reconnect to broker if using SSL

### ISSUE THREAD

**Issue by krm1312** [reactor/reactor-netty#653]
It appears there may be a race in connection pooling logic when an SSL endpoint does not perform any handshake.  This causes spring's stomp client to fail to reconnect under certain conditions.

Details (logs, etc.): https://github.com/spring-projects/spring-framework/issues/22080#issuecomment-474952213

We have:

app -> haproxy -> rabbitmq.

If rabbitmq goes down (all backends), haproxy will still accept the TCP connection, but, quickly close the connection without doing any TLS handshake.

In debugging, it was observed that this block was being hit, and after that no reconnection attempts are made:

https://github.com/reactor/reactor-netty/blob/0.8.x/src/main/java/reactor/netty/resources/PooledConnectionProvider.java#L624

After removing that block https://github.com/krm1312/reactor-netty/commit/04ff03f3478bfdf871822fe3454f2ce9de9b19f5 I have been unable to reproduce the issue.  Not sure of all the implications.

spring boot 2.1.3
spring 5.1.5
reactor-netty 2.8.5
netty 4.1.34
Java 8

**Comment by violetagg** [comment]
Try the latest 0.8.7.BUILD-SNAPSHOT
