### ISSUE TITLE
Expose read-only version of HttpServerOptions in HttpServer

### ISSUE THREAD

**Issue by mbhave** [reactor/reactor-netty#66]
Currently, when the server startup fails, we don't have access to the port that was used to start the server. We would like to log the failure along with the port (in case of a BindException). 

/cc @bclozel

**Comment by rstoyanchev** [comment]
There is a way to obtain the port (see #58).

**Comment by bclozel** [comment]
@rstoyanchev In that case, we never get back the context since the `BindException` is thrown before the `Mono` is completed (we get an error signal instead).
