### ISSUE TITLE
disconnecting state is not called on ConnectionObserver of TcpServer

### ISSUE THREAD

**Issue by chang-chao** [reactor/reactor-netty#688]
Only connection status of connected and configured is called on ConnectionObserver of TcpServer, not disconnecting.

while the [Javadoc](https://github.com/reactor/reactor-netty/blob/5a59344236ea6a04383766693d61fc15d23a58e3/src/main/java/reactor/netty/tcp/TcpServer.java#L354) of `TcpServer.observe` says it should be called after disconnected.
>called on or after Channel has been connected and after it has been disconnected.

[Here](https://github.com/chang-chao/reactor-netty-samples/blob/ff4db82398200206798c48ff9e9c73e437e33e67/src/main/java/me/changchao/reactor_netty_samples/tcp/server/EchoServer.java#L22) is the simple program that can reproduce this issue.
When the simple EchoServer is started, we can test it by a  `echo text | nc localhost 9999`.

**Comment by violetagg** [comment]
@chang-chao Your example is not quite valid:
- You do not have shutdown hook (see below the shutdown hook)
- You keep the channel opened till the end (see #495 and the code below how you can add a channel group in order to close such channel)

```
public class EchoServer {
	final static Logger logger = LoggerFactory.getLogger(EchoServer.class);

	public static void main(String[] args) {
		ChannelGroup group = new DefaultChannelGroup(new DefaultEventExecutor());

		int listenPort = 9999;

		DisposableServer server = TcpServer.create().port(listenPort).doOnConnection(connection -> {
			// only when client is connected, this is OK
			group.add(connection.channel());
			logger.debug("connection:" + connection);
		}).wiretap(true).observe((connection, newState) -> {
			// only called when connection is connected and configured, but not disconnected
			// this is a BUG ?
			logger.debug("connection:" + connection + ", newState=" + newState);
		}).handle(
				(inbound, outbound) -> outbound.options(NettyPipeline.SendOptions::flushOnEach)
						.sendString(inbound.receive().asString()).neverComplete())
				.bindNow();

		Runtime.getRuntime()
				.addShutdownHook(new Thread(() -> {
					FutureMono.from(group.close()).block();
					server.disposeNow();
				}));

		server.onDispose().block();
	}

}
```

However there is still one issue with `disconnecting` event and I'm going to provide a PR.

Regards,
Violeta

**Comment by chang-chao** [comment]
@violetagg , thanks for your feedback, I will update my program according to your advice.

**Comment by violetagg** [comment]
> @violetagg , thanks for your feedback, I will update my program according to your advice.

You need to add the channel to the group when `doOnConnection`

**Comment by chang-chao** [comment]
@violetagg thanks for reminding , it was added in a later commit.
