### ISSUE TITLE
How to time HTTP client events like SSL handshake

### ISSUE THREAD

**Issue by crankydillo** [reactor/reactor-netty#693]
We need to time the following events when using reactor-netty:

- Connection establishment
- DNS lookup
- SSL handshake
- Request send
- Response receive

To see if I could do this, I wrote [this app](https://github.com/crankydillo/reactor-netty/blob/727212895860aa53770f56076406cd3dbf684921/src/main/java/reactor/netty/http/client/App.java#L35) in order to play with various hook points. If a few bugs are fixed, I believe the subscriber context will allow me to time the request/response items; however, I don't have an answer for the others.

Tips on how to achieve this or on how to add this functionality are greatly appreciated!

This was originally posted [here](https://stackoverflow.com/questions/55314645/how-to-time-http-client-events-like-ssl-handshake).

**Comment by violetagg** [comment]
we are working on metrics do you think this will serve your use case
#790

**Comment by crankydillo** [comment]
Hi @violetagg, short story: my team does hope this will serve our needs.  

Long story:
We are actually logging some things (such as HTTP request send) using a transactional logging API.  I don't think micrometer will help with that, but we are pretty sure we have most of those cases covered via existing hook points.  The only one we couldn't get working is connection establishment, and we may use metrics to log those times.  If we do, your micrometer work has a large chance of helping us.

Thanks for the update!

**Comment by violetagg** [comment]
Currently as part of the metrics we have only connect time.
But as a result of switching to Reactor Pool, we will extend the current metrics with more information about the connection pool -> https://github.com/reactor/reactor-pool/blob/master/src/main/java/reactor/pool/PoolMetricsRecorder.java.

**Comment by crankydillo** [comment]
Cool.  I'm going to close this for now since we have a lot of what we need, and may be able to leverage your micrometer work for the rest.  If we have a tangible need, I'll create a new issue.  Thanks again!
