### ISSUE TITLE
Issue #508 has arisen again in the v0.8.5.RELEASE

### ISSUE THREAD

**Issue by xyrc** [reactor/reactor-netty#696]
[#508](https://github.com/reactor/reactor-netty/issues/508)

![image](https://user-images.githubusercontent.com/29597377/55272598-d8414000-52f9-11e9-8006-8803d37058b7.png)

**Comment by xyrc** [comment]
in v0.8.3.RELEASE, the code like this:
`if (!channel.isActive()) {
				Operators.error(s, new AbortedException("Cannot publish the content" +
						dataStream + ", the connection has been closed"));
				return;
			}`

**Comment by xyrc** [comment]
pr [#509](https://github.com/reactor/reactor-netty/pull/509), the code like this:
```java
if (!channel.isActive()) {
    Operators.complete(s);
    return;
}
```

**Comment by violetagg** [comment]
@xyrc Can you give us some reproducible example?

**Comment by xyrc** [comment]
Use this Test?
```java
        @Test
	public void testIssue508() {
		NettyContext server =
				HttpServer.create(ops -> ops.port(0))
				          .newHandler((req, res) -> res.header("Content-Length", "0")
				                                       .sendString(Flux.just("1", "2", "3")))
				          .block(Duration.ofSeconds(30));
		assertThat(server).isNotNull();

		String response =
				HttpClient.create(ops -> ops.port(server.address()
				                                        .getPort()))
				          .get("/", req -> req.addHeader("Connection", "close"))
				          .flatMap(res -> res.receive()
				                             .aggregate()
				                             .asString()
				                             .switchIfEmpty(Mono.just("Empty")))
				          .block(Duration.ofSeconds(30));

		assertThat(response).isEqualTo("Empty");
		server.dispose();
	}
```
Refer [HttpServerTests.java](https://github.com/reactor/reactor-netty/blob/fc6099b456cd4c8bce401a6a81a8b255699f277d/src/test/java/reactor/ipc/netty/http/server/HttpServerTests.java)

**Comment by xyrc** [comment]
spring-cloud-gateway version: 2.1.0
reactor-netty version: 0.8.5
```log
2019-03-30 08:34:56,835:ERROR reactor-http-epoll-4 (Loggers.java:319) - Operator called default onErrorDropped
	io.netty.channel.ChannelPipelineException: reactor.netty.channel.ChannelOperationsHandler.handlerRemoved() has thrown an exception.
	Caused by: reactor.core.Exceptions$BubblingException: reactor.netty.channel.AbortedException: Connection has been closed
	Caused by: reactor.netty.channel.AbortedException: Connection has been closed
	reactor.netty.channel.AbortedException: Connection has been closed
```

**Comment by violetagg** [comment]
@xyrc The fix was enhanced with #554 so that we propagate the cancelation to the Publishers. I do not see the problem with the current code

**Comment by violetagg** [comment]
> spring-cloud-gateway version: 2.1.0
> reactor-netty version: 0.8.5
> 
> ```
> 2019-03-30 08:34:56,835:ERROR reactor-http-epoll-4 (Loggers.java:319) - Operator called default onErrorDropped
> 	io.netty.channel.ChannelPipelineException: reactor.netty.channel.ChannelOperationsHandler.handlerRemoved() has thrown an exception.
> 	Caused by: reactor.core.Exceptions$BubblingException: reactor.netty.channel.AbortedException: Connection has been closed
> 	Caused by: reactor.netty.channel.AbortedException: Connection has been closed
> 	reactor.netty.channel.AbortedException: Connection has been closed
> ```

Ok this must be something else, it seems some error appeared? `Operator called default onErrorDropped`

**Comment by xyrc** [comment]
Okay, I'll check again. thank you!
