### ISSUE TITLE
Default 404 handler doesn't send content-length or transfer-encoding header.

### ISSUE THREAD

**Issue by tokuhirom** [reactor/reactor-netty#7]
Default implementation of HttpClient's 404 handler is following.

```java
						request.delegate()
						       .writeAndFlush(new DefaultHttpResponse(HttpVersion.HTTP_1_1,
								       HttpResponseStatus.NOT_FOUND));
```

This response doesn't include `Content-Length` header and `Transfer-Encoding` header. As a result, HTTP client can't determine end of the response. HTTP/1.1 server must return Content-Length or Transfer-Encoding(iirc).

Curl's verbose output is here:
```
$ curl -vvv http://localhost:8011/jkjk
*   Trying ::1...
* connect to ::1 port 8011 failed: Connection refused
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8011 (#0)
> GET /jkjk HTTP/1.1
> Host: localhost:8011
> User-Agent: curl/7.49.1
> Accept: */*
> 
< HTTP/1.1 404 Not Found
* no chunk, no close, no size. Assume close to signal end
< 
```

**Comment by tokuhirom** [comment]
Note: 500 handler uses `ChannelFutureListener.CLOSE`.

```
				request.delegate()
				       .writeAndFlush(new DefaultHttpResponse(HttpVersion.HTTP_1_1, HttpResponseStatus.INTERNAL_SERVER_ERROR))
						.addListener(ChannelFutureListener.CLOSE);
```

**Comment by smaldini** [comment]
We are currently heavily working on 0.6 to support way more low-level stuff including connection-pooling and server keep-alive. We expect to see 0.6 out around the next month since these latest changes are critical to evaluate the 1.0 GA which is planned to be aligned with Spring 5 GA

**Comment by smaldini** [comment]
Fixed in latest master
