### ISSUE TITLE
Monitor Http Client 

### ISSUE THREAD

**Issue by lubinson** [reactor/reactor-netty#721]
Hi,

I am using reactor http client from spring webclient. 
We want to monitor the http client queue to know the current busy status. 
So does reactor http client has this queue? and even we can set the size during http client initialization?
Or is there any other proposal to monitor similar stats. 

Thanks a lot.

**Comment by violetagg** [comment]
> http client queue
@lubinson What queue exactly do you want to monitor? (connections, requests, ...?)

**Comment by lubinson** [comment]
@violetagg  

The requests queue. Thanks.

**Comment by violetagg** [comment]
We are working on metrics. Do you think this will serve your use case?
#790

**Comment by violetagg** [comment]
Metrics support based on micrometer #790
