### ISSUE TITLE
How to disable Expect: 100-continue default processing by underlying netty

### ISSUE THREAD

**Issue by hmble2** [reactor/reactor-netty#722]
I have a proxy server that forwards requests to destination services. My server app is built using spring reactive + reactor-netty. I expect my proxy server to not handle Expect http request header ( so that target app can handle it). I have seen that proxy server is responding client with HTTP 100 and still forwarding Expect header to target app. This results in client getting two HTTP 100 (one from proxy and other from target app). I want that proxy server should not respond HTTP with 100 and let target app do a complete Expect processing ( the way GoRouter handles it).

How do I disable processing of Expect header with spring-reactive?

**Comment by timothymathison** [comment]
Any updates on this? We're encountering this issue as well

**Comment by violetagg** [comment]
@timothymathison We will try to address this for 0.9.6.RELEASE

**Comment by violetagg** [comment]
@hmble2 @timothymathison

After looking at that issue in details I don't think an enhancement is needed in Reactor Netty.

Reactor Netty will send automatically `100 Continue` ONLY when the IO handler asks for the incoming body and there was no response with `100 Continue` before that operation.

https://github.com/reactor/reactor-netty/blob/89ae010a84e25925952e2f82ece7fae8c015742c/src/main/java/reactor/netty/http/server/HttpServerOperations.java#L292-L301

I'll update the gateway issue https://github.com/spring-cloud/spring-cloud-gateway/issues/1337
