### ISSUE TITLE
Reuse Connection Pool with proxied connections

### ISSUE THREAD

**Issue by shrykull** [reactor/reactor-netty#729]
### Following link https://pivotal.io/security should be used to report security related issues
Not security relevant

### [Gitter](https://gitter.im/reactor/reactor) should be used for questions and discussions
Been there, done that

### Expected behavior
Connection Pool is re-used with a proxied tcpclient 

### Actual behavior
Memory leakage with potentially infinitely growing `reactor.netty.resources.PooledConnectionProvider#channelPools` if nonProxyHosts regex is set for a proxied TcpClient with reactor-netty.

### Steps to reproduce
- create a httpClient which performs 2 or more requests on any uri and is proxied with any regex configured for nonProxyHosts
- enable debug logging
- watch out for `"Creating new client pool [{}] for {}"` logged by `reactor.netty.resources.PooledConnectionProvider#log`: the second connection with the same client will create another pool because the existing one is not recognized

### Related Issues (but those did not completely solve this): 
https://github.com/reactor/reactor-netty/issues/566
https://github.com/reactor/reactor-netty/issues/567

### Reactor Netty version
Confirmed with 0.8.5.RELEASE and 0.8.6.RELEASE

### JVM version (e.g. `java -version`)
Confirmed with Adopt 8, 11

### OS version (e.g. `uname -a`)
Win 10

**Comment by shrykull** [comment]
i did a PR for this: https://github.com/reactor/reactor-netty/pull/728

**Comment by violetagg** [comment]
Thanks for the PR
