### ISSUE TITLE
NettyOutbound.sendObject(Publisher) stops sending messages after a few messages with version 0.9

### ISSUE THREAD

**Issue by mp911de** [reactor/reactor-netty#735]
### Expected behavior

 `NettyOutbound.sendObject(Publisher)` should send (consume) messages from the given `Publisher`

### Actual behavior

After switching from version 0.8.6 to 0.9.0.BUILD-SNAPSHOT, `NettyOutbound.sendObject(Publisher)` no longer seems to consume messages. Messages are emitted (visible in `doOnNext()`) but no longer mapped/consumed (by `concatMap`).

### Steps to reproduce

See R2DBC MS-SQL:

```
EmitterProcessor<ClientMessage> requestProcessor = EmitterProcessor.create(false)

// feed messages into requestProcessor

requestProcessor.as(it -> {
            .concatMap(
                message -> { 
                    Publisher<TdsFragment> encoded = …;
                    connection.outbound().sendObject(encoded);
            .subscribe();
```

After a few processed messages, no further messages get written. We have a `TdsEncoder` handler that does message encoding from `TdsFragment` to `ByteBuf`. We also do not see any incoming messages there.

See [here](https://github.com/r2dbc/r2dbc-mssql/blob/645ce5b489e567d95d3caa9d1ef9b2e4aa6ca1fe/src/main/java/io/r2dbc/mssql/client/ReactorNettyClient.java#L242) for the full code/context.

Reproducer using:

1. Check out https://github.com/r2dbc/r2dbc-mssql
2. Run SQL Server docker image (`docker run -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=A_Str0ng_Required_Password' -p 1433:1433 --name sql1 mcr.microsoft.com/mssql/server:2017-latest`)
3. Upgrade to `reactor-netty` 0.9.0.BUILD-SNAPSHOT
4. Run `io.r2dbc.mssql.MssqlConnectionIntegrationTests`: Test hangs

### Reactor Netty version

0.9.0.BUILD-SNAPSHOT

The issue does not seem related to the used netty version.

### JVM version (e.g. `java -version`)

1.8.0_201

### OS version (e.g. `uname -a`)

MacOS

**Comment by smaldini** [comment]
fixed by https://github.com/reactor/reactor-netty/commit/a55c6674c1b497533a96df3e12cb60bbdb6cbfc8
