### ISSUE TITLE
Strange latency numbers when the rate is inscreased

### ISSUE THREAD

**Issue by benitocm** [reactor/reactor-netty#737]
Hi,
Using the same environment described in https://github.com/reactor/reactor-netty/issues/654  (two AWS instances C5.4xlarge and C5.2xlarge), wrk2 as a test driver and the code similar to the one described in that issue (just testing the webflux option with functional endpoints), I have obtained a weird result in one of the tests.

In the  two tests done here, the server just returns 200 Ok after waiting 100 ms (the mechanism used for delay a request is the same as the one used in https://github.com/reactor/reactor-netty/issues/654 (.i.e. using the .delayElements operator). 

This is how the server responds:

```
private Mono<ServerResponse> text(ServerRequest req) {
		Optional<String> delay = req.queryParam("delay");
		Optional<String> length = req.queryParam("length");

		String body = this.stringGeneratorService.getGeneratedString(Integer.parseInt(length.get()));
		Mono<ServerResponse> serverResponseMono = ServerResponse.ok().contentType(MediaType.TEXT_PLAIN).syncBody(body);

		if (delay.isPresent()) {
			return serverResponseMono.delayElement(Duration.ofMillis(Long.parseLong(delay.get())));
		}
		return serverResponseMono;
	}
```

./wrk2 -t8 -c10000 -d180s -R90000 -L  --timeout 10s http://172.31.23.83:8080/reactivews/getokdelay?length=512\&delay=100
Running 3m test @ http://172.31.23.83:8080/reactivews/getokdelay?length=512&delay=100
  8 threads and 10000 connections
  Thread calibration: mean lat.: 136.379ms, rate sampling interval: 233ms
  Thread calibration: mean lat.: 107.159ms, rate sampling interval: 223ms
  Thread calibration: mean lat.: 107.057ms, rate sampling interval: 223ms
  Thread calibration: mean lat.: 166.570ms, rate sampling interval: 466ms
  Thread calibration: mean lat.: 179.705ms, rate sampling interval: 766ms
  Thread calibration: mean lat.: 106.385ms, rate sampling interval: 222ms
  Thread calibration: mean lat.: 107.060ms, rate sampling interval: 223ms
  Thread calibration: mean lat.: 194.469ms, rate sampling interval: 1030ms
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   103.31ms    6.25ms   1.99s    89.22%
    Req/Sec    11.27k   278.86    12.36k    74.88%
  Latency Distribution (HdrHistogram - Recorded Latency)
 50.000%  101.44ms
 75.000%  102.27ms
 90.000%  110.27ms
 99.000%  122.56ms
 99.900%  130.24ms
 99.990%  138.88ms
 99.999%  551.93ms
100.000%    1.99s

  Detailed Percentile spectrum:
       Value   Percentile   TotalCount 1/(1-Percentile)

     100.223     0.000000           74         1.00
     100.735     0.100000      1768273         1.11
     100.927     0.200000      3312920         1.25
     101.119     0.300000      4979555         1.43
     101.247     0.400000      6103854         1.67
     101.439     0.500000      7693866         2.00
     101.503     0.550000      8164749         2.22
     101.631     0.600000      8986790         2.50
     101.759     0.650000      9651655         2.86
     101.951     0.700000     10380663         3.33
     102.271     0.750000     11084921         4.00
     102.655     0.775000     11464090         4.44
     103.359     0.800000     11789213         5.00
     104.703     0.825000     12169153         5.71
     106.303     0.850000     12532333         6.67
     108.159     0.875000     12896814         8.00
     109.183     0.887500     13081199         8.89
     110.271     0.900000     13268238        10.00
     111.359     0.912500     13447447        11.43
     112.575     0.925000     13639728        13.33
     113.791     0.937500     13823937        16.00
     114.431     0.943750     13914751        17.78
     115.135     0.950000     14007446        20.00
     115.839     0.956250     14093242        22.86
     116.671     0.962500     14184823        26.67
     117.631     0.968750     14278233        32.00
     118.143     0.971875     14323413        35.56
     118.719     0.975000     14370050        40.00
     119.359     0.978125     14417640        45.71
     119.999     0.981250     14461004        53.33
     120.767     0.984375     14507200        64.00
     121.215     0.985938     14531119        71.11
     121.663     0.987500     14553095        80.00
     122.175     0.989062     14575839        91.43
     122.751     0.990625     14598457       106.67
     123.455     0.992188     14622736       128.00
     123.839     0.992969     14634261       142.22
     124.223     0.993750     14644783       160.00
     124.671     0.994531     14655968       182.86
     125.183     0.995313     14667336       213.33
     125.823     0.996094     14679341       256.00
     126.143     0.996484     14684620       284.44
     126.527     0.996875     14690289       320.00
     126.975     0.997266     14696069       365.71
     127.487     0.997656     14702008       426.67
     128.063     0.998047     14707597       512.00
     128.447     0.998242     14710722       568.89
     128.831     0.998437     14713553       640.00
     129.215     0.998633     14716170       731.43
     129.727     0.998828     14719018       853.33
     130.303     0.999023     14721899      1024.00
     130.687     0.999121     14723537      1137.78
     131.071     0.999219     14724913      1280.00
     131.455     0.999316     14726198      1462.86
     131.967     0.999414     14727700      1706.67
     132.607     0.999512     14729171      2048.00
     132.991     0.999561     14729933      2275.56
     133.375     0.999609     14730578      2560.00
     133.887     0.999658     14731338      2925.71
     134.399     0.999707     14731995      3413.33
     135.039     0.999756     14732732      4096.00
     135.423     0.999780     14733062      4551.11
     135.935     0.999805     14733429      5120.00
     136.447     0.999829     14733753      5851.43
     137.215     0.999854     14734157      6826.67
     137.983     0.999878     14734494      8192.00
     138.495     0.999890     14734675      9102.22
     139.007     0.999902     14734840     10240.00
     139.647     0.999915     14735017     11702.86
     140.671     0.999927     14735205     13653.33
     141.951     0.999939     14735374     16384.00
     142.975     0.999945     14735466     18204.44
     144.127     0.999951     14735550     20480.00
     145.535     0.999957     14735639     23405.71
     148.223     0.999963     14735731     27306.67
     158.079     0.999969     14735818     32768.00
     171.775     0.999973     14735863     36408.89
     185.983     0.999976     14735908     40960.00
     206.463     0.999979     14735953     46811.43
     228.991     0.999982     14735998     54613.33
     254.719     0.999985     14736043     65536.00
     266.751     0.999986     14736065     72817.78
     297.215     0.999988     14736088     81920.00
     445.695     0.999989     14736110     93622.86
     669.183     0.999991     14736133    109226.67
     880.639     0.999992     14736155    131072.00
     997.375     0.999993     14736166    145635.56
    1115.135     0.999994     14736178    163840.00
    1218.559     0.999995     14736189    187245.71
    1335.295     0.999995     14736200    218453.33
    1439.743     0.999996     14736211    262144.00
    1503.231     0.999997     14736217    291271.11
    1555.455     0.999997     14736223    327680.00
    1608.703     0.999997     14736228    374491.43
    1669.119     0.999998     14736234    436906.67
    1710.079     0.999998     14736239    524288.00
    1742.847     0.999998     14736242    582542.22
    1774.591     0.999998     14736245    655360.00
    1806.335     0.999999     14736248    748982.86
    1824.767     0.999999     14736251    873813.33
    1846.271     0.999999     14736253   1048576.00
    1867.775     0.999999     14736255   1165084.44
    1879.039     0.999999     14736256   1310720.00
    1900.543     0.999999     14736258   1497965.71
    1910.783     0.999999     14736259   1747626.67
    1922.047     1.000000     14736260   2097152.00
    1932.287     1.000000     14736261   2330168.89
    1943.551     1.000000     14736262   2621440.00
    1953.791     1.000000     14736263   2995931.43
    1953.791     1.000000     14736263   3495253.33
    1955.839     1.000000     14736264   4194304.00
    1955.839     1.000000     14736264   4660337.78
    1967.103     1.000000     14736265   5242880.00
    1967.103     1.000000     14736265   5991862.86
    1967.103     1.000000     14736265   6990506.67
    1977.343     1.000000     14736266   8388608.00
    1977.343     1.000000     14736266   9320675.55
    1977.343     1.000000     14736266  10485760.00
    1977.343     1.000000     14736266  11983725.71
    1977.343     1.000000     14736266  13981013.34
    1987.583     1.000000     14736267  16777216.00
    1987.583     1.000000     14736267          inf
#[Mean    =      103.309, StdDeviation   =        6.255]
#[Max     =     1986.560, Total count    =     14736267]
#[Buckets =           27, SubBuckets     =         2048]
----------------------------------------------------------
  15910161 requests in 3.00m, 8.56GB read
Requests/sec:  88391.90
Transfer/sec:     48.72MB

The CPU consumed was, on average, around 905% (the maximum would be 1600, 16 cores)

I dont have anything to compare with but the numbers do not appears to be bad. The 99.900%  percentile is 130.24ms that is a 30% of the minimun latency (100 ms, the sleep time) with a high load.
```
./wrk2 -t8 -c10000 -d180s -R110000 -L  --timeout 10s http://172.31.23.83:8080/reactivews/getokdelay?length=512\&delay=100
Running 3m test @ http://172.31.23.83:8080/reactivews/getokdelay?length=512&delay=100
  8 threads and 10000 connections
  Thread calibration: mean lat.: 935.462ms, rate sampling interval: 3233ms
  Thread calibration: mean lat.: 952.183ms, rate sampling interval: 3284ms
  Thread calibration: mean lat.: 952.766ms, rate sampling interval: 3291ms
  Thread calibration: mean lat.: 953.102ms, rate sampling interval: 3291ms
  Thread calibration: mean lat.: 950.562ms, rate sampling interval: 3289ms
  Thread calibration: mean lat.: 956.374ms, rate sampling interval: 3301ms
  Thread calibration: mean lat.: 952.036ms, rate sampling interval: 3278ms
  Thread calibration: mean lat.: 949.457ms, rate sampling interval: 3278ms
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    11.71s     5.76s   23.38s    57.81%
    Req/Sec    12.08k    31.57    12.15k    66.16%
  Latency Distribution (HdrHistogram - Recorded Latency)
 50.000%   11.71s
 75.000%   16.70s
 90.000%   19.68s
 99.000%   21.53s
 99.900%   22.07s
 99.990%   22.76s
 99.999%   23.05s
100.000%   23.40s

  Detailed Percentile spectrum:
       Value   Percentile   TotalCount 1/(1-Percentile)

    1263.615     0.000000            1         1.00
    3729.407     0.100000      1582971         1.11
    5738.495     0.200000      3164054         1.25
    7725.055     0.300000      4746831         1.43
    9732.095     0.400000      6333183         1.67
   11714.559     0.500000      7911139         2.00
   12705.791     0.550000      8703502         2.22
   13697.023     0.600000      9495532         2.50
   14688.255     0.650000     10285782         2.86
   15687.679     0.700000     11074524         3.33
   16695.295     0.750000     11870278         4.00
   17203.199     0.775000     12269206         4.44
   17694.719     0.800000     12661990         5.00
   18186.239     0.825000     13053333         5.71
   18694.143     0.850000     13457644         6.67
   19185.663     0.875000     13849940         8.00
   19431.423     0.887500     14046212         8.89
   19677.183     0.900000     14241827        10.00
   19922.943     0.912500     14436354        11.43
   20185.087     0.925000     14644000        13.33
   20430.847     0.937500     14840185        16.00
   20545.535     0.943750     14931754        17.78
   20676.607     0.950000     15036238        20.00
   20791.295     0.956250     15127734        22.86
   20922.367     0.962500     15231825        26.67
   21053.439     0.968750     15335468        32.00
   21102.591     0.971875     15373859        35.56
   21168.127     0.975000     15424553        40.00
   21233.663     0.978125     15474103        45.71
   21315.583     0.981250     15533283        53.33
   21381.119     0.984375     15577771        64.00
   21413.887     0.985938     15598703        71.11
   21463.039     0.987500     15628418        80.00
   21495.807     0.989062     15646979        91.43
   21544.959     0.990625     15672816       106.67
   21594.111     0.992188     15696422       128.00
   21626.879     0.992969     15710596       142.22
   21659.647     0.993750     15723695       160.00
   21692.415     0.994531     15735648       182.86
   21725.183     0.995313     15746393       213.33
   21774.335     0.996094     15760700       256.00
   21790.719     0.996484     15764965       284.44
   21823.487     0.996875     15772632       320.00
   21839.871     0.997266     15776092       365.71
   21872.639     0.997656     15782265       426.67
   21921.791     0.998047     15789942       512.00
   21938.175     0.998242     15792094       568.89
   21954.559     0.998437     15794079       640.00
   21987.327     0.998633     15797550       731.43
   22020.095     0.998828     15800385       853.33
   22069.247     0.999023     15803779      1024.00
   22102.015     0.999121     15805591      1137.78
   22118.399     0.999219     15806372      1280.00
   22167.551     0.999316     15808236      1462.86
   22216.703     0.999414     15809680      1706.67
   22282.239     0.999512     15811221      2048.00
   22315.007     0.999561     15811827      2275.56
   22364.159     0.999609     15812620      2560.00
   22413.311     0.999658     15813336      2925.71
   22478.847     0.999707     15814186      3413.33
   22544.383     0.999756     15814999      4096.00
   22577.151     0.999780     15815388      4551.11
   22609.919     0.999805     15815744      5120.00
   22642.687     0.999829     15816103      5851.43
   22675.455     0.999854     15816445      6826.67
   22724.607     0.999878     15816919      8192.00
   22740.991     0.999890     15817073      9102.22
   22757.375     0.999902     15817211     10240.00
   22790.143     0.999915     15817457     11702.86
   22806.527     0.999927     15817587     13653.33
   22839.295     0.999939     15817818     16384.00
   22855.679     0.999945     15817919     18204.44
   22872.063     0.999951     15818006     20480.00
   22888.447     0.999957     15818077     23405.71
   22904.831     0.999963     15818150     27306.67
   22937.599     0.999969     15818279     32768.00
   22953.983     0.999973     15818347     36408.89
   22953.983     0.999976     15818347     40960.00
   22970.367     0.999979     15818401     46811.43
   22986.751     0.999982     15818450     54613.33
   23003.135     0.999985     15818487     65536.00
   23019.519     0.999986     15818523     72817.78
   23019.519     0.999988     15818523     81920.00
   23035.903     0.999989     15818550     93622.86
   23052.287     0.999991     15818584    109226.67
   23068.671     0.999992     15818606    131072.00
   23068.671     0.999993     15818606    145635.56
   23085.055     0.999994     15818628    163840.00
   23101.439     0.999995     15818646    187245.71
   23101.439     0.999995     15818646    218453.33
   23117.823     0.999996     15818662    262144.00
   23117.823     0.999997     15818662    291271.11
   23134.207     0.999997     15818672    327680.00
   23134.207     0.999997     15818672    374491.43
   23166.975     0.999998     15818683    436906.67
   23183.359     0.999998     15818688    524288.00
   23183.359     0.999998     15818688    582542.22
   23199.743     0.999998     15818692    655360.00
   23216.127     0.999999     15818698    748982.86
   23216.127     0.999999     15818698    873813.33
   23232.511     0.999999     15818700   1048576.00
   23248.895     0.999999     15818703   1165084.44
   23248.895     0.999999     15818703   1310720.00
   23265.279     0.999999     15818706   1497965.71
   23265.279     0.999999     15818706   1747626.67
   23281.663     1.000000     15818707   2097152.00
   23298.047     1.000000     15818708   2330168.89
   23298.047     1.000000     15818708   2621440.00
   23330.815     1.000000     15818710   2995931.43
   23330.815     1.000000     15818710   3495253.33
   23347.199     1.000000     15818711   4194304.00
   23347.199     1.000000     15818711   4660337.78
   23347.199     1.000000     15818711   5242880.00
   23363.583     1.000000     15818712   5991862.86
   23363.583     1.000000     15818712   6990506.67
   23379.967     1.000000     15818713   8388608.00
   23379.967     1.000000     15818713   9320675.55
   23379.967     1.000000     15818713  10485760.00
   23379.967     1.000000     15818713  11983725.71
   23379.967     1.000000     15818713  13981013.34
   23396.351     1.000000     15818714  16777216.00
   23396.351     1.000000     15818714          inf
#[Mean    =    11706.367, StdDeviation   =     5757.881]
#[Max     =    23379.968, Total count    =     15818714]
#[Buckets =           27, SubBuckets     =         2048]
----------------------------------------------------------
  17076114 requests in 3.00m, 9.19GB read
Requests/sec:  94869.82
Transfer/sec:     52.29MB
```
The CPU consumed was, on average, around 848% (the maximum would be 1600, 16 cores)

As you can see the numbers in this case are very bad. The latency are in "seconds".

I dont know the reason but it seems that when passing from 90K req/sec to 110 req/sec I am hitting some bottleneck but I dont know exactly where.

The versions used for these tests are reactor 3.2.9 and reactor-netty 0.8.8

I repeated these tests with the previous version (reactor 3.2.8, reactor netty 0.8.6) and the latency numbers were more or less similar although the CPU consumption was higher: 930 instead of 905 in the case of 90K req/sec and 990 instead of 848 in the case of 110K req/sec

### JVM version (e.g. `java -version`)
java version "1.8.0_202"
Java(TM) SE Runtime Environment (build 1.8.0_202-b08)
Java HotSpot(TM) 64-Bit Server VM (build 25.202-b08, mixed mode)

**Comment by benitocm** [comment]
Hi,

I have repeated the tests updating to spring version 5.1.7. The numbers seems to improve a little in the second test (110K rps) but the latency keeps in "seconds".

./wrk2 -t8 -c10000 -d90s -R90000 -L  --timeout 10s http://172.31.23.83:8080/reactivews/getokdelay?length=512\&delay=100
Running 2m test @ http://172.31.23.83:8080/reactivews/getokdelay?length=512&delay=100
  8 threads and 10000 connections
  Thread calibration: mean lat.: 103.434ms, rate sampling interval: 221ms
  Thread calibration: mean lat.: 103.636ms, rate sampling interval: 223ms
  Thread calibration: mean lat.: 104.607ms, rate sampling interval: 223ms
  Thread calibration: mean lat.: 105.093ms, rate sampling interval: 224ms
  Thread calibration: mean lat.: 103.343ms, rate sampling interval: 221ms
  Thread calibration: mean lat.: 103.718ms, rate sampling interval: 223ms
  Thread calibration: mean lat.: 103.339ms, rate sampling interval: 221ms
  Thread calibration: mean lat.: 103.695ms, rate sampling interval: 221ms
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   103.60ms    5.28ms 305.15ms   86.95%
    Req/Sec    11.27k   318.80    12.58k    72.88%
  Latency Distribution (HdrHistogram - Recorded Latency)
50.000%  101.44ms
75.000%  102.53ms
90.000%  111.49ms
99.000%  124.16ms
99.900%  132.22ms
99.990%  138.37ms
99.999%  146.18ms
100.000%  305.41ms
#[Mean    =      103.598, StdDeviation   =        5.279]
#[Max     =      305.152, Total count    =      6635901]
#[Buckets =           27, SubBuckets     =         2048]
----------------------------------------------------------
  7809042 requests in 1.50m, 4.20GB read
Requests/sec:  86772.30
Transfer/sec:     47.83MB

CPU is around 890% out of 1600%


./wrk2 -t8 -c10000 -d90s -R110000 -L  --timeout 10s http://172.31.23.83:8080/reactivews/getokdelay?length=512\&delay=100
ubuntu@ip-172-31-16-15:~$ ./wrk2 -t8 -c10000 -d90s -R110000 -L  --timeout 10s http://172.31.23.83:8080/reactivews/getokdelay?length=512\&delay=100
Running 2m test @ http://172.31.23.83:8080/reactivews/getokdelay?length=512&delay=100
  8 threads and 10000 connections
  Thread calibration: mean lat.: 940.902ms, rate sampling interval: 3260ms
  Thread calibration: mean lat.: 937.979ms, rate sampling interval: 3250ms
  Thread calibration: mean lat.: 940.714ms, rate sampling interval: 3266ms
  Thread calibration: mean lat.: 921.885ms, rate sampling interval: 3192ms
  Thread calibration: mean lat.: 941.742ms, rate sampling interval: 3270ms
  Thread calibration: mean lat.: 920.538ms, rate sampling interval: 3184ms
  Thread calibration: mean lat.: 933.195ms, rate sampling interval: 3227ms
  Thread calibration: mean lat.: 924.636ms, rate sampling interval: 3188ms
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     6.17s     2.59s   11.33s    58.01%
    Req/Sec    12.08k    38.33    12.18k    70.39%
  Latency Distribution (HdrHistogram - Recorded Latency)
50.000%    6.18s
75.000%    8.40s
90.000%    9.75s
99.000%   10.66s
99.900%   10.93s
99.990%   11.09s
99.999%   11.21s
100.000%   11.34s
#[Mean    =     6172.048, StdDeviation   =     2588.401]
#[Max     =    11329.536, Total count    =      7127012]
#[Buckets =           27, SubBuckets     =         2048]
----------------------------------------------------------
  8388950 requests in 1.50m, 4.52GB read
Requests/sec:  93208.06
Transfer/sec:     51.38MB

CPU is around 800% out of 1600%

**Comment by smaldini** [comment]
we're working on more improvements on 0.8.9.BUILD-SNAPSHOT but this is a weird issue hopefully not a regression with this https://github.com/reactor/reactor-core/pull/1674

**Comment by benitocm** [comment]
Just for me to understand. The usage of CPU should be increased when the rate of requests is increased. The latency will also increase gradually but not in that abrupt leap. Until a certain point when the latency will go up very quickly (ideally similar to a queue system M/M/16)

**Comment by benitocm** [comment]
I think I will not be able to try to reproduce this problems so I will close it for now.
