### ISSUE TITLE
Consider making netty-codec-http[2] dependencies optional

### ISSUE THREAD

**Issue by sdeleuze** [reactor/reactor-netty#739]
While working with `r2dbc-postgresql` and WebFlux i a Gradle project, I faced a very annoying issue where the [exclusions](https://github.com/r2dbc/r2dbc-postgresql/blob/efca10386046e70abec93a35154546ed4cca6802/pom.xml#L87-L99)  of `netty-codec-http` and `netty-codec-http2` in `r2dbc-postgresql` break completely WebFlux since it removes the `netty-codec-http` dependency from the project. We are going to remove for now these excludes from R2DBC but that just a workaround since it will now pull some dependencies it does not need.

Since `reactor-netty` usage is wider than just HTTP (R2DBC is a good example), my proposal is to make these 2 dependencies optionals and update consumer projects like WebFlux to add these explicitly.

**Comment by bsideup** [comment]
We plan to shade them, see #734

**Comment by violetagg** [comment]
Shading is not an option, most probably we will separate the project to submodules.

**Comment by violetagg** [comment]
Reactor Netty is separated on two modules:
- `reactor-netty-core` - contains the core functionality + TCP + UDP
- `reactor-netty-http` - depends on `reactor-netty-core` and provides HTTP
