### ISSUE TITLE
Reactor Netty decodes the path before doing HTTP request

### ISSUE THREAD

**Issue by utwyko** [reactor/reactor-netty#74]
When doing an HTTP request to a URI with any encoded sign, Reactor Netty returns an HTTPClientException with the URI decoded. I assume the HTTP request is done with this decoded URI and that results in the error.

`httpClient.get("/test%25test")`

returns

`reactor.ipc.netty.http.client.HttpClientException: HTTP request failed with code: 400.
Failing URI: /test%test`

The issue does not happen when using an encoded sign in the query part of the URI.

**Comment by utwyko** [comment]
Created a project that reproduces the issue: https://github.com/utwyko/reactor-netty-url-encoding-test

**Comment by utwyko** [comment]
Chased it down to MonoHttpClientResponse, line 99. 

https://github.com/reactor/reactor-netty/blob/96daef2b624d5dada1b42fbaf77056a36122574f/src/main/java/reactor/ipc/netty/http/client/MonoHttpClientResponse.java#L96-L105

Here, the URI is set based on uri.getPath(). uri.getPath() decodes the path. Using uri.getRawPath() would fix this issue.

**Comment by breun** [comment]
We are currently encoding our URI's twice to work around this bug. To anyone doing the same: pay attention when upgrading to a version with this fix, because you won't notice the difference with URI's that don't change when encoded/decoded, but you will with ones that do.
