### ISSUE TITLE
Reactor Netty Milestone (Reference) link is wrong on projectreactor.io

### ISSUE THREAD

**Issue by akiraly** [reactor/reactor-netty#740]
Currently it deeplinks to reactor-core reference guide.

Additionally the javadoc Release link points to 0.8.7 instead of 0.8.8.
Also only the 0.8.7 reference guide is available at https://projectreactor.io/docs/netty/0.8.7.RELEASE/reference/index.html
0.8.8 reference guide is missing.

**Comment by smaldini** [comment]
Good catch, the site has been fixed and redeploying for milestone link. The 0.8.x branch do not have reference guide and the old references have been purged to reflect that (they should now 404).
