### ISSUE TITLE
Investigate if HttpServer can avoid producing cancel on single mono responses

### ISSUE THREAD

**Issue by smaldini** [reactor/reactor-netty#741]
We have a reporter in webflux (https://github.com/spring-projects/spring-framework/issues/22952) observing an unnecessary cancel signal for single mono responses. 
After initial investigation it appears that both webflux and netty can produce this undesired cancel. In the case of reactor-netty it appears that we will callback cancel after successful single response write in HttpTrafficHandler.

**Comment by duke-cliff** [comment]
When will be the release date of 0.9.0? Before this fix, we have to downgrade to 0.8.6.

**Comment by Delorien84** [comment]
Hi, 
 I do not agree marking this issue as enhancement. From my point of view it is a bug, as it broke all `org.springframework.web.server.WebFilter`  those using `onComplete` callback.

**Comment by alfred-thomas** [comment]
I agree with @Delorien84 - For us it means we cannot upgrade from Spring Boot 2.1.4 until this has been fixed, unless we start using Undertow instead of Netty

**Comment by winster** [comment]
Does this deserve an attention?
https://github.com/reactor/reactor-addons/issues/236  
No one is looking at it there. Hence posting here.

**Comment by violetagg** [comment]
@winster What do you mean? This issue is fixed.

**Comment by winster** [comment]
Yes, the issue in reactor-netty is fixed. But there are other components in reactor where it is still open.
reactor-extra - https://github.com/reactor/reactor-addons/issues/236
reactor-core - https://github.com/reactor/reactor-core/issues/2396

I commented here to know in case are these issues related.
