### ISSUE TITLE
031 ERROR 8804 — [ctor-http-nio-1] 

### ISSUE THREAD

**Issue by vymarj** [reactor/reactor-netty#747]
### Expected behavior
client program should wait for whole data to read before exit the client proogram 

### Actual behavior
Current Error: 2019-05-20 17:52:18.031 ERROR 8804 — [ctor-http-nio-1] c.a.f.Service.FdbCheckClientService : [Ljava.lang.StackTraceElement;@43c0301a 

### Reactor Netty version
2.1.4.RELEASE of springboot

### JVM version (e.g. `java -version`)
java 11

### OS version (e.g. `uname -a`)
Windows 10

attached file
 public int fdbCheckCall(String[] inputParams) {

        StringBuffer completeStatement = new StringBuffer();
        List<ResponseMessage> responseMesssageList = new ArrayList<>();
        try {
            MultiValueMap<String, String> paramsMap = utility.createMultiMap(inputParams);
            utility.checkInputParameter(paramsMap);

            Flux<ResponseMessage> result = fdbCheckMakeRequest(paramsMap);

            result.doFinally(signalType -> onEndOfSubcription(signalType, completeStatement))
                    .subscribe(responseMessage -> {
                if(responseMessage.getResponseLevel().equalsIgnoreCase("SUCCESS"))
                    log.info(responseMessage.toString());
                else {
                    log.error(responseMessage.toString());
                }
                responseMesssageList.add(responseMessage);
            },error -> {ErrorPool.increamentErrorCount();
                        log.error(error.getStackTrace().toString());
                    if(error.getMessage().contains("Connection refused"))
                        log.error(error + "\n One of possible reason for error is \n Server may not be running \n");});

           while(!(completeStatement.toString().contains("COMPLETE") || completeStatement.toString().contains("ERROR") || completeStatement.toString().contains("CANCEL")))
            Thread.sleep(1000);
        } catch (Exception e) {
            ErrorPool.increamentErrorCount();
            log.error(e.getMessage());
        }

        if (responseMesssageList.isEmpty())
            return ErrorPool.hasError(null);
        else
            return ErrorPool.hasError(responseMesssageList.get(responseMesssageList.size() - 1));

    }

**Comment by violetagg** [comment]
@vymarj Closing this as there is not enough information.
