### ISSUE TITLE
Using CustomHostnameVerifier instead of default Hostname Verifier for ssl

### ISSUE THREAD

**Issue by venkatesh010** [reactor/reactor-netty#752]
### Expected behavior
Want to avoid hostname verification for ssl using certificates
By default it uses a Default Hostname Verification in Netty
Specified inside class reactor.netty.http.client

### Steps to reproduce
There is a constructor for HttpClientSecure which accepts Netty SslProvider.

But it is not exposed to users

So there is no appropriate way to use a provider with custom hostname verification Which has it's custom matching scheme 

### Reactor Netty version
0.8.5.RELEASE
### JVM version (e.g. `java -version`)
1.8

**Comment by venkatesh010** [comment]
The default hostname verifier is present in 
reactor.netty.http.client.HttpClientSecure

**Comment by venkatesh010** [comment]
Can't we have any method in Netty HttpClient which exposes a way to configure HttpClientSecure using custom SslProvider

Something like:

Public final HttpClient secure(SslProvider sslProvider){
return HttpClientSecure(this, sslProvider);
}

**Comment by violetagg** [comment]
@venkatesh010 What about using the code snippet below?

```
httpClient.secure(ssl -> ssl.sslContext(ctx)
			    .handlerConfigurator(sslHandler -> sslHandler.<some-method-invokation>));
```

`handlerConfigurator` will provide you the Netty's SslHandler

**Comment by venkatesh010** [comment]
It worked.
Was trying this from past two days.
It solved my problem of using custom matcher for hostname verification while using netty for two way ssl

for others, here is the code snippet:

```
public HttpClient getHttpClient(HttpClientProperties properties){

            // configure pool resources
            HttpClientProperties.Pool pool = properties.getPool();

            ConnectionProvider connectionProvider;
            if (pool.getType() == DISABLED) {
                connectionProvider = ConnectionProvider.newConnection();
            }
            else if (pool.getType() == FIXED) {
                connectionProvider = ConnectionProvider.fixed(pool.getName(),
                        pool.getMaxConnections(), pool.getAcquireTimeout());
            }
            else {
                connectionProvider = ConnectionProvider.elastic(pool.getName());
            }

            HttpClient httpClient = HttpClient.create(connectionProvider)
                    .tcpConfiguration(tcpClient -> {

                        if (properties.getConnectTimeout() != null) {
                            tcpClient = tcpClient.option(
                                    ChannelOption.CONNECT_TIMEOUT_MILLIS,
                                    properties.getConnectTimeout());
                        }

                        // configure proxy if proxy host is set.
                        HttpClientProperties.Proxy proxy = properties.getProxy();

                        if (StringUtils.hasText(proxy.getHost())) {

                            tcpClient = tcpClient.proxy(proxySpec -> {
                                ProxyProvider.Builder builder = proxySpec
                                        .type(ProxyProvider.Proxy.HTTP)
                                        .host(proxy.getHost());

                                PropertyMapper map = PropertyMapper.get();

                                map.from(proxy::getPort).whenNonNull().to(builder::port);
                                map.from(proxy::getUsername).whenHasText()
                                        .to(builder::username);
                                map.from(proxy::getPassword).whenHasText()
                                        .to(password -> builder.password(s -> password));
                                map.from(proxy::getNonProxyHostsPattern).whenHasText()
                                        .to(builder::nonProxyHosts);
                            });
                        }
                        return tcpClient;
                    });

            HttpClientProperties.Ssl ssl = properties.getSsl();
            if (ssl.getTrustedX509CertificatesForTrustManager().length > 0
                    || ssl.isUseInsecureTrustManager()) {
                httpClient = httpClient.secure(sslContextSpec -> {
                    // configure ssl
                    SslContextBuilder sslContextBuilder = SslContextBuilder.forClient();

                    X509Certificate[] trustedX509Certificates = ssl
                            .getTrustedX509CertificatesForTrustManager();
                    if (trustedX509Certificates.length > 0) {
                        sslContextBuilder.trustManager(trustedX509Certificates);
                    }
                    else if (ssl.isUseInsecureTrustManager()) {
                        sslContextBuilder
                                .trustManager(InsecureTrustManagerFactory.INSTANCE);
                    }


                    sslContextSpec.sslContext(sslContextBuilder)
                            .defaultConfiguration(ssl.getDefaultConfigurationType())
                            .handshakeTimeout(ssl.getHandshakeTimeout())
                            .closeNotifyFlushTimeout(ssl.getCloseNotifyFlushTimeout())
                            .closeNotifyReadTimeout(ssl.getCloseNotifyReadTimeout())
                            .handlerConfigurator(
                                    (handler)->{
                                        SSLEngine engine = handler.engine();
                                        //engine.setNeedClientAuth(true);
                                        SSLParameters params = new SSLParameters();
                                        List<SNIMatcher> matchers = new LinkedList<>();
                                        SNIMatcher matcher = new SNIMatcher(0) {

                                            @Override
                                            public boolean matches(SNIServerName serverName) {
                                                return true;
                                            }
                                        };
                                        matchers.add(matcher);
                                        params.setSNIMatchers(matchers);
                                        engine.setSSLParameters(params);
                                    }
                            )
                    ;
                });
            }

            return httpClient;

        }
```

**Comment by Nyamkhuub** [comment]
@violetagg  can I see your pom.xml, please?

**Comment by violetagg** [comment]
@Nyamkhuub pom.xml?

What is your problem? Something with versions?

**Comment by Nyamkhuub** [comment]
@violetagg 
Which dependency contains HttpClientProperties class?
I confused. I am using org.springframework.cloud.gateway.config. But, If I'm used this dependency, My project failed.

**Comment by Nyamkhuub** [comment]
@violetagg 

I am using Admin server with Eureka. So all services deployed on the secure (SSL) tomcat server. Then, All services throw SSL exceptions.
For Example:

> javax.net.ssl.SSLHandshakeException
General SSLEngine problem ...

<img src="https://i.imgur.com/WpY5sxY.png"/>

well, I follow this documentation <a href="https://codecentric.github.io/spring-boot-admin/current/#_using_mutual_tls">here</a>

> SBA Server can also use client certificates to authenticate when accessing the actuator endpoints. If a custom configured ClientHttpConnector bean is present, Spring Boot will automatically configure a WebClient.Builder using it, which will be used by Spring Boot Admin.

```
@Bean
public ClientHttpConnector customHttpClient() {
    SslContextBuilder sslContext = SslContextBuilder.forClient();
    //Your sslContext customizations go here
    HttpClient httpClient = HttpClient.create().secure(
        ssl -> ssl.sslContext(sslContext)
    );
    return new ReactorClientHttpConnector(httpClient);
}
```
But doesn't working. So, In my opinion, I should using your function. Help me!

**Comment by violetagg** [comment]
Most probably @venkatesh010 uses https://github.com/spring-cloud/spring-cloud-gateway/blob/master/spring-cloud-gateway-core/src/main/java/org/springframework/cloud/gateway/config/HttpClientProperties.java
in order to instrument the HttpClient used by the gateway

If you are not using gateway you do not need to use this.

```
@Bean
public ClientHttpConnector customHttpClient() {
    SslContextBuilder sslContext = SslContextBuilder.forClient()
             .trustManager(InsecureTrustManagerFactory.INSTANCE);
    //Your sslContext customizations go here
    HttpClient httpClient = HttpClient.create().secure(
        ssl -> ssl.sslContext(sslContext)
              .handlerConfigurator(
                                    (handler)->{
                                        SSLEngine engine = handler.engine();
                                        //engine.setNeedClientAuth(true);
                                        SSLParameters params = new SSLParameters();
                                        List<SNIMatcher> matchers = new LinkedList<>();
                                        SNIMatcher matcher = new SNIMatcher(0) {

                                            @Override
                                            public boolean matches(SNIServerName serverName) {
                                                return true;
                                            }
                                        };
                                        matchers.add(matcher);
                                        params.setSNIMatchers(matchers);
                                        engine.setSSLParameters(params);
                                    }
                            )
    );
    return new ReactorClientHttpConnector(httpClient);
}
```

also you can change `trustManager` with `trustedX509Certificates`.

**Comment by venkatesh010** [comment]
Good to close this

**Comment by copbint** [comment]
Actually this answer is really misleading，there is nothing about SNIMatcher in client side, Set endpointIdentificationAlgorithm to null is the key point。
The code above works because of default value of SSLParameters.endpointIdentificationAlgorithm is null。


```
            .handlerConfigurator(sslHandler -> {
                SSLEngine engine = sslHandler.engine();
                SSLParameters newSslParameters = engine.getSSLParameters(); // 返回的是一个新对象
                // 参考：https://github.com/AdoptOpenJDK/openjdk-jdk11/blob/master/src/java.net.http/share/classes/jdk/internal/net/http/AbstractAsyncSSLConnection.java#L116
                newSslParameters.setEndpointIdentificationAlgorithm(null);
                engine.setSSLParameters(newSslParameters);
            })
```

**Comment by venkatesh010** [comment]
@violetagg hey, in Netty 1.0.3 sslconextbuilder defaultspec is deprecated
So I updated to ProtocolSslContextSpec, and now my sslhandler isn't getting overridden to use nohostnameverifier somehow

Can you suggest on that?

**Comment by violetagg** [comment]
> @violetagg hey, in Netty 1.0.3 sslconextbuilder defaultspec is deprecated So I updated to ProtocolSslContextSpec, and now my sslhandler isn't getting overridden to use nohostnameverifier somehow
> 
> Can you suggest on that?

@venkatesh010 Can you provide here your configuration with the old sslconextbuilder defaultspec?

**Comment by Alex33400** [comment]
Hi;
I don't know it the problem remains, butin the latest versions you can create your own SslProvider then pass it to the httpclient constructor like : 

`
SslContext sslContext = SslContextBuilder.forClient()
                .keyManager(keyManagerFactory)
                .trustManager(trustManagerFactory)
                .build();

        SslProvider sslProvider = SslProvider.builder()
                .sslContext(sslContext)
                //.handlerConfigurator(HttpClientSecurityUtils.HOSTNAME_VERIFICATION_CONFIGURER) // if you finally want to add the hostname verification configurer, on at least put a condition on it
                .build();

        HttpClient httpClient = HttpClient.create()
                .secure(sslProvider);
`

It allows to avoid the defaultSslProvider which set the endpointIdentificationAlgorithm to "HTTPS" which enable the hostname verification
