### ISSUE TITLE
Mutual TLS SSL Context Not Working

### ISSUE THREAD

**Issue by trevorwhitney** [reactor/reactor-netty#757]
### Expected behavior
When I curl the reactor netty server, it should behave the same way as the raw netty server in that it returns a 200 response with the text "Hello World".

### Actual behavior
While the raw netty server works fine, the reactor netty server throws an error `reactor-http-nio-3, fatal error: 80: Inbound closed before receiving peer's close_notify: possible truncation attack?` and curl returns `curl: (56) LibreSSL SSL_read: error:1404C10B:SSL routines:ST_OK:wrong version number, errno 0`

### Steps to reproduce

1. Clone https://github.com/trevorwhitney/reactor-netty-error
1. Follow steps in the README.md

### Reactor Netty version
0.8.8.RELEASE

### JVM version (e.g. `java -version`)
java version "1.8.0_202-ea"
Java(TM) SE Runtime Environment (build 1.8.0_202-ea-b03)
Java HotSpot(TM) 64-Bit Server VM (build 25.202-b03, mixed mode)

### OS version (e.g. `uname -a`)
Darwin 18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64

**Comment by trevorwhitney** [comment]
Also tested again `0.9.0.M1` release and saw the same behavior

**Comment by violetagg** [comment]
Follow https://github.com/netty/netty/issues/9231

**Comment by trevorwhitney** [comment]
Will do! Thanks!

**Comment by trevorwhitney** [comment]
netty/netty#9231 was closed, and based on Norman's [comments](https://github.com/netty/netty/issues/9231#issuecomment-504918060) it sounds like `netty` might be doing an extra `channelReadComplete` causing the connection to switch an encrypted mode sooner, while `reactor-netty` is not. As this extra call seems unnecessary, I would say this is not in fact a bug and am closing the issue. Thanks all for your help!
