### ISSUE TITLE
Met PrematureCloseException: Connection prematurely closed BEFORE response

### ISSUE THREAD

**Issue by xia-deng** [reactor/reactor-netty#774]
Hi, I met an exception: 
reactor.netty.http.client.PrematureCloseException: Connection prematurely closed BEFORE response

I am using spring-boot version: 2.1.6.RELEASE
And the reactor-netty version is: 0.8.9.RELEASE
And the reactor-core version is: 3.2.10.RELEASE
Here is my code:
1.WebClient:
return WebClient.create()
2.using webClient:
`Mono<ClientResponse> resp = webClient.get()
                .uri(url)
                .headers(c -> this.processHeader(c, token, headers))
                .exchange()
                .flatMap(r -> Mono.just(r));
        return verifyResponse(resp, analyzer, url, HttpMethod.GET.name(), null);`

The issue is appeared sometimes.

**Comment by violetagg** [comment]
@xia-deng What does the code `verifyResponse`?

Enable logging - `reactor.netty=debug` and send the logs OR provide a reproducible scenario.

**Comment by violetagg** [comment]
Closing this as there is no response from the author.
