### ISSUE TITLE
 How to switch proxy address?

### ISSUE THREAD

**Issue by machao23** [reactor/reactor-netty#780]
I tried to switch the proxy address by rebuilding httpclient, but the proxy address has not changed because the resource pool is used.
Less elegant way is call HttpResources.reset
netty-reacotr version is 0.7.15.RELEASE

**Comment by violetagg** [comment]
@machao23 Yes use `HttpResources.reset`. We do not support 0.7.x anymore. This issue is resolved with 0.8.x versions.
