### ISSUE TITLE
TCP: Connection.addHandler weird behavior 

### ISSUE THREAD

**Issue by Nashatyrev** [reactor/reactor-netty#783]
### Expected behavior
When adding Netty handler with `Connection.addHandler` `channelRegistered` and `channelActive` events should be fired, pending inbound messages should be delivered 
### Actual behavior
No `channelRegistered`, `channelActive` events received
Without `sleep` the message "aaa" is handled, while with `sleep` the message is lost
`channelInactive` and `channelUnregistered` are received upon disconnect
The similar behavior when adding handler in `doOnConnected` callback
### Steps to reproduce
```kt
        TcpServer.create()
            .port(11111)
            .handle { i, o ->  o.sendString(Flux.just("aaa")).neverComplete()}
            .bindNow()
        val connection = TcpClient.create()
            .host("localhost")
            .port(11111)
            .option(ChannelOption.AUTO_READ, true)
            .connectNow()
        println("Connected")

//        Thread.sleep(1000)

        connection.addHandlerLast("h1", LoggingHandler("###1", LogLevel.ERROR))
```
### Reactor Netty version
0.9.0M2
### JVM version (e.g. `java -version`)
8b162 x64
### OS version (e.g. `uname -a`)
Windows 10

**Comment by Nashatyrev** [comment]
Guys, just would like to know whether I'm doing something wrong or it's just a bug or this is not supposed to work at all this way? Thanks!

**Comment by violetagg** [comment]
@Nashatyrev 
Why do you need this `option(ChannelOption.AUTO_READ, true)`?

`doOnConnected` is invoked when the channel is already registered and active.
https://github.com/reactor/reactor-netty/blob/master/src/main/java/reactor/netty/channel/ChannelOperationsHandler.java#L58

You can try this `doOnConnect(bootstrap -> BootstrapHandlers.updateConfiguration(...))`

If it is about new `LoggingHandler` why don't you use one of the `wiretap()` methods?

**Comment by Nashatyrev** [comment]
@violetagg Thanks for response!
> Why do you need this option(ChannelOption.AUTO_READ, true)?

Because else I would need to manually call `read()`. 
> (I mean you should never set this option)

Why so? Is the `reactor-netty` not designed to work with this option? 
> You can try this doOnConnect(bootstrap -> BootstrapHandlers.updateConfiguration(...))

I would like to completely get rid of installing handlers from inside callbacks and do it like in my sample (you may check out my explanation with more details here https://stackoverflow.com/questions/57078441/delayed-pipeline-handler-setup)

> If it is about new LoggingHandler why don't you use one of the wiretap() methods?

`LoggingHandler` is just a sample handler which just prints all events. Any other handler behaves the same way (i.e. no `channelActive` & `channelRead` events)

**Comment by Nashatyrev** [comment]
Actually the main question is whether invoking `connection.addHandlerLast` outside of channel initialization callback is the acceptable pattern for `reactor-netty` ?

**Comment by violetagg** [comment]
> Because else I would need to manually call read()
That's not true.

> Why so? Is the reactor-netty not designed to work with this option?
Reactor Netty sets `ChannelOption.AUTO_READ=false`explicitly in order to be able to provide Backpressure support. The Reactor Netty's implementation takes care to invoke `read()` when it is necessary. If you observe something else please report an issue.

> Actually the main question is whether invoking connection.addHandlerLast outside of channel initialization callback is the acceptable pattern for reactor-netty ?

In order to receive a `Connection` object when invoking `connectNow()` we need either to acquire a connection from the connection pool or to create a new connection. In both cases you won't be able to listen for specific events like `connect`, `register` etc.

**Comment by Nashatyrev** [comment]
> In both cases you won't be able to listen for specific events like connect, register etc.

But I'm still not able to receive data (`channelRead` is not invoked). Also `channelActive` is not invoked, so the handler couldn't know when it may start writing. The `LoggingHandler` just prints `CLOSE`, `INACTIVE`, `UNREGISTERED` events when the connection is closed

**Comment by Nashatyrev** [comment]
In the sample above I'm expecting that the `LoggingHandler.channelRead("aaa")` is invoked. But it's not. 
Is it a bug or invalid use case?

**Comment by violetagg** [comment]
I'm testing with the code below (I don't know what your code is, do you invoke `connection.inbound().receive()` in order to start receiving data from the server)

```
@Test
public void test() {
	TcpServer.create()
			.port(11111)
			.handle((i, o) -> o.sendString(Flux.just("aaa")).neverComplete())
			.wiretap(true)
			.bindNow();
	Connection connection =
			TcpClient.create()
					.host("localhost")
					.port(11111)
					.wiretap(true)
					.connectNow();
	connection.addHandlerLast("h1", new LoggingHandler("###1", LogLevel.ERROR));
	connection.inbound()
			.receive()
			.blockLast();
}
```

I'm seeing the following output

```
19:19:28.636 [Test worker] DEBUG reactor.netty.tcp.TcpResources - [tcp] resources will use the default LoopResources: DefaultLoopResources {prefix=reactor-tcp, daemon=true, selectCount=8, workerCount=8}
19:19:28.701 [Test worker] DEBUG reactor.netty.tcp.TcpResources - [tcp] resources will use the default ConnectionProvider: PooledConnectionProvider {name=tcp, poolFactory=reactor.netty.resources.ConnectionProvider$$Lambda$13/2113506826@2fc92bd}
19:19:28.742 [Test worker] DEBUG r.netty.resources.DefaultLoopEpoll - Default Epoll support : false
19:19:28.826 [Test worker] DEBUG r.netty.resources.DefaultLoopKQueue - Default KQueue support : false
19:19:30.447 [reactor-tcp-nio-1] DEBUG reactor.netty.tcp.TcpServer - [id: 0xaf8cd5f4, L:/0:0:0:0:0:0:0:0:11111] Bound new server
19:19:30.586 [Test worker] DEBUG r.n.r.PooledConnectionProvider - Creating new client pool [tcp] for localhost:11111
19:19:30.625 [reactor-tcp-nio-5] DEBUG r.n.r.PooledConnectionProvider - [id: 0xd7a0152c] Created new pooled channel, now 0 active connections and 1 inactive connections
19:19:30.715 [reactor-tcp-nio-5] DEBUG r.netty.channel.BootstrapHandlers - [id: 0xd7a0152c] Initialized pipeline DefaultChannelPipeline{(reactor.left.loggingHandler = io.netty.handler.logging.LoggingHandler), (BootstrapHandlers$BootstrapInitializerHandler#0 = reactor.netty.channel.BootstrapHandlers$BootstrapInitializerHandler), (SimpleChannelPool$1#0 = io.netty.channel.pool.SimpleChannelPool$1), (reactor.right.reactiveBridge = reactor.netty.channel.ChannelOperationsHandler)}
19:19:30.776 [reactor-tcp-nio-5] DEBUG reactor.netty.tcp.TcpClient - [id: 0xd7a0152c] REGISTERED
19:19:30.778 [reactor-tcp-nio-5] DEBUG reactor.netty.tcp.TcpClient - [id: 0xd7a0152c] CONNECT: localhost/127.0.0.1:11111
19:19:30.798 [reactor-tcp-nio-5] DEBUG reactor.netty.tcp.TcpClient - [id: 0xd7a0152c, L:/127.0.0.1:52595 - R:localhost/127.0.0.1:11111] ACTIVE
19:19:30.799 [reactor-tcp-nio-5] DEBUG r.n.r.PooledConnectionProvider - [id: 0xd7a0152c, L:/127.0.0.1:52595 - R:localhost/127.0.0.1:11111] onStateChange(PooledConnection{channel=[id: 0xd7a0152c, L:/127.0.0.1:52595 - R:localhost/127.0.0.1:11111]}, [connected])
19:19:30.826 [reactor-tcp-nio-6] DEBUG r.netty.channel.BootstrapHandlers - [id: 0xd7a79816, L:/127.0.0.1:11111 - R:/127.0.0.1:52595] Initialized pipeline DefaultChannelPipeline{(reactor.left.loggingHandler = io.netty.handler.logging.LoggingHandler), (BootstrapHandlers$BootstrapInitializerHandler#0 = reactor.netty.channel.BootstrapHandlers$BootstrapInitializerHandler), (reactor.right.reactiveBridge = reactor.netty.channel.ChannelOperationsHandler)}
19:19:30.828 [reactor-tcp-nio-6] DEBUG reactor.netty.tcp.TcpServer - [id: 0xd7a79816, L:/127.0.0.1:11111 - R:/127.0.0.1:52595] REGISTERED
19:19:30.829 [reactor-tcp-nio-6] DEBUG reactor.netty.tcp.TcpServer - [id: 0xd7a79816, L:/127.0.0.1:11111 - R:/127.0.0.1:52595] ACTIVE
19:19:31.320 [reactor-tcp-nio-6] DEBUG reactor.netty.tcp.TcpServer - [id: 0xd7a79816, L:/127.0.0.1:11111 - R:/127.0.0.1:52595] Handler is being applied: reactor.netty.tcp.TcpClientTests$$Lambda$5/455260278@3ba584d8
19:19:31.320 [reactor-tcp-nio-5] DEBUG r.n.r.PooledConnectionProvider - [id: 0xd7a0152c, L:/127.0.0.1:52595 - R:localhost/127.0.0.1:11111] onStateChange(ChannelOperations{PooledConnection{channel=[id: 0xd7a0152c, L:/127.0.0.1:52595 - R:localhost/127.0.0.1:11111]}}, [configured])
19:19:31.323 [reactor-tcp-nio-5] DEBUG r.n.r.PooledConnectionProvider - [id: 0xd7a0152c, L:/127.0.0.1:52595 - R:localhost/127.0.0.1:11111] Registering pool release on close event for channel
19:19:31.327 [reactor-tcp-nio-5] DEBUG r.n.r.PooledConnectionProvider - [id: 0xd7a0152c, L:/127.0.0.1:52595 - R:localhost/127.0.0.1:11111] Channel connected, now 1 active connections and 0 inactive connections
19:19:31.382 [Test worker] DEBUG reactor.netty.ReactorNetty - [id: 0xd7a0152c, L:/127.0.0.1:52595 - R:localhost/127.0.0.1:11111] Added decoder [h1] at the end of the user pipeline, full pipeline: [reactor.left.loggingHandler, h1, reactor.right.reactiveBridge, DefaultChannelPipeline$TailContext#0]
19:19:31.411 [reactor-tcp-nio-5] DEBUG reactor.netty.channel.FluxReceive - [id: 0xd7a0152c, L:/127.0.0.1:52595 - R:localhost/127.0.0.1:11111] Subscribing inbound receiver [pending: 0, cancelled:false, inboundDone: false]
19:19:31.564 [reactor-tcp-nio-6] DEBUG reactor.netty.tcp.TcpServer - [id: 0xd7a79816, L:/127.0.0.1:11111 - R:/127.0.0.1:52595] WRITE: 3B
         +-------------------------------------------------+
         |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
+--------+-------------------------------------------------+----------------+
|00000000| 61 61 61                                        |aaa             |
+--------+-------------------------------------------------+----------------+
19:19:31.569 [reactor-tcp-nio-6] DEBUG reactor.netty.tcp.TcpServer - [id: 0xd7a79816, L:/127.0.0.1:11111 - R:/127.0.0.1:52595] FLUSH
19:19:31.580 [reactor-tcp-nio-5] DEBUG reactor.netty.tcp.TcpClient - [id: 0xd7a0152c, L:/127.0.0.1:52595 - R:localhost/127.0.0.1:11111] READ: 3B
         +-------------------------------------------------+
         |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
+--------+-------------------------------------------------+----------------+
|00000000| 61 61 61                                        |aaa             |
+--------+-------------------------------------------------+----------------+
19:19:31.584 [reactor-tcp-nio-5] ERROR ###1 - [id: 0xd7a0152c, L:/127.0.0.1:52595 - R:localhost/127.0.0.1:11111] READ: 3B
         +-------------------------------------------------+
         |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
+--------+-------------------------------------------------+----------------+
|00000000| 61 61 61                                        |aaa             |
+--------+-------------------------------------------------+----------------+
19:19:31.588 [reactor-tcp-nio-5] DEBUG reactor.netty.tcp.TcpClient - [id: 0xd7a0152c, L:/127.0.0.1:52595 - R:localhost/127.0.0.1:11111] READ COMPLETE
19:19:31.589 [reactor-tcp-nio-5] ERROR ###1 - [id: 0xd7a0152c, L:/127.0.0.1:52595 - R:localhost/127.0.0.1:11111] READ COMPLETE
Gradle build daemon has been stopped: cancel requested but timed out
```

**Comment by violetagg** [comment]
@Nashatyrev I'm closing this.

As a summary:
- Do not set `auto-read` to `true`.
- For events like `connect`, `register`, `active` you have to use `doOnConnect` and add your handler.
- For other events you can add a handler when you receive `Connection` object and before start reading/writing.

If there are other questions let's discuss on Gitter/Stackoverflow

**Comment by Nashatyrev** [comment]
@violetagg Thanks a lot for your detailed explanations!
The outcome is that adding `ChannelHandler`s via `Connection` significantly differs from adding them directly to pipeline. 
E.g. when adding a handler via `ChannelInitializer` in the sample above it doesn't receive a message: 
```kt
        connection.addHandlerLast("i2", object: ChannelInitializer<Channel>() {
            override fun initChannel(ch: Channel) {
                ch.pipeline().addLast(LoggingHandler("###2", LogLevel.ERROR))
            }
        } )
```

**Comment by violetagg** [comment]
let me reopen that in order to extend the javadoc for `addHandler`

**Comment by jsAlcyon** [comment]
Being a newbie to  ReactorNetty I am fighting with the redesign of  my Netty Tcp server to reactor Netty. The problem I am not able to pass over is how to inject my working pipeline configuration to the  TcpServer.  doOnConnect does not work as you explained because initChannel was already called. Could you provide please a simple example how to do this. Sorry for the low level question but it really stops my progressing in the learning process. Till now JavaDoc is not of any help.
Thanks in advance

**Comment by violetagg** [comment]
@jsAlcyon ask your questions here [Gitter](https://gitter.im/reactor/reactor-netty)
