### ISSUE TITLE
NullPointerException in SendManyInner with Reactor Netty 0.8.9

### ISSUE THREAD

**Issue by ahmedyarub** [reactor/reactor-netty#785]
### Expected behavior
Spring Cloud Gateway should forward requests without errors.

### Actual behavior
I intermittently get:
j.l.NullPointerException: null
	at r.n.c.MonoSendMany$SendManyInner.cleanup(MonoSendMany.java:338)
	at r.n.c.MonoSendMany$SendManyInner.run(MonoSendMany.java:322)
	at i.n.u.c.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at i.n.u.c.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:405)
	at i.n.c.e.EpollEventLoop.run(EpollEventLoop.java:338)
	at i.n.u.c.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:906)
	at i.n.u.i.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)

The exact reason is not yet known. It might be related to malformed headers, however we did not have this with Spring Boot 1.5.x.

### Steps to reproduce
I get it intermittently in production. We are currently trying to replicate the problem in the staging environment.

### Reactor Netty version
0.8.9

### JVM version (e.g. `java -version`)
11

### OS version (e.g. `uname -a`)
Ubuntu 16.04

**Comment by violetagg** [comment]
https://github.com/spring-cloud/spring-cloud-gateway/issues/1173

**Comment by ahmedyarub** [comment]
what information do you need?

**Comment by violetagg** [comment]
> We are currently trying to replicate the problem in the staging environment.
> what information do you need?

Were you able to replicate the problem

**Comment by ahmedyarub** [comment]
We could replicate another error related to sending a PUT packet without a body. It's not a bug in Reactory Netty. I think that the error I mentioned before happens only when there is a lot of traffic, which we can see only in production. Next week we will be deploying again and I'll post the updates here.

**Comment by smaldini** [comment]
Thanks a lot for the report @ahmedyarub , it seems that issue has been fixed (close listener could trigger an interruption of sending operation before it starts and caused this issue). Let's open a new one for the PUT issue - it doesn't seem unfamiliar so we'll be looking closely to it :)

**Comment by smaldini** [comment]
See https://github.com/reactor/reactor-netty/commit/d7267e1638a52edc5012c0422b9982a9ac9a0d8e

**Comment by ahmedyarub** [comment]
> Thanks a lot for the report @ahmedyarub , it seems that issue has been fixed (close listener could trigger an interruption of sending operation before it starts and caused this issue). Let's open a new one for the PUT issue - it doesn't seem unfamiliar so we'll be looking closely to it :)

It doesn't look like the error was related to the PUT method itself. The endpoint was replying erratically (it is based on Spring Boot 1.5.x). For the time being we solved the problem by asking all our clients to follow the specifications of our SDK requiring them to send all the data in the body.
Thanks
