### ISSUE TITLE
Migration guide from 0.7.x to 0.8.x

### ISSUE THREAD

**Issue by nictas** [reactor/reactor-netty#786]
This is more of a question/request, rather than a bug report, which is why I'm not following the template.

In short, I want to migrate a project (https://github.com/cloudfoundry/cf-java-client) to the latest version of reactor-netty, but I can't find a migration guide from 0.7.x to 0.8.x anywhere. I see that you have great notes for almost every release, but there's literally nothing about [0.8.0](https://github.com/reactor/reactor-netty/releases/v0.8.0.RELEASE). Have I missed something? If I haven't, is there any chance you could write a migration guide and publish it somewhere?

Finally, one other small question: Do you keep the project backwards compatible between different patch versions? For example, is there any way 0.8.27 could break the backwards compatibility or are such changes saved for 0.9.x?

Thanks!

**Comment by violetagg** [comment]
@nictas For the moment we have only [Reference Documentation](https://projectreactor.io/docs/netty/snapshot/reference/index.html)

Unfortunately there is no migration guide. However you can check:

this
https://github.com/reactor/reactor-netty/blob/0.7.x/src/test/java/reactor/ipc/netty/http/HttpTests.java

and this
https://github.com/reactor/reactor-netty/blob/0.8.x/src/test/java/reactor/netty/http/HttpTests.java

Also below you can find some slides about the differences in the API
https://www.youtube.com/watch?v=WGRaoGrLlBE

The change in the API between 0.7 and 0.8 was a major change and it was not possible to keep the compatibility.
The current process that we try to follow with 0.8 and 0.9 is: deprecate in 0.8 and provide a replacement and remove the deprecated API in 0.9.

I would suggest the following: take a look at the tests that I linked above and if you have questions ask on [Gitter](https://gitter.im/reactor/reactor-netty).

**Comment by violetagg** [comment]
cc @twoseat
