### ISSUE TITLE
HttpClient Wiretap Specify Log Level

### ISSUE THREAD

**Issue by gtomassi** [reactor/reactor-netty#789]
Many users will want to enable logging at a specified log level. Current implementation defaults to DEBUG always.

Suggested Enhancement:
Overload wiretap with an additional method that supports level as an input (eg wiretap(enable, level))

This is often useful when servers have standard log levels setup but want to temporarily enable logging for traffic without all the overhead of this library's other DEBUG level information. This is also more consistent with netty when adding a LoggingHandler to a pipeline.

**Comment by gtomassi** [comment]
See https://projectreactor.io/docs/netty/release/api/reactor/netty/http/client/HttpClient.html#wiretap-boolean-

**Comment by violetagg** [comment]
@gtomassi [HttpClient.wiretap(boolean)](https://projectreactor.io/docs/netty/release/api/reactor/netty/http/client/HttpClient.html#wiretap-boolean-)
is exposed for a convenience as it is used the most.

If you need more fine tuned wiretap you can use the methods on the tcp level

`httpClient.tcpConfiguration(tcpClient -> tcpClient.wiretap(...));`

[TcpClient wiretap methods](https://projectreactor.io/docs/netty/release/api/reactor/netty/tcp/TcpClient.html#wiretap-boolean-)

Is this what you need?

**Comment by violetagg** [comment]
I'm closing this, we can reopen it if the current API is not sufficient.
