### ISSUE TITLE
Add a way to modify the pipeline on servers

### ISSUE THREAD

**Issue by nename0** [reactor/reactor-netty#80]
Created from #78 

If you want to modify the pipeline on servers, you cannot use something like this, because the handler is invoked [asynchronous](https://github.com/reactor/reactor-netty/blob/master/src/main/java/reactor/ipc/netty/channel/ContextHandler.java#L236):
```java
httpServer.newHandler((httpServerRequest, httpServerResponse) ->
{
      httpServerRequest.context().addHandler(new HttpContentDecompressor());
      httpServerRequest.context().addHandler(new HttpContentCompressor());
      return handler.apply(httpServerRequest, httpServerResponse);
})
```
It will be too late when the handler is invoked, as the data might already be gone through the pipeline.
So it seems the only way to do this is the `afterChannelInit` option but from there you cannot access the `NettyContext.**handler**` or `ReactorNetty.**handler**` methods.

**Comment by smaldini** [comment]
I wonder if addHandler should return a Mono<Void> for this.
In general adding context in the IO thread will just tells the asynchronous block you linked to defer after current actions. 

You might observe the opposite issue in that some data have been consumed already beyond the headers and effectively adding an handler in http handler might prove too late and that could be a bug (we shouldn't consume until you subscribe to request.receive()).

**Comment by nename0** [comment]
Ok I now found a way to modify the pipeline. Maybe I can help a few people wanting to do the same: 
```
HttpServer.builder()
    .options(httpServerOptions ->
    {
        httpServerOptions.afterChannelInit(channel ->
        {
            ChannelOperations channelOperations = ChannelOperations.get(channel);
            channelOperations.addHandler(new HttpContentDecompressor());
        });
    }).build();
```
I don't know if this the intended method, so @smaldini Is the `ChannelOperations.get` intended to be public, like if this project gets modularized(Jigsaw) this method would be exported?

**Comment by simonbasle** [comment]
as another workaround, you can use the channel directly (`afterChannelInit(c -> c.pipeline().add(...))`) but you then need to take care where you put your handlers (see `NettyPipeline` for constant names for reactor-managed handlers).

There is some work to do around that part of the API and internal implementation though.
