### ISSUE TITLE
wiretap is not enable ,but still printing Read/Write bytes log

### ISSUE THREAD

**Issue by harish0000** [reactor/reactor-netty#804]
I have configured the pooled HttpClient as below
```
HttpClient httpClient = HttpClient.create().compress(true)
.tcpConfiguration(tcpClient -> tcpClient.proxy(proxy -> proxy.type(ProxyProvider.Proxy.HTTP)
               .address(new InetSocketAddress("xx.xxx.xx.xx", xxx))));
ReactorClientHttpConnector connector = new ReactorClientHttpConnector(httpClient);
this.webClient = webclientBuilder.clientConnector(connector).baseUrl(url)
.filter(QuotraInterfaceUtil.logRequest()).build();
```

Logging as below
```
logging:
  level:
    reactor.netty: debug
```

### Expected behavior
As i didn't enable wiretap ,it should not print the logs

### Actual behavior
wiretap is not enabled but its still printing the Read/Write bytes 

**Example**

> 2019-08-02 03:40:41,998 DEBUG i.n.u.i.l.AbstractInternalLogger [reactor-http-epoll-4] [id: 0xb41b0f64, L:/xx.xxx.xxx.xxx:xxxx - R:xx.xxx.xx.xx/xx.xxx.xx.xx:xxxx] READ: 692B
>          +-------------------------------------------------+
>          |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
> +--------+-------------------------------------------------+----------------+
> |00000000| b7 fc bc 76 22 1c 1c 91 b2 75 a6 16 61 b2 c8 d3 |...v"....u..a...|
> |00000010| e5 d5 80 65 7b 56 49 70 3c df 9e 4b 1b 7e a0 57 |...e{VIp<..K.~.W|
> |00000020| b9 3d 79 00 3d 00 34 56 30 b3 46 7a eb cb 59 94 |.=y.=.4V0.Fz..Y.|

### Reactor Netty version :
spring-boot-starter-webflux: 2.1.6.RELEASE)  0.8.9.RELEASE

### JVM version : 
openjdk version "11.0.4"

### OS version: 
Linux 4.15.0-52-generic  56~16.04.1-Ubuntu

**Comment by violetagg** [comment]
#805 this should fix the issue
