### ISSUE TITLE
How can I write a log outgoing a raw HTTP Request Body?

### ISSUE THREAD

**Issue by aukhatov** [reactor/reactor-netty#813]
Hello guys!
I have a little trouble. Can you help me?
I want to write a log my HTTP Requests in raw format. These requests provided by [spring webflux ](https://docs.spring.io/spring/docs/current/spring-framework-reference/web-reactive.html#webflux-client)`org.springframework.web.reactive.function.client.WebClient` over `reactor.netty.http.client.HttpClient`.

### Building Web Client with `wiretap(true)`
```java
WebClient.builder()
                .clientConnector(new ReactorClientHttpConnector(
                        HttpClient.create().wiretap(true)
                ))
```

### Enable Log Level

`<logger name="reactor.netty.http.client" level="TRACE"/>`

### Result

```log
2019-08-08 08:57:04.283 DEBUG 20761 --- [or-http-epoll-3] reactor.netty.http.client.HttpClient     : [id: 0x6547c732, L:/127.0.0.1:47144 - R:localhost/127.0.0.1:8081] WRITE: 370B
         +-------------------------------------------------+
         |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
+--------+-------------------------------------------------+----------------+
|00000000| 7b 22 68 64 72 22 3a 7b 22 63 6c 69 65 6e 74 22 |{"hdr":{"client"|
|00000010| 3a 7b 22 69 64 22 3a 22 6e 67 65 6e 69 65 22 2c |:{"id":"ngenie",|
|00000020| 22 70 77 64 22 3a 22 73 75 70 65 72 2d 73 65 63 |"pwd":"super-sec|
|00000030| 72 65 74 2d 70 77 64 22 2c 22 73 65 72 76 69 63 |ret-pwd","servic|
|00000040| 65 69 64 22 3a 6e 75 6c 6c 2c 22 72 65 71 75 65 |eid":null,"reque|
|00000050| 73 74 6d 6f 64 65 22 3a 6e 75 6c 6c 7d 2c 22 76 |stmode":null},"v|
|00000060| 65 72 22 3a 22 33 2e 32 2e 30 22 7d 2c 22 73 6c |er":"3.2.0"},"sl|
|00000070| 69 72 22 3a 7b 22 6d 73 69 64 73 22 3a 7b 22 6d |ir":{"msids":{"m|
|00000080| 73 69 64 4c 69 73 74 22 3a 5b 7b 22 76 61 6c 75 |sidList":[{"valu|
|00000090| 65 22 3a 22 37 39 31 39 33 34 35 32 37 38 35 22 |e":"79193452785"|
|000000a0| 2c 22 74 79 70 65 22 3a 22 4d 53 49 53 44 4e 22 |,"type":"MSISDN"|
|000000b0| 2c 22 65 6e 63 22 3a 22 41 53 43 22 7d 5d 7d 2c |,"enc":"ASC"}]},|
|000000c0| 22 65 71 6f 70 22 3a 6e 75 6c 6c 2c 22 67 65 6f |"eqop":null,"geo|
|000000d0| 49 6e 66 6f 22 3a 6e 75 6c 6c 2c 22 6c 6f 63 54 |Info":null,"locT|
|000000e0| 79 70 65 22 3a 6e 75 6c 6c 2c 22 70 72 69 6f 22 |ype":null,"prio"|
|000000f0| 3a 6e 75 6c 6c 2c 22 70 75 73 68 61 64 64 72 22 |:null,"pushaddr"|
|00000100| 3a 6e 75 6c 6c 2c 22 73 65 72 76 69 63 65 43 6f |:null,"serviceCo|
|00000110| 76 65 72 61 67 65 22 3a 6e 75 6c 6c 2c 22 76 65 |verage":null,"ve|
|00000120| 72 22 3a 22 33 2e 32 2e 30 22 2c 22 72 65 73 54 |r":"3.2.0","resT|
|00000130| 79 70 65 22 3a 22 53 59 4e 43 22 7d 2c 22 65 6d |ype":"SYNC"},"em|
|00000140| 65 4c 69 72 22 3a 6e 75 6c 6c 2c 22 74 6c 72 72 |eLir":null,"tlrr|
|00000150| 22 3a 6e 75 6c 6c 2c 22 74 6c 72 73 72 22 3a 6e |":null,"tlrsr":n|
|00000160| 75 6c 6c 2c 22 76 65 72 22 3a 22 33 2e 32 2e 30 |ull,"ver":"3.2.0|
|00000170| 22 7d                                           |"}              |
+--------+-------------------------------------------------+----------------+
```
There is not RAW format. It's some implementing  or overriding `toString()`.
Because I my HTTP Request body is **XML**.

### What I want to see
I want to see RAW HTTP Request.

Example:
```log
POST /api/v1/messages HTTP/1.1
Host: localhost:8080
Content-Type: application/xml

<xml>
...
</xml>
```

## Environment 

- `spring-webflux:5.1.8`
- `reactor-netty:0.8.9`
- `logback-core:1.2.3`
- `logback-classic:1.2.3`

**Comment by violetagg** [comment]
@aukhatov Something like this? https://stackoverflow.com/questions/55275393/spring-webflux-reactor-netty-http-request-response-hex-dump/55281347#55281347

**Comment by aukhatov** [comment]
> @aukhatov Something like this? https://stackoverflow.com/questions/55275393/spring-webflux-reactor-netty-http-request-response-hex-dump/55281347#55281347

Hello @violetagg !
Unfortunately this approach doesn't work (((

**Comment by aukhatov** [comment]
I **updated** the issue description.

**Comment by violetagg** [comment]
This is the body provided by Spring WebFlux. May be you need different body encoder.
Ask your question here https://stackoverflow.com/tags/spring-webflux

**Comment by sxganapa** [comment]
I need to log  the input request  coming to Netty 2.4  server. What property I need to add to application.conf or logback.xml

**Comment by violetagg** [comment]
@sxganapa What about something like this

```
@Component
public class MyNettyWebServerCustomizer
        implements WebServerFactoryCustomizer<NettyReactiveWebServerFactory> {
    @Override
    public void customize(NettyReactiveWebServerFactory factory) {
        factory.addServerCustomizers(httpServer -> httpServer.wiretap(true));
    }
}
```

In the example `httpServer.wiretap(true)` enables the hex dump. If you do not want a hex dump but plain text then you can use `httpServer.wiretap("category", LogLevel.DEBUG, AdvancedByteBufFormat.TEXTUAL)`

**Comment by jnustud** [comment]
Which version would support this
`httpServer.wiretap("category", LogLevel.DEBUG, AdvancedByteBufFormat.TEXTUAL)`

**Comment by violetagg** [comment]
@jnustud For questions please use [Gitter](https://gitter.im/reactor/reactor-netty) or [stackoverflow.com](https://stackoverflow.com/questions/tagged/reactor-netty)

`httpServer.wiretap("category", LogLevel.DEBUG, AdvancedByteBufFormat.TEXTUAL)`
is available in Reactor Netty 1.0.x versions

**Comment by vinceve** [comment]
@violetagg I tried this on spring boot 2.5.0 with Netty 1.0.7 and it seem sonly to log the headers. Not the fully body like the HEX dump.

**Comment by violetagg** [comment]
@vinceve Let's track this in a new issue. OK?

**Comment by aukhatov** [comment]
After 2 years. Awesome open source!

**Comment by ghilainm** [comment]
@violetagg Any recommended way of logging the textual representation of request body this in the end? I don't see the resolution in this ticket :).

**Comment by violetagg** [comment]
@ghilainm If you observe a problem, please open a new issue with a reproducible example. Thanks.
