### ISSUE TITLE
followRedirect is not actually true by default

### ISSUE THREAD

**Issue by nictas** [reactor/reactor-netty#816]
## Expected Behavior
The Javadoc of `reactor.netty.http.client.HttpClient.followRedirect(boolean)` says that the default value is true and therefore redirects should be followed automatically. 

## Actual Behavior
Redirects are not actually followed by default and one must call `.followRedirect(true)` explicitly.

## Steps to Reproduce
```java
    public static void main(String[] args) {
        String response = HttpClient.create()
                                    .request(HttpMethod.GET)
                                    .uri("bit.ly/2yXfwop") // Redirects to https://postman-echo.com/get
                                    .responseContent()
                                    .aggregate()
                                    .asString()
                                    .block();
        System.out.println(response);
    }
```
The piece of code above prints the following:
```
<html>
<head><title>Bitly</title></head>
<body><a href="https://postman-echo.com/get">moved here</a></body>
</html>
```

## Possible Solution
Change the Javadoc to:
```
	/**
	 * Specifies whether HTTP status 301|302|307|308 auto-redirect support is enabled.
	 *
	 * @param followRedirect if true HTTP status 301|302|307|308 auto-redirect support
	 *                       is enabled, otherwise disabled (default: false).
	 * @return a new {@link HttpClient}
	 */
```
Or change the default value, so that it's actually `true` by default.

## Your Environment
* Reactor version(s) used: 0.8.10.RELEASE
* Other relevant libraries versions (eg. `netty`, ...): Netty 4.1.38.Final
* JVM version (`javar -version`):
```
java version "1.8.0_212"
Java(TM) SE Runtime Environment (build 1.8.0_212-b10)
Java HotSpot(TM) 64-Bit Server VM (build 25.212-b10, mixed mode)
```
* OS and version (eg `uname -a`):
```
MSYS_NT-10.0 SOFN34229528A 2.11.2(0.329/5/3) 2018-11-10 14:38 x86_64 Msys
```

**Comment by violetagg** [comment]
Good catch
Would you like to create a PR?

**Comment by nictas** [comment]
Yes. Just let me know which of the two possible solutions to implement. Change the Javadoc or change the default value?

**Comment by violetagg** [comment]
Change javadoc to point that it is false by default and do the PR against 0.8.x branch

**Comment by violetagg** [comment]
I’m keeping this opened in order to merge it to master
