### ISSUE TITLE
Subscribing to TCP Mono<InputStream>blocks/never occurs

### ISSUE THREAD

**Issue by westonlast** [reactor/reactor-netty#82]
```java
TcpServer tcpServer = TcpServer.create(port);
Mono<? extends NettyContext> nettyContextMono = tcpServer.newHandler((nettyInbound, nettyOutbound) -> {
	Mono<InputStream> mono = nettyInbound.receive().aggregate().asInputStream();
	InputStream inputStream = mono.block();    //never returns
        mono.subscribe(inputstream -> { ... });    //returns immediately
        return nettyOutbound;    //return some dummy; returning closes the connection
});
```
I'm trying to send the InputStream to an external parser and then emit values to a Flux.  I can't get the InputStream from the connection's Flux/Mono.

**Comment by smaldini** [comment]
You cannot block inside a functional callback (especially recursively like this), this leads to deadlocking and it must be done under careful use of thread jump operator (publishOn or subscribeOn + Scheduler).
You should return the Mono directly as it will close only when server remotely close (and use doOnNExt instead of subscribe).

**Comment by westonlast** [comment]
Thank you for your help.  I figured that block() call was tripping it up after the discussion here:
https://github.com/reactor/reactor-core/issues/570

Although it seems like the InputStream should arrive immediately no matter the call since the connection has been made, and it is already a "stream..."

Unfortunately the issue in Reactor Core is blocking my use of Reactor, but I plan to try out your suggestion if that gets resolved.

**Comment by smaldini** [comment]
Will close o rack on reactor-core directly.

**Comment by westonlast** [comment]
"to rack"

https://en.wiktionary.org/wiki/rack#Verb

3. To cause (someone) to suffer pain.
6. (slang) To strike a male in the groin with the knee.

Good to know that I'm appreciated as a member of the vibrant community!

**Comment by westonlast** [comment]
The return value must be Publisher<Void>:

"cannot convert from Mono<InputStream> to Publisher<Void>"

How am I supposed to "return the Mono directly as it will close only when server remotely close?"
