### ISSUE TITLE
Data After End of Packet is Considered Another Packet

### ISSUE THREAD

**Issue by ahmedyarub** [reactor/reactor-netty#833]
We have been getting random 405 Method Not Allowed errors from an endpoint only when we use a Spring Cloud Gateway based proxy. After very lengthy investigation I could capture the some sample packets and reproduce the behavior. The packets, for a reason beyond my understanding, have additional data after the last \r\n. In Spring Cloud Zuul, the proxy would simply ignore these additional data. Spring Cloud Gateway would send this data in a separate packet. The receiving endpoint would receive this packet and not process it because it doesn't have CRLF at the end. Then, it woul receive the next packet and concatenate it with the previous packet. This would yield something like this "garbagePUT HTTP/1.1...", and this causes the 405 error. Not that the requests do not have a "Content-Length" header.

EDIT: I forgot to say that this constitutes a security risk and sending corrupted packets can effectively corrupt packets sent by other clients!

## Expected Behavior
Either reject or truncate the packet after the last CRLF.

## Actual Behavior
The packet is split into two packets.

## Steps to Reproduce
Send a packet with data after the last CRLF to Spring Cloud Gateway.

## Your Environment
Windows 10 and Ubuntu 18.04
Spring Cloud Gateway 2.1.2
OpenJDK 11.0.3

**Comment by ahmedyarub** [comment]
Let me explain with more details then:
The data comes from one of our clients, it passes through some proxy before reaching our API Gateway. The corrupted data is either coming from the client or from our proxy, we are still investigating that. However, we still have this very bad security vulnerability where a packet from Client A that has additional data after the last CRLF in the packet would be added to the packet from Client B. Can you imagine how serious this vulnerability is?
Now regarding Zuul: I didn't make thorough tests yet, but our Zuul based proxy has been online for more than a year getting all kinds of packets and we never had this problem before. I can assume that it is simply truncating the packets since we didn't get any complaint from our client.
As for the 405: it is a random error generated by the endpoint due to appending the remaining split packet to the next one. Let me give you a more detailed example:

Suppose that you have an incoming packet that looks like this:
PUT /service/endpoint HTTP/1.1\r\n
\r\n
garbage

Now obviously, everything after the second \r\n is unwanted. Suppose that after that we receive a valid packet from the same or another client that looks like this
PUT /service/endpoint HTTP/1.1\r\n
\r\n

The result of this is that Spring Cloud Gateay would generate 3 packets:
1:
PUT /service/endpoint HTTP/1.1\r\n
\r\n

2:
garbage

3:
PUT /service/endpoint HTTP/1.1\r\n
\r\n

Now the endpoint will receive and process packet 1, then receive the second packet and NOT process it because it does not end with \r\n. When it receives the third packet it would concatenate it with the second packet resulting in a packet that looks like this:
garbagePUT /service/endpoint HTTP/1.1\r\n
\r\n

Then it would parse the headers of that packet. This would, obviously, produce a 405 error because garbagePUT is not a known HTTP method. However, malicious packets can be crafted to alter the packets of other users in a way that might produce a data leak, DoS, ...etc

**Comment by smaldini** [comment]
Hey @ahmedyarub I'm not sure I understood the vulnerability (or what if Client A and B are different machines or different request). Would it be possible to contact us directly so we triage it as a security issue which I would kindly ask to submit to the email address provided by https://pivotal.io/security.
If you feel the issue is more a bug and we are not dropping/ignoring packets until the next HTTP verb is detected, then that's something we can investigate publicly.

**Comment by ahmedyarub** [comment]
Spring Cloud Gateway is basically a proxy based on Webflux and Reactor Netty that receives HTTP requests, and then builds new ones after being modified by the filters. The end of the headers section of the HTTP packet is marked by an empty line. When the Content-Length is 0 or doesn't exist, the empty line is considered the to be the end of the HTTP request.
The problem that happened with us is the following:
A client sent additional data after the empty line but within the same packet. What Spring Cloud Gateway did was creating two packets out of this one. The second packet simply contains a bunch of characters. As the endpoint received the second packet it was simply buffered awaiting an empty line. Then, a valid packet was sent to the SCG by another client. This packet was sent as-is to the endpoint. The endpoint, however, appended this valid packet to the data already buffered, effectively creating a packet that is made of the data coming from the two clients! 
Ex:
Client 1 sent:
A\r\n
\r\n
B

Client 2 sent:
C\r\n
\r\n

Spring Cloud Gateway produces 3 packets:
A\r\n
\r\n

B

C\r\n
\r\n

Endpoint "sees" 2 packets:
A\r\n
\r\n

BC\r\n
\r\n

I do have a dump from our production servers showing exactly what happened. We can discuss them on a private communication channel (voice, video and/or chatting group) since it has some sensitive data.

**Comment by ahmedyarub** [comment]
Is it clear for you? Do you need more information?

**Comment by smaldini** [comment]
@violetagg and/or me will try to contact you offline for more precision if its sensitive. What I'm failing to look at is how 2 different clients can be a problem, unless its one client doing 2 different requests (or a pooled client) ? In the case the 2 clients mean 2 consecutive connection users producing 3 http messages should not be a security issue, but just an issue (client side first then server). What we can do then is make sure we drop noise packets and we are already trying to do that but something might be amiss.

**Comment by ahmedyarub** [comment]
It is a security issue because the second part of the packet sent by the first client is appended to the packet of the second client. This means that an attacker can craft malicious packets which would augment the packets sent by another client. The other client might be authenticated and have different permissions than the first client. This way, the first client will be able impersonate any other client that might happen to be sending simultaneous packets.
We have tested this theory thoroughly and we have solid proof that this happens consistently. Once you contact me I'll be sharing the evidence with you and explain the problem thoroughly.

**Comment by violetagg** [comment]
@ahmedyarub 
https://github.com/spring-cloud/spring-cloud-gateway/commit/0d2b87af30a86e10ce1e42bd1415f9c90ce8c5e5#diff-5b9ae149fff7a5250b6aec43cc2bd370

#875

**Comment by ahmedyarub** [comment]
I have just tested with Spring Boot 2.2.2 and Hoxton.RELEASE (which come with Reactor Netty 0.9.2.RELEASE), and it's still generating multiple packets out of a single one with extra data at the end.

**Comment by violetagg** [comment]
reopen to check again

**Comment by violetagg** [comment]
@ahmedyarub can you test with the latest releases: 
Reactor Netty 0.9.4.RELEASE
Netty 4.1.44.Final

**Comment by violetagg** [comment]
Closing this. We can reopen it when there is more information.
