### ISSUE TITLE
Netty giving SSL handshaking error while connecting to SNI enabled end points

### ISSUE THREAD

**Issue by bipin-naggarro** [reactor/reactor-netty#838]
## Expected Behavior

I expect Netty to successfully complete SSL handshaking and establish HTTPS connection
## Actual Behavior

Netty fails during SSL handshaking 

## Steps to Reproduce

We are using Netty version 4.1.5.Final .  Please advise if SNI issue is resolved in any version .

I am using following dependencies .
<netty.version>4.1.5.Final</netty.version>

<dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-codec</artifactId>
            <version>${netty.version}</version>
        </dependency>
        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-common</artifactId>
            <version>${netty.version}</version>
        </dependency>
        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-handler</artifactId>
            <version>${netty.version}</version>
        </dependency>
        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-buffer</artifactId>
            <version>${netty.version}</version>
        </dependency>
        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-transport</artifactId>
            <version>${netty.version}</version>
        </dependency>
        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-resolver</artifactId>
            <version>${netty.version}</version>
        </dependency>
        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-handler-proxy</artifactId>
            <version>${netty.version}</version>
        </dependency>
        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-codec-socks</artifactId>
            <version>${netty.version}</version>
        </dependency>
        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-codec-http</artifactId>
            <version>${netty.version}</version>
        </dependency>

I am getting following error logs

INFO   | jvm 1    | main    | 2019/09/05 10:41:48.322 | 3140: 06 03 55 1D 20 04 19 30   174 30 0B 06 09 600 86 48  nioEventLoopGroup-2-1, READ: TLSv1.2 Alert, length = 2
INFO   | jvm 1    | main    | 2019/09/05 10:41:48.322 | ..U. ..20 01  ..4....C..........
INFO   | jvm 1    | main    | 2019/09/05 10:41:48.322 | 00B0: 00 [Raw read]: length = 87
INFO   | jvm 1    | main    | 2019/09/05 10:41:48.323 | 00000: 02 00 00 53 03 03 AB CB   96 FB 26 AD 94 68 06 71  D...S...nioEventLoopGroup-2-1 9F EF  H8..., RECV TLSv1.2 ALERT:  ......&..h.q
INFO   | jvm 1    | main    | 2019/09/05 10:41:48.329 | 0010: 4C 84 14 10 76 94 8F BC   D5 4F 59 59 78 C7 1D 29 0 L...v.0...OYYx..) 0D 00 16 00 14 06   03 06 01 05 03 05 01: 30 5F 02 17 38 0A 1D 4E .98...fatal, 0.D.handshake_failure
INFO   | jvm 1    | main    | 2019/09/05 10:41:48.329 |   48 8A 69 B0 62 E4 75 00  0_..8..NH.i.nioEventLoopGroup-2-1, fatal: engine already closed.  Rethrowing javax.net.ssl.SSLException: Received fatal alert: handshake_failure
INFO   | jvm 1    | main    | 2019/09/05 10:41:48.329 |  04  .....nioEventLoopGroup-2-1, fatal: engine already closed.  Rethrowing javax.net.ssl.SSLException: Received fatal alert: handshake_failure
INFO   | jvm 1    | main    | 2019/09/05 10:41:48.329 | 
INFO   | jvm 1    | main    | 2019/09/05 10:41:48.329 | 0020: BD 02 nioEventLoopGroup-2-1, called closeOutbound()
INFO   | jvm 1    | main    | 2019/09/05 10:41:48.329 | ...b...`.H
INFO   | jvm 1    | main    | 2019/09/05 10:41:48.329 | 0350: 01 86 FD 6C..
INFO   | jvm 1    | main    | 2019/09/05 10:41:48.329 | 0020: DF 4F 56 6D AE D7 C6 22   06 6F 28 01 02 30 08   06 06 67 81 0C 01 02 01  ...l........u.
INFO   | jvm 1    | main    | 2019/09/05 10:41:48.329 | 1CE0: C1 24 nioEventLoopGroup-2-1, closeOutboundInternal()
INFO   | jvm 1    | main    | 2019/09/05 10:41:48.329 | CF 33 DF nioEventLoopGroup-2-12, SEND TLSv1.2 ALERT:  warning, .
INFO   | jvm 1    | main    | 2019/09/05 10:41:48.329 | 00C0: 03 04 01 04 02 02 03 02   01 02 02 00 107... 96 65 79g 74 4A  .OVm...".o(.eytJ
INFO   | jvm 1    | main    | 2019/09/05 10:41:48.329 | 0030: 6D 16 FD 70 00 00 00  ..description = close_notify
INFO   | jvm 1    | main    | 2019/09/05 10:41:48.329 | E B0 88 15 E2 07   00 73 E2 63 05 719 43 0A 7 .$.......snioEventLoopGroup-2-1, WRITE: TLSv1.2 Alert, length = 2
INFO   | jvm 1    | main    | 2019/09/05 10:41:48.329 | .. E9 C9 E2.....
INFO   | jvm 1    | main    | 2019/09/05 10:41:48.329 | 0360:  B4   ACnioEventLoopGroup-2-1, called closeInbound()
INFO   | jvm 1    | main    | 2019/09/05 10:41:48.329 | ........nioEventLoopGroup-2-1, fatal: engine already closed.  Rethrowing javax.net.ssl.SSLException: Inbound closed before receiving peer's close_notify: possible truncation attack?
INFO   | jvm 1    | main    | 2019/09/05 10:41:48.330 | .c.qC.
INFO   | jvm 1    | main    | 2019/09/05 10:41:48.330 | 1CF0: 30 1C 30 31 64 C1 68 06   21  20 17   23 3B 80 FC 41 CB3 92 BA  ...3.. .#;..A...
INFO   | jvm 1    | main    | 2019/09/05 10:41:48.330 | ....
INFO   | jvm 1    | main    | 2019/09/05 10:41:48.330 | 00D0: 00 00 2C 00 2A 00 00 27   6D 6F 6E 69 74 6F 72 69  ..,.*..'monitori
INFO   | jvm 1    | main    | 2019/09/05 10:41:48.330 | 00E0: 6E 67 2E 61 70 43 81 18 5F 75 A4 98  m.3.p.....C.._u..
INFO   | jvm 1    | main    | 2019/09/05 10:41:48.330 | 0040: 500 97 80 8B CC 13 1C 2D 73 6F   75 74 68 65 61 73 74 2D 0 ng.ap-southeast-
INFO   | jvm 1    | main    | 2019/09/05 10:41:48.330 | 00 92 15 92 E2 1F 1F  0.01d0.h.!0......
INFO   | jvm 1    | main    | 2019/09/05 10:41:48.330 | 1D00: E4 11 2F 78 81 DC   F7 B9 F9 19 21 68 4D 62  P...........!hMb
INFO   | jvm 1    | main    | 2019/09/05 10:41:48.330 | 0050: AA 31 29 75 06 08 2B 06 01 05   05 AB C6 01 9C 65 23 8E D6   81 2C 7C E0 03 2C A6 D3  ../x.#...,...,..
INFO   | jvm 1    | main    | 2019/09/05 10:41:48.330 | 1D10: 19 FA3 3B 10 38 44 F9 0F0   27 76 59 0B ACF FC 81 B6  ..;.8D0..'vY.....
INFO   | jvm 1    | main    | 2019/09/05 10:41:48.330 |   07 01 01 04 69 30 67  0u..+.  DF 3C CE1 3E F8 91 CE 19  .1)....e.<.>..: F5 33 7C D4 C6 F6 18 93   F5 43 E5 8E 43 B4 06 47  .3.......C..C..G
INFO   | jvm 1    | main    | 2019/09/05 10:41:48.331 | WARN  [nioEventLoopGroup-2-1] [NettyClient] error on releasing channel
INFO   | jvm 1    | main    | 2019/09/05 10:41:48.331 | java.lang.IllegalStateException: Channel is unhealthy not offering it back to pool
INFO   | jvm 1    | main    | 2019/09/05 10:41:48.331 | 	at io.netty.channel.pool.SimpleChannelPool.releaseAndOffer(...)(Unknown Source) ~[netty-transport-4.1.5.Final.jar:4.1.5.Final]

```java
@Test
public void repoCase() {

}
```

## Your Environment
coming in DEV , QA environment 

* Reactor version(s) used:
* Other relevant libraries versions (eg. `netty`, ...):
* JVM version (`javar -version`): java version "1.8.0_211"
* OS and version (eg `uname -a`): Windows 10

**Comment by smaldini** [comment]
is this a Netty issue or a reactor-netty issue ? in any case the netty version seems outdated.

**Comment by bipin-naggarro** [comment]
@smaldini I am using Netty libraries . can you please advise which version of Netty could fix this issue . I think if Netty supply host name during handshaking then SNI will be identified and appropriate certificate will be validated .

**Comment by smaldini** [comment]
You should try 4.1.39 (https://netty.io/news/2019/08/13/4-1-39-Final.html)
If you still face an issue after upgrade please open in the netty project tracker https://github.com/netty/netty/
