### ISSUE TITLE
how can I release the connection to channelPool create by ConnectionProvider, but close the connection

### ISSUE THREAD

**Issue by shanzhaigegeyml** [reactor/reactor-netty#849]
how can I release the connection to channelPool create by ConnectionProvider, but close the connection

**Comment by violetagg** [comment]
@shanzhaigegeyml This belongs to [Gitter](https://gitter.im/reactor/reactor-netty) or [StackOverflow](https://stackoverflow.com/questions/tagged/reactor-netty)

I do not know your scenario and when you want to close the connection, but you can invoke `Connection#dispose`

**Comment by shanzhaigegeyml** [comment]
the method Connection#dispose will close the connection  on tcp protocol.  I want to release the connection to ConnectionProvider 's channelPool,  so the next time I can get it from ConnectionProvider 's channelPool, but not to create a new tcp connection.
