### ISSUE TITLE
[Question]About the ConnectionObserver

### ISSUE THREAD

**Issue by Liyixin95** [reactor/reactor-netty#861]
Why not use a specific call back method such as `onConnected `and `onConfigured `and so on.Then the `onStageChange` could be split into several specific method and remove the overhead of `State`
judgment.

**Comment by violetagg** [comment]
The idea was to be able add more states in the future.
Also while `ConnectionObserver.State` represents the states on TCP level, we have additional states for the HTTP client and the HTTP server.
https://github.com/reactor/reactor-netty/blob/master/src/main/java/reactor/netty/http/client/HttpClientState.java#L26
https://github.com/reactor/reactor-netty/blob/master/src/main/java/reactor/netty/http/server/HttpServerState.java#L25

However you can use the lifecycle callbacks:

On client level
https://projectreactor.io/docs/netty/release/reference/index.html#_lifecycle_callbacks_2
https://projectreactor.io/docs/netty/release/api/reactor/netty/http/client/HttpClient.html#doAfterRequest-java.util.function.BiConsumer-

On server level
https://projectreactor.io/docs/netty/release/reference/index.html#_lifecycle_callbacks

**Comment by Liyixin95** [comment]
The more state been add, The more overhead of judgment will be cast...And I think put all the branch in one method is less efficient...I could provide a PR and some benchmark if you don‘t mind.

**Comment by violetagg** [comment]
yes sure go ahead

Thanks
Violeta

**Comment by Liyixin95** [comment]
@violetagg I have tried the specify call back method these days.Changing the `onStateChange` to the specify one in the runtime is quite easy but it's very complex in set up time...I guess you may not like this huge modify...

**Comment by violetagg** [comment]
Ok I understand

Thanks
