### ISSUE TITLE
[HttpServer] HttpPredicate$UriPathTemplate can cause OOM

### ISSUE THREAD

**Issue by AntonGabov** [reactor/reactor-netty#866]
## Expected Behavior
`HttpPredicate$UriPathTemplate` shouldn't cause OOM.

## Actual Behavior

`HttpPredicate$UriPathTemplate` keeps track of all incoming uris in variable `HashMap<String, Matcher> matchers`, which leads to OOM.

## Steps to Reproduce

Try to use small java heap to get the OOM faster. Also run java app with parameters: `-XX:+HeapDumpOnOutOfMemoryError` and `-XX:HeapDumpPath=<your_path>`
- create `HttpServer` 
- create a route, eg. `/api/devices/{id}`
- try to generate as many UNIQUE uris as you can, eg. `/api/devices/1`, `/api/devices/2` and so on
- if you don't want to wait for OOM, you can use `jmap`, `jcmd` or `JVisualVM` to capture the heap dump
- in heap dump you'll notice that the variable `HashMap<String, Matcher> matchers` in the class `HttpPredicate$UriPathTemplate` contains all incoming requests

## Possible Solution

Instead of HashMap it's better to use LRU cache via LinkedHashMap. It's a good and simple solution as:
1. If there is a small range of possible uris, all of them will be cached
2. If there is a large range of possible uris, only the last uris will be kept in the variable `matchers`

## Your Environment

* Reactor-netty version: 0.8.11.RELEASE 
* JVM version: openjdk version "11.0.2" 2019-01-15
* OS and version: CentOS Linux 7 (Core) 3.10.0-693.5.2.el7.x86_64 x86_64

**Comment by smaldini** [comment]
Preliminary fix on - https://github.com/reactor/reactor-netty/commit/fe6653fac44df16664bdd0628ad56cd142175bca 

I think it's worth opening a separate issue to improve the fix with an LRU cache while we have the Oom covered now. If you don't agree feel free to reopen this one.
