### ISSUE TITLE
Close channel using reactor's api

### ISSUE THREAD

**Issue by jonhkr** [reactor/reactor-netty#87]
Is there a way to close the connection of the client using reactor's api?

The only way I found was by accessing the netty channel and calling close (`in.context().channel().close()`) but I think that is leaking some internals. I may be a problem because I can call the blocking method `.await()` of the future returned by the `.close()` method.

**Comment by mostroverkhov** [comment]
There is `NettyContext.dispose()` which does not expose underlying `Channel` . `NettyContext` itself is available both inside handler function as `in.context()`,  and as return value `TcpClient.newHandler`: `Mono<NettyContext>`

**Comment by jonhkr** [comment]
I tried calling `in.context().dispose` but it does not close the connection, it is not the same as calling `in.context().channel().close().await()`.

This is what I'm doing:
```Java
in.receive()
    .asString()
    .subscribe(m -> {
        if (m.equals("D\r\n")) {
            try {
                in.context().channel().close().await();
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
        }
    });
```

In this example when I send the message `D` using `telnet` I get the message `Connection closed by foreign host.` which is the correct behavior, but if i use `in.context().dispose()` I don't get any message at all and the connection is not closed.

**Comment by mostroverkhov** [comment]
Indeed, for Tcp disposal operation is noop as seen in [code](https://github.com/reactor/reactor-netty/blob/master/src/main/java/reactor/ipc/netty/channel/ChannelOperations.java#L334-L336). That is either intention or mistake (I am not that familiar with codebase, but at least `HttpClientOperations`  closes its channel). Also, the function you provide in handler returns `Publisher`, and underlying connection is released as soon as that `Publisher` completes - that way you can close channel conditionally.

**Comment by simonbasle** [comment]
@jonhkr does [this commit](https://github.com/reactor/reactor-netty/commit/d9d956393428977b75939b95a1e538aadefe6de5) fix the issue for you?

**Comment by jonhkr** [comment]
I'm not sure if it does. As I understood the commit is related to starting/stopping the server and I'm trying to close a connection conditionally.
