### ISSUE TITLE
NPE in bootstrap config localhost TcpClient

### ISSUE THREAD

**Issue by DenisTunin** [reactor/reactor-netty#871]
## Expected Behavior

Should return new ChannelBindException with message

## Actual Behavior

NullPointerException when executed `ChannelBindException(bootstrap.config().localAddress().toString(), -1, cause)`
## Steps to Reproduce

```java
@Test
public void repoCase() {
   assertNotNull(TcpClient.DEFAULT_BOOTSTRAP.config().localAddress());
}
```

* Reactor version(s) used:
* Other relevant libraries versions (eg. `netty`, ...):
Spring-boot 2.2.0.RELEASE, reactor-netty 0.9.0.RELEASE, netty-* 4.1.42.Final
* JVM version (`javar -version`):
11.0.2
* OS and version (eg `uname -a`):
Windows 10 Enterprise

**Comment by violetagg** [comment]
@DenisTunin With the provided test case it is expected that `localAddress` is NULL. You didn't configure any `localAddress`

`io.netty.bootstrap.AbstractBootstrapConfig#localAddress`
```
    /**
     * Returns the configured local address or {@code null} if non is configured yet.
     */
    public final SocketAddress localAddress() {
        return bootstrap.localAddress();
    }
```

The correct test case is the following

```

	@Test
	public void repoCase() {
		//localAddress is not configured => expected NULL
		assertNull(
				TcpClient.DEFAULT_BOOTSTRAP
						.config()
						.localAddress());

		//localAddress is configured => expected NOT NULL
		assertNotNull(
				TcpClient.DEFAULT_BOOTSTRAP
						.localAddress(12120)
						.config()
						.localAddress());

		//TCP Client is connected, localAddress => expected NOT NULL
		Connection connection =
				TcpClient.create()
						.host("google.com")
						.port(80)
						.connectNow();
		assertNotNull(
				connection.channel()
						.localAddress());

		connection.disposeNow();
	}
```

**Comment by violetagg** [comment]
I'm closing this one, we can reopen it if it is necessary.
