### ISSUE TITLE
Calling traditional SOAP/WSDL Service over netty/rector

### ISSUE THREAD

**Issue by hmble2** [reactor/reactor-netty#872]
My Service provides and consumes a bunch of services most of them are REST and using reactor on the top of netty working just fine which I absolutely love :). Recently, learnt that it needs to consume/call additional SOAP/WSDL service. Could calling SOAP/WSDL over netty is possible (wants to avoid Servlet Container if possible) ? What are the options. Thanks !

**Comment by violetagg** [comment]
@hmble2 We do not provide anything out of the box that can solve your use case.
