### ISSUE TITLE
Websocket server send close with code and reason ,but the client cannot receive the real 'code and reason'

### ISSUE THREAD

**Issue by zzd0058** [reactor/reactor-netty#877]
I am provide the demo with spring-cloud-gateway 
spring boot version : 2.1.3.REALEASE
reactor-netty version: 0.8.5.REALEASE
server:
```
@OnMessage
    public void onMessage(String message, Session session) {
        log.info("收到来自窗口"+sid+"的信息:"+message);
        //群发消息
        for (WebSocketServer item : webSocketSet) {
            try {
                item.sendMessage(message);
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
        if (message.startsWith("dd")) {

            try {
                session.close(new CloseReason(CloseReason.CloseCodes.TOO_BIG,message));
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
    }
```
when server receive message what startwith 'dd' then command 'close' with 'code' and 'reason'
but client receive
code=1005 reason ='' and wasClean=false

I find the code of reactor-netty ：
WebsocketClientOperations
```
public void onInboundNext(ChannelHandlerContext ctx, Object msg) {
...
			if (msg instanceof CloseWebSocketFrame &&
				((CloseWebSocketFrame)msg).isFinalFragment()) {
			if (log.isDebugEnabled()) {
				log.debug(format(channel(), "CloseWebSocketFrame detected. Closing Websocket"));
			}
			onInboundComplete();
			CloseWebSocketFrame close = (CloseWebSocketFrame) msg;
			sendCloseNow(new CloseWebSocketFrame(true,
					close.rsv(),
					close.content()));
		}
...
	}
```
this method is wrong ,because the server send close with some' reason' to netty ,but,the method of 'sendCloseNow' send the 'reason' to server channel ,it should send reason to client channel.
the same to client.

**Comment by violetagg** [comment]
Can you check this feature? 
https://github.com/reactor/reactor-netty/issues/533

**Comment by violetagg** [comment]
`sendCloseNow` and `sendClose` has different purposes.

The first (`sendCloseNow`) is invoked when the server receives `Close` frame from the client. According to the specification https://tools.ietf.org/html/rfc6455#page-36

```
The application MUST NOT send any more data frames after sending a
   Close frame.

If an endpoint receives a Close frame and did not previously send a
   Close frame, the endpoint MUST send a Close frame in response.  (When
   sending a Close frame in response, the endpoint typically echos the
   status code it received.) 
```

Here we mark that Close frame was sent
https://github.com/reactor/reactor-netty/blob/master/src/main/java/reactor/netty/http/server/WebsocketServerOperations.java#L230

The second one (`sendClose`) is close initiated by the application with some close information.
If it is possible we will send that close information, but if previous there was received a Close frame then it won't be send.
https://github.com/reactor/reactor-netty/blob/master/src/main/java/reactor/netty/http/server/WebsocketServerOperations.java#L207

**Comment by zzd0058** [comment]
thanks,i'll try it

**Comment by zzd0058** [comment]
hello,Could you tell give me some suggestions? how to close websocketServer to notify client the 'close code and reason',I update version to 0.9.0.realease cannot work!

**Comment by violetagg** [comment]
@zzd0058 Here are very simple tests that demonstrate that.

```
@Test
public void testClientReceivesCloseFrame() {
	DisposableServer httpServer =
			HttpServer.create()
			          .port(0)
			          .handle((in, out) -> out.sendWebsocket((i, o) -> o.sendClose(1000, "some reason")))
			          .wiretap(true)
			          .bindNow();

	MonoProcessor<WebSocketCloseStatus> proc = MonoProcessor.create();
	HttpClient.create()
	          .port(httpServer.address().getPort())
	          .wiretap(true)
	          .websocket()
	          .uri("/")
	          .handle((i, o) -> {
	              i.receiveCloseStatus()
	               .subscribeWith(proc);
	              return o.neverComplete();
	          })
	          .subscribe();

	StepVerifier.create(proc)
	            .expectNextMatches(webSocketCloseStatus -> webSocketCloseStatus.code() == 1000 &&
	                    "some reason".equals(webSocketCloseStatus.reasonText()))
	            .verifyComplete();

	httpServer.disposeNow();
}

@Test
public void testServerReceivesCloseFrame() {
	MonoProcessor<WebSocketCloseStatus> proc = MonoProcessor.create();
	DisposableServer httpServer =
			HttpServer.create()
			          .port(0)
			          .handle((in, out) -> out.sendWebsocket((i, o) -> {
			              i.receiveCloseStatus()
			               .subscribeWith(proc);
			              return o.neverComplete();
			          }))
			          .wiretap(true)
			          .bindNow();

	HttpClient.create()
	          .port(httpServer.address().getPort())
	          .wiretap(true)
	          .websocket()
	          .uri("/")
	          .handle((i, o) -> o.sendClose(1000, "some reason"))
	          .subscribe();

	StepVerifier.create(proc)
	            .expectNextMatches(webSocketCloseStatus -> webSocketCloseStatus.code() == 1000 &&
	                    "some reason".equals(webSocketCloseStatus.reasonText()))
	            .verifyComplete();

	httpServer.disposeNow();
}
```

**Comment by zzd0058** [comment]
It's a demo, A is a WebsocketClient,B is spring-cloud-gateway,C is websocketServer.
So,A establishes a connection with C through the proxy B,But now ,I found that when C close the channel of websocket and send CloseWebSocketFrame with some ‘reason and closeCode’ to A.
In theory, A should receive the 'reason and code' from C,but it doesn't receive it instead of '1005'.
Can you give me some solutions?

**Comment by violetagg** [comment]
@spencergibb do you forwards Close web socket frames?

/cc @smaldini

**Comment by zzd0058** [comment]
any solution?

**Comment by violetagg** [comment]
@zzd0058 Please create an issue for Spring Cloud Gateway and link this one.
