### ISSUE TITLE
I can not get custom reason phrase

### ISSUE THREAD

**Issue by LeePepe** [reactor/reactor-netty#879]
## Motivation

My server has a custom reason phrase for HttpStatus 400. For example, 400 "Not Found User". And I want to get the reason phrase.
But I found there are no way to get it. I only can get "Bad requst"
## Desired solution

I found the problem is in [HttpClientOperations](https://github.com/reactor/reactor-netty/blob/master/src/main/java/reactor/netty/http/client/HttpClientOperations.java). In 417, method "status", it create a new instance by status code and don't care its reason phrase.

## Considered alternatives

Can it get HttpResponseStatus by both code and its reason phrase?

**Comment by violetagg** [comment]
@LeePepe For which version do you need this enhancement?

**Comment by LeePepe** [comment]
Sorry, this is my first time to open a issue. I don't know what you mean and I don't know why my issue has this label.

**Comment by violetagg** [comment]
@LeePepe I mean the version of Reactor Netty

We have 0.8.x and 0.9.x. Which one do you use?

**Comment by LeePepe** [comment]
@violetagg I use spring boot 2.1.0.RELEASE. So I don't know how to know the version of Reactor Netty. But I found in 0.9.1 and 0.8.x it is same.`return HttpResponseStatus.valueOf(responseState.response.status().code());`

**Comment by violetagg** [comment]
@LeePepe Spring Boot 2.1.0.RELEASE uses 0.8.x and Spring Boot 2.2.0.RELEASE - 0.9.x
