### ISSUE TITLE
How to add custom SSLContext for TCPClientSpec

### ISSUE THREAD

**Issue by Ishukumar91** [reactor/reactor-netty#890]
I am developing a websocket server with STOMP and rabbitmq as a message broker. Its a secured application. My requirement is to establish a secured connection with rabbitmq through websocket. I have created a required configurations in my project and creating TCPClientspec with host, port and ssl option something like below:

{  
...
return tcpClientSpec
                .env(environment)
                .codec(new Reactor2StompCodec(new StompEncoder(), new StompDecoder()))
                .ssl(ssl ? null : null)
                .connect(host, port);
        		
    	}

i am trying to find a way to add custom sslcontext, since i have to use only  truststore and not keystore. Without overriding sslcontext, its looking for config related to keystore.

**Comment by violetagg** [comment]
@Ishukumar91 can you provide more complete example?

**Comment by violetagg** [comment]
@Ishukumar91 If you are using this version of the project
https://github.com/reactor/reactor/tree/v2.0.7.RELEASE/reactor-net/src/main/java/reactor/io/net/impl/netty/tcp

It is not supported anymore.
Try to migrate to the latest version.

**Comment by Ishukumar91** [comment]
ok.. i ll check. I have posted my query in stackoverflow
<https://stackoverflow.com/questions/58728280/spring-boot-ssl-tcpclient-stompbrokerrelaymessagehandler-rabbitmq>.
Please have a look for more details.


Regards
Ishwarya

**Comment by violetagg** [comment]
I'm closing this. We can reopen it if it is needed.
