### ISSUE TITLE
How to realize Udp multicast 

### ISSUE THREAD

**Issue by 1ssqq1lxr** [reactor/reactor-netty#897]

**Comment by violetagg** [comment]
@1ssqq1lxr Something like this? https://github.com/reactor/reactor-netty/blob/master/src/test/java/reactor/netty/udp/UdpServerTests.java#L133

**Comment by violetagg** [comment]
Closing the issue. We can reopen it if this is necessary.

**Comment by zhoyou** [comment]
how to use multicast udp ?
