### ISSUE TITLE
connection pool's max request count policy

### ISSUE THREAD

**Issue by creatorKoo** [reactor/reactor-netty#898]
connection pool's connection have max request count.
after max request count, then connection must be close and re-open connection by connection pool .

It is same feature that nginx's keepalive_requests (http://nginx.org/en/docs/http/ngx_http_core_module.html#keepalive_requests)

## Motivation

This feature need to communicate old lagacy http server using connection pool by WebClient request.
In order to graceful stop in old server, connection must be close from caller(client), so reactor netty's WebClient connection pool must need close connection periodically (or close all connection when graceful stop in old server). 
If you don't do that, old server can't be graceful stop because of having always connected connection and can't graceful-close connection.

## Desired solution

Add ConnectionProvider's argument maxRequestCount
ex) 
int maxRequestCount = 100;
ConnectionProvider.elastic("refresh-pool", maxRequestCount);

## Considered alternatives

Ultimately, add argument 'evictionPredicate' to ConnectionProvider. 
Then, connection pool can customize pool policy by developer, not library maintainer.

## Additional context

Please, add this feature.

**Comment by violetagg** [comment]
@creatorKoo Can't you use the current API
https://projectreactor.io/docs/netty/release/api/reactor/netty/http/client/HttpClient.html#doOnRequest-java.util.function.BiConsumer-
you can keep a counter and when the counter hits for example 100 you can add header `Connection: close` to the request headers

Something similar you can see here
https://github.com/reactor/reactor-netty/blob/master/src/test/java/reactor/netty/http/client/HttpClientTest.java#L1029

**Comment by creatorKoo** [comment]
@violetagg Very good solution for HttpClient. But, I need this feature to TcpClient.

I know that this feature not need to everybody. So, If you think don't need to implement this feature on TcpClient, then, Please know me how to TcpClient's connection pool close safely.

**Comment by violetagg** [comment]
@creatorKoo in TcpClient you also have lifecycle callbacks + observable.
https://projectreactor.io/docs/netty/release/api/reactor/netty/tcp/TcpClient.html#doOnConnect-java.util.function.Consumer-
https://projectreactor.io/docs/netty/release/api/reactor/netty/tcp/TcpClient.html#observe-reactor.netty.ConnectionObserver-
For observe you have states like https://projectreactor.io/docs/netty/release/api/reactor/netty/ConnectionObserver.State.html#RELEASED

**Comment by creatorKoo** [comment]
@violetagg Thank you for your help. ;)

**Comment by creatorKoo** [comment]
@violetagg I test that tips. But, RELEASED state never happend.
```
TcpClient.create(ConnectionProvider.fixed("fixed-test", 2, 2000, Duration.ofSeconds(3)))
.observe((connection, newState) -> {
                    if (newState.equals(ConnectionObserver.State.RELEASED)) {
                        connection.dispose();
                    }
                })
```
My test TcpClient constructor. and state only happen CONNECT, CONFIGURED, only.
Any idea of this issue?

**Comment by violetagg** [comment]
@creatorKoo so with TCP we have packages (it's not as request/response with HTTP)
Can't you just take the connection, send whatever number of packages you want and then dispose the connection?

something similar we have here
https://github.com/reactor/reactor-netty/blob/master/src/test/java/reactor/netty/tcp/TcpClientTests.java#L932
https://github.com/reactor/reactor-netty/blob/master/src/test/java/reactor/netty/tcp/TcpClientTests.java#L988
https://github.com/reactor/reactor-netty/blob/master/src/test/java/reactor/netty/http/server/HttpServerTests.java#L1422

**Comment by creatorKoo** [comment]
Ah.. I found problem.
TcpClient must be reuse it. Not create every call. So I change my code like this
```
private TcpClient tcpClient = TcpClient.create(ConnectionProvider.fixed("fixed-test", 2, 2000, Duration.ofSeconds(3)));

function~~{
    return tcpClient.observe((connection, newState) -> {
                    if (newState.equals(ConnectionObserver.State.RELEASED)) {
                        connection.dispose();
                    }
                })
}
```

so everything work perfect. Thank you for your help. :)

**Comment by creatorKoo** [comment]
No.. It's bad way...
I found alter way.
```
connection.markPersistent(false); 
```

that's really work.

**Comment by gmc-hue** [comment]
I have the same issue, active connections are not closed. Making the above changes didnt resolve the issue

**Comment by violetagg** [comment]
@gmc-hue Please create an issue with a reproducible example.

**Comment by gmc-hue** [comment]
@violetagg , created new issue https://github.com/reactor/reactor-netty/issues/1840.
