### ISSUE TITLE
Add "access control allow origin" method in httpserverresponse

### ISSUE THREAD

**Issue by zhouzhou19950825** [reactor/reactor-netty#902]
I hope "access control allow origin" can be configured globally in httpserver and locally in httpserverresponse.

**Comment by violetagg** [comment]
@zhouzhou19950825 Can't you do that in https://projectreactor.io/docs/netty/release/api/reactor/netty/http/server/HttpServer.html#handle-java.util.function.BiFunction-

there you have access to the request/request headers and response/response headers

**Comment by zhouzhou19950825** [comment]
thanks!
