### ISSUE TITLE
HttpClientOperation shouldn't always write a `LastHttpContent.EMPTY_LAST_CONTENT`

### ISSUE THREAD

**Issue by simonbasle** [reactor/reactor-netty#91]
In `HttpClientOperations#onOutboundComplete()`, if the headers have been sent already then the method automatically writes a `LastHttpContent.EMPTY_LAST_CONTENT` to the `Channel`.

It seems there are cases where the channel has already been written to with a `DefaultFullHttpRequest`, which is already a `LastHttpContent`. In that case, the `HttpObjectEncoder` is reset to ST_INIT and upon encountering EMPTY_LAST_CONTENT just afterward, it fails with the following error:

```
java.lang.IllegalStateException: unexpected message type: LastHttpContent$1
```

Furthermore, I don't think having a trailing LAST_HTTP_CONTENT makes sense if chunked encoding isn't used, so `onOutboundComplete` should at least also test for that.

**Comment by smaldini** [comment]
Related to #69
