### ISSUE TITLE
reactor-netty 0.9.2 no OSGi metadata

### ISSUE THREAD

**Issue by swimmesberger** [reactor/reactor-netty#913]
Since version 0.9.2 the jar file MANIFEST.MF does not contain any OSGi metadata in previous versions the metadata was present. The "reactor-netty-0.9.2.RELEASE-original.jar" still contains the metadata.

## Expected Behavior
The OSGi metadata should be present in the MANIFEST.MF file of the jar.

## Actual Behavior
No OSGi metadata is present

## Steps to Reproduce
- Download https://repo1.maven.org/maven2/io/projectreactor/netty/reactor-netty/0.9.2.RELEASE/reactor-netty-0.9.2.RELEASE.jar 
- Open the jar file with a zip editor
- Look for the "META-INF/MANIFEST.MF" file

## Possible Solution
Correct the gradle build to use the bnd gradle plugin for the "normal" reactor-netty build as you do with the "original" build

**Comment by simonbasle** [comment]
ah, that's a regression due to the combination of `shadowJar` and `bndBuilder` :( see https://github.com/bndtools/bnd/issues/3551 it seems they don't intend to make it easy to generate the `Import-Packages` for jar tasks other than the default `jar` one 😡
