### ISSUE TITLE
SOS HELP!! Ask for help： always io.netty.channel.ConnectionTimeoutException

### ISSUE THREAD

**Issue by chaichunyang** [reactor/reactor-netty#918]
i use spring cloud solution to build my apps, all them are springBoot applications, and use spring cloud gateway as an API Gateway for forward request.

gateway use reactor-netty for forward the **HTTP** requests to other apps.

when i deploy my apps to pro environment, run apps in docker，each app has a separate docker container, and the container is a Linux. then I got a lot of **io.netty.channel.ConnectionTimeoutException**. 

the pro environment has a special limited for tcp connections，it will terminate a tcp connection when the connection not used in  240 seconds, and do not even send a notify.

i try to use **ConnectionProvider.newConnection()** to ensure every forward request is for create a new **Connection**，bug the TimeoutException still happened. i don't know why, and if it has something relate with 240 seconds limited.

may some one can tell me why and how to fix this problem。

the pro environment use NAT、ACS、SDN，i don't know what these words mean， may be it's helpful for this ask！

Thanks a lot！

**Comment by violetagg** [comment]
For questions use either [Gitter](https://gitter.im/reactor/reactor-netty) or [stackoverflow.com](https://stackoverflow.com/questions/tagged/reactor-netty)
