### ISSUE TITLE
ChannelOperationsHandler.exceptionCaught() re-throwing Fatal Error causes the error to be simply ignored

### ISSUE THREAD

**Issue by fayndee** [reactor/reactor-netty#92]
`ChannelOperationsHandler.exceptionCaught()` is re-throwing a 'Fatal Error' according to the [current implementation](https://github.com/reactor/reactor-netty/blob/master/src/main/java/reactor/ipc/netty/channel/ChannelOperationsHandler.java#L164).

The problem with this approach is, in the end, this 'Fatal Error' will be simply ignored in Netty according to the current [Netty AbstractChannelHandlerContext implementation](https://github.com/netty/netty/blob/4.1/transport/src/main/java/io/netty/channel/AbstractChannelHandlerContext.java#L286). So the error is not propagated anywhere and the channel user will get a timeout after the default 30 secs. This should not be the expected behavior. 

Should `ChannelOperationsHandler` propagate the Fatal Error as a channel inbound error as well in this case?

**Comment by smaldini** [comment]
We can limit the scope of the error indeed but JVM fatal exception cannot be and shouldn't be dealt with anyway.
