### ISSUE TITLE
Add Global Option to Disable Fail on Error

### ISSUE THREAD

**Issue by nebhale** [reactor/reactor-netty#93]
Currently in order to disable fail on error behaviors, each request must be modified, setting `failOnClientError` and `failOnServerError`.  If you want to code an application that handles all errors (say for error translation, identification of `401`, etc.) you must disable these options for each and every request.

Instead of requiring this for each request there should be global options to disable these behaviors for all uses of a specific `HttpClient`.

**Comment by violetagg** [comment]
Closing this feature request. These configurations will be removed for 0.8.0. The user will decide how to handle the 40x/50x responses i.e. failOnClientError/failOnServerError always will be false. See #181

**Comment by violetagg** [comment]
Tracked via #182
