### ISSUE TITLE
Add builder for configuring the ConnectionProvider

### ISSUE THREAD

**Issue by violetagg** [reactor/reactor-netty#933]

**Comment by jdaru** [comment]
Hello guys, i'm sorry, but i didn't understand how can i assign to me this issue and how it works, i mean contributing in github :)
i've cloned this project, accepted pivotal cla, looked at the code and realized what was required.
Or please tell me where to read about contributing to this project.

**Comment by violetagg** [comment]
@jdaru commenting here that you want to work on this is enough :+1:

**Comment by violetagg** [comment]
@jdaru once you are ready with the change create a PR and we will discuss there.
https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-requests

**Comment by jdaru** [comment]
@violetagg i've got "unable to access" message, when tried to create pull request or just push code.

**Comment by violetagg** [comment]
@jdaru do you use a fork of the repository or you are trying to use this repository?

**Comment by jdaru** [comment]
@violetagg thank you!!!! yep, i used this repo :)

**Comment by violetagg** [comment]
Thanks for the contribution
