### ISSUE TITLE
Connection has been closed BEFORE response, while sending request body when uploading large file (size: 9 MO)

### ISSUE THREAD

**Issue by jemmali-git** [reactor/reactor-netty#934]
I have spring boot application running behind a spring cloud gateway, when I upload large file (size: 10 MO)  via a postman request, I get the following error:

```java
reactor.netty.http.client.PrematureCloseException: Connection has been closed BEFORE response, while sending request body
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	|_ checkpoint ⇢ org.springframework.cloud.gateway.filter.WeightCalculatorWebFilter [DefaultWebFilterChain]
	|_ checkpoint ⇢ HTTP POST "/hi" [ExceptionHandlingWebHandler]
Stack trace:
```
spring boot application Controller:
```java
@PostMapping(value = "hi")
public String postHi(@RequestHeader HttpHeaders headers) {
  return request.getHeader("Content-Length");
}
```
Spring cloud gateway route configuration :

```java
server:
  port: 8101
spring:
  cloud:
    gateway:
      routes:
        - id: hi
          uri: http://localhost:8080/hi
          predicates:
            - Path=/hi/**
```
## Steps to Reproduce
Here is an example to reproduce the issue
https://github.com/jemmali-git/examples.git

* Reactor version used: 0.9.1RELEASE
* spring cloud gateway version: 2.2.0.RELEASE
* Other relevant libraries versions (eg. `netty`, ...):
* JVM version (`javar -version`): 1.8
* OS and version : Windows 10 Pro

**Comment by violetagg** [comment]
@jemmali-git How do you upload the file - I mean multipart, binary etc...

**Comment by violetagg** [comment]
You might be hitting some of these limitations
https://docs.spring.io/spring-boot/docs/current/reference/html/appendix-application-properties.html

```
server.tomcat.max-http-form-post-size
server.tomcat.max-swallow-size
spring.servlet.multipart.max-file-size
spring.servlet.multipart.max-request-size
```

I see that the target application uses Spring MVC. When the limitations above are met Tomcat will reset the connection which will lead to the exception `Connection has been closed BEFORE response, while sending request body` that you see.

**Comment by Donato10** [comment]
Hi @violetagg since in this case the response will contain a 500 status and the premature closed exception, I wonder how can I override this response to show a 400 saying the file was too large: Like propagate the actual exception message that is thrown by the target app.
Regards

**Comment by violetagg** [comment]
@Donato10 This you should do on the server side

**Comment by Mabintao** [comment]
@violetagg 
![image](https://user-images.githubusercontent.com/25863444/77990851-fdc1b900-7354-11ea-9bfb-3f8aead307dc.png)

I set the following properties, but it didn't work for me.
`spring.servlet.multipart.max-file-size`
`spring.servlet.multipart.max-request-size`

When I upload files larger than 30M, I get the error  
"Connection has been closed BEFORE response, while sending request body"

**Comment by violetagg** [comment]
@Mabintao Open a new issue with a reproducible example.

**Comment by kiwi-field** [comment]
It's the same with me. What's the solution

**Comment by violetagg** [comment]
@kiwi-field Open a new issue with a reproducible example.

**Comment by kiwi-field** [comment]
My parameters are set to

Servlet.Multipart.max-file-size:2MB
Servlet.Multipart.max-request-size: 2MB
Connection has been closed before response does not appear

**Comment by kiwi-field** [comment]
@violetagg see https://github.com/reactor/reactor-netty/issues/1062
