### ISSUE TITLE
Disable Netty HTTP Client Connection Pool

### ISSUE THREAD

**Issue by hanscrg** [reactor/reactor-netty#936]
Spring Boot WebFlux uses Netty HTTP Client. Netty has a connection pool by default. How to disable that connection pool application wise?

**Comment by violetagg** [comment]
This belongs to [Gitter](https://gitter.im/reactor/reactor-netty) or [stackoverflow.com](https://stackoverflow.com/questions/tagged/reactor-netty)

Check
https://projectreactor.io/docs/netty/release/reference/index.html#_connection_pool

```
TcpClient tcpClient =
    TcpClient.newConnection()
             .host("example.com")
             .port(80)
             ...
HttpClient httpClient =
    HttpClient.from(tcpClient);
```

**Comment by hanscrg** [comment]
This only works for a specific http client. I mean application wise, in one place, we can disable connection pool and then any further Netty HTTP Client created will not use connection pool?

**Comment by violetagg** [comment]
@hanscrg That's the application wise way.
Once you have the `httpClient` with this configuration you can use this client for as many as URLs you want.
Every time when you configure a new URL you will receive a new HttpClient instance that will inherit all the previous configurations.
In terms of Spring WebFlux/Boot you can have one `@Bean` that will hold all your common configurations.

**Comment by violetagg** [comment]
https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#howto-webclient-reactor-netty-customization

**Comment by hanscrg** [comment]
I did as what the document said to have a bean created as below, but nothing seems to impact Netty used by Spring OAuth filter. It still use  r.n.resources.PooledConnectionProvider. Any idea why is that?

@bean
public ClientHttpConnector clientHttpConnector() {
return new ReactorClientHttpConnector(HttpClient.create(ConnectionProvider.newConnection()));
}

The is Spring application startup logs,

2019-12-19 15:35:00.707 DEBUG 7 --- [main] o.s.b.f.s.DefaultListableBeanFactory: Creating shared instance of singleton bean 'clientHttpConnector'

2019-12-19 15:35:03.055 DEBUG 7 --- [main] o.s.b.f.s.DefaultListableBeanFactory: Autowiring by type from bean name 'clientConnectorCustomizer' via factory method to bean named 'clientHttpConnector'

ClientHttpConnectorAutoConfiguration#clientConnectorCustomizer matched: - @ConditionalOnBean (types: org.springframework.http.client.reactive.ClientHttpConnector; SearchStrategy: all) found bean 'clientHttpConnector' (OnBeanCondition)

ClientHttpConnectorConfiguration.ReactorNetty:
Did not match:
- @ConditionalOnBean (types: org.springframework.http.client.reactive.ClientHttpConnector; SearchStrategy: all) found beans of type 'org.springframework.http.client.reactive.ClientHttpConnector' clientHttpConnector (OnBeanCondition)
Matched:
- @ConditionalOnClass found required class 'reactor.netty.http.client.HttpClient' (OnClassCondition)

**Comment by violetagg** [comment]
@hanscrg the discussion about WebClient with/without connection pool enabled will be covered in this issue spring-cloud/spring-cloud-gateway#1493
