### ISSUE TITLE
WebSocket client sends raw data instead of Websocket frames

### ISSUE THREAD

**Issue by SergeyLukashevich** [reactor/reactor-netty#937]
When using WebSocket client for connection to the local server as shown in reference, server gets an unexpected data.

Version: 0.9.2.RELEASE

Server output:
```
>wscat.cmd -l 8888
Listening on port 8888 (press CTRL+C to quit)
Client connected
error: Invalid WebSocket frame: RSV2 and RSV3 must be clear
Disconnected (code: 1002, reason: "")
```

Code: 
```        
HttpClient.create()
                  .websocket()
                  .uri("ws://127.0.0.1:8888")
                  .handle((inbound, outbound) -> {
                      inbound.receive()
                             .asString()
                             .take(1)
                             .subscribe(System.out::println);

                      final byte[] msgBytes = "hello".getBytes(CharsetUtil.ISO_8859_1);
                      return outbound.send(Flux.just(Unpooled.wrappedBuffer(msgBytes), Unpooled.wrappedBuffer(msgBytes)), b -> true)
                                     .neverComplete();
                  })
                  .blockLast();
```

Traffic capture: 
[capture.zip](https://github.com/reactor/reactor-netty/files/3980292/capture.zip)

Issue reproduces starting with version 0.9.0.RELEASE.
Similar code for 0.8.14.RELEASE - works fine.

**Comment by violetagg** [comment]
@SergeyLukashevich This is an issue with the documentation
This method should be used as it transforms to frames
https://projectreactor.io/docs/netty/release/api/reactor/netty/http/websocket/WebsocketOutbound.html#send-org.reactivestreams.Publisher-

This one does not transform and one should do it by oneself (this method does not exist in 0.8.x, so I assume you used the one above)
https://projectreactor.io/docs/netty/release/api/reactor/netty/NettyOutbound.html#send-org.reactivestreams.Publisher-java.util.function.Predicate-
