### ISSUE TITLE
Failure to process URL where path is nothing but "//"

### ISSUE THREAD

**Issue by rstoyanchev** [reactor/reactor-netty#948]
After upgrading to Dysprosium snapshots, there is one test failure in the Spring Framework in a scenario where the path is nothing but a double slash, e.g. `"http://localhost:8080//"`.

It results in the following:

```
java.lang.IllegalArgumentException: Expected authority at index 2: //
	at java.net.URI.create(URI.java:852) ~[?:1.8.0_222]
	at reactor.netty.http.HttpOperations.resolvePath(HttpOperations.java:300) ~[reactor-netty-0.9.3.BUILD-SNAPSHOT.jar:0.9.3.BUILD-SNAPSHOT]
	at reactor.netty.http.server.HttpServerOperations.<init>(HttpServerOperations.java:128) ~[reactor-netty-0.9.3.BUILD-SNAPSHOT.jar:0.9.3.BUILD-SNAPSHOT]
	at reactor.netty.http.server.HttpTrafficHandler.channelRead(HttpTrafficHandler.java:157) ~[reactor-netty-0.9.3.BUILD-SNAPSHOT.jar:0.9.3.BUILD-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377) [netty-transport-4.1.44.Final.jar:4.1.44.Final]
...
```

This looks like it might be a side effect of refactoring for #926 in https://github.com/reactor/reactor-netty/commit/dc3fb4b1fe1538e1ac1249412a272a7204912c27.

**Comment by qcastel** [comment]
I am currently hitting this issue in Spring Cloud gateway. 
It can be reproduced with the following curl:

```
curl -k --proxy http://localhost:8500 https://example.com/test
```
(I am testing hoverfly in front of spring cloud gateway btw, https://hoverfly.io/, may help you reproduce the issue)


I thought I would try to see if it is fixed in 0.9.5 but unfortunately, there is still an NPE.

Seems like you re-introduce the bug two days ago, via 327e9b3 @violetagg 

Here is the current stack trace:

```
java.lang.NullPointerException: null
	at reactor.netty.http.HttpOperations.resolvePath(HttpOperations.java:341)
	at reactor.netty.http.server.HttpServerOperations.<init>(HttpServerOperations.java:130)
	at reactor.netty.http.server.HttpTrafficHandler.channelRead(HttpTrafficHandler.java:155)
```

**Comment by violetagg** [comment]
@qcastel can you provide more info?

I did the following:

Spring Gateway

```
@SpringBootApplication
public class DemoApplication {

	public static void main(String[] args) {
		SpringApplication.run(DemoApplication.class, args);
	}

	@Bean
	public RouteLocator myRoutes(RouteLocatorBuilder builder) {
		return builder.routes()
				.route(p -> p
						.path("/get")
						.uri("http://httpbin.org:80"))
				.build();
	}
}
```

Hoverfly started in capture mode

```
hoverctl start
hoverctl mode capture
```

Then Spring Gateway requested like below and the response is received

```
curl --proxy http://localhost:8500 http://localhost:8080/get
{
  "args": {}, 
  "headers": {
    "Accept": "*/*", 
    "Accept-Encoding": "gzip", 
    "Content-Length": "0", 
    "Forwarded": "proto=http;host=\"localhost:8080\";for=\"0:0:0:0:0:0:0:1:52401\"", 
    "Host": "httpbin.org", 
    "Proxy-Connection": "Keep-Alive", 
    "User-Agent": "curl/7.64.1", 
    "X-Amzn-Trace-Id": "Root=1-5e4d757f-01787058a5816cff5108579f", 
    "X-Forwarded-Host": "localhost:8080"
  }, 
  "origin": "0:0:0:0:0:0:0:1, 78.83.99.114", 
  "url": "http://localhost:8080/get"
}
```

Running with latest Reactor Netty 0.9.5.BUILD-SNAPSHOT

**Comment by qcastel** [comment]
Ok so indeed, that wasn't that obvious to reproduce the issue.

Did manage to reproduce it in isolation at the end, I shared a demo repo here: https://github.com/qcastel/reproduce-netty-npe

Essentially two factors are triggering this issue:
1 - you need to proxy to spring cloud gateway
2 - you need to proxy something under https

Thanks for looking at this issue btw!

**Comment by violetagg** [comment]
@qcastel I can reproduce it

**Comment by violetagg** [comment]
@qcastel I committed a fix - dfb71cf. It would be great if you can test 0.9.5.BUILD-SNAPSHOT.

**Comment by qcastel** [comment]
@violetagg Just tried on https://github.com/qcastel/reproduce-netty-npe and think the NPE is resolved now!

Although I do have another error: 
```
curl: (56) Received HTTP code 404 from proxy after CONNECT
```

I also simplified the reproduction steps to not have hoverfly and directly hit Spring cloud gateway.

I guess I will raise a new ticket on Spring cloud gateway this time!

**Comment by violetagg** [comment]
@qcastel so the new failure is not in Reactor Netty?

**Comment by qcastel** [comment]
Hard to tell, I don't get any logs this time. It could still be the netty rejecting the 'CONNECT' requests.
I raised it under https://github.com/spring-cloud/spring-cloud-gateway/issues/1576
I reproduced the issue there (I simplified the reproduction steps btw) https://github.com/qcastel/reproduce-spring-cloud-gateway-error
