### ISSUE TITLE
Connection pool maxPending size unbounded by default and cannot be configured

### ISSUE THREAD

**Issue by jtorkkel** [reactor/reactor-netty#951]
In plain netty 4.1.x it is possible to configure and query pool maxPending size in addition to acquireTimeout.

When reactor-netty fixed Connection pool is used maxPending size cannot be configured and it is set internally to unbound. Only the following parameters can be configured
- pool name
- maxConnections
- acquireTimeout
- MaxIdleTime

Having unbound is problematic because service can run out of memory or out of resource just like elastic connection pool might result out of sockets.

reactor-netty should have configuration option to set/get pool maxPending value and have bound default value as default.

**Comment by violetagg** [comment]
An option will be available with 0.9.5.RELEASE.
However we cannot add a default value because this heavily depends on the use case.

**Comment by violetagg** [comment]
@jtorkkel the default for 0.9.x will not be changed however we will change it for 1.0.x and by default the HTTP client will run with 
- 500 max connections
- 1000 pending acquire max count 
- 45s pending acquire timeout

For more info see #966
