### ISSUE TITLE
Add configuration for switching between FIFO and LIFO order for the channels in the pool 

### ISSUE THREAD

**Issue by violetagg** [reactor/reactor-netty#962]
The current implementation uses FIFO and this cannot be changed.
https://github.com/reactor/reactor-netty/blob/master/src/main/java/reactor/netty/resources/PooledConnectionProvider.java#L108

This feature request is about adding a configuration for switching between FIFO and LIFO.
https://github.com/reactor/reactor-netty/blob/master/src/main/java/reactor/netty/resources/ConnectionProvider.java#L168

**Comment by jdaru** [comment]
took to work
