### ISSUE TITLE
WebSocket compression extension should not depends on SimpleCompressionHandler

### ISSUE THREAD

**Issue by amizurov** [reactor/reactor-netty#970]
## Expected Behavior
If compression is enabled on the server side then WebSocket compression extensions should be applied according to https://tools.ietf.org/html/rfc7692#section-5 and not depend on `SimpleCompressionHandler` present in pipeline or not.

## Actual Behavior
Configure `HttpServer` with enable compression and set `maxResponseSize` to value grate than zero, WebSocket compression never applied.

## Steps to Reproduce

```java
public class EchoServer {

    public static void main(String[] args) {
        HttpServer server =
            HttpServer.create()
                .port(8080)
                .compress(true)
                .compress(2048)
                .wiretap(true)
                .route(r -> r.ws("/ws", (in, out) ->  out.sendObject(in.receiveFrames().doOnNext(WebSocketFrame::retain))));

        server.bindNow()
            .onDispose()
            .block();
    }
}
```

## Possible Solution
Change logic inside `WebsocketServerOperations` constructor.

## Your Environment

* Reactor version(s) used: 1.0.0.BUILD-SNAPSHOT
* Other relevant libraries versions (eg. `netty` ):  4.1.45.Final
* JVM version (`javar -version`): 1.8.0_232
* OS and version (eg `uname -a`): Darwin Kernel Version 18.7.0: Sun Dec  1 18:59:03 PST 2019; root:xnu-4903.278.19~1/RELEASE_X86_64 x86_64

**Comment by violetagg** [comment]
@amizurov PR #971

**Comment by violetagg** [comment]
We will provide a WebSocket configuration for compression on/off

**Comment by violetagg** [comment]
@amizurov @rstoyanchev PTAL PR #980 

In 0.9.x versions we will keep both ways for specifying compression on/off (on HTTP level and the new way with the WebSocket configuration).
In 1.x I'm going to remove the one on HTTP level.
