### ISSUE TITLE
ByteBufFlux hangs when passed downstream in HttpClient

### ISSUE THREAD

**Issue by jpork** [reactor/reactor-netty#974]
When passing the ByteBufFlux content of an http get response downstream out of the response() lamba context like shown below it hangs infinitely. 

```scala
    val content = HttpClient.create()
      .baseUrl(repoUrl)
      .get()
      .uri(s"/$metadataFile")
      .response[Flux[ByteBuf]]{(response: HttpClientResponse , content: ByteBufFlux) =>
        Flux.just(content)}
      .flatMap{content: Flux[ByteBuf]=>
        ByteBufFlux.fromInbound(content).aggregate()}
      .blockFirst().toString(UTF_8)

    println(content)
```

When handling the content inside the response lambda it just works. 

```scala
    val content = HttpClient.create()
      .baseUrl(repoUrl)
      .get()
      .uri(s"/$metadataFile")
      .response[ByteBuf]{(response , content) =>
          content.aggregate()}
      .blockFirst().toString(UTF_8)

    println(content)
```
Shouldn't it be possible to pass the content flux downstream in order to deal with it some steps later?

**Comment by violetagg** [comment]
@jpork This will not work because we will complete the response. https://github.com/reactor/reactor-netty/blob/master/src/main/java/reactor/netty/http/client/HttpClientFinalizer.java#L77-L80

You should do it like this

```
      .responseContent()
     .aggregate()
     .asString(UTF_8)
```

If you insist to use the code above then you should use `responseConnection()`

**Comment by jpork** [comment]
Shouldn't it result in any kind of error if this is not allowed? So far the code just hangs for ever.

I don't see the mechanism how it is completed within the response method.

When using responseContent I can have either the connent or the headers?

When using responseConnection should I free resources? And how should I do so?

**Comment by jpork** [comment]
I didn't expect this so far. The code you've linked creates some intermediate Flux instances. But I cannot recognize where the flux is completed when leaving the response lambda context.

How can I pass both response header and content to later stage processing? When downloading files I would need "Content-Length" and "Content-Type" to be passed  downstream together with content.

**Comment by violetagg** [comment]
@jpork Do you think something like this will help you

https://github.com/reactor/reactor-netty/blob/master/src/test/java/reactor/netty/http/server/HttpServerTests.java#L592-L600

**Comment by jpork** [comment]
This approach would be functional identical to a Future like approach. I would get the data and metadata as single item when the response it completed. 

I would loose the ability to evaluate the progress of the download.

**Comment by violetagg** [comment]
@jpork then you definitely have to use `responseConnection`
