### ISSUE TITLE
Confusing javadoc for `doAfterResponse` and `doOnResponseError`

### ISSUE THREAD

**Issue by crankydillo** [reactor/reactor-netty#975]
The [Javadoc](https://github.com/reactor/reactor-netty/blob/fbd1c30f0da8edb9b81a88ecf540f55d1983db84/src/main/java/reactor/netty/http/client/HttpClient.java#L576) for `doAfterResponse` suggests the callback will fire whenever the response was 'fully received'; however, the callback is described as an observer of disconnect events.  Are these equivalent things?  If the connection is persistent, would the `doAfterResponse` not fire for each response?  Our testing suggests the callback does fire upon each response; however, it doesn't seem tied to a 'fully received' response (see code below).

In our case, we are trying to use `doAfterResponse` and `doOnResponseError` to trigger different behavior.  It requires them to be mutually exclusive (i.e. we didn't expect both to fire for the same request/response).  I think the Javadoc suggests they are mutually exclusive.

Expectations:

- `doAfterResponse` should not fire if `doOnResponseError` fires
- Javadoc for `doAfterResponse` should be cleaned up a bit.

```java
    public static void main(final String[] args) throws Exception {
        final DisposableServer server =
            HttpServer.create().host("localhost")
                .route(routes -> routes
                    .get("/kill", (request, response) -> {
                        return response.sendString(
                            Flux.range(0, 10_000)
                                .map(i -> {
                                    if (i == 1_000) {
                                        response.withConnection(Connection::disposeNow);
                                    }
                                    return "a";
                                })
                        );
                    }))
                .bindNow();


        try {
            final String respBody = HttpClient.create()
                .doAfterResponse((resp, conn) -> {
                    System.out.println("I did not expect to be called:(");
                })
                .doOnResponseError((resp, exc) -> {
                    System.out.println("I expected to be called:(");
                })
                .get()
                .uri("http://localhost:" + server.port() + "/kill")
                .responseSingle((resp, bytes) -> bytes.asString())
                .block();

            // Should not get here!
            System.out.println(respBody);
        } finally {
            server.disposeNow();
        }

    }
```

* Reactor version(s) used: 0.9.3.RELEASE

**Comment by violetagg** [comment]
@crankydillo 
`doAfterResponse ` is invoked on connection terminate event. In pooled connection scenario this means the connection is returned to the pool or closed. As you close the connection on the server side this triggers close connection event on the client side and as a result `doAfterResponse` is invoked.

https://github.com/reactor/reactor-netty/blob/v0.9.4.RELEASE/src/main/java/reactor/netty/http/client/HttpClientDoOn.java#L68-L69

`doOnResponseError ` in invoked when an error happens while receiving the response. As you close the connection on the server side while still sending the response as a result `doOnResponseError` is invoked.

https://github.com/reactor/reactor-netty/blob/v0.9.4.RELEASE/src/main/java/reactor/netty/http/client/HttpClientDoOnError.java#L201-L203
https://github.com/reactor/reactor-netty/blob/v0.9.4.RELEASE/src/main/java/reactor/netty/http/client/HttpClientOperations.java#L254

So I would say these two are not exclusive.

**Comment by crankydillo** [comment]
Thanks for the explanation @violetagg.  If the behavior doesn't change, shouldn't the Javadoc for `doAfterResponse` change?  IMO, it should not say that 'called ... after fully received'.  In fact, I think you should even consider changing the method name to `doOnClose` (or something more indicative of 'done with connection').  On a similar note, I need to check `doAfterRequest`, but I would expect `doOnResponse` would act similarly just for responses as opposed to requests.

Setting the above aside, is there any way to determine via these callbacks if the response was received successfully or not?  Ultimately, that is what we need to do.

**Comment by violetagg** [comment]
@crankydillo I updated the documentation #978 

What about using `HttpClient.observe(...)`?

**Comment by crankydillo** [comment]
Thanks for the doc update.

RE `doAfterResponse`, will it fire per response in a persistent connection scenario?

RE using `HttpClient#observe`, we did look into that.  I just don't think we understood that we should cast `Connection` to `HttpClientRequest` or `HttpClientResponse` to gain access to the subscriber context.  However, even with that, I don't know of any state that indicates receive is done other than doing what you are already doing [here](https://github.com/reactor/reactor-netty/blob/5a7b4f72717ae8b1c3454482f2ea4f63941c87c7/src/main/java/reactor/netty/http/client/HttpClientDoOn.java#L68).  Is `State.RELEASED` a good indicator for 'receive response is done'?

**Comment by violetagg** [comment]
> RE `doAfterResponse`, will it fire per response in a persistent connection scenario?

Yes

> RE using `HttpClient#observe`, we did look into that. I just don't think we understood that we should cast `Connection` to `HttpClientRequest` or `HttpClientResponse` to gain access to the subscriber context. 

Yes no direct access to the subscriber context

> Is `State.RELEASED` a good indicator for 'receive response is done'?

It depends, as I wrote above, even if you are in the pooled scenario you might have connection close.

**Comment by crankydillo** [comment]
Ok, `State.RELEASED` is tied only to returning to the pool.  We're still not sure how to do what we need, but we'll try to figure it out.  If you think of something, we'd greatly appreciate hearing about it:)

I'm assuming you will close this issue when you merge your doc PR (or release).

**Comment by violetagg** [comment]
@crankydillo Still thinking about this...

/cc @rstoyanchev What do you think if we change the current behaviour and introduce a new STATE (RESPONSE_COMPLETED or something like this)? Basically we know when the response was received fully
https://github.com/reactor/reactor-netty/blob/master/src/main/java/reactor/netty/http/client/HttpClientOperations.java#L552-L574

**Comment by violetagg** [comment]
@crankydillo @rstoyanchev PTAL #978

**Comment by crankydillo** [comment]
Thanks!
