### ISSUE TITLE
Support "X-Forwarded-Proto" headers Multiple Values

### ISSUE THREAD

**Issue by devsonic** [reactor/reactor-netty#976]
Recently i found issue in an environment using proxies.
my proxy server sends traffic to netty server with following headers.

> X-Forwarded-Proto: https,https

however, reactor-netty doesn't support "x-forwarded-proto" headers multiple values. (only one value can be parsed, so, it causes a 'scheme' error.)
https://github.com/reactor/reactor-netty/blob/fbd1c30f0da8edb9b81a88ecf540f55d1983db84/src/main/java/reactor/netty/http/server/ConnectionInfo.java#L174

as far as i know, many frameworks can handle multiple values.
and "[Tornnado](https://github.com/tornadoweb/tornado)"web server framework supports it as well.

> [X-Forwarded-Proto Multiple Values](https://github.com/tornadoweb/tornado/issues/2161)

I hope reactor-netty also supports this feature.

**Comment by violetagg** [comment]
@devsonic Are you interested in providing a PR?

**Comment by devsonic** [comment]
@violetagg yes. i will create PR soon.
