### ISSUE TITLE
Premature connection before response - ERROR for both FIXED and ELASTIC

### ISSUE THREAD

**Issue by softwareklinic** [reactor/reactor-netty#982]
In production environment while performing load test we are experiencing "Premature connection exception"

We have tried with below settings for FIXED 
1. Default 500 Max Connections
2. 400 Max Connections
3. 200, 100, 50, 25, 10

All of the above are throwing intermittently Premature connection exception --- and we are using 0.9.2 Reactor netty

We have also tried using ELASTIC (by setting Mac Connections to -1) -- again the same issue

Only when we set MAX Connections to 0 --- meaning NEW CONNECTION for each request --- we have absolutely 0 premature connection exceptions

Also, wanted to know what happens in background when newconnection is called --- does it open and close the connection each time? 

## Steps to Reproduce

```java
@Test
public void repoCase() {

}
```

## Your Environment

* Reactor version(s) used:
* Other relevant libraries versions (eg. `netty`, ...): 0.9.2 (reactor netty)
* JVM version (`javar -version`): JDK 8
* OS and version (eg `uname -a`): RHEL

**Comment by violetagg** [comment]
@softwareklinic Can you provide some reproducible example? Is there a stack trace that you can share?

> Only when we set MAX Connections to 0 --- meaning NEW CONNECTION for each request --- we have absolutely 0 premature connection exceptions
>
> Also, wanted to know what happens in background when newconnection is called --- does it open and close the connection each time?

How do you set this?

**Comment by softwareklinic** [comment]
2020-01-31T15:27:25.251+0000 (UTC) ERROR 82294 --- [reactor-http-nio-8] a.w.r.e.AbstractErrorWebExceptionHandler : [3604fd2a]  500 Server Error for HTTP GET "/requestPost"

reactor.netty.http.client.PrematureCloseException: Connection has been closed BEFORE response, while sending request body
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	|_ checkpoint ⇢ Request to POST http://localhost:9090/postSomething/1580484441998 [DefaultWebClient]
	|_ checkpoint ⇢ Handler com.thsnoopy.report.controller.Controller#trigger() [DispatcherHandler]
	|_ checkpoint ⇢ HTTP GET "/requestPost" [ExceptionHandlingWebHandler]
Stack trace:

[server-actor-2020-01-31.log](https://github.com/reactor/reactor-netty/files/4140130/server-actor-2020-01-31.log)

**Comment by softwareklinic** [comment]
The code I used is exactly the same in this REPO --- the only change I performed was to get the latest reactor netty libraries 

https://github.com/thsnoopy/reactor-netty-report/

**Comment by softwareklinic** [comment]
I will share the code snipped of what we have in production for the newconnetion etc...

**Comment by softwareklinic** [comment]
Here is the code snippet that we use to create newconnection

static class NettyDelegate implements ReactiveClientDelegate {
			
			private TcpClient tcpClient;
			
			public NettyDelegate() {
				tcpClient = TcpClient.create();
			}
			
			public NettyDelegate(String name, int maxConnections, int acquireTimeout) {
				if(maxConnections == 0) {
					tcpClient = TcpClient.create(ConnectionProvider.newConnection());
				}else {
					tcpClient = TcpClient.create(ConnectionProvider.fixed(name, maxConnections, acquireTimeout));
				}
			}
			
			public TcpClient getTcpClient() {
				return tcpClient;
			}
			
			public void setTcpClient(TcpClient tcpClient) {
				this.tcpClient = tcpClient;
			}
	
			@Override
			public ClientHttpConnector build() {
				return new ReactorClientHttpConnector(HttpClient.from(tcpClient)); 
			}
	
			@Override
			public HttpRequestFactoryMode getMode() {
				return HttpRequestFactoryMode.NETTY;
			}
		
	}

**Comment by softwareklinic** [comment]
We removed the code for elastic --- just either newconnection or fixed --- the issue is with fixed... and i need to understand whats going on under the hoods for new connection --- does it close automatically after use ... or does it keep opening new connections  each time the code is triggered... overall we have not seen any premature connection issue with new connection..

**Comment by softwareklinic** [comment]
Any updates?

**Comment by violetagg** [comment]
@softwareklinic 

I did the change below to your example and with that change I do not see issues:

```
diff --git a/client-actor/pom.xml b/client-actor/pom.xml
index 0860c5c..4b306a0 100644
--- a/client-actor/pom.xml
+++ b/client-actor/pom.xml
@@ -5,7 +5,7 @@
     <parent>
         <groupId>org.springframework.boot</groupId>
         <artifactId>spring-boot-starter-parent</artifactId>
-        <version>2.1.6.RELEASE</version>
+        <version>2.1.12.RELEASE</version>
         <relativePath/> <!-- lookup parent from repository -->
     </parent>
     <groupId>com.thsnoopy.report</groupId>
diff --git a/client-actor/src/main/java/com/thsnoopy/report/configuration/WebClientConfiguration.java b/client-actor/src/main/java/com/thsnoopy/report/configuration/WebClientConfiguration.java
index 7b7185a..67ebde4 100644
--- a/client-actor/src/main/java/com/thsnoopy/report/configuration/WebClientConfiguration.java
+++ b/client-actor/src/main/java/com/thsnoopy/report/configuration/WebClientConfiguration.java
@@ -10,9 +10,11 @@ import org.springframework.context.annotation.Configuration;
 import org.springframework.context.annotation.PropertySource;
 import org.springframework.http.client.reactive.ClientHttpConnector;
 import org.springframework.http.client.reactive.ReactorClientHttpConnector;
+import org.springframework.http.client.reactive.ReactorResourceFactory;
 import org.springframework.web.reactive.function.client.WebClient;
 import org.springframework.web.util.DefaultUriBuilderFactory;
 import reactor.netty.http.client.HttpClient;
+import reactor.netty.resources.ConnectionProvider;
 
 import static org.springframework.web.reactive.function.client.ExchangeFilterFunctions.basicAuthentication;
 
@@ -37,16 +39,17 @@ public class WebClientConfiguration {
     }
 
     private ClientHttpConnector clientHttpConnector(int connectTimeoutInMilliSecond, int readWriteTimeoutInSecond) {
-        HttpClient httpClient =
-            HttpClient.create()
-//                    .keepAlive(false);
-                    .tcpConfiguration(client ->
-                            client.option(ChannelOption.CONNECT_TIMEOUT_MILLIS, connectTimeoutInMilliSecond)
-                                    .doOnConnected(conn -> conn
-                                                .addHandlerLast(new ReadTimeoutHandler(readWriteTimeoutInSecond))
-                                                .addHandlerLast(new WriteTimeoutHandler(readWriteTimeoutInSecond))
-                                    )
-                    );
-        return new ReactorClientHttpConnector(httpClient);
+        ReactorResourceFactory factory = new ReactorResourceFactory();
+        factory.setUseGlobalResources(false);
+        factory.setConnectionProvider(ConnectionProvider.fixed("test", 500));
+        factory.afterPropertiesSet();
+        return new ReactorClientHttpConnector(factory,
+                httpClient -> httpClient.tcpConfiguration(client ->
+                        client.option(ChannelOption.CONNECT_TIMEOUT_MILLIS, connectTimeoutInMilliSecond)
+                                .doOnConnected(conn -> conn
+                                        .addHandlerLast(new ReadTimeoutHandler(readWriteTimeoutInSecond))
+                                        .addHandlerLast(new WriteTimeoutHandler(readWriteTimeoutInSecond))
+                                )
+                ));
     }
 }
diff --git a/client-actor/src/main/resources/application.yaml b/client-actor/src/main/resources/application.yaml
index bfa5f92..3c92f3b 100644
--- a/client-actor/src/main/resources/application.yaml
+++ b/client-actor/src/main/resources/application.yaml
@@ -7,7 +7,7 @@ api:
     connectTimeoutInMilliSecond: 20000
     readWriteTimeoutInSecond: 100
 
-logging:
-  level:
-    reactor:
-      netty: debug
\ No newline at end of file
+#logging:
+#  level:
+#    reactor:
+#      netty: debug
\ No newline at end of file
diff --git a/server-actor/pom.xml b/server-actor/pom.xml
index df67188..2094954 100644
--- a/server-actor/pom.xml
+++ b/server-actor/pom.xml
@@ -5,7 +5,7 @@
     <parent>
         <groupId>org.springframework.boot</groupId>
         <artifactId>spring-boot-starter-parent</artifactId>
-        <version>2.1.6.RELEASE</version>
+        <version>2.1.12.RELEASE</version>
         <relativePath/> <!-- lookup parent from repository -->
     </parent>
     <groupId>com.thsnoopy.report</groupId>
diff --git a/test-runner/pom.xml b/test-runner/pom.xml
index 604d976..3f0d6a4 100644
--- a/test-runner/pom.xml
+++ b/test-runner/pom.xml
@@ -5,7 +5,7 @@
     <parent>
         <groupId>org.springframework.boot</groupId>
         <artifactId>spring-boot-starter-parent</artifactId>
-        <version>2.1.6.RELEASE</version>
+        <version>2.1.12.RELEASE</version>
         <relativePath/> <!-- lookup parent from repository -->
     </parent>
     <groupId>com.thsnoopy</groupId>
```

**Comment by violetagg** [comment]
Closing as there is no response from the author. We can reopen it if it is needed.
