### ISSUE TITLE
Support ByteBufFormat option to LoggingHandler

### ISSUE THREAD

**Issue by violetagg** [reactor/reactor-netty#989]
In Netty 4.1.46.Final a new option is added to LoggingHandler (ByteBufFormat)
https://github.com/netty/netty/pull/9915
The idea is to have `wiretap(String, LogLevel, ByteBufFormat)`
This feature request depends on Netty version

**Comment by shahaf-sameach** [comment]
brand new contributor :) can I take this?

**Comment by violetagg** [comment]
@shahaf-sameach yes go for it. Use branch 0.9.x as a base.
