### ISSUE TITLE
opt-out of connection retry

### ISSUE THREAD

**Issue by adriancole** [reactor/reactor-netty#995]
As a part of http tracing interop, I noticed reactor-netty's HttpClient uniquely has a retry-once on connection-reset behavior, which is not possible to disable. I'd like to be able to disable this.

## Motivation
I'd like to improve the quality of trace instrumentation without disabling or special-casing the part that tests traces produced in connection error https://github.com/spring-cloud/spring-cloud-sleuth/pull/1554

## Desired solution
I'd like a way to disable the retry on connection fail.

## Considered alternatives
We could rewrite the behavior of Brave's test framework to work around this, but it seems odd especially as several new and old clients are able to control retry behavior.

## Additional context
According to @violetagg, HttpClient will retry once ONLY in cases of Connection reset by peer

https://github.com/reactor/reactor-netty/blob/master/src/main/java/reactor/netty/http/client/HttpClientConnect.java#L666

**Comment by violetagg** [comment]
@adriancole PTAL #1019
